
# LFH-aware multi-prefix stability check — Gemma2-9B-IT / AGNews

This notebook is the **coarse preliminary rebuttal version**, following the attached Gemma2-2B-IT candidate method rather than the later rank-stability/refined variants.

Experiment design:

1. Use Gemma2-9B-IT and the corresponding middle-layer residual SAE.
2. Sample AGNews test queries, label-balanced.
3. For each query, keep demonstrations 1–7 fixed and vary only demonstration 8 across eight balanced alternatives.
4. Measure query-side SAE pre/post-activations at token positions controlled by one variable only:
   ```python
   query_analysis_positions = [-2]
   ```
   Here `-1` is the final query-span token, `-2` is the second-final token, etc.
5. Select **label-specific** candidate features from the ordinary single-prefix baseline. For label `L`, the score is:
   ```text
   mean preactivation on gold-label-L query items
   - mean preactivation on all other query items
   ```
6. For each label, report the top-20 label-specific features from the baseline prefix and check whether they remain stable across final-demo variants.
7. Run the coarse causal validation: compare multi-prefix-stable versus LFH-sensitive label-feature pairs using active-feature ablation and feature-direction amplification.
8. Plot diagnostics with Plotly only.

The notebook does not read or write analysis caches. Re-running the notebook recomputes the activations from scratch.

In [1]:

# ============================================================
# 0. Imports and configuration
# ============================================================

import os
import re
import json
import math
import random
from collections import defaultdict

import numpy as np
import pandas as pd
import torch
import plotly.express as px
import plotly.graph_objects as go

from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM
from huggingface_hub import hf_hub_download
from IPython.display import display


def set_seed(seed: int):
    print("seed:", seed)
    torch.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.enabled = False
    torch.backends.cudnn.benchmark = False
    os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"
    os.environ["PYTHONHASHSEED"] = str(seed)


# -----------------------------
# User-facing experiment knobs
# -----------------------------
seed = 42
set_seed(seed)

MODEL_FAMILY = "gemma"
MODEL_NAME = "google/gemma-2-9b-it"
MODEL_SHORT_NAME = "Gemma2-9B-IT"
TARGET_LAYER = 20

# Gemma Scope 9B IT residual SAE, middle checkpoint.
SAE_BACKEND = "gemma_scope_npz"
SAE_REPO_ID = "google/gemma-scope-9b-it-res"
SAE_WIDTH = "width_16k"
SAE_AVERAGE_L0 = "average_l0_91"
SAE_FILENAME = f"layer_{TARGET_LAYER}/{SAE_WIDTH}/{SAE_AVERAGE_L0}/params.npz"

# Gemma Scope variants do not need Qwen high-residual-norm filtering.
FILTER_HIGH_NORM_TOKENS_FOR_FEATURE_EXTRACTION = False
HIGH_NORM_FILTER_MULTIPLIER = 10.0

# Multi-prefix stability experiment.
N_QUERY_TOTAL = 100              # label-balanced test queries; use smaller values for debugging
N_SHOT = 8                       # demonstrations per prefix
N_PREFIX_VARIANTS = 8            # with AGNews labels, 8 gives 2 final demos per label
FINAL_DEMO_SLOT = N_SHOT         # vary the last demonstration: Example 8

# Coarse attached-file method: top-20 baseline features and top-20 retention.
LABEL_SPECIFIC_TOP_N = 20        # top-20 features per label in the ordinary single-prefix baseline
RETENTION_TOP_K = 20             # retention is computed against the top-K label-specific ranking in each variant
STABLE_MIN_RETENTION = 0.9
STABLE_MIN_BASELINE_RATIO = 0.50

# One feature-selection token-position variable only.
# -1 is the final query-span token, -2 is the second-final token, etc.
query_analysis_positions = [-2]

# Optional local-control condition: vary an earlier demo while keeping the final demo fixed.
# This approximately doubles the number of forward passes, so it is disabled by default.
RUN_EARLIER_DEMO_CONTROL = False
EARLIER_DEMO_CONTROL_SLOT = 3

# Runtime. Gemma2-9B is larger than the attached 2B notebook, so the batch size is conservative.
DTYPE = torch.bfloat16
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
BATCH_SIZE = 2

# Optional HF token for higher rate limits / gated checkpoints.
HF_TOKEN = os.environ.get("HF_TOKEN") or os.environ.get("HUGGINGFACE_HUB_TOKEN")
HF_KWARGS = {"token": HF_TOKEN} if HF_TOKEN else {}

print("MODEL_NAME:", MODEL_NAME)
print("MODEL_SHORT_NAME:", MODEL_SHORT_NAME)
print("MODEL_FAMILY:", MODEL_FAMILY)
print("TARGET_LAYER:", TARGET_LAYER)
print("SAE_BACKEND:", SAE_BACKEND)
print("SAE_REPO_ID:", SAE_REPO_ID)
print("SAE_FILENAME:", SAE_FILENAME)
print("FILTER_HIGH_NORM_TOKENS_FOR_FEATURE_EXTRACTION:", FILTER_HIGH_NORM_TOKENS_FOR_FEATURE_EXTRACTION)
print("LABEL_SPECIFIC_TOP_N:", LABEL_SPECIFIC_TOP_N)
print("RETENTION_TOP_K:", RETENTION_TOP_K)
print("query_analysis_positions:", query_analysis_positions)
print("BATCH_SIZE:", BATCH_SIZE)
print("DEVICE:", DEVICE)

/home/ikhyuncho23/ml-env/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

seed: 42
MODEL_NAME: google/gemma-2-9b-it
MODEL_SHORT_NAME: Gemma2-9B-IT
MODEL_FAMILY: gemma
TARGET_LAYER: 20
SAE_BACKEND: gemma_scope_npz
SAE_REPO_ID: google/gemma-scope-9b-it-res
SAE_FILENAME: layer_20/width_16k/average_l0_91/params.npz
FILTER_HIGH_NORM_TOKENS_FOR_FEATURE_EXTRACTION: False
LABEL_SPECIFIC_TOP_N: 20
RETENTION_TOP_K: 20
query_analysis_positions: [-2]
BATCH_SIZE: 2
DEVICE: cuda

In [2]:
# ============================================================
# 1. Load AGNews, tokenizer, model, and SAE
# ============================================================

label_to_words_agnews = {
    0: "World",
    1: "Sports",
    2: "Business",
    3: "Technology",
}
word_to_label_agnews = {v: k for k, v in label_to_words_agnews.items()}
NUM_LABELS = len(label_to_words_agnews)


def load_agnews_splits():
    """Use the namespaced HF dataset id to avoid recent hf:// URI errors."""
    candidates = ["fancyzhx/ag_news", "ag_news"]
    errors = []
    for dataset_id in candidates:
        try:
            print(f"Loading AGNews from {dataset_id!r}...")
            return load_dataset(dataset_id, split=["train", "test"], **HF_KWARGS)
        except Exception as e:
            errors.append((dataset_id, type(e).__name__, str(e)))
            print(f"Failed to load {dataset_id!r}: {type(e).__name__}: {e}")
    raise RuntimeError("Could not load AGNews. Errors:\n" + "\n\n".join(map(str, errors)))


dataset = load_agnews_splits()
train_data_agnews = dataset[0]
test_data_agnews = dataset[1]

train_indices_by_label = defaultdict(list)
test_indices_by_label = defaultdict(list)
for i, row in enumerate(train_data_agnews):
    train_indices_by_label[int(row["label"])].append(i)
for i, row in enumerate(test_data_agnews):
    test_indices_by_label[int(row["label"])].append(i)

print("Train counts:", {label_to_words_agnews[k]: len(v) for k, v in train_indices_by_label.items()})
print("Test counts:", {label_to_words_agnews[k]: len(v) for k, v in test_indices_by_label.items()})


tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME,
    trust_remote_code=True,
    use_fast=True,
    **HF_KWARGS,
)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
# Left padding makes causal labels natural and matches the previous notebooks.
tokenizer.padding_side = "left"

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=DTYPE,
    device_map="auto" if torch.cuda.is_available() else None,
    trust_remote_code=True,
    **HF_KWARGS,
)
model.eval()


def get_model_input_device(model):
    return model.get_input_embeddings().weight.device


def get_layer_device(model, layer_idx: int):
    block = model.get_submodule(f"model.layers.{layer_idx}")
    try:
        return next(block.parameters()).device
    except StopIteration:
        return get_model_input_device(model)


MODEL_INPUT_DEVICE = get_model_input_device(model)
TARGET_LAYER_DEVICE = get_layer_device(model, TARGET_LAYER)
print("MODEL_INPUT_DEVICE:", MODEL_INPUT_DEVICE)
print("TARGET_LAYER_DEVICE:", TARGET_LAYER_DEVICE)


class GemmaScopeJumpReLUSAE(torch.nn.Module):
    """Minimal inference wrapper for Gemma Scope JumpReLU residual-stream SAEs."""

    def __init__(self, params, device=DEVICE, dtype=DTYPE):
        super().__init__()
        self.device = torch.device(device)
        self.dtype = dtype

        def get_param(name, *aliases):
            for key in (name,) + aliases:
                if key in params:
                    value = params[key]
                    if isinstance(value, np.ndarray):
                        value = torch.from_numpy(value)
                    return value.detach() if torch.is_tensor(value) else torch.tensor(value)
            raise KeyError(f"Missing SAE parameter {name!r}. Available keys: {sorted(params.keys())}")

        W_enc = get_param("W_enc")
        W_dec = get_param("W_dec")
        b_enc = get_param("b_enc")
        b_dec = get_param("b_dec")
        threshold = get_param("threshold", "thresholds")

        if W_enc.ndim != 2 or W_dec.ndim != 2:
            raise ValueError(f"Expected 2D W_enc/W_dec, got {tuple(W_enc.shape)} and {tuple(W_dec.shape)}")

        d_model = int(W_enc.shape[0])
        n_features = int(W_enc.shape[1])

        if W_dec.shape == (d_model, n_features):
            W_dec = W_dec.T.contiguous()
        if W_dec.shape != (n_features, d_model):
            raise ValueError(f"Expected W_dec shape {(n_features, d_model)}, got {tuple(W_dec.shape)}")
        if b_enc.numel() != n_features:
            raise ValueError(f"Expected b_enc length {n_features}, got {b_enc.numel()}")
        if b_dec.numel() != d_model:
            raise ValueError(f"Expected b_dec length {d_model}, got {b_dec.numel()}")
        if threshold.numel() != n_features:
            raise ValueError(f"Expected threshold length {n_features}, got {threshold.numel()}")

        self.register_buffer("W_enc", W_enc.contiguous().to(device=self.device, dtype=self.dtype))
        self.register_buffer("W_dec", W_dec.contiguous().to(device=self.device, dtype=self.dtype))
        self.register_buffer("b_enc", b_enc.reshape(-1).contiguous().to(device=self.device, dtype=self.dtype))
        self.register_buffer("b_dec", b_dec.reshape(-1).contiguous().to(device=self.device, dtype=self.dtype))
        self.register_buffer("threshold", threshold.reshape(-1).contiguous().to(device=self.device, dtype=self.dtype))

        self.k = None
        self.d_model = d_model
        self.n_features = n_features

    def process_sae_in(self, x: torch.Tensor) -> torch.Tensor:
        # Gemma Scope folds any preprocessing into the encoder parameters for these checkpoints.
        return x

    def encode_pre(self, x: torch.Tensor) -> torch.Tensor:
        x = x.to(device=self.device, dtype=self.dtype)
        return self.process_sae_in(x) @ self.W_enc + self.b_enc

    def activation_fn(self, pre: torch.Tensor) -> torch.Tensor:
        return torch.where(pre > self.threshold, torch.relu(pre), torch.zeros_like(pre))

    def encode(self, x: torch.Tensor) -> torch.Tensor:
        return self.activation_fn(self.encode_pre(x))

    def decode(self, acts: torch.Tensor) -> torch.Tensor:
        acts = acts.to(device=self.device, dtype=self.dtype)
        return acts @ self.W_dec + self.b_dec


class QwenBatchTopKSAE(torch.nn.Module):
    """
    Minimal inference wrapper for Adam Karvonen's Qwen3 BatchTopK SAEs.

    The checkpoint has dictionary_learning-style keys:
      b_dec, k, threshold, decoder.weight, encoder.weight, encoder.bias

    This wrapper exposes the same interface used by the Gemma Scope wrapper:
      W_enc, W_dec, b_enc, b_dec, threshold, encode_pre, activation_fn, encode, decode.
    """

    def __init__(self, state_dict, device=DEVICE, dtype=DTYPE):
        super().__init__()
        self.device = torch.device(device)
        self.dtype = dtype

        if isinstance(state_dict, dict) and "state_dict" in state_dict:
            state_dict = state_dict["state_dict"]
        if isinstance(state_dict, dict) and "model" in state_dict and isinstance(state_dict["model"], dict):
            state_dict = state_dict["model"]

        b_dec = state_dict["b_dec"].detach()
        b_enc = state_dict.get("encoder.bias", state_dict.get("b_enc")).detach()
        enc_w = state_dict.get("encoder.weight", state_dict.get("W_enc")).detach()
        dec_w = state_dict.get("decoder.weight", state_dict.get("W_dec")).detach()
        threshold = state_dict["threshold"]
        threshold = threshold.detach() if torch.is_tensor(threshold) else torch.tensor(threshold)
        k = state_dict.get("k", None)
        if torch.is_tensor(k):
            k = int(k.item())

        d_model = int(b_dec.numel())
        n_features = int(b_enc.numel())

        if enc_w.shape == (n_features, d_model):
            W_enc = enc_w.T.contiguous()
        elif enc_w.shape == (d_model, n_features):
            W_enc = enc_w.contiguous()
        else:
            raise ValueError(
                f"Unexpected encoder.weight shape {tuple(enc_w.shape)} "
                f"for d_model={d_model}, n_features={n_features}"
            )

        if dec_w.shape == (d_model, n_features):
            W_dec = dec_w.T.contiguous()
        elif dec_w.shape == (n_features, d_model):
            W_dec = dec_w.contiguous()
        else:
            raise ValueError(
                f"Unexpected decoder.weight shape {tuple(dec_w.shape)} "
                f"for d_model={d_model}, n_features={n_features}"
            )

        self.register_buffer("W_enc", W_enc.to(device=self.device, dtype=self.dtype))
        self.register_buffer("W_dec", W_dec.to(device=self.device, dtype=self.dtype))
        self.register_buffer("b_enc", b_enc.to(device=self.device, dtype=self.dtype))
        self.register_buffer("b_dec", b_dec.to(device=self.device, dtype=self.dtype))
        self.register_buffer("threshold", threshold.to(device=self.device, dtype=self.dtype))

        self.k = k
        self.d_model = d_model
        self.n_features = n_features

    def process_sae_in(self, x: torch.Tensor) -> torch.Tensor:
        return x - self.b_dec

    def encode_pre(self, x: torch.Tensor) -> torch.Tensor:
        x = x.to(device=self.device, dtype=self.dtype)
        return self.process_sae_in(x) @ self.W_enc + self.b_enc

    def activation_fn(self, pre: torch.Tensor) -> torch.Tensor:
        return torch.where(pre > self.threshold, pre, torch.zeros_like(pre))

    def encode(self, x: torch.Tensor) -> torch.Tensor:
        return self.activation_fn(self.encode_pre(x))

    def decode(self, acts: torch.Tensor) -> torch.Tensor:
        acts = acts.to(device=self.device, dtype=self.dtype)
        return acts @ self.W_dec + self.b_dec


def load_gemma_scope_jumprelu_sae(repo_id: str, filename: str, device=DEVICE, dtype=DTYPE):
    print("Downloading/loading Gemma Scope SAE checkpoint:", repo_id, filename)
    path = hf_hub_download(repo_id=repo_id, filename=filename, **HF_KWARGS)
    with np.load(path, allow_pickle=False) as params_np:
        params = {k: torch.from_numpy(params_np[k]) for k in params_np.files}
    sae = GemmaScopeJumpReLUSAE(params, device=device, dtype=dtype)
    print(
        f"Loaded SAE: d_model={sae.d_model}, n_features={sae.n_features}, "
        f"mean_threshold={float(sae.threshold.detach().float().mean().cpu()):.4f}"
    )
    return sae


def load_qwen_batchtopk_sae(repo_id: str, filename: str, device=DEVICE, dtype=DTYPE):
    print("Downloading/loading Qwen BatchTopK SAE checkpoint:", repo_id, filename)
    path = hf_hub_download(repo_id=repo_id, filename=filename, **HF_KWARGS)
    try:
        state = torch.load(path, map_location="cpu", weights_only=True)
    except TypeError:
        state = torch.load(path, map_location="cpu")
    sae = QwenBatchTopKSAE(state, device=device, dtype=dtype)
    print(
        f"Loaded SAE: d_model={sae.d_model}, n_features={sae.n_features}, "
        f"k={sae.k}, mean_threshold={float(sae.threshold.detach().float().mean().cpu()):.4f}"
    )
    return sae


def load_configured_sae():
    if SAE_BACKEND == "gemma_scope_npz":
        return load_gemma_scope_jumprelu_sae(
            repo_id=SAE_REPO_ID,
            filename=SAE_FILENAME,
            device=TARGET_LAYER_DEVICE,
            dtype=DTYPE,
        )
    if SAE_BACKEND == "qwen_batchtopk":
        return load_qwen_batchtopk_sae(
            repo_id=SAE_REPO_ID,
            filename=SAE_FILENAME,
            device=TARGET_LAYER_DEVICE,
            dtype=DTYPE,
        )
    raise ValueError(f"Unknown SAE_BACKEND={SAE_BACKEND!r}")


sae = load_configured_sae()
print("SAE device:", sae.device)

Loading AGNews from 'fancyzhx/ag_news'...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Train counts: {'Business': 30000, 'Technology': 30000, 'Sports': 30000, 'World': 30000}
Test counts: {'Business': 1900, 'Technology': 1900, 'Sports': 1900, 'World': 1900}

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!
Loading weights: 100%|████████████████████████████████| 464/464 [00:00<00:00, 486.39it/s]

MODEL_INPUT_DEVICE: cuda:0
TARGET_LAYER_DEVICE: cuda:0
Downloading/loading Gemma Scope SAE checkpoint: google/gemma-scope-9b-it-res layer_20/width_16k/average_l0_91/params.npz
Loaded SAE: d_model=3584, n_features=16384, mean_threshold=5.3436
SAE device: cuda:0

In [3]:

# ============================================================
# 2. Prompt sampling and rendering
# ============================================================

rng = random.Random(seed)

INSTRUCTION = """You are given news articles and their topics.
Valid topics: World, Sports, Business, Technology.
For each example, identify the correct topic."""


def balanced_label_sequence(n: int, num_labels: int = NUM_LABELS, rng: random.Random | None = None):
    """Return labels as evenly as possible, shuffled."""
    rng = rng or random
    base = n // num_labels
    rem = n % num_labels
    labels = []
    for lab in range(num_labels):
        labels.extend([lab] * base)
    extra = list(range(num_labels))
    rng.shuffle(extra)
    labels.extend(extra[:rem])
    rng.shuffle(labels)
    return labels


def sample_train_indices_for_labels(label_seq, rng: random.Random, exclude=None):
    exclude = set(exclude or [])
    chosen = []
    used = set(exclude)
    for lab in label_seq:
        pool = [idx for idx in train_indices_by_label[int(lab)] if idx not in used]
        if not pool:
            raise RuntimeError(f"No available training examples for label {lab} after exclusions.")
        idx = rng.choice(pool)
        chosen.append(idx)
        used.add(idx)
    return chosen


def sample_label_balanced_test_indices(n_total: int, rng: random.Random):
    label_seq = balanced_label_sequence(n_total, num_labels=NUM_LABELS, rng=rng)
    out = []
    used = set()
    for lab in label_seq:
        pool = [idx for idx in test_indices_by_label[int(lab)] if idx not in used]
        idx = rng.choice(pool)
        out.append(idx)
        used.add(idx)
    return out


def format_demo(demo_number: int, row) -> str:
    return (
        f"Example {demo_number}:\n"
        f"News article:\n{row['text']}\n"
        f"Topic:\n{label_to_words_agnews[int(row['label'])]}"
    )


def render_single_user_prompt(demo_rows, query_row):
    """
    Render all demonstrations and the test query inside one model-native user prompt.

    Gemma uses one <start_of_turn>user block plus the model-generation header.
    Qwen uses one system message plus one user message plus the assistant-generation header.
    In both cases, all demonstrations are in a single user prompt; individual demos are not wrapped.

    Returns:
      prompt: full model input string
      query_char_span: [start, end) character span of the query block inside prompt
    """
    if len(demo_rows) != N_SHOT:
        raise ValueError(f"Expected {N_SHOT} demos, got {len(demo_rows)}")

    demo_text = "\n\n".join(format_demo(i + 1, row) for i, row in enumerate(demo_rows))
    query_block = f"Test article:\n{query_row['text']}\nTopic:\n"

    if MODEL_FAMILY == "gemma":
        user_content = f"{INSTRUCTION}\n\n{demo_text}\n\n{query_block}"
        prompt = f"<bos><start_of_turn>user\n{user_content}<end_of_turn>\n<start_of_turn>model\n"

        # Sanity checks: one user turn, one model-generation header, all demos in the user turn.
        if prompt.count("<start_of_turn>user") != 1:
            raise AssertionError("Prompt should contain exactly one user turn.")
        if prompt.count("<start_of_turn>model") != 1:
            raise AssertionError("Prompt should contain exactly one model-generation header.")
        if prompt.count("<end_of_turn>") != 1:
            raise AssertionError("Prompt should contain exactly one user-turn terminator.")

    elif MODEL_FAMILY == "qwen":
        user_content = f"{demo_text}\n\n{query_block}"
        messages = [
            {"role": "system", "content": INSTRUCTION},
            {"role": "user", "content": user_content},
        ]
        try:
            prompt = tokenizer.apply_chat_template(
                messages,
                tokenize=False,
                add_generation_prompt=True,
                enable_thinking=False,
            )
        except TypeError:
            # Older transformers/tokenizers may not expose enable_thinking.
            # In that case, include Qwen's non-thinking directive in the system content.
            messages = [
                {"role": "system", "content": INSTRUCTION + "\n/no_think"},
                {"role": "user", "content": user_content},
            ]
            prompt = tokenizer.apply_chat_template(
                messages,
                tokenize=False,
                add_generation_prompt=True,
            )

        if prompt.count(query_block) != 1:
            raise AssertionError("Could not uniquely locate the query block in the Qwen chat-template prompt.")
    else:
        raise ValueError(f"Unknown MODEL_FAMILY={MODEL_FAMILY!r}")

    query_start = prompt.index(query_block)
    query_end = query_start + len(query_block)

    if len(re.findall(r"(?m)^Example\s+\d+:", prompt)) != N_SHOT:
        raise AssertionError(f"Prompt should contain exactly {N_SHOT} numbered demo headers.")

    return prompt, (query_start, query_end)


def build_final_demo_variant_prompts():
    """
    Build Q x V prompts using the coarse attached-file method.

    For each fixed query:
      - demos 1..7 are fixed for that query;
      - demo 8 varies across N_PREFIX_VARIANTS alternatives;
      - final-demo labels are as balanced as possible.
    """
    test_indices = sample_label_balanced_test_indices(N_QUERY_TOTAL, rng)
    prompts = []
    metadata = []

    for q_local_idx, test_idx in enumerate(test_indices):
        query_row = test_data_agnews[int(test_idx)]

        fixed_label_seq = balanced_label_sequence(N_SHOT - 1, rng=rng)
        fixed_demo_indices = sample_train_indices_for_labels(fixed_label_seq, rng=rng)

        final_label_seq = balanced_label_sequence(N_PREFIX_VARIANTS, rng=rng)
        final_demo_indices = sample_train_indices_for_labels(
            final_label_seq,
            rng=rng,
            exclude=fixed_demo_indices,
        )

        fixed_demo_rows = [train_data_agnews[int(i)] for i in fixed_demo_indices]

        for variant_idx, final_demo_idx in enumerate(final_demo_indices):
            demo_indices = list(fixed_demo_indices) + [int(final_demo_idx)]
            demo_rows = fixed_demo_rows + [train_data_agnews[int(final_demo_idx)]]
            prompt, query_char_span = render_single_user_prompt(demo_rows, query_row)
            prompts.append(prompt)
            metadata.append({
                "query_local_idx": int(q_local_idx),
                "variant_idx": int(variant_idx),
                "query_test_idx": int(test_idx),
                "query_label": int(query_row["label"]),
                "query_label_word": label_to_words_agnews[int(query_row["label"])],
                "fixed_demo_indices": [int(x) for x in fixed_demo_indices],
                "fixed_demo_labels": [int(train_data_agnews[int(x)]["label"]) for x in fixed_demo_indices],
                "final_demo_idx": int(final_demo_idx),
                "final_demo_label": int(train_data_agnews[int(final_demo_idx)]["label"]),
                "final_demo_label_word": label_to_words_agnews[int(train_data_agnews[int(final_demo_idx)]["label"])],
                "query_char_start": int(query_char_span[0]),
                "query_char_end": int(query_char_span[1]),
            })

    return prompts, metadata


prompts, prompt_metadata = build_final_demo_variant_prompts()
print(f"Built {len(prompts)} prompts = {N_QUERY_TOTAL} queries x {N_PREFIX_VARIANTS} final-demo variants.")
print("First prompt excerpt:\n")
print(prompts[0][:2000])

meta_df = pd.DataFrame(prompt_metadata)
print("\nQuery label counts:")
display(meta_df.drop_duplicates("query_local_idx")["query_label_word"].value_counts().sort_index().to_frame("count"))
print("Final-demo label counts across all variants:")
display(meta_df["final_demo_label_word"].value_counts().sort_index().to_frame("count"))

Built 800 prompts = 100 queries x 8 final-demo variants.
First prompt excerpt:

<bos><start_of_turn>user
You are given news articles and their topics.
Valid topics: World, Sports, Business, Technology.
For each example, identify the correct topic.

Example 1:
News article:
Hamm #39;s legacy should be for Olympic ideal Even though he has fled the perceived hostile atmosphere of Athens and the Olympic village for more friendly terrain in the United States, there is still time for Paul Hamm to do what #39;s right.
Topic:
Sports

Example 2:
News article:
Greenspan rejects talk of throwing dollar a lifeline ALAN GREENSPAN, Chairman of the US Federal Reserve, undercut lingering hopes of staging an operation to support the dollar at a meeting of bankers in Frankfurt yesterday
Topic:
Business

Example 3:
News article:
Google Desktop Search app lets you 'google' your Windows PC Google Inc. unveiled a desktop search application that lets users catalog and search through e-mail, files, Web histories, instant message chats and other content on their PCs.
Topic:
Technology

Example 4:
News article:
Mozambique Prepares for Elections to Replace Chissano Mozambique holds elections on Wednesday and Thursday to choose a successor to President Joaquim Chissano, who ruled for 18 years and led the southern African country to peace after a long civil war that claimed up to a million lives.
Topic:
World

Example 5:
News article:
Israel celebrates joy of first gold medal Israel has celebrated its first Olympic gold medal, saying Gal Fridman #39;s win gave pride and joy to Jewish people around the world.
Topic:
Sports

Example 6:
News article:
Nephew has Arafat medical file No evidence exists that Palestinian leader Yasser Arafat died of poisoning, his nephew says. But at a press conference in Paris, Nasser al-Quidwa did not definitely dismiss
Topic:
World

Example 7:
News article:
Automatic Data #39;s Improving Fundamentals Prudential Equity Group raised its earnings estimates for Automatic Data Processing (nyse: ADP - news - people ) after the payroll and data proc

Query label counts:

                  count
query_label_word
Business             25
Sports               25
Technology           25
World                25

Final-demo label counts across all variants:

                       count
final_demo_label_word
Business                 200
Sports                   200
Technology               200
World                    200

In [4]:

# ============================================================
# 3. Token-span helpers and model/SAE extraction
# ============================================================


def token_positions_for_char_span(prompt: str, char_start: int, char_end: int):
    """Map a prompt character span to unpadded token indices."""
    enc = tokenizer(
        prompt,
        add_special_tokens=False,
        return_offsets_mapping=True,
    )
    offsets = enc["offset_mapping"]
    positions = []
    for tok_idx, (s, e) in enumerate(offsets):
        # Skip empty special offsets if any appear.
        if e <= s:
            continue
        # Token overlaps the query span.
        if max(int(s), int(char_start)) < min(int(e), int(char_end)):
            positions.append(tok_idx)
    if not positions:
        raise RuntimeError("No token positions found for query character span.")
    return positions


def select_query_positions(all_query_positions):
    """
    Select query-span token positions using query_analysis_positions only.

    Offset semantics:
      -1 -> final query-span token
      -2 -> second-final query-span token
      -3 -> third-final query-span token
    """
    selected = []
    n = len(all_query_positions)
    for off in query_analysis_positions:
        off = int(off)
        if off >= 0:
            raise ValueError("query_analysis_positions must contain negative offsets, e.g. [-1, -2].")
        idx = n + off
        if idx < 0 or idx >= n:
            raise IndexError(f"Offset {off} is out of range for query span with {n} tokens.")
        selected.append(all_query_positions[idx])
    return selected


# Precompute selected unpadded token positions for every prompt.
for meta, prompt in zip(prompt_metadata, prompts):
    all_positions = token_positions_for_char_span(
        prompt=prompt,
        char_start=meta["query_char_start"],
        char_end=meta["query_char_end"],
    )
    meta["all_query_token_positions"] = [int(x) for x in all_positions]
    meta["selected_query_token_positions"] = [int(x) for x in select_query_positions(all_positions)]
    meta["num_query_tokens"] = int(len(all_positions))
    meta["num_selected_query_tokens"] = int(len(meta["selected_query_token_positions"]))

print("Selected query-token counts:")
display(pd.Series([m["num_selected_query_tokens"] for m in prompt_metadata]).describe().to_frame("selected_query_tokens"))
print("Example selected offsets:", query_analysis_positions)
print("First prompt selected unpadded token positions:", prompt_metadata[0]["selected_query_token_positions"])


def clear_all_hooks(model: torch.nn.Module):
    for module in model.modules():
        module._forward_hooks.clear()
        module._forward_pre_hooks.clear()
        module._backward_hooks.clear()


@torch.no_grad()
def get_layer_output(model, input_ids, attention_mask, layer_idx: int):
    """Run a forward pass and capture model.layers[layer_idx] output, shape [B, S, D]."""
    captured = {}

    def hook_fn(module, inputs, output):
        captured["x"] = output[0].detach() if isinstance(output, tuple) else output.detach()
        return output

    block = model.get_submodule(f"model.layers.{layer_idx}")
    handle = block.register_forward_hook(hook_fn)
    try:
        _ = model(input_ids=input_ids, attention_mask=attention_mask, use_cache=False)
    finally:
        handle.remove()

    if "x" not in captured:
        raise RuntimeError(f"Failed to capture output from layer {layer_idx}")
    return captured["x"]



@torch.no_grad()
def sae_encode_pre_for_positions(hidden_row: torch.Tensor, selected_positions):
    """
    Encode SAE preactivations for selected positions from one prompt's hidden states.

    For Qwen BatchTopK SAEs, optionally zero out high-residual-norm tokens using the
    same median-norm rule used in the Qwen SAE release. Gemma variants keep this off.
    """
    positions = [int(p) for p in selected_positions]
    x = hidden_row[positions, :]
    pre = sae.encode_pre(x).float()

    if FILTER_HIGH_NORM_TOKENS_FOR_FEATURE_EXTRACTION:
        norms = hidden_row.detach().float().norm(dim=-1)
        median_norm = norms.median().clamp_min(1e-6)
        high_norm_mask = norms[positions] > (HIGH_NORM_FILTER_MULTIPLIER * median_norm)
        if bool(high_norm_mask.any().item()):
            pre = pre.clone()
            pre[high_norm_mask.to(pre.device)] = 0.0

    return pre




def apply_optional_high_norm_filter_to_pre(x: torch.Tensor, pre: torch.Tensor) -> torch.Tensor:
    """
    Optionally zero SAE preactivations for abnormally high-residual-norm tokens.

    This is enabled for Qwen BatchTopK SAEs and disabled for Gemma Scope SAEs.
    """
    if not FILTER_HIGH_NORM_TOKENS_FOR_FEATURE_EXTRACTION:
        return pre
    if x.ndim < 2:
        return pre
    norms = x.detach().float().norm(dim=-1)
    median_norm = norms.median().clamp_min(1e-6)
    high_norm_mask = norms > (HIGH_NORM_FILTER_MULTIPLIER * median_norm)
    if high_norm_mask.any():
        pre = pre.masked_fill(high_norm_mask.to(pre.device)[..., None], 0.0)
    return pre

@torch.no_grad()
def collect_query_feature_stats_for_prompts(prompts, metadata):
    """
    Return per-prompt query-side feature statistics:
      pre_by_prompt:  [P, F] mean SAE pre-activation over selected query tokens
      post_by_prompt: [P, F] mean SAE post-activation over selected query tokens
      freq_by_prompt: [P, F] fraction of selected query tokens with post-activation > 0
    """

    n_prompts = len(prompts)
    n_features = int(sae.n_features)
    pre_by_prompt = np.zeros((n_prompts, n_features), dtype=np.float32)
    post_by_prompt = np.zeros((n_prompts, n_features), dtype=np.float32)
    freq_by_prompt = np.zeros((n_prompts, n_features), dtype=np.float32)

    model_device = get_model_input_device(model)
    model.eval()
    sae.eval()

    for start in range(0, n_prompts, BATCH_SIZE):
        end = min(start + BATCH_SIZE, n_prompts)
        batch_prompts = prompts[start:end]
        batch_meta = metadata[start:end]

        enc = tokenizer(
            batch_prompts,
            padding=True,
            return_tensors="pt",
            add_special_tokens=False,
        )
        input_ids = enc["input_ids"].to(model_device)
        attention_mask = enc["attention_mask"].to(model_device)

        hidden = get_layer_output(model, input_ids, attention_mask, TARGET_LAYER)  # [B, S, D]
        batch_seq_len = int(input_ids.shape[1])

        for b, meta in enumerate(batch_meta):
            unpadded_len = int(attention_mask[b].sum().item())
            pad_shift = batch_seq_len - unpadded_len
            selected_positions = [pad_shift + int(pos) for pos in meta["selected_query_token_positions"]]
            selected_positions = [pos for pos in selected_positions if 0 <= pos < batch_seq_len]
            if not selected_positions:
                raise RuntimeError(f"No valid selected token positions for prompt index {start + b}.")

            pre = sae_encode_pre_for_positions(hidden[b], selected_positions)
            post = sae.activation_fn(pre.to(dtype=sae.dtype)).float()

            pre_by_prompt[start + b] = pre.mean(dim=0).detach().cpu().numpy()
            post_by_prompt[start + b] = post.mean(dim=0).detach().cpu().numpy()
            freq_by_prompt[start + b] = (post > 0).float().mean(dim=0).detach().cpu().numpy()

        del hidden, input_ids, attention_mask, enc

        print(f"Processed prompts {end}/{n_prompts}")

    return pre_by_prompt, post_by_prompt, freq_by_prompt, metadata

Selected query-token counts:

       selected_query_tokens
count                  800.0
mean                     1.0
std                      0.0
min                      1.0
25%                      1.0
50%                      1.0
75%                      1.0
max                      1.0

Example selected offsets: [-2]
First prompt selected unpadded token positions: [577]

In [5]:

# ============================================================
# 4. Run final-demo-variant extraction
# ============================================================

pre_by_prompt, post_by_prompt, freq_by_prompt, prompt_metadata_loaded = collect_query_feature_stats_for_prompts(
    prompts=prompts,
    metadata=prompt_metadata,
)

# Reshape from [Q*V, F] to [Q, V, F]. Prompts were built query-major, then variant-major.
n_features = pre_by_prompt.shape[-1]
pre_by_query_variant = pre_by_prompt.reshape(N_QUERY_TOTAL, N_PREFIX_VARIANTS, n_features)
post_by_query_variant = post_by_prompt.reshape(N_QUERY_TOTAL, N_PREFIX_VARIANTS, n_features)
freq_by_query_variant = freq_by_prompt.reshape(N_QUERY_TOTAL, N_PREFIX_VARIANTS, n_features)

print("pre_by_query_variant:", pre_by_query_variant.shape)
print("post_by_query_variant:", post_by_query_variant.shape)
print("freq_by_query_variant:", freq_by_query_variant.shape)

Processed prompts 2/800
Processed prompts 4/800
Processed prompts 6/800
Processed prompts 8/800
Processed prompts 10/800
Processed prompts 12/800
Processed prompts 14/800
Processed prompts 16/800
Processed prompts 18/800
Processed prompts 20/800
Processed prompts 22/800
Processed prompts 24/800
Processed prompts 26/800
Processed prompts 28/800
Processed prompts 30/800
Processed prompts 32/800
Processed prompts 34/800
Processed prompts 36/800
Processed prompts 38/800
Processed prompts 40/800
Processed prompts 42/800
Processed prompts 44/800
Processed prompts 46/800
Processed prompts 48/800
Processed prompts 50/800
Processed prompts 52/800
Processed prompts 54/800
Processed prompts 56/800
Processed prompts 58/800
Processed prompts 60/800
Processed prompts 62/800
Processed prompts 64/800
Processed prompts 66/800
Processed prompts 68/800
Processed prompts 70/800
Processed prompts 72/800
Processed prompts 74/800
Processed prompts 76/800
Processed prompts 78/800
Processed prompts 80/800
Processed prompts 82/800
Processed prompts 84/800
Processed prompts 86/800
Processed prompts 88/800
Processed prompts 90/800
Processed prompts 92/800
Processed prompts 94/800
Processed prompts 96/800
Processed prompts 98/800
Processed prompts 100/800
Processed prompts 102/800
Processed prompts 104/800
Processed prompts 106/800
Processed prompts 108/800
Processed prompts 110/800
Processed prompts 112/800
Processed prompts 114/800
Processed prompts 116/800
Processed prompts 118/800
Processed prompts 120/800
Processed prompts 122/800
Processed prompts 124/800
Processed prompts 126/800
Processed prompts 128/800
Processed prompts 130/800
Processed prompts 132/800
Processed prompts 134/800
Processed prompts 136/800
Processed prompts 138/800
Processed prompts 140/800
Processed prompts 142/800
Processed prompts 144/800
Processed prompts 146/800
Processed prompts 148/800
Processed prompts 150/800
Processed prompts 152/800
Processed prompts 154/800
Processed prompts 156/800
Processed prompts 158/800
Processed prompts 160/800
Processed prompts 162/800
Processed prompts 164/800
Processed prompts 166/800
Processed prompts 168/800
Processed prompts 170/800
Processed prompts 172/800
Processed prompts 174/800
Processed prompts 176/800
Processed prompts 178/800
Processed prompts 180/800
Processed prompts 182/800
Processed prompts 184/800
Processed prompts 186/800
Processed prompts 188/800
Processed prompts 190/800
Processed prompts 192/800
Processed prompts 194/800
Processed prompts 196/800
Processed prompts 198/800
Processed prompts 200/800
Processed prompts 202/800
Processed prompts 204/800
Processed prompts 206/800
Processed prompts 208/800
Processed prompts 210/800
Processed prompts 212/800
Processed prompts 214/800
Processed prompts 216/800
Processed prompts 218/800
Processed prompts 220/800
Processed prompts 222/800
Processed prompts 224/800
Processed prompts 226/800
Processed prompts 228/800
Processed prompts 230/800
Processed prompts 232/800
Processed prompts 234/800
Processed prompts 236/800
Processed prompts 238/800
Processed prompts 240/800
Processed prompts 242/800
Processed prompts 244/800
Processed prompts 246/800
Processed prompts 248/800
Processed prompts 250/800
Processed prompts 252/800
Processed prompts 254/800
Processed prompts 256/800
Processed prompts 258/800
Processed prompts 260/800
Processed prompts 262/800
Processed prompts 264/800
Processed prompts 266/800
Processed prompts 268/800
Processed prompts 270/800
Processed prompts 272/800
Processed prompts 274/800
Processed prompts 276/800
Processed prompts 278/800
Processed prompts 280/800
Processed prompts 282/800
Processed prompts 284/800
Processed prompts 286/800
Processed prompts 288/800
Processed prompts 290/800
Processed prompts 292/800
Processed prompts 294/800
Processed prompts 296/800
Processed prompts 298/800
Processed prompts 300/800
Processed prompts 302/800
Processed prompts 304/800
Processed prompts 306/800
Processed prompts 308/800
Processed prompts 310/800
Processed prompts 312/800
Processed prompts 314/800
Processed prompts 316/800
Processed prompts 318/800
Processed prompts 320/800
Processed prompts 322/800
Processed prompts 324/800
Processed prompts 326/800
Processed prompts 328/800
Processed prompts 330/800
Processed prompts 332/800
Processed prompts 334/800
Processed prompts 336/800
Processed prompts 338/800
Processed prompts 340/800
Processed prompts 342/800
Processed prompts 344/800
Processed prompts 346/800
Processed prompts 348/800
Processed prompts 350/800
Processed prompts 352/800
Processed prompts 354/800
Processed prompts 356/800
Processed prompts 358/800
Processed prompts 360/800
Processed prompts 362/800
Processed prompts 364/800
Processed prompts 366/800
Processed prompts 368/800
Processed prompts 370/800
Processed prompts 372/800
Processed prompts 374/800
Processed prompts 376/800
Processed prompts 378/800
Processed prompts 380/800
Processed prompts 382/800
Processed prompts 384/800
Processed prompts 386/800
Processed prompts 388/800
Processed prompts 390/800
Processed prompts 392/800
Processed prompts 394/800
Processed prompts 396/800
Processed prompts 398/800
Processed prompts 400/800
Processed prompts 402/800
Processed prompts 404/800
Processed prompts 406/800
Processed prompts 408/800
Processed prompts 410/800
Processed prompts 412/800
Processed prompts 414/800
Processed prompts 416/800
Processed prompts 418/800
Processed prompts 420/800
Processed prompts 422/800
Processed prompts 424/800
Processed prompts 426/800
Processed prompts 428/800
Processed prompts 430/800
Processed prompts 432/800
Processed prompts 434/800
Processed prompts 436/800
Processed prompts 438/800
Processed prompts 440/800
Processed prompts 442/800
Processed prompts 444/800
Processed prompts 446/800
Processed prompts 448/800
Processed prompts 450/800
Processed prompts 452/800
Processed prompts 454/800
Processed prompts 456/800
Processed prompts 458/800
Processed prompts 460/800
Processed prompts 462/800
Processed prompts 464/800
Processed prompts 466/800
Processed prompts 468/800
Processed prompts 470/800
Processed prompts 472/800
Processed prompts 474/800
Processed prompts 476/800
Processed prompts 478/800
Processed prompts 480/800
Processed prompts 482/800
Processed prompts 484/800
Processed prompts 486/800
Processed prompts 488/800
Processed prompts 490/800
Processed prompts 492/800
Processed prompts 494/800
Processed prompts 496/800
Processed prompts 498/800
Processed prompts 500/800
Processed prompts 502/800
Processed prompts 504/800
Processed prompts 506/800
Processed prompts 508/800
Processed prompts 510/800
Processed prompts 512/800
Processed prompts 514/800
Processed prompts 516/800
Processed prompts 518/800
Processed prompts 520/800
Processed prompts 522/800
Processed prompts 524/800
Processed prompts 526/800
Processed prompts 528/800
Processed prompts 530/800
Processed prompts 532/800
Processed prompts 534/800
Processed prompts 536/800
Processed prompts 538/800
Processed prompts 540/800
Processed prompts 542/800
Processed prompts 544/800
Processed prompts 546/800
Processed prompts 548/800
Processed prompts 550/800
Processed prompts 552/800
Processed prompts 554/800
Processed prompts 556/800
Processed prompts 558/800
Processed prompts 560/800
Processed prompts 562/800
Processed prompts 564/800
Processed prompts 566/800
Processed prompts 568/800
Processed prompts 570/800
Processed prompts 572/800
Processed prompts 574/800
Processed prompts 576/800
Processed prompts 578/800
Processed prompts 580/800
Processed prompts 582/800
Processed prompts 584/800
Processed prompts 586/800
Processed prompts 588/800
Processed prompts 590/800
Processed prompts 592/800
Processed prompts 594/800
Processed prompts 596/800
Processed prompts 598/800
Processed prompts 600/800
Processed prompts 602/800
Processed prompts 604/800
Processed prompts 606/800
Processed prompts 608/800
Processed prompts 610/800
Processed prompts 612/800
Processed prompts 614/800
Processed prompts 616/800
Processed prompts 618/800
Processed prompts 620/800
Processed prompts 622/800
Processed prompts 624/800
Processed prompts 626/800
Processed prompts 628/800
Processed prompts 630/800
Processed prompts 632/800
Processed prompts 634/800
Processed prompts 636/800

Processed prompts 638/800
Processed prompts 640/800
Processed prompts 642/800
Processed prompts 644/800
Processed prompts 646/800
Processed prompts 648/800
Processed prompts 650/800
Processed prompts 652/800
Processed prompts 654/800
Processed prompts 656/800
Processed prompts 658/800
Processed prompts 660/800
Processed prompts 662/800
Processed prompts 664/800
Processed prompts 666/800
Processed prompts 668/800
Processed prompts 670/800
Processed prompts 672/800
Processed prompts 674/800
Processed prompts 676/800
Processed prompts 678/800
Processed prompts 680/800
Processed prompts 682/800
Processed prompts 684/800
Processed prompts 686/800
Processed prompts 688/800
Processed prompts 690/800
Processed prompts 692/800
Processed prompts 694/800
Processed prompts 696/800
Processed prompts 698/800
Processed prompts 700/800
Processed prompts 702/800
Processed prompts 704/800
Processed prompts 706/800
Processed prompts 708/800
Processed prompts 710/800
Processed prompts 712/800
Processed prompts 714/800
Processed prompts 716/800
Processed prompts 718/800
Processed prompts 720/800
Processed prompts 722/800
Processed prompts 724/800
Processed prompts 726/800
Processed prompts 728/800
Processed prompts 730/800
Processed prompts 732/800
Processed prompts 734/800
Processed prompts 736/800
Processed prompts 738/800
Processed prompts 740/800
Processed prompts 742/800
Processed prompts 744/800
Processed prompts 746/800
Processed prompts 748/800
Processed prompts 750/800
Processed prompts 752/800
Processed prompts 754/800
Processed prompts 756/800
Processed prompts 758/800
Processed prompts 760/800
Processed prompts 762/800
Processed prompts 764/800
Processed prompts 766/800
Processed prompts 768/800
Processed prompts 770/800
Processed prompts 772/800
Processed prompts 774/800
Processed prompts 776/800
Processed prompts 778/800
Processed prompts 780/800
Processed prompts 782/800
Processed prompts 784/800
Processed prompts 786/800
Processed prompts 788/800
Processed prompts 790/800
Processed prompts 792/800
Processed prompts 794/800
Processed prompts 796/800
Processed prompts 798/800
Processed prompts 800/800
pre_by_query_variant: (100, 8, 16384)
post_by_query_variant: (100, 8, 16384)
freq_by_query_variant: (100, 8, 16384)

In [6]:

# ============================================================
# 5. Label-specific feature selection and multi-prefix stability
# ============================================================

# Query labels in the same query-major order used by pre_by_query_variant/post_by_query_variant.
query_meta_df = meta_df.drop_duplicates("query_local_idx").sort_values("query_local_idx").reset_index(drop=True)
query_labels = query_meta_df["query_label"].to_numpy(dtype=np.int64)
if len(query_labels) != N_QUERY_TOTAL:
    raise AssertionError(f"Expected {N_QUERY_TOTAL} query labels, got {len(query_labels)}")

print("Query label counts used for label-specific scoring:")
display(pd.Series(query_labels).map(label_to_words_agnews).value_counts().sort_index().to_frame("count"))


def label_vs_other_means(arr_qvf: np.ndarray, labels: np.ndarray):
    """
    Compute label-vs-other means for arrays shaped [Q, V, F].

    Returns:
      label_mean: [L, V, F]
      other_mean: [L, V, F]
    """
    if arr_qvf.shape[0] != labels.shape[0]:
        raise ValueError(f"arr_qvf has {arr_qvf.shape[0]} queries but labels has {labels.shape[0]}")
    label_mean = np.zeros((NUM_LABELS, arr_qvf.shape[1], arr_qvf.shape[2]), dtype=np.float32)
    other_mean = np.zeros_like(label_mean)
    for lab in range(NUM_LABELS):
        mask = labels == lab
        other = ~mask
        if mask.sum() == 0 or other.sum() == 0:
            raise RuntimeError(f"Need at least one label-{lab} and one non-label-{lab} query.")
        label_mean[lab] = arr_qvf[mask].mean(axis=0)
        other_mean[lab] = arr_qvf[other].mean(axis=0)
    return label_mean, other_mean


# Label-specific score requested by the user:
#   average preactivation on label L - average preactivation on all other labels.
label_mean_pre, other_mean_pre = label_vs_other_means(pre_by_query_variant, query_labels)
label_mean_post, other_mean_post = label_vs_other_means(post_by_query_variant, query_labels)
label_mean_freq, other_mean_freq = label_vs_other_means(freq_by_query_variant, query_labels)
label_specific_pre_gap = label_mean_pre - other_mean_pre  # [label, variant, feature]

# Rank every feature by label-specific preactivation gap within each label and prefix variant.
label_variant_ranks = np.empty_like(label_specific_pre_gap, dtype=np.int32)  # [L, V, F]
for lab in range(NUM_LABELS):
    for v in range(N_PREFIX_VARIANTS):
        order = np.argsort(-label_specific_pre_gap[lab, v])
        ranks_v = np.empty(n_features, dtype=np.int32)
        ranks_v[order] = np.arange(1, n_features + 1, dtype=np.int32)
        label_variant_ranks[lab, v] = ranks_v


def summarize_label_specific_feature(lab: int, feat: int, rank: int):
    scores_v = label_specific_pre_gap[lab, :, feat]
    ranks_v = label_variant_ranks[lab, :, feat]
    baseline = float(scores_v[0])
    mean_score = float(scores_v.mean())
    std_score = float(scores_v.std(ddof=0))
    min_score = float(scores_v.min())
    max_score = float(scores_v.max())
    score_range = float(max_score - min_score)
    eps = 1e-12

    if baseline > eps:
        min_over_baseline = float(min_score / baseline)
        mean_over_baseline = float(mean_score / baseline)
    else:
        min_over_baseline = np.nan
        mean_over_baseline = np.nan

    retention_rate = float((ranks_v <= RETENTION_TOP_K).mean())
    stable = bool(
        (retention_rate >= STABLE_MIN_RETENTION)
        and np.isfinite(min_over_baseline)
        and (min_over_baseline >= STABLE_MIN_BASELINE_RATIO)
    )

    return {
        "label": int(lab),
        "label_word": label_to_words_agnews[int(lab)],
        "label_specific_rank": int(rank),
        "feature_idx": int(feat),
        "baseline_label_specific_pre_gap": baseline,
        "mean_label_specific_pre_gap_across_prefixes": mean_score,
        "std_label_specific_pre_gap_across_prefixes": std_score,
        "min_label_specific_pre_gap_across_prefixes": min_score,
        "max_label_specific_pre_gap_across_prefixes": max_score,
        "range_label_specific_pre_gap_across_prefixes": score_range,
        "mean_over_baseline": mean_over_baseline,
        "min_over_baseline": min_over_baseline,
        f"retention_rate_top_{RETENTION_TOP_K}": retention_rate,
        "worst_variant_rank": int(ranks_v.max()),
        "best_variant_rank": int(ranks_v.min()),
        "stable_by_rule": stable,
        "baseline_mean_pre_label": float(label_mean_pre[lab, 0, feat]),
        "baseline_mean_pre_other": float(other_mean_pre[lab, 0, feat]),
        "baseline_mean_post_label": float(label_mean_post[lab, 0, feat]),
        "baseline_mean_post_other": float(other_mean_post[lab, 0, feat]),
        "baseline_activation_frequency_label": float(label_mean_freq[lab, 0, feat]),
        "baseline_activation_frequency_other": float(other_mean_freq[lab, 0, feat]),
        "mean_pre_label_across_prefixes": float(label_mean_pre[lab, :, feat].mean()),
        "mean_pre_other_across_prefixes": float(other_mean_pre[lab, :, feat].mean()),
        "mean_post_label_across_prefixes": float(label_mean_post[lab, :, feat].mean()),
        "mean_post_other_across_prefixes": float(other_mean_post[lab, :, feat].mean()),
        "activation_frequency_label_across_prefixes": float(label_mean_freq[lab, :, feat].mean()),
        "activation_frequency_other_across_prefixes": float(other_mean_freq[lab, :, feat].mean()),
    }


label_top_features = {}
rows = []
for lab in range(NUM_LABELS):
    baseline_scores = label_specific_pre_gap[lab, 0]  # ordinary single-prefix setting, variant 0
    order = np.argsort(-baseline_scores)
    top_feats = [int(x) for x in order[:LABEL_SPECIFIC_TOP_N]]
    label_top_features[lab] = top_feats
    for rank, feat in enumerate(top_feats, start=1):
        rows.append(summarize_label_specific_feature(lab=lab, feat=feat, rank=rank))

label_specific_stability_df = pd.DataFrame(rows)
label_specific_stability_df = label_specific_stability_df.sort_values(
    by=["label", "label_specific_rank"],
    ascending=[True, True],
).reset_index(drop=True)

lfh_sensitive_label_specific_df = label_specific_stability_df[~label_specific_stability_df["stable_by_rule"]].sort_values(
    by=["label", "label_specific_rank"],
    ascending=[True, True],
).reset_index(drop=True)

print(f"Top-{LABEL_SPECIFIC_TOP_N} label-specific features per label, selected by baseline preactivation gap.")
display(label_specific_stability_df)

print("\nOriginally top-ranked label-specific features flagged as LFH-sensitive by the simple multi-prefix rule:")
display(lfh_sensitive_label_specific_df)

print("\nPer-label tables:")
for lab in range(NUM_LABELS):
    label_word = label_to_words_agnews[lab]
    print("=" * 100)
    print(f"{label_word}: top-{LABEL_SPECIFIC_TOP_N} label-specific features")
    display(label_specific_stability_df[label_specific_stability_df["label"] == lab].reset_index(drop=True))

# Union of all top label-specific features, useful for optional controls.
candidate_label_feature_pairs = [
    (int(row["label"]), int(row["feature_idx"]))
    for _, row in label_specific_stability_df.iterrows()
]
candidate_feature_ids = sorted({feat for _, feat in candidate_label_feature_pairs})
print(f"Union of selected features across labels: {len(candidate_feature_ids)} unique features.")

Query label counts used for label-specific scoring:

            count
Business       25
Sports         25
Technology     25
World          25

Top-20 label-specific features per label, selected by baseline preactivation gap.

,label,label_word,label_specific_rank,feature_idx,baseline_label_specific_pre_gap,mean_label_specific_pre_gap_across_prefixes,std_label_specific_pre_gap_across_prefixes,min_label_specific_pre_gap_across_prefixes,max_label_specific_pre_gap_across_prefixes,range_label_specific_pre_gap_across_prefixes,...,baseline_mean_post_label,baseline_mean_post_other,baseline_activation_frequency_label,baseline_activation_frequency_other,mean_pre_label_across_prefixes,mean_pre_other_across_prefixes,mean_post_label_across_prefixes,mean_post_other_across_prefixes,activation_frequency_label_across_prefixes,activation_frequency_other_across_prefixes
0,0,World,1,13844,22.572865,21.723679,1.048429,19.794817,23.019375,3.224558,...,8.417500,0.925417,0.60,0.080000,5.061728,-16.661951,7.690000,0.863125,0.535,0.071667
1,0,World,2,3994,17.208542,18.228321,0.666845,17.208542,19.366875,2.158333,...,22.834999,8.120417,1.00,0.520000,23.457188,5.228868,23.387655,8.265417,0.985,0.526667
2,0,World,3,14744,17.116394,17.072041,0.482776,16.062317,17.796955,1.734638,...,26.072500,11.304584,1.00,0.640000,25.730000,8.657959,25.704063,11.171249,0.995,0.650000
3,0,World,4,3163,10.695886,10.434789,0.271945,9.915703,10.813854,0.898151,...,13.188750,1.786250,1.00,0.186667,12.976680,2.541891,12.789531,2.100781,0.955,0.248333
4,0,World,5,5222,9.152500,9.738646,0.434983,9.058959,10.305521,1.246562,...,2.136250,0.539583,0.24,0.053333,1.513203,-8.225443,2.016094,0.576406,0.225,0.065000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,3,Technology,16,7281,4.958855,4.098086,0.734436,2.895782,4.958855,2.063073,...,8.957500,4.635833,0.72,0.373333,8.722950,4.624863,8.547501,5.033438,0.700,0.416667
76,3,Technology,17,12559,4.935482,4.577303,0.258178,4.067435,4.935482,0.868047,...,3.100000,0.405417,0.44,0.053333,3.469800,-1.107503,2.443750,0.572135,0.335,0.073333
77,3,Technology,18,7152,4.660000,4.016875,0.475936,3.059999,4.660000,1.600000,...,0.000000,0.000000,0.00,0.000000,-26.318750,-30.335625,0.000000,0.000000,0.000,0.000000
78,3,Technology,19,12592,4.537498,4.100625,0.394584,3.491667,4.537498,1.045832,...,0.000000,0.000000,0.00,0.000000,-21.790939,-25.891563,0.000000,0.000000,0.000,0.000000
79,3,Technology,20,6880,4.260000,3.815834,0.423438,3.134998,4.310417,1.175419,...,30.900000,26.617500,1.00,0.986667,30.310314,26.494480,30.310314,26.472500,1.000,0.985000

Originally top-ranked label-specific features flagged as LFH-sensitive by the simple multi-prefix rule:

,label,label_word,label_specific_rank,feature_idx,baseline_label_specific_pre_gap,mean_label_specific_pre_gap_across_prefixes,std_label_specific_pre_gap_across_prefixes,min_label_specific_pre_gap_across_prefixes,max_label_specific_pre_gap_across_prefixes,range_label_specific_pre_gap_across_prefixes,...,baseline_mean_post_label,baseline_mean_post_other,baseline_activation_frequency_label,baseline_activation_frequency_other,mean_pre_label_across_prefixes,mean_pre_other_across_prefixes,mean_post_label_across_prefixes,mean_post_other_across_prefixes,activation_frequency_label_across_prefixes,activation_frequency_other_across_prefixes
0,0,World,11,1295,6.906670,6.035001,1.135353,3.399994,7.333336,3.933342,...,87.440002,80.533333,1.00,1.000000,86.085007,80.050003,86.085007,80.051666,1.000,0.998333
1,0,World,12,6211,6.290755,5.423099,0.615843,4.495000,6.435468,1.940468,...,10.587500,3.507917,0.80,0.346667,10.365703,4.942604,9.496876,3.648177,0.760,0.380000
2,0,World,16,8386,5.642500,5.291221,0.395903,4.616563,5.877135,1.260572,...,5.203750,1.525000,0.60,0.186667,5.737158,0.445937,4.579375,1.392240,0.530,0.173333
3,0,World,17,3648,5.611178,5.076105,0.286442,4.753691,5.611178,0.857487,...,3.851250,0.000000,0.48,0.000000,4.945849,-0.130256,3.257812,0.029635,0.420,0.005000
4,0,World,18,2221,5.330026,5.019306,0.347828,4.443151,5.584323,1.141172,...,0.591250,0.000000,0.08,0.000000,0.812930,-4.206377,0.623594,0.000000,0.090,0.000000
5,1,Sports,17,11476,5.504167,5.121387,0.420500,4.522760,5.934427,1.411667,...,0.693750,0.278333,0.08,0.026667,0.619043,-4.502344,1.203437,0.137812,0.145,0.015000
6,1,Sports,18,7502,5.475469,4.457223,0.708568,3.391198,5.475469,2.084271,...,0.255000,0.000000,0.04,0.000000,-4.133349,-8.590573,0.290469,0.000000,0.040,0.000000
7,1,Sports,19,2572,5.453331,4.900416,0.795629,3.396667,6.093334,2.696667,...,0.000000,0.000000,0.00,0.000000,-57.055000,-61.955414,0.000000,0.000000,0.000,0.000000
8,1,Sports,20,14255,5.294167,4.996667,0.247574,4.716667,5.406666,0.689999,...,0.000000,0.000000,0.00,0.000000,-18.322811,-23.319479,0.000000,0.000000,0.000,0.000000
9,2,Business,18,9009,3.850625,3.340475,0.447017,2.765781,4.054375,1.288594,...,0.320000,0.000000,0.04,0.000000,-2.235942,-5.576417,0.134531,0.014062,0.020,0.001667
10,2,Business,19,44,3.568620,3.480794,0.372420,2.956771,4.001849,1.045078,...,4.353750,0.839167,0.48,0.106667,4.296474,0.815680,3.933438,0.698021,0.470,0.095000
11,2,Business,20,8551,3.481354,3.930846,0.727305,2.922917,5.050208,2.127291,...,3.977500,2.336667,0.36,0.213333,1.818438,-2.112409,4.408594,2.390156,0.395,0.238333
12,3,Technology,12,8551,6.235520,5.040794,0.609251,3.899896,6.235520,2.335625,...,4.920000,2.022500,0.44,0.186667,2.650898,-2.389896,4.617031,2.320677,0.450,0.220000
13,3,Technology,15,5131,5.481668,4.733750,0.433373,4.176666,5.481668,1.305002,...,0.000000,0.000000,0.00,0.000000,-29.993126,-34.726875,0.000000,0.000000,0.000,0.000000
14,3,Technology,16,7281,4.958855,4.098086,0.734436,2.895782,4.958855,2.063073,...,8.957500,4.635833,0.72,0.373333,8.722950,4.624863,8.547501,5.033438,0.700,0.416667
15,3,Technology,17,12559,4.935482,4.577303,0.258178,4.067435,4.935482,0.868047,...,3.100000,0.405417,0.44,0.053333,3.469800,-1.107503,2.443750,0.572135,0.335,0.073333
16,3,Technology,18,7152,4.660000,4.016875,0.475936,3.059999,4.660000,1.600000,...,0.000000,0.000000,0.00,0.000000,-26.318750,-30.335625,0.000000,0.000000,0.000,0.000000
17,3,Technology,19,12592,4.537498,4.100625,0.394584,3.491667,4.537498,1.045832,...,0.000000,0.000000,0.00,0.000000,-21.790939,-25.891563,0.000000,0.000000,0.000,0.000000
18,3,Technology,20,6880,4.260000,3.815834,0.423438,3.134998,4.310417,1.175419,...,30.900000,26.617500,1.00,0.986667,30.310314,26.494480,30.310314,26.472500,1.000,0.985000

Per-label tables:
====================================================================================================
World: top-20 label-specific features

,label,label_word,label_specific_rank,feature_idx,baseline_label_specific_pre_gap,mean_label_specific_pre_gap_across_prefixes,std_label_specific_pre_gap_across_prefixes,min_label_specific_pre_gap_across_prefixes,max_label_specific_pre_gap_across_prefixes,range_label_specific_pre_gap_across_prefixes,...,baseline_mean_post_label,baseline_mean_post_other,baseline_activation_frequency_label,baseline_activation_frequency_other,mean_pre_label_across_prefixes,mean_pre_other_across_prefixes,mean_post_label_across_prefixes,mean_post_other_across_prefixes,activation_frequency_label_across_prefixes,activation_frequency_other_across_prefixes
0,0,World,1,13844,22.572865,21.723679,1.048429,19.794817,23.019375,3.224558,...,8.417500,0.925417,0.60,0.080000,5.061728,-16.661951,7.690000,0.863125,0.535,0.071667
1,0,World,2,3994,17.208542,18.228321,0.666845,17.208542,19.366875,2.158333,...,22.834999,8.120417,1.00,0.520000,23.457188,5.228868,23.387655,8.265417,0.985,0.526667
2,0,World,3,14744,17.116394,17.072041,0.482776,16.062317,17.796955,1.734638,...,26.072500,11.304584,1.00,0.640000,25.730000,8.657959,25.704063,11.171249,0.995,0.650000
3,0,World,4,3163,10.695886,10.434789,0.271945,9.915703,10.813854,0.898151,...,13.188750,1.786250,1.00,0.186667,12.976680,2.541891,12.789531,2.100781,0.955,0.248333
4,0,World,5,5222,9.152500,9.738646,0.434983,9.058959,10.305521,1.246562,...,2.136250,0.539583,0.24,0.053333,1.513203,-8.225443,2.016094,0.576406,0.225,0.065000
5,0,World,6,8901,9.130677,9.579131,0.463442,9.046276,10.284297,1.238021,...,11.070000,5.321250,0.72,0.386667,12.034394,2.455264,12.284844,5.432760,0.815,0.390000
6,0,World,7,406,8.718281,8.490631,0.455950,7.646354,9.005938,1.359583,...,5.815000,0.969583,0.60,0.133333,5.422598,-3.068034,5.217031,0.639583,0.540,0.090000
7,0,World,8,1728,8.028021,7.837565,0.576295,7.321458,9.230937,1.909479,...,1.585000,0.133333,0.20,0.013333,0.125273,-7.712292,1.445000,0.238333,0.175,0.028333
8,0,World,9,9069,7.454505,7.366465,0.095896,7.236146,7.472734,0.236588,...,6.240000,0.288333,0.68,0.026667,6.773203,-0.593262,6.136094,0.290000,0.665,0.028333
9,0,World,10,5743,7.108073,6.363096,0.474912,5.509922,7.108073,1.598151,...,11.075000,4.142917,0.88,0.453333,10.740742,4.377646,10.353750,4.118125,0.860,0.445000
10,0,World,11,1295,6.906670,6.035001,1.135353,3.399994,7.333336,3.933342,...,87.440002,80.533333,1.00,1.000000,86.085007,80.050003,86.085007,80.051666,1.000,0.998333
11,0,World,12,6211,6.290755,5.423099,0.615843,4.495000,6.435468,1.940468,...,10.587500,3.507917,0.80,0.346667,10.365703,4.942604,9.496876,3.648177,0.760,0.380000
12,0,World,13,11438,6.254206,6.362297,0.430337,5.527044,6.959271,1.432227,...,4.525000,0.586250,0.52,0.080000,4.993096,-1.369201,4.454375,0.449427,0.540,0.060000
13,0,World,14,2791,5.826881,5.904463,0.254279,5.545866,6.302370,0.756504,...,1.733750,0.173333,0.24,0.026667,3.014052,-2.890411,1.867969,0.200833,0.265,0.026667
14,0,World,15,13051,5.646966,5.330585,0.289526,4.813509,5.821875,1.008366,...,6.947500,1.601250,0.80,0.213333,7.202910,1.872325,6.390312,1.510573,0.755,0.206667
15,0,World,16,8386,5.642500,5.291221,0.395903,4.616563,5.877135,1.260572,...,5.203750,1.525000,0.60,0.186667,5.737158,0.445937,4.579375,1.392240,0.530,0.173333
16,0,World,17,3648,5.611178,5.076105,0.286442,4.753691,5.611178,0.857487,...,3.851250,0.000000,0.48,0.000000,4.945849,-0.130256,3.257812,0.029635,0.420,0.005000
17,0,World,18,2221,5.330026,5.019306,0.347828,4.443151,5.584323,1.141172,...,0.591250,0.000000,0.08,0.000000,0.812930,-4.206377,0.623594,0.000000,0.090,0.000000
18,0,World,19,14785,5.302891,5.150410,0.151394,4.854766,5.375391,0.520625,...,0.827500,0.000000,0.12,0.000000,3.141670,-2.008740,0.864375,0.000000,0.130,0.000000
19,0,World,20,541,5.249551,5.596493,0.193346,5.249551,5.931797,0.682246,...,2.832500,0.000000,0.36,0.000000,4.110859,-1.485634,3.232344,0.000000,0.420,0.000000

====================================================================================================
Sports: top-20 label-specific features

,label,label_word,label_specific_rank,feature_idx,baseline_label_specific_pre_gap,mean_label_specific_pre_gap_across_prefixes,std_label_specific_pre_gap_across_prefixes,min_label_specific_pre_gap_across_prefixes,max_label_specific_pre_gap_across_prefixes,range_label_specific_pre_gap_across_prefixes,...,baseline_mean_post_label,baseline_mean_post_other,baseline_activation_frequency_label,baseline_activation_frequency_other,mean_pre_label_across_prefixes,mean_pre_other_across_prefixes,mean_post_label_across_prefixes,mean_post_other_across_prefixes,activation_frequency_label_across_prefixes,activation_frequency_other_across_prefixes
0,1,Sports,1,8298,24.050652,22.940477,0.845712,21.719284,24.276039,2.556755,...,19.915001,1.837500,0.92,0.160000,18.930851,-4.009625,18.868752,1.949948,0.880,0.188333
1,1,Sports,2,3408,22.800678,23.357067,0.753121,22.364714,24.672396,2.307682,...,17.660000,3.086250,0.84,0.213333,16.739004,-6.618063,17.533123,2.690677,0.840,0.181667
2,1,Sports,3,13985,16.599998,16.668333,1.261279,14.639999,18.840004,4.200005,...,0.000000,0.000000,0.00,0.000000,-69.315002,-85.983330,0.000000,0.000000,0.000,0.000000
3,1,Sports,4,1740,14.022396,12.845013,0.688349,11.890000,14.022396,2.132396,...,13.695000,3.922500,0.80,0.293333,13.174101,0.329089,12.707188,3.903854,0.775,0.306667
4,1,Sports,5,14142,11.956979,12.132500,0.192365,11.770729,12.377396,0.606667,...,8.292500,0.000000,0.80,0.000000,9.259922,-2.872578,8.487500,0.000000,0.805,0.000000
5,1,Sports,6,5092,9.999765,8.855375,0.818214,7.872513,10.153509,2.280996,...,6.677500,0.922083,0.68,0.106667,6.103071,-2.752304,6.005625,1.203073,0.590,0.153333
6,1,Sports,7,5672,9.779193,9.778961,0.252513,9.532344,10.286563,0.754219,...,6.388750,0.000000,0.72,0.000000,7.119688,-2.659274,6.174219,0.000000,0.660,0.000000
7,1,Sports,8,9289,9.066875,8.910572,0.774636,7.620208,9.758750,2.138542,...,7.647500,2.866667,0.64,0.253333,7.790781,-1.119792,7.724375,2.678021,0.605,0.230000
8,1,Sports,9,2671,8.329636,7.141553,0.639478,6.330912,8.329636,1.998724,...,6.572500,1.614583,0.72,0.213333,5.989239,-1.152314,5.115781,1.337396,0.550,0.175000
9,1,Sports,10,3375,8.309010,7.341723,1.067167,5.686198,9.120013,3.433815,...,18.379999,12.889584,0.88,0.600000,16.863304,9.521583,17.306250,12.783697,0.855,0.605000
10,1,Sports,11,2999,8.238750,8.276276,0.556652,7.283334,9.093333,1.809999,...,15.690000,8.551666,0.88,0.560000,15.906797,7.630521,15.825624,8.489479,0.895,0.553333
11,1,Sports,12,5104,7.969713,7.359183,0.328925,6.930182,7.969713,1.039531,...,5.176250,0.000000,0.64,0.000000,4.604140,-2.755042,4.233281,0.000000,0.510,0.000000
12,1,Sports,13,1774,6.919844,7.046009,0.121218,6.913490,7.262500,0.349010,...,0.221250,0.000000,0.04,0.000000,1.552578,-5.493431,0.405156,0.000000,0.065,0.000000
13,1,Sports,14,45,6.072083,6.140192,0.249111,5.604974,6.468541,0.863567,...,7.243750,1.535417,0.80,0.173333,8.068047,1.927855,7.386250,1.554479,0.795,0.186667
14,1,Sports,15,13203,5.700078,5.362946,0.295426,4.834063,5.779479,0.945416,...,3.592500,0.000000,0.52,0.000000,5.038008,-0.324938,2.972969,0.000000,0.430,0.000000
15,1,Sports,16,13093,5.619583,5.317754,0.219556,4.981146,5.619583,0.638437,...,1.972500,0.178750,0.28,0.026667,3.286465,-2.031289,1.280469,0.150000,0.190,0.023333
16,1,Sports,17,11476,5.504167,5.121387,0.420500,4.522760,5.934427,1.411667,...,0.693750,0.278333,0.08,0.026667,0.619043,-4.502344,1.203437,0.137812,0.145,0.015000
17,1,Sports,18,7502,5.475469,4.457223,0.708568,3.391198,5.475469,2.084271,...,0.255000,0.000000,0.04,0.000000,-4.133349,-8.590573,0.290469,0.000000,0.040,0.000000
18,1,Sports,19,2572,5.453331,4.900416,0.795629,3.396667,6.093334,2.696667,...,0.000000,0.000000,0.00,0.000000,-57.055000,-61.955414,0.000000,0.000000,0.000,0.000000
19,1,Sports,20,14255,5.294167,4.996667,0.247574,4.716667,5.406666,0.689999,...,0.000000,0.000000,0.00,0.000000,-18.322811,-23.319479,0.000000,0.000000,0.000,0.000000

====================================================================================================
Business: top-20 label-specific features

,label,label_word,label_specific_rank,feature_idx,baseline_label_specific_pre_gap,mean_label_specific_pre_gap_across_prefixes,std_label_specific_pre_gap_across_prefixes,min_label_specific_pre_gap_across_prefixes,max_label_specific_pre_gap_across_prefixes,range_label_specific_pre_gap_across_prefixes,...,baseline_mean_post_label,baseline_mean_post_other,baseline_activation_frequency_label,baseline_activation_frequency_other,mean_pre_label_across_prefixes,mean_pre_other_across_prefixes,mean_post_label_across_prefixes,mean_post_other_across_prefixes,activation_frequency_label_across_prefixes,activation_frequency_other_across_prefixes
0,2,Business,1,16288,18.021406,17.906029,0.819717,16.492188,19.204584,2.712397,...,13.192500,2.028750,0.88,0.200000,12.246855,-5.659173,12.898125,1.699375,0.810,0.176667
1,2,Business,2,5333,13.143958,13.979466,0.715816,13.109062,15.095729,1.986667,...,4.641250,1.220000,0.36,0.093333,0.689570,-13.289895,4.822187,1.472188,0.365,0.111667
2,2,Business,3,5349,10.461979,10.877018,0.254624,10.461979,11.209583,0.747604,...,5.710000,0.535833,0.48,0.066667,3.337148,-7.539869,5.371562,0.500156,0.480,0.060000
3,2,Business,4,1295,9.786667,8.961668,1.476517,6.840004,10.706665,3.866661,...,89.599998,79.813332,1.00,1.000000,88.279999,79.318336,88.279999,79.320000,1.000,0.998333
4,2,Business,5,16159,8.708261,8.988398,0.889292,7.797657,10.407084,2.609427,...,10.621250,5.459583,0.60,0.360000,7.467456,-1.520942,11.019062,5.763333,0.595,0.393333
5,2,Business,6,3678,7.642838,7.297445,0.532268,6.535228,8.058743,1.523516,...,4.456250,1.046667,0.40,0.120000,4.181824,-3.115621,4.601875,0.993542,0.465,0.123333
6,2,Business,7,3375,7.496718,9.034328,0.783126,7.496718,9.744219,2.247500,...,17.625000,13.141250,0.80,0.626667,18.132759,9.098431,18.420469,12.412292,0.870,0.600000
7,2,Business,8,2039,6.826914,6.845218,0.192631,6.487507,7.074707,0.587200,...,8.751250,1.240417,0.84,0.173333,9.311289,2.466071,8.868593,1.110000,0.865,0.155000
8,2,Business,9,15267,6.668333,6.343281,0.362414,5.701250,6.823334,1.122084,...,0.000000,0.000000,0.00,0.000000,-23.018282,-29.361563,0.000000,0.000000,0.000,0.000000
9,2,Business,10,14960,6.380482,6.098875,0.425689,5.367604,6.565729,1.198125,...,5.041250,0.901667,0.44,0.106667,4.904075,-1.194800,4.425312,0.654740,0.420,0.075000
10,2,Business,11,10303,5.940000,5.414632,0.557673,4.661562,5.986042,1.324479,...,2.798750,1.464583,0.32,0.160000,2.648047,-2.766585,2.569062,1.503802,0.275,0.165000
11,2,Business,12,10090,5.499636,5.707090,0.237604,5.304199,6.123750,0.819551,...,1.012500,0.000000,0.12,0.000000,1.979448,-3.727642,1.069688,0.010104,0.140,0.001667
12,2,Business,13,6193,5.424583,5.431357,0.256519,4.996198,5.961120,0.964921,...,4.042500,0.253333,0.40,0.026667,4.355859,-1.075498,3.702500,0.223854,0.395,0.028333
13,2,Business,14,10489,5.201589,5.476843,0.284638,5.175026,5.996407,0.821381,...,2.670000,0.080000,0.28,0.013333,-0.546846,-6.023688,2.395313,0.110833,0.235,0.015000
14,2,Business,15,8901,4.534010,4.424300,0.417562,3.655886,4.980703,1.324818,...,9.920000,5.704583,0.68,0.400000,8.168272,3.743971,9.576718,6.335468,0.620,0.455000
15,2,Business,16,10483,4.466042,4.477539,0.281875,4.021823,4.831407,0.809584,...,2.245000,0.193333,0.28,0.026667,1.539727,-2.937812,1.991250,0.119583,0.260,0.018333
16,2,Business,17,8875,4.051068,4.146771,0.430896,3.599167,4.771250,1.172083,...,2.255000,2.277500,0.28,0.213333,2.817510,-1.329261,2.356875,2.248229,0.275,0.201667
17,2,Business,18,9009,3.850625,3.340475,0.447017,2.765781,4.054375,1.288594,...,0.320000,0.000000,0.04,0.000000,-2.235942,-5.576417,0.134531,0.014062,0.020,0.001667
18,2,Business,19,44,3.568620,3.480794,0.372420,2.956771,4.001849,1.045078,...,4.353750,0.839167,0.48,0.106667,4.296474,0.815680,3.933438,0.698021,0.470,0.095000
19,2,Business,20,8551,3.481354,3.930846,0.727305,2.922917,5.050208,2.127291,...,3.977500,2.336667,0.36,0.213333,1.818438,-2.112409,4.408594,2.390156,0.395,0.238333

====================================================================================================
Technology: top-20 label-specific features

,label,label_word,label_specific_rank,feature_idx,baseline_label_specific_pre_gap,mean_label_specific_pre_gap_across_prefixes,std_label_specific_pre_gap_across_prefixes,min_label_specific_pre_gap_across_prefixes,max_label_specific_pre_gap_across_prefixes,range_label_specific_pre_gap_across_prefixes,...,baseline_mean_post_label,baseline_mean_post_other,baseline_activation_frequency_label,baseline_activation_frequency_other,mean_pre_label_across_prefixes,mean_pre_other_across_prefixes,mean_post_label_across_prefixes,mean_post_other_across_prefixes,activation_frequency_label_across_prefixes,activation_frequency_other_across_prefixes
0,3,Technology,1,1831,18.446405,17.769663,0.399834,17.148815,18.446405,1.297590,...,5.548750,0.429583,0.40,0.026667,-0.809346,-18.579010,5.779375,0.452917,0.410,0.028333
1,3,Technology,2,3442,14.010313,13.757292,0.361856,13.073854,14.207812,1.133958,...,6.460000,1.104167,0.52,0.106667,6.358945,-7.398346,6.702500,1.107708,0.550,0.105000
2,3,Technology,3,16159,12.843471,12.190546,0.857285,10.102630,12.843471,2.740841,...,10.512500,5.495833,0.68,0.333333,9.869067,-2.321479,10.420626,5.962812,0.675,0.366667
3,3,Technology,4,7700,11.832865,12.011211,0.254297,11.573385,12.343229,0.769844,...,13.573750,2.967917,0.88,0.253333,14.510704,2.499492,14.463125,3.766719,0.905,0.330000
4,3,Technology,5,9247,11.271146,10.950583,0.705674,10.012917,12.210990,2.198073,...,6.308750,1.355000,0.40,0.133333,3.515400,-7.435183,6.415000,1.494948,0.455,0.146667
5,3,Technology,6,8875,9.317318,7.984427,0.650001,7.155416,9.317318,2.161901,...,6.562500,0.841667,0.60,0.106667,5.695752,-2.288675,6.142500,0.986354,0.535,0.115000
6,3,Technology,7,13811,8.518959,8.362705,0.487091,7.628333,9.117161,1.488828,...,1.492500,0.000000,0.20,0.000000,-0.066436,-8.429140,1.486875,0.011146,0.195,0.001667
7,3,Technology,8,14601,8.241979,7.082448,0.530843,6.416979,8.241979,1.824999,...,2.027500,0.241667,0.16,0.026667,-4.491601,-11.574049,1.840312,0.373490,0.185,0.048333
8,3,Technology,9,10070,7.406666,7.053958,0.599918,5.976669,7.993336,2.016666,...,0.000000,0.000000,0.00,0.000000,-40.016876,-47.070831,0.000000,0.000000,0.000,0.000000
9,3,Technology,10,10303,7.059792,6.406273,0.431194,5.728463,7.060521,1.332058,...,4.393750,0.932917,0.48,0.106667,3.391778,-3.014495,4.450937,0.876510,0.485,0.095000
10,3,Technology,11,3375,6.755260,5.329477,0.655025,4.557774,6.755260,2.197487,...,18.014999,13.011250,0.76,0.640000,15.354120,10.024643,17.271873,12.795156,0.745,0.641667
11,3,Technology,12,8551,6.235520,5.040794,0.609251,3.899896,6.235520,2.335625,...,4.920000,2.022500,0.44,0.186667,2.650898,-2.389896,4.617031,2.320677,0.450,0.220000
12,3,Technology,13,14316,5.854375,5.443210,0.239978,5.085938,5.854375,0.768437,...,4.302500,0.192500,0.52,0.026667,4.030039,-1.413171,4.163906,0.206458,0.530,0.028333
13,3,Technology,14,14370,5.646875,5.133496,0.323178,4.777552,5.646875,0.869323,...,1.398750,0.000000,0.20,0.000000,0.194258,-4.939239,0.897500,0.012240,0.130,0.001667
14,3,Technology,15,5131,5.481668,4.733750,0.433373,4.176666,5.481668,1.305002,...,0.000000,0.000000,0.00,0.000000,-29.993126,-34.726875,0.000000,0.000000,0.000,0.000000
15,3,Technology,16,7281,4.958855,4.098086,0.734436,2.895782,4.958855,2.063073,...,8.957500,4.635833,0.72,0.373333,8.722950,4.624863,8.547501,5.033438,0.700,0.416667
16,3,Technology,17,12559,4.935482,4.577303,0.258178,4.067435,4.935482,0.868047,...,3.100000,0.405417,0.44,0.053333,3.469800,-1.107503,2.443750,0.572135,0.335,0.073333
17,3,Technology,18,7152,4.660000,4.016875,0.475936,3.059999,4.660000,1.600000,...,0.000000,0.000000,0.00,0.000000,-26.318750,-30.335625,0.000000,0.000000,0.000,0.000000
18,3,Technology,19,12592,4.537498,4.100625,0.394584,3.491667,4.537498,1.045832,...,0.000000,0.000000,0.00,0.000000,-21.790939,-25.891563,0.000000,0.000000,0.000,0.000000
19,3,Technology,20,6880,4.260000,3.815834,0.423438,3.134998,4.310417,1.175419,...,30.900000,26.617500,1.00,0.986667,30.310314,26.494480,30.310314,26.472500,1.000,0.985000

Union of selected features across labels: 72 unique features.

## 5A. Rank table for baseline top-20 label-specific features across P2–P8

This diagnostic keeps the 80 features selected from the ordinary baseline prefix `P1` and reports where each one ranks under the alternative final-demo prefixes `P2` through `P8`. Rank `1` means the most label-specific feature for that label under that prefix; larger ranks indicate that the feature becomes less label-specific under that prefix.

In [7]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

In [8]:

# ============================================================
# 5A. Rank table: baseline top-20 label-specific features in P2..P8
# ============================================================

# This cell assumes Section 5 has already run and created:
#   label_specific_stability_df
#   label_variant_ranks
#   label_specific_pre_gap
#   label_top_features
#
# Interpretation:
#   P1 is the ordinary single-prefix baseline used to select top-20 features.
#   P2..P8 keep the same queries and demos 1..7, but replace only demo 8.
#   Rank 1 = most label-specific feature for that label under that prefix.

required_for_rank_table = [
    "label_specific_stability_df",
    "label_variant_ranks",
    "label_specific_pre_gap",
    "label_top_features",
]
missing = [name for name in required_for_rank_table if name not in globals()]
if missing:
    raise RuntimeError(
        "Run Sections 4 and 5 before this rank-table diagnostic. "
        f"Missing variables: {missing}"
    )

rank_rows = []
for _, row in label_specific_stability_df.iterrows():
    lab = int(row["label"])
    feat = int(row["feature_idx"])
    baseline_rank = int(row["label_specific_rank"])

    ranks = [int(label_variant_ranks[lab, v, feat]) for v in range(N_PREFIX_VARIANTS)]
    gaps = [float(label_specific_pre_gap[lab, v, feat]) for v in range(N_PREFIX_VARIANTS)]

    additional_ranks = ranks[1:]
    additional_gaps = gaps[1:]
    worst_additional_idx = int(np.argmax(additional_ranks)) + 1  # convert additional slot to variant index v
    best_additional_idx = int(np.argmin(additional_ranks)) + 1

    out = {
        "label_word": row["label_word"],
        "P1_baseline_rank": baseline_rank,
        "feature_idx": feat,
        "feature": f"L{TARGET_LAYER}-{feat}",
        "stable_by_rule": bool(row["stable_by_rule"]),
        "retention_rate_topK": float(row[f"retention_rate_top_{RETENTION_TOP_K}"]),
        "min_over_baseline": float(row["min_over_baseline"]),
        "baseline_gap_P1": float(gaps[0]),
        "worst_rank_P2_to_P8": int(max(additional_ranks)),
        "worst_prefix_P2_to_P8": f"P{worst_additional_idx + 1}",
        "best_rank_P2_to_P8": int(min(additional_ranks)),
        "best_prefix_P2_to_P8": f"P{best_additional_idx + 1}",
        f"n_P2_to_P8_in_top{RETENTION_TOP_K}": int(sum(r <= RETENTION_TOP_K for r in additional_ranks)),
    }

    # Add exact ranks and gaps for every prefix. P1 is included for context;
    # P2..P8 are the requested alternative-prefix ranks.
    for v in range(N_PREFIX_VARIANTS):
        out[f"P{v + 1}_rank"] = int(ranks[v])
    for v in range(N_PREFIX_VARIANTS):
        out[f"P{v + 1}_gap"] = float(gaps[v])

    rank_rows.append(out)

# Main table: one row per baseline-selected top-20 label-specific feature.
top20_label_specific_rank_by_prefix_df = pd.DataFrame(rank_rows)

rank_display_cols = (
    [
        "label_word",
        "P1_baseline_rank",
        "feature",
        "feature_idx",
        "stable_by_rule",
        "retention_rate_topK",
        "min_over_baseline",
        "baseline_gap_P1",
        "worst_rank_P2_to_P8",
        "worst_prefix_P2_to_P8",
        "best_rank_P2_to_P8",
        "best_prefix_P2_to_P8",
        f"n_P2_to_P8_in_top{RETENTION_TOP_K}",
    ]
    + [f"P{v + 1}_rank" for v in range(N_PREFIX_VARIANTS)]
)

# Requested table: rank under P2..P8 for each P1 top-20 label-specific feature.
print("=" * 100)
print(f"Ranks of P1 top-{LABEL_SPECIFIC_TOP_N} label-specific features under P2..P{N_PREFIX_VARIANTS}")
print("Rank 1 = most label-specific under that prefix. Larger ranks indicate loss of label specificity.")
print("=" * 100)
display(
    top20_label_specific_rank_by_prefix_df[rank_display_cols]
    .sort_values(["label_word", "P1_baseline_rank"])
    .reset_index(drop=True)
)

# Per-label compact tables, easier to copy into a rebuttal appendix.
for lab in range(NUM_LABELS):
    label_word = label_to_words_agnews[lab]
    print("=" * 100)
    print(f"{label_word}: P1 top-{LABEL_SPECIFIC_TOP_N} features and their ranks in P2..P{N_PREFIX_VARIANTS}")
    cols = (
        ["P1_baseline_rank", "feature", "stable_by_rule", "worst_rank_P2_to_P8", "worst_prefix_P2_to_P8"]
        + [f"P{v + 1}_rank" for v in range(1, N_PREFIX_VARIANTS)]
    )
    display(
        top20_label_specific_rank_by_prefix_df
        .loc[top20_label_specific_rank_by_prefix_df["label_word"] == label_word, cols]
        .sort_values("P1_baseline_rank")
        .reset_index(drop=True)
    )

# Worst rank collapses across all labels. This is useful for illustrating the single-prefix risk.
rank_collapse_examples_df = (
    top20_label_specific_rank_by_prefix_df
    .assign(rank_collapse=lambda df: df["worst_rank_P2_to_P8"] - df["P1_baseline_rank"])
    .sort_values("rank_collapse", ascending=False)
    .reset_index(drop=True)
)

print("=" * 100)
print("Largest rank-collapse examples among the P1 top-20 label-specific features")
print("=" * 100)
display(
    rank_collapse_examples_df[
        [
            "label_word", "P1_baseline_rank", "feature", "stable_by_rule",
            "worst_prefix_P2_to_P8", "worst_rank_P2_to_P8", "rank_collapse",
        ]
        + [f"P{v + 1}_rank" for v in range(N_PREFIX_VARIANTS)]
    ].head(20)
)

# Optional Plotly heatmap of log10(rank). This makes large rank collapses visible without saturating the scale.
def plot_top20_rank_heatmap_by_label(lab: int):
    label_word = label_to_words_agnews[int(lab)]
    sub = (
        top20_label_specific_rank_by_prefix_df
        .loc[top20_label_specific_rank_by_prefix_df["label_word"] == label_word]
        .sort_values("P1_baseline_rank")
        .reset_index(drop=True)
    )
    rank_cols = [f"P{v + 1}_rank" for v in range(N_PREFIX_VARIANTS)]
    ranks = sub[rank_cols].to_numpy(dtype=np.float64)
    log_ranks = np.log10(ranks)

    fig = go.Figure(
        data=go.Heatmap(
            z=log_ranks,
            x=[f"P{v + 1}" for v in range(N_PREFIX_VARIANTS)],
            y=[f"{r['feature']} (P1 rank {int(r['P1_baseline_rank'])})" for _, r in sub.iterrows()],
            colorscale="Blues",
            customdata=ranks,
            colorbar=dict(title="log10(rank)"),
            hovertemplate=(
                "feature=%{y}<br>prefix=%{x}<br>"
                "rank=%{customdata:.0f}<br>log10(rank)=%{z:.3f}<extra></extra>"
            ),
        )
    )
    fig.update_layout(
        title=f"{label_word}: ranks of P1 top-{LABEL_SPECIFIC_TOP_N} label-specific features across P1..P{N_PREFIX_VARIANTS}",
        xaxis_title="Prefix variant",
        yaxis_title="Feature selected from P1 baseline",
        height=max(450, 26 * len(sub) + 180),
        width=max(850, 90 * N_PREFIX_VARIANTS + 350),
    )
    fig.show()

for lab in range(NUM_LABELS):
    plot_top20_rank_heatmap_by_label(lab)

====================================================================================================
Ranks of P1 top-20 label-specific features under P2..P8
Rank 1 = most label-specific under that prefix. Larger ranks indicate loss of label specificity.
====================================================================================================

,label_word,P1_baseline_rank,feature,feature_idx,stable_by_rule,retention_rate_topK,min_over_baseline,baseline_gap_P1,worst_rank_P2_to_P8,worst_prefix_P2_to_P8,best_rank_P2_to_P8,best_prefix_P2_to_P8,n_P2_to_P8_in_top20,P1_rank,P2_rank,P3_rank,P4_rank,P5_rank,P6_rank,P7_rank,P8_rank
0,Business,1,L20-16288,16288,True,1.000,0.915144,18.021406,1,P2,1,P2,7,1,1,1,1,1,1,1,1
1,Business,2,L20-5333,5333,True,1.000,0.997345,13.143958,2,P2,2,P2,7,2,2,2,2,2,2,2,2
2,Business,3,L20-5349,5349,True,1.000,1.000000,10.461979,3,P2,3,P2,7,3,3,3,3,3,3,3,3
3,Business,4,L20-1295,1295,True,1.000,0.698910,9.786667,8,P8,4,P3,7,4,7,4,5,5,4,6,8
4,Business,5,L20-16159,16159,True,1.000,0.895432,8.708261,6,P5,4,P4,7,5,5,5,4,6,6,5,4
5,Business,6,L20-3678,3678,True,1.000,0.855079,7.642838,8,P4,6,P2,7,6,6,7,8,7,8,7,6
6,Business,7,L20-3375,3375,True,1.000,1.000000,7.496718,6,P3,4,P2,7,7,4,6,6,4,5,4,5
7,Business,8,L20-2039,2039,True,1.000,0.950284,6.826914,8,P2,7,P4,7,8,8,8,7,8,7,8,7
8,Business,9,L20-15267,15267,True,1.000,0.854974,6.668333,13,P2,9,P3,7,9,13,9,9,9,10,9,10
9,Business,10,L20-14960,14960,True,1.000,0.841254,6.380482,11,P3,9,P2,7,10,9,11,10,10,9,10,9
10,Business,11,L20-10303,10303,True,1.000,0.784775,5.940000,15,P3,10,P2,7,11,10,15,13,15,13,15,12
11,Business,12,L20-10090,10090,True,1.000,0.964464,5.499636,12,P2,10,P3,7,12,12,10,11,11,12,11,11
12,Business,13,L20-6193,6193,True,1.000,0.921029,5.424583,14,P4,11,P2,7,13,11,13,14,12,14,12,14
13,Business,14,L20-10489,10489,True,1.000,0.994893,5.201589,14,P2,11,P6,7,14,14,12,12,13,11,13,13
14,Business,15,L20-8901,8901,True,1.000,0.806325,4.534010,19,P2,14,P3,7,15,19,14,18,16,16,14,17
15,Business,16,L20-10483,10483,True,1.000,0.900534,4.466042,17,P2,14,P5,7,16,17,16,16,14,15,17,15
16,Business,17,L20-8875,8875,True,1.000,0.888449,4.051068,19,P5,15,P4,7,17,16,18,15,19,18,16,18
17,Business,18,L20-9009,9009,False,0.375,0.718268,3.850625,29,P4,17,P5,2,18,21,25,29,17,21,22,19
18,Business,19,L20-44,44,False,0.750,0.828547,3.568620,24,P6,18,P2,5,19,18,20,21,18,24,19,20
19,Business,20,L20-8551,8551,False,0.625,0.839592,3.481354,22,P5,15,P2,4,20,15,21,17,22,17,21,16
20,Sports,1,L20-8298,8298,True,1.000,0.903064,24.050652,2,P3,1,P2,7,1,1,2,2,2,1,2,2
21,Sports,2,L20-3408,3408,True,1.000,0.980879,22.800678,2,P2,1,P3,7,2,2,1,1,1,2,1,1
22,Sports,3,L20-13985,13985,True,1.000,0.881928,16.599998,3,P2,3,P2,7,3,3,3,3,3,3,3,3
23,Sports,4,L20-1740,1740,True,1.000,0.847929,14.022396,5,P4,4,P2,7,4,4,4,5,4,4,4,4
24,Sports,5,L20-14142,14142,True,1.000,0.984423,11.956979,5,P2,4,P4,7,5,5,5,4,5,5,5,5
25,Sports,6,L20-5092,5092,True,1.000,0.787270,9.999765,9,P6,6,P2,7,6,6,7,8,8,9,7,8
26,Sports,7,L20-5672,5672,True,1.000,0.974758,9.779193,7,P2,6,P3,7,7,7,6,6,6,6,6,7
27,Sports,8,L20-9289,9289,True,1.000,0.840445,9.066875,10,P7,6,P8,7,8,8,9,7,7,7,10,6
28,Sports,9,L20-2671,2671,True,1.000,0.760047,8.329636,13,P3,11,P2,7,9,11,13,11,13,12,13,12
29,Sports,10,L20-3375,3375,True,1.000,0.684341,8.309010,15,P6,9,P2,7,10,9,12,14,10,15,9,10
30,Sports,11,L20-2999,2999,True,1.000,0.884034,8.238750,10,P2,8,P3,7,11,10,8,10,9,8,8,9
31,Sports,12,L20-5104,5104,True,1.000,0.869565,7.969713,12,P2,9,P4,7,12,12,10,9,12,11,11,11
32,Sports,13,L20-1774,1774,True,1.000,0.999082,6.919844,13,P2,10,P6,7,13,13,11,12,11,10,12,13
33,Sports,14,L20-45,45,True,1.000,0.923073,6.072083,14,P2,13,P4,7,14,14,14,13,14,13,14,14
34,Sports,15,L20-13203,13203,True,1.000,0.848070,5.700078,20,P3,15,P8,7,15,16,20,17,17,17,18,15
35,Sports,16,L20-13093,13093,True,1.000,0.886391,5.619583,19,P7,15,P5,7,16,18,17,16,15,16,19,19
36,Sports,17,L20-11476,11476,False,0.625,0.821698,5.504167,24,P7,15,P2,4,17,15,21,18,20,19,24,21
37,Sports,18,L20-7502,7502,False,0.250,0.619344,5.475469,47,P7,20,P8,1,18,21,41,37,26,23,47,20
38,Sports,19,L20-2572,2572,False,0.625,0.622861,5.453331,46,P7,14,P6,4,19,19,28,33,19,14,46,16
39,Sports,20,L20-14255,14255,False,0.625,0.890918,5.294167,25,P2,18,P3,4,20,25,18,22,22,18,20,18
40,Technology,1,L20-1831,1831,True,1.000,0.929656,18.446405,1,P2,1,P2,7,1,1,1,1,1,1,1,1
41,Technology,2,L20-3442,3442,True,1.000,0.933159,14.010313,2,P2,2,P2,7,2,2,2,2,2,2,2,2
42,Technology,3,L20-16159,16159,True,1.000,0.786597,12.843471,5,P6,3,P3,7,3,4,3,3,3,5,3,3
43,Technology,4,L20-7700,7700,True,1.000,0.978071,11.832865,5,P3,3,P2,7,4,3,5,4,4,3,4,4
44,Technology,5,L20-9247,9247,True,1.000,0.888367,11.271146,5,P2,4,P3,7,5,5,4,5,5,4,5,5
45,Technology,6,L20-8875,8875,True,1.000,0.767970,9.317318,8,P3,6,P2,7,6,6,8,7,7,7,7,7
46,Technology,7,L20-13811,13811,True,1.000,0.895454,8.518959,7,P2,6,P3,7,7,7,6,6,6,6,6,6
47,Technology,8,L20-14601,14601,True,1.000,0.778573,8.241979,9,P2,7,P3,7,8,9,7,9,8,9,9,9
48,Technology,9,L20-10070,10070,True,1.000,0.806931,7.406666,10,P3,8,P2,7,9,8,10,8,10,8,8,8
49,Technology,10,L20-10303,10303,True,1.000,0.811421,7.059792,10,P2,9,P3,7,10,10,9,10,9,10,10,10
50,Technology,11,L20-3375,3375,True,1.000,0.674700,6.755260,15,P2,11,P7,7,11,15,12,12,15,12,11,13
51,Technology,12,L20-8551,8551,False,0.875,0.625432,6.235520,21,P4,12,P5,6,12,14,13,21,12,13,14,14
52,Technology,13,L20-14316,14316,True,1.000,0.868741,5.854375,13,P5,11,P3,7,13,12,11,11,13,11,12,11
53,Technology,14,L20-14370,14370,True,1.000,0.846052,5.646875,14,P3,11,P5,7,14,13,14,13,11,14,13,12
54,Technology,15,L20-5131,5131,False,0.875,0.761933,5.481668,21,P7,11,P2,6,15,11,16,14,16,17,21,15
55,Technology,16,L20-7281,7281,False,0.625,0.583962,4.958855,48,P2,15,P6,4,16,48,22,38,19,15,17,20
56,Technology,17,L20-12559,12559,False,0.875,0.824121,4.935482,22,P6,14,P5,6,17,16,15,15,14,22,18,16
57,Technology,18,L20-7152,7152,False,0.375,0.656652,4.660000,43,P3,17,P8,2,18,22,43,23,25,20,25,17
58,Technology,19,L20-12592,12592,False,0.500,0.769514,4.537498,29,P3,18,P2,3,19,18,29,28,24,18,23,18
59,Technology,20,L20-6880,6880,False,0.375,0.735915,4.260000,39,P2,16,P4,2,20,39,32,16,20,21,27,35
60,World,1,L20-13844,13844,True,1.000,0.876930,22.572865,1,P2,1,P2,7,1,1,1,1,1,1,1,1
61,World,2,L20-3994,3994,True,1.000,1.000000,17.208542,2,P2,2,P2,7,2,2,2,2,2,2,2,2
62,World,3,L20-14744,14744,True,1.000,0.938417,17.116394,3,P2,3,P2,7,3,3,3,3,3,3,3,3
63,World,4,L20-3163,3163,True,1.000,0.927058,10.695886,6,P4,4,P2,7,4,4,4,6,4,4,4,4
64,World,5,L20-5222,5222,True,1.000,0.989780,9.152500,6,P3,4,P4,7,5,5,6,4,6,5,5,5
65,World,6,L20-8901,8901,True,1.000,0.990756,9.130677,6,P2,5,P3,7,6,6,5,5,5,6,6,6
66,World,7,L20-406,406,True,1.000,0.877048,8.718281,8,P6,7,P2,7,7,7,7,7,7,8,8,7
67,World,8,L20-1728,1728,True,1.000,0.911988,8.028021,9,P2,7,P6,7,8,9,9,8,8,7,7,8
68,World,9,L20-9069,9069,True,1.000,0.970708,7.454505,10,P8,8,P2,7,9,8,8,9,9,9,9,10
69,World,10,L20-5743,5743,True,1.000,0.775164,7.108073,15,P6,10,P3,7,10,12,10,10,11,15,12,11
70,World,11,L20-1295,1295,False,0.875,0.492277,6.906670,43,P4,9,P8,6,11,11,14,43,10,10,13,9
71,World,12,L20-6211,6211,False,0.875,0.714541,6.290755,25,P7,12,P8,6,12,17,17,17,15,16,25,12
72,World,13,L20-11438,11438,True,1.000,0.883732,6.254206,13,P3,10,P2,7,13,10,13,11,12,11,10,13
73,World,14,L20-2791,2791,True,1.000,0.951773,5.826881,14,P6,11,P7,7,14,13,12,12,13,14,11,14
74,World,15,L20-13051,13051,True,1.000,0.852406,5.646966,20,P3,15,P4,7,15,18,20,15,16,18,15,16
75,World,16,L20-8386,8386,False,0.750,0.818177,5.642500,23,P5,14,P2,5,16,14,15,14,23,21,18,17
76,World,17,L20-3648,3648,False,0.500,0.847182,5.611178,22,P2,16,P7,3,17,22,21,21,18,20,16,21
77,World,18,L20-2221,2221,False,0.750,0.833608,5.330026,23,P7,16,P2,5,18,16,22,18,19,19,23,18
78,World,19,L20-14785,14785,True,1.000,0.915494,5.302891,20,P2,17,P5,7,19,20,18,19,17,17,17,19
79,World,20,L20-541,541,True,1.000,1.000000,5.249551,15,P2,11,P3,7,20,15,11,13,14,12,14,15

====================================================================================================
World: P1 top-20 features and their ranks in P2..P8

,P1_baseline_rank,feature,stable_by_rule,worst_rank_P2_to_P8,worst_prefix_P2_to_P8,P2_rank,P3_rank,P4_rank,P5_rank,P6_rank,P7_rank,P8_rank
0,1,L20-13844,True,1,P2,1,1,1,1,1,1,1
1,2,L20-3994,True,2,P2,2,2,2,2,2,2,2
2,3,L20-14744,True,3,P2,3,3,3,3,3,3,3
3,4,L20-3163,True,6,P4,4,4,6,4,4,4,4
4,5,L20-5222,True,6,P3,5,6,4,6,5,5,5
5,6,L20-8901,True,6,P2,6,5,5,5,6,6,6
6,7,L20-406,True,8,P6,7,7,7,7,8,8,7
7,8,L20-1728,True,9,P2,9,9,8,8,7,7,8
8,9,L20-9069,True,10,P8,8,8,9,9,9,9,10
9,10,L20-5743,True,15,P6,12,10,10,11,15,12,11
10,11,L20-1295,False,43,P4,11,14,43,10,10,13,9
11,12,L20-6211,False,25,P7,17,17,17,15,16,25,12
12,13,L20-11438,True,13,P3,10,13,11,12,11,10,13
13,14,L20-2791,True,14,P6,13,12,12,13,14,11,14
14,15,L20-13051,True,20,P3,18,20,15,16,18,15,16
15,16,L20-8386,False,23,P5,14,15,14,23,21,18,17
16,17,L20-3648,False,22,P2,22,21,21,18,20,16,21
17,18,L20-2221,False,23,P7,16,22,18,19,19,23,18
18,19,L20-14785,True,20,P2,20,18,19,17,17,17,19
19,20,L20-541,True,15,P2,15,11,13,14,12,14,15

====================================================================================================
Sports: P1 top-20 features and their ranks in P2..P8

,P1_baseline_rank,feature,stable_by_rule,worst_rank_P2_to_P8,worst_prefix_P2_to_P8,P2_rank,P3_rank,P4_rank,P5_rank,P6_rank,P7_rank,P8_rank
0,1,L20-8298,True,2,P3,1,2,2,2,1,2,2
1,2,L20-3408,True,2,P2,2,1,1,1,2,1,1
2,3,L20-13985,True,3,P2,3,3,3,3,3,3,3
3,4,L20-1740,True,5,P4,4,4,5,4,4,4,4
4,5,L20-14142,True,5,P2,5,5,4,5,5,5,5
5,6,L20-5092,True,9,P6,6,7,8,8,9,7,8
6,7,L20-5672,True,7,P2,7,6,6,6,6,6,7
7,8,L20-9289,True,10,P7,8,9,7,7,7,10,6
8,9,L20-2671,True,13,P3,11,13,11,13,12,13,12
9,10,L20-3375,True,15,P6,9,12,14,10,15,9,10
10,11,L20-2999,True,10,P2,10,8,10,9,8,8,9
11,12,L20-5104,True,12,P2,12,10,9,12,11,11,11
12,13,L20-1774,True,13,P2,13,11,12,11,10,12,13
13,14,L20-45,True,14,P2,14,14,13,14,13,14,14
14,15,L20-13203,True,20,P3,16,20,17,17,17,18,15
15,16,L20-13093,True,19,P7,18,17,16,15,16,19,19
16,17,L20-11476,False,24,P7,15,21,18,20,19,24,21
17,18,L20-7502,False,47,P7,21,41,37,26,23,47,20
18,19,L20-2572,False,46,P7,19,28,33,19,14,46,16
19,20,L20-14255,False,25,P2,25,18,22,22,18,20,18

====================================================================================================
Business: P1 top-20 features and their ranks in P2..P8

,P1_baseline_rank,feature,stable_by_rule,worst_rank_P2_to_P8,worst_prefix_P2_to_P8,P2_rank,P3_rank,P4_rank,P5_rank,P6_rank,P7_rank,P8_rank
0,1,L20-16288,True,1,P2,1,1,1,1,1,1,1
1,2,L20-5333,True,2,P2,2,2,2,2,2,2,2
2,3,L20-5349,True,3,P2,3,3,3,3,3,3,3
3,4,L20-1295,True,8,P8,7,4,5,5,4,6,8
4,5,L20-16159,True,6,P5,5,5,4,6,6,5,4
5,6,L20-3678,True,8,P4,6,7,8,7,8,7,6
6,7,L20-3375,True,6,P3,4,6,6,4,5,4,5
7,8,L20-2039,True,8,P2,8,8,7,8,7,8,7
8,9,L20-15267,True,13,P2,13,9,9,9,10,9,10
9,10,L20-14960,True,11,P3,9,11,10,10,9,10,9
10,11,L20-10303,True,15,P3,10,15,13,15,13,15,12
11,12,L20-10090,True,12,P2,12,10,11,11,12,11,11
12,13,L20-6193,True,14,P4,11,13,14,12,14,12,14
13,14,L20-10489,True,14,P2,14,12,12,13,11,13,13
14,15,L20-8901,True,19,P2,19,14,18,16,16,14,17
15,16,L20-10483,True,17,P2,17,16,16,14,15,17,15
16,17,L20-8875,True,19,P5,16,18,15,19,18,16,18
17,18,L20-9009,False,29,P4,21,25,29,17,21,22,19
18,19,L20-44,False,24,P6,18,20,21,18,24,19,20
19,20,L20-8551,False,22,P5,15,21,17,22,17,21,16

====================================================================================================
Technology: P1 top-20 features and their ranks in P2..P8

,P1_baseline_rank,feature,stable_by_rule,worst_rank_P2_to_P8,worst_prefix_P2_to_P8,P2_rank,P3_rank,P4_rank,P5_rank,P6_rank,P7_rank,P8_rank
0,1,L20-1831,True,1,P2,1,1,1,1,1,1,1
1,2,L20-3442,True,2,P2,2,2,2,2,2,2,2
2,3,L20-16159,True,5,P6,4,3,3,3,5,3,3
3,4,L20-7700,True,5,P3,3,5,4,4,3,4,4
4,5,L20-9247,True,5,P2,5,4,5,5,4,5,5
5,6,L20-8875,True,8,P3,6,8,7,7,7,7,7
6,7,L20-13811,True,7,P2,7,6,6,6,6,6,6
7,8,L20-14601,True,9,P2,9,7,9,8,9,9,9
8,9,L20-10070,True,10,P3,8,10,8,10,8,8,8
9,10,L20-10303,True,10,P2,10,9,10,9,10,10,10
10,11,L20-3375,True,15,P2,15,12,12,15,12,11,13
11,12,L20-8551,False,21,P4,14,13,21,12,13,14,14
12,13,L20-14316,True,13,P5,12,11,11,13,11,12,11
13,14,L20-14370,True,14,P3,13,14,13,11,14,13,12
14,15,L20-5131,False,21,P7,11,16,14,16,17,21,15
15,16,L20-7281,False,48,P2,48,22,38,19,15,17,20
16,17,L20-12559,False,22,P6,16,15,15,14,22,18,16
17,18,L20-7152,False,43,P3,22,43,23,25,20,25,17
18,19,L20-12592,False,29,P3,18,29,28,24,18,23,18
19,20,L20-6880,False,39,P2,39,32,16,20,21,27,35

====================================================================================================
Largest rank-collapse examples among the P1 top-20 label-specific features
====================================================================================================

,label_word,P1_baseline_rank,feature,stable_by_rule,worst_prefix_P2_to_P8,worst_rank_P2_to_P8,rank_collapse,P1_rank,P2_rank,P3_rank,P4_rank,P5_rank,P6_rank,P7_rank,P8_rank
0,World,11,L20-1295,False,P4,43,32,11,11,14,43,10,10,13,9
1,Technology,16,L20-7281,False,P2,48,32,16,48,22,38,19,15,17,20
2,Sports,18,L20-7502,False,P7,47,29,18,21,41,37,26,23,47,20
3,Sports,19,L20-2572,False,P7,46,27,19,19,28,33,19,14,46,16
4,Technology,18,L20-7152,False,P3,43,25,18,22,43,23,25,20,25,17
5,Technology,20,L20-6880,False,P2,39,19,20,39,32,16,20,21,27,35
6,World,12,L20-6211,False,P7,25,13,12,17,17,17,15,16,25,12
7,Business,18,L20-9009,False,P4,29,11,18,21,25,29,17,21,22,19
8,Technology,19,L20-12592,False,P3,29,10,19,18,29,28,24,18,23,18
9,Technology,12,L20-8551,False,P4,21,9,12,14,13,21,12,13,14,14
10,World,16,L20-8386,False,P5,23,7,16,14,15,14,23,21,18,17
11,Sports,17,L20-11476,False,P7,24,7,17,15,21,18,20,19,24,21
12,Technology,15,L20-5131,False,P7,21,6,15,11,16,14,16,17,21,15
13,Business,19,L20-44,False,P6,24,5,19,18,20,21,18,24,19,20
14,World,15,L20-13051,True,P3,20,5,15,18,20,15,16,18,15,16
15,World,10,L20-5743,True,P6,15,5,10,12,10,10,11,15,12,11
16,Technology,17,L20-12559,False,P6,22,5,17,16,15,15,14,22,18,16
17,World,18,L20-2221,False,P7,23,5,18,16,22,18,19,19,23,18
18,Sports,10,L20-3375,True,P6,15,5,10,9,12,14,10,15,9,10
19,World,17,L20-3648,False,P2,22,5,17,22,21,21,18,20,16,21

In [9]:

# ============================================================
# 6. Plotly diagnostics and heatmaps
# ============================================================

summary = {
    "model": MODEL_SHORT_NAME,
    "target_layer": TARGET_LAYER,
    "n_queries": N_QUERY_TOTAL,
    "n_prefix_variants": N_PREFIX_VARIANTS,
    "label_specific_top_n_per_label": LABEL_SPECIFIC_TOP_N,
    "retention_top_k": RETENTION_TOP_K,
    "stable_min_retention": STABLE_MIN_RETENTION,
    "stable_min_baseline_ratio": STABLE_MIN_BASELINE_RATIO,
    "query_analysis_positions": query_analysis_positions,
    "stable_count": int(label_specific_stability_df["stable_by_rule"].sum()),
    "sensitive_count": int((~label_specific_stability_df["stable_by_rule"]).sum()),
}
print(json.dumps(summary, indent=2))

# Per-variant final-demo label distribution. This checks whether variant index itself is label-confounded.
variant_label_counts = pd.crosstab(meta_df["variant_idx"], meta_df["final_demo_label_word"])
print("Final-demo label counts by variant index:")
display(variant_label_counts)

fig_counts = px.imshow(
    variant_label_counts,
    text_auto=True,
    aspect="auto",
    title="Final-demo label counts by prefix-variant index",
    labels=dict(x="Final-demo label", y="Variant index", color="count"),
)
fig_counts.show()


def plot_label_specific_heatmap(lab: int, normalize_to_baseline: bool = False):
    """Plot top label-specific features for one label across final-demo variants."""
    feature_ids = label_top_features[int(lab)]
    mat = label_specific_pre_gap[int(lab), :, feature_ids].T  # [features, variants]
    if normalize_to_baseline:
        denom = np.abs(mat[:, [0]]) + 1e-12
        mat_to_plot = mat / denom
        colorbar_title = "pre-gap / |baseline gap|"
        title_suffix = "ratio to baseline"
    else:
        mat_to_plot = mat
        colorbar_title = "label-specific preactivation gap"
        title_suffix = "raw gap"

    y_labels = [f"L{TARGET_LAYER}-{int(f)}" for f in feature_ids]
    x_labels = [f"v{v}" for v in range(N_PREFIX_VARIANTS)]
    fig = go.Figure(
        data=go.Heatmap(
            z=mat_to_plot,
            x=x_labels,
            y=y_labels,
            colorscale="RdBu",
            reversescale=True,
            zmid=0.0,
            colorbar=dict(title=colorbar_title),
            hovertemplate=(
                "feature=%{y}<br>variant=%{x}<br>"
                + colorbar_title
                + "=%{z:.4f}<extra></extra>"
            ),
        )
    )
    fig.update_layout(
        title=f"{label_to_words_agnews[int(lab)]}: top-{LABEL_SPECIFIC_TOP_N} label-specific features across final-demo variants ({title_suffix})",
        xaxis_title="Final-demo prefix variant",
        yaxis_title="SAE feature",
        height=max(450, 26 * len(feature_ids) + 180),
        width=max(850, 80 * N_PREFIX_VARIANTS + 350),
    )
    fig.show()


for lab in range(NUM_LABELS):
    plot_label_specific_heatmap(lab, normalize_to_baseline=False)

# Optional normalized heatmaps. These are useful for visually identifying LFH-sensitive features.
for lab in range(NUM_LABELS):
    plot_label_specific_heatmap(lab, normalize_to_baseline=True)

# Retention plot for all selected label-specific features.
fig_retention = px.scatter(
    label_specific_stability_df,
    x="label_specific_rank",
    y=f"retention_rate_top_{RETENTION_TOP_K}",
    color="label_word",
    symbol="stable_by_rule",
    hover_data=[
        "feature_idx",
        "baseline_label_specific_pre_gap",
        "min_over_baseline",
        "worst_variant_rank",
        "best_variant_rank",
    ],
    title=f"Single-prefix label-specific rank versus multi-prefix retention in top-{RETENTION_TOP_K}",
    labels={
        "label_specific_rank": "Original single-prefix label-specific rank",
        f"retention_rate_top_{RETENTION_TOP_K}": f"Retention rate in top-{RETENTION_TOP_K}",
        "label_word": "Gold label",
    },
)
fig_retention.add_hline(y=STABLE_MIN_RETENTION, line_dash="dash")
fig_retention.update_layout(height=500, width=900)
fig_retention.show()

# Gap range plot: how much the label-specific score moves when only the final demo changes.
fig_range = px.scatter(
    label_specific_stability_df,
    x="baseline_label_specific_pre_gap",
    y="range_label_specific_pre_gap_across_prefixes",
    color="label_word",
    symbol="stable_by_rule",
    hover_data=["feature_idx", "label_specific_rank", "min_over_baseline", f"retention_rate_top_{RETENTION_TOP_K}"],
    title="Label-specific preactivation gap instability under final-demo variation",
    labels={
        "baseline_label_specific_pre_gap": "Baseline label-specific preactivation gap",
        "range_label_specific_pre_gap_across_prefixes": "Range of gap across prefix variants",
        "label_word": "Gold label",
    },
)
fig_range.update_layout(height=500, width=900)
fig_range.show()

{
  "model": "Gemma2-9B-IT",
  "target_layer": 20,
  "n_queries": 100,
  "n_prefix_variants": 8,
  "label_specific_top_n_per_label": 20,
  "retention_top_k": 20,
  "stable_min_retention": 0.9,
  "stable_min_baseline_ratio": 0.5,
  "query_analysis_positions": [
    -2
  ],
  "stable_count": 61,
  "sensitive_count": 19
}
Final-demo label counts by variant index:

final_demo_label_word  Business  Sports  Technology  World
variant_idx
0                            24      19          31     26
1                            29      26          27     18
2                            29      23          20     28
3                            23      26          27     24
4                            24      26          24     26
5                            29      29          23     19
6                            23      29          22     26
7                            19      22          26     33


# 8. Causal validation: are multi-prefix-stable label features more causally relevant?

This section tests the hypothesis behind the LFH-aware stability filter:

- **Stable group:** label-specific features that remain label-specific across final-demo variants.
- **LFH-sensitive group:** label-specific features that looked strong under the original single-prefix prompt but failed the multi-prefix stability rule.

For every selected `(label, feature)` pair, we evaluate prompts whose gold query label is that label and intervene at the same query-token positions used for feature measurement.

Two interventions are run:

1. **Active-feature ablation:** when the feature is active at an edited token, subtract its current SAE reconstruction contribution:
   `hidden <- hidden - activation_f * W_dec[f]`.
2. **Feature amplification:** add the feature decoder direction with the current value of `CAUSAL_AMPLIFICATION_ALPHA`:
   `hidden <- hidden + CAUSAL_AMPLIFICATION_ALPHA * W_dec[f]`.

The outcome is the model's next-token probability for the gold label, normalized over the four AGNews label tokens. The main quantities are:

- `ablation_decrease_p_label = baseline P(L) - ablated P(L)`; larger is stronger causal support for the label.
- `amplification_increase_p_label = amplified P(L) - baseline P(L)`; larger is stronger causal support for the label.

In [10]:

# ============================================================
# 8. Causal validation of stable versus LFH-sensitive features
# ============================================================

# Causal validation settings.
# By default this evaluates all 80 selected label-feature pairs: top-20 per AGNews label.
CAUSAL_MAX_PAIRS = None          # None = all selected pairs; set e.g. 8 for a quick smoke test
CAUSAL_BATCH_SIZE = BATCH_SIZE   # reduce if you hit memory limits
CAUSAL_AMPLIFICATION_ALPHA = 50.0  # coarse preliminary setting from the attached candidate notebook
CAUSAL_BOOTSTRAP_SAMPLES = 2000

# The causal outcome is P(label) normalized over the four label words. This is usually the
# most interpretable probability for a classification prompt.
CAUSAL_PROBABILITY_MODE = "label_conditional"  # fixed in this cell

print("CAUSAL_MAX_PAIRS:", CAUSAL_MAX_PAIRS)
print("CAUSAL_BATCH_SIZE:", CAUSAL_BATCH_SIZE)
print("CAUSAL_AMPLIFICATION_ALPHA:", CAUSAL_AMPLIFICATION_ALPHA)
print("CAUSAL_PROBABILITY_MODE:", CAUSAL_PROBABILITY_MODE)


def get_single_token_label_ids():
    """Return one tokenizer id per AGNews label word, with sanity checks."""
    label_ids = []
    rows = []
    for lab in range(NUM_LABELS):
        word = label_to_words_agnews[lab]
        ids = tokenizer(word, add_special_tokens=False)["input_ids"]
        rows.append({"label": lab, "label_word": word, "token_ids": ids, "n_tokens": len(ids)})
        if len(ids) != 1:
            raise ValueError(
                f"Label word {word!r} tokenized into {len(ids)} tokens: {ids}. "
                "This causal cell expects single-token labels."
            )
        label_ids.append(int(ids[0]))
    display(pd.DataFrame(rows))
    return label_ids


LABEL_TOKEN_IDS = get_single_token_label_ids()
LABEL_TOKEN_IDS_TENSOR = torch.tensor(LABEL_TOKEN_IDS, dtype=torch.long, device=get_model_input_device(model))


def label_conditional_probs_from_logits(logits: torch.Tensor) -> torch.Tensor:
    """
    Return P(label) normalized over the four AGNews label tokens.

    logits: [B, S, vocab]. We use logits at the final prompt token to score the next token.
    Returns: [B, NUM_LABELS].
    """
    label_token_ids = LABEL_TOKEN_IDS_TENSOR.to(logits.device)
    next_logits = logits[:, -1, :].float()
    label_logits = next_logits[:, label_token_ids]
    return torch.softmax(label_logits, dim=-1)


@torch.no_grad()
def collect_baseline_label_probs(prompts, batch_size: int = CAUSAL_BATCH_SIZE):
    """Collect baseline next-token P(label), normalized across the four label tokens, for every prompt."""
    model_device = get_model_input_device(model)
    probs = np.zeros((len(prompts), NUM_LABELS), dtype=np.float32)
    model.eval()

    for start in range(0, len(prompts), batch_size):
        end = min(start + batch_size, len(prompts))
        enc = tokenizer(
            prompts[start:end],
            padding=True,
            return_tensors="pt",
            add_special_tokens=False,
        )
        input_ids = enc["input_ids"].to(model_device)
        attention_mask = enc["attention_mask"].to(model_device)

        out = model(input_ids=input_ids, attention_mask=attention_mask, use_cache=False)
        label_probs = label_conditional_probs_from_logits(out.logits)
        probs[start:end] = label_probs.detach().cpu().numpy()

        del out, input_ids, attention_mask, enc, label_probs
        print(f"Baseline probabilities: {end}/{len(prompts)}")

    return probs


baseline_label_probs_by_prompt = collect_baseline_label_probs(prompts)
print("baseline_label_probs_by_prompt:", baseline_label_probs_by_prompt.shape)


# Build the label-feature pairs to test. Each row corresponds to the same pair used in the
# stability table, so duplicated feature ids across labels are intentionally retained.
causal_pairs_df = label_specific_stability_df.copy().reset_index(drop=False).rename(columns={"index": "pair_id"})
if CAUSAL_MAX_PAIRS is not None:
    # Balanced quick mode: take from stable and sensitive groups separately when possible.
    stable_part = causal_pairs_df[causal_pairs_df["stable_by_rule"]].head(int(CAUSAL_MAX_PAIRS) // 2)
    sensitive_part = causal_pairs_df[~causal_pairs_df["stable_by_rule"]].head(int(CAUSAL_MAX_PAIRS) - len(stable_part))
    causal_pairs_df = pd.concat([stable_part, sensitive_part], ignore_index=True)

causal_pairs_df["causal_group"] = np.where(causal_pairs_df["stable_by_rule"], "multi-prefix stable", "LFH-sensitive")
print("Causal pairs to test:", len(causal_pairs_df))
display(causal_pairs_df[[
    "pair_id", "label_word", "feature_idx", "label_specific_rank", "stable_by_rule",
    "baseline_label_specific_pre_gap", f"retention_rate_top_{RETENTION_TOP_K}", "min_over_baseline", "worst_variant_rank"
]])


# Construct one intervention instance per (label-feature pair, prompt whose query label matches that label).
instance_rows = []
for _, pair in causal_pairs_df.iterrows():
    lab = int(pair["label"])
    feat = int(pair["feature_idx"])
    pair_id = int(pair["pair_id"])
    prompt_indices_for_label = meta_df.index[meta_df["query_label"].to_numpy(dtype=np.int64) == lab].to_numpy(dtype=np.int64)
    for prompt_idx in prompt_indices_for_label:
        meta = prompt_metadata[int(prompt_idx)]
        instance_rows.append({
            "pair_id": pair_id,
            "prompt_idx": int(prompt_idx),
            "query_local_idx": int(meta["query_local_idx"]),
            "variant_idx": int(meta["variant_idx"]),
            "label": lab,
            "label_word": label_to_words_agnews[lab],
            "feature_idx": feat,
        })

causal_instances_df = pd.DataFrame(instance_rows)
print("Causal intervention instances:", len(causal_instances_df))
display(causal_instances_df.head())


def _selected_padded_positions_for_batch(batch_meta, attention_mask, batch_seq_len: int):
    """Convert saved unpadded selected query positions into padded batch positions."""
    selected_positions_by_row = []
    for b, meta in enumerate(batch_meta):
        unpadded_len = int(attention_mask[b].sum().item())
        pad_shift = int(batch_seq_len - unpadded_len)
        positions = [pad_shift + int(pos) for pos in meta["selected_query_token_positions"]]
        positions = [pos for pos in positions if 0 <= pos < batch_seq_len]
        if not positions:
            raise RuntimeError("No valid selected token positions after padding adjustment.")
        selected_positions_by_row.append(positions)
    return selected_positions_by_row


@torch.no_grad()
def collect_intervened_gold_label_probs(instances_df: pd.DataFrame, mode: str, batch_size: int = CAUSAL_BATCH_SIZE):
    """
    Run feature-level interventions for prompt-feature instances.

    mode:
      - 'ablate_active': subtract current post-activation_f * W_dec[f] on selected query tokens.
      - 'amplify': add CAUSAL_AMPLIFICATION_ALPHA * W_dec[f] on selected query tokens.

    Returns: [n_instances] containing P(gold label) after intervention.
    """
    if mode not in {"ablate_active", "amplify"}:
        raise ValueError(f"Unknown intervention mode: {mode}")

    n = len(instances_df)
    gold_probs = np.zeros(n, dtype=np.float32)
    model_device = get_model_input_device(model)
    block = model.get_submodule(f"model.layers.{TARGET_LAYER}")
    model.eval()
    sae.eval()

    for start in range(0, n, batch_size):
        end = min(start + batch_size, n)
        batch_rows = instances_df.iloc[start:end]
        batch_prompt_indices = batch_rows["prompt_idx"].to_numpy(dtype=np.int64)
        batch_prompts = [prompts[int(i)] for i in batch_prompt_indices]
        batch_meta = [prompt_metadata[int(i)] for i in batch_prompt_indices]
        batch_features = batch_rows["feature_idx"].to_numpy(dtype=np.int64)
        batch_labels = batch_rows["label"].to_numpy(dtype=np.int64)

        enc = tokenizer(
            batch_prompts,
            padding=True,
            return_tensors="pt",
            add_special_tokens=False,
        )
        input_ids = enc["input_ids"].to(model_device)
        attention_mask = enc["attention_mask"].to(model_device)
        batch_seq_len = int(input_ids.shape[1])
        selected_positions_by_row = _selected_padded_positions_for_batch(batch_meta, attention_mask, batch_seq_len)

        def hook_fn(module, inputs, output):
            hidden = output[0] if isinstance(output, tuple) else output
            hidden_mod = hidden.clone()
            hidden_device = hidden_mod.device
            hidden_dtype = hidden_mod.dtype

            for b, feat in enumerate(batch_features):
                feat = int(feat)
                pos = selected_positions_by_row[b]
                x = hidden[b, pos, :]
                decoder_dir = sae.W_dec[feat].to(device=hidden_device, dtype=hidden_dtype)

                if mode == "ablate_active":
                    # Compute the current SAE post-activation and remove only the active contribution.
                    pre = sae_encode_pre_for_positions(hidden[b], pos)
                    post = sae.activation_fn(pre.to(dtype=sae.dtype)).float()
                    coeff = post[:, feat].to(device=hidden_device, dtype=hidden_dtype)
                    hidden_mod[b, pos, :] = hidden_mod[b, pos, :] - coeff[:, None] * decoder_dir[None, :]
                elif mode == "amplify":
                    hidden_mod[b, pos, :] = hidden_mod[b, pos, :] + float(CAUSAL_AMPLIFICATION_ALPHA) * decoder_dir[None, :]

            if isinstance(output, tuple):
                return (hidden_mod,) + output[1:]
            return hidden_mod

        handle = block.register_forward_hook(hook_fn)
        try:
            out = model(input_ids=input_ids, attention_mask=attention_mask, use_cache=False)
        finally:
            handle.remove()

        label_probs = label_conditional_probs_from_logits(out.logits).detach().cpu().numpy()
        gold_probs[start:end] = label_probs[np.arange(end - start), batch_labels]

        del out, input_ids, attention_mask, enc, label_probs
        print(f"{mode}: {end}/{n}")

    return gold_probs


# Baseline summaries per pair using the same prompt subset as each intervention.
baseline_rows = []
for _, pair in causal_pairs_df.iterrows():
    pair_id = int(pair["pair_id"])
    lab = int(pair["label"])
    feat = int(pair["feature_idx"])
    prompt_indices = causal_instances_df.loc[causal_instances_df["pair_id"] == pair_id, "prompt_idx"].to_numpy(dtype=np.int64)

    baseline_gold = baseline_label_probs_by_prompt[prompt_indices, lab]
    feature_freq = freq_by_prompt[prompt_indices, feat]
    feature_post = post_by_prompt[prompt_indices, feat]
    feature_pre = pre_by_prompt[prompt_indices, feat]

    baseline_rows.append({
        "pair_id": pair_id,
        "baseline_mean_p_label": float(np.mean(baseline_gold)),
        "baseline_median_p_label": float(np.median(baseline_gold)),
        "n_prompts_for_label": int(len(prompt_indices)),
        "feature_active_prompt_fraction": float(np.mean(feature_freq > 0)),
        "mean_feature_preactivation_on_gold_label_prompts": float(np.mean(feature_pre)),
        "mean_feature_postactivation_on_gold_label_prompts": float(np.mean(feature_post)),
    })

baseline_pair_df = pd.DataFrame(baseline_rows)

# Run the two causal interventions.
ablation_gold_probs = collect_intervened_gold_label_probs(causal_instances_df, mode="ablate_active")
amplified_gold_probs = collect_intervened_gold_label_probs(causal_instances_df, mode="amplify")

causal_instances_df = causal_instances_df.copy()
causal_instances_df["baseline_p_label"] = baseline_label_probs_by_prompt[
    causal_instances_df["prompt_idx"].to_numpy(dtype=np.int64),
    causal_instances_df["label"].to_numpy(dtype=np.int64),
]
causal_instances_df["ablated_p_label"] = ablation_gold_probs
causal_instances_df["amplified_p_label"] = amplified_gold_probs
causal_instances_df["ablation_decrease_p_label"] = causal_instances_df["baseline_p_label"] - causal_instances_df["ablated_p_label"]
causal_instances_df["amplification_increase_p_label"] = causal_instances_df["amplified_p_label"] - causal_instances_df["baseline_p_label"]

# Aggregate intervention effects per label-feature pair.
causal_pair_effects_df = (
    causal_instances_df
    .groupby("pair_id")
    .agg(
        ablated_mean_p_label=("ablated_p_label", "mean"),
        amplified_mean_p_label=("amplified_p_label", "mean"),
        mean_ablation_decrease_p_label=("ablation_decrease_p_label", "mean"),
        median_ablation_decrease_p_label=("ablation_decrease_p_label", "median"),
        mean_amplification_increase_p_label=("amplification_increase_p_label", "mean"),
        median_amplification_increase_p_label=("amplification_increase_p_label", "median"),
        frac_prompts_ablation_decreases_p_label=("ablation_decrease_p_label", lambda x: float(np.mean(np.asarray(x) > 0))),
        frac_prompts_amplification_increases_p_label=("amplification_increase_p_label", lambda x: float(np.mean(np.asarray(x) > 0))),
    )
    .reset_index()
)

causal_validation_df = (
    causal_pairs_df
    .merge(baseline_pair_df, on="pair_id", how="left")
    .merge(causal_pair_effects_df, on="pair_id", how="left")
)

# Convenience columns for reading.
causal_validation_df["ablation_decrease_pp"] = 100.0 * causal_validation_df["mean_ablation_decrease_p_label"]
causal_validation_df["amplification_increase_pp"] = 100.0 * causal_validation_df["mean_amplification_increase_p_label"]
causal_validation_df["baseline_p_label_pct"] = 100.0 * causal_validation_df["baseline_mean_p_label"]
causal_validation_df["ablated_p_label_pct"] = 100.0 * causal_validation_df["ablated_mean_p_label"]
causal_validation_df["amplified_p_label_pct"] = 100.0 * causal_validation_df["amplified_mean_p_label"]

print("Causal validation per label-feature pair:")
display(causal_validation_df[[
    "label_word", "feature_idx", "label_specific_rank", "stable_by_rule", "causal_group",
    "baseline_label_specific_pre_gap", f"retention_rate_top_{RETENTION_TOP_K}", "min_over_baseline",
    "feature_active_prompt_fraction", "baseline_p_label_pct", "ablated_p_label_pct", "amplified_p_label_pct",
    "ablation_decrease_pp", "amplification_increase_pp",
    "frac_prompts_ablation_decreases_p_label", "frac_prompts_amplification_increases_p_label",
]].sort_values(["stable_by_rule", "label_word", "label_specific_rank"], ascending=[False, True, True]))


def bootstrap_mean_ci(values, n_boot: int = CAUSAL_BOOTSTRAP_SAMPLES, seed: int = seed, ci: float = 0.95):
    vals = np.asarray(values, dtype=np.float64)
    vals = vals[np.isfinite(vals)]
    if vals.size == 0:
        return np.nan, np.nan, np.nan
    mean = float(vals.mean())
    if vals.size == 1 or n_boot <= 0:
        return mean, np.nan, np.nan
    rng_boot = np.random.default_rng(seed)
    draws = rng_boot.choice(vals, size=(int(n_boot), vals.size), replace=True).mean(axis=1)
    lo = float(np.quantile(draws, (1.0 - ci) / 2.0))
    hi = float(np.quantile(draws, 1.0 - (1.0 - ci) / 2.0))
    return mean, lo, hi


group_rows = []
for stable_value, group_name in [(True, "multi-prefix stable"), (False, "LFH-sensitive")]:
    g = causal_validation_df[causal_validation_df["stable_by_rule"] == stable_value]
    row = {
        "causal_group": group_name,
        "n_label_feature_pairs": int(len(g)),
        "mean_active_prompt_fraction": float(g["feature_active_prompt_fraction"].mean()) if len(g) else np.nan,
        "median_active_prompt_fraction": float(g["feature_active_prompt_fraction"].median()) if len(g) else np.nan,
    }
    for metric, label in [
        ("mean_ablation_decrease_p_label", "ablation_decrease"),
        ("mean_amplification_increase_p_label", "amplification_increase"),
    ]:
        mean, lo, hi = bootstrap_mean_ci(g[metric].to_numpy(), seed=seed + (1 if stable_value else 2))
        row[f"mean_{label}"] = mean
        row[f"mean_{label}_ci_low"] = lo
        row[f"mean_{label}_ci_high"] = hi
        row[f"mean_{label}_pp"] = 100.0 * mean if np.isfinite(mean) else np.nan
        row[f"mean_{label}_ci_low_pp"] = 100.0 * lo if np.isfinite(lo) else np.nan
        row[f"mean_{label}_ci_high_pp"] = 100.0 * hi if np.isfinite(hi) else np.nan
    group_rows.append(row)

causal_group_summary_df = pd.DataFrame(group_rows)
print("Stable versus LFH-sensitive causal summary:")
display(causal_group_summary_df)

# Label-level group summary, useful for finding whether one label dominates the comparison.
label_group_summary_df = (
    causal_validation_df
    .groupby(["label_word", "causal_group"])
    .agg(
        n_label_feature_pairs=("feature_idx", "count"),
        mean_ablation_decrease_pp=("ablation_decrease_pp", "mean"),
        mean_amplification_increase_pp=("amplification_increase_pp", "mean"),
        mean_active_prompt_fraction=("feature_active_prompt_fraction", "mean"),
    )
    .reset_index()
)
print("Per-label stable/sensitive causal summary:")
display(label_group_summary_df)

# Plotly comparison: ablation and amplification effects by stability group.
plot_df = causal_validation_df.copy()
plot_df["stability_group"] = np.where(plot_df["stable_by_rule"], "multi-prefix stable", "LFH-sensitive")

fig_ablation = px.box(
    plot_df,
    x="stability_group",
    y="ablation_decrease_pp",
    color="label_word",
    points="all",
    hover_data=["feature_idx", "label_specific_rank", "feature_active_prompt_fraction", f"retention_rate_top_{RETENTION_TOP_K}", "min_over_baseline"],
    title="Feature ablation: decrease in gold-label probability by multi-prefix stability group",
    labels={
        "stability_group": "Feature group",
        "ablation_decrease_pp": "Baseline P(L) - ablated P(L), percentage points",
        "label_word": "Gold label",
    },
)
fig_ablation.add_hline(y=0.0, line_dash="dash")
fig_ablation.update_layout(height=550, width=950)
fig_ablation.show()

fig_amplification = px.box(
    plot_df,
    x="stability_group",
    y="amplification_increase_pp",
    color="label_word",
    points="all",
    hover_data=["feature_idx", "label_specific_rank", "feature_active_prompt_fraction", f"retention_rate_top_{RETENTION_TOP_K}", "min_over_baseline"],
    title=f"Feature amplification (alpha={CAUSAL_AMPLIFICATION_ALPHA:g}): increase in gold-label probability by stability group",
    labels={
        "stability_group": "Feature group",
        "amplification_increase_pp": "Amplified P(L) - baseline P(L), percentage points",
        "label_word": "Gold label",
    },
)
fig_amplification.add_hline(y=0.0, line_dash="dash")
fig_amplification.update_layout(height=550, width=950)
fig_amplification.show()

# Scatter: stability score versus causal effect. Ideally, more stable features have stronger causal effects.
fig_scatter = px.scatter(
    plot_df,
    x=f"retention_rate_top_{RETENTION_TOP_K}",
    y="ablation_decrease_pp",
    color="label_word",
    symbol="stable_by_rule",
    size="feature_active_prompt_fraction",
    hover_data=["feature_idx", "label_specific_rank", "amplification_increase_pp", "min_over_baseline", "worst_variant_rank"],
    title="Does multi-prefix retention predict feature-ablation causal relevance?",
    labels={
        f"retention_rate_top_{RETENTION_TOP_K}": f"Retention rate in top-{RETENTION_TOP_K}",
        "ablation_decrease_pp": "Ablation decrease in P(L), percentage points",
        "label_word": "Gold label",
    },
)
fig_scatter.add_hline(y=0.0, line_dash="dash")
fig_scatter.add_vline(x=STABLE_MIN_RETENTION, line_dash="dash")
fig_scatter.update_layout(height=550, width=950)
fig_scatter.show()

# Compact interpretation helper.
stable_mean_ablate = causal_group_summary_df.loc[causal_group_summary_df["causal_group"] == "multi-prefix stable", "mean_ablation_decrease_pp"].iloc[0]
sens_mean_ablate = causal_group_summary_df.loc[causal_group_summary_df["causal_group"] == "LFH-sensitive", "mean_ablation_decrease_pp"].iloc[0]
stable_mean_amp = causal_group_summary_df.loc[causal_group_summary_df["causal_group"] == "multi-prefix stable", "mean_amplification_increase_pp"].iloc[0]
sens_mean_amp = causal_group_summary_df.loc[causal_group_summary_df["causal_group"] == "LFH-sensitive", "mean_amplification_increase_pp"].iloc[0]

print("=" * 100)
print("Quick readout")
print("=" * 100)
print(f"Mean ablation decrease, stable group:      {stable_mean_ablate:.4f} percentage points")
print(f"Mean ablation decrease, LFH-sensitive:     {sens_mean_ablate:.4f} percentage points")
print(f"Mean amplification increase, stable group: {stable_mean_amp:.4f} percentage points")
print(f"Mean amplification increase, sensitive:    {sens_mean_amp:.4f} percentage points")
print()
if stable_mean_ablate > sens_mean_ablate and stable_mean_amp > sens_mean_amp:
    print("Pattern matches the ideal validation: multi-prefix-stable features are more causally relevant on both tests.")
elif stable_mean_ablate > sens_mean_ablate or stable_mean_amp > sens_mean_amp:
    print("Pattern is partially supportive: stable features are stronger on one causal test but not both.")
else:
    print("Pattern is not supportive under this run/settings; inspect label-wise summaries and active fractions.")

CAUSAL_MAX_PAIRS: None
CAUSAL_BATCH_SIZE: 2
CAUSAL_AMPLIFICATION_ALPHA: 50.0
CAUSAL_PROBABILITY_MODE: label_conditional

   label  label_word token_ids  n_tokens
0      0       World   [10772]         1
1      1      Sports   [27093]         1
2      2    Business   [14103]         1
3      3  Technology   [39364]         1

Baseline probabilities: 2/800
Baseline probabilities: 4/800
Baseline probabilities: 6/800
Baseline probabilities: 8/800
Baseline probabilities: 10/800
Baseline probabilities: 12/800
Baseline probabilities: 14/800
Baseline probabilities: 16/800
Baseline probabilities: 18/800
Baseline probabilities: 20/800
Baseline probabilities: 22/800
Baseline probabilities: 24/800
Baseline probabilities: 26/800
Baseline probabilities: 28/800
Baseline probabilities: 30/800
Baseline probabilities: 32/800
Baseline probabilities: 34/800
Baseline probabilities: 36/800
Baseline probabilities: 38/800
Baseline probabilities: 40/800
Baseline probabilities: 42/800
Baseline probabilities: 44/800
Baseline probabilities: 46/800
Baseline probabilities: 48/800
Baseline probabilities: 50/800
Baseline probabilities: 52/800
Baseline probabilities: 54/800
Baseline probabilities: 56/800
Baseline probabilities: 58/800
Baseline probabilities: 60/800
Baseline probabilities: 62/800
Baseline probabilities: 64/800
Baseline probabilities: 66/800
Baseline probabilities: 68/800
Baseline probabilities: 70/800
Baseline probabilities: 72/800
Baseline probabilities: 74/800
Baseline probabilities: 76/800
Baseline probabilities: 78/800
Baseline probabilities: 80/800
Baseline probabilities: 82/800
Baseline probabilities: 84/800
Baseline probabilities: 86/800
Baseline probabilities: 88/800
Baseline probabilities: 90/800
Baseline probabilities: 92/800
Baseline probabilities: 94/800
Baseline probabilities: 96/800
Baseline probabilities: 98/800
Baseline probabilities: 100/800
Baseline probabilities: 102/800
Baseline probabilities: 104/800
Baseline probabilities: 106/800
Baseline probabilities: 108/800
Baseline probabilities: 110/800
Baseline probabilities: 112/800
Baseline probabilities: 114/800
Baseline probabilities: 116/800
Baseline probabilities: 118/800
Baseline probabilities: 120/800
Baseline probabilities: 122/800
Baseline probabilities: 124/800
Baseline probabilities: 126/800
Baseline probabilities: 128/800
Baseline probabilities: 130/800
Baseline probabilities: 132/800
Baseline probabilities: 134/800
Baseline probabilities: 136/800
Baseline probabilities: 138/800
Baseline probabilities: 140/800
Baseline probabilities: 142/800
Baseline probabilities: 144/800
Baseline probabilities: 146/800
Baseline probabilities: 148/800
Baseline probabilities: 150/800
Baseline probabilities: 152/800
Baseline probabilities: 154/800
Baseline probabilities: 156/800
Baseline probabilities: 158/800
Baseline probabilities: 160/800
Baseline probabilities: 162/800
Baseline probabilities: 164/800
Baseline probabilities: 166/800
Baseline probabilities: 168/800
Baseline probabilities: 170/800
Baseline probabilities: 172/800
Baseline probabilities: 174/800
Baseline probabilities: 176/800
Baseline probabilities: 178/800
Baseline probabilities: 180/800
Baseline probabilities: 182/800
Baseline probabilities: 184/800
Baseline probabilities: 186/800
Baseline probabilities: 188/800
Baseline probabilities: 190/800
Baseline probabilities: 192/800
Baseline probabilities: 194/800
Baseline probabilities: 196/800
Baseline probabilities: 198/800
Baseline probabilities: 200/800
Baseline probabilities: 202/800
Baseline probabilities: 204/800
Baseline probabilities: 206/800
Baseline probabilities: 208/800
Baseline probabilities: 210/800
Baseline probabilities: 212/800
Baseline probabilities: 214/800
Baseline probabilities: 216/800
Baseline probabilities: 218/800
Baseline probabilities: 220/800
Baseline probabilities: 222/800
Baseline probabilities: 224/800
Baseline probabilities: 226/800
Baseline probabilities: 228/800
Baseline probabilities: 230/800
Baseline probabilities: 232/800
Baseline probabilities: 234/800
Baseline probabilities: 236/800
Baseline probabilities: 238/800
Baseline probabilities: 240/800
Baseline probabilities: 242/800
Baseline probabilities: 244/800
Baseline probabilities: 246/800
Baseline probabilities: 248/800
Baseline probabilities: 250/800
Baseline probabilities: 252/800
Baseline probabilities: 254/800
Baseline probabilities: 256/800
Baseline probabilities: 258/800
Baseline probabilities: 260/800
Baseline probabilities: 262/800
Baseline probabilities: 264/800
Baseline probabilities: 266/800
Baseline probabilities: 268/800
Baseline probabilities: 270/800
Baseline probabilities: 272/800
Baseline probabilities: 274/800
Baseline probabilities: 276/800
Baseline probabilities: 278/800
Baseline probabilities: 280/800
Baseline probabilities: 282/800
Baseline probabilities: 284/800
Baseline probabilities: 286/800
Baseline probabilities: 288/800
Baseline probabilities: 290/800
Baseline probabilities: 292/800
Baseline probabilities: 294/800
Baseline probabilities: 296/800
Baseline probabilities: 298/800
Baseline probabilities: 300/800
Baseline probabilities: 302/800
Baseline probabilities: 304/800
Baseline probabilities: 306/800
Baseline probabilities: 308/800
Baseline probabilities: 310/800
Baseline probabilities: 312/800
Baseline probabilities: 314/800
Baseline probabilities: 316/800
Baseline probabilities: 318/800
Baseline probabilities: 320/800
Baseline probabilities: 322/800
Baseline probabilities: 324/800
Baseline probabilities: 326/800
Baseline probabilities: 328/800
Baseline probabilities: 330/800
Baseline probabilities: 332/800
Baseline probabilities: 334/800
Baseline probabilities: 336/800
Baseline probabilities: 338/800
Baseline probabilities: 340/800
Baseline probabilities: 342/800
Baseline probabilities: 344/800
Baseline probabilities: 346/800
Baseline probabilities: 348/800
Baseline probabilities: 350/800
Baseline probabilities: 352/800
Baseline probabilities: 354/800
Baseline probabilities: 356/800
Baseline probabilities: 358/800
Baseline probabilities: 360/800
Baseline probabilities: 362/800
Baseline probabilities: 364/800
Baseline probabilities: 366/800
Baseline probabilities: 368/800
Baseline probabilities: 370/800
Baseline probabilities: 372/800
Baseline probabilities: 374/800
Baseline probabilities: 376/800
Baseline probabilities: 378/800
Baseline probabilities: 380/800
Baseline probabilities: 382/800
Baseline probabilities: 384/800
Baseline probabilities: 386/800
Baseline probabilities: 388/800
Baseline probabilities: 390/800
Baseline probabilities: 392/800
Baseline probabilities: 394/800
Baseline probabilities: 396/800
Baseline probabilities: 398/800
Baseline probabilities: 400/800
Baseline probabilities: 402/800
Baseline probabilities: 404/800
Baseline probabilities: 406/800
Baseline probabilities: 408/800
Baseline probabilities: 410/800
Baseline probabilities: 412/800
Baseline probabilities: 414/800
Baseline probabilities: 416/800
Baseline probabilities: 418/800
Baseline probabilities: 420/800
Baseline probabilities: 422/800
Baseline probabilities: 424/800
Baseline probabilities: 426/800
Baseline probabilities: 428/800
Baseline probabilities: 430/800
Baseline probabilities: 432/800
Baseline probabilities: 434/800
Baseline probabilities: 436/800
Baseline probabilities: 438/800
Baseline probabilities: 440/800
Baseline probabilities: 442/800
Baseline probabilities: 444/800
Baseline probabilities: 446/800
Baseline probabilities: 448/800
Baseline probabilities: 450/800
Baseline probabilities: 452/800
Baseline probabilities: 454/800
Baseline probabilities: 456/800
Baseline probabilities: 458/800
Baseline probabilities: 460/800
Baseline probabilities: 462/800
Baseline probabilities: 464/800
Baseline probabilities: 466/800
Baseline probabilities: 468/800
Baseline probabilities: 470/800
Baseline probabilities: 472/800
Baseline probabilities: 474/800
Baseline probabilities: 476/800
Baseline probabilities: 478/800
Baseline probabilities: 480/800
Baseline probabilities: 482/800
Baseline probabilities: 484/800
Baseline probabilities: 486/800
Baseline probabilities: 488/800
Baseline probabilities: 490/800
Baseline probabilities: 492/800
Baseline probabilities: 494/800
Baseline probabilities: 496/800
Baseline probabilities: 498/800
Baseline probabilities: 500/800
Baseline probabilities: 502/800
Baseline probabilities: 504/800
Baseline probabilities: 506/800
Baseline probabilities: 508/800
Baseline probabilities: 510/800
Baseline probabilities: 512/800
Baseline probabilities: 514/800
Baseline probabilities: 516/800
Baseline probabilities: 518/800

Baseline probabilities: 520/800
Baseline probabilities: 522/800
Baseline probabilities: 524/800
Baseline probabilities: 526/800
Baseline probabilities: 528/800
Baseline probabilities: 530/800
Baseline probabilities: 532/800
Baseline probabilities: 534/800
Baseline probabilities: 536/800
Baseline probabilities: 538/800
Baseline probabilities: 540/800
Baseline probabilities: 542/800
Baseline probabilities: 544/800
Baseline probabilities: 546/800
Baseline probabilities: 548/800
Baseline probabilities: 550/800
Baseline probabilities: 552/800
Baseline probabilities: 554/800
Baseline probabilities: 556/800
Baseline probabilities: 558/800
Baseline probabilities: 560/800
Baseline probabilities: 562/800
Baseline probabilities: 564/800
Baseline probabilities: 566/800
Baseline probabilities: 568/800
Baseline probabilities: 570/800
Baseline probabilities: 572/800
Baseline probabilities: 574/800
Baseline probabilities: 576/800
Baseline probabilities: 578/800
Baseline probabilities: 580/800
Baseline probabilities: 582/800
Baseline probabilities: 584/800
Baseline probabilities: 586/800
Baseline probabilities: 588/800
Baseline probabilities: 590/800
Baseline probabilities: 592/800
Baseline probabilities: 594/800
Baseline probabilities: 596/800
Baseline probabilities: 598/800
Baseline probabilities: 600/800
Baseline probabilities: 602/800
Baseline probabilities: 604/800
Baseline probabilities: 606/800
Baseline probabilities: 608/800
Baseline probabilities: 610/800
Baseline probabilities: 612/800
Baseline probabilities: 614/800
Baseline probabilities: 616/800
Baseline probabilities: 618/800
Baseline probabilities: 620/800
Baseline probabilities: 622/800
Baseline probabilities: 624/800
Baseline probabilities: 626/800
Baseline probabilities: 628/800
Baseline probabilities: 630/800
Baseline probabilities: 632/800
Baseline probabilities: 634/800
Baseline probabilities: 636/800
Baseline probabilities: 638/800
Baseline probabilities: 640/800
Baseline probabilities: 642/800
Baseline probabilities: 644/800
Baseline probabilities: 646/800
Baseline probabilities: 648/800
Baseline probabilities: 650/800
Baseline probabilities: 652/800
Baseline probabilities: 654/800
Baseline probabilities: 656/800
Baseline probabilities: 658/800
Baseline probabilities: 660/800
Baseline probabilities: 662/800
Baseline probabilities: 664/800
Baseline probabilities: 666/800
Baseline probabilities: 668/800
Baseline probabilities: 670/800
Baseline probabilities: 672/800
Baseline probabilities: 674/800
Baseline probabilities: 676/800
Baseline probabilities: 678/800
Baseline probabilities: 680/800
Baseline probabilities: 682/800
Baseline probabilities: 684/800
Baseline probabilities: 686/800
Baseline probabilities: 688/800
Baseline probabilities: 690/800
Baseline probabilities: 692/800
Baseline probabilities: 694/800
Baseline probabilities: 696/800
Baseline probabilities: 698/800
Baseline probabilities: 700/800
Baseline probabilities: 702/800
Baseline probabilities: 704/800
Baseline probabilities: 706/800
Baseline probabilities: 708/800
Baseline probabilities: 710/800
Baseline probabilities: 712/800
Baseline probabilities: 714/800
Baseline probabilities: 716/800
Baseline probabilities: 718/800
Baseline probabilities: 720/800
Baseline probabilities: 722/800
Baseline probabilities: 724/800
Baseline probabilities: 726/800
Baseline probabilities: 728/800
Baseline probabilities: 730/800
Baseline probabilities: 732/800
Baseline probabilities: 734/800
Baseline probabilities: 736/800
Baseline probabilities: 738/800
Baseline probabilities: 740/800
Baseline probabilities: 742/800
Baseline probabilities: 744/800
Baseline probabilities: 746/800
Baseline probabilities: 748/800
Baseline probabilities: 750/800
Baseline probabilities: 752/800
Baseline probabilities: 754/800
Baseline probabilities: 756/800
Baseline probabilities: 758/800
Baseline probabilities: 760/800
Baseline probabilities: 762/800
Baseline probabilities: 764/800
Baseline probabilities: 766/800
Baseline probabilities: 768/800
Baseline probabilities: 770/800
Baseline probabilities: 772/800
Baseline probabilities: 774/800
Baseline probabilities: 776/800
Baseline probabilities: 778/800
Baseline probabilities: 780/800
Baseline probabilities: 782/800
Baseline probabilities: 784/800
Baseline probabilities: 786/800
Baseline probabilities: 788/800
Baseline probabilities: 790/800
Baseline probabilities: 792/800
Baseline probabilities: 794/800
Baseline probabilities: 796/800
Baseline probabilities: 798/800
Baseline probabilities: 800/800
baseline_label_probs_by_prompt: (800, 4)
Causal pairs to test: 80

,pair_id,label_word,feature_idx,label_specific_rank,stable_by_rule,baseline_label_specific_pre_gap,retention_rate_top_20,min_over_baseline,worst_variant_rank
0,0,World,13844,1,True,22.572865,1.000,0.876930,1
1,1,World,3994,2,True,17.208542,1.000,1.000000,2
2,2,World,14744,3,True,17.116394,1.000,0.938417,3
3,3,World,3163,4,True,10.695886,1.000,0.927058,6
4,4,World,5222,5,True,9.152500,1.000,0.989780,6
5,5,World,8901,6,True,9.130677,1.000,0.990756,6
6,6,World,406,7,True,8.718281,1.000,0.877048,8
7,7,World,1728,8,True,8.028021,1.000,0.911988,9
8,8,World,9069,9,True,7.454505,1.000,0.970708,10
9,9,World,5743,10,True,7.108073,1.000,0.775164,15
10,10,World,1295,11,False,6.906670,0.875,0.492277,43
11,11,World,6211,12,False,6.290755,0.875,0.714541,25
12,12,World,11438,13,True,6.254206,1.000,0.883732,13
13,13,World,2791,14,True,5.826881,1.000,0.951773,14
14,14,World,13051,15,True,5.646966,1.000,0.852406,20
15,15,World,8386,16,False,5.642500,0.750,0.818177,23
16,16,World,3648,17,False,5.611178,0.500,0.847182,22
17,17,World,2221,18,False,5.330026,0.750,0.833608,23
18,18,World,14785,19,True,5.302891,1.000,0.915494,20
19,19,World,541,20,True,5.249551,1.000,1.000000,20
20,20,Sports,8298,1,True,24.050652,1.000,0.903064,2
21,21,Sports,3408,2,True,22.800678,1.000,0.980879,2
22,22,Sports,13985,3,True,16.599998,1.000,0.881928,3
23,23,Sports,1740,4,True,14.022396,1.000,0.847929,5
24,24,Sports,14142,5,True,11.956979,1.000,0.984423,5
25,25,Sports,5092,6,True,9.999765,1.000,0.787270,9
26,26,Sports,5672,7,True,9.779193,1.000,0.974758,7
27,27,Sports,9289,8,True,9.066875,1.000,0.840445,10
28,28,Sports,2671,9,True,8.329636,1.000,0.760047,13
29,29,Sports,3375,10,True,8.309010,1.000,0.684341,15
30,30,Sports,2999,11,True,8.238750,1.000,0.884034,11
31,31,Sports,5104,12,True,7.969713,1.000,0.869565,12
32,32,Sports,1774,13,True,6.919844,1.000,0.999082,13
33,33,Sports,45,14,True,6.072083,1.000,0.923073,14
34,34,Sports,13203,15,True,5.700078,1.000,0.848070,20
35,35,Sports,13093,16,True,5.619583,1.000,0.886391,19
36,36,Sports,11476,17,False,5.504167,0.625,0.821698,24
37,37,Sports,7502,18,False,5.475469,0.250,0.619344,47
38,38,Sports,2572,19,False,5.453331,0.625,0.622861,46
39,39,Sports,14255,20,False,5.294167,0.625,0.890918,25
40,40,Business,16288,1,True,18.021406,1.000,0.915144,1
41,41,Business,5333,2,True,13.143958,1.000,0.997345,2
42,42,Business,5349,3,True,10.461979,1.000,1.000000,3
43,43,Business,1295,4,True,9.786667,1.000,0.698910,8
44,44,Business,16159,5,True,8.708261,1.000,0.895432,6
45,45,Business,3678,6,True,7.642838,1.000,0.855079,8
46,46,Business,3375,7,True,7.496718,1.000,1.000000,7
47,47,Business,2039,8,True,6.826914,1.000,0.950284,8
48,48,Business,15267,9,True,6.668333,1.000,0.854974,13
49,49,Business,14960,10,True,6.380482,1.000,0.841254,11
50,50,Business,10303,11,True,5.940000,1.000,0.784775,15
51,51,Business,10090,12,True,5.499636,1.000,0.964464,12
52,52,Business,6193,13,True,5.424583,1.000,0.921029,14
53,53,Business,10489,14,True,5.201589,1.000,0.994893,14
54,54,Business,8901,15,True,4.534010,1.000,0.806325,19
55,55,Business,10483,16,True,4.466042,1.000,0.900534,17
56,56,Business,8875,17,True,4.051068,1.000,0.888449,19
57,57,Business,9009,18,False,3.850625,0.375,0.718268,29
58,58,Business,44,19,False,3.568620,0.750,0.828547,24
59,59,Business,8551,20,False,3.481354,0.625,0.839592,22
60,60,Technology,1831,1,True,18.446405,1.000,0.929656,1
61,61,Technology,3442,2,True,14.010313,1.000,0.933159,2
62,62,Technology,16159,3,True,12.843471,1.000,0.786597,5
63,63,Technology,7700,4,True,11.832865,1.000,0.978071,5
64,64,Technology,9247,5,True,11.271146,1.000,0.888367,5
65,65,Technology,8875,6,True,9.317318,1.000,0.767970,8
66,66,Technology,13811,7,True,8.518959,1.000,0.895454,7
67,67,Technology,14601,8,True,8.241979,1.000,0.778573,9
68,68,Technology,10070,9,True,7.406666,1.000,0.806931,10
69,69,Technology,10303,10,True,7.059792,1.000,0.811421,10
70,70,Technology,3375,11,True,6.755260,1.000,0.674700,15
71,71,Technology,8551,12,False,6.235520,0.875,0.625432,21
72,72,Technology,14316,13,True,5.854375,1.000,0.868741,13
73,73,Technology,14370,14,True,5.646875,1.000,0.846052,14
74,74,Technology,5131,15,False,5.481668,0.875,0.761933,21
75,75,Technology,7281,16,False,4.958855,0.625,0.583962,48
76,76,Technology,12559,17,False,4.935482,0.875,0.824121,22
77,77,Technology,7152,18,False,4.660000,0.375,0.656652,43
78,78,Technology,12592,19,False,4.537498,0.500,0.769514,29
79,79,Technology,6880,20,False,4.260000,0.375,0.735915,39

Causal intervention instances: 16000

,pair_id,prompt_idx,query_local_idx,variant_idx,label,label_word,feature_idx
0,0,16,2,0,0,World,13844
1,0,17,2,1,0,World,13844
2,0,18,2,2,0,World,13844
3,0,19,2,3,0,World,13844
4,0,20,2,4,0,World,13844

ablate_active: 2/16000
ablate_active: 4/16000
ablate_active: 6/16000
ablate_active: 8/16000
ablate_active: 10/16000
ablate_active: 12/16000
ablate_active: 14/16000
ablate_active: 16/16000
ablate_active: 18/16000
ablate_active: 20/16000
ablate_active: 22/16000
ablate_active: 24/16000
ablate_active: 26/16000
ablate_active: 28/16000
ablate_active: 30/16000
ablate_active: 32/16000
ablate_active: 34/16000
ablate_active: 36/16000
ablate_active: 38/16000
ablate_active: 40/16000
ablate_active: 42/16000
ablate_active: 44/16000
ablate_active: 46/16000
ablate_active: 48/16000
ablate_active: 50/16000
ablate_active: 52/16000
ablate_active: 54/16000
ablate_active: 56/16000
ablate_active: 58/16000
ablate_active: 60/16000
ablate_active: 62/16000
ablate_active: 64/16000
ablate_active: 66/16000
ablate_active: 68/16000
ablate_active: 70/16000
ablate_active: 72/16000
ablate_active: 74/16000
ablate_active: 76/16000
ablate_active: 78/16000
ablate_active: 80/16000
ablate_active: 82/16000
ablate_active: 84/16000
ablate_active: 86/16000
ablate_active: 88/16000
ablate_active: 90/16000
ablate_active: 92/16000
ablate_active: 94/16000
ablate_active: 96/16000
ablate_active: 98/16000
ablate_active: 100/16000
ablate_active: 102/16000
ablate_active: 104/16000
ablate_active: 106/16000
ablate_active: 108/16000
ablate_active: 110/16000
ablate_active: 112/16000
ablate_active: 114/16000
ablate_active: 116/16000
ablate_active: 118/16000
ablate_active: 120/16000
ablate_active: 122/16000
ablate_active: 124/16000
ablate_active: 126/16000
ablate_active: 128/16000
ablate_active: 130/16000
ablate_active: 132/16000
ablate_active: 134/16000
ablate_active: 136/16000
ablate_active: 138/16000
ablate_active: 140/16000
ablate_active: 142/16000
ablate_active: 144/16000
ablate_active: 146/16000
ablate_active: 148/16000
ablate_active: 150/16000
ablate_active: 152/16000
ablate_active: 154/16000
ablate_active: 156/16000
ablate_active: 158/16000
ablate_active: 160/16000
ablate_active: 162/16000
ablate_active: 164/16000
ablate_active: 166/16000
ablate_active: 168/16000
ablate_active: 170/16000
ablate_active: 172/16000
ablate_active: 174/16000
ablate_active: 176/16000
ablate_active: 178/16000
ablate_active: 180/16000
ablate_active: 182/16000
ablate_active: 184/16000
ablate_active: 186/16000
ablate_active: 188/16000
ablate_active: 190/16000
ablate_active: 192/16000
ablate_active: 194/16000
ablate_active: 196/16000
ablate_active: 198/16000
ablate_active: 200/16000
ablate_active: 202/16000
ablate_active: 204/16000
ablate_active: 206/16000
ablate_active: 208/16000
ablate_active: 210/16000
ablate_active: 212/16000
ablate_active: 214/16000
ablate_active: 216/16000
ablate_active: 218/16000
ablate_active: 220/16000
ablate_active: 222/16000
ablate_active: 224/16000
ablate_active: 226/16000
ablate_active: 228/16000
ablate_active: 230/16000
ablate_active: 232/16000
ablate_active: 234/16000
ablate_active: 236/16000
ablate_active: 238/16000
ablate_active: 240/16000
ablate_active: 242/16000
ablate_active: 244/16000
ablate_active: 246/16000
ablate_active: 248/16000
ablate_active: 250/16000
ablate_active: 252/16000
ablate_active: 254/16000
ablate_active: 256/16000
ablate_active: 258/16000
ablate_active: 260/16000
ablate_active: 262/16000
ablate_active: 264/16000
ablate_active: 266/16000
ablate_active: 268/16000
ablate_active: 270/16000
ablate_active: 272/16000
ablate_active: 274/16000
ablate_active: 276/16000
ablate_active: 278/16000
ablate_active: 280/16000
ablate_active: 282/16000
ablate_active: 284/16000
ablate_active: 286/16000
ablate_active: 288/16000
ablate_active: 290/16000
ablate_active: 292/16000
ablate_active: 294/16000
ablate_active: 296/16000
ablate_active: 298/16000
ablate_active: 300/16000
ablate_active: 302/16000
ablate_active: 304/16000
ablate_active: 306/16000
ablate_active: 308/16000
ablate_active: 310/16000
ablate_active: 312/16000
ablate_active: 314/16000
ablate_active: 316/16000
ablate_active: 318/16000
ablate_active: 320/16000
ablate_active: 322/16000
ablate_active: 324/16000
ablate_active: 326/16000
ablate_active: 328/16000
ablate_active: 330/16000
ablate_active: 332/16000
ablate_active: 334/16000
ablate_active: 336/16000
ablate_active: 338/16000
ablate_active: 340/16000
ablate_active: 342/16000
ablate_active: 344/16000
ablate_active: 346/16000
ablate_active: 348/16000
ablate_active: 350/16000
ablate_active: 352/16000
ablate_active: 354/16000
ablate_active: 356/16000
ablate_active: 358/16000
ablate_active: 360/16000
ablate_active: 362/16000
ablate_active: 364/16000
ablate_active: 366/16000
ablate_active: 368/16000
ablate_active: 370/16000
ablate_active: 372/16000
ablate_active: 374/16000
ablate_active: 376/16000
ablate_active: 378/16000
ablate_active: 380/16000
ablate_active: 382/16000
ablate_active: 384/16000
ablate_active: 386/16000
ablate_active: 388/16000
ablate_active: 390/16000
ablate_active: 392/16000
ablate_active: 394/16000
ablate_active: 396/16000
ablate_active: 398/16000
ablate_active: 400/16000
ablate_active: 402/16000
ablate_active: 404/16000
ablate_active: 406/16000
ablate_active: 408/16000
ablate_active: 410/16000
ablate_active: 412/16000
ablate_active: 414/16000
ablate_active: 416/16000
ablate_active: 418/16000
ablate_active: 420/16000
ablate_active: 422/16000
ablate_active: 424/16000
ablate_active: 426/16000
ablate_active: 428/16000
ablate_active: 430/16000
ablate_active: 432/16000
ablate_active: 434/16000
ablate_active: 436/16000
ablate_active: 438/16000
ablate_active: 440/16000
ablate_active: 442/16000
ablate_active: 444/16000
ablate_active: 446/16000
ablate_active: 448/16000
ablate_active: 450/16000
ablate_active: 452/16000
ablate_active: 454/16000
ablate_active: 456/16000
ablate_active: 458/16000
ablate_active: 460/16000
ablate_active: 462/16000
ablate_active: 464/16000
ablate_active: 466/16000
ablate_active: 468/16000
ablate_active: 470/16000
ablate_active: 472/16000
ablate_active: 474/16000
ablate_active: 476/16000
ablate_active: 478/16000
ablate_active: 480/16000
ablate_active: 482/16000
ablate_active: 484/16000
ablate_active: 486/16000
ablate_active: 488/16000
ablate_active: 490/16000
ablate_active: 492/16000
ablate_active: 494/16000
ablate_active: 496/16000
ablate_active: 498/16000
ablate_active: 500/16000
ablate_active: 502/16000
ablate_active: 504/16000
ablate_active: 506/16000
ablate_active: 508/16000
ablate_active: 510/16000
ablate_active: 512/16000
ablate_active: 514/16000
ablate_active: 516/16000
ablate_active: 518/16000
ablate_active: 520/16000
ablate_active: 522/16000
ablate_active: 524/16000
ablate_active: 526/16000
ablate_active: 528/16000
ablate_active: 530/16000
ablate_active: 532/16000
ablate_active: 534/16000
ablate_active: 536/16000
ablate_active: 538/16000
ablate_active: 540/16000
ablate_active: 542/16000
ablate_active: 544/16000
ablate_active: 546/16000
ablate_active: 548/16000
ablate_active: 550/16000
ablate_active: 552/16000
ablate_active: 554/16000
ablate_active: 556/16000
ablate_active: 558/16000
ablate_active: 560/16000
ablate_active: 562/16000
ablate_active: 564/16000
ablate_active: 566/16000
ablate_active: 568/16000
ablate_active: 570/16000
ablate_active: 572/16000
ablate_active: 574/16000
ablate_active: 576/16000
ablate_active: 578/16000
ablate_active: 580/16000
ablate_active: 582/16000
ablate_active: 584/16000
ablate_active: 586/16000
ablate_active: 588/16000
ablate_active: 590/16000
ablate_active: 592/16000
ablate_active: 594/16000
ablate_active: 596/16000
ablate_active: 598/16000
ablate_active: 600/16000
ablate_active: 602/16000
ablate_active: 604/16000
ablate_active: 606/16000
ablate_active: 608/16000
ablate_active: 610/16000
ablate_active: 612/16000
ablate_active: 614/16000
ablate_active: 616/16000
ablate_active: 618/16000
ablate_active: 620/16000
ablate_active: 622/16000
ablate_active: 624/16000
ablate_active: 626/16000
ablate_active: 628/16000
ablate_active: 630/16000
ablate_active: 632/16000
ablate_active: 634/16000
ablate_active: 636/16000
ablate_active: 638/16000
ablate_active: 640/16000
ablate_active: 642/16000
ablate_active: 644/16000
ablate_active: 646/16000
ablate_active: 648/16000
ablate_active: 650/16000
ablate_active: 652/16000
ablate_active: 654/16000
ablate_active: 656/16000
ablate_active: 658/16000
ablate_active: 660/16000
ablate_active: 662/16000
ablate_active: 664/16000

ablate_active: 666/16000
ablate_active: 668/16000
ablate_active: 670/16000
ablate_active: 672/16000
ablate_active: 674/16000
ablate_active: 676/16000
ablate_active: 678/16000
ablate_active: 680/16000
ablate_active: 682/16000
ablate_active: 684/16000
ablate_active: 686/16000
ablate_active: 688/16000
ablate_active: 690/16000
ablate_active: 692/16000
ablate_active: 694/16000
ablate_active: 696/16000
ablate_active: 698/16000
ablate_active: 700/16000
ablate_active: 702/16000
ablate_active: 704/16000
ablate_active: 706/16000
ablate_active: 708/16000
ablate_active: 710/16000
ablate_active: 712/16000
ablate_active: 714/16000
ablate_active: 716/16000
ablate_active: 718/16000
ablate_active: 720/16000
ablate_active: 722/16000
ablate_active: 724/16000
ablate_active: 726/16000
ablate_active: 728/16000
ablate_active: 730/16000
ablate_active: 732/16000
ablate_active: 734/16000
ablate_active: 736/16000
ablate_active: 738/16000
ablate_active: 740/16000
ablate_active: 742/16000
ablate_active: 744/16000
ablate_active: 746/16000
ablate_active: 748/16000
ablate_active: 750/16000
ablate_active: 752/16000
ablate_active: 754/16000
ablate_active: 756/16000
ablate_active: 758/16000
ablate_active: 760/16000
ablate_active: 762/16000
ablate_active: 764/16000
ablate_active: 766/16000
ablate_active: 768/16000
ablate_active: 770/16000
ablate_active: 772/16000
ablate_active: 774/16000
ablate_active: 776/16000
ablate_active: 778/16000
ablate_active: 780/16000
ablate_active: 782/16000
ablate_active: 784/16000
ablate_active: 786/16000
ablate_active: 788/16000
ablate_active: 790/16000
ablate_active: 792/16000
ablate_active: 794/16000
ablate_active: 796/16000
ablate_active: 798/16000
ablate_active: 800/16000
ablate_active: 802/16000
ablate_active: 804/16000
ablate_active: 806/16000
ablate_active: 808/16000
ablate_active: 810/16000
ablate_active: 812/16000
ablate_active: 814/16000
ablate_active: 816/16000
ablate_active: 818/16000
ablate_active: 820/16000
ablate_active: 822/16000
ablate_active: 824/16000
ablate_active: 826/16000
ablate_active: 828/16000
ablate_active: 830/16000
ablate_active: 832/16000
ablate_active: 834/16000
ablate_active: 836/16000
ablate_active: 838/16000
ablate_active: 840/16000
ablate_active: 842/16000
ablate_active: 844/16000
ablate_active: 846/16000
ablate_active: 848/16000
ablate_active: 850/16000
ablate_active: 852/16000
ablate_active: 854/16000
ablate_active: 856/16000
ablate_active: 858/16000
ablate_active: 860/16000
ablate_active: 862/16000
ablate_active: 864/16000
ablate_active: 866/16000
ablate_active: 868/16000
ablate_active: 870/16000
ablate_active: 872/16000
ablate_active: 874/16000
ablate_active: 876/16000
ablate_active: 878/16000
ablate_active: 880/16000
ablate_active: 882/16000
ablate_active: 884/16000
ablate_active: 886/16000
ablate_active: 888/16000
ablate_active: 890/16000
ablate_active: 892/16000
ablate_active: 894/16000
ablate_active: 896/16000
ablate_active: 898/16000
ablate_active: 900/16000
ablate_active: 902/16000
ablate_active: 904/16000
ablate_active: 906/16000
ablate_active: 908/16000
ablate_active: 910/16000
ablate_active: 912/16000
ablate_active: 914/16000
ablate_active: 916/16000
ablate_active: 918/16000
ablate_active: 920/16000
ablate_active: 922/16000
ablate_active: 924/16000
ablate_active: 926/16000
ablate_active: 928/16000
ablate_active: 930/16000
ablate_active: 932/16000
ablate_active: 934/16000
ablate_active: 936/16000
ablate_active: 938/16000
ablate_active: 940/16000
ablate_active: 942/16000
ablate_active: 944/16000
ablate_active: 946/16000
ablate_active: 948/16000
ablate_active: 950/16000
ablate_active: 952/16000
ablate_active: 954/16000
ablate_active: 956/16000
ablate_active: 958/16000
ablate_active: 960/16000
ablate_active: 962/16000
ablate_active: 964/16000
ablate_active: 966/16000
ablate_active: 968/16000
ablate_active: 970/16000
ablate_active: 972/16000
ablate_active: 974/16000
ablate_active: 976/16000
ablate_active: 978/16000
ablate_active: 980/16000
ablate_active: 982/16000
ablate_active: 984/16000
ablate_active: 986/16000
ablate_active: 988/16000
ablate_active: 990/16000
ablate_active: 992/16000
ablate_active: 994/16000
ablate_active: 996/16000
ablate_active: 998/16000
ablate_active: 1000/16000
ablate_active: 1002/16000
ablate_active: 1004/16000
ablate_active: 1006/16000
ablate_active: 1008/16000
ablate_active: 1010/16000
ablate_active: 1012/16000
ablate_active: 1014/16000
ablate_active: 1016/16000
ablate_active: 1018/16000
ablate_active: 1020/16000
ablate_active: 1022/16000
ablate_active: 1024/16000
ablate_active: 1026/16000
ablate_active: 1028/16000
ablate_active: 1030/16000
ablate_active: 1032/16000
ablate_active: 1034/16000
ablate_active: 1036/16000
ablate_active: 1038/16000
ablate_active: 1040/16000
ablate_active: 1042/16000
ablate_active: 1044/16000
ablate_active: 1046/16000
ablate_active: 1048/16000
ablate_active: 1050/16000
ablate_active: 1052/16000
ablate_active: 1054/16000
ablate_active: 1056/16000
ablate_active: 1058/16000
ablate_active: 1060/16000
ablate_active: 1062/16000
ablate_active: 1064/16000
ablate_active: 1066/16000
ablate_active: 1068/16000
ablate_active: 1070/16000
ablate_active: 1072/16000
ablate_active: 1074/16000
ablate_active: 1076/16000
ablate_active: 1078/16000
ablate_active: 1080/16000
ablate_active: 1082/16000
ablate_active: 1084/16000
ablate_active: 1086/16000
ablate_active: 1088/16000
ablate_active: 1090/16000
ablate_active: 1092/16000
ablate_active: 1094/16000
ablate_active: 1096/16000
ablate_active: 1098/16000
ablate_active: 1100/16000
ablate_active: 1102/16000
ablate_active: 1104/16000
ablate_active: 1106/16000
ablate_active: 1108/16000
ablate_active: 1110/16000
ablate_active: 1112/16000
ablate_active: 1114/16000
ablate_active: 1116/16000
ablate_active: 1118/16000
ablate_active: 1120/16000
ablate_active: 1122/16000
ablate_active: 1124/16000
ablate_active: 1126/16000
ablate_active: 1128/16000
ablate_active: 1130/16000
ablate_active: 1132/16000
ablate_active: 1134/16000
ablate_active: 1136/16000
ablate_active: 1138/16000
ablate_active: 1140/16000
ablate_active: 1142/16000
ablate_active: 1144/16000
ablate_active: 1146/16000
ablate_active: 1148/16000
ablate_active: 1150/16000
ablate_active: 1152/16000
ablate_active: 1154/16000
ablate_active: 1156/16000
ablate_active: 1158/16000
ablate_active: 1160/16000
ablate_active: 1162/16000
ablate_active: 1164/16000
ablate_active: 1166/16000
ablate_active: 1168/16000
ablate_active: 1170/16000
ablate_active: 1172/16000
ablate_active: 1174/16000
ablate_active: 1176/16000
ablate_active: 1178/16000
ablate_active: 1180/16000
ablate_active: 1182/16000
ablate_active: 1184/16000
ablate_active: 1186/16000
ablate_active: 1188/16000
ablate_active: 1190/16000
ablate_active: 1192/16000
ablate_active: 1194/16000
ablate_active: 1196/16000
ablate_active: 1198/16000
ablate_active: 1200/16000
ablate_active: 1202/16000
ablate_active: 1204/16000
ablate_active: 1206/16000
ablate_active: 1208/16000
ablate_active: 1210/16000
ablate_active: 1212/16000
ablate_active: 1214/16000
ablate_active: 1216/16000
ablate_active: 1218/16000
ablate_active: 1220/16000
ablate_active: 1222/16000
ablate_active: 1224/16000
ablate_active: 1226/16000
ablate_active: 1228/16000
ablate_active: 1230/16000
ablate_active: 1232/16000
ablate_active: 1234/16000
ablate_active: 1236/16000
ablate_active: 1238/16000
ablate_active: 1240/16000
ablate_active: 1242/16000
ablate_active: 1244/16000
ablate_active: 1246/16000
ablate_active: 1248/16000
ablate_active: 1250/16000
ablate_active: 1252/16000
ablate_active: 1254/16000
ablate_active: 1256/16000
ablate_active: 1258/16000
ablate_active: 1260/16000
ablate_active: 1262/16000
ablate_active: 1264/16000
ablate_active: 1266/16000
ablate_active: 1268/16000
ablate_active: 1270/16000
ablate_active: 1272/16000
ablate_active: 1274/16000
ablate_active: 1276/16000
ablate_active: 1278/16000
ablate_active: 1280/16000
ablate_active: 1282/16000
ablate_active: 1284/16000
ablate_active: 1286/16000
ablate_active: 1288/16000
ablate_active: 1290/16000
ablate_active: 1292/16000
ablate_active: 1294/16000
ablate_active: 1296/16000
ablate_active: 1298/16000
ablate_active: 1300/16000
ablate_active: 1302/16000
ablate_active: 1304/16000
ablate_active: 1306/16000
ablate_active: 1308/16000
ablate_active: 1310/16000

ablate_active: 1312/16000
ablate_active: 1314/16000
ablate_active: 1316/16000
ablate_active: 1318/16000
ablate_active: 1320/16000
ablate_active: 1322/16000
ablate_active: 1324/16000
ablate_active: 1326/16000
ablate_active: 1328/16000
ablate_active: 1330/16000
ablate_active: 1332/16000
ablate_active: 1334/16000
ablate_active: 1336/16000
ablate_active: 1338/16000
ablate_active: 1340/16000
ablate_active: 1342/16000
ablate_active: 1344/16000
ablate_active: 1346/16000
ablate_active: 1348/16000
ablate_active: 1350/16000
ablate_active: 1352/16000
ablate_active: 1354/16000
ablate_active: 1356/16000
ablate_active: 1358/16000
ablate_active: 1360/16000
ablate_active: 1362/16000
ablate_active: 1364/16000
ablate_active: 1366/16000
ablate_active: 1368/16000
ablate_active: 1370/16000
ablate_active: 1372/16000
ablate_active: 1374/16000
ablate_active: 1376/16000
ablate_active: 1378/16000
ablate_active: 1380/16000
ablate_active: 1382/16000
ablate_active: 1384/16000
ablate_active: 1386/16000
ablate_active: 1388/16000
ablate_active: 1390/16000
ablate_active: 1392/16000
ablate_active: 1394/16000
ablate_active: 1396/16000
ablate_active: 1398/16000
ablate_active: 1400/16000
ablate_active: 1402/16000
ablate_active: 1404/16000
ablate_active: 1406/16000
ablate_active: 1408/16000
ablate_active: 1410/16000
ablate_active: 1412/16000
ablate_active: 1414/16000
ablate_active: 1416/16000
ablate_active: 1418/16000
ablate_active: 1420/16000
ablate_active: 1422/16000
ablate_active: 1424/16000
ablate_active: 1426/16000
ablate_active: 1428/16000
ablate_active: 1430/16000
ablate_active: 1432/16000
ablate_active: 1434/16000
ablate_active: 1436/16000
ablate_active: 1438/16000
ablate_active: 1440/16000
ablate_active: 1442/16000
ablate_active: 1444/16000
ablate_active: 1446/16000
ablate_active: 1448/16000
ablate_active: 1450/16000
ablate_active: 1452/16000
ablate_active: 1454/16000
ablate_active: 1456/16000
ablate_active: 1458/16000
ablate_active: 1460/16000
ablate_active: 1462/16000
ablate_active: 1464/16000
ablate_active: 1466/16000
ablate_active: 1468/16000
ablate_active: 1470/16000
ablate_active: 1472/16000
ablate_active: 1474/16000
ablate_active: 1476/16000
ablate_active: 1478/16000
ablate_active: 1480/16000
ablate_active: 1482/16000
ablate_active: 1484/16000
ablate_active: 1486/16000
ablate_active: 1488/16000
ablate_active: 1490/16000
ablate_active: 1492/16000
ablate_active: 1494/16000
ablate_active: 1496/16000
ablate_active: 1498/16000
ablate_active: 1500/16000
ablate_active: 1502/16000
ablate_active: 1504/16000
ablate_active: 1506/16000
ablate_active: 1508/16000
ablate_active: 1510/16000
ablate_active: 1512/16000
ablate_active: 1514/16000
ablate_active: 1516/16000
ablate_active: 1518/16000
ablate_active: 1520/16000
ablate_active: 1522/16000
ablate_active: 1524/16000
ablate_active: 1526/16000
ablate_active: 1528/16000
ablate_active: 1530/16000
ablate_active: 1532/16000
ablate_active: 1534/16000
ablate_active: 1536/16000
ablate_active: 1538/16000
ablate_active: 1540/16000
ablate_active: 1542/16000
ablate_active: 1544/16000
ablate_active: 1546/16000
ablate_active: 1548/16000
ablate_active: 1550/16000
ablate_active: 1552/16000
ablate_active: 1554/16000
ablate_active: 1556/16000
ablate_active: 1558/16000
ablate_active: 1560/16000
ablate_active: 1562/16000
ablate_active: 1564/16000
ablate_active: 1566/16000
ablate_active: 1568/16000
ablate_active: 1570/16000
ablate_active: 1572/16000
ablate_active: 1574/16000
ablate_active: 1576/16000
ablate_active: 1578/16000
ablate_active: 1580/16000
ablate_active: 1582/16000
ablate_active: 1584/16000
ablate_active: 1586/16000
ablate_active: 1588/16000
ablate_active: 1590/16000
ablate_active: 1592/16000
ablate_active: 1594/16000
ablate_active: 1596/16000
ablate_active: 1598/16000
ablate_active: 1600/16000
ablate_active: 1602/16000
ablate_active: 1604/16000
ablate_active: 1606/16000
ablate_active: 1608/16000
ablate_active: 1610/16000
ablate_active: 1612/16000
ablate_active: 1614/16000
ablate_active: 1616/16000
ablate_active: 1618/16000
ablate_active: 1620/16000
ablate_active: 1622/16000
ablate_active: 1624/16000
ablate_active: 1626/16000
ablate_active: 1628/16000
ablate_active: 1630/16000
ablate_active: 1632/16000
ablate_active: 1634/16000
ablate_active: 1636/16000
ablate_active: 1638/16000
ablate_active: 1640/16000
ablate_active: 1642/16000
ablate_active: 1644/16000
ablate_active: 1646/16000
ablate_active: 1648/16000
ablate_active: 1650/16000
ablate_active: 1652/16000
ablate_active: 1654/16000
ablate_active: 1656/16000
ablate_active: 1658/16000
ablate_active: 1660/16000
ablate_active: 1662/16000
ablate_active: 1664/16000
ablate_active: 1666/16000
ablate_active: 1668/16000
ablate_active: 1670/16000
ablate_active: 1672/16000
ablate_active: 1674/16000
ablate_active: 1676/16000
ablate_active: 1678/16000
ablate_active: 1680/16000
ablate_active: 1682/16000
ablate_active: 1684/16000
ablate_active: 1686/16000
ablate_active: 1688/16000
ablate_active: 1690/16000
ablate_active: 1692/16000
ablate_active: 1694/16000
ablate_active: 1696/16000
ablate_active: 1698/16000
ablate_active: 1700/16000
ablate_active: 1702/16000
ablate_active: 1704/16000
ablate_active: 1706/16000
ablate_active: 1708/16000
ablate_active: 1710/16000
ablate_active: 1712/16000
ablate_active: 1714/16000
ablate_active: 1716/16000
ablate_active: 1718/16000
ablate_active: 1720/16000
ablate_active: 1722/16000
ablate_active: 1724/16000
ablate_active: 1726/16000
ablate_active: 1728/16000
ablate_active: 1730/16000
ablate_active: 1732/16000
ablate_active: 1734/16000
ablate_active: 1736/16000
ablate_active: 1738/16000
ablate_active: 1740/16000
ablate_active: 1742/16000
ablate_active: 1744/16000
ablate_active: 1746/16000
ablate_active: 1748/16000
ablate_active: 1750/16000
ablate_active: 1752/16000
ablate_active: 1754/16000
ablate_active: 1756/16000
ablate_active: 1758/16000
ablate_active: 1760/16000
ablate_active: 1762/16000
ablate_active: 1764/16000
ablate_active: 1766/16000
ablate_active: 1768/16000
ablate_active: 1770/16000
ablate_active: 1772/16000
ablate_active: 1774/16000
ablate_active: 1776/16000
ablate_active: 1778/16000
ablate_active: 1780/16000
ablate_active: 1782/16000
ablate_active: 1784/16000
ablate_active: 1786/16000
ablate_active: 1788/16000
ablate_active: 1790/16000
ablate_active: 1792/16000
ablate_active: 1794/16000
ablate_active: 1796/16000
ablate_active: 1798/16000
ablate_active: 1800/16000
ablate_active: 1802/16000
ablate_active: 1804/16000
ablate_active: 1806/16000
ablate_active: 1808/16000
ablate_active: 1810/16000
ablate_active: 1812/16000
ablate_active: 1814/16000
ablate_active: 1816/16000
ablate_active: 1818/16000
ablate_active: 1820/16000
ablate_active: 1822/16000
ablate_active: 1824/16000
ablate_active: 1826/16000
ablate_active: 1828/16000
ablate_active: 1830/16000
ablate_active: 1832/16000
ablate_active: 1834/16000
ablate_active: 1836/16000
ablate_active: 1838/16000
ablate_active: 1840/16000
ablate_active: 1842/16000
ablate_active: 1844/16000
ablate_active: 1846/16000
ablate_active: 1848/16000
ablate_active: 1850/16000
ablate_active: 1852/16000
ablate_active: 1854/16000
ablate_active: 1856/16000
ablate_active: 1858/16000
ablate_active: 1860/16000
ablate_active: 1862/16000
ablate_active: 1864/16000
ablate_active: 1866/16000
ablate_active: 1868/16000
ablate_active: 1870/16000
ablate_active: 1872/16000
ablate_active: 1874/16000
ablate_active: 1876/16000
ablate_active: 1878/16000
ablate_active: 1880/16000
ablate_active: 1882/16000
ablate_active: 1884/16000
ablate_active: 1886/16000
ablate_active: 1888/16000
ablate_active: 1890/16000
ablate_active: 1892/16000
ablate_active: 1894/16000
ablate_active: 1896/16000
ablate_active: 1898/16000
ablate_active: 1900/16000
ablate_active: 1902/16000
ablate_active: 1904/16000
ablate_active: 1906/16000
ablate_active: 1908/16000
ablate_active: 1910/16000
ablate_active: 1912/16000
ablate_active: 1914/16000
ablate_active: 1916/16000
ablate_active: 1918/16000
ablate_active: 1920/16000
ablate_active: 1922/16000
ablate_active: 1924/16000
ablate_active: 1926/16000
ablate_active: 1928/16000
ablate_active: 1930/16000
ablate_active: 1932/16000
ablate_active: 1934/16000
ablate_active: 1936/16000
ablate_active: 1938/16000
ablate_active: 1940/16000
ablate_active: 1942/16000
ablate_active: 1944/16000

ablate_active: 1946/16000
ablate_active: 1948/16000
ablate_active: 1950/16000
ablate_active: 1952/16000
ablate_active: 1954/16000
ablate_active: 1956/16000
ablate_active: 1958/16000
ablate_active: 1960/16000
ablate_active: 1962/16000
ablate_active: 1964/16000
ablate_active: 1966/16000
ablate_active: 1968/16000
ablate_active: 1970/16000
ablate_active: 1972/16000
ablate_active: 1974/16000
ablate_active: 1976/16000
ablate_active: 1978/16000
ablate_active: 1980/16000
ablate_active: 1982/16000
ablate_active: 1984/16000
ablate_active: 1986/16000
ablate_active: 1988/16000
ablate_active: 1990/16000
ablate_active: 1992/16000
ablate_active: 1994/16000
ablate_active: 1996/16000
ablate_active: 1998/16000
ablate_active: 2000/16000
ablate_active: 2002/16000
ablate_active: 2004/16000
ablate_active: 2006/16000
ablate_active: 2008/16000
ablate_active: 2010/16000
ablate_active: 2012/16000
ablate_active: 2014/16000
ablate_active: 2016/16000
ablate_active: 2018/16000
ablate_active: 2020/16000
ablate_active: 2022/16000
ablate_active: 2024/16000
ablate_active: 2026/16000
ablate_active: 2028/16000
ablate_active: 2030/16000
ablate_active: 2032/16000
ablate_active: 2034/16000
ablate_active: 2036/16000
ablate_active: 2038/16000
ablate_active: 2040/16000
ablate_active: 2042/16000
ablate_active: 2044/16000
ablate_active: 2046/16000
ablate_active: 2048/16000
ablate_active: 2050/16000
ablate_active: 2052/16000
ablate_active: 2054/16000
ablate_active: 2056/16000
ablate_active: 2058/16000
ablate_active: 2060/16000
ablate_active: 2062/16000
ablate_active: 2064/16000
ablate_active: 2066/16000
ablate_active: 2068/16000
ablate_active: 2070/16000
ablate_active: 2072/16000
ablate_active: 2074/16000
ablate_active: 2076/16000
ablate_active: 2078/16000
ablate_active: 2080/16000
ablate_active: 2082/16000
ablate_active: 2084/16000
ablate_active: 2086/16000
ablate_active: 2088/16000
ablate_active: 2090/16000
ablate_active: 2092/16000
ablate_active: 2094/16000
ablate_active: 2096/16000
ablate_active: 2098/16000
ablate_active: 2100/16000
ablate_active: 2102/16000
ablate_active: 2104/16000
ablate_active: 2106/16000
ablate_active: 2108/16000
ablate_active: 2110/16000
ablate_active: 2112/16000
ablate_active: 2114/16000
ablate_active: 2116/16000
ablate_active: 2118/16000
ablate_active: 2120/16000
ablate_active: 2122/16000
ablate_active: 2124/16000
ablate_active: 2126/16000
ablate_active: 2128/16000
ablate_active: 2130/16000
ablate_active: 2132/16000
ablate_active: 2134/16000
ablate_active: 2136/16000
ablate_active: 2138/16000
ablate_active: 2140/16000
ablate_active: 2142/16000
ablate_active: 2144/16000
ablate_active: 2146/16000
ablate_active: 2148/16000
ablate_active: 2150/16000
ablate_active: 2152/16000
ablate_active: 2154/16000
ablate_active: 2156/16000
ablate_active: 2158/16000
ablate_active: 2160/16000
ablate_active: 2162/16000
ablate_active: 2164/16000
ablate_active: 2166/16000
ablate_active: 2168/16000
ablate_active: 2170/16000
ablate_active: 2172/16000
ablate_active: 2174/16000
ablate_active: 2176/16000
ablate_active: 2178/16000
ablate_active: 2180/16000
ablate_active: 2182/16000
ablate_active: 2184/16000
ablate_active: 2186/16000
ablate_active: 2188/16000
ablate_active: 2190/16000
ablate_active: 2192/16000
ablate_active: 2194/16000
ablate_active: 2196/16000
ablate_active: 2198/16000
ablate_active: 2200/16000
ablate_active: 2202/16000
ablate_active: 2204/16000
ablate_active: 2206/16000
ablate_active: 2208/16000
ablate_active: 2210/16000
ablate_active: 2212/16000
ablate_active: 2214/16000
ablate_active: 2216/16000
ablate_active: 2218/16000
ablate_active: 2220/16000
ablate_active: 2222/16000
ablate_active: 2224/16000
ablate_active: 2226/16000
ablate_active: 2228/16000
ablate_active: 2230/16000
ablate_active: 2232/16000
ablate_active: 2234/16000
ablate_active: 2236/16000
ablate_active: 2238/16000
ablate_active: 2240/16000
ablate_active: 2242/16000
ablate_active: 2244/16000
ablate_active: 2246/16000
ablate_active: 2248/16000
ablate_active: 2250/16000
ablate_active: 2252/16000
ablate_active: 2254/16000
ablate_active: 2256/16000
ablate_active: 2258/16000
ablate_active: 2260/16000
ablate_active: 2262/16000
ablate_active: 2264/16000
ablate_active: 2266/16000
ablate_active: 2268/16000
ablate_active: 2270/16000
ablate_active: 2272/16000
ablate_active: 2274/16000
ablate_active: 2276/16000
ablate_active: 2278/16000
ablate_active: 2280/16000
ablate_active: 2282/16000
ablate_active: 2284/16000
ablate_active: 2286/16000
ablate_active: 2288/16000
ablate_active: 2290/16000
ablate_active: 2292/16000
ablate_active: 2294/16000
ablate_active: 2296/16000
ablate_active: 2298/16000
ablate_active: 2300/16000
ablate_active: 2302/16000
ablate_active: 2304/16000
ablate_active: 2306/16000
ablate_active: 2308/16000
ablate_active: 2310/16000
ablate_active: 2312/16000
ablate_active: 2314/16000
ablate_active: 2316/16000
ablate_active: 2318/16000
ablate_active: 2320/16000
ablate_active: 2322/16000
ablate_active: 2324/16000
ablate_active: 2326/16000
ablate_active: 2328/16000
ablate_active: 2330/16000
ablate_active: 2332/16000
ablate_active: 2334/16000
ablate_active: 2336/16000
ablate_active: 2338/16000
ablate_active: 2340/16000
ablate_active: 2342/16000
ablate_active: 2344/16000
ablate_active: 2346/16000
ablate_active: 2348/16000
ablate_active: 2350/16000
ablate_active: 2352/16000
ablate_active: 2354/16000
ablate_active: 2356/16000
ablate_active: 2358/16000
ablate_active: 2360/16000
ablate_active: 2362/16000
ablate_active: 2364/16000
ablate_active: 2366/16000
ablate_active: 2368/16000
ablate_active: 2370/16000
ablate_active: 2372/16000
ablate_active: 2374/16000
ablate_active: 2376/16000
ablate_active: 2378/16000
ablate_active: 2380/16000
ablate_active: 2382/16000
ablate_active: 2384/16000
ablate_active: 2386/16000
ablate_active: 2388/16000
ablate_active: 2390/16000
ablate_active: 2392/16000
ablate_active: 2394/16000
ablate_active: 2396/16000
ablate_active: 2398/16000
ablate_active: 2400/16000
ablate_active: 2402/16000
ablate_active: 2404/16000
ablate_active: 2406/16000
ablate_active: 2408/16000
ablate_active: 2410/16000
ablate_active: 2412/16000
ablate_active: 2414/16000
ablate_active: 2416/16000
ablate_active: 2418/16000
ablate_active: 2420/16000
ablate_active: 2422/16000
ablate_active: 2424/16000
ablate_active: 2426/16000
ablate_active: 2428/16000
ablate_active: 2430/16000
ablate_active: 2432/16000
ablate_active: 2434/16000
ablate_active: 2436/16000
ablate_active: 2438/16000
ablate_active: 2440/16000
ablate_active: 2442/16000
ablate_active: 2444/16000
ablate_active: 2446/16000
ablate_active: 2448/16000
ablate_active: 2450/16000
ablate_active: 2452/16000
ablate_active: 2454/16000
ablate_active: 2456/16000
ablate_active: 2458/16000
ablate_active: 2460/16000
ablate_active: 2462/16000
ablate_active: 2464/16000
ablate_active: 2466/16000
ablate_active: 2468/16000
ablate_active: 2470/16000
ablate_active: 2472/16000
ablate_active: 2474/16000
ablate_active: 2476/16000
ablate_active: 2478/16000
ablate_active: 2480/16000
ablate_active: 2482/16000
ablate_active: 2484/16000
ablate_active: 2486/16000
ablate_active: 2488/16000
ablate_active: 2490/16000
ablate_active: 2492/16000
ablate_active: 2494/16000
ablate_active: 2496/16000
ablate_active: 2498/16000
ablate_active: 2500/16000
ablate_active: 2502/16000
ablate_active: 2504/16000
ablate_active: 2506/16000
ablate_active: 2508/16000
ablate_active: 2510/16000
ablate_active: 2512/16000
ablate_active: 2514/16000
ablate_active: 2516/16000
ablate_active: 2518/16000
ablate_active: 2520/16000
ablate_active: 2522/16000
ablate_active: 2524/16000
ablate_active: 2526/16000
ablate_active: 2528/16000
ablate_active: 2530/16000
ablate_active: 2532/16000
ablate_active: 2534/16000
ablate_active: 2536/16000
ablate_active: 2538/16000
ablate_active: 2540/16000
ablate_active: 2542/16000
ablate_active: 2544/16000
ablate_active: 2546/16000
ablate_active: 2548/16000
ablate_active: 2550/16000
ablate_active: 2552/16000
ablate_active: 2554/16000
ablate_active: 2556/16000
ablate_active: 2558/16000
ablate_active: 2560/16000
ablate_active: 2562/16000
ablate_active: 2564/16000
ablate_active: 2566/16000
ablate_active: 2568/16000
ablate_active: 2570/16000
ablate_active: 2572/16000
ablate_active: 2574/16000
ablate_active: 2576/16000

ablate_active: 2578/16000
ablate_active: 2580/16000
ablate_active: 2582/16000
ablate_active: 2584/16000
ablate_active: 2586/16000
ablate_active: 2588/16000
ablate_active: 2590/16000
ablate_active: 2592/16000
ablate_active: 2594/16000
ablate_active: 2596/16000
ablate_active: 2598/16000
ablate_active: 2600/16000
ablate_active: 2602/16000
ablate_active: 2604/16000
ablate_active: 2606/16000
ablate_active: 2608/16000
ablate_active: 2610/16000
ablate_active: 2612/16000
ablate_active: 2614/16000
ablate_active: 2616/16000
ablate_active: 2618/16000
ablate_active: 2620/16000
ablate_active: 2622/16000
ablate_active: 2624/16000
ablate_active: 2626/16000
ablate_active: 2628/16000
ablate_active: 2630/16000
ablate_active: 2632/16000
ablate_active: 2634/16000
ablate_active: 2636/16000
ablate_active: 2638/16000
ablate_active: 2640/16000
ablate_active: 2642/16000
ablate_active: 2644/16000
ablate_active: 2646/16000
ablate_active: 2648/16000
ablate_active: 2650/16000
ablate_active: 2652/16000
ablate_active: 2654/16000
ablate_active: 2656/16000
ablate_active: 2658/16000
ablate_active: 2660/16000
ablate_active: 2662/16000
ablate_active: 2664/16000
ablate_active: 2666/16000
ablate_active: 2668/16000
ablate_active: 2670/16000
ablate_active: 2672/16000
ablate_active: 2674/16000
ablate_active: 2676/16000
ablate_active: 2678/16000
ablate_active: 2680/16000
ablate_active: 2682/16000
ablate_active: 2684/16000
ablate_active: 2686/16000
ablate_active: 2688/16000
ablate_active: 2690/16000
ablate_active: 2692/16000
ablate_active: 2694/16000
ablate_active: 2696/16000
ablate_active: 2698/16000
ablate_active: 2700/16000
ablate_active: 2702/16000
ablate_active: 2704/16000
ablate_active: 2706/16000
ablate_active: 2708/16000
ablate_active: 2710/16000
ablate_active: 2712/16000
ablate_active: 2714/16000
ablate_active: 2716/16000
ablate_active: 2718/16000
ablate_active: 2720/16000
ablate_active: 2722/16000
ablate_active: 2724/16000
ablate_active: 2726/16000
ablate_active: 2728/16000
ablate_active: 2730/16000
ablate_active: 2732/16000
ablate_active: 2734/16000
ablate_active: 2736/16000
ablate_active: 2738/16000
ablate_active: 2740/16000
ablate_active: 2742/16000
ablate_active: 2744/16000
ablate_active: 2746/16000
ablate_active: 2748/16000
ablate_active: 2750/16000
ablate_active: 2752/16000
ablate_active: 2754/16000
ablate_active: 2756/16000
ablate_active: 2758/16000
ablate_active: 2760/16000
ablate_active: 2762/16000
ablate_active: 2764/16000
ablate_active: 2766/16000
ablate_active: 2768/16000
ablate_active: 2770/16000
ablate_active: 2772/16000
ablate_active: 2774/16000
ablate_active: 2776/16000
ablate_active: 2778/16000
ablate_active: 2780/16000
ablate_active: 2782/16000
ablate_active: 2784/16000
ablate_active: 2786/16000
ablate_active: 2788/16000
ablate_active: 2790/16000
ablate_active: 2792/16000
ablate_active: 2794/16000
ablate_active: 2796/16000
ablate_active: 2798/16000
ablate_active: 2800/16000
ablate_active: 2802/16000
ablate_active: 2804/16000
ablate_active: 2806/16000
ablate_active: 2808/16000
ablate_active: 2810/16000
ablate_active: 2812/16000
ablate_active: 2814/16000
ablate_active: 2816/16000
ablate_active: 2818/16000
ablate_active: 2820/16000
ablate_active: 2822/16000
ablate_active: 2824/16000
ablate_active: 2826/16000
ablate_active: 2828/16000
ablate_active: 2830/16000
ablate_active: 2832/16000
ablate_active: 2834/16000
ablate_active: 2836/16000
ablate_active: 2838/16000
ablate_active: 2840/16000
ablate_active: 2842/16000
ablate_active: 2844/16000
ablate_active: 2846/16000
ablate_active: 2848/16000
ablate_active: 2850/16000
ablate_active: 2852/16000
ablate_active: 2854/16000
ablate_active: 2856/16000
ablate_active: 2858/16000
ablate_active: 2860/16000
ablate_active: 2862/16000
ablate_active: 2864/16000
ablate_active: 2866/16000
ablate_active: 2868/16000
ablate_active: 2870/16000
ablate_active: 2872/16000
ablate_active: 2874/16000
ablate_active: 2876/16000
ablate_active: 2878/16000
ablate_active: 2880/16000
ablate_active: 2882/16000
ablate_active: 2884/16000
ablate_active: 2886/16000
ablate_active: 2888/16000
ablate_active: 2890/16000
ablate_active: 2892/16000
ablate_active: 2894/16000
ablate_active: 2896/16000
ablate_active: 2898/16000
ablate_active: 2900/16000
ablate_active: 2902/16000
ablate_active: 2904/16000
ablate_active: 2906/16000
ablate_active: 2908/16000
ablate_active: 2910/16000
ablate_active: 2912/16000
ablate_active: 2914/16000
ablate_active: 2916/16000
ablate_active: 2918/16000
ablate_active: 2920/16000
ablate_active: 2922/16000
ablate_active: 2924/16000
ablate_active: 2926/16000
ablate_active: 2928/16000
ablate_active: 2930/16000
ablate_active: 2932/16000
ablate_active: 2934/16000
ablate_active: 2936/16000
ablate_active: 2938/16000
ablate_active: 2940/16000
ablate_active: 2942/16000
ablate_active: 2944/16000
ablate_active: 2946/16000
ablate_active: 2948/16000
ablate_active: 2950/16000
ablate_active: 2952/16000
ablate_active: 2954/16000
ablate_active: 2956/16000
ablate_active: 2958/16000
ablate_active: 2960/16000
ablate_active: 2962/16000
ablate_active: 2964/16000
ablate_active: 2966/16000
ablate_active: 2968/16000
ablate_active: 2970/16000
ablate_active: 2972/16000
ablate_active: 2974/16000
ablate_active: 2976/16000
ablate_active: 2978/16000
ablate_active: 2980/16000
ablate_active: 2982/16000
ablate_active: 2984/16000
ablate_active: 2986/16000
ablate_active: 2988/16000
ablate_active: 2990/16000
ablate_active: 2992/16000
ablate_active: 2994/16000
ablate_active: 2996/16000
ablate_active: 2998/16000
ablate_active: 3000/16000
ablate_active: 3002/16000
ablate_active: 3004/16000
ablate_active: 3006/16000
ablate_active: 3008/16000
ablate_active: 3010/16000
ablate_active: 3012/16000
ablate_active: 3014/16000
ablate_active: 3016/16000
ablate_active: 3018/16000
ablate_active: 3020/16000
ablate_active: 3022/16000
ablate_active: 3024/16000
ablate_active: 3026/16000
ablate_active: 3028/16000
ablate_active: 3030/16000
ablate_active: 3032/16000
ablate_active: 3034/16000
ablate_active: 3036/16000
ablate_active: 3038/16000
ablate_active: 3040/16000
ablate_active: 3042/16000
ablate_active: 3044/16000
ablate_active: 3046/16000
ablate_active: 3048/16000
ablate_active: 3050/16000
ablate_active: 3052/16000
ablate_active: 3054/16000
ablate_active: 3056/16000
ablate_active: 3058/16000
ablate_active: 3060/16000
ablate_active: 3062/16000
ablate_active: 3064/16000
ablate_active: 3066/16000
ablate_active: 3068/16000
ablate_active: 3070/16000
ablate_active: 3072/16000
ablate_active: 3074/16000
ablate_active: 3076/16000
ablate_active: 3078/16000
ablate_active: 3080/16000
ablate_active: 3082/16000
ablate_active: 3084/16000
ablate_active: 3086/16000
ablate_active: 3088/16000
ablate_active: 3090/16000
ablate_active: 3092/16000
ablate_active: 3094/16000
ablate_active: 3096/16000
ablate_active: 3098/16000
ablate_active: 3100/16000
ablate_active: 3102/16000
ablate_active: 3104/16000
ablate_active: 3106/16000
ablate_active: 3108/16000
ablate_active: 3110/16000
ablate_active: 3112/16000
ablate_active: 3114/16000
ablate_active: 3116/16000
ablate_active: 3118/16000
ablate_active: 3120/16000
ablate_active: 3122/16000
ablate_active: 3124/16000
ablate_active: 3126/16000
ablate_active: 3128/16000
ablate_active: 3130/16000
ablate_active: 3132/16000
ablate_active: 3134/16000
ablate_active: 3136/16000
ablate_active: 3138/16000
ablate_active: 3140/16000
ablate_active: 3142/16000
ablate_active: 3144/16000
ablate_active: 3146/16000
ablate_active: 3148/16000
ablate_active: 3150/16000
ablate_active: 3152/16000
ablate_active: 3154/16000
ablate_active: 3156/16000
ablate_active: 3158/16000
ablate_active: 3160/16000
ablate_active: 3162/16000
ablate_active: 3164/16000
ablate_active: 3166/16000
ablate_active: 3168/16000
ablate_active: 3170/16000
ablate_active: 3172/16000
ablate_active: 3174/16000
ablate_active: 3176/16000
ablate_active: 3178/16000
ablate_active: 3180/16000
ablate_active: 3182/16000
ablate_active: 3184/16000
ablate_active: 3186/16000
ablate_active: 3188/16000
ablate_active: 3190/16000
ablate_active: 3192/16000
ablate_active: 3194/16000
ablate_active: 3196/16000
ablate_active: 3198/16000
ablate_active: 3200/16000
ablate_active: 3202/16000
ablate_active: 3204/16000
ablate_active: 3206/16000
ablate_active: 3208/16000
ablate_active: 3210/16000

ablate_active: 3212/16000
ablate_active: 3214/16000
ablate_active: 3216/16000
ablate_active: 3218/16000
ablate_active: 3220/16000
ablate_active: 3222/16000
ablate_active: 3224/16000
ablate_active: 3226/16000
ablate_active: 3228/16000
ablate_active: 3230/16000
ablate_active: 3232/16000
ablate_active: 3234/16000
ablate_active: 3236/16000
ablate_active: 3238/16000
ablate_active: 3240/16000
ablate_active: 3242/16000
ablate_active: 3244/16000
ablate_active: 3246/16000
ablate_active: 3248/16000
ablate_active: 3250/16000
ablate_active: 3252/16000
ablate_active: 3254/16000
ablate_active: 3256/16000
ablate_active: 3258/16000
ablate_active: 3260/16000
ablate_active: 3262/16000
ablate_active: 3264/16000
ablate_active: 3266/16000
ablate_active: 3268/16000
ablate_active: 3270/16000
ablate_active: 3272/16000
ablate_active: 3274/16000
ablate_active: 3276/16000
ablate_active: 3278/16000
ablate_active: 3280/16000
ablate_active: 3282/16000
ablate_active: 3284/16000
ablate_active: 3286/16000
ablate_active: 3288/16000
ablate_active: 3290/16000
ablate_active: 3292/16000
ablate_active: 3294/16000
ablate_active: 3296/16000
ablate_active: 3298/16000
ablate_active: 3300/16000
ablate_active: 3302/16000
ablate_active: 3304/16000
ablate_active: 3306/16000
ablate_active: 3308/16000
ablate_active: 3310/16000
ablate_active: 3312/16000
ablate_active: 3314/16000
ablate_active: 3316/16000
ablate_active: 3318/16000
ablate_active: 3320/16000
ablate_active: 3322/16000
ablate_active: 3324/16000
ablate_active: 3326/16000
ablate_active: 3328/16000
ablate_active: 3330/16000
ablate_active: 3332/16000
ablate_active: 3334/16000
ablate_active: 3336/16000
ablate_active: 3338/16000
ablate_active: 3340/16000
ablate_active: 3342/16000
ablate_active: 3344/16000
ablate_active: 3346/16000
ablate_active: 3348/16000
ablate_active: 3350/16000
ablate_active: 3352/16000
ablate_active: 3354/16000
ablate_active: 3356/16000
ablate_active: 3358/16000
ablate_active: 3360/16000
ablate_active: 3362/16000
ablate_active: 3364/16000
ablate_active: 3366/16000
ablate_active: 3368/16000
ablate_active: 3370/16000
ablate_active: 3372/16000
ablate_active: 3374/16000
ablate_active: 3376/16000
ablate_active: 3378/16000
ablate_active: 3380/16000
ablate_active: 3382/16000
ablate_active: 3384/16000
ablate_active: 3386/16000
ablate_active: 3388/16000
ablate_active: 3390/16000
ablate_active: 3392/16000
ablate_active: 3394/16000
ablate_active: 3396/16000
ablate_active: 3398/16000
ablate_active: 3400/16000
ablate_active: 3402/16000
ablate_active: 3404/16000
ablate_active: 3406/16000
ablate_active: 3408/16000
ablate_active: 3410/16000
ablate_active: 3412/16000
ablate_active: 3414/16000
ablate_active: 3416/16000
ablate_active: 3418/16000
ablate_active: 3420/16000
ablate_active: 3422/16000
ablate_active: 3424/16000
ablate_active: 3426/16000
ablate_active: 3428/16000
ablate_active: 3430/16000
ablate_active: 3432/16000
ablate_active: 3434/16000
ablate_active: 3436/16000
ablate_active: 3438/16000
ablate_active: 3440/16000
ablate_active: 3442/16000
ablate_active: 3444/16000
ablate_active: 3446/16000
ablate_active: 3448/16000
ablate_active: 3450/16000
ablate_active: 3452/16000
ablate_active: 3454/16000
ablate_active: 3456/16000
ablate_active: 3458/16000
ablate_active: 3460/16000
ablate_active: 3462/16000
ablate_active: 3464/16000
ablate_active: 3466/16000
ablate_active: 3468/16000
ablate_active: 3470/16000
ablate_active: 3472/16000
ablate_active: 3474/16000
ablate_active: 3476/16000
ablate_active: 3478/16000
ablate_active: 3480/16000
ablate_active: 3482/16000
ablate_active: 3484/16000
ablate_active: 3486/16000
ablate_active: 3488/16000
ablate_active: 3490/16000
ablate_active: 3492/16000
ablate_active: 3494/16000
ablate_active: 3496/16000
ablate_active: 3498/16000
ablate_active: 3500/16000
ablate_active: 3502/16000
ablate_active: 3504/16000
ablate_active: 3506/16000
ablate_active: 3508/16000
ablate_active: 3510/16000
ablate_active: 3512/16000
ablate_active: 3514/16000
ablate_active: 3516/16000
ablate_active: 3518/16000
ablate_active: 3520/16000
ablate_active: 3522/16000
ablate_active: 3524/16000
ablate_active: 3526/16000
ablate_active: 3528/16000
ablate_active: 3530/16000
ablate_active: 3532/16000
ablate_active: 3534/16000
ablate_active: 3536/16000
ablate_active: 3538/16000
ablate_active: 3540/16000
ablate_active: 3542/16000
ablate_active: 3544/16000
ablate_active: 3546/16000
ablate_active: 3548/16000
ablate_active: 3550/16000
ablate_active: 3552/16000
ablate_active: 3554/16000
ablate_active: 3556/16000
ablate_active: 3558/16000
ablate_active: 3560/16000
ablate_active: 3562/16000
ablate_active: 3564/16000
ablate_active: 3566/16000
ablate_active: 3568/16000
ablate_active: 3570/16000
ablate_active: 3572/16000
ablate_active: 3574/16000
ablate_active: 3576/16000
ablate_active: 3578/16000
ablate_active: 3580/16000
ablate_active: 3582/16000
ablate_active: 3584/16000
ablate_active: 3586/16000
ablate_active: 3588/16000
ablate_active: 3590/16000
ablate_active: 3592/16000
ablate_active: 3594/16000
ablate_active: 3596/16000
ablate_active: 3598/16000
ablate_active: 3600/16000
ablate_active: 3602/16000
ablate_active: 3604/16000
ablate_active: 3606/16000
ablate_active: 3608/16000
ablate_active: 3610/16000
ablate_active: 3612/16000
ablate_active: 3614/16000
ablate_active: 3616/16000
ablate_active: 3618/16000
ablate_active: 3620/16000
ablate_active: 3622/16000
ablate_active: 3624/16000
ablate_active: 3626/16000
ablate_active: 3628/16000
ablate_active: 3630/16000
ablate_active: 3632/16000
ablate_active: 3634/16000
ablate_active: 3636/16000
ablate_active: 3638/16000
ablate_active: 3640/16000
ablate_active: 3642/16000
ablate_active: 3644/16000
ablate_active: 3646/16000
ablate_active: 3648/16000
ablate_active: 3650/16000
ablate_active: 3652/16000
ablate_active: 3654/16000
ablate_active: 3656/16000
ablate_active: 3658/16000
ablate_active: 3660/16000
ablate_active: 3662/16000
ablate_active: 3664/16000
ablate_active: 3666/16000
ablate_active: 3668/16000
ablate_active: 3670/16000
ablate_active: 3672/16000
ablate_active: 3674/16000
ablate_active: 3676/16000
ablate_active: 3678/16000
ablate_active: 3680/16000
ablate_active: 3682/16000
ablate_active: 3684/16000
ablate_active: 3686/16000
ablate_active: 3688/16000
ablate_active: 3690/16000
ablate_active: 3692/16000
ablate_active: 3694/16000
ablate_active: 3696/16000
ablate_active: 3698/16000
ablate_active: 3700/16000
ablate_active: 3702/16000
ablate_active: 3704/16000
ablate_active: 3706/16000
ablate_active: 3708/16000
ablate_active: 3710/16000
ablate_active: 3712/16000
ablate_active: 3714/16000
ablate_active: 3716/16000
ablate_active: 3718/16000
ablate_active: 3720/16000
ablate_active: 3722/16000
ablate_active: 3724/16000
ablate_active: 3726/16000
ablate_active: 3728/16000
ablate_active: 3730/16000
ablate_active: 3732/16000
ablate_active: 3734/16000
ablate_active: 3736/16000
ablate_active: 3738/16000
ablate_active: 3740/16000
ablate_active: 3742/16000
ablate_active: 3744/16000
ablate_active: 3746/16000
ablate_active: 3748/16000
ablate_active: 3750/16000
ablate_active: 3752/16000
ablate_active: 3754/16000
ablate_active: 3756/16000
ablate_active: 3758/16000
ablate_active: 3760/16000
ablate_active: 3762/16000
ablate_active: 3764/16000
ablate_active: 3766/16000
ablate_active: 3768/16000
ablate_active: 3770/16000
ablate_active: 3772/16000
ablate_active: 3774/16000
ablate_active: 3776/16000
ablate_active: 3778/16000
ablate_active: 3780/16000
ablate_active: 3782/16000
ablate_active: 3784/16000
ablate_active: 3786/16000
ablate_active: 3788/16000
ablate_active: 3790/16000
ablate_active: 3792/16000
ablate_active: 3794/16000
ablate_active: 3796/16000
ablate_active: 3798/16000
ablate_active: 3800/16000
ablate_active: 3802/16000
ablate_active: 3804/16000
ablate_active: 3806/16000
ablate_active: 3808/16000
ablate_active: 3810/16000
ablate_active: 3812/16000
ablate_active: 3814/16000
ablate_active: 3816/16000
ablate_active: 3818/16000
ablate_active: 3820/16000
ablate_active: 3822/16000
ablate_active: 3824/16000
ablate_active: 3826/16000
ablate_active: 3828/16000
ablate_active: 3830/16000
ablate_active: 3832/16000
ablate_active: 3834/16000
ablate_active: 3836/16000
ablate_active: 3838/16000
ablate_active: 3840/16000
ablate_active: 3842/16000
ablate_active: 3844/16000
ablate_active: 3846/16000

ablate_active: 3848/16000
ablate_active: 3850/16000
ablate_active: 3852/16000
ablate_active: 3854/16000
ablate_active: 3856/16000
ablate_active: 3858/16000
ablate_active: 3860/16000
ablate_active: 3862/16000
ablate_active: 3864/16000
ablate_active: 3866/16000
ablate_active: 3868/16000
ablate_active: 3870/16000
ablate_active: 3872/16000
ablate_active: 3874/16000
ablate_active: 3876/16000
ablate_active: 3878/16000
ablate_active: 3880/16000
ablate_active: 3882/16000
ablate_active: 3884/16000
ablate_active: 3886/16000
ablate_active: 3888/16000
ablate_active: 3890/16000
ablate_active: 3892/16000
ablate_active: 3894/16000
ablate_active: 3896/16000
ablate_active: 3898/16000
ablate_active: 3900/16000
ablate_active: 3902/16000
ablate_active: 3904/16000
ablate_active: 3906/16000
ablate_active: 3908/16000
ablate_active: 3910/16000
ablate_active: 3912/16000
ablate_active: 3914/16000
ablate_active: 3916/16000
ablate_active: 3918/16000
ablate_active: 3920/16000
ablate_active: 3922/16000
ablate_active: 3924/16000
ablate_active: 3926/16000
ablate_active: 3928/16000
ablate_active: 3930/16000
ablate_active: 3932/16000
ablate_active: 3934/16000
ablate_active: 3936/16000
ablate_active: 3938/16000
ablate_active: 3940/16000
ablate_active: 3942/16000
ablate_active: 3944/16000
ablate_active: 3946/16000
ablate_active: 3948/16000
ablate_active: 3950/16000
ablate_active: 3952/16000
ablate_active: 3954/16000
ablate_active: 3956/16000
ablate_active: 3958/16000
ablate_active: 3960/16000
ablate_active: 3962/16000
ablate_active: 3964/16000
ablate_active: 3966/16000
ablate_active: 3968/16000
ablate_active: 3970/16000
ablate_active: 3972/16000
ablate_active: 3974/16000
ablate_active: 3976/16000
ablate_active: 3978/16000
ablate_active: 3980/16000
ablate_active: 3982/16000
ablate_active: 3984/16000
ablate_active: 3986/16000
ablate_active: 3988/16000
ablate_active: 3990/16000
ablate_active: 3992/16000
ablate_active: 3994/16000
ablate_active: 3996/16000
ablate_active: 3998/16000
ablate_active: 4000/16000
ablate_active: 4002/16000
ablate_active: 4004/16000
ablate_active: 4006/16000
ablate_active: 4008/16000
ablate_active: 4010/16000
ablate_active: 4012/16000
ablate_active: 4014/16000
ablate_active: 4016/16000
ablate_active: 4018/16000
ablate_active: 4020/16000
ablate_active: 4022/16000
ablate_active: 4024/16000
ablate_active: 4026/16000
ablate_active: 4028/16000
ablate_active: 4030/16000
ablate_active: 4032/16000
ablate_active: 4034/16000
ablate_active: 4036/16000
ablate_active: 4038/16000
ablate_active: 4040/16000
ablate_active: 4042/16000
ablate_active: 4044/16000
ablate_active: 4046/16000
ablate_active: 4048/16000
ablate_active: 4050/16000
ablate_active: 4052/16000
ablate_active: 4054/16000
ablate_active: 4056/16000
ablate_active: 4058/16000
ablate_active: 4060/16000
ablate_active: 4062/16000
ablate_active: 4064/16000
ablate_active: 4066/16000
ablate_active: 4068/16000
ablate_active: 4070/16000
ablate_active: 4072/16000
ablate_active: 4074/16000
ablate_active: 4076/16000
ablate_active: 4078/16000
ablate_active: 4080/16000
ablate_active: 4082/16000
ablate_active: 4084/16000
ablate_active: 4086/16000
ablate_active: 4088/16000
ablate_active: 4090/16000
ablate_active: 4092/16000
ablate_active: 4094/16000
ablate_active: 4096/16000
ablate_active: 4098/16000
ablate_active: 4100/16000
ablate_active: 4102/16000
ablate_active: 4104/16000
ablate_active: 4106/16000
ablate_active: 4108/16000
ablate_active: 4110/16000
ablate_active: 4112/16000
ablate_active: 4114/16000
ablate_active: 4116/16000
ablate_active: 4118/16000
ablate_active: 4120/16000
ablate_active: 4122/16000
ablate_active: 4124/16000
ablate_active: 4126/16000
ablate_active: 4128/16000
ablate_active: 4130/16000
ablate_active: 4132/16000
ablate_active: 4134/16000
ablate_active: 4136/16000
ablate_active: 4138/16000
ablate_active: 4140/16000
ablate_active: 4142/16000
ablate_active: 4144/16000
ablate_active: 4146/16000
ablate_active: 4148/16000
ablate_active: 4150/16000
ablate_active: 4152/16000
ablate_active: 4154/16000
ablate_active: 4156/16000
ablate_active: 4158/16000
ablate_active: 4160/16000
ablate_active: 4162/16000
ablate_active: 4164/16000
ablate_active: 4166/16000
ablate_active: 4168/16000
ablate_active: 4170/16000
ablate_active: 4172/16000
ablate_active: 4174/16000
ablate_active: 4176/16000
ablate_active: 4178/16000
ablate_active: 4180/16000
ablate_active: 4182/16000
ablate_active: 4184/16000
ablate_active: 4186/16000
ablate_active: 4188/16000
ablate_active: 4190/16000
ablate_active: 4192/16000
ablate_active: 4194/16000
ablate_active: 4196/16000
ablate_active: 4198/16000
ablate_active: 4200/16000
ablate_active: 4202/16000
ablate_active: 4204/16000
ablate_active: 4206/16000
ablate_active: 4208/16000
ablate_active: 4210/16000
ablate_active: 4212/16000
ablate_active: 4214/16000
ablate_active: 4216/16000
ablate_active: 4218/16000
ablate_active: 4220/16000
ablate_active: 4222/16000
ablate_active: 4224/16000
ablate_active: 4226/16000
ablate_active: 4228/16000
ablate_active: 4230/16000
ablate_active: 4232/16000
ablate_active: 4234/16000
ablate_active: 4236/16000
ablate_active: 4238/16000
ablate_active: 4240/16000
ablate_active: 4242/16000
ablate_active: 4244/16000
ablate_active: 4246/16000
ablate_active: 4248/16000
ablate_active: 4250/16000
ablate_active: 4252/16000
ablate_active: 4254/16000
ablate_active: 4256/16000
ablate_active: 4258/16000
ablate_active: 4260/16000
ablate_active: 4262/16000
ablate_active: 4264/16000
ablate_active: 4266/16000
ablate_active: 4268/16000
ablate_active: 4270/16000
ablate_active: 4272/16000
ablate_active: 4274/16000
ablate_active: 4276/16000
ablate_active: 4278/16000
ablate_active: 4280/16000
ablate_active: 4282/16000
ablate_active: 4284/16000
ablate_active: 4286/16000
ablate_active: 4288/16000
ablate_active: 4290/16000
ablate_active: 4292/16000
ablate_active: 4294/16000
ablate_active: 4296/16000
ablate_active: 4298/16000
ablate_active: 4300/16000
ablate_active: 4302/16000
ablate_active: 4304/16000
ablate_active: 4306/16000
ablate_active: 4308/16000
ablate_active: 4310/16000
ablate_active: 4312/16000
ablate_active: 4314/16000
ablate_active: 4316/16000
ablate_active: 4318/16000
ablate_active: 4320/16000
ablate_active: 4322/16000
ablate_active: 4324/16000
ablate_active: 4326/16000
ablate_active: 4328/16000
ablate_active: 4330/16000
ablate_active: 4332/16000
ablate_active: 4334/16000
ablate_active: 4336/16000
ablate_active: 4338/16000
ablate_active: 4340/16000
ablate_active: 4342/16000
ablate_active: 4344/16000
ablate_active: 4346/16000
ablate_active: 4348/16000
ablate_active: 4350/16000
ablate_active: 4352/16000
ablate_active: 4354/16000
ablate_active: 4356/16000
ablate_active: 4358/16000
ablate_active: 4360/16000
ablate_active: 4362/16000
ablate_active: 4364/16000
ablate_active: 4366/16000
ablate_active: 4368/16000
ablate_active: 4370/16000
ablate_active: 4372/16000
ablate_active: 4374/16000
ablate_active: 4376/16000
ablate_active: 4378/16000
ablate_active: 4380/16000
ablate_active: 4382/16000
ablate_active: 4384/16000
ablate_active: 4386/16000
ablate_active: 4388/16000
ablate_active: 4390/16000
ablate_active: 4392/16000
ablate_active: 4394/16000
ablate_active: 4396/16000
ablate_active: 4398/16000
ablate_active: 4400/16000
ablate_active: 4402/16000
ablate_active: 4404/16000
ablate_active: 4406/16000
ablate_active: 4408/16000
ablate_active: 4410/16000
ablate_active: 4412/16000
ablate_active: 4414/16000
ablate_active: 4416/16000
ablate_active: 4418/16000
ablate_active: 4420/16000
ablate_active: 4422/16000
ablate_active: 4424/16000
ablate_active: 4426/16000
ablate_active: 4428/16000
ablate_active: 4430/16000
ablate_active: 4432/16000
ablate_active: 4434/16000
ablate_active: 4436/16000
ablate_active: 4438/16000
ablate_active: 4440/16000
ablate_active: 4442/16000
ablate_active: 4444/16000
ablate_active: 4446/16000
ablate_active: 4448/16000
ablate_active: 4450/16000
ablate_active: 4452/16000
ablate_active: 4454/16000
ablate_active: 4456/16000
ablate_active: 4458/16000
ablate_active: 4460/16000
ablate_active: 4462/16000
ablate_active: 4464/16000
ablate_active: 4466/16000
ablate_active: 4468/16000
ablate_active: 4470/16000
ablate_active: 4472/16000
ablate_active: 4474/16000
ablate_active: 4476/16000
ablate_active: 4478/16000
ablate_active: 4480/16000

ablate_active: 4482/16000
ablate_active: 4484/16000
ablate_active: 4486/16000
ablate_active: 4488/16000
ablate_active: 4490/16000
ablate_active: 4492/16000
ablate_active: 4494/16000
ablate_active: 4496/16000
ablate_active: 4498/16000
ablate_active: 4500/16000
ablate_active: 4502/16000
ablate_active: 4504/16000
ablate_active: 4506/16000
ablate_active: 4508/16000
ablate_active: 4510/16000
ablate_active: 4512/16000
ablate_active: 4514/16000
ablate_active: 4516/16000
ablate_active: 4518/16000
ablate_active: 4520/16000
ablate_active: 4522/16000
ablate_active: 4524/16000
ablate_active: 4526/16000
ablate_active: 4528/16000
ablate_active: 4530/16000
ablate_active: 4532/16000
ablate_active: 4534/16000
ablate_active: 4536/16000
ablate_active: 4538/16000
ablate_active: 4540/16000
ablate_active: 4542/16000
ablate_active: 4544/16000
ablate_active: 4546/16000
ablate_active: 4548/16000
ablate_active: 4550/16000
ablate_active: 4552/16000
ablate_active: 4554/16000
ablate_active: 4556/16000
ablate_active: 4558/16000
ablate_active: 4560/16000
ablate_active: 4562/16000
ablate_active: 4564/16000
ablate_active: 4566/16000
ablate_active: 4568/16000
ablate_active: 4570/16000
ablate_active: 4572/16000
ablate_active: 4574/16000
ablate_active: 4576/16000
ablate_active: 4578/16000
ablate_active: 4580/16000
ablate_active: 4582/16000
ablate_active: 4584/16000
ablate_active: 4586/16000
ablate_active: 4588/16000
ablate_active: 4590/16000
ablate_active: 4592/16000
ablate_active: 4594/16000
ablate_active: 4596/16000
ablate_active: 4598/16000
ablate_active: 4600/16000
ablate_active: 4602/16000
ablate_active: 4604/16000
ablate_active: 4606/16000
ablate_active: 4608/16000
ablate_active: 4610/16000
ablate_active: 4612/16000
ablate_active: 4614/16000
ablate_active: 4616/16000
ablate_active: 4618/16000
ablate_active: 4620/16000
ablate_active: 4622/16000
ablate_active: 4624/16000
ablate_active: 4626/16000
ablate_active: 4628/16000
ablate_active: 4630/16000
ablate_active: 4632/16000
ablate_active: 4634/16000
ablate_active: 4636/16000
ablate_active: 4638/16000
ablate_active: 4640/16000
ablate_active: 4642/16000
ablate_active: 4644/16000
ablate_active: 4646/16000
ablate_active: 4648/16000
ablate_active: 4650/16000
ablate_active: 4652/16000
ablate_active: 4654/16000
ablate_active: 4656/16000
ablate_active: 4658/16000
ablate_active: 4660/16000
ablate_active: 4662/16000
ablate_active: 4664/16000
ablate_active: 4666/16000
ablate_active: 4668/16000
ablate_active: 4670/16000
ablate_active: 4672/16000
ablate_active: 4674/16000
ablate_active: 4676/16000
ablate_active: 4678/16000
ablate_active: 4680/16000
ablate_active: 4682/16000
ablate_active: 4684/16000
ablate_active: 4686/16000
ablate_active: 4688/16000
ablate_active: 4690/16000
ablate_active: 4692/16000
ablate_active: 4694/16000
ablate_active: 4696/16000
ablate_active: 4698/16000
ablate_active: 4700/16000
ablate_active: 4702/16000
ablate_active: 4704/16000
ablate_active: 4706/16000
ablate_active: 4708/16000
ablate_active: 4710/16000
ablate_active: 4712/16000
ablate_active: 4714/16000
ablate_active: 4716/16000
ablate_active: 4718/16000
ablate_active: 4720/16000
ablate_active: 4722/16000
ablate_active: 4724/16000
ablate_active: 4726/16000
ablate_active: 4728/16000
ablate_active: 4730/16000
ablate_active: 4732/16000
ablate_active: 4734/16000
ablate_active: 4736/16000
ablate_active: 4738/16000
ablate_active: 4740/16000
ablate_active: 4742/16000
ablate_active: 4744/16000
ablate_active: 4746/16000
ablate_active: 4748/16000
ablate_active: 4750/16000
ablate_active: 4752/16000
ablate_active: 4754/16000
ablate_active: 4756/16000
ablate_active: 4758/16000
ablate_active: 4760/16000
ablate_active: 4762/16000
ablate_active: 4764/16000
ablate_active: 4766/16000
ablate_active: 4768/16000
ablate_active: 4770/16000
ablate_active: 4772/16000
ablate_active: 4774/16000
ablate_active: 4776/16000
ablate_active: 4778/16000
ablate_active: 4780/16000
ablate_active: 4782/16000
ablate_active: 4784/16000
ablate_active: 4786/16000
ablate_active: 4788/16000
ablate_active: 4790/16000
ablate_active: 4792/16000
ablate_active: 4794/16000
ablate_active: 4796/16000
ablate_active: 4798/16000
ablate_active: 4800/16000
ablate_active: 4802/16000
ablate_active: 4804/16000
ablate_active: 4806/16000
ablate_active: 4808/16000
ablate_active: 4810/16000
ablate_active: 4812/16000
ablate_active: 4814/16000
ablate_active: 4816/16000
ablate_active: 4818/16000
ablate_active: 4820/16000
ablate_active: 4822/16000
ablate_active: 4824/16000
ablate_active: 4826/16000
ablate_active: 4828/16000
ablate_active: 4830/16000
ablate_active: 4832/16000
ablate_active: 4834/16000
ablate_active: 4836/16000
ablate_active: 4838/16000
ablate_active: 4840/16000
ablate_active: 4842/16000
ablate_active: 4844/16000
ablate_active: 4846/16000
ablate_active: 4848/16000
ablate_active: 4850/16000
ablate_active: 4852/16000
ablate_active: 4854/16000
ablate_active: 4856/16000
ablate_active: 4858/16000
ablate_active: 4860/16000
ablate_active: 4862/16000
ablate_active: 4864/16000
ablate_active: 4866/16000
ablate_active: 4868/16000
ablate_active: 4870/16000
ablate_active: 4872/16000
ablate_active: 4874/16000
ablate_active: 4876/16000
ablate_active: 4878/16000
ablate_active: 4880/16000
ablate_active: 4882/16000
ablate_active: 4884/16000
ablate_active: 4886/16000
ablate_active: 4888/16000
ablate_active: 4890/16000
ablate_active: 4892/16000
ablate_active: 4894/16000
ablate_active: 4896/16000
ablate_active: 4898/16000
ablate_active: 4900/16000
ablate_active: 4902/16000
ablate_active: 4904/16000
ablate_active: 4906/16000
ablate_active: 4908/16000
ablate_active: 4910/16000
ablate_active: 4912/16000
ablate_active: 4914/16000
ablate_active: 4916/16000
ablate_active: 4918/16000
ablate_active: 4920/16000
ablate_active: 4922/16000
ablate_active: 4924/16000
ablate_active: 4926/16000
ablate_active: 4928/16000
ablate_active: 4930/16000
ablate_active: 4932/16000
ablate_active: 4934/16000
ablate_active: 4936/16000
ablate_active: 4938/16000
ablate_active: 4940/16000
ablate_active: 4942/16000
ablate_active: 4944/16000
ablate_active: 4946/16000
ablate_active: 4948/16000
ablate_active: 4950/16000
ablate_active: 4952/16000
ablate_active: 4954/16000
ablate_active: 4956/16000
ablate_active: 4958/16000
ablate_active: 4960/16000
ablate_active: 4962/16000
ablate_active: 4964/16000
ablate_active: 4966/16000
ablate_active: 4968/16000
ablate_active: 4970/16000
ablate_active: 4972/16000
ablate_active: 4974/16000
ablate_active: 4976/16000
ablate_active: 4978/16000
ablate_active: 4980/16000
ablate_active: 4982/16000
ablate_active: 4984/16000
ablate_active: 4986/16000
ablate_active: 4988/16000
ablate_active: 4990/16000
ablate_active: 4992/16000
ablate_active: 4994/16000
ablate_active: 4996/16000
ablate_active: 4998/16000
ablate_active: 5000/16000
ablate_active: 5002/16000
ablate_active: 5004/16000
ablate_active: 5006/16000
ablate_active: 5008/16000
ablate_active: 5010/16000
ablate_active: 5012/16000
ablate_active: 5014/16000
ablate_active: 5016/16000
ablate_active: 5018/16000
ablate_active: 5020/16000
ablate_active: 5022/16000
ablate_active: 5024/16000
ablate_active: 5026/16000
ablate_active: 5028/16000
ablate_active: 5030/16000
ablate_active: 5032/16000
ablate_active: 5034/16000
ablate_active: 5036/16000
ablate_active: 5038/16000
ablate_active: 5040/16000
ablate_active: 5042/16000
ablate_active: 5044/16000
ablate_active: 5046/16000
ablate_active: 5048/16000
ablate_active: 5050/16000
ablate_active: 5052/16000
ablate_active: 5054/16000
ablate_active: 5056/16000
ablate_active: 5058/16000
ablate_active: 5060/16000
ablate_active: 5062/16000
ablate_active: 5064/16000
ablate_active: 5066/16000
ablate_active: 5068/16000
ablate_active: 5070/16000
ablate_active: 5072/16000
ablate_active: 5074/16000
ablate_active: 5076/16000
ablate_active: 5078/16000
ablate_active: 5080/16000
ablate_active: 5082/16000
ablate_active: 5084/16000
ablate_active: 5086/16000
ablate_active: 5088/16000
ablate_active: 5090/16000
ablate_active: 5092/16000
ablate_active: 5094/16000
ablate_active: 5096/16000
ablate_active: 5098/16000
ablate_active: 5100/16000
ablate_active: 5102/16000
ablate_active: 5104/16000
ablate_active: 5106/16000
ablate_active: 5108/16000
ablate_active: 5110/16000
ablate_active: 5112/16000
ablate_active: 5114/16000
ablate_active: 5116/16000

ablate_active: 5118/16000
ablate_active: 5120/16000
ablate_active: 5122/16000
ablate_active: 5124/16000
ablate_active: 5126/16000
ablate_active: 5128/16000
ablate_active: 5130/16000
ablate_active: 5132/16000
ablate_active: 5134/16000
ablate_active: 5136/16000
ablate_active: 5138/16000
ablate_active: 5140/16000
ablate_active: 5142/16000
ablate_active: 5144/16000
ablate_active: 5146/16000
ablate_active: 5148/16000
ablate_active: 5150/16000
ablate_active: 5152/16000
ablate_active: 5154/16000
ablate_active: 5156/16000
ablate_active: 5158/16000
ablate_active: 5160/16000
ablate_active: 5162/16000
ablate_active: 5164/16000
ablate_active: 5166/16000
ablate_active: 5168/16000
ablate_active: 5170/16000
ablate_active: 5172/16000
ablate_active: 5174/16000
ablate_active: 5176/16000
ablate_active: 5178/16000
ablate_active: 5180/16000
ablate_active: 5182/16000
ablate_active: 5184/16000
ablate_active: 5186/16000
ablate_active: 5188/16000
ablate_active: 5190/16000
ablate_active: 5192/16000
ablate_active: 5194/16000
ablate_active: 5196/16000
ablate_active: 5198/16000
ablate_active: 5200/16000
ablate_active: 5202/16000
ablate_active: 5204/16000
ablate_active: 5206/16000
ablate_active: 5208/16000
ablate_active: 5210/16000
ablate_active: 5212/16000
ablate_active: 5214/16000
ablate_active: 5216/16000
ablate_active: 5218/16000
ablate_active: 5220/16000
ablate_active: 5222/16000
ablate_active: 5224/16000
ablate_active: 5226/16000
ablate_active: 5228/16000
ablate_active: 5230/16000
ablate_active: 5232/16000
ablate_active: 5234/16000
ablate_active: 5236/16000
ablate_active: 5238/16000
ablate_active: 5240/16000
ablate_active: 5242/16000
ablate_active: 5244/16000
ablate_active: 5246/16000
ablate_active: 5248/16000
ablate_active: 5250/16000
ablate_active: 5252/16000
ablate_active: 5254/16000
ablate_active: 5256/16000
ablate_active: 5258/16000
ablate_active: 5260/16000
ablate_active: 5262/16000
ablate_active: 5264/16000
ablate_active: 5266/16000
ablate_active: 5268/16000
ablate_active: 5270/16000
ablate_active: 5272/16000
ablate_active: 5274/16000
ablate_active: 5276/16000
ablate_active: 5278/16000
ablate_active: 5280/16000
ablate_active: 5282/16000
ablate_active: 5284/16000
ablate_active: 5286/16000
ablate_active: 5288/16000
ablate_active: 5290/16000
ablate_active: 5292/16000
ablate_active: 5294/16000
ablate_active: 5296/16000
ablate_active: 5298/16000
ablate_active: 5300/16000
ablate_active: 5302/16000
ablate_active: 5304/16000
ablate_active: 5306/16000
ablate_active: 5308/16000
ablate_active: 5310/16000
ablate_active: 5312/16000
ablate_active: 5314/16000
ablate_active: 5316/16000
ablate_active: 5318/16000
ablate_active: 5320/16000
ablate_active: 5322/16000
ablate_active: 5324/16000
ablate_active: 5326/16000
ablate_active: 5328/16000
ablate_active: 5330/16000
ablate_active: 5332/16000
ablate_active: 5334/16000
ablate_active: 5336/16000
ablate_active: 5338/16000
ablate_active: 5340/16000
ablate_active: 5342/16000
ablate_active: 5344/16000
ablate_active: 5346/16000
ablate_active: 5348/16000
ablate_active: 5350/16000
ablate_active: 5352/16000
ablate_active: 5354/16000
ablate_active: 5356/16000
ablate_active: 5358/16000
ablate_active: 5360/16000
ablate_active: 5362/16000
ablate_active: 5364/16000
ablate_active: 5366/16000
ablate_active: 5368/16000
ablate_active: 5370/16000
ablate_active: 5372/16000
ablate_active: 5374/16000
ablate_active: 5376/16000
ablate_active: 5378/16000
ablate_active: 5380/16000
ablate_active: 5382/16000
ablate_active: 5384/16000
ablate_active: 5386/16000
ablate_active: 5388/16000
ablate_active: 5390/16000
ablate_active: 5392/16000
ablate_active: 5394/16000
ablate_active: 5396/16000
ablate_active: 5398/16000
ablate_active: 5400/16000
ablate_active: 5402/16000
ablate_active: 5404/16000
ablate_active: 5406/16000
ablate_active: 5408/16000
ablate_active: 5410/16000
ablate_active: 5412/16000
ablate_active: 5414/16000
ablate_active: 5416/16000
ablate_active: 5418/16000
ablate_active: 5420/16000
ablate_active: 5422/16000
ablate_active: 5424/16000
ablate_active: 5426/16000
ablate_active: 5428/16000
ablate_active: 5430/16000
ablate_active: 5432/16000
ablate_active: 5434/16000
ablate_active: 5436/16000
ablate_active: 5438/16000
ablate_active: 5440/16000
ablate_active: 5442/16000
ablate_active: 5444/16000
ablate_active: 5446/16000
ablate_active: 5448/16000
ablate_active: 5450/16000
ablate_active: 5452/16000
ablate_active: 5454/16000
ablate_active: 5456/16000
ablate_active: 5458/16000
ablate_active: 5460/16000
ablate_active: 5462/16000
ablate_active: 5464/16000
ablate_active: 5466/16000
ablate_active: 5468/16000
ablate_active: 5470/16000
ablate_active: 5472/16000
ablate_active: 5474/16000
ablate_active: 5476/16000
ablate_active: 5478/16000
ablate_active: 5480/16000
ablate_active: 5482/16000
ablate_active: 5484/16000
ablate_active: 5486/16000
ablate_active: 5488/16000
ablate_active: 5490/16000
ablate_active: 5492/16000
ablate_active: 5494/16000
ablate_active: 5496/16000
ablate_active: 5498/16000
ablate_active: 5500/16000
ablate_active: 5502/16000
ablate_active: 5504/16000
ablate_active: 5506/16000
ablate_active: 5508/16000
ablate_active: 5510/16000
ablate_active: 5512/16000
ablate_active: 5514/16000
ablate_active: 5516/16000
ablate_active: 5518/16000
ablate_active: 5520/16000
ablate_active: 5522/16000
ablate_active: 5524/16000
ablate_active: 5526/16000
ablate_active: 5528/16000
ablate_active: 5530/16000
ablate_active: 5532/16000
ablate_active: 5534/16000
ablate_active: 5536/16000
ablate_active: 5538/16000
ablate_active: 5540/16000
ablate_active: 5542/16000
ablate_active: 5544/16000
ablate_active: 5546/16000
ablate_active: 5548/16000
ablate_active: 5550/16000
ablate_active: 5552/16000
ablate_active: 5554/16000
ablate_active: 5556/16000
ablate_active: 5558/16000
ablate_active: 5560/16000
ablate_active: 5562/16000
ablate_active: 5564/16000
ablate_active: 5566/16000
ablate_active: 5568/16000
ablate_active: 5570/16000
ablate_active: 5572/16000
ablate_active: 5574/16000
ablate_active: 5576/16000
ablate_active: 5578/16000
ablate_active: 5580/16000
ablate_active: 5582/16000
ablate_active: 5584/16000
ablate_active: 5586/16000
ablate_active: 5588/16000
ablate_active: 5590/16000
ablate_active: 5592/16000
ablate_active: 5594/16000
ablate_active: 5596/16000
ablate_active: 5598/16000
ablate_active: 5600/16000
ablate_active: 5602/16000
ablate_active: 5604/16000
ablate_active: 5606/16000
ablate_active: 5608/16000
ablate_active: 5610/16000
ablate_active: 5612/16000
ablate_active: 5614/16000
ablate_active: 5616/16000
ablate_active: 5618/16000
ablate_active: 5620/16000
ablate_active: 5622/16000
ablate_active: 5624/16000
ablate_active: 5626/16000
ablate_active: 5628/16000
ablate_active: 5630/16000
ablate_active: 5632/16000
ablate_active: 5634/16000
ablate_active: 5636/16000
ablate_active: 5638/16000
ablate_active: 5640/16000
ablate_active: 5642/16000
ablate_active: 5644/16000
ablate_active: 5646/16000
ablate_active: 5648/16000
ablate_active: 5650/16000
ablate_active: 5652/16000
ablate_active: 5654/16000
ablate_active: 5656/16000
ablate_active: 5658/16000
ablate_active: 5660/16000
ablate_active: 5662/16000
ablate_active: 5664/16000
ablate_active: 5666/16000
ablate_active: 5668/16000
ablate_active: 5670/16000
ablate_active: 5672/16000
ablate_active: 5674/16000
ablate_active: 5676/16000
ablate_active: 5678/16000
ablate_active: 5680/16000
ablate_active: 5682/16000
ablate_active: 5684/16000
ablate_active: 5686/16000
ablate_active: 5688/16000
ablate_active: 5690/16000
ablate_active: 5692/16000
ablate_active: 5694/16000
ablate_active: 5696/16000
ablate_active: 5698/16000
ablate_active: 5700/16000
ablate_active: 5702/16000
ablate_active: 5704/16000
ablate_active: 5706/16000
ablate_active: 5708/16000
ablate_active: 5710/16000
ablate_active: 5712/16000
ablate_active: 5714/16000
ablate_active: 5716/16000
ablate_active: 5718/16000
ablate_active: 5720/16000
ablate_active: 5722/16000
ablate_active: 5724/16000
ablate_active: 5726/16000
ablate_active: 5728/16000
ablate_active: 5730/16000
ablate_active: 5732/16000
ablate_active: 5734/16000
ablate_active: 5736/16000
ablate_active: 5738/16000
ablate_active: 5740/16000
ablate_active: 5742/16000
ablate_active: 5744/16000
ablate_active: 5746/16000
ablate_active: 5748/16000

ablate_active: 5750/16000
ablate_active: 5752/16000
ablate_active: 5754/16000
ablate_active: 5756/16000
ablate_active: 5758/16000
ablate_active: 5760/16000
ablate_active: 5762/16000
ablate_active: 5764/16000
ablate_active: 5766/16000
ablate_active: 5768/16000
ablate_active: 5770/16000
ablate_active: 5772/16000
ablate_active: 5774/16000
ablate_active: 5776/16000
ablate_active: 5778/16000
ablate_active: 5780/16000
ablate_active: 5782/16000
ablate_active: 5784/16000
ablate_active: 5786/16000
ablate_active: 5788/16000
ablate_active: 5790/16000
ablate_active: 5792/16000
ablate_active: 5794/16000
ablate_active: 5796/16000
ablate_active: 5798/16000
ablate_active: 5800/16000
ablate_active: 5802/16000
ablate_active: 5804/16000
ablate_active: 5806/16000
ablate_active: 5808/16000
ablate_active: 5810/16000
ablate_active: 5812/16000
ablate_active: 5814/16000
ablate_active: 5816/16000
ablate_active: 5818/16000
ablate_active: 5820/16000
ablate_active: 5822/16000
ablate_active: 5824/16000
ablate_active: 5826/16000
ablate_active: 5828/16000
ablate_active: 5830/16000
ablate_active: 5832/16000
ablate_active: 5834/16000
ablate_active: 5836/16000
ablate_active: 5838/16000
ablate_active: 5840/16000
ablate_active: 5842/16000
ablate_active: 5844/16000
ablate_active: 5846/16000
ablate_active: 5848/16000
ablate_active: 5850/16000
ablate_active: 5852/16000
ablate_active: 5854/16000
ablate_active: 5856/16000
ablate_active: 5858/16000
ablate_active: 5860/16000
ablate_active: 5862/16000
ablate_active: 5864/16000
ablate_active: 5866/16000
ablate_active: 5868/16000
ablate_active: 5870/16000
ablate_active: 5872/16000
ablate_active: 5874/16000
ablate_active: 5876/16000
ablate_active: 5878/16000
ablate_active: 5880/16000
ablate_active: 5882/16000
ablate_active: 5884/16000
ablate_active: 5886/16000
ablate_active: 5888/16000
ablate_active: 5890/16000
ablate_active: 5892/16000
ablate_active: 5894/16000
ablate_active: 5896/16000
ablate_active: 5898/16000
ablate_active: 5900/16000
ablate_active: 5902/16000
ablate_active: 5904/16000
ablate_active: 5906/16000
ablate_active: 5908/16000
ablate_active: 5910/16000
ablate_active: 5912/16000
ablate_active: 5914/16000
ablate_active: 5916/16000
ablate_active: 5918/16000
ablate_active: 5920/16000
ablate_active: 5922/16000
ablate_active: 5924/16000
ablate_active: 5926/16000
ablate_active: 5928/16000
ablate_active: 5930/16000
ablate_active: 5932/16000
ablate_active: 5934/16000
ablate_active: 5936/16000
ablate_active: 5938/16000
ablate_active: 5940/16000
ablate_active: 5942/16000
ablate_active: 5944/16000
ablate_active: 5946/16000
ablate_active: 5948/16000
ablate_active: 5950/16000
ablate_active: 5952/16000
ablate_active: 5954/16000
ablate_active: 5956/16000
ablate_active: 5958/16000
ablate_active: 5960/16000
ablate_active: 5962/16000
ablate_active: 5964/16000
ablate_active: 5966/16000
ablate_active: 5968/16000
ablate_active: 5970/16000
ablate_active: 5972/16000
ablate_active: 5974/16000
ablate_active: 5976/16000
ablate_active: 5978/16000
ablate_active: 5980/16000
ablate_active: 5982/16000
ablate_active: 5984/16000
ablate_active: 5986/16000
ablate_active: 5988/16000
ablate_active: 5990/16000
ablate_active: 5992/16000
ablate_active: 5994/16000
ablate_active: 5996/16000
ablate_active: 5998/16000
ablate_active: 6000/16000
ablate_active: 6002/16000
ablate_active: 6004/16000
ablate_active: 6006/16000
ablate_active: 6008/16000
ablate_active: 6010/16000
ablate_active: 6012/16000
ablate_active: 6014/16000
ablate_active: 6016/16000
ablate_active: 6018/16000
ablate_active: 6020/16000
ablate_active: 6022/16000
ablate_active: 6024/16000
ablate_active: 6026/16000
ablate_active: 6028/16000
ablate_active: 6030/16000
ablate_active: 6032/16000
ablate_active: 6034/16000
ablate_active: 6036/16000
ablate_active: 6038/16000
ablate_active: 6040/16000
ablate_active: 6042/16000
ablate_active: 6044/16000
ablate_active: 6046/16000
ablate_active: 6048/16000
ablate_active: 6050/16000
ablate_active: 6052/16000
ablate_active: 6054/16000
ablate_active: 6056/16000
ablate_active: 6058/16000
ablate_active: 6060/16000
ablate_active: 6062/16000
ablate_active: 6064/16000
ablate_active: 6066/16000
ablate_active: 6068/16000
ablate_active: 6070/16000
ablate_active: 6072/16000
ablate_active: 6074/16000
ablate_active: 6076/16000
ablate_active: 6078/16000
ablate_active: 6080/16000
ablate_active: 6082/16000
ablate_active: 6084/16000
ablate_active: 6086/16000
ablate_active: 6088/16000
ablate_active: 6090/16000
ablate_active: 6092/16000
ablate_active: 6094/16000
ablate_active: 6096/16000
ablate_active: 6098/16000
ablate_active: 6100/16000
ablate_active: 6102/16000
ablate_active: 6104/16000
ablate_active: 6106/16000
ablate_active: 6108/16000
ablate_active: 6110/16000
ablate_active: 6112/16000
ablate_active: 6114/16000
ablate_active: 6116/16000
ablate_active: 6118/16000
ablate_active: 6120/16000
ablate_active: 6122/16000
ablate_active: 6124/16000
ablate_active: 6126/16000
ablate_active: 6128/16000
ablate_active: 6130/16000
ablate_active: 6132/16000
ablate_active: 6134/16000
ablate_active: 6136/16000
ablate_active: 6138/16000
ablate_active: 6140/16000
ablate_active: 6142/16000
ablate_active: 6144/16000
ablate_active: 6146/16000
ablate_active: 6148/16000
ablate_active: 6150/16000
ablate_active: 6152/16000
ablate_active: 6154/16000
ablate_active: 6156/16000
ablate_active: 6158/16000
ablate_active: 6160/16000
ablate_active: 6162/16000
ablate_active: 6164/16000
ablate_active: 6166/16000
ablate_active: 6168/16000
ablate_active: 6170/16000
ablate_active: 6172/16000
ablate_active: 6174/16000
ablate_active: 6176/16000
ablate_active: 6178/16000
ablate_active: 6180/16000
ablate_active: 6182/16000
ablate_active: 6184/16000
ablate_active: 6186/16000
ablate_active: 6188/16000
ablate_active: 6190/16000
ablate_active: 6192/16000
ablate_active: 6194/16000
ablate_active: 6196/16000
ablate_active: 6198/16000
ablate_active: 6200/16000
ablate_active: 6202/16000
ablate_active: 6204/16000
ablate_active: 6206/16000
ablate_active: 6208/16000
ablate_active: 6210/16000
ablate_active: 6212/16000
ablate_active: 6214/16000
ablate_active: 6216/16000
ablate_active: 6218/16000
ablate_active: 6220/16000
ablate_active: 6222/16000
ablate_active: 6224/16000
ablate_active: 6226/16000
ablate_active: 6228/16000
ablate_active: 6230/16000
ablate_active: 6232/16000
ablate_active: 6234/16000
ablate_active: 6236/16000
ablate_active: 6238/16000
ablate_active: 6240/16000
ablate_active: 6242/16000
ablate_active: 6244/16000
ablate_active: 6246/16000
ablate_active: 6248/16000
ablate_active: 6250/16000
ablate_active: 6252/16000
ablate_active: 6254/16000
ablate_active: 6256/16000
ablate_active: 6258/16000
ablate_active: 6260/16000
ablate_active: 6262/16000
ablate_active: 6264/16000
ablate_active: 6266/16000
ablate_active: 6268/16000
ablate_active: 6270/16000
ablate_active: 6272/16000
ablate_active: 6274/16000
ablate_active: 6276/16000
ablate_active: 6278/16000
ablate_active: 6280/16000
ablate_active: 6282/16000
ablate_active: 6284/16000
ablate_active: 6286/16000
ablate_active: 6288/16000
ablate_active: 6290/16000
ablate_active: 6292/16000
ablate_active: 6294/16000
ablate_active: 6296/16000
ablate_active: 6298/16000
ablate_active: 6300/16000
ablate_active: 6302/16000
ablate_active: 6304/16000
ablate_active: 6306/16000
ablate_active: 6308/16000
ablate_active: 6310/16000
ablate_active: 6312/16000
ablate_active: 6314/16000
ablate_active: 6316/16000
ablate_active: 6318/16000
ablate_active: 6320/16000
ablate_active: 6322/16000
ablate_active: 6324/16000
ablate_active: 6326/16000
ablate_active: 6328/16000
ablate_active: 6330/16000
ablate_active: 6332/16000
ablate_active: 6334/16000
ablate_active: 6336/16000
ablate_active: 6338/16000
ablate_active: 6340/16000
ablate_active: 6342/16000
ablate_active: 6344/16000
ablate_active: 6346/16000
ablate_active: 6348/16000
ablate_active: 6350/16000
ablate_active: 6352/16000
ablate_active: 6354/16000
ablate_active: 6356/16000
ablate_active: 6358/16000
ablate_active: 6360/16000
ablate_active: 6362/16000
ablate_active: 6364/16000
ablate_active: 6366/16000
ablate_active: 6368/16000
ablate_active: 6370/16000
ablate_active: 6372/16000
ablate_active: 6374/16000
ablate_active: 6376/16000
ablate_active: 6378/16000
ablate_active: 6380/16000

ablate_active: 6382/16000
ablate_active: 6384/16000
ablate_active: 6386/16000
ablate_active: 6388/16000
ablate_active: 6390/16000
ablate_active: 6392/16000
ablate_active: 6394/16000
ablate_active: 6396/16000
ablate_active: 6398/16000
ablate_active: 6400/16000
ablate_active: 6402/16000
ablate_active: 6404/16000
ablate_active: 6406/16000
ablate_active: 6408/16000
ablate_active: 6410/16000
ablate_active: 6412/16000
ablate_active: 6414/16000
ablate_active: 6416/16000
ablate_active: 6418/16000
ablate_active: 6420/16000
ablate_active: 6422/16000
ablate_active: 6424/16000
ablate_active: 6426/16000
ablate_active: 6428/16000
ablate_active: 6430/16000
ablate_active: 6432/16000
ablate_active: 6434/16000
ablate_active: 6436/16000
ablate_active: 6438/16000
ablate_active: 6440/16000
ablate_active: 6442/16000
ablate_active: 6444/16000
ablate_active: 6446/16000
ablate_active: 6448/16000
ablate_active: 6450/16000
ablate_active: 6452/16000
ablate_active: 6454/16000
ablate_active: 6456/16000
ablate_active: 6458/16000
ablate_active: 6460/16000
ablate_active: 6462/16000
ablate_active: 6464/16000
ablate_active: 6466/16000
ablate_active: 6468/16000
ablate_active: 6470/16000
ablate_active: 6472/16000
ablate_active: 6474/16000
ablate_active: 6476/16000
ablate_active: 6478/16000
ablate_active: 6480/16000
ablate_active: 6482/16000
ablate_active: 6484/16000
ablate_active: 6486/16000
ablate_active: 6488/16000
ablate_active: 6490/16000
ablate_active: 6492/16000
ablate_active: 6494/16000
ablate_active: 6496/16000
ablate_active: 6498/16000
ablate_active: 6500/16000
ablate_active: 6502/16000
ablate_active: 6504/16000
ablate_active: 6506/16000
ablate_active: 6508/16000
ablate_active: 6510/16000
ablate_active: 6512/16000
ablate_active: 6514/16000
ablate_active: 6516/16000
ablate_active: 6518/16000
ablate_active: 6520/16000
ablate_active: 6522/16000
ablate_active: 6524/16000
ablate_active: 6526/16000
ablate_active: 6528/16000
ablate_active: 6530/16000
ablate_active: 6532/16000
ablate_active: 6534/16000
ablate_active: 6536/16000
ablate_active: 6538/16000
ablate_active: 6540/16000
ablate_active: 6542/16000
ablate_active: 6544/16000
ablate_active: 6546/16000
ablate_active: 6548/16000
ablate_active: 6550/16000
ablate_active: 6552/16000
ablate_active: 6554/16000
ablate_active: 6556/16000
ablate_active: 6558/16000
ablate_active: 6560/16000
ablate_active: 6562/16000
ablate_active: 6564/16000
ablate_active: 6566/16000
ablate_active: 6568/16000
ablate_active: 6570/16000
ablate_active: 6572/16000
ablate_active: 6574/16000
ablate_active: 6576/16000
ablate_active: 6578/16000
ablate_active: 6580/16000
ablate_active: 6582/16000
ablate_active: 6584/16000
ablate_active: 6586/16000
ablate_active: 6588/16000
ablate_active: 6590/16000
ablate_active: 6592/16000
ablate_active: 6594/16000
ablate_active: 6596/16000
ablate_active: 6598/16000
ablate_active: 6600/16000
ablate_active: 6602/16000
ablate_active: 6604/16000
ablate_active: 6606/16000
ablate_active: 6608/16000
ablate_active: 6610/16000
ablate_active: 6612/16000
ablate_active: 6614/16000
ablate_active: 6616/16000
ablate_active: 6618/16000
ablate_active: 6620/16000
ablate_active: 6622/16000
ablate_active: 6624/16000
ablate_active: 6626/16000
ablate_active: 6628/16000
ablate_active: 6630/16000
ablate_active: 6632/16000
ablate_active: 6634/16000
ablate_active: 6636/16000
ablate_active: 6638/16000
ablate_active: 6640/16000
ablate_active: 6642/16000
ablate_active: 6644/16000
ablate_active: 6646/16000
ablate_active: 6648/16000
ablate_active: 6650/16000
ablate_active: 6652/16000
ablate_active: 6654/16000
ablate_active: 6656/16000
ablate_active: 6658/16000
ablate_active: 6660/16000
ablate_active: 6662/16000
ablate_active: 6664/16000
ablate_active: 6666/16000
ablate_active: 6668/16000
ablate_active: 6670/16000
ablate_active: 6672/16000
ablate_active: 6674/16000
ablate_active: 6676/16000
ablate_active: 6678/16000
ablate_active: 6680/16000
ablate_active: 6682/16000
ablate_active: 6684/16000
ablate_active: 6686/16000
ablate_active: 6688/16000
ablate_active: 6690/16000
ablate_active: 6692/16000
ablate_active: 6694/16000
ablate_active: 6696/16000
ablate_active: 6698/16000
ablate_active: 6700/16000
ablate_active: 6702/16000
ablate_active: 6704/16000
ablate_active: 6706/16000
ablate_active: 6708/16000
ablate_active: 6710/16000
ablate_active: 6712/16000
ablate_active: 6714/16000
ablate_active: 6716/16000
ablate_active: 6718/16000
ablate_active: 6720/16000
ablate_active: 6722/16000
ablate_active: 6724/16000
ablate_active: 6726/16000
ablate_active: 6728/16000
ablate_active: 6730/16000
ablate_active: 6732/16000
ablate_active: 6734/16000
ablate_active: 6736/16000
ablate_active: 6738/16000
ablate_active: 6740/16000
ablate_active: 6742/16000
ablate_active: 6744/16000
ablate_active: 6746/16000
ablate_active: 6748/16000
ablate_active: 6750/16000
ablate_active: 6752/16000
ablate_active: 6754/16000
ablate_active: 6756/16000
ablate_active: 6758/16000
ablate_active: 6760/16000
ablate_active: 6762/16000
ablate_active: 6764/16000
ablate_active: 6766/16000
ablate_active: 6768/16000
ablate_active: 6770/16000
ablate_active: 6772/16000
ablate_active: 6774/16000
ablate_active: 6776/16000
ablate_active: 6778/16000
ablate_active: 6780/16000
ablate_active: 6782/16000
ablate_active: 6784/16000
ablate_active: 6786/16000
ablate_active: 6788/16000
ablate_active: 6790/16000
ablate_active: 6792/16000
ablate_active: 6794/16000
ablate_active: 6796/16000
ablate_active: 6798/16000
ablate_active: 6800/16000
ablate_active: 6802/16000
ablate_active: 6804/16000
ablate_active: 6806/16000
ablate_active: 6808/16000
ablate_active: 6810/16000
ablate_active: 6812/16000
ablate_active: 6814/16000
ablate_active: 6816/16000
ablate_active: 6818/16000
ablate_active: 6820/16000
ablate_active: 6822/16000
ablate_active: 6824/16000
ablate_active: 6826/16000
ablate_active: 6828/16000
ablate_active: 6830/16000
ablate_active: 6832/16000
ablate_active: 6834/16000
ablate_active: 6836/16000
ablate_active: 6838/16000
ablate_active: 6840/16000
ablate_active: 6842/16000
ablate_active: 6844/16000
ablate_active: 6846/16000
ablate_active: 6848/16000
ablate_active: 6850/16000
ablate_active: 6852/16000
ablate_active: 6854/16000
ablate_active: 6856/16000
ablate_active: 6858/16000
ablate_active: 6860/16000
ablate_active: 6862/16000
ablate_active: 6864/16000
ablate_active: 6866/16000
ablate_active: 6868/16000
ablate_active: 6870/16000
ablate_active: 6872/16000
ablate_active: 6874/16000
ablate_active: 6876/16000
ablate_active: 6878/16000
ablate_active: 6880/16000
ablate_active: 6882/16000
ablate_active: 6884/16000
ablate_active: 6886/16000
ablate_active: 6888/16000
ablate_active: 6890/16000
ablate_active: 6892/16000
ablate_active: 6894/16000
ablate_active: 6896/16000
ablate_active: 6898/16000
ablate_active: 6900/16000
ablate_active: 6902/16000
ablate_active: 6904/16000
ablate_active: 6906/16000
ablate_active: 6908/16000
ablate_active: 6910/16000
ablate_active: 6912/16000
ablate_active: 6914/16000
ablate_active: 6916/16000
ablate_active: 6918/16000
ablate_active: 6920/16000
ablate_active: 6922/16000
ablate_active: 6924/16000
ablate_active: 6926/16000
ablate_active: 6928/16000
ablate_active: 6930/16000
ablate_active: 6932/16000
ablate_active: 6934/16000
ablate_active: 6936/16000
ablate_active: 6938/16000
ablate_active: 6940/16000
ablate_active: 6942/16000
ablate_active: 6944/16000
ablate_active: 6946/16000
ablate_active: 6948/16000
ablate_active: 6950/16000
ablate_active: 6952/16000
ablate_active: 6954/16000
ablate_active: 6956/16000
ablate_active: 6958/16000
ablate_active: 6960/16000
ablate_active: 6962/16000
ablate_active: 6964/16000
ablate_active: 6966/16000
ablate_active: 6968/16000
ablate_active: 6970/16000
ablate_active: 6972/16000
ablate_active: 6974/16000
ablate_active: 6976/16000
ablate_active: 6978/16000
ablate_active: 6980/16000
ablate_active: 6982/16000
ablate_active: 6984/16000
ablate_active: 6986/16000
ablate_active: 6988/16000
ablate_active: 6990/16000
ablate_active: 6992/16000
ablate_active: 6994/16000
ablate_active: 6996/16000
ablate_active: 6998/16000
ablate_active: 7000/16000
ablate_active: 7002/16000
ablate_active: 7004/16000
ablate_active: 7006/16000
ablate_active: 7008/16000
ablate_active: 7010/16000
ablate_active: 7012/16000

ablate_active: 7014/16000
ablate_active: 7016/16000
ablate_active: 7018/16000
ablate_active: 7020/16000
ablate_active: 7022/16000
ablate_active: 7024/16000
ablate_active: 7026/16000
ablate_active: 7028/16000
ablate_active: 7030/16000
ablate_active: 7032/16000
ablate_active: 7034/16000
ablate_active: 7036/16000
ablate_active: 7038/16000
ablate_active: 7040/16000
ablate_active: 7042/16000
ablate_active: 7044/16000
ablate_active: 7046/16000
ablate_active: 7048/16000
ablate_active: 7050/16000
ablate_active: 7052/16000
ablate_active: 7054/16000
ablate_active: 7056/16000
ablate_active: 7058/16000
ablate_active: 7060/16000
ablate_active: 7062/16000
ablate_active: 7064/16000
ablate_active: 7066/16000
ablate_active: 7068/16000
ablate_active: 7070/16000
ablate_active: 7072/16000
ablate_active: 7074/16000
ablate_active: 7076/16000
ablate_active: 7078/16000
ablate_active: 7080/16000
ablate_active: 7082/16000
ablate_active: 7084/16000
ablate_active: 7086/16000
ablate_active: 7088/16000
ablate_active: 7090/16000
ablate_active: 7092/16000
ablate_active: 7094/16000
ablate_active: 7096/16000
ablate_active: 7098/16000
ablate_active: 7100/16000
ablate_active: 7102/16000
ablate_active: 7104/16000
ablate_active: 7106/16000
ablate_active: 7108/16000
ablate_active: 7110/16000
ablate_active: 7112/16000
ablate_active: 7114/16000
ablate_active: 7116/16000
ablate_active: 7118/16000
ablate_active: 7120/16000
ablate_active: 7122/16000
ablate_active: 7124/16000
ablate_active: 7126/16000
ablate_active: 7128/16000
ablate_active: 7130/16000
ablate_active: 7132/16000
ablate_active: 7134/16000
ablate_active: 7136/16000
ablate_active: 7138/16000
ablate_active: 7140/16000
ablate_active: 7142/16000
ablate_active: 7144/16000
ablate_active: 7146/16000
ablate_active: 7148/16000
ablate_active: 7150/16000
ablate_active: 7152/16000
ablate_active: 7154/16000
ablate_active: 7156/16000
ablate_active: 7158/16000
ablate_active: 7160/16000
ablate_active: 7162/16000
ablate_active: 7164/16000
ablate_active: 7166/16000
ablate_active: 7168/16000
ablate_active: 7170/16000
ablate_active: 7172/16000
ablate_active: 7174/16000
ablate_active: 7176/16000
ablate_active: 7178/16000
ablate_active: 7180/16000
ablate_active: 7182/16000
ablate_active: 7184/16000
ablate_active: 7186/16000
ablate_active: 7188/16000
ablate_active: 7190/16000
ablate_active: 7192/16000
ablate_active: 7194/16000
ablate_active: 7196/16000
ablate_active: 7198/16000
ablate_active: 7200/16000
ablate_active: 7202/16000
ablate_active: 7204/16000
ablate_active: 7206/16000
ablate_active: 7208/16000
ablate_active: 7210/16000
ablate_active: 7212/16000
ablate_active: 7214/16000
ablate_active: 7216/16000
ablate_active: 7218/16000
ablate_active: 7220/16000
ablate_active: 7222/16000
ablate_active: 7224/16000
ablate_active: 7226/16000
ablate_active: 7228/16000
ablate_active: 7230/16000
ablate_active: 7232/16000
ablate_active: 7234/16000
ablate_active: 7236/16000
ablate_active: 7238/16000
ablate_active: 7240/16000
ablate_active: 7242/16000
ablate_active: 7244/16000
ablate_active: 7246/16000
ablate_active: 7248/16000
ablate_active: 7250/16000
ablate_active: 7252/16000
ablate_active: 7254/16000
ablate_active: 7256/16000
ablate_active: 7258/16000
ablate_active: 7260/16000
ablate_active: 7262/16000
ablate_active: 7264/16000
ablate_active: 7266/16000
ablate_active: 7268/16000
ablate_active: 7270/16000
ablate_active: 7272/16000
ablate_active: 7274/16000
ablate_active: 7276/16000
ablate_active: 7278/16000
ablate_active: 7280/16000
ablate_active: 7282/16000
ablate_active: 7284/16000
ablate_active: 7286/16000
ablate_active: 7288/16000
ablate_active: 7290/16000
ablate_active: 7292/16000
ablate_active: 7294/16000
ablate_active: 7296/16000
ablate_active: 7298/16000
ablate_active: 7300/16000
ablate_active: 7302/16000
ablate_active: 7304/16000
ablate_active: 7306/16000
ablate_active: 7308/16000
ablate_active: 7310/16000
ablate_active: 7312/16000
ablate_active: 7314/16000
ablate_active: 7316/16000
ablate_active: 7318/16000
ablate_active: 7320/16000
ablate_active: 7322/16000
ablate_active: 7324/16000
ablate_active: 7326/16000
ablate_active: 7328/16000
ablate_active: 7330/16000
ablate_active: 7332/16000
ablate_active: 7334/16000
ablate_active: 7336/16000
ablate_active: 7338/16000
ablate_active: 7340/16000
ablate_active: 7342/16000
ablate_active: 7344/16000
ablate_active: 7346/16000
ablate_active: 7348/16000
ablate_active: 7350/16000
ablate_active: 7352/16000
ablate_active: 7354/16000
ablate_active: 7356/16000
ablate_active: 7358/16000
ablate_active: 7360/16000
ablate_active: 7362/16000
ablate_active: 7364/16000
ablate_active: 7366/16000
ablate_active: 7368/16000
ablate_active: 7370/16000
ablate_active: 7372/16000
ablate_active: 7374/16000
ablate_active: 7376/16000
ablate_active: 7378/16000
ablate_active: 7380/16000
ablate_active: 7382/16000
ablate_active: 7384/16000
ablate_active: 7386/16000
ablate_active: 7388/16000
ablate_active: 7390/16000
ablate_active: 7392/16000
ablate_active: 7394/16000
ablate_active: 7396/16000
ablate_active: 7398/16000
ablate_active: 7400/16000
ablate_active: 7402/16000
ablate_active: 7404/16000
ablate_active: 7406/16000
ablate_active: 7408/16000
ablate_active: 7410/16000
ablate_active: 7412/16000
ablate_active: 7414/16000
ablate_active: 7416/16000
ablate_active: 7418/16000
ablate_active: 7420/16000
ablate_active: 7422/16000
ablate_active: 7424/16000
ablate_active: 7426/16000
ablate_active: 7428/16000
ablate_active: 7430/16000
ablate_active: 7432/16000
ablate_active: 7434/16000
ablate_active: 7436/16000
ablate_active: 7438/16000
ablate_active: 7440/16000
ablate_active: 7442/16000
ablate_active: 7444/16000
ablate_active: 7446/16000
ablate_active: 7448/16000
ablate_active: 7450/16000
ablate_active: 7452/16000
ablate_active: 7454/16000
ablate_active: 7456/16000
ablate_active: 7458/16000
ablate_active: 7460/16000
ablate_active: 7462/16000
ablate_active: 7464/16000
ablate_active: 7466/16000
ablate_active: 7468/16000
ablate_active: 7470/16000
ablate_active: 7472/16000
ablate_active: 7474/16000
ablate_active: 7476/16000
ablate_active: 7478/16000
ablate_active: 7480/16000
ablate_active: 7482/16000
ablate_active: 7484/16000
ablate_active: 7486/16000
ablate_active: 7488/16000
ablate_active: 7490/16000
ablate_active: 7492/16000
ablate_active: 7494/16000
ablate_active: 7496/16000
ablate_active: 7498/16000
ablate_active: 7500/16000
ablate_active: 7502/16000
ablate_active: 7504/16000
ablate_active: 7506/16000
ablate_active: 7508/16000
ablate_active: 7510/16000
ablate_active: 7512/16000
ablate_active: 7514/16000
ablate_active: 7516/16000
ablate_active: 7518/16000
ablate_active: 7520/16000
ablate_active: 7522/16000
ablate_active: 7524/16000
ablate_active: 7526/16000
ablate_active: 7528/16000
ablate_active: 7530/16000
ablate_active: 7532/16000
ablate_active: 7534/16000
ablate_active: 7536/16000
ablate_active: 7538/16000
ablate_active: 7540/16000
ablate_active: 7542/16000
ablate_active: 7544/16000
ablate_active: 7546/16000
ablate_active: 7548/16000
ablate_active: 7550/16000
ablate_active: 7552/16000
ablate_active: 7554/16000
ablate_active: 7556/16000
ablate_active: 7558/16000
ablate_active: 7560/16000
ablate_active: 7562/16000
ablate_active: 7564/16000
ablate_active: 7566/16000
ablate_active: 7568/16000
ablate_active: 7570/16000
ablate_active: 7572/16000
ablate_active: 7574/16000
ablate_active: 7576/16000
ablate_active: 7578/16000
ablate_active: 7580/16000
ablate_active: 7582/16000
ablate_active: 7584/16000
ablate_active: 7586/16000
ablate_active: 7588/16000
ablate_active: 7590/16000
ablate_active: 7592/16000
ablate_active: 7594/16000
ablate_active: 7596/16000
ablate_active: 7598/16000
ablate_active: 7600/16000
ablate_active: 7602/16000
ablate_active: 7604/16000
ablate_active: 7606/16000
ablate_active: 7608/16000
ablate_active: 7610/16000
ablate_active: 7612/16000
ablate_active: 7614/16000
ablate_active: 7616/16000
ablate_active: 7618/16000
ablate_active: 7620/16000
ablate_active: 7622/16000
ablate_active: 7624/16000
ablate_active: 7626/16000
ablate_active: 7628/16000
ablate_active: 7630/16000
ablate_active: 7632/16000
ablate_active: 7634/16000
ablate_active: 7636/16000
ablate_active: 7638/16000
ablate_active: 7640/16000
ablate_active: 7642/16000
ablate_active: 7644/16000

ablate_active: 7646/16000
ablate_active: 7648/16000
ablate_active: 7650/16000
ablate_active: 7652/16000
ablate_active: 7654/16000
ablate_active: 7656/16000
ablate_active: 7658/16000
ablate_active: 7660/16000
ablate_active: 7662/16000
ablate_active: 7664/16000
ablate_active: 7666/16000
ablate_active: 7668/16000
ablate_active: 7670/16000
ablate_active: 7672/16000
ablate_active: 7674/16000
ablate_active: 7676/16000
ablate_active: 7678/16000
ablate_active: 7680/16000
ablate_active: 7682/16000
ablate_active: 7684/16000
ablate_active: 7686/16000
ablate_active: 7688/16000
ablate_active: 7690/16000
ablate_active: 7692/16000
ablate_active: 7694/16000
ablate_active: 7696/16000
ablate_active: 7698/16000
ablate_active: 7700/16000
ablate_active: 7702/16000
ablate_active: 7704/16000
ablate_active: 7706/16000
ablate_active: 7708/16000
ablate_active: 7710/16000
ablate_active: 7712/16000
ablate_active: 7714/16000
ablate_active: 7716/16000
ablate_active: 7718/16000
ablate_active: 7720/16000
ablate_active: 7722/16000
ablate_active: 7724/16000
ablate_active: 7726/16000
ablate_active: 7728/16000
ablate_active: 7730/16000
ablate_active: 7732/16000
ablate_active: 7734/16000
ablate_active: 7736/16000
ablate_active: 7738/16000
ablate_active: 7740/16000
ablate_active: 7742/16000
ablate_active: 7744/16000
ablate_active: 7746/16000
ablate_active: 7748/16000
ablate_active: 7750/16000
ablate_active: 7752/16000
ablate_active: 7754/16000
ablate_active: 7756/16000
ablate_active: 7758/16000
ablate_active: 7760/16000
ablate_active: 7762/16000
ablate_active: 7764/16000
ablate_active: 7766/16000
ablate_active: 7768/16000
ablate_active: 7770/16000
ablate_active: 7772/16000
ablate_active: 7774/16000
ablate_active: 7776/16000
ablate_active: 7778/16000
ablate_active: 7780/16000
ablate_active: 7782/16000
ablate_active: 7784/16000
ablate_active: 7786/16000
ablate_active: 7788/16000
ablate_active: 7790/16000
ablate_active: 7792/16000
ablate_active: 7794/16000
ablate_active: 7796/16000
ablate_active: 7798/16000
ablate_active: 7800/16000
ablate_active: 7802/16000
ablate_active: 7804/16000
ablate_active: 7806/16000
ablate_active: 7808/16000
ablate_active: 7810/16000
ablate_active: 7812/16000
ablate_active: 7814/16000
ablate_active: 7816/16000
ablate_active: 7818/16000
ablate_active: 7820/16000
ablate_active: 7822/16000
ablate_active: 7824/16000
ablate_active: 7826/16000
ablate_active: 7828/16000
ablate_active: 7830/16000
ablate_active: 7832/16000
ablate_active: 7834/16000
ablate_active: 7836/16000
ablate_active: 7838/16000
ablate_active: 7840/16000
ablate_active: 7842/16000
ablate_active: 7844/16000
ablate_active: 7846/16000
ablate_active: 7848/16000
ablate_active: 7850/16000
ablate_active: 7852/16000
ablate_active: 7854/16000
ablate_active: 7856/16000
ablate_active: 7858/16000
ablate_active: 7860/16000
ablate_active: 7862/16000
ablate_active: 7864/16000
ablate_active: 7866/16000
ablate_active: 7868/16000
ablate_active: 7870/16000
ablate_active: 7872/16000
ablate_active: 7874/16000
ablate_active: 7876/16000
ablate_active: 7878/16000
ablate_active: 7880/16000
ablate_active: 7882/16000
ablate_active: 7884/16000
ablate_active: 7886/16000
ablate_active: 7888/16000
ablate_active: 7890/16000
ablate_active: 7892/16000
ablate_active: 7894/16000
ablate_active: 7896/16000
ablate_active: 7898/16000
ablate_active: 7900/16000
ablate_active: 7902/16000
ablate_active: 7904/16000
ablate_active: 7906/16000
ablate_active: 7908/16000
ablate_active: 7910/16000
ablate_active: 7912/16000
ablate_active: 7914/16000
ablate_active: 7916/16000
ablate_active: 7918/16000
ablate_active: 7920/16000
ablate_active: 7922/16000
ablate_active: 7924/16000
ablate_active: 7926/16000
ablate_active: 7928/16000
ablate_active: 7930/16000
ablate_active: 7932/16000
ablate_active: 7934/16000
ablate_active: 7936/16000
ablate_active: 7938/16000
ablate_active: 7940/16000
ablate_active: 7942/16000
ablate_active: 7944/16000
ablate_active: 7946/16000
ablate_active: 7948/16000
ablate_active: 7950/16000
ablate_active: 7952/16000
ablate_active: 7954/16000
ablate_active: 7956/16000
ablate_active: 7958/16000
ablate_active: 7960/16000
ablate_active: 7962/16000
ablate_active: 7964/16000
ablate_active: 7966/16000
ablate_active: 7968/16000
ablate_active: 7970/16000
ablate_active: 7972/16000
ablate_active: 7974/16000
ablate_active: 7976/16000
ablate_active: 7978/16000
ablate_active: 7980/16000
ablate_active: 7982/16000
ablate_active: 7984/16000
ablate_active: 7986/16000
ablate_active: 7988/16000
ablate_active: 7990/16000
ablate_active: 7992/16000
ablate_active: 7994/16000
ablate_active: 7996/16000
ablate_active: 7998/16000
ablate_active: 8000/16000
ablate_active: 8002/16000
ablate_active: 8004/16000
ablate_active: 8006/16000
ablate_active: 8008/16000
ablate_active: 8010/16000
ablate_active: 8012/16000
ablate_active: 8014/16000
ablate_active: 8016/16000
ablate_active: 8018/16000
ablate_active: 8020/16000
ablate_active: 8022/16000
ablate_active: 8024/16000
ablate_active: 8026/16000
ablate_active: 8028/16000
ablate_active: 8030/16000
ablate_active: 8032/16000
ablate_active: 8034/16000
ablate_active: 8036/16000
ablate_active: 8038/16000
ablate_active: 8040/16000
ablate_active: 8042/16000
ablate_active: 8044/16000
ablate_active: 8046/16000
ablate_active: 8048/16000
ablate_active: 8050/16000
ablate_active: 8052/16000
ablate_active: 8054/16000
ablate_active: 8056/16000
ablate_active: 8058/16000
ablate_active: 8060/16000
ablate_active: 8062/16000
ablate_active: 8064/16000
ablate_active: 8066/16000
ablate_active: 8068/16000
ablate_active: 8070/16000
ablate_active: 8072/16000
ablate_active: 8074/16000
ablate_active: 8076/16000
ablate_active: 8078/16000
ablate_active: 8080/16000
ablate_active: 8082/16000
ablate_active: 8084/16000
ablate_active: 8086/16000
ablate_active: 8088/16000
ablate_active: 8090/16000
ablate_active: 8092/16000
ablate_active: 8094/16000
ablate_active: 8096/16000
ablate_active: 8098/16000
ablate_active: 8100/16000
ablate_active: 8102/16000
ablate_active: 8104/16000
ablate_active: 8106/16000
ablate_active: 8108/16000
ablate_active: 8110/16000
ablate_active: 8112/16000
ablate_active: 8114/16000
ablate_active: 8116/16000
ablate_active: 8118/16000
ablate_active: 8120/16000
ablate_active: 8122/16000
ablate_active: 8124/16000
ablate_active: 8126/16000
ablate_active: 8128/16000
ablate_active: 8130/16000
ablate_active: 8132/16000
ablate_active: 8134/16000
ablate_active: 8136/16000
ablate_active: 8138/16000
ablate_active: 8140/16000
ablate_active: 8142/16000
ablate_active: 8144/16000
ablate_active: 8146/16000
ablate_active: 8148/16000
ablate_active: 8150/16000
ablate_active: 8152/16000
ablate_active: 8154/16000
ablate_active: 8156/16000
ablate_active: 8158/16000
ablate_active: 8160/16000
ablate_active: 8162/16000
ablate_active: 8164/16000
ablate_active: 8166/16000
ablate_active: 8168/16000
ablate_active: 8170/16000
ablate_active: 8172/16000
ablate_active: 8174/16000
ablate_active: 8176/16000
ablate_active: 8178/16000
ablate_active: 8180/16000
ablate_active: 8182/16000
ablate_active: 8184/16000
ablate_active: 8186/16000
ablate_active: 8188/16000
ablate_active: 8190/16000
ablate_active: 8192/16000
ablate_active: 8194/16000
ablate_active: 8196/16000
ablate_active: 8198/16000
ablate_active: 8200/16000
ablate_active: 8202/16000
ablate_active: 8204/16000
ablate_active: 8206/16000
ablate_active: 8208/16000
ablate_active: 8210/16000
ablate_active: 8212/16000
ablate_active: 8214/16000
ablate_active: 8216/16000
ablate_active: 8218/16000
ablate_active: 8220/16000
ablate_active: 8222/16000
ablate_active: 8224/16000
ablate_active: 8226/16000
ablate_active: 8228/16000
ablate_active: 8230/16000
ablate_active: 8232/16000
ablate_active: 8234/16000
ablate_active: 8236/16000
ablate_active: 8238/16000
ablate_active: 8240/16000
ablate_active: 8242/16000
ablate_active: 8244/16000
ablate_active: 8246/16000
ablate_active: 8248/16000
ablate_active: 8250/16000
ablate_active: 8252/16000
ablate_active: 8254/16000
ablate_active: 8256/16000
ablate_active: 8258/16000
ablate_active: 8260/16000
ablate_active: 8262/16000
ablate_active: 8264/16000
ablate_active: 8266/16000
ablate_active: 8268/16000
ablate_active: 8270/16000
ablate_active: 8272/16000
ablate_active: 8274/16000
ablate_active: 8276/16000

ablate_active: 8278/16000
ablate_active: 8280/16000
ablate_active: 8282/16000
ablate_active: 8284/16000
ablate_active: 8286/16000
ablate_active: 8288/16000
ablate_active: 8290/16000
ablate_active: 8292/16000
ablate_active: 8294/16000
ablate_active: 8296/16000
ablate_active: 8298/16000
ablate_active: 8300/16000
ablate_active: 8302/16000
ablate_active: 8304/16000
ablate_active: 8306/16000
ablate_active: 8308/16000
ablate_active: 8310/16000
ablate_active: 8312/16000
ablate_active: 8314/16000
ablate_active: 8316/16000
ablate_active: 8318/16000
ablate_active: 8320/16000
ablate_active: 8322/16000
ablate_active: 8324/16000
ablate_active: 8326/16000
ablate_active: 8328/16000
ablate_active: 8330/16000
ablate_active: 8332/16000
ablate_active: 8334/16000
ablate_active: 8336/16000
ablate_active: 8338/16000
ablate_active: 8340/16000
ablate_active: 8342/16000
ablate_active: 8344/16000
ablate_active: 8346/16000
ablate_active: 8348/16000
ablate_active: 8350/16000
ablate_active: 8352/16000
ablate_active: 8354/16000
ablate_active: 8356/16000
ablate_active: 8358/16000
ablate_active: 8360/16000
ablate_active: 8362/16000
ablate_active: 8364/16000
ablate_active: 8366/16000
ablate_active: 8368/16000
ablate_active: 8370/16000
ablate_active: 8372/16000
ablate_active: 8374/16000
ablate_active: 8376/16000
ablate_active: 8378/16000
ablate_active: 8380/16000
ablate_active: 8382/16000
ablate_active: 8384/16000
ablate_active: 8386/16000
ablate_active: 8388/16000
ablate_active: 8390/16000
ablate_active: 8392/16000
ablate_active: 8394/16000
ablate_active: 8396/16000
ablate_active: 8398/16000
ablate_active: 8400/16000
ablate_active: 8402/16000
ablate_active: 8404/16000
ablate_active: 8406/16000
ablate_active: 8408/16000
ablate_active: 8410/16000
ablate_active: 8412/16000
ablate_active: 8414/16000
ablate_active: 8416/16000
ablate_active: 8418/16000
ablate_active: 8420/16000
ablate_active: 8422/16000
ablate_active: 8424/16000
ablate_active: 8426/16000
ablate_active: 8428/16000
ablate_active: 8430/16000
ablate_active: 8432/16000
ablate_active: 8434/16000
ablate_active: 8436/16000
ablate_active: 8438/16000
ablate_active: 8440/16000
ablate_active: 8442/16000
ablate_active: 8444/16000
ablate_active: 8446/16000
ablate_active: 8448/16000
ablate_active: 8450/16000
ablate_active: 8452/16000
ablate_active: 8454/16000
ablate_active: 8456/16000
ablate_active: 8458/16000
ablate_active: 8460/16000
ablate_active: 8462/16000
ablate_active: 8464/16000
ablate_active: 8466/16000
ablate_active: 8468/16000
ablate_active: 8470/16000
ablate_active: 8472/16000
ablate_active: 8474/16000
ablate_active: 8476/16000
ablate_active: 8478/16000
ablate_active: 8480/16000
ablate_active: 8482/16000
ablate_active: 8484/16000
ablate_active: 8486/16000
ablate_active: 8488/16000
ablate_active: 8490/16000
ablate_active: 8492/16000
ablate_active: 8494/16000
ablate_active: 8496/16000
ablate_active: 8498/16000
ablate_active: 8500/16000
ablate_active: 8502/16000
ablate_active: 8504/16000
ablate_active: 8506/16000
ablate_active: 8508/16000
ablate_active: 8510/16000
ablate_active: 8512/16000
ablate_active: 8514/16000
ablate_active: 8516/16000
ablate_active: 8518/16000
ablate_active: 8520/16000
ablate_active: 8522/16000
ablate_active: 8524/16000
ablate_active: 8526/16000
ablate_active: 8528/16000
ablate_active: 8530/16000
ablate_active: 8532/16000
ablate_active: 8534/16000
ablate_active: 8536/16000
ablate_active: 8538/16000
ablate_active: 8540/16000
ablate_active: 8542/16000
ablate_active: 8544/16000
ablate_active: 8546/16000
ablate_active: 8548/16000
ablate_active: 8550/16000
ablate_active: 8552/16000
ablate_active: 8554/16000
ablate_active: 8556/16000
ablate_active: 8558/16000
ablate_active: 8560/16000
ablate_active: 8562/16000
ablate_active: 8564/16000
ablate_active: 8566/16000
ablate_active: 8568/16000
ablate_active: 8570/16000
ablate_active: 8572/16000
ablate_active: 8574/16000
ablate_active: 8576/16000
ablate_active: 8578/16000
ablate_active: 8580/16000
ablate_active: 8582/16000
ablate_active: 8584/16000
ablate_active: 8586/16000
ablate_active: 8588/16000
ablate_active: 8590/16000
ablate_active: 8592/16000
ablate_active: 8594/16000
ablate_active: 8596/16000
ablate_active: 8598/16000
ablate_active: 8600/16000
ablate_active: 8602/16000
ablate_active: 8604/16000
ablate_active: 8606/16000
ablate_active: 8608/16000
ablate_active: 8610/16000
ablate_active: 8612/16000
ablate_active: 8614/16000
ablate_active: 8616/16000
ablate_active: 8618/16000
ablate_active: 8620/16000
ablate_active: 8622/16000
ablate_active: 8624/16000
ablate_active: 8626/16000
ablate_active: 8628/16000
ablate_active: 8630/16000
ablate_active: 8632/16000
ablate_active: 8634/16000
ablate_active: 8636/16000
ablate_active: 8638/16000
ablate_active: 8640/16000
ablate_active: 8642/16000
ablate_active: 8644/16000
ablate_active: 8646/16000
ablate_active: 8648/16000
ablate_active: 8650/16000
ablate_active: 8652/16000
ablate_active: 8654/16000
ablate_active: 8656/16000
ablate_active: 8658/16000
ablate_active: 8660/16000
ablate_active: 8662/16000
ablate_active: 8664/16000
ablate_active: 8666/16000
ablate_active: 8668/16000
ablate_active: 8670/16000
ablate_active: 8672/16000
ablate_active: 8674/16000
ablate_active: 8676/16000
ablate_active: 8678/16000
ablate_active: 8680/16000
ablate_active: 8682/16000
ablate_active: 8684/16000
ablate_active: 8686/16000
ablate_active: 8688/16000
ablate_active: 8690/16000
ablate_active: 8692/16000
ablate_active: 8694/16000
ablate_active: 8696/16000
ablate_active: 8698/16000
ablate_active: 8700/16000
ablate_active: 8702/16000
ablate_active: 8704/16000
ablate_active: 8706/16000
ablate_active: 8708/16000
ablate_active: 8710/16000
ablate_active: 8712/16000
ablate_active: 8714/16000
ablate_active: 8716/16000
ablate_active: 8718/16000
ablate_active: 8720/16000
ablate_active: 8722/16000
ablate_active: 8724/16000
ablate_active: 8726/16000
ablate_active: 8728/16000
ablate_active: 8730/16000
ablate_active: 8732/16000
ablate_active: 8734/16000
ablate_active: 8736/16000
ablate_active: 8738/16000
ablate_active: 8740/16000
ablate_active: 8742/16000
ablate_active: 8744/16000
ablate_active: 8746/16000
ablate_active: 8748/16000
ablate_active: 8750/16000
ablate_active: 8752/16000
ablate_active: 8754/16000
ablate_active: 8756/16000
ablate_active: 8758/16000
ablate_active: 8760/16000
ablate_active: 8762/16000
ablate_active: 8764/16000
ablate_active: 8766/16000
ablate_active: 8768/16000
ablate_active: 8770/16000
ablate_active: 8772/16000
ablate_active: 8774/16000
ablate_active: 8776/16000
ablate_active: 8778/16000
ablate_active: 8780/16000
ablate_active: 8782/16000
ablate_active: 8784/16000
ablate_active: 8786/16000
ablate_active: 8788/16000
ablate_active: 8790/16000
ablate_active: 8792/16000
ablate_active: 8794/16000
ablate_active: 8796/16000
ablate_active: 8798/16000
ablate_active: 8800/16000
ablate_active: 8802/16000
ablate_active: 8804/16000
ablate_active: 8806/16000
ablate_active: 8808/16000
ablate_active: 8810/16000
ablate_active: 8812/16000
ablate_active: 8814/16000
ablate_active: 8816/16000
ablate_active: 8818/16000
ablate_active: 8820/16000
ablate_active: 8822/16000
ablate_active: 8824/16000
ablate_active: 8826/16000
ablate_active: 8828/16000
ablate_active: 8830/16000
ablate_active: 8832/16000
ablate_active: 8834/16000
ablate_active: 8836/16000
ablate_active: 8838/16000
ablate_active: 8840/16000
ablate_active: 8842/16000
ablate_active: 8844/16000
ablate_active: 8846/16000
ablate_active: 8848/16000
ablate_active: 8850/16000
ablate_active: 8852/16000
ablate_active: 8854/16000
ablate_active: 8856/16000
ablate_active: 8858/16000
ablate_active: 8860/16000
ablate_active: 8862/16000
ablate_active: 8864/16000
ablate_active: 8866/16000
ablate_active: 8868/16000
ablate_active: 8870/16000
ablate_active: 8872/16000
ablate_active: 8874/16000
ablate_active: 8876/16000
ablate_active: 8878/16000
ablate_active: 8880/16000
ablate_active: 8882/16000
ablate_active: 8884/16000
ablate_active: 8886/16000
ablate_active: 8888/16000
ablate_active: 8890/16000
ablate_active: 8892/16000
ablate_active: 8894/16000
ablate_active: 8896/16000
ablate_active: 8898/16000
ablate_active: 8900/16000
ablate_active: 8902/16000
ablate_active: 8904/16000
ablate_active: 8906/16000
ablate_active: 8908/16000

ablate_active: 8910/16000
ablate_active: 8912/16000
ablate_active: 8914/16000
ablate_active: 8916/16000
ablate_active: 8918/16000
ablate_active: 8920/16000
ablate_active: 8922/16000
ablate_active: 8924/16000
ablate_active: 8926/16000
ablate_active: 8928/16000
ablate_active: 8930/16000
ablate_active: 8932/16000
ablate_active: 8934/16000
ablate_active: 8936/16000
ablate_active: 8938/16000
ablate_active: 8940/16000
ablate_active: 8942/16000
ablate_active: 8944/16000
ablate_active: 8946/16000
ablate_active: 8948/16000
ablate_active: 8950/16000
ablate_active: 8952/16000
ablate_active: 8954/16000
ablate_active: 8956/16000
ablate_active: 8958/16000
ablate_active: 8960/16000
ablate_active: 8962/16000
ablate_active: 8964/16000
ablate_active: 8966/16000
ablate_active: 8968/16000
ablate_active: 8970/16000
ablate_active: 8972/16000
ablate_active: 8974/16000
ablate_active: 8976/16000
ablate_active: 8978/16000
ablate_active: 8980/16000
ablate_active: 8982/16000
ablate_active: 8984/16000
ablate_active: 8986/16000
ablate_active: 8988/16000
ablate_active: 8990/16000
ablate_active: 8992/16000
ablate_active: 8994/16000
ablate_active: 8996/16000
ablate_active: 8998/16000
ablate_active: 9000/16000
ablate_active: 9002/16000
ablate_active: 9004/16000
ablate_active: 9006/16000
ablate_active: 9008/16000
ablate_active: 9010/16000
ablate_active: 9012/16000
ablate_active: 9014/16000
ablate_active: 9016/16000
ablate_active: 9018/16000
ablate_active: 9020/16000
ablate_active: 9022/16000
ablate_active: 9024/16000
ablate_active: 9026/16000
ablate_active: 9028/16000
ablate_active: 9030/16000
ablate_active: 9032/16000
ablate_active: 9034/16000
ablate_active: 9036/16000
ablate_active: 9038/16000
ablate_active: 9040/16000
ablate_active: 9042/16000
ablate_active: 9044/16000
ablate_active: 9046/16000
ablate_active: 9048/16000
ablate_active: 9050/16000
ablate_active: 9052/16000
ablate_active: 9054/16000
ablate_active: 9056/16000
ablate_active: 9058/16000
ablate_active: 9060/16000
ablate_active: 9062/16000
ablate_active: 9064/16000
ablate_active: 9066/16000
ablate_active: 9068/16000
ablate_active: 9070/16000
ablate_active: 9072/16000
ablate_active: 9074/16000
ablate_active: 9076/16000
ablate_active: 9078/16000
ablate_active: 9080/16000
ablate_active: 9082/16000
ablate_active: 9084/16000
ablate_active: 9086/16000
ablate_active: 9088/16000
ablate_active: 9090/16000
ablate_active: 9092/16000
ablate_active: 9094/16000
ablate_active: 9096/16000
ablate_active: 9098/16000
ablate_active: 9100/16000
ablate_active: 9102/16000
ablate_active: 9104/16000
ablate_active: 9106/16000
ablate_active: 9108/16000
ablate_active: 9110/16000
ablate_active: 9112/16000
ablate_active: 9114/16000
ablate_active: 9116/16000
ablate_active: 9118/16000
ablate_active: 9120/16000
ablate_active: 9122/16000
ablate_active: 9124/16000
ablate_active: 9126/16000
ablate_active: 9128/16000
ablate_active: 9130/16000
ablate_active: 9132/16000
ablate_active: 9134/16000
ablate_active: 9136/16000
ablate_active: 9138/16000
ablate_active: 9140/16000
ablate_active: 9142/16000
ablate_active: 9144/16000
ablate_active: 9146/16000
ablate_active: 9148/16000
ablate_active: 9150/16000
ablate_active: 9152/16000
ablate_active: 9154/16000
ablate_active: 9156/16000
ablate_active: 9158/16000
ablate_active: 9160/16000
ablate_active: 9162/16000
ablate_active: 9164/16000
ablate_active: 9166/16000
ablate_active: 9168/16000
ablate_active: 9170/16000
ablate_active: 9172/16000
ablate_active: 9174/16000
ablate_active: 9176/16000
ablate_active: 9178/16000
ablate_active: 9180/16000
ablate_active: 9182/16000
ablate_active: 9184/16000
ablate_active: 9186/16000
ablate_active: 9188/16000
ablate_active: 9190/16000
ablate_active: 9192/16000
ablate_active: 9194/16000
ablate_active: 9196/16000
ablate_active: 9198/16000
ablate_active: 9200/16000
ablate_active: 9202/16000
ablate_active: 9204/16000
ablate_active: 9206/16000
ablate_active: 9208/16000
ablate_active: 9210/16000
ablate_active: 9212/16000
ablate_active: 9214/16000
ablate_active: 9216/16000
ablate_active: 9218/16000
ablate_active: 9220/16000
ablate_active: 9222/16000
ablate_active: 9224/16000
ablate_active: 9226/16000
ablate_active: 9228/16000
ablate_active: 9230/16000
ablate_active: 9232/16000
ablate_active: 9234/16000
ablate_active: 9236/16000
ablate_active: 9238/16000
ablate_active: 9240/16000
ablate_active: 9242/16000
ablate_active: 9244/16000
ablate_active: 9246/16000
ablate_active: 9248/16000
ablate_active: 9250/16000
ablate_active: 9252/16000
ablate_active: 9254/16000
ablate_active: 9256/16000
ablate_active: 9258/16000
ablate_active: 9260/16000
ablate_active: 9262/16000
ablate_active: 9264/16000
ablate_active: 9266/16000
ablate_active: 9268/16000
ablate_active: 9270/16000
ablate_active: 9272/16000
ablate_active: 9274/16000
ablate_active: 9276/16000
ablate_active: 9278/16000
ablate_active: 9280/16000
ablate_active: 9282/16000
ablate_active: 9284/16000
ablate_active: 9286/16000
ablate_active: 9288/16000
ablate_active: 9290/16000
ablate_active: 9292/16000
ablate_active: 9294/16000
ablate_active: 9296/16000
ablate_active: 9298/16000
ablate_active: 9300/16000
ablate_active: 9302/16000
ablate_active: 9304/16000
ablate_active: 9306/16000
ablate_active: 9308/16000
ablate_active: 9310/16000
ablate_active: 9312/16000
ablate_active: 9314/16000
ablate_active: 9316/16000
ablate_active: 9318/16000
ablate_active: 9320/16000
ablate_active: 9322/16000
ablate_active: 9324/16000
ablate_active: 9326/16000
ablate_active: 9328/16000
ablate_active: 9330/16000
ablate_active: 9332/16000
ablate_active: 9334/16000
ablate_active: 9336/16000
ablate_active: 9338/16000
ablate_active: 9340/16000
ablate_active: 9342/16000
ablate_active: 9344/16000
ablate_active: 9346/16000
ablate_active: 9348/16000
ablate_active: 9350/16000
ablate_active: 9352/16000
ablate_active: 9354/16000
ablate_active: 9356/16000
ablate_active: 9358/16000
ablate_active: 9360/16000
ablate_active: 9362/16000
ablate_active: 9364/16000
ablate_active: 9366/16000
ablate_active: 9368/16000
ablate_active: 9370/16000
ablate_active: 9372/16000
ablate_active: 9374/16000
ablate_active: 9376/16000
ablate_active: 9378/16000
ablate_active: 9380/16000
ablate_active: 9382/16000
ablate_active: 9384/16000
ablate_active: 9386/16000
ablate_active: 9388/16000
ablate_active: 9390/16000
ablate_active: 9392/16000
ablate_active: 9394/16000
ablate_active: 9396/16000
ablate_active: 9398/16000
ablate_active: 9400/16000
ablate_active: 9402/16000
ablate_active: 9404/16000
ablate_active: 9406/16000
ablate_active: 9408/16000
ablate_active: 9410/16000
ablate_active: 9412/16000
ablate_active: 9414/16000
ablate_active: 9416/16000
ablate_active: 9418/16000
ablate_active: 9420/16000
ablate_active: 9422/16000
ablate_active: 9424/16000
ablate_active: 9426/16000
ablate_active: 9428/16000
ablate_active: 9430/16000
ablate_active: 9432/16000
ablate_active: 9434/16000
ablate_active: 9436/16000
ablate_active: 9438/16000
ablate_active: 9440/16000
ablate_active: 9442/16000
ablate_active: 9444/16000
ablate_active: 9446/16000
ablate_active: 9448/16000
ablate_active: 9450/16000
ablate_active: 9452/16000
ablate_active: 9454/16000
ablate_active: 9456/16000
ablate_active: 9458/16000
ablate_active: 9460/16000
ablate_active: 9462/16000
ablate_active: 9464/16000
ablate_active: 9466/16000
ablate_active: 9468/16000
ablate_active: 9470/16000
ablate_active: 9472/16000
ablate_active: 9474/16000
ablate_active: 9476/16000
ablate_active: 9478/16000
ablate_active: 9480/16000
ablate_active: 9482/16000
ablate_active: 9484/16000
ablate_active: 9486/16000
ablate_active: 9488/16000
ablate_active: 9490/16000
ablate_active: 9492/16000
ablate_active: 9494/16000
ablate_active: 9496/16000
ablate_active: 9498/16000
ablate_active: 9500/16000
ablate_active: 9502/16000
ablate_active: 9504/16000
ablate_active: 9506/16000
ablate_active: 9508/16000
ablate_active: 9510/16000
ablate_active: 9512/16000
ablate_active: 9514/16000
ablate_active: 9516/16000
ablate_active: 9518/16000
ablate_active: 9520/16000
ablate_active: 9522/16000
ablate_active: 9524/16000
ablate_active: 9526/16000
ablate_active: 9528/16000
ablate_active: 9530/16000
ablate_active: 9532/16000
ablate_active: 9534/16000
ablate_active: 9536/16000
ablate_active: 9538/16000
ablate_active: 9540/16000
ablate_active: 9542/16000

ablate_active: 9544/16000
ablate_active: 9546/16000
ablate_active: 9548/16000
ablate_active: 9550/16000
ablate_active: 9552/16000
ablate_active: 9554/16000
ablate_active: 9556/16000
ablate_active: 9558/16000
ablate_active: 9560/16000
ablate_active: 9562/16000
ablate_active: 9564/16000
ablate_active: 9566/16000
ablate_active: 9568/16000
ablate_active: 9570/16000
ablate_active: 9572/16000
ablate_active: 9574/16000
ablate_active: 9576/16000
ablate_active: 9578/16000
ablate_active: 9580/16000
ablate_active: 9582/16000
ablate_active: 9584/16000
ablate_active: 9586/16000
ablate_active: 9588/16000
ablate_active: 9590/16000
ablate_active: 9592/16000
ablate_active: 9594/16000
ablate_active: 9596/16000
ablate_active: 9598/16000
ablate_active: 9600/16000
ablate_active: 9602/16000
ablate_active: 9604/16000
ablate_active: 9606/16000
ablate_active: 9608/16000
ablate_active: 9610/16000
ablate_active: 9612/16000
ablate_active: 9614/16000
ablate_active: 9616/16000
ablate_active: 9618/16000
ablate_active: 9620/16000
ablate_active: 9622/16000
ablate_active: 9624/16000
ablate_active: 9626/16000
ablate_active: 9628/16000
ablate_active: 9630/16000
ablate_active: 9632/16000
ablate_active: 9634/16000
ablate_active: 9636/16000
ablate_active: 9638/16000
ablate_active: 9640/16000
ablate_active: 9642/16000
ablate_active: 9644/16000
ablate_active: 9646/16000
ablate_active: 9648/16000
ablate_active: 9650/16000
ablate_active: 9652/16000
ablate_active: 9654/16000
ablate_active: 9656/16000
ablate_active: 9658/16000
ablate_active: 9660/16000
ablate_active: 9662/16000
ablate_active: 9664/16000
ablate_active: 9666/16000
ablate_active: 9668/16000
ablate_active: 9670/16000
ablate_active: 9672/16000
ablate_active: 9674/16000
ablate_active: 9676/16000
ablate_active: 9678/16000
ablate_active: 9680/16000
ablate_active: 9682/16000
ablate_active: 9684/16000
ablate_active: 9686/16000
ablate_active: 9688/16000
ablate_active: 9690/16000
ablate_active: 9692/16000
ablate_active: 9694/16000
ablate_active: 9696/16000
ablate_active: 9698/16000
ablate_active: 9700/16000
ablate_active: 9702/16000
ablate_active: 9704/16000
ablate_active: 9706/16000
ablate_active: 9708/16000
ablate_active: 9710/16000
ablate_active: 9712/16000
ablate_active: 9714/16000
ablate_active: 9716/16000
ablate_active: 9718/16000
ablate_active: 9720/16000
ablate_active: 9722/16000
ablate_active: 9724/16000
ablate_active: 9726/16000
ablate_active: 9728/16000
ablate_active: 9730/16000
ablate_active: 9732/16000
ablate_active: 9734/16000
ablate_active: 9736/16000
ablate_active: 9738/16000
ablate_active: 9740/16000
ablate_active: 9742/16000
ablate_active: 9744/16000
ablate_active: 9746/16000
ablate_active: 9748/16000
ablate_active: 9750/16000
ablate_active: 9752/16000
ablate_active: 9754/16000
ablate_active: 9756/16000
ablate_active: 9758/16000
ablate_active: 9760/16000
ablate_active: 9762/16000
ablate_active: 9764/16000
ablate_active: 9766/16000
ablate_active: 9768/16000
ablate_active: 9770/16000
ablate_active: 9772/16000
ablate_active: 9774/16000
ablate_active: 9776/16000
ablate_active: 9778/16000
ablate_active: 9780/16000
ablate_active: 9782/16000
ablate_active: 9784/16000
ablate_active: 9786/16000
ablate_active: 9788/16000
ablate_active: 9790/16000
ablate_active: 9792/16000
ablate_active: 9794/16000
ablate_active: 9796/16000
ablate_active: 9798/16000
ablate_active: 9800/16000
ablate_active: 9802/16000
ablate_active: 9804/16000
ablate_active: 9806/16000
ablate_active: 9808/16000
ablate_active: 9810/16000
ablate_active: 9812/16000
ablate_active: 9814/16000
ablate_active: 9816/16000
ablate_active: 9818/16000
ablate_active: 9820/16000
ablate_active: 9822/16000
ablate_active: 9824/16000
ablate_active: 9826/16000
ablate_active: 9828/16000
ablate_active: 9830/16000
ablate_active: 9832/16000
ablate_active: 9834/16000
ablate_active: 9836/16000
ablate_active: 9838/16000
ablate_active: 9840/16000
ablate_active: 9842/16000
ablate_active: 9844/16000
ablate_active: 9846/16000
ablate_active: 9848/16000
ablate_active: 9850/16000
ablate_active: 9852/16000
ablate_active: 9854/16000
ablate_active: 9856/16000
ablate_active: 9858/16000
ablate_active: 9860/16000
ablate_active: 9862/16000
ablate_active: 9864/16000
ablate_active: 9866/16000
ablate_active: 9868/16000
ablate_active: 9870/16000
ablate_active: 9872/16000
ablate_active: 9874/16000
ablate_active: 9876/16000
ablate_active: 9878/16000
ablate_active: 9880/16000
ablate_active: 9882/16000
ablate_active: 9884/16000
ablate_active: 9886/16000
ablate_active: 9888/16000
ablate_active: 9890/16000
ablate_active: 9892/16000
ablate_active: 9894/16000
ablate_active: 9896/16000
ablate_active: 9898/16000
ablate_active: 9900/16000
ablate_active: 9902/16000
ablate_active: 9904/16000
ablate_active: 9906/16000
ablate_active: 9908/16000
ablate_active: 9910/16000
ablate_active: 9912/16000
ablate_active: 9914/16000
ablate_active: 9916/16000
ablate_active: 9918/16000
ablate_active: 9920/16000
ablate_active: 9922/16000
ablate_active: 9924/16000
ablate_active: 9926/16000
ablate_active: 9928/16000
ablate_active: 9930/16000
ablate_active: 9932/16000
ablate_active: 9934/16000
ablate_active: 9936/16000
ablate_active: 9938/16000
ablate_active: 9940/16000
ablate_active: 9942/16000
ablate_active: 9944/16000
ablate_active: 9946/16000
ablate_active: 9948/16000
ablate_active: 9950/16000
ablate_active: 9952/16000
ablate_active: 9954/16000
ablate_active: 9956/16000
ablate_active: 9958/16000
ablate_active: 9960/16000
ablate_active: 9962/16000
ablate_active: 9964/16000
ablate_active: 9966/16000
ablate_active: 9968/16000
ablate_active: 9970/16000
ablate_active: 9972/16000
ablate_active: 9974/16000
ablate_active: 9976/16000
ablate_active: 9978/16000
ablate_active: 9980/16000
ablate_active: 9982/16000
ablate_active: 9984/16000
ablate_active: 9986/16000
ablate_active: 9988/16000
ablate_active: 9990/16000
ablate_active: 9992/16000
ablate_active: 9994/16000
ablate_active: 9996/16000
ablate_active: 9998/16000
ablate_active: 10000/16000
ablate_active: 10002/16000
ablate_active: 10004/16000
ablate_active: 10006/16000
ablate_active: 10008/16000
ablate_active: 10010/16000
ablate_active: 10012/16000
ablate_active: 10014/16000
ablate_active: 10016/16000
ablate_active: 10018/16000
ablate_active: 10020/16000
ablate_active: 10022/16000
ablate_active: 10024/16000
ablate_active: 10026/16000
ablate_active: 10028/16000
ablate_active: 10030/16000
ablate_active: 10032/16000
ablate_active: 10034/16000
ablate_active: 10036/16000
ablate_active: 10038/16000
ablate_active: 10040/16000
ablate_active: 10042/16000
ablate_active: 10044/16000
ablate_active: 10046/16000
ablate_active: 10048/16000
ablate_active: 10050/16000
ablate_active: 10052/16000
ablate_active: 10054/16000
ablate_active: 10056/16000
ablate_active: 10058/16000
ablate_active: 10060/16000
ablate_active: 10062/16000
ablate_active: 10064/16000
ablate_active: 10066/16000
ablate_active: 10068/16000
ablate_active: 10070/16000
ablate_active: 10072/16000
ablate_active: 10074/16000
ablate_active: 10076/16000
ablate_active: 10078/16000
ablate_active: 10080/16000
ablate_active: 10082/16000
ablate_active: 10084/16000
ablate_active: 10086/16000
ablate_active: 10088/16000
ablate_active: 10090/16000
ablate_active: 10092/16000
ablate_active: 10094/16000
ablate_active: 10096/16000
ablate_active: 10098/16000
ablate_active: 10100/16000
ablate_active: 10102/16000
ablate_active: 10104/16000
ablate_active: 10106/16000
ablate_active: 10108/16000
ablate_active: 10110/16000
ablate_active: 10112/16000
ablate_active: 10114/16000
ablate_active: 10116/16000
ablate_active: 10118/16000
ablate_active: 10120/16000
ablate_active: 10122/16000
ablate_active: 10124/16000
ablate_active: 10126/16000
ablate_active: 10128/16000
ablate_active: 10130/16000
ablate_active: 10132/16000
ablate_active: 10134/16000
ablate_active: 10136/16000
ablate_active: 10138/16000
ablate_active: 10140/16000
ablate_active: 10142/16000
ablate_active: 10144/16000
ablate_active: 10146/16000
ablate_active: 10148/16000
ablate_active: 10150/16000
ablate_active: 10152/16000
ablate_active: 10154/16000
ablate_active: 10156/16000
ablate_active: 10158/16000
ablate_active: 10160/16000
ablate_active: 10162/16000
ablate_active: 10164/16000
ablate_active: 10166/16000

ablate_active: 10168/16000
ablate_active: 10170/16000
ablate_active: 10172/16000
ablate_active: 10174/16000
ablate_active: 10176/16000
ablate_active: 10178/16000
ablate_active: 10180/16000
ablate_active: 10182/16000
ablate_active: 10184/16000
ablate_active: 10186/16000
ablate_active: 10188/16000
ablate_active: 10190/16000
ablate_active: 10192/16000
ablate_active: 10194/16000
ablate_active: 10196/16000
ablate_active: 10198/16000
ablate_active: 10200/16000
ablate_active: 10202/16000
ablate_active: 10204/16000
ablate_active: 10206/16000
ablate_active: 10208/16000
ablate_active: 10210/16000
ablate_active: 10212/16000
ablate_active: 10214/16000
ablate_active: 10216/16000
ablate_active: 10218/16000
ablate_active: 10220/16000
ablate_active: 10222/16000
ablate_active: 10224/16000
ablate_active: 10226/16000
ablate_active: 10228/16000
ablate_active: 10230/16000
ablate_active: 10232/16000
ablate_active: 10234/16000
ablate_active: 10236/16000
ablate_active: 10238/16000
ablate_active: 10240/16000
ablate_active: 10242/16000
ablate_active: 10244/16000
ablate_active: 10246/16000
ablate_active: 10248/16000
ablate_active: 10250/16000
ablate_active: 10252/16000
ablate_active: 10254/16000
ablate_active: 10256/16000
ablate_active: 10258/16000
ablate_active: 10260/16000
ablate_active: 10262/16000
ablate_active: 10264/16000
ablate_active: 10266/16000
ablate_active: 10268/16000
ablate_active: 10270/16000
ablate_active: 10272/16000
ablate_active: 10274/16000
ablate_active: 10276/16000
ablate_active: 10278/16000
ablate_active: 10280/16000
ablate_active: 10282/16000
ablate_active: 10284/16000
ablate_active: 10286/16000
ablate_active: 10288/16000
ablate_active: 10290/16000
ablate_active: 10292/16000
ablate_active: 10294/16000
ablate_active: 10296/16000
ablate_active: 10298/16000
ablate_active: 10300/16000
ablate_active: 10302/16000
ablate_active: 10304/16000
ablate_active: 10306/16000
ablate_active: 10308/16000
ablate_active: 10310/16000
ablate_active: 10312/16000
ablate_active: 10314/16000
ablate_active: 10316/16000
ablate_active: 10318/16000
ablate_active: 10320/16000
ablate_active: 10322/16000
ablate_active: 10324/16000
ablate_active: 10326/16000
ablate_active: 10328/16000
ablate_active: 10330/16000
ablate_active: 10332/16000
ablate_active: 10334/16000
ablate_active: 10336/16000
ablate_active: 10338/16000
ablate_active: 10340/16000
ablate_active: 10342/16000
ablate_active: 10344/16000
ablate_active: 10346/16000
ablate_active: 10348/16000
ablate_active: 10350/16000
ablate_active: 10352/16000
ablate_active: 10354/16000
ablate_active: 10356/16000
ablate_active: 10358/16000
ablate_active: 10360/16000
ablate_active: 10362/16000
ablate_active: 10364/16000
ablate_active: 10366/16000
ablate_active: 10368/16000
ablate_active: 10370/16000
ablate_active: 10372/16000
ablate_active: 10374/16000
ablate_active: 10376/16000
ablate_active: 10378/16000
ablate_active: 10380/16000
ablate_active: 10382/16000
ablate_active: 10384/16000
ablate_active: 10386/16000
ablate_active: 10388/16000
ablate_active: 10390/16000
ablate_active: 10392/16000
ablate_active: 10394/16000
ablate_active: 10396/16000
ablate_active: 10398/16000
ablate_active: 10400/16000
ablate_active: 10402/16000
ablate_active: 10404/16000
ablate_active: 10406/16000
ablate_active: 10408/16000
ablate_active: 10410/16000
ablate_active: 10412/16000
ablate_active: 10414/16000
ablate_active: 10416/16000
ablate_active: 10418/16000
ablate_active: 10420/16000
ablate_active: 10422/16000
ablate_active: 10424/16000
ablate_active: 10426/16000
ablate_active: 10428/16000
ablate_active: 10430/16000
ablate_active: 10432/16000
ablate_active: 10434/16000
ablate_active: 10436/16000
ablate_active: 10438/16000
ablate_active: 10440/16000
ablate_active: 10442/16000
ablate_active: 10444/16000
ablate_active: 10446/16000
ablate_active: 10448/16000
ablate_active: 10450/16000
ablate_active: 10452/16000
ablate_active: 10454/16000
ablate_active: 10456/16000
ablate_active: 10458/16000
ablate_active: 10460/16000
ablate_active: 10462/16000
ablate_active: 10464/16000
ablate_active: 10466/16000
ablate_active: 10468/16000
ablate_active: 10470/16000
ablate_active: 10472/16000
ablate_active: 10474/16000
ablate_active: 10476/16000
ablate_active: 10478/16000
ablate_active: 10480/16000
ablate_active: 10482/16000
ablate_active: 10484/16000
ablate_active: 10486/16000
ablate_active: 10488/16000
ablate_active: 10490/16000
ablate_active: 10492/16000
ablate_active: 10494/16000
ablate_active: 10496/16000
ablate_active: 10498/16000
ablate_active: 10500/16000
ablate_active: 10502/16000
ablate_active: 10504/16000
ablate_active: 10506/16000
ablate_active: 10508/16000
ablate_active: 10510/16000
ablate_active: 10512/16000
ablate_active: 10514/16000
ablate_active: 10516/16000
ablate_active: 10518/16000
ablate_active: 10520/16000
ablate_active: 10522/16000
ablate_active: 10524/16000
ablate_active: 10526/16000
ablate_active: 10528/16000
ablate_active: 10530/16000
ablate_active: 10532/16000
ablate_active: 10534/16000
ablate_active: 10536/16000
ablate_active: 10538/16000
ablate_active: 10540/16000
ablate_active: 10542/16000
ablate_active: 10544/16000
ablate_active: 10546/16000
ablate_active: 10548/16000
ablate_active: 10550/16000
ablate_active: 10552/16000
ablate_active: 10554/16000
ablate_active: 10556/16000
ablate_active: 10558/16000
ablate_active: 10560/16000
ablate_active: 10562/16000
ablate_active: 10564/16000
ablate_active: 10566/16000
ablate_active: 10568/16000
ablate_active: 10570/16000
ablate_active: 10572/16000
ablate_active: 10574/16000
ablate_active: 10576/16000
ablate_active: 10578/16000
ablate_active: 10580/16000
ablate_active: 10582/16000
ablate_active: 10584/16000
ablate_active: 10586/16000
ablate_active: 10588/16000
ablate_active: 10590/16000
ablate_active: 10592/16000
ablate_active: 10594/16000
ablate_active: 10596/16000
ablate_active: 10598/16000
ablate_active: 10600/16000
ablate_active: 10602/16000
ablate_active: 10604/16000
ablate_active: 10606/16000
ablate_active: 10608/16000
ablate_active: 10610/16000
ablate_active: 10612/16000
ablate_active: 10614/16000
ablate_active: 10616/16000
ablate_active: 10618/16000
ablate_active: 10620/16000
ablate_active: 10622/16000
ablate_active: 10624/16000
ablate_active: 10626/16000
ablate_active: 10628/16000
ablate_active: 10630/16000
ablate_active: 10632/16000
ablate_active: 10634/16000
ablate_active: 10636/16000
ablate_active: 10638/16000
ablate_active: 10640/16000
ablate_active: 10642/16000
ablate_active: 10644/16000
ablate_active: 10646/16000
ablate_active: 10648/16000
ablate_active: 10650/16000
ablate_active: 10652/16000
ablate_active: 10654/16000
ablate_active: 10656/16000
ablate_active: 10658/16000
ablate_active: 10660/16000
ablate_active: 10662/16000
ablate_active: 10664/16000
ablate_active: 10666/16000
ablate_active: 10668/16000
ablate_active: 10670/16000
ablate_active: 10672/16000
ablate_active: 10674/16000
ablate_active: 10676/16000
ablate_active: 10678/16000
ablate_active: 10680/16000
ablate_active: 10682/16000
ablate_active: 10684/16000
ablate_active: 10686/16000
ablate_active: 10688/16000
ablate_active: 10690/16000
ablate_active: 10692/16000
ablate_active: 10694/16000
ablate_active: 10696/16000
ablate_active: 10698/16000
ablate_active: 10700/16000
ablate_active: 10702/16000
ablate_active: 10704/16000
ablate_active: 10706/16000
ablate_active: 10708/16000
ablate_active: 10710/16000
ablate_active: 10712/16000
ablate_active: 10714/16000
ablate_active: 10716/16000
ablate_active: 10718/16000
ablate_active: 10720/16000
ablate_active: 10722/16000
ablate_active: 10724/16000
ablate_active: 10726/16000
ablate_active: 10728/16000
ablate_active: 10730/16000
ablate_active: 10732/16000
ablate_active: 10734/16000
ablate_active: 10736/16000
ablate_active: 10738/16000
ablate_active: 10740/16000
ablate_active: 10742/16000
ablate_active: 10744/16000
ablate_active: 10746/16000
ablate_active: 10748/16000
ablate_active: 10750/16000
ablate_active: 10752/16000
ablate_active: 10754/16000
ablate_active: 10756/16000
ablate_active: 10758/16000
ablate_active: 10760/16000
ablate_active: 10762/16000
ablate_active: 10764/16000
ablate_active: 10766/16000
ablate_active: 10768/16000
ablate_active: 10770/16000
ablate_active: 10772/16000
ablate_active: 10774/16000
ablate_active: 10776/16000
ablate_active: 10778/16000

ablate_active: 10780/16000
ablate_active: 10782/16000
ablate_active: 10784/16000
ablate_active: 10786/16000
ablate_active: 10788/16000
ablate_active: 10790/16000
ablate_active: 10792/16000
ablate_active: 10794/16000
ablate_active: 10796/16000
ablate_active: 10798/16000
ablate_active: 10800/16000
ablate_active: 10802/16000
ablate_active: 10804/16000
ablate_active: 10806/16000
ablate_active: 10808/16000
ablate_active: 10810/16000
ablate_active: 10812/16000
ablate_active: 10814/16000
ablate_active: 10816/16000
ablate_active: 10818/16000
ablate_active: 10820/16000
ablate_active: 10822/16000
ablate_active: 10824/16000
ablate_active: 10826/16000
ablate_active: 10828/16000
ablate_active: 10830/16000
ablate_active: 10832/16000
ablate_active: 10834/16000
ablate_active: 10836/16000
ablate_active: 10838/16000
ablate_active: 10840/16000
ablate_active: 10842/16000
ablate_active: 10844/16000
ablate_active: 10846/16000
ablate_active: 10848/16000
ablate_active: 10850/16000
ablate_active: 10852/16000
ablate_active: 10854/16000
ablate_active: 10856/16000
ablate_active: 10858/16000
ablate_active: 10860/16000
ablate_active: 10862/16000
ablate_active: 10864/16000
ablate_active: 10866/16000
ablate_active: 10868/16000
ablate_active: 10870/16000
ablate_active: 10872/16000
ablate_active: 10874/16000
ablate_active: 10876/16000
ablate_active: 10878/16000
ablate_active: 10880/16000
ablate_active: 10882/16000
ablate_active: 10884/16000
ablate_active: 10886/16000
ablate_active: 10888/16000
ablate_active: 10890/16000
ablate_active: 10892/16000
ablate_active: 10894/16000
ablate_active: 10896/16000
ablate_active: 10898/16000
ablate_active: 10900/16000
ablate_active: 10902/16000
ablate_active: 10904/16000
ablate_active: 10906/16000
ablate_active: 10908/16000
ablate_active: 10910/16000
ablate_active: 10912/16000
ablate_active: 10914/16000
ablate_active: 10916/16000
ablate_active: 10918/16000
ablate_active: 10920/16000
ablate_active: 10922/16000
ablate_active: 10924/16000
ablate_active: 10926/16000
ablate_active: 10928/16000
ablate_active: 10930/16000
ablate_active: 10932/16000
ablate_active: 10934/16000
ablate_active: 10936/16000
ablate_active: 10938/16000
ablate_active: 10940/16000
ablate_active: 10942/16000
ablate_active: 10944/16000
ablate_active: 10946/16000
ablate_active: 10948/16000
ablate_active: 10950/16000
ablate_active: 10952/16000
ablate_active: 10954/16000
ablate_active: 10956/16000
ablate_active: 10958/16000
ablate_active: 10960/16000
ablate_active: 10962/16000
ablate_active: 10964/16000
ablate_active: 10966/16000
ablate_active: 10968/16000
ablate_active: 10970/16000
ablate_active: 10972/16000
ablate_active: 10974/16000
ablate_active: 10976/16000
ablate_active: 10978/16000
ablate_active: 10980/16000
ablate_active: 10982/16000
ablate_active: 10984/16000
ablate_active: 10986/16000
ablate_active: 10988/16000
ablate_active: 10990/16000
ablate_active: 10992/16000
ablate_active: 10994/16000
ablate_active: 10996/16000
ablate_active: 10998/16000
ablate_active: 11000/16000
ablate_active: 11002/16000
ablate_active: 11004/16000
ablate_active: 11006/16000
ablate_active: 11008/16000
ablate_active: 11010/16000
ablate_active: 11012/16000
ablate_active: 11014/16000
ablate_active: 11016/16000
ablate_active: 11018/16000
ablate_active: 11020/16000
ablate_active: 11022/16000
ablate_active: 11024/16000
ablate_active: 11026/16000
ablate_active: 11028/16000
ablate_active: 11030/16000
ablate_active: 11032/16000
ablate_active: 11034/16000
ablate_active: 11036/16000
ablate_active: 11038/16000
ablate_active: 11040/16000
ablate_active: 11042/16000
ablate_active: 11044/16000
ablate_active: 11046/16000
ablate_active: 11048/16000
ablate_active: 11050/16000
ablate_active: 11052/16000
ablate_active: 11054/16000
ablate_active: 11056/16000
ablate_active: 11058/16000
ablate_active: 11060/16000
ablate_active: 11062/16000
ablate_active: 11064/16000
ablate_active: 11066/16000
ablate_active: 11068/16000
ablate_active: 11070/16000
ablate_active: 11072/16000
ablate_active: 11074/16000
ablate_active: 11076/16000
ablate_active: 11078/16000
ablate_active: 11080/16000
ablate_active: 11082/16000
ablate_active: 11084/16000
ablate_active: 11086/16000
ablate_active: 11088/16000
ablate_active: 11090/16000
ablate_active: 11092/16000
ablate_active: 11094/16000
ablate_active: 11096/16000
ablate_active: 11098/16000
ablate_active: 11100/16000
ablate_active: 11102/16000
ablate_active: 11104/16000
ablate_active: 11106/16000
ablate_active: 11108/16000
ablate_active: 11110/16000
ablate_active: 11112/16000
ablate_active: 11114/16000
ablate_active: 11116/16000
ablate_active: 11118/16000
ablate_active: 11120/16000
ablate_active: 11122/16000
ablate_active: 11124/16000
ablate_active: 11126/16000
ablate_active: 11128/16000
ablate_active: 11130/16000
ablate_active: 11132/16000
ablate_active: 11134/16000
ablate_active: 11136/16000
ablate_active: 11138/16000
ablate_active: 11140/16000
ablate_active: 11142/16000
ablate_active: 11144/16000
ablate_active: 11146/16000
ablate_active: 11148/16000
ablate_active: 11150/16000
ablate_active: 11152/16000
ablate_active: 11154/16000
ablate_active: 11156/16000
ablate_active: 11158/16000
ablate_active: 11160/16000
ablate_active: 11162/16000
ablate_active: 11164/16000
ablate_active: 11166/16000
ablate_active: 11168/16000
ablate_active: 11170/16000
ablate_active: 11172/16000
ablate_active: 11174/16000
ablate_active: 11176/16000
ablate_active: 11178/16000
ablate_active: 11180/16000
ablate_active: 11182/16000
ablate_active: 11184/16000
ablate_active: 11186/16000
ablate_active: 11188/16000
ablate_active: 11190/16000
ablate_active: 11192/16000
ablate_active: 11194/16000
ablate_active: 11196/16000
ablate_active: 11198/16000
ablate_active: 11200/16000
ablate_active: 11202/16000
ablate_active: 11204/16000
ablate_active: 11206/16000
ablate_active: 11208/16000
ablate_active: 11210/16000
ablate_active: 11212/16000
ablate_active: 11214/16000
ablate_active: 11216/16000
ablate_active: 11218/16000
ablate_active: 11220/16000
ablate_active: 11222/16000
ablate_active: 11224/16000
ablate_active: 11226/16000
ablate_active: 11228/16000
ablate_active: 11230/16000
ablate_active: 11232/16000
ablate_active: 11234/16000
ablate_active: 11236/16000
ablate_active: 11238/16000
ablate_active: 11240/16000
ablate_active: 11242/16000
ablate_active: 11244/16000
ablate_active: 11246/16000
ablate_active: 11248/16000
ablate_active: 11250/16000
ablate_active: 11252/16000
ablate_active: 11254/16000
ablate_active: 11256/16000
ablate_active: 11258/16000
ablate_active: 11260/16000
ablate_active: 11262/16000
ablate_active: 11264/16000
ablate_active: 11266/16000
ablate_active: 11268/16000
ablate_active: 11270/16000
ablate_active: 11272/16000
ablate_active: 11274/16000
ablate_active: 11276/16000
ablate_active: 11278/16000
ablate_active: 11280/16000
ablate_active: 11282/16000
ablate_active: 11284/16000
ablate_active: 11286/16000
ablate_active: 11288/16000
ablate_active: 11290/16000
ablate_active: 11292/16000
ablate_active: 11294/16000
ablate_active: 11296/16000
ablate_active: 11298/16000
ablate_active: 11300/16000
ablate_active: 11302/16000
ablate_active: 11304/16000
ablate_active: 11306/16000
ablate_active: 11308/16000
ablate_active: 11310/16000
ablate_active: 11312/16000
ablate_active: 11314/16000
ablate_active: 11316/16000
ablate_active: 11318/16000
ablate_active: 11320/16000
ablate_active: 11322/16000
ablate_active: 11324/16000
ablate_active: 11326/16000
ablate_active: 11328/16000
ablate_active: 11330/16000
ablate_active: 11332/16000
ablate_active: 11334/16000
ablate_active: 11336/16000
ablate_active: 11338/16000
ablate_active: 11340/16000
ablate_active: 11342/16000
ablate_active: 11344/16000
ablate_active: 11346/16000
ablate_active: 11348/16000
ablate_active: 11350/16000
ablate_active: 11352/16000
ablate_active: 11354/16000
ablate_active: 11356/16000
ablate_active: 11358/16000
ablate_active: 11360/16000
ablate_active: 11362/16000
ablate_active: 11364/16000
ablate_active: 11366/16000
ablate_active: 11368/16000
ablate_active: 11370/16000
ablate_active: 11372/16000
ablate_active: 11374/16000
ablate_active: 11376/16000
ablate_active: 11378/16000
ablate_active: 11380/16000
ablate_active: 11382/16000
ablate_active: 11384/16000
ablate_active: 11386/16000
ablate_active: 11388/16000

ablate_active: 11390/16000
ablate_active: 11392/16000
ablate_active: 11394/16000
ablate_active: 11396/16000
ablate_active: 11398/16000
ablate_active: 11400/16000
ablate_active: 11402/16000
ablate_active: 11404/16000
ablate_active: 11406/16000
ablate_active: 11408/16000
ablate_active: 11410/16000
ablate_active: 11412/16000
ablate_active: 11414/16000
ablate_active: 11416/16000
ablate_active: 11418/16000
ablate_active: 11420/16000
ablate_active: 11422/16000
ablate_active: 11424/16000
ablate_active: 11426/16000
ablate_active: 11428/16000
ablate_active: 11430/16000
ablate_active: 11432/16000
ablate_active: 11434/16000
ablate_active: 11436/16000
ablate_active: 11438/16000
ablate_active: 11440/16000
ablate_active: 11442/16000
ablate_active: 11444/16000
ablate_active: 11446/16000
ablate_active: 11448/16000
ablate_active: 11450/16000
ablate_active: 11452/16000
ablate_active: 11454/16000
ablate_active: 11456/16000
ablate_active: 11458/16000
ablate_active: 11460/16000
ablate_active: 11462/16000
ablate_active: 11464/16000
ablate_active: 11466/16000
ablate_active: 11468/16000
ablate_active: 11470/16000
ablate_active: 11472/16000
ablate_active: 11474/16000
ablate_active: 11476/16000
ablate_active: 11478/16000
ablate_active: 11480/16000
ablate_active: 11482/16000
ablate_active: 11484/16000
ablate_active: 11486/16000
ablate_active: 11488/16000
ablate_active: 11490/16000
ablate_active: 11492/16000
ablate_active: 11494/16000
ablate_active: 11496/16000
ablate_active: 11498/16000
ablate_active: 11500/16000
ablate_active: 11502/16000
ablate_active: 11504/16000
ablate_active: 11506/16000
ablate_active: 11508/16000
ablate_active: 11510/16000
ablate_active: 11512/16000
ablate_active: 11514/16000
ablate_active: 11516/16000
ablate_active: 11518/16000
ablate_active: 11520/16000
ablate_active: 11522/16000
ablate_active: 11524/16000
ablate_active: 11526/16000
ablate_active: 11528/16000
ablate_active: 11530/16000
ablate_active: 11532/16000
ablate_active: 11534/16000
ablate_active: 11536/16000
ablate_active: 11538/16000
ablate_active: 11540/16000
ablate_active: 11542/16000
ablate_active: 11544/16000
ablate_active: 11546/16000
ablate_active: 11548/16000
ablate_active: 11550/16000
ablate_active: 11552/16000
ablate_active: 11554/16000
ablate_active: 11556/16000
ablate_active: 11558/16000
ablate_active: 11560/16000
ablate_active: 11562/16000
ablate_active: 11564/16000
ablate_active: 11566/16000
ablate_active: 11568/16000
ablate_active: 11570/16000
ablate_active: 11572/16000
ablate_active: 11574/16000
ablate_active: 11576/16000
ablate_active: 11578/16000
ablate_active: 11580/16000
ablate_active: 11582/16000
ablate_active: 11584/16000
ablate_active: 11586/16000
ablate_active: 11588/16000
ablate_active: 11590/16000
ablate_active: 11592/16000
ablate_active: 11594/16000
ablate_active: 11596/16000
ablate_active: 11598/16000
ablate_active: 11600/16000
ablate_active: 11602/16000
ablate_active: 11604/16000
ablate_active: 11606/16000
ablate_active: 11608/16000
ablate_active: 11610/16000
ablate_active: 11612/16000
ablate_active: 11614/16000
ablate_active: 11616/16000
ablate_active: 11618/16000
ablate_active: 11620/16000
ablate_active: 11622/16000
ablate_active: 11624/16000
ablate_active: 11626/16000
ablate_active: 11628/16000
ablate_active: 11630/16000
ablate_active: 11632/16000
ablate_active: 11634/16000
ablate_active: 11636/16000
ablate_active: 11638/16000
ablate_active: 11640/16000
ablate_active: 11642/16000
ablate_active: 11644/16000
ablate_active: 11646/16000
ablate_active: 11648/16000
ablate_active: 11650/16000
ablate_active: 11652/16000
ablate_active: 11654/16000
ablate_active: 11656/16000
ablate_active: 11658/16000
ablate_active: 11660/16000
ablate_active: 11662/16000
ablate_active: 11664/16000
ablate_active: 11666/16000
ablate_active: 11668/16000
ablate_active: 11670/16000
ablate_active: 11672/16000
ablate_active: 11674/16000
ablate_active: 11676/16000
ablate_active: 11678/16000
ablate_active: 11680/16000
ablate_active: 11682/16000
ablate_active: 11684/16000
ablate_active: 11686/16000
ablate_active: 11688/16000
ablate_active: 11690/16000
ablate_active: 11692/16000
ablate_active: 11694/16000
ablate_active: 11696/16000
ablate_active: 11698/16000
ablate_active: 11700/16000
ablate_active: 11702/16000
ablate_active: 11704/16000
ablate_active: 11706/16000
ablate_active: 11708/16000
ablate_active: 11710/16000
ablate_active: 11712/16000
ablate_active: 11714/16000
ablate_active: 11716/16000
ablate_active: 11718/16000
ablate_active: 11720/16000
ablate_active: 11722/16000
ablate_active: 11724/16000
ablate_active: 11726/16000
ablate_active: 11728/16000
ablate_active: 11730/16000
ablate_active: 11732/16000
ablate_active: 11734/16000
ablate_active: 11736/16000
ablate_active: 11738/16000
ablate_active: 11740/16000
ablate_active: 11742/16000
ablate_active: 11744/16000
ablate_active: 11746/16000
ablate_active: 11748/16000
ablate_active: 11750/16000
ablate_active: 11752/16000
ablate_active: 11754/16000
ablate_active: 11756/16000
ablate_active: 11758/16000
ablate_active: 11760/16000
ablate_active: 11762/16000
ablate_active: 11764/16000
ablate_active: 11766/16000
ablate_active: 11768/16000
ablate_active: 11770/16000
ablate_active: 11772/16000
ablate_active: 11774/16000
ablate_active: 11776/16000
ablate_active: 11778/16000
ablate_active: 11780/16000
ablate_active: 11782/16000
ablate_active: 11784/16000
ablate_active: 11786/16000
ablate_active: 11788/16000
ablate_active: 11790/16000
ablate_active: 11792/16000
ablate_active: 11794/16000
ablate_active: 11796/16000
ablate_active: 11798/16000
ablate_active: 11800/16000
ablate_active: 11802/16000
ablate_active: 11804/16000
ablate_active: 11806/16000
ablate_active: 11808/16000
ablate_active: 11810/16000
ablate_active: 11812/16000
ablate_active: 11814/16000
ablate_active: 11816/16000
ablate_active: 11818/16000
ablate_active: 11820/16000
ablate_active: 11822/16000
ablate_active: 11824/16000
ablate_active: 11826/16000
ablate_active: 11828/16000
ablate_active: 11830/16000
ablate_active: 11832/16000
ablate_active: 11834/16000
ablate_active: 11836/16000
ablate_active: 11838/16000
ablate_active: 11840/16000
ablate_active: 11842/16000
ablate_active: 11844/16000
ablate_active: 11846/16000
ablate_active: 11848/16000
ablate_active: 11850/16000
ablate_active: 11852/16000
ablate_active: 11854/16000
ablate_active: 11856/16000
ablate_active: 11858/16000
ablate_active: 11860/16000
ablate_active: 11862/16000
ablate_active: 11864/16000
ablate_active: 11866/16000
ablate_active: 11868/16000
ablate_active: 11870/16000
ablate_active: 11872/16000
ablate_active: 11874/16000
ablate_active: 11876/16000
ablate_active: 11878/16000
ablate_active: 11880/16000
ablate_active: 11882/16000
ablate_active: 11884/16000
ablate_active: 11886/16000
ablate_active: 11888/16000
ablate_active: 11890/16000
ablate_active: 11892/16000
ablate_active: 11894/16000
ablate_active: 11896/16000
ablate_active: 11898/16000
ablate_active: 11900/16000
ablate_active: 11902/16000
ablate_active: 11904/16000
ablate_active: 11906/16000
ablate_active: 11908/16000
ablate_active: 11910/16000
ablate_active: 11912/16000
ablate_active: 11914/16000
ablate_active: 11916/16000
ablate_active: 11918/16000
ablate_active: 11920/16000
ablate_active: 11922/16000
ablate_active: 11924/16000
ablate_active: 11926/16000
ablate_active: 11928/16000
ablate_active: 11930/16000
ablate_active: 11932/16000
ablate_active: 11934/16000
ablate_active: 11936/16000
ablate_active: 11938/16000
ablate_active: 11940/16000
ablate_active: 11942/16000
ablate_active: 11944/16000
ablate_active: 11946/16000
ablate_active: 11948/16000
ablate_active: 11950/16000
ablate_active: 11952/16000
ablate_active: 11954/16000
ablate_active: 11956/16000
ablate_active: 11958/16000
ablate_active: 11960/16000
ablate_active: 11962/16000
ablate_active: 11964/16000
ablate_active: 11966/16000
ablate_active: 11968/16000
ablate_active: 11970/16000
ablate_active: 11972/16000
ablate_active: 11974/16000
ablate_active: 11976/16000
ablate_active: 11978/16000
ablate_active: 11980/16000
ablate_active: 11982/16000
ablate_active: 11984/16000
ablate_active: 11986/16000
ablate_active: 11988/16000
ablate_active: 11990/16000
ablate_active: 11992/16000
ablate_active: 11994/16000
ablate_active: 11996/16000
ablate_active: 11998/16000
ablate_active: 12000/16000

ablate_active: 12002/16000
ablate_active: 12004/16000
ablate_active: 12006/16000
ablate_active: 12008/16000
ablate_active: 12010/16000
ablate_active: 12012/16000
ablate_active: 12014/16000
ablate_active: 12016/16000
ablate_active: 12018/16000
ablate_active: 12020/16000
ablate_active: 12022/16000
ablate_active: 12024/16000
ablate_active: 12026/16000
ablate_active: 12028/16000
ablate_active: 12030/16000
ablate_active: 12032/16000
ablate_active: 12034/16000
ablate_active: 12036/16000
ablate_active: 12038/16000
ablate_active: 12040/16000
ablate_active: 12042/16000
ablate_active: 12044/16000
ablate_active: 12046/16000
ablate_active: 12048/16000
ablate_active: 12050/16000
ablate_active: 12052/16000
ablate_active: 12054/16000
ablate_active: 12056/16000
ablate_active: 12058/16000
ablate_active: 12060/16000
ablate_active: 12062/16000
ablate_active: 12064/16000
ablate_active: 12066/16000
ablate_active: 12068/16000
ablate_active: 12070/16000
ablate_active: 12072/16000
ablate_active: 12074/16000
ablate_active: 12076/16000
ablate_active: 12078/16000
ablate_active: 12080/16000
ablate_active: 12082/16000
ablate_active: 12084/16000
ablate_active: 12086/16000
ablate_active: 12088/16000
ablate_active: 12090/16000
ablate_active: 12092/16000
ablate_active: 12094/16000
ablate_active: 12096/16000
ablate_active: 12098/16000
ablate_active: 12100/16000
ablate_active: 12102/16000
ablate_active: 12104/16000
ablate_active: 12106/16000
ablate_active: 12108/16000
ablate_active: 12110/16000
ablate_active: 12112/16000
ablate_active: 12114/16000
ablate_active: 12116/16000
ablate_active: 12118/16000
ablate_active: 12120/16000
ablate_active: 12122/16000
ablate_active: 12124/16000
ablate_active: 12126/16000
ablate_active: 12128/16000
ablate_active: 12130/16000
ablate_active: 12132/16000
ablate_active: 12134/16000
ablate_active: 12136/16000
ablate_active: 12138/16000
ablate_active: 12140/16000
ablate_active: 12142/16000
ablate_active: 12144/16000
ablate_active: 12146/16000
ablate_active: 12148/16000
ablate_active: 12150/16000
ablate_active: 12152/16000
ablate_active: 12154/16000
ablate_active: 12156/16000
ablate_active: 12158/16000
ablate_active: 12160/16000
ablate_active: 12162/16000
ablate_active: 12164/16000
ablate_active: 12166/16000
ablate_active: 12168/16000
ablate_active: 12170/16000
ablate_active: 12172/16000
ablate_active: 12174/16000
ablate_active: 12176/16000
ablate_active: 12178/16000
ablate_active: 12180/16000
ablate_active: 12182/16000
ablate_active: 12184/16000
ablate_active: 12186/16000
ablate_active: 12188/16000
ablate_active: 12190/16000
ablate_active: 12192/16000
ablate_active: 12194/16000
ablate_active: 12196/16000
ablate_active: 12198/16000
ablate_active: 12200/16000
ablate_active: 12202/16000
ablate_active: 12204/16000
ablate_active: 12206/16000
ablate_active: 12208/16000
ablate_active: 12210/16000
ablate_active: 12212/16000
ablate_active: 12214/16000
ablate_active: 12216/16000
ablate_active: 12218/16000
ablate_active: 12220/16000
ablate_active: 12222/16000
ablate_active: 12224/16000
ablate_active: 12226/16000
ablate_active: 12228/16000
ablate_active: 12230/16000
ablate_active: 12232/16000
ablate_active: 12234/16000
ablate_active: 12236/16000
ablate_active: 12238/16000
ablate_active: 12240/16000
ablate_active: 12242/16000
ablate_active: 12244/16000
ablate_active: 12246/16000
ablate_active: 12248/16000
ablate_active: 12250/16000
ablate_active: 12252/16000
ablate_active: 12254/16000
ablate_active: 12256/16000
ablate_active: 12258/16000
ablate_active: 12260/16000
ablate_active: 12262/16000
ablate_active: 12264/16000
ablate_active: 12266/16000
ablate_active: 12268/16000
ablate_active: 12270/16000
ablate_active: 12272/16000
ablate_active: 12274/16000
ablate_active: 12276/16000
ablate_active: 12278/16000
ablate_active: 12280/16000
ablate_active: 12282/16000
ablate_active: 12284/16000
ablate_active: 12286/16000
ablate_active: 12288/16000
ablate_active: 12290/16000
ablate_active: 12292/16000
ablate_active: 12294/16000
ablate_active: 12296/16000
ablate_active: 12298/16000
ablate_active: 12300/16000
ablate_active: 12302/16000
ablate_active: 12304/16000
ablate_active: 12306/16000
ablate_active: 12308/16000
ablate_active: 12310/16000
ablate_active: 12312/16000
ablate_active: 12314/16000
ablate_active: 12316/16000
ablate_active: 12318/16000
ablate_active: 12320/16000
ablate_active: 12322/16000
ablate_active: 12324/16000
ablate_active: 12326/16000
ablate_active: 12328/16000
ablate_active: 12330/16000
ablate_active: 12332/16000
ablate_active: 12334/16000
ablate_active: 12336/16000
ablate_active: 12338/16000
ablate_active: 12340/16000
ablate_active: 12342/16000
ablate_active: 12344/16000
ablate_active: 12346/16000
ablate_active: 12348/16000
ablate_active: 12350/16000
ablate_active: 12352/16000
ablate_active: 12354/16000
ablate_active: 12356/16000
ablate_active: 12358/16000
ablate_active: 12360/16000
ablate_active: 12362/16000
ablate_active: 12364/16000
ablate_active: 12366/16000
ablate_active: 12368/16000
ablate_active: 12370/16000
ablate_active: 12372/16000
ablate_active: 12374/16000
ablate_active: 12376/16000
ablate_active: 12378/16000
ablate_active: 12380/16000
ablate_active: 12382/16000
ablate_active: 12384/16000
ablate_active: 12386/16000
ablate_active: 12388/16000
ablate_active: 12390/16000
ablate_active: 12392/16000
ablate_active: 12394/16000
ablate_active: 12396/16000
ablate_active: 12398/16000
ablate_active: 12400/16000
ablate_active: 12402/16000
ablate_active: 12404/16000
ablate_active: 12406/16000
ablate_active: 12408/16000
ablate_active: 12410/16000
ablate_active: 12412/16000
ablate_active: 12414/16000
ablate_active: 12416/16000
ablate_active: 12418/16000
ablate_active: 12420/16000
ablate_active: 12422/16000
ablate_active: 12424/16000
ablate_active: 12426/16000
ablate_active: 12428/16000
ablate_active: 12430/16000
ablate_active: 12432/16000
ablate_active: 12434/16000
ablate_active: 12436/16000
ablate_active: 12438/16000
ablate_active: 12440/16000
ablate_active: 12442/16000
ablate_active: 12444/16000
ablate_active: 12446/16000
ablate_active: 12448/16000
ablate_active: 12450/16000
ablate_active: 12452/16000
ablate_active: 12454/16000
ablate_active: 12456/16000
ablate_active: 12458/16000
ablate_active: 12460/16000
ablate_active: 12462/16000
ablate_active: 12464/16000
ablate_active: 12466/16000
ablate_active: 12468/16000
ablate_active: 12470/16000
ablate_active: 12472/16000
ablate_active: 12474/16000
ablate_active: 12476/16000
ablate_active: 12478/16000
ablate_active: 12480/16000
ablate_active: 12482/16000
ablate_active: 12484/16000
ablate_active: 12486/16000
ablate_active: 12488/16000
ablate_active: 12490/16000
ablate_active: 12492/16000
ablate_active: 12494/16000
ablate_active: 12496/16000
ablate_active: 12498/16000
ablate_active: 12500/16000
ablate_active: 12502/16000
ablate_active: 12504/16000
ablate_active: 12506/16000
ablate_active: 12508/16000
ablate_active: 12510/16000
ablate_active: 12512/16000
ablate_active: 12514/16000
ablate_active: 12516/16000
ablate_active: 12518/16000
ablate_active: 12520/16000
ablate_active: 12522/16000
ablate_active: 12524/16000
ablate_active: 12526/16000
ablate_active: 12528/16000
ablate_active: 12530/16000
ablate_active: 12532/16000
ablate_active: 12534/16000
ablate_active: 12536/16000
ablate_active: 12538/16000
ablate_active: 12540/16000
ablate_active: 12542/16000
ablate_active: 12544/16000
ablate_active: 12546/16000
ablate_active: 12548/16000
ablate_active: 12550/16000
ablate_active: 12552/16000
ablate_active: 12554/16000
ablate_active: 12556/16000
ablate_active: 12558/16000
ablate_active: 12560/16000
ablate_active: 12562/16000
ablate_active: 12564/16000
ablate_active: 12566/16000
ablate_active: 12568/16000
ablate_active: 12570/16000
ablate_active: 12572/16000
ablate_active: 12574/16000
ablate_active: 12576/16000
ablate_active: 12578/16000
ablate_active: 12580/16000
ablate_active: 12582/16000
ablate_active: 12584/16000
ablate_active: 12586/16000
ablate_active: 12588/16000
ablate_active: 12590/16000
ablate_active: 12592/16000
ablate_active: 12594/16000
ablate_active: 12596/16000
ablate_active: 12598/16000
ablate_active: 12600/16000
ablate_active: 12602/16000
ablate_active: 12604/16000
ablate_active: 12606/16000
ablate_active: 12608/16000
ablate_active: 12610/16000

ablate_active: 12612/16000
ablate_active: 12614/16000
ablate_active: 12616/16000
ablate_active: 12618/16000
ablate_active: 12620/16000
ablate_active: 12622/16000
ablate_active: 12624/16000
ablate_active: 12626/16000
ablate_active: 12628/16000
ablate_active: 12630/16000
ablate_active: 12632/16000
ablate_active: 12634/16000
ablate_active: 12636/16000
ablate_active: 12638/16000
ablate_active: 12640/16000
ablate_active: 12642/16000
ablate_active: 12644/16000
ablate_active: 12646/16000
ablate_active: 12648/16000
ablate_active: 12650/16000
ablate_active: 12652/16000
ablate_active: 12654/16000
ablate_active: 12656/16000
ablate_active: 12658/16000
ablate_active: 12660/16000
ablate_active: 12662/16000
ablate_active: 12664/16000
ablate_active: 12666/16000
ablate_active: 12668/16000
ablate_active: 12670/16000
ablate_active: 12672/16000
ablate_active: 12674/16000
ablate_active: 12676/16000
ablate_active: 12678/16000
ablate_active: 12680/16000
ablate_active: 12682/16000
ablate_active: 12684/16000
ablate_active: 12686/16000
ablate_active: 12688/16000
ablate_active: 12690/16000
ablate_active: 12692/16000
ablate_active: 12694/16000
ablate_active: 12696/16000
ablate_active: 12698/16000
ablate_active: 12700/16000
ablate_active: 12702/16000
ablate_active: 12704/16000
ablate_active: 12706/16000
ablate_active: 12708/16000
ablate_active: 12710/16000
ablate_active: 12712/16000
ablate_active: 12714/16000
ablate_active: 12716/16000
ablate_active: 12718/16000
ablate_active: 12720/16000
ablate_active: 12722/16000
ablate_active: 12724/16000
ablate_active: 12726/16000
ablate_active: 12728/16000
ablate_active: 12730/16000
ablate_active: 12732/16000
ablate_active: 12734/16000
ablate_active: 12736/16000
ablate_active: 12738/16000
ablate_active: 12740/16000
ablate_active: 12742/16000
ablate_active: 12744/16000
ablate_active: 12746/16000
ablate_active: 12748/16000
ablate_active: 12750/16000
ablate_active: 12752/16000
ablate_active: 12754/16000
ablate_active: 12756/16000
ablate_active: 12758/16000
ablate_active: 12760/16000
ablate_active: 12762/16000
ablate_active: 12764/16000
ablate_active: 12766/16000
ablate_active: 12768/16000
ablate_active: 12770/16000
ablate_active: 12772/16000
ablate_active: 12774/16000
ablate_active: 12776/16000
ablate_active: 12778/16000
ablate_active: 12780/16000
ablate_active: 12782/16000
ablate_active: 12784/16000
ablate_active: 12786/16000
ablate_active: 12788/16000
ablate_active: 12790/16000
ablate_active: 12792/16000
ablate_active: 12794/16000
ablate_active: 12796/16000
ablate_active: 12798/16000
ablate_active: 12800/16000
ablate_active: 12802/16000
ablate_active: 12804/16000
ablate_active: 12806/16000
ablate_active: 12808/16000
ablate_active: 12810/16000
ablate_active: 12812/16000
ablate_active: 12814/16000
ablate_active: 12816/16000
ablate_active: 12818/16000
ablate_active: 12820/16000
ablate_active: 12822/16000
ablate_active: 12824/16000
ablate_active: 12826/16000
ablate_active: 12828/16000
ablate_active: 12830/16000
ablate_active: 12832/16000
ablate_active: 12834/16000
ablate_active: 12836/16000
ablate_active: 12838/16000
ablate_active: 12840/16000
ablate_active: 12842/16000
ablate_active: 12844/16000
ablate_active: 12846/16000
ablate_active: 12848/16000
ablate_active: 12850/16000
ablate_active: 12852/16000
ablate_active: 12854/16000
ablate_active: 12856/16000
ablate_active: 12858/16000
ablate_active: 12860/16000
ablate_active: 12862/16000
ablate_active: 12864/16000
ablate_active: 12866/16000
ablate_active: 12868/16000
ablate_active: 12870/16000
ablate_active: 12872/16000
ablate_active: 12874/16000
ablate_active: 12876/16000
ablate_active: 12878/16000
ablate_active: 12880/16000
ablate_active: 12882/16000
ablate_active: 12884/16000
ablate_active: 12886/16000
ablate_active: 12888/16000
ablate_active: 12890/16000
ablate_active: 12892/16000
ablate_active: 12894/16000
ablate_active: 12896/16000
ablate_active: 12898/16000
ablate_active: 12900/16000
ablate_active: 12902/16000
ablate_active: 12904/16000
ablate_active: 12906/16000
ablate_active: 12908/16000
ablate_active: 12910/16000
ablate_active: 12912/16000
ablate_active: 12914/16000
ablate_active: 12916/16000
ablate_active: 12918/16000
ablate_active: 12920/16000
ablate_active: 12922/16000
ablate_active: 12924/16000
ablate_active: 12926/16000
ablate_active: 12928/16000
ablate_active: 12930/16000
ablate_active: 12932/16000
ablate_active: 12934/16000
ablate_active: 12936/16000
ablate_active: 12938/16000
ablate_active: 12940/16000
ablate_active: 12942/16000
ablate_active: 12944/16000
ablate_active: 12946/16000
ablate_active: 12948/16000
ablate_active: 12950/16000
ablate_active: 12952/16000
ablate_active: 12954/16000
ablate_active: 12956/16000
ablate_active: 12958/16000
ablate_active: 12960/16000
ablate_active: 12962/16000
ablate_active: 12964/16000
ablate_active: 12966/16000
ablate_active: 12968/16000
ablate_active: 12970/16000
ablate_active: 12972/16000
ablate_active: 12974/16000
ablate_active: 12976/16000
ablate_active: 12978/16000
ablate_active: 12980/16000
ablate_active: 12982/16000
ablate_active: 12984/16000
ablate_active: 12986/16000
ablate_active: 12988/16000
ablate_active: 12990/16000
ablate_active: 12992/16000
ablate_active: 12994/16000
ablate_active: 12996/16000
ablate_active: 12998/16000
ablate_active: 13000/16000
ablate_active: 13002/16000
ablate_active: 13004/16000
ablate_active: 13006/16000
ablate_active: 13008/16000
ablate_active: 13010/16000
ablate_active: 13012/16000
ablate_active: 13014/16000
ablate_active: 13016/16000
ablate_active: 13018/16000
ablate_active: 13020/16000
ablate_active: 13022/16000
ablate_active: 13024/16000
ablate_active: 13026/16000
ablate_active: 13028/16000
ablate_active: 13030/16000
ablate_active: 13032/16000
ablate_active: 13034/16000
ablate_active: 13036/16000
ablate_active: 13038/16000
ablate_active: 13040/16000
ablate_active: 13042/16000
ablate_active: 13044/16000
ablate_active: 13046/16000
ablate_active: 13048/16000
ablate_active: 13050/16000
ablate_active: 13052/16000
ablate_active: 13054/16000
ablate_active: 13056/16000
ablate_active: 13058/16000
ablate_active: 13060/16000
ablate_active: 13062/16000
ablate_active: 13064/16000
ablate_active: 13066/16000
ablate_active: 13068/16000
ablate_active: 13070/16000
ablate_active: 13072/16000
ablate_active: 13074/16000
ablate_active: 13076/16000
ablate_active: 13078/16000
ablate_active: 13080/16000
ablate_active: 13082/16000
ablate_active: 13084/16000
ablate_active: 13086/16000
ablate_active: 13088/16000
ablate_active: 13090/16000
ablate_active: 13092/16000
ablate_active: 13094/16000
ablate_active: 13096/16000
ablate_active: 13098/16000
ablate_active: 13100/16000
ablate_active: 13102/16000
ablate_active: 13104/16000
ablate_active: 13106/16000
ablate_active: 13108/16000
ablate_active: 13110/16000
ablate_active: 13112/16000
ablate_active: 13114/16000
ablate_active: 13116/16000
ablate_active: 13118/16000
ablate_active: 13120/16000
ablate_active: 13122/16000
ablate_active: 13124/16000
ablate_active: 13126/16000
ablate_active: 13128/16000
ablate_active: 13130/16000
ablate_active: 13132/16000
ablate_active: 13134/16000
ablate_active: 13136/16000
ablate_active: 13138/16000
ablate_active: 13140/16000
ablate_active: 13142/16000
ablate_active: 13144/16000
ablate_active: 13146/16000
ablate_active: 13148/16000
ablate_active: 13150/16000
ablate_active: 13152/16000
ablate_active: 13154/16000
ablate_active: 13156/16000
ablate_active: 13158/16000
ablate_active: 13160/16000
ablate_active: 13162/16000
ablate_active: 13164/16000
ablate_active: 13166/16000
ablate_active: 13168/16000
ablate_active: 13170/16000
ablate_active: 13172/16000
ablate_active: 13174/16000
ablate_active: 13176/16000
ablate_active: 13178/16000
ablate_active: 13180/16000
ablate_active: 13182/16000
ablate_active: 13184/16000
ablate_active: 13186/16000
ablate_active: 13188/16000
ablate_active: 13190/16000
ablate_active: 13192/16000
ablate_active: 13194/16000
ablate_active: 13196/16000
ablate_active: 13198/16000
ablate_active: 13200/16000
ablate_active: 13202/16000
ablate_active: 13204/16000
ablate_active: 13206/16000
ablate_active: 13208/16000
ablate_active: 13210/16000
ablate_active: 13212/16000
ablate_active: 13214/16000
ablate_active: 13216/16000
ablate_active: 13218/16000
ablate_active: 13220/16000
ablate_active: 13222/16000

ablate_active: 13224/16000
ablate_active: 13226/16000
ablate_active: 13228/16000
ablate_active: 13230/16000
ablate_active: 13232/16000
ablate_active: 13234/16000
ablate_active: 13236/16000
ablate_active: 13238/16000
ablate_active: 13240/16000
ablate_active: 13242/16000
ablate_active: 13244/16000
ablate_active: 13246/16000
ablate_active: 13248/16000
ablate_active: 13250/16000
ablate_active: 13252/16000
ablate_active: 13254/16000
ablate_active: 13256/16000
ablate_active: 13258/16000
ablate_active: 13260/16000
ablate_active: 13262/16000
ablate_active: 13264/16000
ablate_active: 13266/16000
ablate_active: 13268/16000
ablate_active: 13270/16000
ablate_active: 13272/16000
ablate_active: 13274/16000
ablate_active: 13276/16000
ablate_active: 13278/16000
ablate_active: 13280/16000
ablate_active: 13282/16000
ablate_active: 13284/16000
ablate_active: 13286/16000
ablate_active: 13288/16000
ablate_active: 13290/16000
ablate_active: 13292/16000
ablate_active: 13294/16000
ablate_active: 13296/16000
ablate_active: 13298/16000
ablate_active: 13300/16000
ablate_active: 13302/16000
ablate_active: 13304/16000
ablate_active: 13306/16000
ablate_active: 13308/16000
ablate_active: 13310/16000
ablate_active: 13312/16000
ablate_active: 13314/16000
ablate_active: 13316/16000
ablate_active: 13318/16000
ablate_active: 13320/16000
ablate_active: 13322/16000
ablate_active: 13324/16000
ablate_active: 13326/16000
ablate_active: 13328/16000
ablate_active: 13330/16000
ablate_active: 13332/16000
ablate_active: 13334/16000
ablate_active: 13336/16000
ablate_active: 13338/16000
ablate_active: 13340/16000
ablate_active: 13342/16000
ablate_active: 13344/16000
ablate_active: 13346/16000
ablate_active: 13348/16000
ablate_active: 13350/16000
ablate_active: 13352/16000
ablate_active: 13354/16000
ablate_active: 13356/16000
ablate_active: 13358/16000
ablate_active: 13360/16000
ablate_active: 13362/16000
ablate_active: 13364/16000
ablate_active: 13366/16000
ablate_active: 13368/16000
ablate_active: 13370/16000
ablate_active: 13372/16000
ablate_active: 13374/16000
ablate_active: 13376/16000
ablate_active: 13378/16000
ablate_active: 13380/16000
ablate_active: 13382/16000
ablate_active: 13384/16000
ablate_active: 13386/16000
ablate_active: 13388/16000
ablate_active: 13390/16000
ablate_active: 13392/16000
ablate_active: 13394/16000
ablate_active: 13396/16000
ablate_active: 13398/16000
ablate_active: 13400/16000
ablate_active: 13402/16000
ablate_active: 13404/16000
ablate_active: 13406/16000
ablate_active: 13408/16000
ablate_active: 13410/16000
ablate_active: 13412/16000
ablate_active: 13414/16000
ablate_active: 13416/16000
ablate_active: 13418/16000
ablate_active: 13420/16000
ablate_active: 13422/16000
ablate_active: 13424/16000
ablate_active: 13426/16000
ablate_active: 13428/16000
ablate_active: 13430/16000
ablate_active: 13432/16000
ablate_active: 13434/16000
ablate_active: 13436/16000
ablate_active: 13438/16000
ablate_active: 13440/16000
ablate_active: 13442/16000
ablate_active: 13444/16000
ablate_active: 13446/16000
ablate_active: 13448/16000
ablate_active: 13450/16000
ablate_active: 13452/16000
ablate_active: 13454/16000
ablate_active: 13456/16000
ablate_active: 13458/16000
ablate_active: 13460/16000
ablate_active: 13462/16000
ablate_active: 13464/16000
ablate_active: 13466/16000
ablate_active: 13468/16000
ablate_active: 13470/16000
ablate_active: 13472/16000
ablate_active: 13474/16000
ablate_active: 13476/16000
ablate_active: 13478/16000
ablate_active: 13480/16000
ablate_active: 13482/16000
ablate_active: 13484/16000
ablate_active: 13486/16000
ablate_active: 13488/16000
ablate_active: 13490/16000
ablate_active: 13492/16000
ablate_active: 13494/16000
ablate_active: 13496/16000
ablate_active: 13498/16000
ablate_active: 13500/16000
ablate_active: 13502/16000
ablate_active: 13504/16000
ablate_active: 13506/16000
ablate_active: 13508/16000
ablate_active: 13510/16000
ablate_active: 13512/16000
ablate_active: 13514/16000
ablate_active: 13516/16000
ablate_active: 13518/16000
ablate_active: 13520/16000
ablate_active: 13522/16000
ablate_active: 13524/16000
ablate_active: 13526/16000
ablate_active: 13528/16000
ablate_active: 13530/16000
ablate_active: 13532/16000
ablate_active: 13534/16000
ablate_active: 13536/16000
ablate_active: 13538/16000
ablate_active: 13540/16000
ablate_active: 13542/16000
ablate_active: 13544/16000
ablate_active: 13546/16000
ablate_active: 13548/16000
ablate_active: 13550/16000
ablate_active: 13552/16000
ablate_active: 13554/16000
ablate_active: 13556/16000
ablate_active: 13558/16000
ablate_active: 13560/16000
ablate_active: 13562/16000
ablate_active: 13564/16000
ablate_active: 13566/16000
ablate_active: 13568/16000
ablate_active: 13570/16000
ablate_active: 13572/16000
ablate_active: 13574/16000
ablate_active: 13576/16000
ablate_active: 13578/16000
ablate_active: 13580/16000
ablate_active: 13582/16000
ablate_active: 13584/16000
ablate_active: 13586/16000
ablate_active: 13588/16000
ablate_active: 13590/16000
ablate_active: 13592/16000
ablate_active: 13594/16000
ablate_active: 13596/16000
ablate_active: 13598/16000
ablate_active: 13600/16000
ablate_active: 13602/16000
ablate_active: 13604/16000
ablate_active: 13606/16000
ablate_active: 13608/16000
ablate_active: 13610/16000
ablate_active: 13612/16000
ablate_active: 13614/16000
ablate_active: 13616/16000
ablate_active: 13618/16000
ablate_active: 13620/16000
ablate_active: 13622/16000
ablate_active: 13624/16000
ablate_active: 13626/16000
ablate_active: 13628/16000
ablate_active: 13630/16000
ablate_active: 13632/16000
ablate_active: 13634/16000
ablate_active: 13636/16000
ablate_active: 13638/16000
ablate_active: 13640/16000
ablate_active: 13642/16000
ablate_active: 13644/16000
ablate_active: 13646/16000
ablate_active: 13648/16000
ablate_active: 13650/16000
ablate_active: 13652/16000
ablate_active: 13654/16000
ablate_active: 13656/16000
ablate_active: 13658/16000
ablate_active: 13660/16000
ablate_active: 13662/16000
ablate_active: 13664/16000
ablate_active: 13666/16000
ablate_active: 13668/16000
ablate_active: 13670/16000
ablate_active: 13672/16000
ablate_active: 13674/16000
ablate_active: 13676/16000
ablate_active: 13678/16000
ablate_active: 13680/16000
ablate_active: 13682/16000
ablate_active: 13684/16000
ablate_active: 13686/16000
ablate_active: 13688/16000
ablate_active: 13690/16000
ablate_active: 13692/16000
ablate_active: 13694/16000
ablate_active: 13696/16000
ablate_active: 13698/16000
ablate_active: 13700/16000
ablate_active: 13702/16000
ablate_active: 13704/16000
ablate_active: 13706/16000
ablate_active: 13708/16000
ablate_active: 13710/16000
ablate_active: 13712/16000
ablate_active: 13714/16000
ablate_active: 13716/16000
ablate_active: 13718/16000
ablate_active: 13720/16000
ablate_active: 13722/16000
ablate_active: 13724/16000
ablate_active: 13726/16000
ablate_active: 13728/16000
ablate_active: 13730/16000
ablate_active: 13732/16000
ablate_active: 13734/16000
ablate_active: 13736/16000
ablate_active: 13738/16000
ablate_active: 13740/16000
ablate_active: 13742/16000
ablate_active: 13744/16000
ablate_active: 13746/16000
ablate_active: 13748/16000
ablate_active: 13750/16000
ablate_active: 13752/16000
ablate_active: 13754/16000
ablate_active: 13756/16000
ablate_active: 13758/16000
ablate_active: 13760/16000
ablate_active: 13762/16000
ablate_active: 13764/16000
ablate_active: 13766/16000
ablate_active: 13768/16000
ablate_active: 13770/16000
ablate_active: 13772/16000
ablate_active: 13774/16000
ablate_active: 13776/16000
ablate_active: 13778/16000
ablate_active: 13780/16000
ablate_active: 13782/16000
ablate_active: 13784/16000
ablate_active: 13786/16000
ablate_active: 13788/16000
ablate_active: 13790/16000
ablate_active: 13792/16000
ablate_active: 13794/16000
ablate_active: 13796/16000
ablate_active: 13798/16000
ablate_active: 13800/16000
ablate_active: 13802/16000
ablate_active: 13804/16000
ablate_active: 13806/16000
ablate_active: 13808/16000
ablate_active: 13810/16000
ablate_active: 13812/16000
ablate_active: 13814/16000
ablate_active: 13816/16000
ablate_active: 13818/16000
ablate_active: 13820/16000
ablate_active: 13822/16000
ablate_active: 13824/16000
ablate_active: 13826/16000
ablate_active: 13828/16000
ablate_active: 13830/16000
ablate_active: 13832/16000
ablate_active: 13834/16000

ablate_active: 13836/16000
ablate_active: 13838/16000
ablate_active: 13840/16000
ablate_active: 13842/16000
ablate_active: 13844/16000
ablate_active: 13846/16000
ablate_active: 13848/16000
ablate_active: 13850/16000
ablate_active: 13852/16000
ablate_active: 13854/16000
ablate_active: 13856/16000
ablate_active: 13858/16000
ablate_active: 13860/16000
ablate_active: 13862/16000
ablate_active: 13864/16000
ablate_active: 13866/16000
ablate_active: 13868/16000
ablate_active: 13870/16000
ablate_active: 13872/16000
ablate_active: 13874/16000
ablate_active: 13876/16000
ablate_active: 13878/16000
ablate_active: 13880/16000
ablate_active: 13882/16000
ablate_active: 13884/16000
ablate_active: 13886/16000
ablate_active: 13888/16000
ablate_active: 13890/16000
ablate_active: 13892/16000
ablate_active: 13894/16000
ablate_active: 13896/16000
ablate_active: 13898/16000
ablate_active: 13900/16000
ablate_active: 13902/16000
ablate_active: 13904/16000
ablate_active: 13906/16000
ablate_active: 13908/16000
ablate_active: 13910/16000
ablate_active: 13912/16000
ablate_active: 13914/16000
ablate_active: 13916/16000
ablate_active: 13918/16000
ablate_active: 13920/16000
ablate_active: 13922/16000
ablate_active: 13924/16000
ablate_active: 13926/16000
ablate_active: 13928/16000
ablate_active: 13930/16000
ablate_active: 13932/16000
ablate_active: 13934/16000
ablate_active: 13936/16000
ablate_active: 13938/16000
ablate_active: 13940/16000
ablate_active: 13942/16000
ablate_active: 13944/16000
ablate_active: 13946/16000
ablate_active: 13948/16000
ablate_active: 13950/16000
ablate_active: 13952/16000
ablate_active: 13954/16000
ablate_active: 13956/16000
ablate_active: 13958/16000
ablate_active: 13960/16000
ablate_active: 13962/16000
ablate_active: 13964/16000
ablate_active: 13966/16000
ablate_active: 13968/16000
ablate_active: 13970/16000
ablate_active: 13972/16000
ablate_active: 13974/16000
ablate_active: 13976/16000
ablate_active: 13978/16000
ablate_active: 13980/16000
ablate_active: 13982/16000
ablate_active: 13984/16000
ablate_active: 13986/16000
ablate_active: 13988/16000
ablate_active: 13990/16000
ablate_active: 13992/16000
ablate_active: 13994/16000
ablate_active: 13996/16000
ablate_active: 13998/16000
ablate_active: 14000/16000
ablate_active: 14002/16000
ablate_active: 14004/16000
ablate_active: 14006/16000
ablate_active: 14008/16000
ablate_active: 14010/16000
ablate_active: 14012/16000
ablate_active: 14014/16000
ablate_active: 14016/16000
ablate_active: 14018/16000
ablate_active: 14020/16000
ablate_active: 14022/16000
ablate_active: 14024/16000
ablate_active: 14026/16000
ablate_active: 14028/16000
ablate_active: 14030/16000
ablate_active: 14032/16000
ablate_active: 14034/16000
ablate_active: 14036/16000
ablate_active: 14038/16000
ablate_active: 14040/16000
ablate_active: 14042/16000
ablate_active: 14044/16000
ablate_active: 14046/16000
ablate_active: 14048/16000
ablate_active: 14050/16000
ablate_active: 14052/16000
ablate_active: 14054/16000
ablate_active: 14056/16000
ablate_active: 14058/16000
ablate_active: 14060/16000
ablate_active: 14062/16000
ablate_active: 14064/16000
ablate_active: 14066/16000
ablate_active: 14068/16000
ablate_active: 14070/16000
ablate_active: 14072/16000
ablate_active: 14074/16000
ablate_active: 14076/16000
ablate_active: 14078/16000
ablate_active: 14080/16000
ablate_active: 14082/16000
ablate_active: 14084/16000
ablate_active: 14086/16000
ablate_active: 14088/16000
ablate_active: 14090/16000
ablate_active: 14092/16000
ablate_active: 14094/16000
ablate_active: 14096/16000
ablate_active: 14098/16000
ablate_active: 14100/16000
ablate_active: 14102/16000
ablate_active: 14104/16000
ablate_active: 14106/16000
ablate_active: 14108/16000
ablate_active: 14110/16000
ablate_active: 14112/16000
ablate_active: 14114/16000
ablate_active: 14116/16000
ablate_active: 14118/16000
ablate_active: 14120/16000
ablate_active: 14122/16000
ablate_active: 14124/16000
ablate_active: 14126/16000
ablate_active: 14128/16000
ablate_active: 14130/16000
ablate_active: 14132/16000
ablate_active: 14134/16000
ablate_active: 14136/16000
ablate_active: 14138/16000
ablate_active: 14140/16000
ablate_active: 14142/16000
ablate_active: 14144/16000
ablate_active: 14146/16000
ablate_active: 14148/16000
ablate_active: 14150/16000
ablate_active: 14152/16000
ablate_active: 14154/16000
ablate_active: 14156/16000
ablate_active: 14158/16000
ablate_active: 14160/16000
ablate_active: 14162/16000
ablate_active: 14164/16000
ablate_active: 14166/16000
ablate_active: 14168/16000
ablate_active: 14170/16000
ablate_active: 14172/16000
ablate_active: 14174/16000
ablate_active: 14176/16000
ablate_active: 14178/16000
ablate_active: 14180/16000
ablate_active: 14182/16000
ablate_active: 14184/16000
ablate_active: 14186/16000
ablate_active: 14188/16000
ablate_active: 14190/16000
ablate_active: 14192/16000
ablate_active: 14194/16000
ablate_active: 14196/16000
ablate_active: 14198/16000
ablate_active: 14200/16000
ablate_active: 14202/16000
ablate_active: 14204/16000
ablate_active: 14206/16000
ablate_active: 14208/16000
ablate_active: 14210/16000
ablate_active: 14212/16000
ablate_active: 14214/16000
ablate_active: 14216/16000
ablate_active: 14218/16000
ablate_active: 14220/16000
ablate_active: 14222/16000
ablate_active: 14224/16000
ablate_active: 14226/16000
ablate_active: 14228/16000
ablate_active: 14230/16000
ablate_active: 14232/16000
ablate_active: 14234/16000
ablate_active: 14236/16000
ablate_active: 14238/16000
ablate_active: 14240/16000
ablate_active: 14242/16000
ablate_active: 14244/16000
ablate_active: 14246/16000
ablate_active: 14248/16000
ablate_active: 14250/16000
ablate_active: 14252/16000
ablate_active: 14254/16000
ablate_active: 14256/16000
ablate_active: 14258/16000
ablate_active: 14260/16000
ablate_active: 14262/16000
ablate_active: 14264/16000
ablate_active: 14266/16000
ablate_active: 14268/16000
ablate_active: 14270/16000
ablate_active: 14272/16000
ablate_active: 14274/16000
ablate_active: 14276/16000
ablate_active: 14278/16000
ablate_active: 14280/16000
ablate_active: 14282/16000
ablate_active: 14284/16000
ablate_active: 14286/16000
ablate_active: 14288/16000
ablate_active: 14290/16000
ablate_active: 14292/16000
ablate_active: 14294/16000
ablate_active: 14296/16000
ablate_active: 14298/16000
ablate_active: 14300/16000
ablate_active: 14302/16000
ablate_active: 14304/16000
ablate_active: 14306/16000
ablate_active: 14308/16000
ablate_active: 14310/16000
ablate_active: 14312/16000
ablate_active: 14314/16000
ablate_active: 14316/16000
ablate_active: 14318/16000
ablate_active: 14320/16000
ablate_active: 14322/16000
ablate_active: 14324/16000
ablate_active: 14326/16000
ablate_active: 14328/16000
ablate_active: 14330/16000
ablate_active: 14332/16000
ablate_active: 14334/16000
ablate_active: 14336/16000
ablate_active: 14338/16000
ablate_active: 14340/16000
ablate_active: 14342/16000
ablate_active: 14344/16000
ablate_active: 14346/16000
ablate_active: 14348/16000
ablate_active: 14350/16000
ablate_active: 14352/16000
ablate_active: 14354/16000
ablate_active: 14356/16000
ablate_active: 14358/16000
ablate_active: 14360/16000
ablate_active: 14362/16000
ablate_active: 14364/16000
ablate_active: 14366/16000
ablate_active: 14368/16000
ablate_active: 14370/16000
ablate_active: 14372/16000
ablate_active: 14374/16000
ablate_active: 14376/16000
ablate_active: 14378/16000
ablate_active: 14380/16000
ablate_active: 14382/16000
ablate_active: 14384/16000
ablate_active: 14386/16000
ablate_active: 14388/16000
ablate_active: 14390/16000
ablate_active: 14392/16000
ablate_active: 14394/16000
ablate_active: 14396/16000
ablate_active: 14398/16000
ablate_active: 14400/16000
ablate_active: 14402/16000
ablate_active: 14404/16000
ablate_active: 14406/16000
ablate_active: 14408/16000
ablate_active: 14410/16000
ablate_active: 14412/16000
ablate_active: 14414/16000
ablate_active: 14416/16000
ablate_active: 14418/16000
ablate_active: 14420/16000
ablate_active: 14422/16000
ablate_active: 14424/16000
ablate_active: 14426/16000
ablate_active: 14428/16000
ablate_active: 14430/16000
ablate_active: 14432/16000
ablate_active: 14434/16000
ablate_active: 14436/16000
ablate_active: 14438/16000
ablate_active: 14440/16000
ablate_active: 14442/16000

ablate_active: 14444/16000
ablate_active: 14446/16000
ablate_active: 14448/16000
ablate_active: 14450/16000
ablate_active: 14452/16000
ablate_active: 14454/16000
ablate_active: 14456/16000
ablate_active: 14458/16000
ablate_active: 14460/16000
ablate_active: 14462/16000
ablate_active: 14464/16000
ablate_active: 14466/16000
ablate_active: 14468/16000
ablate_active: 14470/16000
ablate_active: 14472/16000
ablate_active: 14474/16000
ablate_active: 14476/16000
ablate_active: 14478/16000
ablate_active: 14480/16000
ablate_active: 14482/16000
ablate_active: 14484/16000
ablate_active: 14486/16000
ablate_active: 14488/16000
ablate_active: 14490/16000
ablate_active: 14492/16000
ablate_active: 14494/16000
ablate_active: 14496/16000
ablate_active: 14498/16000
ablate_active: 14500/16000
ablate_active: 14502/16000
ablate_active: 14504/16000
ablate_active: 14506/16000
ablate_active: 14508/16000
ablate_active: 14510/16000
ablate_active: 14512/16000
ablate_active: 14514/16000
ablate_active: 14516/16000
ablate_active: 14518/16000
ablate_active: 14520/16000
ablate_active: 14522/16000
ablate_active: 14524/16000
ablate_active: 14526/16000
ablate_active: 14528/16000
ablate_active: 14530/16000
ablate_active: 14532/16000
ablate_active: 14534/16000
ablate_active: 14536/16000
ablate_active: 14538/16000
ablate_active: 14540/16000
ablate_active: 14542/16000
ablate_active: 14544/16000
ablate_active: 14546/16000
ablate_active: 14548/16000
ablate_active: 14550/16000
ablate_active: 14552/16000
ablate_active: 14554/16000
ablate_active: 14556/16000
ablate_active: 14558/16000
ablate_active: 14560/16000
ablate_active: 14562/16000
ablate_active: 14564/16000
ablate_active: 14566/16000
ablate_active: 14568/16000
ablate_active: 14570/16000
ablate_active: 14572/16000
ablate_active: 14574/16000
ablate_active: 14576/16000
ablate_active: 14578/16000
ablate_active: 14580/16000
ablate_active: 14582/16000
ablate_active: 14584/16000
ablate_active: 14586/16000
ablate_active: 14588/16000
ablate_active: 14590/16000
ablate_active: 14592/16000
ablate_active: 14594/16000
ablate_active: 14596/16000
ablate_active: 14598/16000
ablate_active: 14600/16000
ablate_active: 14602/16000
ablate_active: 14604/16000
ablate_active: 14606/16000
ablate_active: 14608/16000
ablate_active: 14610/16000
ablate_active: 14612/16000
ablate_active: 14614/16000
ablate_active: 14616/16000
ablate_active: 14618/16000
ablate_active: 14620/16000
ablate_active: 14622/16000
ablate_active: 14624/16000
ablate_active: 14626/16000
ablate_active: 14628/16000
ablate_active: 14630/16000
ablate_active: 14632/16000
ablate_active: 14634/16000
ablate_active: 14636/16000
ablate_active: 14638/16000
ablate_active: 14640/16000
ablate_active: 14642/16000
ablate_active: 14644/16000
ablate_active: 14646/16000
ablate_active: 14648/16000
ablate_active: 14650/16000
ablate_active: 14652/16000
ablate_active: 14654/16000
ablate_active: 14656/16000
ablate_active: 14658/16000
ablate_active: 14660/16000
ablate_active: 14662/16000
ablate_active: 14664/16000
ablate_active: 14666/16000
ablate_active: 14668/16000
ablate_active: 14670/16000
ablate_active: 14672/16000
ablate_active: 14674/16000
ablate_active: 14676/16000
ablate_active: 14678/16000
ablate_active: 14680/16000
ablate_active: 14682/16000
ablate_active: 14684/16000
ablate_active: 14686/16000
ablate_active: 14688/16000
ablate_active: 14690/16000
ablate_active: 14692/16000
ablate_active: 14694/16000
ablate_active: 14696/16000
ablate_active: 14698/16000
ablate_active: 14700/16000
ablate_active: 14702/16000
ablate_active: 14704/16000
ablate_active: 14706/16000
ablate_active: 14708/16000
ablate_active: 14710/16000
ablate_active: 14712/16000
ablate_active: 14714/16000
ablate_active: 14716/16000
ablate_active: 14718/16000
ablate_active: 14720/16000
ablate_active: 14722/16000
ablate_active: 14724/16000
ablate_active: 14726/16000
ablate_active: 14728/16000
ablate_active: 14730/16000
ablate_active: 14732/16000
ablate_active: 14734/16000
ablate_active: 14736/16000
ablate_active: 14738/16000
ablate_active: 14740/16000
ablate_active: 14742/16000
ablate_active: 14744/16000
ablate_active: 14746/16000
ablate_active: 14748/16000
ablate_active: 14750/16000
ablate_active: 14752/16000
ablate_active: 14754/16000
ablate_active: 14756/16000
ablate_active: 14758/16000
ablate_active: 14760/16000
ablate_active: 14762/16000
ablate_active: 14764/16000
ablate_active: 14766/16000
ablate_active: 14768/16000
ablate_active: 14770/16000
ablate_active: 14772/16000
ablate_active: 14774/16000
ablate_active: 14776/16000
ablate_active: 14778/16000
ablate_active: 14780/16000
ablate_active: 14782/16000
ablate_active: 14784/16000
ablate_active: 14786/16000
ablate_active: 14788/16000
ablate_active: 14790/16000
ablate_active: 14792/16000
ablate_active: 14794/16000
ablate_active: 14796/16000
ablate_active: 14798/16000
ablate_active: 14800/16000
ablate_active: 14802/16000
ablate_active: 14804/16000
ablate_active: 14806/16000
ablate_active: 14808/16000
ablate_active: 14810/16000
ablate_active: 14812/16000
ablate_active: 14814/16000
ablate_active: 14816/16000
ablate_active: 14818/16000
ablate_active: 14820/16000
ablate_active: 14822/16000
ablate_active: 14824/16000
ablate_active: 14826/16000
ablate_active: 14828/16000
ablate_active: 14830/16000
ablate_active: 14832/16000
ablate_active: 14834/16000
ablate_active: 14836/16000
ablate_active: 14838/16000
ablate_active: 14840/16000
ablate_active: 14842/16000
ablate_active: 14844/16000
ablate_active: 14846/16000
ablate_active: 14848/16000
ablate_active: 14850/16000
ablate_active: 14852/16000
ablate_active: 14854/16000
ablate_active: 14856/16000
ablate_active: 14858/16000
ablate_active: 14860/16000
ablate_active: 14862/16000
ablate_active: 14864/16000
ablate_active: 14866/16000
ablate_active: 14868/16000
ablate_active: 14870/16000
ablate_active: 14872/16000
ablate_active: 14874/16000
ablate_active: 14876/16000
ablate_active: 14878/16000
ablate_active: 14880/16000
ablate_active: 14882/16000
ablate_active: 14884/16000
ablate_active: 14886/16000
ablate_active: 14888/16000
ablate_active: 14890/16000
ablate_active: 14892/16000
ablate_active: 14894/16000
ablate_active: 14896/16000
ablate_active: 14898/16000
ablate_active: 14900/16000
ablate_active: 14902/16000
ablate_active: 14904/16000
ablate_active: 14906/16000
ablate_active: 14908/16000
ablate_active: 14910/16000
ablate_active: 14912/16000
ablate_active: 14914/16000
ablate_active: 14916/16000
ablate_active: 14918/16000
ablate_active: 14920/16000
ablate_active: 14922/16000
ablate_active: 14924/16000
ablate_active: 14926/16000
ablate_active: 14928/16000
ablate_active: 14930/16000
ablate_active: 14932/16000
ablate_active: 14934/16000
ablate_active: 14936/16000
ablate_active: 14938/16000
ablate_active: 14940/16000
ablate_active: 14942/16000
ablate_active: 14944/16000
ablate_active: 14946/16000
ablate_active: 14948/16000
ablate_active: 14950/16000
ablate_active: 14952/16000
ablate_active: 14954/16000
ablate_active: 14956/16000
ablate_active: 14958/16000
ablate_active: 14960/16000
ablate_active: 14962/16000
ablate_active: 14964/16000
ablate_active: 14966/16000
ablate_active: 14968/16000
ablate_active: 14970/16000
ablate_active: 14972/16000
ablate_active: 14974/16000
ablate_active: 14976/16000
ablate_active: 14978/16000
ablate_active: 14980/16000
ablate_active: 14982/16000
ablate_active: 14984/16000
ablate_active: 14986/16000
ablate_active: 14988/16000
ablate_active: 14990/16000
ablate_active: 14992/16000
ablate_active: 14994/16000
ablate_active: 14996/16000
ablate_active: 14998/16000
ablate_active: 15000/16000
ablate_active: 15002/16000
ablate_active: 15004/16000
ablate_active: 15006/16000
ablate_active: 15008/16000
ablate_active: 15010/16000
ablate_active: 15012/16000
ablate_active: 15014/16000
ablate_active: 15016/16000
ablate_active: 15018/16000
ablate_active: 15020/16000
ablate_active: 15022/16000
ablate_active: 15024/16000
ablate_active: 15026/16000
ablate_active: 15028/16000
ablate_active: 15030/16000
ablate_active: 15032/16000
ablate_active: 15034/16000
ablate_active: 15036/16000
ablate_active: 15038/16000
ablate_active: 15040/16000
ablate_active: 15042/16000
ablate_active: 15044/16000
ablate_active: 15046/16000
ablate_active: 15048/16000
ablate_active: 15050/16000
ablate_active: 15052/16000

ablate_active: 15054/16000
ablate_active: 15056/16000
ablate_active: 15058/16000
ablate_active: 15060/16000
ablate_active: 15062/16000
ablate_active: 15064/16000
ablate_active: 15066/16000
ablate_active: 15068/16000
ablate_active: 15070/16000
ablate_active: 15072/16000
ablate_active: 15074/16000
ablate_active: 15076/16000
ablate_active: 15078/16000
ablate_active: 15080/16000
ablate_active: 15082/16000
ablate_active: 15084/16000
ablate_active: 15086/16000
ablate_active: 15088/16000
ablate_active: 15090/16000
ablate_active: 15092/16000
ablate_active: 15094/16000
ablate_active: 15096/16000
ablate_active: 15098/16000
ablate_active: 15100/16000
ablate_active: 15102/16000
ablate_active: 15104/16000
ablate_active: 15106/16000
ablate_active: 15108/16000
ablate_active: 15110/16000
ablate_active: 15112/16000
ablate_active: 15114/16000
ablate_active: 15116/16000
ablate_active: 15118/16000
ablate_active: 15120/16000
ablate_active: 15122/16000
ablate_active: 15124/16000
ablate_active: 15126/16000
ablate_active: 15128/16000
ablate_active: 15130/16000
ablate_active: 15132/16000
ablate_active: 15134/16000
ablate_active: 15136/16000
ablate_active: 15138/16000
ablate_active: 15140/16000
ablate_active: 15142/16000
ablate_active: 15144/16000
ablate_active: 15146/16000
ablate_active: 15148/16000
ablate_active: 15150/16000
ablate_active: 15152/16000
ablate_active: 15154/16000
ablate_active: 15156/16000
ablate_active: 15158/16000
ablate_active: 15160/16000
ablate_active: 15162/16000
ablate_active: 15164/16000
ablate_active: 15166/16000
ablate_active: 15168/16000
ablate_active: 15170/16000
ablate_active: 15172/16000
ablate_active: 15174/16000
ablate_active: 15176/16000
ablate_active: 15178/16000
ablate_active: 15180/16000
ablate_active: 15182/16000
ablate_active: 15184/16000
ablate_active: 15186/16000
ablate_active: 15188/16000
ablate_active: 15190/16000
ablate_active: 15192/16000
ablate_active: 15194/16000
ablate_active: 15196/16000
ablate_active: 15198/16000
ablate_active: 15200/16000
ablate_active: 15202/16000
ablate_active: 15204/16000
ablate_active: 15206/16000
ablate_active: 15208/16000
ablate_active: 15210/16000
ablate_active: 15212/16000
ablate_active: 15214/16000
ablate_active: 15216/16000
ablate_active: 15218/16000
ablate_active: 15220/16000
ablate_active: 15222/16000
ablate_active: 15224/16000
ablate_active: 15226/16000
ablate_active: 15228/16000
ablate_active: 15230/16000
ablate_active: 15232/16000
ablate_active: 15234/16000
ablate_active: 15236/16000
ablate_active: 15238/16000
ablate_active: 15240/16000
ablate_active: 15242/16000
ablate_active: 15244/16000
ablate_active: 15246/16000
ablate_active: 15248/16000
ablate_active: 15250/16000
ablate_active: 15252/16000
ablate_active: 15254/16000
ablate_active: 15256/16000
ablate_active: 15258/16000
ablate_active: 15260/16000
ablate_active: 15262/16000
ablate_active: 15264/16000
ablate_active: 15266/16000
ablate_active: 15268/16000
ablate_active: 15270/16000
ablate_active: 15272/16000
ablate_active: 15274/16000
ablate_active: 15276/16000
ablate_active: 15278/16000
ablate_active: 15280/16000
ablate_active: 15282/16000
ablate_active: 15284/16000
ablate_active: 15286/16000
ablate_active: 15288/16000
ablate_active: 15290/16000
ablate_active: 15292/16000
ablate_active: 15294/16000
ablate_active: 15296/16000
ablate_active: 15298/16000
ablate_active: 15300/16000
ablate_active: 15302/16000
ablate_active: 15304/16000
ablate_active: 15306/16000
ablate_active: 15308/16000
ablate_active: 15310/16000
ablate_active: 15312/16000
ablate_active: 15314/16000
ablate_active: 15316/16000
ablate_active: 15318/16000
ablate_active: 15320/16000
ablate_active: 15322/16000
ablate_active: 15324/16000
ablate_active: 15326/16000
ablate_active: 15328/16000
ablate_active: 15330/16000
ablate_active: 15332/16000
ablate_active: 15334/16000
ablate_active: 15336/16000
ablate_active: 15338/16000
ablate_active: 15340/16000
ablate_active: 15342/16000
ablate_active: 15344/16000
ablate_active: 15346/16000
ablate_active: 15348/16000
ablate_active: 15350/16000
ablate_active: 15352/16000
ablate_active: 15354/16000
ablate_active: 15356/16000
ablate_active: 15358/16000
ablate_active: 15360/16000
ablate_active: 15362/16000
ablate_active: 15364/16000
ablate_active: 15366/16000
ablate_active: 15368/16000
ablate_active: 15370/16000
ablate_active: 15372/16000
ablate_active: 15374/16000
ablate_active: 15376/16000
ablate_active: 15378/16000
ablate_active: 15380/16000
ablate_active: 15382/16000
ablate_active: 15384/16000
ablate_active: 15386/16000
ablate_active: 15388/16000
ablate_active: 15390/16000
ablate_active: 15392/16000
ablate_active: 15394/16000
ablate_active: 15396/16000
ablate_active: 15398/16000
ablate_active: 15400/16000
ablate_active: 15402/16000
ablate_active: 15404/16000
ablate_active: 15406/16000
ablate_active: 15408/16000
ablate_active: 15410/16000
ablate_active: 15412/16000
ablate_active: 15414/16000
ablate_active: 15416/16000
ablate_active: 15418/16000
ablate_active: 15420/16000
ablate_active: 15422/16000
ablate_active: 15424/16000
ablate_active: 15426/16000
ablate_active: 15428/16000
ablate_active: 15430/16000
ablate_active: 15432/16000
ablate_active: 15434/16000
ablate_active: 15436/16000
ablate_active: 15438/16000
ablate_active: 15440/16000
ablate_active: 15442/16000
ablate_active: 15444/16000
ablate_active: 15446/16000
ablate_active: 15448/16000
ablate_active: 15450/16000
ablate_active: 15452/16000
ablate_active: 15454/16000
ablate_active: 15456/16000
ablate_active: 15458/16000
ablate_active: 15460/16000
ablate_active: 15462/16000
ablate_active: 15464/16000
ablate_active: 15466/16000
ablate_active: 15468/16000
ablate_active: 15470/16000
ablate_active: 15472/16000
ablate_active: 15474/16000
ablate_active: 15476/16000
ablate_active: 15478/16000
ablate_active: 15480/16000
ablate_active: 15482/16000
ablate_active: 15484/16000
ablate_active: 15486/16000
ablate_active: 15488/16000
ablate_active: 15490/16000
ablate_active: 15492/16000
ablate_active: 15494/16000
ablate_active: 15496/16000
ablate_active: 15498/16000
ablate_active: 15500/16000
ablate_active: 15502/16000
ablate_active: 15504/16000
ablate_active: 15506/16000
ablate_active: 15508/16000
ablate_active: 15510/16000
ablate_active: 15512/16000
ablate_active: 15514/16000
ablate_active: 15516/16000
ablate_active: 15518/16000
ablate_active: 15520/16000
ablate_active: 15522/16000
ablate_active: 15524/16000
ablate_active: 15526/16000
ablate_active: 15528/16000
ablate_active: 15530/16000
ablate_active: 15532/16000
ablate_active: 15534/16000
ablate_active: 15536/16000
ablate_active: 15538/16000
ablate_active: 15540/16000
ablate_active: 15542/16000
ablate_active: 15544/16000
ablate_active: 15546/16000
ablate_active: 15548/16000
ablate_active: 15550/16000
ablate_active: 15552/16000
ablate_active: 15554/16000
ablate_active: 15556/16000
ablate_active: 15558/16000
ablate_active: 15560/16000
ablate_active: 15562/16000
ablate_active: 15564/16000
ablate_active: 15566/16000
ablate_active: 15568/16000
ablate_active: 15570/16000
ablate_active: 15572/16000
ablate_active: 15574/16000
ablate_active: 15576/16000
ablate_active: 15578/16000
ablate_active: 15580/16000
ablate_active: 15582/16000
ablate_active: 15584/16000
ablate_active: 15586/16000
ablate_active: 15588/16000
ablate_active: 15590/16000
ablate_active: 15592/16000
ablate_active: 15594/16000
ablate_active: 15596/16000
ablate_active: 15598/16000
ablate_active: 15600/16000
ablate_active: 15602/16000
ablate_active: 15604/16000
ablate_active: 15606/16000
ablate_active: 15608/16000
ablate_active: 15610/16000
ablate_active: 15612/16000
ablate_active: 15614/16000
ablate_active: 15616/16000
ablate_active: 15618/16000
ablate_active: 15620/16000
ablate_active: 15622/16000
ablate_active: 15624/16000
ablate_active: 15626/16000
ablate_active: 15628/16000
ablate_active: 15630/16000
ablate_active: 15632/16000
ablate_active: 15634/16000
ablate_active: 15636/16000
ablate_active: 15638/16000
ablate_active: 15640/16000
ablate_active: 15642/16000
ablate_active: 15644/16000
ablate_active: 15646/16000
ablate_active: 15648/16000
ablate_active: 15650/16000
ablate_active: 15652/16000
ablate_active: 15654/16000
ablate_active: 15656/16000
ablate_active: 15658/16000
ablate_active: 15660/16000
ablate_active: 15662/16000
ablate_active: 15664/16000

ablate_active: 15666/16000
ablate_active: 15668/16000
ablate_active: 15670/16000
ablate_active: 15672/16000
ablate_active: 15674/16000
ablate_active: 15676/16000
ablate_active: 15678/16000
ablate_active: 15680/16000
ablate_active: 15682/16000
ablate_active: 15684/16000
ablate_active: 15686/16000
ablate_active: 15688/16000
ablate_active: 15690/16000
ablate_active: 15692/16000
ablate_active: 15694/16000
ablate_active: 15696/16000
ablate_active: 15698/16000
ablate_active: 15700/16000
ablate_active: 15702/16000
ablate_active: 15704/16000
ablate_active: 15706/16000
ablate_active: 15708/16000
ablate_active: 15710/16000
ablate_active: 15712/16000
ablate_active: 15714/16000
ablate_active: 15716/16000
ablate_active: 15718/16000
ablate_active: 15720/16000
ablate_active: 15722/16000
ablate_active: 15724/16000
ablate_active: 15726/16000
ablate_active: 15728/16000
ablate_active: 15730/16000
ablate_active: 15732/16000
ablate_active: 15734/16000
ablate_active: 15736/16000
ablate_active: 15738/16000
ablate_active: 15740/16000
ablate_active: 15742/16000
ablate_active: 15744/16000
ablate_active: 15746/16000
ablate_active: 15748/16000
ablate_active: 15750/16000
ablate_active: 15752/16000
ablate_active: 15754/16000
ablate_active: 15756/16000
ablate_active: 15758/16000
ablate_active: 15760/16000
ablate_active: 15762/16000
ablate_active: 15764/16000
ablate_active: 15766/16000
ablate_active: 15768/16000
ablate_active: 15770/16000
ablate_active: 15772/16000
ablate_active: 15774/16000
ablate_active: 15776/16000
ablate_active: 15778/16000
ablate_active: 15780/16000
ablate_active: 15782/16000
ablate_active: 15784/16000
ablate_active: 15786/16000
ablate_active: 15788/16000
ablate_active: 15790/16000
ablate_active: 15792/16000
ablate_active: 15794/16000
ablate_active: 15796/16000
ablate_active: 15798/16000
ablate_active: 15800/16000
ablate_active: 15802/16000
ablate_active: 15804/16000
ablate_active: 15806/16000
ablate_active: 15808/16000
ablate_active: 15810/16000
ablate_active: 15812/16000
ablate_active: 15814/16000
ablate_active: 15816/16000
ablate_active: 15818/16000
ablate_active: 15820/16000
ablate_active: 15822/16000
ablate_active: 15824/16000
ablate_active: 15826/16000
ablate_active: 15828/16000
ablate_active: 15830/16000
ablate_active: 15832/16000
ablate_active: 15834/16000
ablate_active: 15836/16000
ablate_active: 15838/16000
ablate_active: 15840/16000
ablate_active: 15842/16000
ablate_active: 15844/16000
ablate_active: 15846/16000
ablate_active: 15848/16000
ablate_active: 15850/16000
ablate_active: 15852/16000
ablate_active: 15854/16000
ablate_active: 15856/16000
ablate_active: 15858/16000
ablate_active: 15860/16000
ablate_active: 15862/16000
ablate_active: 15864/16000
ablate_active: 15866/16000
ablate_active: 15868/16000
ablate_active: 15870/16000
ablate_active: 15872/16000
ablate_active: 15874/16000
ablate_active: 15876/16000
ablate_active: 15878/16000
ablate_active: 15880/16000
ablate_active: 15882/16000
ablate_active: 15884/16000
ablate_active: 15886/16000
ablate_active: 15888/16000
ablate_active: 15890/16000
ablate_active: 15892/16000
ablate_active: 15894/16000
ablate_active: 15896/16000
ablate_active: 15898/16000
ablate_active: 15900/16000
ablate_active: 15902/16000
ablate_active: 15904/16000
ablate_active: 15906/16000
ablate_active: 15908/16000
ablate_active: 15910/16000
ablate_active: 15912/16000
ablate_active: 15914/16000
ablate_active: 15916/16000
ablate_active: 15918/16000
ablate_active: 15920/16000
ablate_active: 15922/16000
ablate_active: 15924/16000
ablate_active: 15926/16000
ablate_active: 15928/16000
ablate_active: 15930/16000
ablate_active: 15932/16000
ablate_active: 15934/16000
ablate_active: 15936/16000
ablate_active: 15938/16000
ablate_active: 15940/16000
ablate_active: 15942/16000
ablate_active: 15944/16000
ablate_active: 15946/16000
ablate_active: 15948/16000
ablate_active: 15950/16000
ablate_active: 15952/16000
ablate_active: 15954/16000
ablate_active: 15956/16000
ablate_active: 15958/16000
ablate_active: 15960/16000
ablate_active: 15962/16000
ablate_active: 15964/16000
ablate_active: 15966/16000
ablate_active: 15968/16000
ablate_active: 15970/16000
ablate_active: 15972/16000
ablate_active: 15974/16000
ablate_active: 15976/16000
ablate_active: 15978/16000
ablate_active: 15980/16000
ablate_active: 15982/16000
ablate_active: 15984/16000
ablate_active: 15986/16000
ablate_active: 15988/16000
ablate_active: 15990/16000
ablate_active: 15992/16000
ablate_active: 15994/16000
ablate_active: 15996/16000
ablate_active: 15998/16000
ablate_active: 16000/16000
amplify: 2/16000
amplify: 4/16000
amplify: 6/16000
amplify: 8/16000
amplify: 10/16000
amplify: 12/16000
amplify: 14/16000
amplify: 16/16000
amplify: 18/16000
amplify: 20/16000
amplify: 22/16000
amplify: 24/16000
amplify: 26/16000
amplify: 28/16000
amplify: 30/16000
amplify: 32/16000
amplify: 34/16000
amplify: 36/16000
amplify: 38/16000
amplify: 40/16000
amplify: 42/16000
amplify: 44/16000
amplify: 46/16000
amplify: 48/16000
amplify: 50/16000
amplify: 52/16000
amplify: 54/16000
amplify: 56/16000
amplify: 58/16000
amplify: 60/16000
amplify: 62/16000
amplify: 64/16000
amplify: 66/16000
amplify: 68/16000
amplify: 70/16000
amplify: 72/16000
amplify: 74/16000
amplify: 76/16000
amplify: 78/16000
amplify: 80/16000
amplify: 82/16000
amplify: 84/16000
amplify: 86/16000
amplify: 88/16000
amplify: 90/16000
amplify: 92/16000
amplify: 94/16000
amplify: 96/16000
amplify: 98/16000
amplify: 100/16000
amplify: 102/16000
amplify: 104/16000
amplify: 106/16000
amplify: 108/16000
amplify: 110/16000
amplify: 112/16000
amplify: 114/16000
amplify: 116/16000
amplify: 118/16000
amplify: 120/16000
amplify: 122/16000
amplify: 124/16000
amplify: 126/16000
amplify: 128/16000
amplify: 130/16000
amplify: 132/16000
amplify: 134/16000
amplify: 136/16000
amplify: 138/16000
amplify: 140/16000
amplify: 142/16000
amplify: 144/16000
amplify: 146/16000
amplify: 148/16000
amplify: 150/16000
amplify: 152/16000
amplify: 154/16000
amplify: 156/16000
amplify: 158/16000
amplify: 160/16000
amplify: 162/16000
amplify: 164/16000
amplify: 166/16000
amplify: 168/16000
amplify: 170/16000
amplify: 172/16000
amplify: 174/16000
amplify: 176/16000
amplify: 178/16000
amplify: 180/16000
amplify: 182/16000
amplify: 184/16000
amplify: 186/16000
amplify: 188/16000
amplify: 190/16000
amplify: 192/16000
amplify: 194/16000
amplify: 196/16000
amplify: 198/16000
amplify: 200/16000
amplify: 202/16000
amplify: 204/16000
amplify: 206/16000
amplify: 208/16000
amplify: 210/16000
amplify: 212/16000
amplify: 214/16000
amplify: 216/16000
amplify: 218/16000
amplify: 220/16000
amplify: 222/16000
amplify: 224/16000
amplify: 226/16000
amplify: 228/16000
amplify: 230/16000
amplify: 232/16000
amplify: 234/16000
amplify: 236/16000
amplify: 238/16000
amplify: 240/16000
amplify: 242/16000
amplify: 244/16000
amplify: 246/16000
amplify: 248/16000
amplify: 250/16000
amplify: 252/16000
amplify: 254/16000
amplify: 256/16000
amplify: 258/16000
amplify: 260/16000
amplify: 262/16000
amplify: 264/16000
amplify: 266/16000
amplify: 268/16000
amplify: 270/16000
amplify: 272/16000
amplify: 274/16000
amplify: 276/16000
amplify: 278/16000
amplify: 280/16000
amplify: 282/16000
amplify: 284/16000
amplify: 286/16000
amplify: 288/16000
amplify: 290/16000
amplify: 292/16000
amplify: 294/16000
amplify: 296/16000
amplify: 298/16000
amplify: 300/16000
amplify: 302/16000
amplify: 304/16000
amplify: 306/16000
amplify: 308/16000
amplify: 310/16000
amplify: 312/16000
amplify: 314/16000
amplify: 316/16000
amplify: 318/16000
amplify: 320/16000
amplify: 322/16000
amplify: 324/16000
amplify: 326/16000
amplify: 328/16000
amplify: 330/16000
amplify: 332/16000
amplify: 334/16000
amplify: 336/16000
amplify: 338/16000
amplify: 340/16000
amplify: 342/16000
amplify: 344/16000
amplify: 346/16000
amplify: 348/16000
amplify: 350/16000
amplify: 352/16000
amplify: 354/16000
amplify: 356/16000
amplify: 358/16000
amplify: 360/16000
amplify: 362/16000
amplify: 364/16000
amplify: 366/16000
amplify: 368/16000
amplify: 370/16000
amplify: 372/16000
amplify: 374/16000
amplify: 376/16000
amplify: 378/16000
amplify: 380/16000
amplify: 382/16000
amplify: 384/16000
amplify: 386/16000
amplify: 388/16000
amplify: 390/16000
amplify: 392/16000
amplify: 394/16000

amplify: 396/16000
amplify: 398/16000
amplify: 400/16000
amplify: 402/16000
amplify: 404/16000
amplify: 406/16000
amplify: 408/16000
amplify: 410/16000
amplify: 412/16000
amplify: 414/16000
amplify: 416/16000
amplify: 418/16000
amplify: 420/16000
amplify: 422/16000
amplify: 424/16000
amplify: 426/16000
amplify: 428/16000
amplify: 430/16000
amplify: 432/16000
amplify: 434/16000
amplify: 436/16000
amplify: 438/16000
amplify: 440/16000
amplify: 442/16000
amplify: 444/16000
amplify: 446/16000
amplify: 448/16000
amplify: 450/16000
amplify: 452/16000
amplify: 454/16000
amplify: 456/16000
amplify: 458/16000
amplify: 460/16000
amplify: 462/16000
amplify: 464/16000
amplify: 466/16000
amplify: 468/16000
amplify: 470/16000
amplify: 472/16000
amplify: 474/16000
amplify: 476/16000
amplify: 478/16000
amplify: 480/16000
amplify: 482/16000
amplify: 484/16000
amplify: 486/16000
amplify: 488/16000
amplify: 490/16000
amplify: 492/16000
amplify: 494/16000
amplify: 496/16000
amplify: 498/16000
amplify: 500/16000
amplify: 502/16000
amplify: 504/16000
amplify: 506/16000
amplify: 508/16000
amplify: 510/16000
amplify: 512/16000
amplify: 514/16000
amplify: 516/16000
amplify: 518/16000
amplify: 520/16000
amplify: 522/16000
amplify: 524/16000
amplify: 526/16000
amplify: 528/16000
amplify: 530/16000
amplify: 532/16000
amplify: 534/16000
amplify: 536/16000
amplify: 538/16000
amplify: 540/16000
amplify: 542/16000
amplify: 544/16000
amplify: 546/16000
amplify: 548/16000
amplify: 550/16000
amplify: 552/16000
amplify: 554/16000
amplify: 556/16000
amplify: 558/16000
amplify: 560/16000
amplify: 562/16000
amplify: 564/16000
amplify: 566/16000
amplify: 568/16000
amplify: 570/16000
amplify: 572/16000
amplify: 574/16000
amplify: 576/16000
amplify: 578/16000
amplify: 580/16000
amplify: 582/16000
amplify: 584/16000
amplify: 586/16000
amplify: 588/16000
amplify: 590/16000
amplify: 592/16000
amplify: 594/16000
amplify: 596/16000
amplify: 598/16000
amplify: 600/16000
amplify: 602/16000
amplify: 604/16000
amplify: 606/16000
amplify: 608/16000
amplify: 610/16000
amplify: 612/16000
amplify: 614/16000
amplify: 616/16000
amplify: 618/16000
amplify: 620/16000
amplify: 622/16000
amplify: 624/16000
amplify: 626/16000
amplify: 628/16000
amplify: 630/16000
amplify: 632/16000
amplify: 634/16000
amplify: 636/16000
amplify: 638/16000
amplify: 640/16000
amplify: 642/16000
amplify: 644/16000
amplify: 646/16000
amplify: 648/16000
amplify: 650/16000
amplify: 652/16000
amplify: 654/16000
amplify: 656/16000
amplify: 658/16000
amplify: 660/16000
amplify: 662/16000
amplify: 664/16000
amplify: 666/16000
amplify: 668/16000
amplify: 670/16000
amplify: 672/16000
amplify: 674/16000
amplify: 676/16000
amplify: 678/16000
amplify: 680/16000
amplify: 682/16000
amplify: 684/16000
amplify: 686/16000
amplify: 688/16000
amplify: 690/16000
amplify: 692/16000
amplify: 694/16000
amplify: 696/16000
amplify: 698/16000
amplify: 700/16000
amplify: 702/16000
amplify: 704/16000
amplify: 706/16000
amplify: 708/16000
amplify: 710/16000
amplify: 712/16000
amplify: 714/16000
amplify: 716/16000
amplify: 718/16000
amplify: 720/16000
amplify: 722/16000
amplify: 724/16000
amplify: 726/16000
amplify: 728/16000
amplify: 730/16000
amplify: 732/16000
amplify: 734/16000
amplify: 736/16000
amplify: 738/16000
amplify: 740/16000
amplify: 742/16000
amplify: 744/16000
amplify: 746/16000
amplify: 748/16000
amplify: 750/16000
amplify: 752/16000
amplify: 754/16000
amplify: 756/16000
amplify: 758/16000
amplify: 760/16000
amplify: 762/16000
amplify: 764/16000
amplify: 766/16000
amplify: 768/16000
amplify: 770/16000
amplify: 772/16000
amplify: 774/16000
amplify: 776/16000
amplify: 778/16000
amplify: 780/16000
amplify: 782/16000
amplify: 784/16000
amplify: 786/16000
amplify: 788/16000
amplify: 790/16000
amplify: 792/16000
amplify: 794/16000
amplify: 796/16000
amplify: 798/16000
amplify: 800/16000
amplify: 802/16000
amplify: 804/16000
amplify: 806/16000
amplify: 808/16000
amplify: 810/16000
amplify: 812/16000
amplify: 814/16000
amplify: 816/16000
amplify: 818/16000
amplify: 820/16000
amplify: 822/16000
amplify: 824/16000
amplify: 826/16000
amplify: 828/16000
amplify: 830/16000
amplify: 832/16000
amplify: 834/16000
amplify: 836/16000
amplify: 838/16000
amplify: 840/16000
amplify: 842/16000
amplify: 844/16000
amplify: 846/16000
amplify: 848/16000
amplify: 850/16000
amplify: 852/16000
amplify: 854/16000
amplify: 856/16000
amplify: 858/16000
amplify: 860/16000
amplify: 862/16000
amplify: 864/16000
amplify: 866/16000
amplify: 868/16000
amplify: 870/16000
amplify: 872/16000
amplify: 874/16000
amplify: 876/16000
amplify: 878/16000
amplify: 880/16000
amplify: 882/16000
amplify: 884/16000
amplify: 886/16000
amplify: 888/16000
amplify: 890/16000
amplify: 892/16000
amplify: 894/16000
amplify: 896/16000
amplify: 898/16000
amplify: 900/16000
amplify: 902/16000
amplify: 904/16000
amplify: 906/16000
amplify: 908/16000
amplify: 910/16000
amplify: 912/16000
amplify: 914/16000
amplify: 916/16000
amplify: 918/16000
amplify: 920/16000
amplify: 922/16000
amplify: 924/16000
amplify: 926/16000
amplify: 928/16000
amplify: 930/16000
amplify: 932/16000
amplify: 934/16000
amplify: 936/16000
amplify: 938/16000
amplify: 940/16000
amplify: 942/16000
amplify: 944/16000
amplify: 946/16000
amplify: 948/16000
amplify: 950/16000
amplify: 952/16000
amplify: 954/16000
amplify: 956/16000
amplify: 958/16000
amplify: 960/16000
amplify: 962/16000
amplify: 964/16000
amplify: 966/16000
amplify: 968/16000
amplify: 970/16000
amplify: 972/16000
amplify: 974/16000
amplify: 976/16000
amplify: 978/16000
amplify: 980/16000
amplify: 982/16000
amplify: 984/16000
amplify: 986/16000
amplify: 988/16000
amplify: 990/16000
amplify: 992/16000
amplify: 994/16000
amplify: 996/16000
amplify: 998/16000
amplify: 1000/16000
amplify: 1002/16000
amplify: 1004/16000
amplify: 1006/16000
amplify: 1008/16000
amplify: 1010/16000
amplify: 1012/16000
amplify: 1014/16000
amplify: 1016/16000
amplify: 1018/16000
amplify: 1020/16000
amplify: 1022/16000
amplify: 1024/16000
amplify: 1026/16000
amplify: 1028/16000
amplify: 1030/16000
amplify: 1032/16000
amplify: 1034/16000
amplify: 1036/16000
amplify: 1038/16000
amplify: 1040/16000
amplify: 1042/16000
amplify: 1044/16000
amplify: 1046/16000
amplify: 1048/16000
amplify: 1050/16000
amplify: 1052/16000
amplify: 1054/16000
amplify: 1056/16000
amplify: 1058/16000
amplify: 1060/16000
amplify: 1062/16000
amplify: 1064/16000
amplify: 1066/16000
amplify: 1068/16000
amplify: 1070/16000
amplify: 1072/16000
amplify: 1074/16000
amplify: 1076/16000
amplify: 1078/16000
amplify: 1080/16000
amplify: 1082/16000
amplify: 1084/16000
amplify: 1086/16000
amplify: 1088/16000
amplify: 1090/16000
amplify: 1092/16000
amplify: 1094/16000
amplify: 1096/16000
amplify: 1098/16000
amplify: 1100/16000
amplify: 1102/16000
amplify: 1104/16000
amplify: 1106/16000
amplify: 1108/16000
amplify: 1110/16000
amplify: 1112/16000
amplify: 1114/16000
amplify: 1116/16000
amplify: 1118/16000
amplify: 1120/16000
amplify: 1122/16000
amplify: 1124/16000
amplify: 1126/16000
amplify: 1128/16000
amplify: 1130/16000
amplify: 1132/16000
amplify: 1134/16000
amplify: 1136/16000
amplify: 1138/16000
amplify: 1140/16000
amplify: 1142/16000
amplify: 1144/16000
amplify: 1146/16000
amplify: 1148/16000
amplify: 1150/16000
amplify: 1152/16000
amplify: 1154/16000
amplify: 1156/16000
amplify: 1158/16000
amplify: 1160/16000
amplify: 1162/16000
amplify: 1164/16000
amplify: 1166/16000
amplify: 1168/16000
amplify: 1170/16000
amplify: 1172/16000
amplify: 1174/16000
amplify: 1176/16000
amplify: 1178/16000
amplify: 1180/16000
amplify: 1182/16000
amplify: 1184/16000
amplify: 1186/16000
amplify: 1188/16000
amplify: 1190/16000
amplify: 1192/16000
amplify: 1194/16000
amplify: 1196/16000
amplify: 1198/16000
amplify: 1200/16000
amplify: 1202/16000
amplify: 1204/16000
amplify: 1206/16000
amplify: 1208/16000
amplify: 1210/16000
amplify: 1212/16000
amplify: 1214/16000
amplify: 1216/16000
amplify: 1218/16000
amplify: 1220/16000
amplify: 1222/16000
amplify: 1224/16000
amplify: 1226/16000
amplify: 1228/16000
amplify: 1230/16000
amplify: 1232/16000
amplify: 1234/16000
amplify: 1236/16000
amplify: 1238/16000
amplify: 1240/16000
amplify: 1242/16000
amplify: 1244/16000
amplify: 1246/16000

amplify: 1248/16000
amplify: 1250/16000
amplify: 1252/16000
amplify: 1254/16000
amplify: 1256/16000
amplify: 1258/16000
amplify: 1260/16000
amplify: 1262/16000
amplify: 1264/16000
amplify: 1266/16000
amplify: 1268/16000
amplify: 1270/16000
amplify: 1272/16000
amplify: 1274/16000
amplify: 1276/16000
amplify: 1278/16000
amplify: 1280/16000
amplify: 1282/16000
amplify: 1284/16000
amplify: 1286/16000
amplify: 1288/16000
amplify: 1290/16000
amplify: 1292/16000
amplify: 1294/16000
amplify: 1296/16000
amplify: 1298/16000
amplify: 1300/16000
amplify: 1302/16000
amplify: 1304/16000
amplify: 1306/16000
amplify: 1308/16000
amplify: 1310/16000
amplify: 1312/16000
amplify: 1314/16000
amplify: 1316/16000
amplify: 1318/16000
amplify: 1320/16000
amplify: 1322/16000
amplify: 1324/16000
amplify: 1326/16000
amplify: 1328/16000
amplify: 1330/16000
amplify: 1332/16000
amplify: 1334/16000
amplify: 1336/16000
amplify: 1338/16000
amplify: 1340/16000
amplify: 1342/16000
amplify: 1344/16000
amplify: 1346/16000
amplify: 1348/16000
amplify: 1350/16000
amplify: 1352/16000
amplify: 1354/16000
amplify: 1356/16000
amplify: 1358/16000
amplify: 1360/16000
amplify: 1362/16000
amplify: 1364/16000
amplify: 1366/16000
amplify: 1368/16000
amplify: 1370/16000
amplify: 1372/16000
amplify: 1374/16000
amplify: 1376/16000
amplify: 1378/16000
amplify: 1380/16000
amplify: 1382/16000
amplify: 1384/16000
amplify: 1386/16000
amplify: 1388/16000
amplify: 1390/16000
amplify: 1392/16000
amplify: 1394/16000
amplify: 1396/16000
amplify: 1398/16000
amplify: 1400/16000
amplify: 1402/16000
amplify: 1404/16000
amplify: 1406/16000
amplify: 1408/16000
amplify: 1410/16000
amplify: 1412/16000
amplify: 1414/16000
amplify: 1416/16000
amplify: 1418/16000
amplify: 1420/16000
amplify: 1422/16000
amplify: 1424/16000
amplify: 1426/16000
amplify: 1428/16000
amplify: 1430/16000
amplify: 1432/16000
amplify: 1434/16000
amplify: 1436/16000
amplify: 1438/16000
amplify: 1440/16000
amplify: 1442/16000
amplify: 1444/16000
amplify: 1446/16000
amplify: 1448/16000
amplify: 1450/16000
amplify: 1452/16000
amplify: 1454/16000
amplify: 1456/16000
amplify: 1458/16000
amplify: 1460/16000
amplify: 1462/16000
amplify: 1464/16000
amplify: 1466/16000
amplify: 1468/16000
amplify: 1470/16000
amplify: 1472/16000
amplify: 1474/16000
amplify: 1476/16000
amplify: 1478/16000
amplify: 1480/16000
amplify: 1482/16000
amplify: 1484/16000
amplify: 1486/16000
amplify: 1488/16000
amplify: 1490/16000
amplify: 1492/16000
amplify: 1494/16000
amplify: 1496/16000
amplify: 1498/16000
amplify: 1500/16000
amplify: 1502/16000
amplify: 1504/16000
amplify: 1506/16000
amplify: 1508/16000
amplify: 1510/16000
amplify: 1512/16000
amplify: 1514/16000
amplify: 1516/16000
amplify: 1518/16000
amplify: 1520/16000
amplify: 1522/16000
amplify: 1524/16000
amplify: 1526/16000
amplify: 1528/16000
amplify: 1530/16000
amplify: 1532/16000
amplify: 1534/16000
amplify: 1536/16000
amplify: 1538/16000
amplify: 1540/16000
amplify: 1542/16000
amplify: 1544/16000
amplify: 1546/16000
amplify: 1548/16000
amplify: 1550/16000
amplify: 1552/16000
amplify: 1554/16000
amplify: 1556/16000
amplify: 1558/16000
amplify: 1560/16000
amplify: 1562/16000
amplify: 1564/16000
amplify: 1566/16000
amplify: 1568/16000
amplify: 1570/16000
amplify: 1572/16000
amplify: 1574/16000
amplify: 1576/16000
amplify: 1578/16000
amplify: 1580/16000
amplify: 1582/16000
amplify: 1584/16000
amplify: 1586/16000
amplify: 1588/16000
amplify: 1590/16000
amplify: 1592/16000
amplify: 1594/16000
amplify: 1596/16000
amplify: 1598/16000
amplify: 1600/16000
amplify: 1602/16000
amplify: 1604/16000
amplify: 1606/16000
amplify: 1608/16000
amplify: 1610/16000
amplify: 1612/16000
amplify: 1614/16000
amplify: 1616/16000
amplify: 1618/16000
amplify: 1620/16000
amplify: 1622/16000
amplify: 1624/16000
amplify: 1626/16000
amplify: 1628/16000
amplify: 1630/16000
amplify: 1632/16000
amplify: 1634/16000
amplify: 1636/16000
amplify: 1638/16000
amplify: 1640/16000
amplify: 1642/16000
amplify: 1644/16000
amplify: 1646/16000
amplify: 1648/16000
amplify: 1650/16000
amplify: 1652/16000
amplify: 1654/16000
amplify: 1656/16000
amplify: 1658/16000
amplify: 1660/16000
amplify: 1662/16000
amplify: 1664/16000
amplify: 1666/16000
amplify: 1668/16000
amplify: 1670/16000
amplify: 1672/16000
amplify: 1674/16000
amplify: 1676/16000
amplify: 1678/16000
amplify: 1680/16000
amplify: 1682/16000
amplify: 1684/16000
amplify: 1686/16000
amplify: 1688/16000
amplify: 1690/16000
amplify: 1692/16000
amplify: 1694/16000
amplify: 1696/16000
amplify: 1698/16000
amplify: 1700/16000
amplify: 1702/16000
amplify: 1704/16000
amplify: 1706/16000
amplify: 1708/16000
amplify: 1710/16000
amplify: 1712/16000
amplify: 1714/16000
amplify: 1716/16000
amplify: 1718/16000
amplify: 1720/16000
amplify: 1722/16000
amplify: 1724/16000
amplify: 1726/16000
amplify: 1728/16000
amplify: 1730/16000
amplify: 1732/16000
amplify: 1734/16000
amplify: 1736/16000
amplify: 1738/16000
amplify: 1740/16000
amplify: 1742/16000
amplify: 1744/16000
amplify: 1746/16000
amplify: 1748/16000
amplify: 1750/16000
amplify: 1752/16000
amplify: 1754/16000
amplify: 1756/16000
amplify: 1758/16000
amplify: 1760/16000
amplify: 1762/16000
amplify: 1764/16000
amplify: 1766/16000
amplify: 1768/16000
amplify: 1770/16000
amplify: 1772/16000
amplify: 1774/16000
amplify: 1776/16000
amplify: 1778/16000
amplify: 1780/16000
amplify: 1782/16000
amplify: 1784/16000
amplify: 1786/16000
amplify: 1788/16000
amplify: 1790/16000
amplify: 1792/16000
amplify: 1794/16000
amplify: 1796/16000
amplify: 1798/16000
amplify: 1800/16000
amplify: 1802/16000
amplify: 1804/16000
amplify: 1806/16000
amplify: 1808/16000
amplify: 1810/16000
amplify: 1812/16000
amplify: 1814/16000
amplify: 1816/16000
amplify: 1818/16000
amplify: 1820/16000
amplify: 1822/16000
amplify: 1824/16000
amplify: 1826/16000
amplify: 1828/16000
amplify: 1830/16000
amplify: 1832/16000
amplify: 1834/16000
amplify: 1836/16000
amplify: 1838/16000
amplify: 1840/16000
amplify: 1842/16000
amplify: 1844/16000
amplify: 1846/16000
amplify: 1848/16000
amplify: 1850/16000
amplify: 1852/16000
amplify: 1854/16000
amplify: 1856/16000
amplify: 1858/16000
amplify: 1860/16000
amplify: 1862/16000
amplify: 1864/16000
amplify: 1866/16000
amplify: 1868/16000
amplify: 1870/16000
amplify: 1872/16000
amplify: 1874/16000
amplify: 1876/16000
amplify: 1878/16000
amplify: 1880/16000
amplify: 1882/16000
amplify: 1884/16000
amplify: 1886/16000
amplify: 1888/16000
amplify: 1890/16000
amplify: 1892/16000
amplify: 1894/16000
amplify: 1896/16000
amplify: 1898/16000
amplify: 1900/16000
amplify: 1902/16000
amplify: 1904/16000
amplify: 1906/16000
amplify: 1908/16000
amplify: 1910/16000
amplify: 1912/16000
amplify: 1914/16000
amplify: 1916/16000
amplify: 1918/16000
amplify: 1920/16000
amplify: 1922/16000
amplify: 1924/16000
amplify: 1926/16000
amplify: 1928/16000
amplify: 1930/16000
amplify: 1932/16000
amplify: 1934/16000
amplify: 1936/16000
amplify: 1938/16000
amplify: 1940/16000
amplify: 1942/16000
amplify: 1944/16000
amplify: 1946/16000
amplify: 1948/16000
amplify: 1950/16000
amplify: 1952/16000
amplify: 1954/16000
amplify: 1956/16000
amplify: 1958/16000
amplify: 1960/16000
amplify: 1962/16000
amplify: 1964/16000
amplify: 1966/16000
amplify: 1968/16000
amplify: 1970/16000
amplify: 1972/16000
amplify: 1974/16000
amplify: 1976/16000
amplify: 1978/16000
amplify: 1980/16000
amplify: 1982/16000
amplify: 1984/16000
amplify: 1986/16000
amplify: 1988/16000
amplify: 1990/16000
amplify: 1992/16000
amplify: 1994/16000
amplify: 1996/16000
amplify: 1998/16000
amplify: 2000/16000
amplify: 2002/16000
amplify: 2004/16000
amplify: 2006/16000
amplify: 2008/16000
amplify: 2010/16000
amplify: 2012/16000
amplify: 2014/16000
amplify: 2016/16000
amplify: 2018/16000
amplify: 2020/16000
amplify: 2022/16000
amplify: 2024/16000
amplify: 2026/16000
amplify: 2028/16000
amplify: 2030/16000
amplify: 2032/16000
amplify: 2034/16000
amplify: 2036/16000
amplify: 2038/16000
amplify: 2040/16000
amplify: 2042/16000
amplify: 2044/16000
amplify: 2046/16000
amplify: 2048/16000
amplify: 2050/16000
amplify: 2052/16000
amplify: 2054/16000
amplify: 2056/16000
amplify: 2058/16000
amplify: 2060/16000
amplify: 2062/16000
amplify: 2064/16000
amplify: 2066/16000
amplify: 2068/16000
amplify: 2070/16000

amplify: 2072/16000
amplify: 2074/16000
amplify: 2076/16000
amplify: 2078/16000
amplify: 2080/16000
amplify: 2082/16000
amplify: 2084/16000
amplify: 2086/16000
amplify: 2088/16000
amplify: 2090/16000
amplify: 2092/16000
amplify: 2094/16000
amplify: 2096/16000
amplify: 2098/16000
amplify: 2100/16000
amplify: 2102/16000
amplify: 2104/16000
amplify: 2106/16000
amplify: 2108/16000
amplify: 2110/16000
amplify: 2112/16000
amplify: 2114/16000
amplify: 2116/16000
amplify: 2118/16000
amplify: 2120/16000
amplify: 2122/16000
amplify: 2124/16000
amplify: 2126/16000
amplify: 2128/16000
amplify: 2130/16000
amplify: 2132/16000
amplify: 2134/16000
amplify: 2136/16000
amplify: 2138/16000
amplify: 2140/16000
amplify: 2142/16000
amplify: 2144/16000
amplify: 2146/16000
amplify: 2148/16000
amplify: 2150/16000
amplify: 2152/16000
amplify: 2154/16000
amplify: 2156/16000
amplify: 2158/16000
amplify: 2160/16000
amplify: 2162/16000
amplify: 2164/16000
amplify: 2166/16000
amplify: 2168/16000
amplify: 2170/16000
amplify: 2172/16000
amplify: 2174/16000
amplify: 2176/16000
amplify: 2178/16000
amplify: 2180/16000
amplify: 2182/16000
amplify: 2184/16000
amplify: 2186/16000
amplify: 2188/16000
amplify: 2190/16000
amplify: 2192/16000
amplify: 2194/16000
amplify: 2196/16000
amplify: 2198/16000
amplify: 2200/16000
amplify: 2202/16000
amplify: 2204/16000
amplify: 2206/16000
amplify: 2208/16000
amplify: 2210/16000
amplify: 2212/16000
amplify: 2214/16000
amplify: 2216/16000
amplify: 2218/16000
amplify: 2220/16000
amplify: 2222/16000
amplify: 2224/16000
amplify: 2226/16000
amplify: 2228/16000
amplify: 2230/16000
amplify: 2232/16000
amplify: 2234/16000
amplify: 2236/16000
amplify: 2238/16000
amplify: 2240/16000
amplify: 2242/16000
amplify: 2244/16000
amplify: 2246/16000
amplify: 2248/16000
amplify: 2250/16000
amplify: 2252/16000
amplify: 2254/16000
amplify: 2256/16000
amplify: 2258/16000
amplify: 2260/16000
amplify: 2262/16000
amplify: 2264/16000
amplify: 2266/16000
amplify: 2268/16000
amplify: 2270/16000
amplify: 2272/16000
amplify: 2274/16000
amplify: 2276/16000
amplify: 2278/16000
amplify: 2280/16000
amplify: 2282/16000
amplify: 2284/16000
amplify: 2286/16000
amplify: 2288/16000
amplify: 2290/16000
amplify: 2292/16000
amplify: 2294/16000
amplify: 2296/16000
amplify: 2298/16000
amplify: 2300/16000
amplify: 2302/16000
amplify: 2304/16000
amplify: 2306/16000
amplify: 2308/16000
amplify: 2310/16000
amplify: 2312/16000
amplify: 2314/16000
amplify: 2316/16000
amplify: 2318/16000
amplify: 2320/16000
amplify: 2322/16000
amplify: 2324/16000
amplify: 2326/16000
amplify: 2328/16000
amplify: 2330/16000
amplify: 2332/16000
amplify: 2334/16000
amplify: 2336/16000
amplify: 2338/16000
amplify: 2340/16000
amplify: 2342/16000
amplify: 2344/16000
amplify: 2346/16000
amplify: 2348/16000
amplify: 2350/16000
amplify: 2352/16000
amplify: 2354/16000
amplify: 2356/16000
amplify: 2358/16000
amplify: 2360/16000
amplify: 2362/16000
amplify: 2364/16000
amplify: 2366/16000
amplify: 2368/16000
amplify: 2370/16000
amplify: 2372/16000
amplify: 2374/16000
amplify: 2376/16000
amplify: 2378/16000
amplify: 2380/16000
amplify: 2382/16000
amplify: 2384/16000
amplify: 2386/16000
amplify: 2388/16000
amplify: 2390/16000
amplify: 2392/16000
amplify: 2394/16000
amplify: 2396/16000
amplify: 2398/16000
amplify: 2400/16000
amplify: 2402/16000
amplify: 2404/16000
amplify: 2406/16000
amplify: 2408/16000
amplify: 2410/16000
amplify: 2412/16000
amplify: 2414/16000
amplify: 2416/16000
amplify: 2418/16000
amplify: 2420/16000
amplify: 2422/16000
amplify: 2424/16000
amplify: 2426/16000
amplify: 2428/16000
amplify: 2430/16000
amplify: 2432/16000
amplify: 2434/16000
amplify: 2436/16000
amplify: 2438/16000
amplify: 2440/16000
amplify: 2442/16000
amplify: 2444/16000
amplify: 2446/16000
amplify: 2448/16000
amplify: 2450/16000
amplify: 2452/16000
amplify: 2454/16000
amplify: 2456/16000
amplify: 2458/16000
amplify: 2460/16000
amplify: 2462/16000
amplify: 2464/16000
amplify: 2466/16000
amplify: 2468/16000
amplify: 2470/16000
amplify: 2472/16000
amplify: 2474/16000
amplify: 2476/16000
amplify: 2478/16000
amplify: 2480/16000
amplify: 2482/16000
amplify: 2484/16000
amplify: 2486/16000
amplify: 2488/16000
amplify: 2490/16000
amplify: 2492/16000
amplify: 2494/16000
amplify: 2496/16000
amplify: 2498/16000
amplify: 2500/16000
amplify: 2502/16000
amplify: 2504/16000
amplify: 2506/16000
amplify: 2508/16000
amplify: 2510/16000
amplify: 2512/16000
amplify: 2514/16000
amplify: 2516/16000
amplify: 2518/16000
amplify: 2520/16000
amplify: 2522/16000
amplify: 2524/16000
amplify: 2526/16000
amplify: 2528/16000
amplify: 2530/16000
amplify: 2532/16000
amplify: 2534/16000
amplify: 2536/16000
amplify: 2538/16000
amplify: 2540/16000
amplify: 2542/16000
amplify: 2544/16000
amplify: 2546/16000
amplify: 2548/16000
amplify: 2550/16000
amplify: 2552/16000
amplify: 2554/16000
amplify: 2556/16000
amplify: 2558/16000
amplify: 2560/16000
amplify: 2562/16000
amplify: 2564/16000
amplify: 2566/16000
amplify: 2568/16000
amplify: 2570/16000
amplify: 2572/16000
amplify: 2574/16000
amplify: 2576/16000
amplify: 2578/16000
amplify: 2580/16000
amplify: 2582/16000
amplify: 2584/16000
amplify: 2586/16000
amplify: 2588/16000
amplify: 2590/16000
amplify: 2592/16000
amplify: 2594/16000
amplify: 2596/16000
amplify: 2598/16000
amplify: 2600/16000
amplify: 2602/16000
amplify: 2604/16000
amplify: 2606/16000
amplify: 2608/16000
amplify: 2610/16000
amplify: 2612/16000
amplify: 2614/16000
amplify: 2616/16000
amplify: 2618/16000
amplify: 2620/16000
amplify: 2622/16000
amplify: 2624/16000
amplify: 2626/16000
amplify: 2628/16000
amplify: 2630/16000
amplify: 2632/16000
amplify: 2634/16000
amplify: 2636/16000
amplify: 2638/16000
amplify: 2640/16000
amplify: 2642/16000
amplify: 2644/16000
amplify: 2646/16000
amplify: 2648/16000
amplify: 2650/16000
amplify: 2652/16000
amplify: 2654/16000
amplify: 2656/16000
amplify: 2658/16000
amplify: 2660/16000
amplify: 2662/16000
amplify: 2664/16000
amplify: 2666/16000
amplify: 2668/16000
amplify: 2670/16000
amplify: 2672/16000
amplify: 2674/16000
amplify: 2676/16000
amplify: 2678/16000
amplify: 2680/16000
amplify: 2682/16000
amplify: 2684/16000
amplify: 2686/16000
amplify: 2688/16000
amplify: 2690/16000
amplify: 2692/16000
amplify: 2694/16000
amplify: 2696/16000
amplify: 2698/16000
amplify: 2700/16000
amplify: 2702/16000
amplify: 2704/16000
amplify: 2706/16000
amplify: 2708/16000
amplify: 2710/16000
amplify: 2712/16000
amplify: 2714/16000
amplify: 2716/16000
amplify: 2718/16000
amplify: 2720/16000
amplify: 2722/16000
amplify: 2724/16000
amplify: 2726/16000
amplify: 2728/16000
amplify: 2730/16000
amplify: 2732/16000
amplify: 2734/16000
amplify: 2736/16000
amplify: 2738/16000
amplify: 2740/16000
amplify: 2742/16000
amplify: 2744/16000
amplify: 2746/16000
amplify: 2748/16000
amplify: 2750/16000
amplify: 2752/16000
amplify: 2754/16000
amplify: 2756/16000
amplify: 2758/16000
amplify: 2760/16000
amplify: 2762/16000
amplify: 2764/16000
amplify: 2766/16000
amplify: 2768/16000
amplify: 2770/16000
amplify: 2772/16000
amplify: 2774/16000
amplify: 2776/16000
amplify: 2778/16000
amplify: 2780/16000
amplify: 2782/16000
amplify: 2784/16000
amplify: 2786/16000
amplify: 2788/16000
amplify: 2790/16000
amplify: 2792/16000
amplify: 2794/16000
amplify: 2796/16000
amplify: 2798/16000
amplify: 2800/16000
amplify: 2802/16000
amplify: 2804/16000
amplify: 2806/16000
amplify: 2808/16000
amplify: 2810/16000
amplify: 2812/16000
amplify: 2814/16000
amplify: 2816/16000
amplify: 2818/16000
amplify: 2820/16000
amplify: 2822/16000
amplify: 2824/16000
amplify: 2826/16000
amplify: 2828/16000
amplify: 2830/16000
amplify: 2832/16000
amplify: 2834/16000
amplify: 2836/16000
amplify: 2838/16000
amplify: 2840/16000
amplify: 2842/16000
amplify: 2844/16000
amplify: 2846/16000
amplify: 2848/16000
amplify: 2850/16000
amplify: 2852/16000
amplify: 2854/16000
amplify: 2856/16000
amplify: 2858/16000
amplify: 2860/16000
amplify: 2862/16000
amplify: 2864/16000
amplify: 2866/16000
amplify: 2868/16000
amplify: 2870/16000
amplify: 2872/16000
amplify: 2874/16000
amplify: 2876/16000
amplify: 2878/16000
amplify: 2880/16000
amplify: 2882/16000
amplify: 2884/16000
amplify: 2886/16000
amplify: 2888/16000
amplify: 2890/16000
amplify: 2892/16000

amplify: 2894/16000
amplify: 2896/16000
amplify: 2898/16000
amplify: 2900/16000
amplify: 2902/16000
amplify: 2904/16000
amplify: 2906/16000
amplify: 2908/16000
amplify: 2910/16000
amplify: 2912/16000
amplify: 2914/16000
amplify: 2916/16000
amplify: 2918/16000
amplify: 2920/16000
amplify: 2922/16000
amplify: 2924/16000
amplify: 2926/16000
amplify: 2928/16000
amplify: 2930/16000
amplify: 2932/16000
amplify: 2934/16000
amplify: 2936/16000
amplify: 2938/16000
amplify: 2940/16000
amplify: 2942/16000
amplify: 2944/16000
amplify: 2946/16000
amplify: 2948/16000
amplify: 2950/16000
amplify: 2952/16000
amplify: 2954/16000
amplify: 2956/16000
amplify: 2958/16000
amplify: 2960/16000
amplify: 2962/16000
amplify: 2964/16000
amplify: 2966/16000
amplify: 2968/16000
amplify: 2970/16000
amplify: 2972/16000
amplify: 2974/16000
amplify: 2976/16000
amplify: 2978/16000
amplify: 2980/16000
amplify: 2982/16000
amplify: 2984/16000
amplify: 2986/16000
amplify: 2988/16000
amplify: 2990/16000
amplify: 2992/16000
amplify: 2994/16000
amplify: 2996/16000
amplify: 2998/16000
amplify: 3000/16000
amplify: 3002/16000
amplify: 3004/16000
amplify: 3006/16000
amplify: 3008/16000
amplify: 3010/16000
amplify: 3012/16000
amplify: 3014/16000
amplify: 3016/16000
amplify: 3018/16000
amplify: 3020/16000
amplify: 3022/16000
amplify: 3024/16000
amplify: 3026/16000
amplify: 3028/16000
amplify: 3030/16000
amplify: 3032/16000
amplify: 3034/16000
amplify: 3036/16000
amplify: 3038/16000
amplify: 3040/16000
amplify: 3042/16000
amplify: 3044/16000
amplify: 3046/16000
amplify: 3048/16000
amplify: 3050/16000
amplify: 3052/16000
amplify: 3054/16000
amplify: 3056/16000
amplify: 3058/16000
amplify: 3060/16000
amplify: 3062/16000
amplify: 3064/16000
amplify: 3066/16000
amplify: 3068/16000
amplify: 3070/16000
amplify: 3072/16000
amplify: 3074/16000
amplify: 3076/16000
amplify: 3078/16000
amplify: 3080/16000
amplify: 3082/16000
amplify: 3084/16000
amplify: 3086/16000
amplify: 3088/16000
amplify: 3090/16000
amplify: 3092/16000
amplify: 3094/16000
amplify: 3096/16000
amplify: 3098/16000
amplify: 3100/16000
amplify: 3102/16000
amplify: 3104/16000
amplify: 3106/16000
amplify: 3108/16000
amplify: 3110/16000
amplify: 3112/16000
amplify: 3114/16000
amplify: 3116/16000
amplify: 3118/16000
amplify: 3120/16000
amplify: 3122/16000
amplify: 3124/16000
amplify: 3126/16000
amplify: 3128/16000
amplify: 3130/16000
amplify: 3132/16000
amplify: 3134/16000
amplify: 3136/16000
amplify: 3138/16000
amplify: 3140/16000
amplify: 3142/16000
amplify: 3144/16000
amplify: 3146/16000
amplify: 3148/16000
amplify: 3150/16000
amplify: 3152/16000
amplify: 3154/16000
amplify: 3156/16000
amplify: 3158/16000
amplify: 3160/16000
amplify: 3162/16000
amplify: 3164/16000
amplify: 3166/16000
amplify: 3168/16000
amplify: 3170/16000
amplify: 3172/16000
amplify: 3174/16000
amplify: 3176/16000
amplify: 3178/16000
amplify: 3180/16000
amplify: 3182/16000
amplify: 3184/16000
amplify: 3186/16000
amplify: 3188/16000
amplify: 3190/16000
amplify: 3192/16000
amplify: 3194/16000
amplify: 3196/16000
amplify: 3198/16000
amplify: 3200/16000
amplify: 3202/16000
amplify: 3204/16000
amplify: 3206/16000
amplify: 3208/16000
amplify: 3210/16000
amplify: 3212/16000
amplify: 3214/16000
amplify: 3216/16000
amplify: 3218/16000
amplify: 3220/16000
amplify: 3222/16000
amplify: 3224/16000
amplify: 3226/16000
amplify: 3228/16000
amplify: 3230/16000
amplify: 3232/16000
amplify: 3234/16000
amplify: 3236/16000
amplify: 3238/16000
amplify: 3240/16000
amplify: 3242/16000
amplify: 3244/16000
amplify: 3246/16000
amplify: 3248/16000
amplify: 3250/16000
amplify: 3252/16000
amplify: 3254/16000
amplify: 3256/16000
amplify: 3258/16000
amplify: 3260/16000
amplify: 3262/16000
amplify: 3264/16000
amplify: 3266/16000
amplify: 3268/16000
amplify: 3270/16000
amplify: 3272/16000
amplify: 3274/16000
amplify: 3276/16000
amplify: 3278/16000
amplify: 3280/16000
amplify: 3282/16000
amplify: 3284/16000
amplify: 3286/16000
amplify: 3288/16000
amplify: 3290/16000
amplify: 3292/16000
amplify: 3294/16000
amplify: 3296/16000
amplify: 3298/16000
amplify: 3300/16000
amplify: 3302/16000
amplify: 3304/16000
amplify: 3306/16000
amplify: 3308/16000
amplify: 3310/16000
amplify: 3312/16000
amplify: 3314/16000
amplify: 3316/16000
amplify: 3318/16000
amplify: 3320/16000
amplify: 3322/16000
amplify: 3324/16000
amplify: 3326/16000
amplify: 3328/16000
amplify: 3330/16000
amplify: 3332/16000
amplify: 3334/16000
amplify: 3336/16000
amplify: 3338/16000
amplify: 3340/16000
amplify: 3342/16000
amplify: 3344/16000
amplify: 3346/16000
amplify: 3348/16000
amplify: 3350/16000
amplify: 3352/16000
amplify: 3354/16000
amplify: 3356/16000
amplify: 3358/16000
amplify: 3360/16000
amplify: 3362/16000
amplify: 3364/16000
amplify: 3366/16000
amplify: 3368/16000
amplify: 3370/16000
amplify: 3372/16000
amplify: 3374/16000
amplify: 3376/16000
amplify: 3378/16000
amplify: 3380/16000
amplify: 3382/16000
amplify: 3384/16000
amplify: 3386/16000
amplify: 3388/16000
amplify: 3390/16000
amplify: 3392/16000
amplify: 3394/16000
amplify: 3396/16000
amplify: 3398/16000
amplify: 3400/16000
amplify: 3402/16000
amplify: 3404/16000
amplify: 3406/16000
amplify: 3408/16000
amplify: 3410/16000
amplify: 3412/16000
amplify: 3414/16000
amplify: 3416/16000
amplify: 3418/16000
amplify: 3420/16000
amplify: 3422/16000
amplify: 3424/16000
amplify: 3426/16000
amplify: 3428/16000
amplify: 3430/16000
amplify: 3432/16000
amplify: 3434/16000
amplify: 3436/16000
amplify: 3438/16000
amplify: 3440/16000
amplify: 3442/16000
amplify: 3444/16000
amplify: 3446/16000
amplify: 3448/16000
amplify: 3450/16000
amplify: 3452/16000
amplify: 3454/16000
amplify: 3456/16000
amplify: 3458/16000
amplify: 3460/16000
amplify: 3462/16000
amplify: 3464/16000
amplify: 3466/16000
amplify: 3468/16000
amplify: 3470/16000
amplify: 3472/16000
amplify: 3474/16000
amplify: 3476/16000
amplify: 3478/16000
amplify: 3480/16000
amplify: 3482/16000
amplify: 3484/16000
amplify: 3486/16000
amplify: 3488/16000
amplify: 3490/16000
amplify: 3492/16000
amplify: 3494/16000
amplify: 3496/16000
amplify: 3498/16000
amplify: 3500/16000
amplify: 3502/16000
amplify: 3504/16000
amplify: 3506/16000
amplify: 3508/16000
amplify: 3510/16000
amplify: 3512/16000
amplify: 3514/16000
amplify: 3516/16000
amplify: 3518/16000
amplify: 3520/16000
amplify: 3522/16000
amplify: 3524/16000
amplify: 3526/16000
amplify: 3528/16000
amplify: 3530/16000
amplify: 3532/16000
amplify: 3534/16000
amplify: 3536/16000
amplify: 3538/16000
amplify: 3540/16000
amplify: 3542/16000
amplify: 3544/16000
amplify: 3546/16000
amplify: 3548/16000
amplify: 3550/16000
amplify: 3552/16000
amplify: 3554/16000
amplify: 3556/16000
amplify: 3558/16000
amplify: 3560/16000
amplify: 3562/16000
amplify: 3564/16000
amplify: 3566/16000
amplify: 3568/16000
amplify: 3570/16000
amplify: 3572/16000
amplify: 3574/16000
amplify: 3576/16000
amplify: 3578/16000
amplify: 3580/16000
amplify: 3582/16000
amplify: 3584/16000
amplify: 3586/16000
amplify: 3588/16000
amplify: 3590/16000
amplify: 3592/16000
amplify: 3594/16000
amplify: 3596/16000
amplify: 3598/16000
amplify: 3600/16000
amplify: 3602/16000
amplify: 3604/16000
amplify: 3606/16000
amplify: 3608/16000
amplify: 3610/16000
amplify: 3612/16000
amplify: 3614/16000
amplify: 3616/16000
amplify: 3618/16000
amplify: 3620/16000
amplify: 3622/16000
amplify: 3624/16000
amplify: 3626/16000
amplify: 3628/16000
amplify: 3630/16000
amplify: 3632/16000
amplify: 3634/16000
amplify: 3636/16000
amplify: 3638/16000
amplify: 3640/16000
amplify: 3642/16000
amplify: 3644/16000
amplify: 3646/16000
amplify: 3648/16000
amplify: 3650/16000
amplify: 3652/16000
amplify: 3654/16000
amplify: 3656/16000
amplify: 3658/16000
amplify: 3660/16000
amplify: 3662/16000
amplify: 3664/16000
amplify: 3666/16000
amplify: 3668/16000
amplify: 3670/16000
amplify: 3672/16000
amplify: 3674/16000
amplify: 3676/16000
amplify: 3678/16000
amplify: 3680/16000
amplify: 3682/16000
amplify: 3684/16000
amplify: 3686/16000
amplify: 3688/16000
amplify: 3690/16000
amplify: 3692/16000
amplify: 3694/16000
amplify: 3696/16000
amplify: 3698/16000
amplify: 3700/16000
amplify: 3702/16000
amplify: 3704/16000
amplify: 3706/16000
amplify: 3708/16000
amplify: 3710/16000
amplify: 3712/16000
amplify: 3714/16000
amplify: 3716/16000

amplify: 3718/16000
amplify: 3720/16000
amplify: 3722/16000
amplify: 3724/16000
amplify: 3726/16000
amplify: 3728/16000
amplify: 3730/16000
amplify: 3732/16000
amplify: 3734/16000
amplify: 3736/16000
amplify: 3738/16000
amplify: 3740/16000
amplify: 3742/16000
amplify: 3744/16000
amplify: 3746/16000
amplify: 3748/16000
amplify: 3750/16000
amplify: 3752/16000
amplify: 3754/16000
amplify: 3756/16000
amplify: 3758/16000
amplify: 3760/16000
amplify: 3762/16000
amplify: 3764/16000
amplify: 3766/16000
amplify: 3768/16000
amplify: 3770/16000
amplify: 3772/16000
amplify: 3774/16000
amplify: 3776/16000
amplify: 3778/16000
amplify: 3780/16000
amplify: 3782/16000
amplify: 3784/16000
amplify: 3786/16000
amplify: 3788/16000
amplify: 3790/16000
amplify: 3792/16000
amplify: 3794/16000
amplify: 3796/16000
amplify: 3798/16000
amplify: 3800/16000
amplify: 3802/16000
amplify: 3804/16000
amplify: 3806/16000
amplify: 3808/16000
amplify: 3810/16000
amplify: 3812/16000
amplify: 3814/16000
amplify: 3816/16000
amplify: 3818/16000
amplify: 3820/16000
amplify: 3822/16000
amplify: 3824/16000
amplify: 3826/16000
amplify: 3828/16000
amplify: 3830/16000
amplify: 3832/16000
amplify: 3834/16000
amplify: 3836/16000
amplify: 3838/16000
amplify: 3840/16000
amplify: 3842/16000
amplify: 3844/16000
amplify: 3846/16000
amplify: 3848/16000
amplify: 3850/16000
amplify: 3852/16000
amplify: 3854/16000
amplify: 3856/16000
amplify: 3858/16000
amplify: 3860/16000
amplify: 3862/16000
amplify: 3864/16000
amplify: 3866/16000
amplify: 3868/16000
amplify: 3870/16000
amplify: 3872/16000
amplify: 3874/16000
amplify: 3876/16000
amplify: 3878/16000
amplify: 3880/16000
amplify: 3882/16000
amplify: 3884/16000
amplify: 3886/16000
amplify: 3888/16000
amplify: 3890/16000
amplify: 3892/16000
amplify: 3894/16000
amplify: 3896/16000
amplify: 3898/16000
amplify: 3900/16000
amplify: 3902/16000
amplify: 3904/16000
amplify: 3906/16000
amplify: 3908/16000
amplify: 3910/16000
amplify: 3912/16000
amplify: 3914/16000
amplify: 3916/16000
amplify: 3918/16000
amplify: 3920/16000
amplify: 3922/16000
amplify: 3924/16000
amplify: 3926/16000
amplify: 3928/16000
amplify: 3930/16000
amplify: 3932/16000
amplify: 3934/16000
amplify: 3936/16000
amplify: 3938/16000
amplify: 3940/16000
amplify: 3942/16000
amplify: 3944/16000
amplify: 3946/16000
amplify: 3948/16000
amplify: 3950/16000
amplify: 3952/16000
amplify: 3954/16000
amplify: 3956/16000
amplify: 3958/16000
amplify: 3960/16000
amplify: 3962/16000
amplify: 3964/16000
amplify: 3966/16000
amplify: 3968/16000
amplify: 3970/16000
amplify: 3972/16000
amplify: 3974/16000
amplify: 3976/16000
amplify: 3978/16000
amplify: 3980/16000
amplify: 3982/16000
amplify: 3984/16000
amplify: 3986/16000
amplify: 3988/16000
amplify: 3990/16000
amplify: 3992/16000
amplify: 3994/16000
amplify: 3996/16000
amplify: 3998/16000
amplify: 4000/16000
amplify: 4002/16000
amplify: 4004/16000
amplify: 4006/16000
amplify: 4008/16000
amplify: 4010/16000
amplify: 4012/16000
amplify: 4014/16000
amplify: 4016/16000
amplify: 4018/16000
amplify: 4020/16000
amplify: 4022/16000
amplify: 4024/16000
amplify: 4026/16000
amplify: 4028/16000
amplify: 4030/16000
amplify: 4032/16000
amplify: 4034/16000
amplify: 4036/16000
amplify: 4038/16000
amplify: 4040/16000
amplify: 4042/16000
amplify: 4044/16000
amplify: 4046/16000
amplify: 4048/16000
amplify: 4050/16000
amplify: 4052/16000
amplify: 4054/16000
amplify: 4056/16000
amplify: 4058/16000
amplify: 4060/16000
amplify: 4062/16000
amplify: 4064/16000
amplify: 4066/16000
amplify: 4068/16000
amplify: 4070/16000
amplify: 4072/16000
amplify: 4074/16000
amplify: 4076/16000
amplify: 4078/16000
amplify: 4080/16000
amplify: 4082/16000
amplify: 4084/16000
amplify: 4086/16000
amplify: 4088/16000
amplify: 4090/16000
amplify: 4092/16000
amplify: 4094/16000
amplify: 4096/16000
amplify: 4098/16000
amplify: 4100/16000
amplify: 4102/16000
amplify: 4104/16000
amplify: 4106/16000
amplify: 4108/16000
amplify: 4110/16000
amplify: 4112/16000
amplify: 4114/16000
amplify: 4116/16000
amplify: 4118/16000
amplify: 4120/16000
amplify: 4122/16000
amplify: 4124/16000
amplify: 4126/16000
amplify: 4128/16000
amplify: 4130/16000
amplify: 4132/16000
amplify: 4134/16000
amplify: 4136/16000
amplify: 4138/16000
amplify: 4140/16000
amplify: 4142/16000
amplify: 4144/16000
amplify: 4146/16000
amplify: 4148/16000
amplify: 4150/16000
amplify: 4152/16000
amplify: 4154/16000
amplify: 4156/16000
amplify: 4158/16000
amplify: 4160/16000
amplify: 4162/16000
amplify: 4164/16000
amplify: 4166/16000
amplify: 4168/16000
amplify: 4170/16000
amplify: 4172/16000
amplify: 4174/16000
amplify: 4176/16000
amplify: 4178/16000
amplify: 4180/16000
amplify: 4182/16000
amplify: 4184/16000
amplify: 4186/16000
amplify: 4188/16000
amplify: 4190/16000
amplify: 4192/16000
amplify: 4194/16000
amplify: 4196/16000
amplify: 4198/16000
amplify: 4200/16000
amplify: 4202/16000
amplify: 4204/16000
amplify: 4206/16000
amplify: 4208/16000
amplify: 4210/16000
amplify: 4212/16000
amplify: 4214/16000
amplify: 4216/16000
amplify: 4218/16000
amplify: 4220/16000
amplify: 4222/16000
amplify: 4224/16000
amplify: 4226/16000
amplify: 4228/16000
amplify: 4230/16000
amplify: 4232/16000
amplify: 4234/16000
amplify: 4236/16000
amplify: 4238/16000
amplify: 4240/16000
amplify: 4242/16000
amplify: 4244/16000
amplify: 4246/16000
amplify: 4248/16000
amplify: 4250/16000
amplify: 4252/16000
amplify: 4254/16000
amplify: 4256/16000
amplify: 4258/16000
amplify: 4260/16000
amplify: 4262/16000
amplify: 4264/16000
amplify: 4266/16000
amplify: 4268/16000
amplify: 4270/16000
amplify: 4272/16000
amplify: 4274/16000
amplify: 4276/16000
amplify: 4278/16000
amplify: 4280/16000
amplify: 4282/16000
amplify: 4284/16000
amplify: 4286/16000
amplify: 4288/16000
amplify: 4290/16000
amplify: 4292/16000
amplify: 4294/16000
amplify: 4296/16000
amplify: 4298/16000
amplify: 4300/16000
amplify: 4302/16000
amplify: 4304/16000
amplify: 4306/16000
amplify: 4308/16000
amplify: 4310/16000
amplify: 4312/16000
amplify: 4314/16000
amplify: 4316/16000
amplify: 4318/16000
amplify: 4320/16000
amplify: 4322/16000
amplify: 4324/16000
amplify: 4326/16000
amplify: 4328/16000
amplify: 4330/16000
amplify: 4332/16000
amplify: 4334/16000
amplify: 4336/16000
amplify: 4338/16000
amplify: 4340/16000
amplify: 4342/16000
amplify: 4344/16000
amplify: 4346/16000
amplify: 4348/16000
amplify: 4350/16000
amplify: 4352/16000
amplify: 4354/16000
amplify: 4356/16000
amplify: 4358/16000
amplify: 4360/16000
amplify: 4362/16000
amplify: 4364/16000
amplify: 4366/16000
amplify: 4368/16000
amplify: 4370/16000
amplify: 4372/16000
amplify: 4374/16000
amplify: 4376/16000
amplify: 4378/16000
amplify: 4380/16000
amplify: 4382/16000
amplify: 4384/16000
amplify: 4386/16000
amplify: 4388/16000
amplify: 4390/16000
amplify: 4392/16000
amplify: 4394/16000
amplify: 4396/16000
amplify: 4398/16000
amplify: 4400/16000
amplify: 4402/16000
amplify: 4404/16000
amplify: 4406/16000
amplify: 4408/16000
amplify: 4410/16000
amplify: 4412/16000
amplify: 4414/16000
amplify: 4416/16000
amplify: 4418/16000
amplify: 4420/16000
amplify: 4422/16000
amplify: 4424/16000
amplify: 4426/16000
amplify: 4428/16000
amplify: 4430/16000
amplify: 4432/16000
amplify: 4434/16000
amplify: 4436/16000
amplify: 4438/16000
amplify: 4440/16000
amplify: 4442/16000
amplify: 4444/16000
amplify: 4446/16000
amplify: 4448/16000
amplify: 4450/16000
amplify: 4452/16000
amplify: 4454/16000
amplify: 4456/16000
amplify: 4458/16000
amplify: 4460/16000
amplify: 4462/16000
amplify: 4464/16000
amplify: 4466/16000
amplify: 4468/16000
amplify: 4470/16000
amplify: 4472/16000
amplify: 4474/16000
amplify: 4476/16000
amplify: 4478/16000
amplify: 4480/16000
amplify: 4482/16000
amplify: 4484/16000
amplify: 4486/16000
amplify: 4488/16000
amplify: 4490/16000
amplify: 4492/16000
amplify: 4494/16000
amplify: 4496/16000
amplify: 4498/16000
amplify: 4500/16000
amplify: 4502/16000
amplify: 4504/16000
amplify: 4506/16000
amplify: 4508/16000
amplify: 4510/16000
amplify: 4512/16000
amplify: 4514/16000
amplify: 4516/16000
amplify: 4518/16000
amplify: 4520/16000
amplify: 4522/16000
amplify: 4524/16000
amplify: 4526/16000
amplify: 4528/16000
amplify: 4530/16000
amplify: 4532/16000
amplify: 4534/16000
amplify: 4536/16000
amplify: 4538/16000

amplify: 4540/16000
amplify: 4542/16000
amplify: 4544/16000
amplify: 4546/16000
amplify: 4548/16000
amplify: 4550/16000
amplify: 4552/16000
amplify: 4554/16000
amplify: 4556/16000
amplify: 4558/16000
amplify: 4560/16000
amplify: 4562/16000
amplify: 4564/16000
amplify: 4566/16000
amplify: 4568/16000
amplify: 4570/16000
amplify: 4572/16000
amplify: 4574/16000
amplify: 4576/16000
amplify: 4578/16000
amplify: 4580/16000
amplify: 4582/16000
amplify: 4584/16000
amplify: 4586/16000
amplify: 4588/16000
amplify: 4590/16000
amplify: 4592/16000
amplify: 4594/16000
amplify: 4596/16000
amplify: 4598/16000
amplify: 4600/16000
amplify: 4602/16000
amplify: 4604/16000
amplify: 4606/16000
amplify: 4608/16000
amplify: 4610/16000
amplify: 4612/16000
amplify: 4614/16000
amplify: 4616/16000
amplify: 4618/16000
amplify: 4620/16000
amplify: 4622/16000
amplify: 4624/16000
amplify: 4626/16000
amplify: 4628/16000
amplify: 4630/16000
amplify: 4632/16000
amplify: 4634/16000
amplify: 4636/16000
amplify: 4638/16000
amplify: 4640/16000
amplify: 4642/16000
amplify: 4644/16000
amplify: 4646/16000
amplify: 4648/16000
amplify: 4650/16000
amplify: 4652/16000
amplify: 4654/16000
amplify: 4656/16000
amplify: 4658/16000
amplify: 4660/16000
amplify: 4662/16000
amplify: 4664/16000
amplify: 4666/16000
amplify: 4668/16000
amplify: 4670/16000
amplify: 4672/16000
amplify: 4674/16000
amplify: 4676/16000
amplify: 4678/16000
amplify: 4680/16000
amplify: 4682/16000
amplify: 4684/16000
amplify: 4686/16000
amplify: 4688/16000
amplify: 4690/16000
amplify: 4692/16000
amplify: 4694/16000
amplify: 4696/16000
amplify: 4698/16000
amplify: 4700/16000
amplify: 4702/16000
amplify: 4704/16000
amplify: 4706/16000
amplify: 4708/16000
amplify: 4710/16000
amplify: 4712/16000
amplify: 4714/16000
amplify: 4716/16000
amplify: 4718/16000
amplify: 4720/16000
amplify: 4722/16000
amplify: 4724/16000
amplify: 4726/16000
amplify: 4728/16000
amplify: 4730/16000
amplify: 4732/16000
amplify: 4734/16000
amplify: 4736/16000
amplify: 4738/16000
amplify: 4740/16000
amplify: 4742/16000
amplify: 4744/16000
amplify: 4746/16000
amplify: 4748/16000
amplify: 4750/16000
amplify: 4752/16000
amplify: 4754/16000
amplify: 4756/16000
amplify: 4758/16000
amplify: 4760/16000
amplify: 4762/16000
amplify: 4764/16000
amplify: 4766/16000
amplify: 4768/16000
amplify: 4770/16000
amplify: 4772/16000
amplify: 4774/16000
amplify: 4776/16000
amplify: 4778/16000
amplify: 4780/16000
amplify: 4782/16000
amplify: 4784/16000
amplify: 4786/16000
amplify: 4788/16000
amplify: 4790/16000
amplify: 4792/16000
amplify: 4794/16000
amplify: 4796/16000
amplify: 4798/16000
amplify: 4800/16000
amplify: 4802/16000
amplify: 4804/16000
amplify: 4806/16000
amplify: 4808/16000
amplify: 4810/16000
amplify: 4812/16000
amplify: 4814/16000
amplify: 4816/16000
amplify: 4818/16000
amplify: 4820/16000
amplify: 4822/16000
amplify: 4824/16000
amplify: 4826/16000
amplify: 4828/16000
amplify: 4830/16000
amplify: 4832/16000
amplify: 4834/16000
amplify: 4836/16000
amplify: 4838/16000
amplify: 4840/16000
amplify: 4842/16000
amplify: 4844/16000
amplify: 4846/16000
amplify: 4848/16000
amplify: 4850/16000
amplify: 4852/16000
amplify: 4854/16000
amplify: 4856/16000
amplify: 4858/16000
amplify: 4860/16000
amplify: 4862/16000
amplify: 4864/16000
amplify: 4866/16000
amplify: 4868/16000
amplify: 4870/16000
amplify: 4872/16000
amplify: 4874/16000
amplify: 4876/16000
amplify: 4878/16000
amplify: 4880/16000
amplify: 4882/16000
amplify: 4884/16000
amplify: 4886/16000
amplify: 4888/16000
amplify: 4890/16000
amplify: 4892/16000
amplify: 4894/16000
amplify: 4896/16000
amplify: 4898/16000
amplify: 4900/16000
amplify: 4902/16000
amplify: 4904/16000
amplify: 4906/16000
amplify: 4908/16000
amplify: 4910/16000
amplify: 4912/16000
amplify: 4914/16000
amplify: 4916/16000
amplify: 4918/16000
amplify: 4920/16000
amplify: 4922/16000
amplify: 4924/16000
amplify: 4926/16000
amplify: 4928/16000
amplify: 4930/16000
amplify: 4932/16000
amplify: 4934/16000
amplify: 4936/16000
amplify: 4938/16000
amplify: 4940/16000
amplify: 4942/16000
amplify: 4944/16000
amplify: 4946/16000
amplify: 4948/16000
amplify: 4950/16000
amplify: 4952/16000
amplify: 4954/16000
amplify: 4956/16000
amplify: 4958/16000
amplify: 4960/16000
amplify: 4962/16000
amplify: 4964/16000
amplify: 4966/16000
amplify: 4968/16000
amplify: 4970/16000
amplify: 4972/16000
amplify: 4974/16000
amplify: 4976/16000
amplify: 4978/16000
amplify: 4980/16000
amplify: 4982/16000
amplify: 4984/16000
amplify: 4986/16000
amplify: 4988/16000
amplify: 4990/16000
amplify: 4992/16000
amplify: 4994/16000
amplify: 4996/16000
amplify: 4998/16000
amplify: 5000/16000
amplify: 5002/16000
amplify: 5004/16000
amplify: 5006/16000
amplify: 5008/16000
amplify: 5010/16000
amplify: 5012/16000
amplify: 5014/16000
amplify: 5016/16000
amplify: 5018/16000
amplify: 5020/16000
amplify: 5022/16000
amplify: 5024/16000
amplify: 5026/16000
amplify: 5028/16000
amplify: 5030/16000
amplify: 5032/16000
amplify: 5034/16000
amplify: 5036/16000
amplify: 5038/16000
amplify: 5040/16000
amplify: 5042/16000
amplify: 5044/16000
amplify: 5046/16000
amplify: 5048/16000
amplify: 5050/16000
amplify: 5052/16000
amplify: 5054/16000
amplify: 5056/16000
amplify: 5058/16000
amplify: 5060/16000
amplify: 5062/16000
amplify: 5064/16000
amplify: 5066/16000
amplify: 5068/16000
amplify: 5070/16000
amplify: 5072/16000
amplify: 5074/16000
amplify: 5076/16000
amplify: 5078/16000
amplify: 5080/16000
amplify: 5082/16000
amplify: 5084/16000
amplify: 5086/16000
amplify: 5088/16000
amplify: 5090/16000
amplify: 5092/16000
amplify: 5094/16000
amplify: 5096/16000
amplify: 5098/16000
amplify: 5100/16000
amplify: 5102/16000
amplify: 5104/16000
amplify: 5106/16000
amplify: 5108/16000
amplify: 5110/16000
amplify: 5112/16000
amplify: 5114/16000
amplify: 5116/16000
amplify: 5118/16000
amplify: 5120/16000
amplify: 5122/16000
amplify: 5124/16000
amplify: 5126/16000
amplify: 5128/16000
amplify: 5130/16000
amplify: 5132/16000
amplify: 5134/16000
amplify: 5136/16000
amplify: 5138/16000
amplify: 5140/16000
amplify: 5142/16000
amplify: 5144/16000
amplify: 5146/16000
amplify: 5148/16000
amplify: 5150/16000
amplify: 5152/16000
amplify: 5154/16000
amplify: 5156/16000
amplify: 5158/16000
amplify: 5160/16000
amplify: 5162/16000
amplify: 5164/16000
amplify: 5166/16000
amplify: 5168/16000
amplify: 5170/16000
amplify: 5172/16000
amplify: 5174/16000
amplify: 5176/16000
amplify: 5178/16000
amplify: 5180/16000
amplify: 5182/16000
amplify: 5184/16000
amplify: 5186/16000
amplify: 5188/16000
amplify: 5190/16000
amplify: 5192/16000
amplify: 5194/16000
amplify: 5196/16000
amplify: 5198/16000
amplify: 5200/16000
amplify: 5202/16000
amplify: 5204/16000
amplify: 5206/16000
amplify: 5208/16000
amplify: 5210/16000
amplify: 5212/16000
amplify: 5214/16000
amplify: 5216/16000
amplify: 5218/16000
amplify: 5220/16000
amplify: 5222/16000
amplify: 5224/16000
amplify: 5226/16000
amplify: 5228/16000
amplify: 5230/16000
amplify: 5232/16000
amplify: 5234/16000
amplify: 5236/16000
amplify: 5238/16000
amplify: 5240/16000
amplify: 5242/16000
amplify: 5244/16000
amplify: 5246/16000
amplify: 5248/16000
amplify: 5250/16000
amplify: 5252/16000
amplify: 5254/16000
amplify: 5256/16000
amplify: 5258/16000
amplify: 5260/16000
amplify: 5262/16000
amplify: 5264/16000
amplify: 5266/16000
amplify: 5268/16000
amplify: 5270/16000
amplify: 5272/16000
amplify: 5274/16000
amplify: 5276/16000
amplify: 5278/16000
amplify: 5280/16000
amplify: 5282/16000
amplify: 5284/16000
amplify: 5286/16000
amplify: 5288/16000
amplify: 5290/16000
amplify: 5292/16000
amplify: 5294/16000
amplify: 5296/16000
amplify: 5298/16000
amplify: 5300/16000
amplify: 5302/16000
amplify: 5304/16000
amplify: 5306/16000
amplify: 5308/16000
amplify: 5310/16000
amplify: 5312/16000
amplify: 5314/16000
amplify: 5316/16000
amplify: 5318/16000
amplify: 5320/16000
amplify: 5322/16000
amplify: 5324/16000
amplify: 5326/16000
amplify: 5328/16000
amplify: 5330/16000
amplify: 5332/16000
amplify: 5334/16000
amplify: 5336/16000
amplify: 5338/16000
amplify: 5340/16000
amplify: 5342/16000
amplify: 5344/16000
amplify: 5346/16000
amplify: 5348/16000
amplify: 5350/16000
amplify: 5352/16000
amplify: 5354/16000
amplify: 5356/16000
amplify: 5358/16000
amplify: 5360/16000

amplify: 5362/16000
amplify: 5364/16000
amplify: 5366/16000
amplify: 5368/16000
amplify: 5370/16000
amplify: 5372/16000
amplify: 5374/16000
amplify: 5376/16000
amplify: 5378/16000
amplify: 5380/16000
amplify: 5382/16000
amplify: 5384/16000
amplify: 5386/16000
amplify: 5388/16000
amplify: 5390/16000
amplify: 5392/16000
amplify: 5394/16000
amplify: 5396/16000
amplify: 5398/16000
amplify: 5400/16000
amplify: 5402/16000
amplify: 5404/16000
amplify: 5406/16000
amplify: 5408/16000
amplify: 5410/16000
amplify: 5412/16000
amplify: 5414/16000
amplify: 5416/16000
amplify: 5418/16000
amplify: 5420/16000
amplify: 5422/16000
amplify: 5424/16000
amplify: 5426/16000
amplify: 5428/16000
amplify: 5430/16000
amplify: 5432/16000
amplify: 5434/16000
amplify: 5436/16000
amplify: 5438/16000
amplify: 5440/16000
amplify: 5442/16000
amplify: 5444/16000
amplify: 5446/16000
amplify: 5448/16000
amplify: 5450/16000
amplify: 5452/16000
amplify: 5454/16000
amplify: 5456/16000
amplify: 5458/16000
amplify: 5460/16000
amplify: 5462/16000
amplify: 5464/16000
amplify: 5466/16000
amplify: 5468/16000
amplify: 5470/16000
amplify: 5472/16000
amplify: 5474/16000
amplify: 5476/16000
amplify: 5478/16000
amplify: 5480/16000
amplify: 5482/16000
amplify: 5484/16000
amplify: 5486/16000
amplify: 5488/16000
amplify: 5490/16000
amplify: 5492/16000
amplify: 5494/16000
amplify: 5496/16000
amplify: 5498/16000
amplify: 5500/16000
amplify: 5502/16000
amplify: 5504/16000
amplify: 5506/16000
amplify: 5508/16000
amplify: 5510/16000
amplify: 5512/16000
amplify: 5514/16000
amplify: 5516/16000
amplify: 5518/16000
amplify: 5520/16000
amplify: 5522/16000
amplify: 5524/16000
amplify: 5526/16000
amplify: 5528/16000
amplify: 5530/16000
amplify: 5532/16000
amplify: 5534/16000
amplify: 5536/16000
amplify: 5538/16000
amplify: 5540/16000
amplify: 5542/16000
amplify: 5544/16000
amplify: 5546/16000
amplify: 5548/16000
amplify: 5550/16000
amplify: 5552/16000
amplify: 5554/16000
amplify: 5556/16000
amplify: 5558/16000
amplify: 5560/16000
amplify: 5562/16000
amplify: 5564/16000
amplify: 5566/16000
amplify: 5568/16000
amplify: 5570/16000
amplify: 5572/16000
amplify: 5574/16000
amplify: 5576/16000
amplify: 5578/16000
amplify: 5580/16000
amplify: 5582/16000
amplify: 5584/16000
amplify: 5586/16000
amplify: 5588/16000
amplify: 5590/16000
amplify: 5592/16000
amplify: 5594/16000
amplify: 5596/16000
amplify: 5598/16000
amplify: 5600/16000
amplify: 5602/16000
amplify: 5604/16000
amplify: 5606/16000
amplify: 5608/16000
amplify: 5610/16000
amplify: 5612/16000
amplify: 5614/16000
amplify: 5616/16000
amplify: 5618/16000
amplify: 5620/16000
amplify: 5622/16000
amplify: 5624/16000
amplify: 5626/16000
amplify: 5628/16000
amplify: 5630/16000
amplify: 5632/16000
amplify: 5634/16000
amplify: 5636/16000
amplify: 5638/16000
amplify: 5640/16000
amplify: 5642/16000
amplify: 5644/16000
amplify: 5646/16000
amplify: 5648/16000
amplify: 5650/16000
amplify: 5652/16000
amplify: 5654/16000
amplify: 5656/16000
amplify: 5658/16000
amplify: 5660/16000
amplify: 5662/16000
amplify: 5664/16000
amplify: 5666/16000
amplify: 5668/16000
amplify: 5670/16000
amplify: 5672/16000
amplify: 5674/16000
amplify: 5676/16000
amplify: 5678/16000
amplify: 5680/16000
amplify: 5682/16000
amplify: 5684/16000
amplify: 5686/16000
amplify: 5688/16000
amplify: 5690/16000
amplify: 5692/16000
amplify: 5694/16000
amplify: 5696/16000
amplify: 5698/16000
amplify: 5700/16000
amplify: 5702/16000
amplify: 5704/16000
amplify: 5706/16000
amplify: 5708/16000
amplify: 5710/16000
amplify: 5712/16000
amplify: 5714/16000
amplify: 5716/16000
amplify: 5718/16000
amplify: 5720/16000
amplify: 5722/16000
amplify: 5724/16000
amplify: 5726/16000
amplify: 5728/16000
amplify: 5730/16000
amplify: 5732/16000
amplify: 5734/16000
amplify: 5736/16000
amplify: 5738/16000
amplify: 5740/16000
amplify: 5742/16000
amplify: 5744/16000
amplify: 5746/16000
amplify: 5748/16000
amplify: 5750/16000
amplify: 5752/16000
amplify: 5754/16000
amplify: 5756/16000
amplify: 5758/16000
amplify: 5760/16000
amplify: 5762/16000
amplify: 5764/16000
amplify: 5766/16000
amplify: 5768/16000
amplify: 5770/16000
amplify: 5772/16000
amplify: 5774/16000
amplify: 5776/16000
amplify: 5778/16000
amplify: 5780/16000
amplify: 5782/16000
amplify: 5784/16000
amplify: 5786/16000
amplify: 5788/16000
amplify: 5790/16000
amplify: 5792/16000
amplify: 5794/16000
amplify: 5796/16000
amplify: 5798/16000
amplify: 5800/16000
amplify: 5802/16000
amplify: 5804/16000
amplify: 5806/16000
amplify: 5808/16000
amplify: 5810/16000
amplify: 5812/16000
amplify: 5814/16000
amplify: 5816/16000
amplify: 5818/16000
amplify: 5820/16000
amplify: 5822/16000
amplify: 5824/16000
amplify: 5826/16000
amplify: 5828/16000
amplify: 5830/16000
amplify: 5832/16000
amplify: 5834/16000
amplify: 5836/16000
amplify: 5838/16000
amplify: 5840/16000
amplify: 5842/16000
amplify: 5844/16000
amplify: 5846/16000
amplify: 5848/16000
amplify: 5850/16000
amplify: 5852/16000
amplify: 5854/16000
amplify: 5856/16000
amplify: 5858/16000
amplify: 5860/16000
amplify: 5862/16000
amplify: 5864/16000
amplify: 5866/16000
amplify: 5868/16000
amplify: 5870/16000
amplify: 5872/16000
amplify: 5874/16000
amplify: 5876/16000
amplify: 5878/16000
amplify: 5880/16000
amplify: 5882/16000
amplify: 5884/16000
amplify: 5886/16000
amplify: 5888/16000
amplify: 5890/16000
amplify: 5892/16000
amplify: 5894/16000
amplify: 5896/16000
amplify: 5898/16000
amplify: 5900/16000
amplify: 5902/16000
amplify: 5904/16000
amplify: 5906/16000
amplify: 5908/16000
amplify: 5910/16000
amplify: 5912/16000
amplify: 5914/16000
amplify: 5916/16000
amplify: 5918/16000
amplify: 5920/16000
amplify: 5922/16000
amplify: 5924/16000
amplify: 5926/16000
amplify: 5928/16000
amplify: 5930/16000
amplify: 5932/16000
amplify: 5934/16000
amplify: 5936/16000
amplify: 5938/16000
amplify: 5940/16000
amplify: 5942/16000
amplify: 5944/16000
amplify: 5946/16000
amplify: 5948/16000
amplify: 5950/16000
amplify: 5952/16000
amplify: 5954/16000
amplify: 5956/16000
amplify: 5958/16000
amplify: 5960/16000
amplify: 5962/16000
amplify: 5964/16000
amplify: 5966/16000
amplify: 5968/16000
amplify: 5970/16000
amplify: 5972/16000
amplify: 5974/16000
amplify: 5976/16000
amplify: 5978/16000
amplify: 5980/16000
amplify: 5982/16000
amplify: 5984/16000
amplify: 5986/16000
amplify: 5988/16000
amplify: 5990/16000
amplify: 5992/16000
amplify: 5994/16000
amplify: 5996/16000
amplify: 5998/16000
amplify: 6000/16000
amplify: 6002/16000
amplify: 6004/16000
amplify: 6006/16000
amplify: 6008/16000
amplify: 6010/16000
amplify: 6012/16000
amplify: 6014/16000
amplify: 6016/16000
amplify: 6018/16000
amplify: 6020/16000
amplify: 6022/16000
amplify: 6024/16000
amplify: 6026/16000
amplify: 6028/16000
amplify: 6030/16000
amplify: 6032/16000
amplify: 6034/16000
amplify: 6036/16000
amplify: 6038/16000
amplify: 6040/16000
amplify: 6042/16000
amplify: 6044/16000
amplify: 6046/16000
amplify: 6048/16000
amplify: 6050/16000
amplify: 6052/16000
amplify: 6054/16000
amplify: 6056/16000
amplify: 6058/16000
amplify: 6060/16000
amplify: 6062/16000
amplify: 6064/16000
amplify: 6066/16000
amplify: 6068/16000
amplify: 6070/16000
amplify: 6072/16000
amplify: 6074/16000
amplify: 6076/16000
amplify: 6078/16000
amplify: 6080/16000
amplify: 6082/16000
amplify: 6084/16000
amplify: 6086/16000
amplify: 6088/16000
amplify: 6090/16000
amplify: 6092/16000
amplify: 6094/16000
amplify: 6096/16000
amplify: 6098/16000
amplify: 6100/16000
amplify: 6102/16000
amplify: 6104/16000
amplify: 6106/16000
amplify: 6108/16000
amplify: 6110/16000
amplify: 6112/16000
amplify: 6114/16000
amplify: 6116/16000
amplify: 6118/16000
amplify: 6120/16000
amplify: 6122/16000
amplify: 6124/16000
amplify: 6126/16000
amplify: 6128/16000
amplify: 6130/16000
amplify: 6132/16000
amplify: 6134/16000
amplify: 6136/16000
amplify: 6138/16000
amplify: 6140/16000
amplify: 6142/16000
amplify: 6144/16000
amplify: 6146/16000
amplify: 6148/16000
amplify: 6150/16000
amplify: 6152/16000
amplify: 6154/16000
amplify: 6156/16000
amplify: 6158/16000
amplify: 6160/16000
amplify: 6162/16000
amplify: 6164/16000
amplify: 6166/16000
amplify: 6168/16000
amplify: 6170/16000
amplify: 6172/16000
amplify: 6174/16000
amplify: 6176/16000
amplify: 6178/16000
amplify: 6180/16000

amplify: 6182/16000
amplify: 6184/16000
amplify: 6186/16000
amplify: 6188/16000
amplify: 6190/16000
amplify: 6192/16000
amplify: 6194/16000
amplify: 6196/16000
amplify: 6198/16000
amplify: 6200/16000
amplify: 6202/16000
amplify: 6204/16000
amplify: 6206/16000
amplify: 6208/16000
amplify: 6210/16000
amplify: 6212/16000
amplify: 6214/16000
amplify: 6216/16000
amplify: 6218/16000
amplify: 6220/16000
amplify: 6222/16000
amplify: 6224/16000
amplify: 6226/16000
amplify: 6228/16000
amplify: 6230/16000
amplify: 6232/16000
amplify: 6234/16000
amplify: 6236/16000
amplify: 6238/16000
amplify: 6240/16000
amplify: 6242/16000
amplify: 6244/16000
amplify: 6246/16000
amplify: 6248/16000
amplify: 6250/16000
amplify: 6252/16000
amplify: 6254/16000
amplify: 6256/16000
amplify: 6258/16000
amplify: 6260/16000
amplify: 6262/16000
amplify: 6264/16000
amplify: 6266/16000
amplify: 6268/16000
amplify: 6270/16000
amplify: 6272/16000
amplify: 6274/16000
amplify: 6276/16000
amplify: 6278/16000
amplify: 6280/16000
amplify: 6282/16000
amplify: 6284/16000
amplify: 6286/16000
amplify: 6288/16000
amplify: 6290/16000
amplify: 6292/16000
amplify: 6294/16000
amplify: 6296/16000
amplify: 6298/16000
amplify: 6300/16000
amplify: 6302/16000
amplify: 6304/16000
amplify: 6306/16000
amplify: 6308/16000
amplify: 6310/16000
amplify: 6312/16000
amplify: 6314/16000
amplify: 6316/16000
amplify: 6318/16000
amplify: 6320/16000
amplify: 6322/16000
amplify: 6324/16000
amplify: 6326/16000
amplify: 6328/16000
amplify: 6330/16000
amplify: 6332/16000
amplify: 6334/16000
amplify: 6336/16000
amplify: 6338/16000
amplify: 6340/16000
amplify: 6342/16000
amplify: 6344/16000
amplify: 6346/16000
amplify: 6348/16000
amplify: 6350/16000
amplify: 6352/16000
amplify: 6354/16000
amplify: 6356/16000
amplify: 6358/16000
amplify: 6360/16000
amplify: 6362/16000
amplify: 6364/16000
amplify: 6366/16000
amplify: 6368/16000
amplify: 6370/16000
amplify: 6372/16000
amplify: 6374/16000
amplify: 6376/16000
amplify: 6378/16000
amplify: 6380/16000
amplify: 6382/16000
amplify: 6384/16000
amplify: 6386/16000
amplify: 6388/16000
amplify: 6390/16000
amplify: 6392/16000
amplify: 6394/16000
amplify: 6396/16000
amplify: 6398/16000
amplify: 6400/16000
amplify: 6402/16000
amplify: 6404/16000
amplify: 6406/16000
amplify: 6408/16000
amplify: 6410/16000
amplify: 6412/16000
amplify: 6414/16000
amplify: 6416/16000
amplify: 6418/16000
amplify: 6420/16000
amplify: 6422/16000
amplify: 6424/16000
amplify: 6426/16000
amplify: 6428/16000
amplify: 6430/16000
amplify: 6432/16000
amplify: 6434/16000
amplify: 6436/16000
amplify: 6438/16000
amplify: 6440/16000
amplify: 6442/16000
amplify: 6444/16000
amplify: 6446/16000
amplify: 6448/16000
amplify: 6450/16000
amplify: 6452/16000
amplify: 6454/16000
amplify: 6456/16000
amplify: 6458/16000
amplify: 6460/16000
amplify: 6462/16000
amplify: 6464/16000
amplify: 6466/16000
amplify: 6468/16000
amplify: 6470/16000
amplify: 6472/16000
amplify: 6474/16000
amplify: 6476/16000
amplify: 6478/16000
amplify: 6480/16000
amplify: 6482/16000
amplify: 6484/16000
amplify: 6486/16000
amplify: 6488/16000
amplify: 6490/16000
amplify: 6492/16000
amplify: 6494/16000
amplify: 6496/16000
amplify: 6498/16000
amplify: 6500/16000
amplify: 6502/16000
amplify: 6504/16000
amplify: 6506/16000
amplify: 6508/16000
amplify: 6510/16000
amplify: 6512/16000
amplify: 6514/16000
amplify: 6516/16000
amplify: 6518/16000
amplify: 6520/16000
amplify: 6522/16000
amplify: 6524/16000
amplify: 6526/16000
amplify: 6528/16000
amplify: 6530/16000
amplify: 6532/16000
amplify: 6534/16000
amplify: 6536/16000
amplify: 6538/16000
amplify: 6540/16000
amplify: 6542/16000
amplify: 6544/16000
amplify: 6546/16000
amplify: 6548/16000
amplify: 6550/16000
amplify: 6552/16000
amplify: 6554/16000
amplify: 6556/16000
amplify: 6558/16000
amplify: 6560/16000
amplify: 6562/16000
amplify: 6564/16000
amplify: 6566/16000
amplify: 6568/16000
amplify: 6570/16000
amplify: 6572/16000
amplify: 6574/16000
amplify: 6576/16000
amplify: 6578/16000
amplify: 6580/16000
amplify: 6582/16000
amplify: 6584/16000
amplify: 6586/16000
amplify: 6588/16000
amplify: 6590/16000
amplify: 6592/16000
amplify: 6594/16000
amplify: 6596/16000
amplify: 6598/16000
amplify: 6600/16000
amplify: 6602/16000
amplify: 6604/16000
amplify: 6606/16000
amplify: 6608/16000
amplify: 6610/16000
amplify: 6612/16000
amplify: 6614/16000
amplify: 6616/16000
amplify: 6618/16000
amplify: 6620/16000
amplify: 6622/16000
amplify: 6624/16000
amplify: 6626/16000
amplify: 6628/16000
amplify: 6630/16000
amplify: 6632/16000
amplify: 6634/16000
amplify: 6636/16000
amplify: 6638/16000
amplify: 6640/16000
amplify: 6642/16000
amplify: 6644/16000
amplify: 6646/16000
amplify: 6648/16000
amplify: 6650/16000
amplify: 6652/16000
amplify: 6654/16000
amplify: 6656/16000
amplify: 6658/16000
amplify: 6660/16000
amplify: 6662/16000
amplify: 6664/16000
amplify: 6666/16000
amplify: 6668/16000
amplify: 6670/16000
amplify: 6672/16000
amplify: 6674/16000
amplify: 6676/16000
amplify: 6678/16000
amplify: 6680/16000
amplify: 6682/16000
amplify: 6684/16000
amplify: 6686/16000
amplify: 6688/16000
amplify: 6690/16000
amplify: 6692/16000
amplify: 6694/16000
amplify: 6696/16000
amplify: 6698/16000
amplify: 6700/16000
amplify: 6702/16000
amplify: 6704/16000
amplify: 6706/16000
amplify: 6708/16000
amplify: 6710/16000
amplify: 6712/16000
amplify: 6714/16000
amplify: 6716/16000
amplify: 6718/16000
amplify: 6720/16000
amplify: 6722/16000
amplify: 6724/16000
amplify: 6726/16000
amplify: 6728/16000
amplify: 6730/16000
amplify: 6732/16000
amplify: 6734/16000
amplify: 6736/16000
amplify: 6738/16000
amplify: 6740/16000
amplify: 6742/16000
amplify: 6744/16000
amplify: 6746/16000
amplify: 6748/16000
amplify: 6750/16000
amplify: 6752/16000
amplify: 6754/16000
amplify: 6756/16000
amplify: 6758/16000
amplify: 6760/16000
amplify: 6762/16000
amplify: 6764/16000
amplify: 6766/16000
amplify: 6768/16000
amplify: 6770/16000
amplify: 6772/16000
amplify: 6774/16000
amplify: 6776/16000
amplify: 6778/16000
amplify: 6780/16000
amplify: 6782/16000
amplify: 6784/16000
amplify: 6786/16000
amplify: 6788/16000
amplify: 6790/16000
amplify: 6792/16000
amplify: 6794/16000
amplify: 6796/16000
amplify: 6798/16000
amplify: 6800/16000
amplify: 6802/16000
amplify: 6804/16000
amplify: 6806/16000
amplify: 6808/16000
amplify: 6810/16000
amplify: 6812/16000
amplify: 6814/16000
amplify: 6816/16000
amplify: 6818/16000
amplify: 6820/16000
amplify: 6822/16000
amplify: 6824/16000
amplify: 6826/16000
amplify: 6828/16000
amplify: 6830/16000
amplify: 6832/16000
amplify: 6834/16000
amplify: 6836/16000
amplify: 6838/16000
amplify: 6840/16000
amplify: 6842/16000
amplify: 6844/16000
amplify: 6846/16000
amplify: 6848/16000
amplify: 6850/16000
amplify: 6852/16000
amplify: 6854/16000
amplify: 6856/16000
amplify: 6858/16000
amplify: 6860/16000
amplify: 6862/16000
amplify: 6864/16000
amplify: 6866/16000
amplify: 6868/16000
amplify: 6870/16000
amplify: 6872/16000
amplify: 6874/16000
amplify: 6876/16000
amplify: 6878/16000
amplify: 6880/16000
amplify: 6882/16000
amplify: 6884/16000
amplify: 6886/16000
amplify: 6888/16000
amplify: 6890/16000
amplify: 6892/16000
amplify: 6894/16000
amplify: 6896/16000
amplify: 6898/16000
amplify: 6900/16000
amplify: 6902/16000
amplify: 6904/16000
amplify: 6906/16000
amplify: 6908/16000
amplify: 6910/16000
amplify: 6912/16000
amplify: 6914/16000
amplify: 6916/16000
amplify: 6918/16000
amplify: 6920/16000
amplify: 6922/16000
amplify: 6924/16000
amplify: 6926/16000
amplify: 6928/16000
amplify: 6930/16000
amplify: 6932/16000
amplify: 6934/16000
amplify: 6936/16000
amplify: 6938/16000
amplify: 6940/16000
amplify: 6942/16000
amplify: 6944/16000
amplify: 6946/16000
amplify: 6948/16000
amplify: 6950/16000
amplify: 6952/16000
amplify: 6954/16000
amplify: 6956/16000
amplify: 6958/16000
amplify: 6960/16000
amplify: 6962/16000
amplify: 6964/16000
amplify: 6966/16000
amplify: 6968/16000
amplify: 6970/16000
amplify: 6972/16000
amplify: 6974/16000
amplify: 6976/16000
amplify: 6978/16000
amplify: 6980/16000
amplify: 6982/16000
amplify: 6984/16000
amplify: 6986/16000
amplify: 6988/16000
amplify: 6990/16000
amplify: 6992/16000
amplify: 6994/16000
amplify: 6996/16000
amplify: 6998/16000
amplify: 7000/16000
amplify: 7002/16000

amplify: 7004/16000
amplify: 7006/16000
amplify: 7008/16000
amplify: 7010/16000
amplify: 7012/16000
amplify: 7014/16000
amplify: 7016/16000
amplify: 7018/16000
amplify: 7020/16000
amplify: 7022/16000
amplify: 7024/16000
amplify: 7026/16000
amplify: 7028/16000
amplify: 7030/16000
amplify: 7032/16000
amplify: 7034/16000
amplify: 7036/16000
amplify: 7038/16000
amplify: 7040/16000
amplify: 7042/16000
amplify: 7044/16000
amplify: 7046/16000
amplify: 7048/16000
amplify: 7050/16000
amplify: 7052/16000
amplify: 7054/16000
amplify: 7056/16000
amplify: 7058/16000
amplify: 7060/16000
amplify: 7062/16000
amplify: 7064/16000
amplify: 7066/16000
amplify: 7068/16000
amplify: 7070/16000
amplify: 7072/16000
amplify: 7074/16000
amplify: 7076/16000
amplify: 7078/16000
amplify: 7080/16000
amplify: 7082/16000
amplify: 7084/16000
amplify: 7086/16000
amplify: 7088/16000
amplify: 7090/16000
amplify: 7092/16000
amplify: 7094/16000
amplify: 7096/16000
amplify: 7098/16000
amplify: 7100/16000
amplify: 7102/16000
amplify: 7104/16000
amplify: 7106/16000
amplify: 7108/16000
amplify: 7110/16000
amplify: 7112/16000
amplify: 7114/16000
amplify: 7116/16000
amplify: 7118/16000
amplify: 7120/16000
amplify: 7122/16000
amplify: 7124/16000
amplify: 7126/16000
amplify: 7128/16000
amplify: 7130/16000
amplify: 7132/16000
amplify: 7134/16000
amplify: 7136/16000
amplify: 7138/16000
amplify: 7140/16000
amplify: 7142/16000
amplify: 7144/16000
amplify: 7146/16000
amplify: 7148/16000
amplify: 7150/16000
amplify: 7152/16000
amplify: 7154/16000
amplify: 7156/16000
amplify: 7158/16000
amplify: 7160/16000
amplify: 7162/16000
amplify: 7164/16000
amplify: 7166/16000
amplify: 7168/16000
amplify: 7170/16000
amplify: 7172/16000
amplify: 7174/16000
amplify: 7176/16000
amplify: 7178/16000
amplify: 7180/16000
amplify: 7182/16000
amplify: 7184/16000
amplify: 7186/16000
amplify: 7188/16000
amplify: 7190/16000
amplify: 7192/16000
amplify: 7194/16000
amplify: 7196/16000
amplify: 7198/16000
amplify: 7200/16000
amplify: 7202/16000
amplify: 7204/16000
amplify: 7206/16000
amplify: 7208/16000
amplify: 7210/16000
amplify: 7212/16000
amplify: 7214/16000
amplify: 7216/16000
amplify: 7218/16000
amplify: 7220/16000
amplify: 7222/16000
amplify: 7224/16000
amplify: 7226/16000
amplify: 7228/16000
amplify: 7230/16000
amplify: 7232/16000
amplify: 7234/16000
amplify: 7236/16000
amplify: 7238/16000
amplify: 7240/16000
amplify: 7242/16000
amplify: 7244/16000
amplify: 7246/16000
amplify: 7248/16000
amplify: 7250/16000
amplify: 7252/16000
amplify: 7254/16000
amplify: 7256/16000
amplify: 7258/16000
amplify: 7260/16000
amplify: 7262/16000
amplify: 7264/16000
amplify: 7266/16000
amplify: 7268/16000
amplify: 7270/16000
amplify: 7272/16000
amplify: 7274/16000
amplify: 7276/16000
amplify: 7278/16000
amplify: 7280/16000
amplify: 7282/16000
amplify: 7284/16000
amplify: 7286/16000
amplify: 7288/16000
amplify: 7290/16000
amplify: 7292/16000
amplify: 7294/16000
amplify: 7296/16000
amplify: 7298/16000
amplify: 7300/16000
amplify: 7302/16000
amplify: 7304/16000
amplify: 7306/16000
amplify: 7308/16000
amplify: 7310/16000
amplify: 7312/16000
amplify: 7314/16000
amplify: 7316/16000
amplify: 7318/16000
amplify: 7320/16000
amplify: 7322/16000
amplify: 7324/16000
amplify: 7326/16000
amplify: 7328/16000
amplify: 7330/16000
amplify: 7332/16000
amplify: 7334/16000
amplify: 7336/16000
amplify: 7338/16000
amplify: 7340/16000
amplify: 7342/16000
amplify: 7344/16000
amplify: 7346/16000
amplify: 7348/16000
amplify: 7350/16000
amplify: 7352/16000
amplify: 7354/16000
amplify: 7356/16000
amplify: 7358/16000
amplify: 7360/16000
amplify: 7362/16000
amplify: 7364/16000
amplify: 7366/16000
amplify: 7368/16000
amplify: 7370/16000
amplify: 7372/16000
amplify: 7374/16000
amplify: 7376/16000
amplify: 7378/16000
amplify: 7380/16000
amplify: 7382/16000
amplify: 7384/16000
amplify: 7386/16000
amplify: 7388/16000
amplify: 7390/16000
amplify: 7392/16000
amplify: 7394/16000
amplify: 7396/16000
amplify: 7398/16000
amplify: 7400/16000
amplify: 7402/16000
amplify: 7404/16000
amplify: 7406/16000
amplify: 7408/16000
amplify: 7410/16000
amplify: 7412/16000
amplify: 7414/16000
amplify: 7416/16000
amplify: 7418/16000
amplify: 7420/16000
amplify: 7422/16000
amplify: 7424/16000
amplify: 7426/16000
amplify: 7428/16000
amplify: 7430/16000
amplify: 7432/16000
amplify: 7434/16000
amplify: 7436/16000
amplify: 7438/16000
amplify: 7440/16000
amplify: 7442/16000
amplify: 7444/16000
amplify: 7446/16000
amplify: 7448/16000
amplify: 7450/16000
amplify: 7452/16000
amplify: 7454/16000
amplify: 7456/16000
amplify: 7458/16000
amplify: 7460/16000
amplify: 7462/16000
amplify: 7464/16000
amplify: 7466/16000
amplify: 7468/16000
amplify: 7470/16000
amplify: 7472/16000
amplify: 7474/16000
amplify: 7476/16000
amplify: 7478/16000
amplify: 7480/16000
amplify: 7482/16000
amplify: 7484/16000
amplify: 7486/16000
amplify: 7488/16000
amplify: 7490/16000
amplify: 7492/16000
amplify: 7494/16000
amplify: 7496/16000
amplify: 7498/16000
amplify: 7500/16000
amplify: 7502/16000
amplify: 7504/16000
amplify: 7506/16000
amplify: 7508/16000
amplify: 7510/16000
amplify: 7512/16000
amplify: 7514/16000
amplify: 7516/16000
amplify: 7518/16000
amplify: 7520/16000
amplify: 7522/16000
amplify: 7524/16000
amplify: 7526/16000
amplify: 7528/16000
amplify: 7530/16000
amplify: 7532/16000
amplify: 7534/16000
amplify: 7536/16000
amplify: 7538/16000
amplify: 7540/16000
amplify: 7542/16000
amplify: 7544/16000
amplify: 7546/16000
amplify: 7548/16000
amplify: 7550/16000
amplify: 7552/16000
amplify: 7554/16000
amplify: 7556/16000
amplify: 7558/16000
amplify: 7560/16000
amplify: 7562/16000
amplify: 7564/16000
amplify: 7566/16000
amplify: 7568/16000
amplify: 7570/16000
amplify: 7572/16000
amplify: 7574/16000
amplify: 7576/16000
amplify: 7578/16000
amplify: 7580/16000
amplify: 7582/16000
amplify: 7584/16000
amplify: 7586/16000
amplify: 7588/16000
amplify: 7590/16000
amplify: 7592/16000
amplify: 7594/16000
amplify: 7596/16000
amplify: 7598/16000
amplify: 7600/16000
amplify: 7602/16000
amplify: 7604/16000
amplify: 7606/16000
amplify: 7608/16000
amplify: 7610/16000
amplify: 7612/16000
amplify: 7614/16000
amplify: 7616/16000
amplify: 7618/16000
amplify: 7620/16000
amplify: 7622/16000
amplify: 7624/16000
amplify: 7626/16000
amplify: 7628/16000
amplify: 7630/16000
amplify: 7632/16000
amplify: 7634/16000
amplify: 7636/16000
amplify: 7638/16000
amplify: 7640/16000
amplify: 7642/16000
amplify: 7644/16000
amplify: 7646/16000
amplify: 7648/16000
amplify: 7650/16000
amplify: 7652/16000
amplify: 7654/16000
amplify: 7656/16000
amplify: 7658/16000
amplify: 7660/16000
amplify: 7662/16000
amplify: 7664/16000
amplify: 7666/16000
amplify: 7668/16000
amplify: 7670/16000
amplify: 7672/16000
amplify: 7674/16000
amplify: 7676/16000
amplify: 7678/16000
amplify: 7680/16000
amplify: 7682/16000
amplify: 7684/16000
amplify: 7686/16000
amplify: 7688/16000
amplify: 7690/16000
amplify: 7692/16000
amplify: 7694/16000
amplify: 7696/16000
amplify: 7698/16000
amplify: 7700/16000
amplify: 7702/16000
amplify: 7704/16000
amplify: 7706/16000
amplify: 7708/16000
amplify: 7710/16000
amplify: 7712/16000
amplify: 7714/16000
amplify: 7716/16000
amplify: 7718/16000
amplify: 7720/16000
amplify: 7722/16000
amplify: 7724/16000
amplify: 7726/16000
amplify: 7728/16000
amplify: 7730/16000
amplify: 7732/16000
amplify: 7734/16000
amplify: 7736/16000
amplify: 7738/16000
amplify: 7740/16000
amplify: 7742/16000
amplify: 7744/16000
amplify: 7746/16000
amplify: 7748/16000
amplify: 7750/16000
amplify: 7752/16000
amplify: 7754/16000
amplify: 7756/16000
amplify: 7758/16000
amplify: 7760/16000
amplify: 7762/16000
amplify: 7764/16000
amplify: 7766/16000
amplify: 7768/16000
amplify: 7770/16000
amplify: 7772/16000
amplify: 7774/16000
amplify: 7776/16000
amplify: 7778/16000
amplify: 7780/16000
amplify: 7782/16000
amplify: 7784/16000
amplify: 7786/16000
amplify: 7788/16000
amplify: 7790/16000
amplify: 7792/16000
amplify: 7794/16000
amplify: 7796/16000
amplify: 7798/16000
amplify: 7800/16000
amplify: 7802/16000
amplify: 7804/16000
amplify: 7806/16000
amplify: 7808/16000
amplify: 7810/16000
amplify: 7812/16000
amplify: 7814/16000
amplify: 7816/16000
amplify: 7818/16000
amplify: 7820/16000
amplify: 7822/16000

amplify: 7824/16000
amplify: 7826/16000
amplify: 7828/16000
amplify: 7830/16000
amplify: 7832/16000
amplify: 7834/16000
amplify: 7836/16000
amplify: 7838/16000
amplify: 7840/16000
amplify: 7842/16000
amplify: 7844/16000
amplify: 7846/16000
amplify: 7848/16000
amplify: 7850/16000
amplify: 7852/16000
amplify: 7854/16000
amplify: 7856/16000
amplify: 7858/16000
amplify: 7860/16000
amplify: 7862/16000
amplify: 7864/16000
amplify: 7866/16000
amplify: 7868/16000
amplify: 7870/16000
amplify: 7872/16000
amplify: 7874/16000
amplify: 7876/16000
amplify: 7878/16000
amplify: 7880/16000
amplify: 7882/16000
amplify: 7884/16000
amplify: 7886/16000
amplify: 7888/16000
amplify: 7890/16000
amplify: 7892/16000
amplify: 7894/16000
amplify: 7896/16000
amplify: 7898/16000
amplify: 7900/16000
amplify: 7902/16000
amplify: 7904/16000
amplify: 7906/16000
amplify: 7908/16000
amplify: 7910/16000
amplify: 7912/16000
amplify: 7914/16000
amplify: 7916/16000
amplify: 7918/16000
amplify: 7920/16000
amplify: 7922/16000
amplify: 7924/16000
amplify: 7926/16000
amplify: 7928/16000
amplify: 7930/16000
amplify: 7932/16000
amplify: 7934/16000
amplify: 7936/16000
amplify: 7938/16000
amplify: 7940/16000
amplify: 7942/16000
amplify: 7944/16000
amplify: 7946/16000
amplify: 7948/16000
amplify: 7950/16000
amplify: 7952/16000
amplify: 7954/16000
amplify: 7956/16000
amplify: 7958/16000
amplify: 7960/16000
amplify: 7962/16000
amplify: 7964/16000
amplify: 7966/16000
amplify: 7968/16000
amplify: 7970/16000
amplify: 7972/16000
amplify: 7974/16000
amplify: 7976/16000
amplify: 7978/16000
amplify: 7980/16000
amplify: 7982/16000
amplify: 7984/16000
amplify: 7986/16000
amplify: 7988/16000
amplify: 7990/16000
amplify: 7992/16000
amplify: 7994/16000
amplify: 7996/16000
amplify: 7998/16000
amplify: 8000/16000
amplify: 8002/16000
amplify: 8004/16000
amplify: 8006/16000
amplify: 8008/16000
amplify: 8010/16000
amplify: 8012/16000
amplify: 8014/16000
amplify: 8016/16000
amplify: 8018/16000
amplify: 8020/16000
amplify: 8022/16000
amplify: 8024/16000
amplify: 8026/16000
amplify: 8028/16000
amplify: 8030/16000
amplify: 8032/16000
amplify: 8034/16000
amplify: 8036/16000
amplify: 8038/16000
amplify: 8040/16000
amplify: 8042/16000
amplify: 8044/16000
amplify: 8046/16000
amplify: 8048/16000
amplify: 8050/16000
amplify: 8052/16000
amplify: 8054/16000
amplify: 8056/16000
amplify: 8058/16000
amplify: 8060/16000
amplify: 8062/16000
amplify: 8064/16000
amplify: 8066/16000
amplify: 8068/16000
amplify: 8070/16000
amplify: 8072/16000
amplify: 8074/16000
amplify: 8076/16000
amplify: 8078/16000
amplify: 8080/16000
amplify: 8082/16000
amplify: 8084/16000
amplify: 8086/16000
amplify: 8088/16000
amplify: 8090/16000
amplify: 8092/16000
amplify: 8094/16000
amplify: 8096/16000
amplify: 8098/16000
amplify: 8100/16000
amplify: 8102/16000
amplify: 8104/16000
amplify: 8106/16000
amplify: 8108/16000
amplify: 8110/16000
amplify: 8112/16000
amplify: 8114/16000
amplify: 8116/16000
amplify: 8118/16000
amplify: 8120/16000
amplify: 8122/16000
amplify: 8124/16000
amplify: 8126/16000
amplify: 8128/16000
amplify: 8130/16000
amplify: 8132/16000
amplify: 8134/16000
amplify: 8136/16000
amplify: 8138/16000
amplify: 8140/16000
amplify: 8142/16000
amplify: 8144/16000
amplify: 8146/16000
amplify: 8148/16000
amplify: 8150/16000
amplify: 8152/16000
amplify: 8154/16000
amplify: 8156/16000
amplify: 8158/16000
amplify: 8160/16000
amplify: 8162/16000
amplify: 8164/16000
amplify: 8166/16000
amplify: 8168/16000
amplify: 8170/16000
amplify: 8172/16000
amplify: 8174/16000
amplify: 8176/16000
amplify: 8178/16000
amplify: 8180/16000
amplify: 8182/16000
amplify: 8184/16000
amplify: 8186/16000
amplify: 8188/16000
amplify: 8190/16000
amplify: 8192/16000
amplify: 8194/16000
amplify: 8196/16000
amplify: 8198/16000
amplify: 8200/16000
amplify: 8202/16000
amplify: 8204/16000
amplify: 8206/16000
amplify: 8208/16000
amplify: 8210/16000
amplify: 8212/16000
amplify: 8214/16000
amplify: 8216/16000
amplify: 8218/16000
amplify: 8220/16000
amplify: 8222/16000
amplify: 8224/16000
amplify: 8226/16000
amplify: 8228/16000
amplify: 8230/16000
amplify: 8232/16000
amplify: 8234/16000
amplify: 8236/16000
amplify: 8238/16000
amplify: 8240/16000
amplify: 8242/16000
amplify: 8244/16000
amplify: 8246/16000
amplify: 8248/16000
amplify: 8250/16000
amplify: 8252/16000
amplify: 8254/16000
amplify: 8256/16000
amplify: 8258/16000
amplify: 8260/16000
amplify: 8262/16000
amplify: 8264/16000
amplify: 8266/16000
amplify: 8268/16000
amplify: 8270/16000
amplify: 8272/16000
amplify: 8274/16000
amplify: 8276/16000
amplify: 8278/16000
amplify: 8280/16000
amplify: 8282/16000
amplify: 8284/16000
amplify: 8286/16000
amplify: 8288/16000
amplify: 8290/16000
amplify: 8292/16000
amplify: 8294/16000
amplify: 8296/16000
amplify: 8298/16000
amplify: 8300/16000
amplify: 8302/16000
amplify: 8304/16000
amplify: 8306/16000
amplify: 8308/16000
amplify: 8310/16000
amplify: 8312/16000
amplify: 8314/16000
amplify: 8316/16000
amplify: 8318/16000
amplify: 8320/16000
amplify: 8322/16000
amplify: 8324/16000
amplify: 8326/16000
amplify: 8328/16000
amplify: 8330/16000
amplify: 8332/16000
amplify: 8334/16000
amplify: 8336/16000
amplify: 8338/16000
amplify: 8340/16000
amplify: 8342/16000
amplify: 8344/16000
amplify: 8346/16000
amplify: 8348/16000
amplify: 8350/16000
amplify: 8352/16000
amplify: 8354/16000
amplify: 8356/16000
amplify: 8358/16000
amplify: 8360/16000
amplify: 8362/16000
amplify: 8364/16000
amplify: 8366/16000
amplify: 8368/16000
amplify: 8370/16000
amplify: 8372/16000
amplify: 8374/16000
amplify: 8376/16000
amplify: 8378/16000
amplify: 8380/16000
amplify: 8382/16000
amplify: 8384/16000
amplify: 8386/16000
amplify: 8388/16000
amplify: 8390/16000
amplify: 8392/16000
amplify: 8394/16000
amplify: 8396/16000
amplify: 8398/16000
amplify: 8400/16000
amplify: 8402/16000
amplify: 8404/16000
amplify: 8406/16000
amplify: 8408/16000
amplify: 8410/16000
amplify: 8412/16000
amplify: 8414/16000
amplify: 8416/16000
amplify: 8418/16000
amplify: 8420/16000
amplify: 8422/16000
amplify: 8424/16000
amplify: 8426/16000
amplify: 8428/16000
amplify: 8430/16000
amplify: 8432/16000
amplify: 8434/16000
amplify: 8436/16000
amplify: 8438/16000
amplify: 8440/16000
amplify: 8442/16000
amplify: 8444/16000
amplify: 8446/16000
amplify: 8448/16000
amplify: 8450/16000
amplify: 8452/16000
amplify: 8454/16000
amplify: 8456/16000
amplify: 8458/16000
amplify: 8460/16000
amplify: 8462/16000
amplify: 8464/16000
amplify: 8466/16000
amplify: 8468/16000
amplify: 8470/16000
amplify: 8472/16000
amplify: 8474/16000
amplify: 8476/16000
amplify: 8478/16000
amplify: 8480/16000
amplify: 8482/16000
amplify: 8484/16000
amplify: 8486/16000
amplify: 8488/16000
amplify: 8490/16000
amplify: 8492/16000
amplify: 8494/16000
amplify: 8496/16000
amplify: 8498/16000
amplify: 8500/16000
amplify: 8502/16000
amplify: 8504/16000
amplify: 8506/16000
amplify: 8508/16000
amplify: 8510/16000
amplify: 8512/16000
amplify: 8514/16000
amplify: 8516/16000
amplify: 8518/16000
amplify: 8520/16000
amplify: 8522/16000
amplify: 8524/16000
amplify: 8526/16000
amplify: 8528/16000
amplify: 8530/16000
amplify: 8532/16000
amplify: 8534/16000
amplify: 8536/16000
amplify: 8538/16000
amplify: 8540/16000
amplify: 8542/16000
amplify: 8544/16000
amplify: 8546/16000
amplify: 8548/16000
amplify: 8550/16000
amplify: 8552/16000
amplify: 8554/16000
amplify: 8556/16000
amplify: 8558/16000
amplify: 8560/16000
amplify: 8562/16000
amplify: 8564/16000
amplify: 8566/16000
amplify: 8568/16000
amplify: 8570/16000
amplify: 8572/16000
amplify: 8574/16000
amplify: 8576/16000
amplify: 8578/16000
amplify: 8580/16000
amplify: 8582/16000
amplify: 8584/16000
amplify: 8586/16000
amplify: 8588/16000
amplify: 8590/16000
amplify: 8592/16000
amplify: 8594/16000
amplify: 8596/16000
amplify: 8598/16000
amplify: 8600/16000
amplify: 8602/16000
amplify: 8604/16000
amplify: 8606/16000
amplify: 8608/16000
amplify: 8610/16000
amplify: 8612/16000
amplify: 8614/16000
amplify: 8616/16000
amplify: 8618/16000
amplify: 8620/16000
amplify: 8622/16000
amplify: 8624/16000
amplify: 8626/16000
amplify: 8628/16000
amplify: 8630/16000
amplify: 8632/16000
amplify: 8634/16000
amplify: 8636/16000
amplify: 8638/16000
amplify: 8640/16000
amplify: 8642/16000

amplify: 8644/16000
amplify: 8646/16000
amplify: 8648/16000
amplify: 8650/16000
amplify: 8652/16000
amplify: 8654/16000
amplify: 8656/16000
amplify: 8658/16000
amplify: 8660/16000
amplify: 8662/16000
amplify: 8664/16000
amplify: 8666/16000
amplify: 8668/16000
amplify: 8670/16000
amplify: 8672/16000
amplify: 8674/16000
amplify: 8676/16000
amplify: 8678/16000
amplify: 8680/16000
amplify: 8682/16000
amplify: 8684/16000
amplify: 8686/16000
amplify: 8688/16000
amplify: 8690/16000
amplify: 8692/16000
amplify: 8694/16000
amplify: 8696/16000
amplify: 8698/16000
amplify: 8700/16000
amplify: 8702/16000
amplify: 8704/16000
amplify: 8706/16000
amplify: 8708/16000
amplify: 8710/16000
amplify: 8712/16000
amplify: 8714/16000
amplify: 8716/16000
amplify: 8718/16000
amplify: 8720/16000
amplify: 8722/16000
amplify: 8724/16000
amplify: 8726/16000
amplify: 8728/16000
amplify: 8730/16000
amplify: 8732/16000
amplify: 8734/16000
amplify: 8736/16000
amplify: 8738/16000
amplify: 8740/16000
amplify: 8742/16000
amplify: 8744/16000
amplify: 8746/16000
amplify: 8748/16000
amplify: 8750/16000
amplify: 8752/16000
amplify: 8754/16000
amplify: 8756/16000
amplify: 8758/16000
amplify: 8760/16000
amplify: 8762/16000
amplify: 8764/16000
amplify: 8766/16000
amplify: 8768/16000
amplify: 8770/16000
amplify: 8772/16000
amplify: 8774/16000
amplify: 8776/16000
amplify: 8778/16000
amplify: 8780/16000
amplify: 8782/16000
amplify: 8784/16000
amplify: 8786/16000
amplify: 8788/16000
amplify: 8790/16000
amplify: 8792/16000
amplify: 8794/16000
amplify: 8796/16000
amplify: 8798/16000
amplify: 8800/16000
amplify: 8802/16000
amplify: 8804/16000
amplify: 8806/16000
amplify: 8808/16000
amplify: 8810/16000
amplify: 8812/16000
amplify: 8814/16000
amplify: 8816/16000
amplify: 8818/16000
amplify: 8820/16000
amplify: 8822/16000
amplify: 8824/16000
amplify: 8826/16000
amplify: 8828/16000
amplify: 8830/16000
amplify: 8832/16000
amplify: 8834/16000
amplify: 8836/16000
amplify: 8838/16000
amplify: 8840/16000
amplify: 8842/16000
amplify: 8844/16000
amplify: 8846/16000
amplify: 8848/16000
amplify: 8850/16000
amplify: 8852/16000
amplify: 8854/16000
amplify: 8856/16000
amplify: 8858/16000
amplify: 8860/16000
amplify: 8862/16000
amplify: 8864/16000
amplify: 8866/16000
amplify: 8868/16000
amplify: 8870/16000
amplify: 8872/16000
amplify: 8874/16000
amplify: 8876/16000
amplify: 8878/16000
amplify: 8880/16000
amplify: 8882/16000
amplify: 8884/16000
amplify: 8886/16000
amplify: 8888/16000
amplify: 8890/16000
amplify: 8892/16000
amplify: 8894/16000
amplify: 8896/16000
amplify: 8898/16000
amplify: 8900/16000
amplify: 8902/16000
amplify: 8904/16000
amplify: 8906/16000
amplify: 8908/16000
amplify: 8910/16000
amplify: 8912/16000
amplify: 8914/16000
amplify: 8916/16000
amplify: 8918/16000
amplify: 8920/16000
amplify: 8922/16000
amplify: 8924/16000
amplify: 8926/16000
amplify: 8928/16000
amplify: 8930/16000
amplify: 8932/16000
amplify: 8934/16000
amplify: 8936/16000
amplify: 8938/16000
amplify: 8940/16000
amplify: 8942/16000
amplify: 8944/16000
amplify: 8946/16000
amplify: 8948/16000
amplify: 8950/16000
amplify: 8952/16000
amplify: 8954/16000
amplify: 8956/16000
amplify: 8958/16000
amplify: 8960/16000
amplify: 8962/16000
amplify: 8964/16000
amplify: 8966/16000
amplify: 8968/16000
amplify: 8970/16000
amplify: 8972/16000
amplify: 8974/16000
amplify: 8976/16000
amplify: 8978/16000
amplify: 8980/16000
amplify: 8982/16000
amplify: 8984/16000
amplify: 8986/16000
amplify: 8988/16000
amplify: 8990/16000
amplify: 8992/16000
amplify: 8994/16000
amplify: 8996/16000
amplify: 8998/16000
amplify: 9000/16000
amplify: 9002/16000
amplify: 9004/16000
amplify: 9006/16000
amplify: 9008/16000
amplify: 9010/16000
amplify: 9012/16000
amplify: 9014/16000
amplify: 9016/16000
amplify: 9018/16000
amplify: 9020/16000
amplify: 9022/16000
amplify: 9024/16000
amplify: 9026/16000
amplify: 9028/16000
amplify: 9030/16000
amplify: 9032/16000
amplify: 9034/16000
amplify: 9036/16000
amplify: 9038/16000
amplify: 9040/16000
amplify: 9042/16000
amplify: 9044/16000
amplify: 9046/16000
amplify: 9048/16000
amplify: 9050/16000
amplify: 9052/16000
amplify: 9054/16000
amplify: 9056/16000
amplify: 9058/16000
amplify: 9060/16000
amplify: 9062/16000
amplify: 9064/16000
amplify: 9066/16000
amplify: 9068/16000
amplify: 9070/16000
amplify: 9072/16000
amplify: 9074/16000
amplify: 9076/16000
amplify: 9078/16000
amplify: 9080/16000
amplify: 9082/16000
amplify: 9084/16000
amplify: 9086/16000
amplify: 9088/16000
amplify: 9090/16000
amplify: 9092/16000
amplify: 9094/16000
amplify: 9096/16000
amplify: 9098/16000
amplify: 9100/16000
amplify: 9102/16000
amplify: 9104/16000
amplify: 9106/16000
amplify: 9108/16000
amplify: 9110/16000
amplify: 9112/16000
amplify: 9114/16000
amplify: 9116/16000
amplify: 9118/16000
amplify: 9120/16000
amplify: 9122/16000
amplify: 9124/16000
amplify: 9126/16000
amplify: 9128/16000
amplify: 9130/16000
amplify: 9132/16000
amplify: 9134/16000
amplify: 9136/16000
amplify: 9138/16000
amplify: 9140/16000
amplify: 9142/16000
amplify: 9144/16000
amplify: 9146/16000
amplify: 9148/16000
amplify: 9150/16000
amplify: 9152/16000
amplify: 9154/16000
amplify: 9156/16000
amplify: 9158/16000
amplify: 9160/16000
amplify: 9162/16000
amplify: 9164/16000
amplify: 9166/16000
amplify: 9168/16000
amplify: 9170/16000
amplify: 9172/16000
amplify: 9174/16000
amplify: 9176/16000
amplify: 9178/16000
amplify: 9180/16000
amplify: 9182/16000
amplify: 9184/16000
amplify: 9186/16000
amplify: 9188/16000
amplify: 9190/16000
amplify: 9192/16000
amplify: 9194/16000
amplify: 9196/16000
amplify: 9198/16000
amplify: 9200/16000
amplify: 9202/16000
amplify: 9204/16000
amplify: 9206/16000
amplify: 9208/16000
amplify: 9210/16000
amplify: 9212/16000
amplify: 9214/16000
amplify: 9216/16000
amplify: 9218/16000
amplify: 9220/16000
amplify: 9222/16000
amplify: 9224/16000
amplify: 9226/16000
amplify: 9228/16000
amplify: 9230/16000
amplify: 9232/16000
amplify: 9234/16000
amplify: 9236/16000
amplify: 9238/16000
amplify: 9240/16000
amplify: 9242/16000
amplify: 9244/16000
amplify: 9246/16000
amplify: 9248/16000
amplify: 9250/16000
amplify: 9252/16000
amplify: 9254/16000
amplify: 9256/16000
amplify: 9258/16000
amplify: 9260/16000
amplify: 9262/16000
amplify: 9264/16000
amplify: 9266/16000
amplify: 9268/16000
amplify: 9270/16000
amplify: 9272/16000
amplify: 9274/16000
amplify: 9276/16000
amplify: 9278/16000
amplify: 9280/16000
amplify: 9282/16000
amplify: 9284/16000
amplify: 9286/16000
amplify: 9288/16000
amplify: 9290/16000
amplify: 9292/16000
amplify: 9294/16000
amplify: 9296/16000
amplify: 9298/16000
amplify: 9300/16000
amplify: 9302/16000
amplify: 9304/16000
amplify: 9306/16000
amplify: 9308/16000
amplify: 9310/16000
amplify: 9312/16000
amplify: 9314/16000
amplify: 9316/16000
amplify: 9318/16000
amplify: 9320/16000
amplify: 9322/16000
amplify: 9324/16000
amplify: 9326/16000
amplify: 9328/16000
amplify: 9330/16000
amplify: 9332/16000
amplify: 9334/16000
amplify: 9336/16000
amplify: 9338/16000
amplify: 9340/16000
amplify: 9342/16000
amplify: 9344/16000
amplify: 9346/16000
amplify: 9348/16000
amplify: 9350/16000
amplify: 9352/16000
amplify: 9354/16000
amplify: 9356/16000
amplify: 9358/16000
amplify: 9360/16000
amplify: 9362/16000
amplify: 9364/16000
amplify: 9366/16000
amplify: 9368/16000
amplify: 9370/16000
amplify: 9372/16000
amplify: 9374/16000
amplify: 9376/16000
amplify: 9378/16000
amplify: 9380/16000
amplify: 9382/16000
amplify: 9384/16000
amplify: 9386/16000
amplify: 9388/16000
amplify: 9390/16000
amplify: 9392/16000
amplify: 9394/16000
amplify: 9396/16000
amplify: 9398/16000
amplify: 9400/16000
amplify: 9402/16000
amplify: 9404/16000
amplify: 9406/16000
amplify: 9408/16000
amplify: 9410/16000
amplify: 9412/16000
amplify: 9414/16000
amplify: 9416/16000
amplify: 9418/16000
amplify: 9420/16000
amplify: 9422/16000
amplify: 9424/16000
amplify: 9426/16000
amplify: 9428/16000
amplify: 9430/16000
amplify: 9432/16000
amplify: 9434/16000
amplify: 9436/16000
amplify: 9438/16000
amplify: 9440/16000
amplify: 9442/16000
amplify: 9444/16000
amplify: 9446/16000
amplify: 9448/16000
amplify: 9450/16000
amplify: 9452/16000
amplify: 9454/16000
amplify: 9456/16000
amplify: 9458/16000
amplify: 9460/16000
amplify: 9462/16000
amplify: 9464/16000

amplify: 9466/16000
amplify: 9468/16000
amplify: 9470/16000
amplify: 9472/16000
amplify: 9474/16000
amplify: 9476/16000
amplify: 9478/16000
amplify: 9480/16000
amplify: 9482/16000
amplify: 9484/16000
amplify: 9486/16000
amplify: 9488/16000
amplify: 9490/16000
amplify: 9492/16000
amplify: 9494/16000
amplify: 9496/16000
amplify: 9498/16000
amplify: 9500/16000
amplify: 9502/16000
amplify: 9504/16000
amplify: 9506/16000
amplify: 9508/16000
amplify: 9510/16000
amplify: 9512/16000
amplify: 9514/16000
amplify: 9516/16000
amplify: 9518/16000
amplify: 9520/16000
amplify: 9522/16000
amplify: 9524/16000
amplify: 9526/16000
amplify: 9528/16000
amplify: 9530/16000
amplify: 9532/16000
amplify: 9534/16000
amplify: 9536/16000
amplify: 9538/16000
amplify: 9540/16000
amplify: 9542/16000
amplify: 9544/16000
amplify: 9546/16000
amplify: 9548/16000
amplify: 9550/16000
amplify: 9552/16000
amplify: 9554/16000
amplify: 9556/16000
amplify: 9558/16000
amplify: 9560/16000
amplify: 9562/16000
amplify: 9564/16000
amplify: 9566/16000
amplify: 9568/16000
amplify: 9570/16000
amplify: 9572/16000
amplify: 9574/16000
amplify: 9576/16000
amplify: 9578/16000
amplify: 9580/16000
amplify: 9582/16000
amplify: 9584/16000
amplify: 9586/16000
amplify: 9588/16000
amplify: 9590/16000
amplify: 9592/16000
amplify: 9594/16000
amplify: 9596/16000
amplify: 9598/16000
amplify: 9600/16000
amplify: 9602/16000
amplify: 9604/16000
amplify: 9606/16000
amplify: 9608/16000
amplify: 9610/16000
amplify: 9612/16000
amplify: 9614/16000
amplify: 9616/16000
amplify: 9618/16000
amplify: 9620/16000
amplify: 9622/16000
amplify: 9624/16000
amplify: 9626/16000
amplify: 9628/16000
amplify: 9630/16000
amplify: 9632/16000
amplify: 9634/16000
amplify: 9636/16000
amplify: 9638/16000
amplify: 9640/16000
amplify: 9642/16000
amplify: 9644/16000
amplify: 9646/16000
amplify: 9648/16000
amplify: 9650/16000
amplify: 9652/16000
amplify: 9654/16000
amplify: 9656/16000
amplify: 9658/16000
amplify: 9660/16000
amplify: 9662/16000
amplify: 9664/16000
amplify: 9666/16000
amplify: 9668/16000
amplify: 9670/16000
amplify: 9672/16000
amplify: 9674/16000
amplify: 9676/16000
amplify: 9678/16000
amplify: 9680/16000
amplify: 9682/16000
amplify: 9684/16000
amplify: 9686/16000
amplify: 9688/16000
amplify: 9690/16000
amplify: 9692/16000
amplify: 9694/16000
amplify: 9696/16000
amplify: 9698/16000
amplify: 9700/16000
amplify: 9702/16000
amplify: 9704/16000
amplify: 9706/16000
amplify: 9708/16000
amplify: 9710/16000
amplify: 9712/16000
amplify: 9714/16000
amplify: 9716/16000
amplify: 9718/16000
amplify: 9720/16000
amplify: 9722/16000
amplify: 9724/16000
amplify: 9726/16000
amplify: 9728/16000
amplify: 9730/16000
amplify: 9732/16000
amplify: 9734/16000
amplify: 9736/16000
amplify: 9738/16000
amplify: 9740/16000
amplify: 9742/16000
amplify: 9744/16000
amplify: 9746/16000
amplify: 9748/16000
amplify: 9750/16000
amplify: 9752/16000
amplify: 9754/16000
amplify: 9756/16000
amplify: 9758/16000
amplify: 9760/16000
amplify: 9762/16000
amplify: 9764/16000
amplify: 9766/16000
amplify: 9768/16000
amplify: 9770/16000
amplify: 9772/16000
amplify: 9774/16000
amplify: 9776/16000
amplify: 9778/16000
amplify: 9780/16000
amplify: 9782/16000
amplify: 9784/16000
amplify: 9786/16000
amplify: 9788/16000
amplify: 9790/16000
amplify: 9792/16000
amplify: 9794/16000
amplify: 9796/16000
amplify: 9798/16000
amplify: 9800/16000
amplify: 9802/16000
amplify: 9804/16000
amplify: 9806/16000
amplify: 9808/16000
amplify: 9810/16000
amplify: 9812/16000
amplify: 9814/16000
amplify: 9816/16000
amplify: 9818/16000
amplify: 9820/16000
amplify: 9822/16000
amplify: 9824/16000
amplify: 9826/16000
amplify: 9828/16000
amplify: 9830/16000
amplify: 9832/16000
amplify: 9834/16000
amplify: 9836/16000
amplify: 9838/16000
amplify: 9840/16000
amplify: 9842/16000
amplify: 9844/16000
amplify: 9846/16000
amplify: 9848/16000
amplify: 9850/16000
amplify: 9852/16000
amplify: 9854/16000
amplify: 9856/16000
amplify: 9858/16000
amplify: 9860/16000
amplify: 9862/16000
amplify: 9864/16000
amplify: 9866/16000
amplify: 9868/16000
amplify: 9870/16000
amplify: 9872/16000
amplify: 9874/16000
amplify: 9876/16000
amplify: 9878/16000
amplify: 9880/16000
amplify: 9882/16000
amplify: 9884/16000
amplify: 9886/16000
amplify: 9888/16000
amplify: 9890/16000
amplify: 9892/16000
amplify: 9894/16000
amplify: 9896/16000
amplify: 9898/16000
amplify: 9900/16000
amplify: 9902/16000
amplify: 9904/16000
amplify: 9906/16000
amplify: 9908/16000
amplify: 9910/16000
amplify: 9912/16000
amplify: 9914/16000
amplify: 9916/16000
amplify: 9918/16000
amplify: 9920/16000
amplify: 9922/16000
amplify: 9924/16000
amplify: 9926/16000
amplify: 9928/16000
amplify: 9930/16000
amplify: 9932/16000
amplify: 9934/16000
amplify: 9936/16000
amplify: 9938/16000
amplify: 9940/16000
amplify: 9942/16000
amplify: 9944/16000
amplify: 9946/16000
amplify: 9948/16000
amplify: 9950/16000
amplify: 9952/16000
amplify: 9954/16000
amplify: 9956/16000
amplify: 9958/16000
amplify: 9960/16000
amplify: 9962/16000
amplify: 9964/16000
amplify: 9966/16000
amplify: 9968/16000
amplify: 9970/16000
amplify: 9972/16000
amplify: 9974/16000
amplify: 9976/16000
amplify: 9978/16000
amplify: 9980/16000
amplify: 9982/16000
amplify: 9984/16000
amplify: 9986/16000
amplify: 9988/16000
amplify: 9990/16000
amplify: 9992/16000
amplify: 9994/16000
amplify: 9996/16000
amplify: 9998/16000
amplify: 10000/16000
amplify: 10002/16000
amplify: 10004/16000
amplify: 10006/16000
amplify: 10008/16000
amplify: 10010/16000
amplify: 10012/16000
amplify: 10014/16000
amplify: 10016/16000
amplify: 10018/16000
amplify: 10020/16000
amplify: 10022/16000
amplify: 10024/16000
amplify: 10026/16000
amplify: 10028/16000
amplify: 10030/16000
amplify: 10032/16000
amplify: 10034/16000
amplify: 10036/16000
amplify: 10038/16000
amplify: 10040/16000
amplify: 10042/16000
amplify: 10044/16000
amplify: 10046/16000
amplify: 10048/16000
amplify: 10050/16000
amplify: 10052/16000
amplify: 10054/16000
amplify: 10056/16000
amplify: 10058/16000
amplify: 10060/16000
amplify: 10062/16000
amplify: 10064/16000
amplify: 10066/16000
amplify: 10068/16000
amplify: 10070/16000
amplify: 10072/16000
amplify: 10074/16000
amplify: 10076/16000
amplify: 10078/16000
amplify: 10080/16000
amplify: 10082/16000
amplify: 10084/16000
amplify: 10086/16000
amplify: 10088/16000
amplify: 10090/16000
amplify: 10092/16000
amplify: 10094/16000
amplify: 10096/16000
amplify: 10098/16000
amplify: 10100/16000
amplify: 10102/16000
amplify: 10104/16000
amplify: 10106/16000
amplify: 10108/16000
amplify: 10110/16000
amplify: 10112/16000
amplify: 10114/16000
amplify: 10116/16000
amplify: 10118/16000
amplify: 10120/16000
amplify: 10122/16000
amplify: 10124/16000
amplify: 10126/16000
amplify: 10128/16000
amplify: 10130/16000
amplify: 10132/16000
amplify: 10134/16000
amplify: 10136/16000
amplify: 10138/16000
amplify: 10140/16000
amplify: 10142/16000
amplify: 10144/16000
amplify: 10146/16000
amplify: 10148/16000
amplify: 10150/16000
amplify: 10152/16000
amplify: 10154/16000
amplify: 10156/16000
amplify: 10158/16000
amplify: 10160/16000
amplify: 10162/16000
amplify: 10164/16000
amplify: 10166/16000
amplify: 10168/16000
amplify: 10170/16000
amplify: 10172/16000
amplify: 10174/16000
amplify: 10176/16000
amplify: 10178/16000
amplify: 10180/16000
amplify: 10182/16000
amplify: 10184/16000
amplify: 10186/16000
amplify: 10188/16000
amplify: 10190/16000
amplify: 10192/16000
amplify: 10194/16000
amplify: 10196/16000
amplify: 10198/16000
amplify: 10200/16000
amplify: 10202/16000
amplify: 10204/16000
amplify: 10206/16000
amplify: 10208/16000
amplify: 10210/16000
amplify: 10212/16000
amplify: 10214/16000
amplify: 10216/16000
amplify: 10218/16000
amplify: 10220/16000
amplify: 10222/16000
amplify: 10224/16000
amplify: 10226/16000
amplify: 10228/16000
amplify: 10230/16000
amplify: 10232/16000
amplify: 10234/16000
amplify: 10236/16000
amplify: 10238/16000
amplify: 10240/16000
amplify: 10242/16000
amplify: 10244/16000
amplify: 10246/16000
amplify: 10248/16000
amplify: 10250/16000
amplify: 10252/16000
amplify: 10254/16000
amplify: 10256/16000
amplify: 10258/16000
amplify: 10260/16000
amplify: 10262/16000
amplify: 10264/16000
amplify: 10266/16000
amplify: 10268/16000
amplify: 10270/16000
amplify: 10272/16000

amplify: 10274/16000
amplify: 10276/16000
amplify: 10278/16000
amplify: 10280/16000
amplify: 10282/16000
amplify: 10284/16000
amplify: 10286/16000
amplify: 10288/16000
amplify: 10290/16000
amplify: 10292/16000
amplify: 10294/16000
amplify: 10296/16000
amplify: 10298/16000
amplify: 10300/16000
amplify: 10302/16000
amplify: 10304/16000
amplify: 10306/16000
amplify: 10308/16000
amplify: 10310/16000
amplify: 10312/16000
amplify: 10314/16000
amplify: 10316/16000
amplify: 10318/16000
amplify: 10320/16000
amplify: 10322/16000
amplify: 10324/16000
amplify: 10326/16000
amplify: 10328/16000
amplify: 10330/16000
amplify: 10332/16000
amplify: 10334/16000
amplify: 10336/16000
amplify: 10338/16000
amplify: 10340/16000
amplify: 10342/16000
amplify: 10344/16000
amplify: 10346/16000
amplify: 10348/16000
amplify: 10350/16000
amplify: 10352/16000
amplify: 10354/16000
amplify: 10356/16000
amplify: 10358/16000
amplify: 10360/16000
amplify: 10362/16000
amplify: 10364/16000
amplify: 10366/16000
amplify: 10368/16000
amplify: 10370/16000
amplify: 10372/16000
amplify: 10374/16000
amplify: 10376/16000
amplify: 10378/16000
amplify: 10380/16000
amplify: 10382/16000
amplify: 10384/16000
amplify: 10386/16000
amplify: 10388/16000
amplify: 10390/16000
amplify: 10392/16000
amplify: 10394/16000
amplify: 10396/16000
amplify: 10398/16000
amplify: 10400/16000
amplify: 10402/16000
amplify: 10404/16000
amplify: 10406/16000
amplify: 10408/16000
amplify: 10410/16000
amplify: 10412/16000
amplify: 10414/16000
amplify: 10416/16000
amplify: 10418/16000
amplify: 10420/16000
amplify: 10422/16000
amplify: 10424/16000
amplify: 10426/16000
amplify: 10428/16000
amplify: 10430/16000
amplify: 10432/16000
amplify: 10434/16000
amplify: 10436/16000
amplify: 10438/16000
amplify: 10440/16000
amplify: 10442/16000
amplify: 10444/16000
amplify: 10446/16000
amplify: 10448/16000
amplify: 10450/16000
amplify: 10452/16000
amplify: 10454/16000
amplify: 10456/16000
amplify: 10458/16000
amplify: 10460/16000
amplify: 10462/16000
amplify: 10464/16000
amplify: 10466/16000
amplify: 10468/16000
amplify: 10470/16000
amplify: 10472/16000
amplify: 10474/16000
amplify: 10476/16000
amplify: 10478/16000
amplify: 10480/16000
amplify: 10482/16000
amplify: 10484/16000
amplify: 10486/16000
amplify: 10488/16000
amplify: 10490/16000
amplify: 10492/16000
amplify: 10494/16000
amplify: 10496/16000
amplify: 10498/16000
amplify: 10500/16000
amplify: 10502/16000
amplify: 10504/16000
amplify: 10506/16000
amplify: 10508/16000
amplify: 10510/16000
amplify: 10512/16000
amplify: 10514/16000
amplify: 10516/16000
amplify: 10518/16000
amplify: 10520/16000
amplify: 10522/16000
amplify: 10524/16000
amplify: 10526/16000
amplify: 10528/16000
amplify: 10530/16000
amplify: 10532/16000
amplify: 10534/16000
amplify: 10536/16000
amplify: 10538/16000
amplify: 10540/16000
amplify: 10542/16000
amplify: 10544/16000
amplify: 10546/16000
amplify: 10548/16000
amplify: 10550/16000
amplify: 10552/16000
amplify: 10554/16000
amplify: 10556/16000
amplify: 10558/16000
amplify: 10560/16000
amplify: 10562/16000
amplify: 10564/16000
amplify: 10566/16000
amplify: 10568/16000
amplify: 10570/16000
amplify: 10572/16000
amplify: 10574/16000
amplify: 10576/16000
amplify: 10578/16000
amplify: 10580/16000
amplify: 10582/16000
amplify: 10584/16000
amplify: 10586/16000
amplify: 10588/16000
amplify: 10590/16000
amplify: 10592/16000
amplify: 10594/16000
amplify: 10596/16000
amplify: 10598/16000
amplify: 10600/16000
amplify: 10602/16000
amplify: 10604/16000
amplify: 10606/16000
amplify: 10608/16000
amplify: 10610/16000
amplify: 10612/16000
amplify: 10614/16000
amplify: 10616/16000
amplify: 10618/16000
amplify: 10620/16000
amplify: 10622/16000
amplify: 10624/16000
amplify: 10626/16000
amplify: 10628/16000
amplify: 10630/16000
amplify: 10632/16000
amplify: 10634/16000
amplify: 10636/16000
amplify: 10638/16000
amplify: 10640/16000
amplify: 10642/16000
amplify: 10644/16000
amplify: 10646/16000
amplify: 10648/16000
amplify: 10650/16000
amplify: 10652/16000
amplify: 10654/16000
amplify: 10656/16000
amplify: 10658/16000
amplify: 10660/16000
amplify: 10662/16000
amplify: 10664/16000
amplify: 10666/16000
amplify: 10668/16000
amplify: 10670/16000
amplify: 10672/16000
amplify: 10674/16000
amplify: 10676/16000
amplify: 10678/16000
amplify: 10680/16000
amplify: 10682/16000
amplify: 10684/16000
amplify: 10686/16000
amplify: 10688/16000
amplify: 10690/16000
amplify: 10692/16000
amplify: 10694/16000
amplify: 10696/16000
amplify: 10698/16000
amplify: 10700/16000
amplify: 10702/16000
amplify: 10704/16000
amplify: 10706/16000
amplify: 10708/16000
amplify: 10710/16000
amplify: 10712/16000
amplify: 10714/16000
amplify: 10716/16000
amplify: 10718/16000
amplify: 10720/16000
amplify: 10722/16000
amplify: 10724/16000
amplify: 10726/16000
amplify: 10728/16000
amplify: 10730/16000
amplify: 10732/16000
amplify: 10734/16000
amplify: 10736/16000
amplify: 10738/16000
amplify: 10740/16000
amplify: 10742/16000
amplify: 10744/16000
amplify: 10746/16000
amplify: 10748/16000
amplify: 10750/16000
amplify: 10752/16000
amplify: 10754/16000
amplify: 10756/16000
amplify: 10758/16000
amplify: 10760/16000
amplify: 10762/16000
amplify: 10764/16000
amplify: 10766/16000
amplify: 10768/16000
amplify: 10770/16000
amplify: 10772/16000
amplify: 10774/16000
amplify: 10776/16000
amplify: 10778/16000
amplify: 10780/16000
amplify: 10782/16000
amplify: 10784/16000
amplify: 10786/16000
amplify: 10788/16000
amplify: 10790/16000
amplify: 10792/16000
amplify: 10794/16000
amplify: 10796/16000
amplify: 10798/16000
amplify: 10800/16000
amplify: 10802/16000
amplify: 10804/16000
amplify: 10806/16000
amplify: 10808/16000
amplify: 10810/16000
amplify: 10812/16000
amplify: 10814/16000
amplify: 10816/16000
amplify: 10818/16000
amplify: 10820/16000
amplify: 10822/16000
amplify: 10824/16000
amplify: 10826/16000
amplify: 10828/16000
amplify: 10830/16000
amplify: 10832/16000
amplify: 10834/16000
amplify: 10836/16000
amplify: 10838/16000
amplify: 10840/16000
amplify: 10842/16000
amplify: 10844/16000
amplify: 10846/16000
amplify: 10848/16000
amplify: 10850/16000
amplify: 10852/16000
amplify: 10854/16000
amplify: 10856/16000
amplify: 10858/16000
amplify: 10860/16000
amplify: 10862/16000
amplify: 10864/16000
amplify: 10866/16000
amplify: 10868/16000
amplify: 10870/16000
amplify: 10872/16000
amplify: 10874/16000
amplify: 10876/16000
amplify: 10878/16000
amplify: 10880/16000
amplify: 10882/16000
amplify: 10884/16000
amplify: 10886/16000
amplify: 10888/16000
amplify: 10890/16000
amplify: 10892/16000
amplify: 10894/16000
amplify: 10896/16000
amplify: 10898/16000
amplify: 10900/16000
amplify: 10902/16000
amplify: 10904/16000
amplify: 10906/16000
amplify: 10908/16000
amplify: 10910/16000
amplify: 10912/16000
amplify: 10914/16000
amplify: 10916/16000
amplify: 10918/16000
amplify: 10920/16000
amplify: 10922/16000
amplify: 10924/16000
amplify: 10926/16000
amplify: 10928/16000
amplify: 10930/16000
amplify: 10932/16000
amplify: 10934/16000
amplify: 10936/16000
amplify: 10938/16000
amplify: 10940/16000
amplify: 10942/16000
amplify: 10944/16000
amplify: 10946/16000
amplify: 10948/16000
amplify: 10950/16000
amplify: 10952/16000
amplify: 10954/16000
amplify: 10956/16000
amplify: 10958/16000
amplify: 10960/16000
amplify: 10962/16000
amplify: 10964/16000
amplify: 10966/16000
amplify: 10968/16000
amplify: 10970/16000
amplify: 10972/16000
amplify: 10974/16000
amplify: 10976/16000
amplify: 10978/16000
amplify: 10980/16000
amplify: 10982/16000
amplify: 10984/16000
amplify: 10986/16000
amplify: 10988/16000
amplify: 10990/16000
amplify: 10992/16000
amplify: 10994/16000
amplify: 10996/16000
amplify: 10998/16000
amplify: 11000/16000
amplify: 11002/16000
amplify: 11004/16000
amplify: 11006/16000
amplify: 11008/16000
amplify: 11010/16000
amplify: 11012/16000
amplify: 11014/16000
amplify: 11016/16000
amplify: 11018/16000
amplify: 11020/16000
amplify: 11022/16000
amplify: 11024/16000
amplify: 11026/16000
amplify: 11028/16000
amplify: 11030/16000
amplify: 11032/16000
amplify: 11034/16000
amplify: 11036/16000
amplify: 11038/16000
amplify: 11040/16000
amplify: 11042/16000
amplify: 11044/16000
amplify: 11046/16000
amplify: 11048/16000
amplify: 11050/16000
amplify: 11052/16000
amplify: 11054/16000

amplify: 11056/16000
amplify: 11058/16000
amplify: 11060/16000
amplify: 11062/16000
amplify: 11064/16000
amplify: 11066/16000
amplify: 11068/16000
amplify: 11070/16000
amplify: 11072/16000
amplify: 11074/16000
amplify: 11076/16000
amplify: 11078/16000
amplify: 11080/16000
amplify: 11082/16000
amplify: 11084/16000
amplify: 11086/16000
amplify: 11088/16000
amplify: 11090/16000
amplify: 11092/16000
amplify: 11094/16000
amplify: 11096/16000
amplify: 11098/16000
amplify: 11100/16000
amplify: 11102/16000
amplify: 11104/16000
amplify: 11106/16000
amplify: 11108/16000
amplify: 11110/16000
amplify: 11112/16000
amplify: 11114/16000
amplify: 11116/16000
amplify: 11118/16000
amplify: 11120/16000
amplify: 11122/16000
amplify: 11124/16000
amplify: 11126/16000
amplify: 11128/16000
amplify: 11130/16000
amplify: 11132/16000
amplify: 11134/16000
amplify: 11136/16000
amplify: 11138/16000
amplify: 11140/16000
amplify: 11142/16000
amplify: 11144/16000
amplify: 11146/16000
amplify: 11148/16000
amplify: 11150/16000
amplify: 11152/16000
amplify: 11154/16000
amplify: 11156/16000
amplify: 11158/16000
amplify: 11160/16000
amplify: 11162/16000
amplify: 11164/16000
amplify: 11166/16000
amplify: 11168/16000
amplify: 11170/16000
amplify: 11172/16000
amplify: 11174/16000
amplify: 11176/16000
amplify: 11178/16000
amplify: 11180/16000
amplify: 11182/16000
amplify: 11184/16000
amplify: 11186/16000
amplify: 11188/16000
amplify: 11190/16000
amplify: 11192/16000
amplify: 11194/16000
amplify: 11196/16000
amplify: 11198/16000
amplify: 11200/16000
amplify: 11202/16000
amplify: 11204/16000
amplify: 11206/16000
amplify: 11208/16000
amplify: 11210/16000
amplify: 11212/16000
amplify: 11214/16000
amplify: 11216/16000
amplify: 11218/16000
amplify: 11220/16000
amplify: 11222/16000
amplify: 11224/16000
amplify: 11226/16000
amplify: 11228/16000
amplify: 11230/16000
amplify: 11232/16000
amplify: 11234/16000
amplify: 11236/16000
amplify: 11238/16000
amplify: 11240/16000
amplify: 11242/16000
amplify: 11244/16000
amplify: 11246/16000
amplify: 11248/16000
amplify: 11250/16000
amplify: 11252/16000
amplify: 11254/16000
amplify: 11256/16000
amplify: 11258/16000
amplify: 11260/16000
amplify: 11262/16000
amplify: 11264/16000
amplify: 11266/16000
amplify: 11268/16000
amplify: 11270/16000
amplify: 11272/16000
amplify: 11274/16000
amplify: 11276/16000
amplify: 11278/16000
amplify: 11280/16000
amplify: 11282/16000
amplify: 11284/16000
amplify: 11286/16000
amplify: 11288/16000
amplify: 11290/16000
amplify: 11292/16000
amplify: 11294/16000
amplify: 11296/16000
amplify: 11298/16000
amplify: 11300/16000
amplify: 11302/16000
amplify: 11304/16000
amplify: 11306/16000
amplify: 11308/16000
amplify: 11310/16000
amplify: 11312/16000
amplify: 11314/16000
amplify: 11316/16000
amplify: 11318/16000
amplify: 11320/16000
amplify: 11322/16000
amplify: 11324/16000
amplify: 11326/16000
amplify: 11328/16000
amplify: 11330/16000
amplify: 11332/16000
amplify: 11334/16000
amplify: 11336/16000
amplify: 11338/16000
amplify: 11340/16000
amplify: 11342/16000
amplify: 11344/16000
amplify: 11346/16000
amplify: 11348/16000
amplify: 11350/16000
amplify: 11352/16000
amplify: 11354/16000
amplify: 11356/16000
amplify: 11358/16000
amplify: 11360/16000
amplify: 11362/16000
amplify: 11364/16000
amplify: 11366/16000
amplify: 11368/16000
amplify: 11370/16000
amplify: 11372/16000
amplify: 11374/16000
amplify: 11376/16000
amplify: 11378/16000
amplify: 11380/16000
amplify: 11382/16000
amplify: 11384/16000
amplify: 11386/16000
amplify: 11388/16000
amplify: 11390/16000
amplify: 11392/16000
amplify: 11394/16000
amplify: 11396/16000
amplify: 11398/16000
amplify: 11400/16000
amplify: 11402/16000
amplify: 11404/16000
amplify: 11406/16000
amplify: 11408/16000
amplify: 11410/16000
amplify: 11412/16000
amplify: 11414/16000
amplify: 11416/16000
amplify: 11418/16000
amplify: 11420/16000
amplify: 11422/16000
amplify: 11424/16000
amplify: 11426/16000
amplify: 11428/16000
amplify: 11430/16000
amplify: 11432/16000
amplify: 11434/16000
amplify: 11436/16000
amplify: 11438/16000
amplify: 11440/16000
amplify: 11442/16000
amplify: 11444/16000
amplify: 11446/16000
amplify: 11448/16000
amplify: 11450/16000
amplify: 11452/16000
amplify: 11454/16000
amplify: 11456/16000
amplify: 11458/16000
amplify: 11460/16000
amplify: 11462/16000
amplify: 11464/16000
amplify: 11466/16000
amplify: 11468/16000
amplify: 11470/16000
amplify: 11472/16000
amplify: 11474/16000
amplify: 11476/16000
amplify: 11478/16000
amplify: 11480/16000
amplify: 11482/16000
amplify: 11484/16000
amplify: 11486/16000
amplify: 11488/16000
amplify: 11490/16000
amplify: 11492/16000
amplify: 11494/16000
amplify: 11496/16000
amplify: 11498/16000
amplify: 11500/16000
amplify: 11502/16000
amplify: 11504/16000
amplify: 11506/16000
amplify: 11508/16000
amplify: 11510/16000
amplify: 11512/16000
amplify: 11514/16000
amplify: 11516/16000
amplify: 11518/16000
amplify: 11520/16000
amplify: 11522/16000
amplify: 11524/16000
amplify: 11526/16000
amplify: 11528/16000
amplify: 11530/16000
amplify: 11532/16000
amplify: 11534/16000
amplify: 11536/16000
amplify: 11538/16000
amplify: 11540/16000
amplify: 11542/16000
amplify: 11544/16000
amplify: 11546/16000
amplify: 11548/16000
amplify: 11550/16000
amplify: 11552/16000
amplify: 11554/16000
amplify: 11556/16000
amplify: 11558/16000
amplify: 11560/16000
amplify: 11562/16000
amplify: 11564/16000
amplify: 11566/16000
amplify: 11568/16000
amplify: 11570/16000
amplify: 11572/16000
amplify: 11574/16000
amplify: 11576/16000
amplify: 11578/16000
amplify: 11580/16000
amplify: 11582/16000
amplify: 11584/16000
amplify: 11586/16000
amplify: 11588/16000
amplify: 11590/16000
amplify: 11592/16000
amplify: 11594/16000
amplify: 11596/16000
amplify: 11598/16000
amplify: 11600/16000
amplify: 11602/16000
amplify: 11604/16000
amplify: 11606/16000
amplify: 11608/16000
amplify: 11610/16000
amplify: 11612/16000
amplify: 11614/16000
amplify: 11616/16000
amplify: 11618/16000
amplify: 11620/16000
amplify: 11622/16000
amplify: 11624/16000
amplify: 11626/16000
amplify: 11628/16000
amplify: 11630/16000
amplify: 11632/16000
amplify: 11634/16000
amplify: 11636/16000
amplify: 11638/16000
amplify: 11640/16000
amplify: 11642/16000
amplify: 11644/16000
amplify: 11646/16000
amplify: 11648/16000
amplify: 11650/16000
amplify: 11652/16000
amplify: 11654/16000
amplify: 11656/16000
amplify: 11658/16000
amplify: 11660/16000
amplify: 11662/16000
amplify: 11664/16000
amplify: 11666/16000
amplify: 11668/16000
amplify: 11670/16000
amplify: 11672/16000
amplify: 11674/16000
amplify: 11676/16000
amplify: 11678/16000
amplify: 11680/16000
amplify: 11682/16000
amplify: 11684/16000
amplify: 11686/16000
amplify: 11688/16000
amplify: 11690/16000
amplify: 11692/16000
amplify: 11694/16000
amplify: 11696/16000
amplify: 11698/16000
amplify: 11700/16000
amplify: 11702/16000
amplify: 11704/16000
amplify: 11706/16000
amplify: 11708/16000
amplify: 11710/16000
amplify: 11712/16000
amplify: 11714/16000
amplify: 11716/16000
amplify: 11718/16000
amplify: 11720/16000
amplify: 11722/16000
amplify: 11724/16000
amplify: 11726/16000
amplify: 11728/16000
amplify: 11730/16000
amplify: 11732/16000
amplify: 11734/16000
amplify: 11736/16000
amplify: 11738/16000
amplify: 11740/16000
amplify: 11742/16000
amplify: 11744/16000
amplify: 11746/16000
amplify: 11748/16000
amplify: 11750/16000
amplify: 11752/16000
amplify: 11754/16000
amplify: 11756/16000
amplify: 11758/16000
amplify: 11760/16000
amplify: 11762/16000
amplify: 11764/16000
amplify: 11766/16000
amplify: 11768/16000
amplify: 11770/16000
amplify: 11772/16000
amplify: 11774/16000
amplify: 11776/16000
amplify: 11778/16000
amplify: 11780/16000
amplify: 11782/16000
amplify: 11784/16000
amplify: 11786/16000
amplify: 11788/16000
amplify: 11790/16000
amplify: 11792/16000
amplify: 11794/16000
amplify: 11796/16000
amplify: 11798/16000
amplify: 11800/16000
amplify: 11802/16000
amplify: 11804/16000
amplify: 11806/16000
amplify: 11808/16000
amplify: 11810/16000
amplify: 11812/16000
amplify: 11814/16000
amplify: 11816/16000
amplify: 11818/16000
amplify: 11820/16000
amplify: 11822/16000
amplify: 11824/16000
amplify: 11826/16000
amplify: 11828/16000
amplify: 11830/16000
amplify: 11832/16000
amplify: 11834/16000
amplify: 11836/16000

amplify: 11838/16000
amplify: 11840/16000
amplify: 11842/16000
amplify: 11844/16000
amplify: 11846/16000
amplify: 11848/16000
amplify: 11850/16000
amplify: 11852/16000
amplify: 11854/16000
amplify: 11856/16000
amplify: 11858/16000
amplify: 11860/16000
amplify: 11862/16000
amplify: 11864/16000
amplify: 11866/16000
amplify: 11868/16000
amplify: 11870/16000
amplify: 11872/16000
amplify: 11874/16000
amplify: 11876/16000
amplify: 11878/16000
amplify: 11880/16000
amplify: 11882/16000
amplify: 11884/16000
amplify: 11886/16000
amplify: 11888/16000
amplify: 11890/16000
amplify: 11892/16000
amplify: 11894/16000
amplify: 11896/16000
amplify: 11898/16000
amplify: 11900/16000
amplify: 11902/16000
amplify: 11904/16000
amplify: 11906/16000
amplify: 11908/16000
amplify: 11910/16000
amplify: 11912/16000
amplify: 11914/16000
amplify: 11916/16000
amplify: 11918/16000
amplify: 11920/16000
amplify: 11922/16000
amplify: 11924/16000
amplify: 11926/16000
amplify: 11928/16000
amplify: 11930/16000
amplify: 11932/16000
amplify: 11934/16000
amplify: 11936/16000
amplify: 11938/16000
amplify: 11940/16000
amplify: 11942/16000
amplify: 11944/16000
amplify: 11946/16000
amplify: 11948/16000
amplify: 11950/16000
amplify: 11952/16000
amplify: 11954/16000
amplify: 11956/16000
amplify: 11958/16000
amplify: 11960/16000
amplify: 11962/16000
amplify: 11964/16000
amplify: 11966/16000
amplify: 11968/16000
amplify: 11970/16000
amplify: 11972/16000
amplify: 11974/16000
amplify: 11976/16000
amplify: 11978/16000
amplify: 11980/16000
amplify: 11982/16000
amplify: 11984/16000
amplify: 11986/16000
amplify: 11988/16000
amplify: 11990/16000
amplify: 11992/16000
amplify: 11994/16000
amplify: 11996/16000
amplify: 11998/16000
amplify: 12000/16000
amplify: 12002/16000
amplify: 12004/16000
amplify: 12006/16000
amplify: 12008/16000
amplify: 12010/16000
amplify: 12012/16000
amplify: 12014/16000
amplify: 12016/16000
amplify: 12018/16000
amplify: 12020/16000
amplify: 12022/16000
amplify: 12024/16000
amplify: 12026/16000
amplify: 12028/16000
amplify: 12030/16000
amplify: 12032/16000
amplify: 12034/16000
amplify: 12036/16000
amplify: 12038/16000
amplify: 12040/16000
amplify: 12042/16000
amplify: 12044/16000
amplify: 12046/16000
amplify: 12048/16000
amplify: 12050/16000
amplify: 12052/16000
amplify: 12054/16000
amplify: 12056/16000
amplify: 12058/16000
amplify: 12060/16000
amplify: 12062/16000
amplify: 12064/16000
amplify: 12066/16000
amplify: 12068/16000
amplify: 12070/16000
amplify: 12072/16000
amplify: 12074/16000
amplify: 12076/16000
amplify: 12078/16000
amplify: 12080/16000
amplify: 12082/16000
amplify: 12084/16000
amplify: 12086/16000
amplify: 12088/16000
amplify: 12090/16000
amplify: 12092/16000
amplify: 12094/16000
amplify: 12096/16000
amplify: 12098/16000
amplify: 12100/16000
amplify: 12102/16000
amplify: 12104/16000
amplify: 12106/16000
amplify: 12108/16000
amplify: 12110/16000
amplify: 12112/16000
amplify: 12114/16000
amplify: 12116/16000
amplify: 12118/16000
amplify: 12120/16000
amplify: 12122/16000
amplify: 12124/16000
amplify: 12126/16000
amplify: 12128/16000
amplify: 12130/16000
amplify: 12132/16000
amplify: 12134/16000
amplify: 12136/16000
amplify: 12138/16000
amplify: 12140/16000
amplify: 12142/16000
amplify: 12144/16000
amplify: 12146/16000
amplify: 12148/16000
amplify: 12150/16000
amplify: 12152/16000
amplify: 12154/16000
amplify: 12156/16000
amplify: 12158/16000
amplify: 12160/16000
amplify: 12162/16000
amplify: 12164/16000
amplify: 12166/16000
amplify: 12168/16000
amplify: 12170/16000
amplify: 12172/16000
amplify: 12174/16000
amplify: 12176/16000
amplify: 12178/16000
amplify: 12180/16000
amplify: 12182/16000
amplify: 12184/16000
amplify: 12186/16000
amplify: 12188/16000
amplify: 12190/16000
amplify: 12192/16000
amplify: 12194/16000
amplify: 12196/16000
amplify: 12198/16000
amplify: 12200/16000
amplify: 12202/16000
amplify: 12204/16000
amplify: 12206/16000
amplify: 12208/16000
amplify: 12210/16000
amplify: 12212/16000
amplify: 12214/16000
amplify: 12216/16000
amplify: 12218/16000
amplify: 12220/16000
amplify: 12222/16000
amplify: 12224/16000
amplify: 12226/16000
amplify: 12228/16000
amplify: 12230/16000
amplify: 12232/16000
amplify: 12234/16000
amplify: 12236/16000
amplify: 12238/16000
amplify: 12240/16000
amplify: 12242/16000
amplify: 12244/16000
amplify: 12246/16000
amplify: 12248/16000
amplify: 12250/16000
amplify: 12252/16000
amplify: 12254/16000
amplify: 12256/16000
amplify: 12258/16000
amplify: 12260/16000
amplify: 12262/16000
amplify: 12264/16000
amplify: 12266/16000
amplify: 12268/16000
amplify: 12270/16000
amplify: 12272/16000
amplify: 12274/16000
amplify: 12276/16000
amplify: 12278/16000
amplify: 12280/16000
amplify: 12282/16000
amplify: 12284/16000
amplify: 12286/16000
amplify: 12288/16000
amplify: 12290/16000
amplify: 12292/16000
amplify: 12294/16000
amplify: 12296/16000
amplify: 12298/16000
amplify: 12300/16000
amplify: 12302/16000
amplify: 12304/16000
amplify: 12306/16000
amplify: 12308/16000
amplify: 12310/16000
amplify: 12312/16000
amplify: 12314/16000
amplify: 12316/16000
amplify: 12318/16000
amplify: 12320/16000
amplify: 12322/16000
amplify: 12324/16000
amplify: 12326/16000
amplify: 12328/16000
amplify: 12330/16000
amplify: 12332/16000
amplify: 12334/16000
amplify: 12336/16000
amplify: 12338/16000
amplify: 12340/16000
amplify: 12342/16000
amplify: 12344/16000
amplify: 12346/16000
amplify: 12348/16000
amplify: 12350/16000
amplify: 12352/16000
amplify: 12354/16000
amplify: 12356/16000
amplify: 12358/16000
amplify: 12360/16000
amplify: 12362/16000
amplify: 12364/16000
amplify: 12366/16000
amplify: 12368/16000
amplify: 12370/16000
amplify: 12372/16000
amplify: 12374/16000
amplify: 12376/16000
amplify: 12378/16000
amplify: 12380/16000
amplify: 12382/16000
amplify: 12384/16000
amplify: 12386/16000
amplify: 12388/16000
amplify: 12390/16000
amplify: 12392/16000
amplify: 12394/16000
amplify: 12396/16000
amplify: 12398/16000
amplify: 12400/16000
amplify: 12402/16000
amplify: 12404/16000
amplify: 12406/16000
amplify: 12408/16000
amplify: 12410/16000
amplify: 12412/16000
amplify: 12414/16000
amplify: 12416/16000
amplify: 12418/16000
amplify: 12420/16000
amplify: 12422/16000
amplify: 12424/16000
amplify: 12426/16000
amplify: 12428/16000
amplify: 12430/16000
amplify: 12432/16000
amplify: 12434/16000
amplify: 12436/16000
amplify: 12438/16000
amplify: 12440/16000
amplify: 12442/16000
amplify: 12444/16000
amplify: 12446/16000
amplify: 12448/16000
amplify: 12450/16000
amplify: 12452/16000
amplify: 12454/16000
amplify: 12456/16000
amplify: 12458/16000
amplify: 12460/16000
amplify: 12462/16000
amplify: 12464/16000
amplify: 12466/16000
amplify: 12468/16000
amplify: 12470/16000
amplify: 12472/16000
amplify: 12474/16000
amplify: 12476/16000
amplify: 12478/16000
amplify: 12480/16000
amplify: 12482/16000
amplify: 12484/16000
amplify: 12486/16000
amplify: 12488/16000
amplify: 12490/16000
amplify: 12492/16000
amplify: 12494/16000
amplify: 12496/16000
amplify: 12498/16000
amplify: 12500/16000
amplify: 12502/16000
amplify: 12504/16000
amplify: 12506/16000
amplify: 12508/16000
amplify: 12510/16000
amplify: 12512/16000
amplify: 12514/16000
amplify: 12516/16000
amplify: 12518/16000
amplify: 12520/16000
amplify: 12522/16000
amplify: 12524/16000
amplify: 12526/16000
amplify: 12528/16000
amplify: 12530/16000
amplify: 12532/16000
amplify: 12534/16000
amplify: 12536/16000
amplify: 12538/16000
amplify: 12540/16000
amplify: 12542/16000
amplify: 12544/16000
amplify: 12546/16000
amplify: 12548/16000
amplify: 12550/16000
amplify: 12552/16000
amplify: 12554/16000
amplify: 12556/16000
amplify: 12558/16000
amplify: 12560/16000
amplify: 12562/16000
amplify: 12564/16000
amplify: 12566/16000
amplify: 12568/16000
amplify: 12570/16000
amplify: 12572/16000
amplify: 12574/16000
amplify: 12576/16000
amplify: 12578/16000
amplify: 12580/16000
amplify: 12582/16000
amplify: 12584/16000
amplify: 12586/16000
amplify: 12588/16000
amplify: 12590/16000
amplify: 12592/16000
amplify: 12594/16000
amplify: 12596/16000
amplify: 12598/16000
amplify: 12600/16000
amplify: 12602/16000
amplify: 12604/16000
amplify: 12606/16000
amplify: 12608/16000
amplify: 12610/16000
amplify: 12612/16000
amplify: 12614/16000
amplify: 12616/16000
amplify: 12618/16000
amplify: 12620/16000
amplify: 12622/16000

amplify: 12624/16000
amplify: 12626/16000
amplify: 12628/16000
amplify: 12630/16000
amplify: 12632/16000
amplify: 12634/16000
amplify: 12636/16000
amplify: 12638/16000
amplify: 12640/16000
amplify: 12642/16000
amplify: 12644/16000
amplify: 12646/16000
amplify: 12648/16000
amplify: 12650/16000
amplify: 12652/16000
amplify: 12654/16000
amplify: 12656/16000
amplify: 12658/16000
amplify: 12660/16000
amplify: 12662/16000
amplify: 12664/16000
amplify: 12666/16000
amplify: 12668/16000
amplify: 12670/16000
amplify: 12672/16000
amplify: 12674/16000
amplify: 12676/16000
amplify: 12678/16000
amplify: 12680/16000
amplify: 12682/16000
amplify: 12684/16000
amplify: 12686/16000
amplify: 12688/16000
amplify: 12690/16000
amplify: 12692/16000
amplify: 12694/16000
amplify: 12696/16000
amplify: 12698/16000
amplify: 12700/16000
amplify: 12702/16000
amplify: 12704/16000
amplify: 12706/16000
amplify: 12708/16000
amplify: 12710/16000
amplify: 12712/16000
amplify: 12714/16000
amplify: 12716/16000
amplify: 12718/16000
amplify: 12720/16000
amplify: 12722/16000
amplify: 12724/16000
amplify: 12726/16000
amplify: 12728/16000
amplify: 12730/16000
amplify: 12732/16000
amplify: 12734/16000
amplify: 12736/16000
amplify: 12738/16000
amplify: 12740/16000
amplify: 12742/16000
amplify: 12744/16000
amplify: 12746/16000
amplify: 12748/16000
amplify: 12750/16000
amplify: 12752/16000
amplify: 12754/16000
amplify: 12756/16000
amplify: 12758/16000
amplify: 12760/16000
amplify: 12762/16000
amplify: 12764/16000
amplify: 12766/16000
amplify: 12768/16000
amplify: 12770/16000
amplify: 12772/16000
amplify: 12774/16000
amplify: 12776/16000
amplify: 12778/16000
amplify: 12780/16000
amplify: 12782/16000
amplify: 12784/16000
amplify: 12786/16000
amplify: 12788/16000
amplify: 12790/16000
amplify: 12792/16000
amplify: 12794/16000
amplify: 12796/16000
amplify: 12798/16000
amplify: 12800/16000
amplify: 12802/16000
amplify: 12804/16000
amplify: 12806/16000
amplify: 12808/16000
amplify: 12810/16000
amplify: 12812/16000
amplify: 12814/16000
amplify: 12816/16000
amplify: 12818/16000
amplify: 12820/16000
amplify: 12822/16000
amplify: 12824/16000
amplify: 12826/16000
amplify: 12828/16000
amplify: 12830/16000
amplify: 12832/16000
amplify: 12834/16000
amplify: 12836/16000
amplify: 12838/16000
amplify: 12840/16000
amplify: 12842/16000
amplify: 12844/16000
amplify: 12846/16000
amplify: 12848/16000
amplify: 12850/16000
amplify: 12852/16000
amplify: 12854/16000
amplify: 12856/16000
amplify: 12858/16000
amplify: 12860/16000
amplify: 12862/16000
amplify: 12864/16000
amplify: 12866/16000
amplify: 12868/16000
amplify: 12870/16000
amplify: 12872/16000
amplify: 12874/16000
amplify: 12876/16000
amplify: 12878/16000
amplify: 12880/16000
amplify: 12882/16000
amplify: 12884/16000
amplify: 12886/16000
amplify: 12888/16000
amplify: 12890/16000
amplify: 12892/16000
amplify: 12894/16000
amplify: 12896/16000
amplify: 12898/16000
amplify: 12900/16000
amplify: 12902/16000
amplify: 12904/16000
amplify: 12906/16000
amplify: 12908/16000
amplify: 12910/16000
amplify: 12912/16000
amplify: 12914/16000
amplify: 12916/16000
amplify: 12918/16000
amplify: 12920/16000
amplify: 12922/16000
amplify: 12924/16000
amplify: 12926/16000
amplify: 12928/16000
amplify: 12930/16000
amplify: 12932/16000
amplify: 12934/16000
amplify: 12936/16000
amplify: 12938/16000
amplify: 12940/16000
amplify: 12942/16000
amplify: 12944/16000
amplify: 12946/16000
amplify: 12948/16000
amplify: 12950/16000
amplify: 12952/16000
amplify: 12954/16000
amplify: 12956/16000
amplify: 12958/16000
amplify: 12960/16000
amplify: 12962/16000
amplify: 12964/16000
amplify: 12966/16000
amplify: 12968/16000
amplify: 12970/16000
amplify: 12972/16000
amplify: 12974/16000
amplify: 12976/16000
amplify: 12978/16000
amplify: 12980/16000
amplify: 12982/16000
amplify: 12984/16000
amplify: 12986/16000
amplify: 12988/16000
amplify: 12990/16000
amplify: 12992/16000
amplify: 12994/16000
amplify: 12996/16000
amplify: 12998/16000
amplify: 13000/16000
amplify: 13002/16000
amplify: 13004/16000
amplify: 13006/16000
amplify: 13008/16000
amplify: 13010/16000
amplify: 13012/16000
amplify: 13014/16000
amplify: 13016/16000
amplify: 13018/16000
amplify: 13020/16000
amplify: 13022/16000
amplify: 13024/16000
amplify: 13026/16000
amplify: 13028/16000
amplify: 13030/16000
amplify: 13032/16000
amplify: 13034/16000
amplify: 13036/16000
amplify: 13038/16000
amplify: 13040/16000
amplify: 13042/16000
amplify: 13044/16000
amplify: 13046/16000
amplify: 13048/16000
amplify: 13050/16000
amplify: 13052/16000
amplify: 13054/16000
amplify: 13056/16000
amplify: 13058/16000
amplify: 13060/16000
amplify: 13062/16000
amplify: 13064/16000
amplify: 13066/16000
amplify: 13068/16000
amplify: 13070/16000
amplify: 13072/16000
amplify: 13074/16000
amplify: 13076/16000
amplify: 13078/16000
amplify: 13080/16000
amplify: 13082/16000
amplify: 13084/16000
amplify: 13086/16000
amplify: 13088/16000
amplify: 13090/16000
amplify: 13092/16000
amplify: 13094/16000
amplify: 13096/16000
amplify: 13098/16000
amplify: 13100/16000
amplify: 13102/16000
amplify: 13104/16000
amplify: 13106/16000
amplify: 13108/16000
amplify: 13110/16000
amplify: 13112/16000
amplify: 13114/16000
amplify: 13116/16000
amplify: 13118/16000
amplify: 13120/16000
amplify: 13122/16000
amplify: 13124/16000
amplify: 13126/16000
amplify: 13128/16000
amplify: 13130/16000
amplify: 13132/16000
amplify: 13134/16000
amplify: 13136/16000
amplify: 13138/16000
amplify: 13140/16000
amplify: 13142/16000
amplify: 13144/16000
amplify: 13146/16000
amplify: 13148/16000
amplify: 13150/16000
amplify: 13152/16000
amplify: 13154/16000
amplify: 13156/16000
amplify: 13158/16000
amplify: 13160/16000
amplify: 13162/16000
amplify: 13164/16000
amplify: 13166/16000
amplify: 13168/16000
amplify: 13170/16000
amplify: 13172/16000
amplify: 13174/16000
amplify: 13176/16000
amplify: 13178/16000
amplify: 13180/16000
amplify: 13182/16000
amplify: 13184/16000
amplify: 13186/16000
amplify: 13188/16000
amplify: 13190/16000
amplify: 13192/16000
amplify: 13194/16000
amplify: 13196/16000
amplify: 13198/16000
amplify: 13200/16000
amplify: 13202/16000
amplify: 13204/16000
amplify: 13206/16000
amplify: 13208/16000
amplify: 13210/16000
amplify: 13212/16000
amplify: 13214/16000
amplify: 13216/16000
amplify: 13218/16000
amplify: 13220/16000
amplify: 13222/16000
amplify: 13224/16000
amplify: 13226/16000
amplify: 13228/16000
amplify: 13230/16000
amplify: 13232/16000
amplify: 13234/16000
amplify: 13236/16000
amplify: 13238/16000
amplify: 13240/16000
amplify: 13242/16000
amplify: 13244/16000
amplify: 13246/16000
amplify: 13248/16000
amplify: 13250/16000
amplify: 13252/16000
amplify: 13254/16000
amplify: 13256/16000
amplify: 13258/16000
amplify: 13260/16000
amplify: 13262/16000
amplify: 13264/16000
amplify: 13266/16000
amplify: 13268/16000
amplify: 13270/16000
amplify: 13272/16000
amplify: 13274/16000
amplify: 13276/16000
amplify: 13278/16000
amplify: 13280/16000
amplify: 13282/16000
amplify: 13284/16000
amplify: 13286/16000
amplify: 13288/16000
amplify: 13290/16000
amplify: 13292/16000
amplify: 13294/16000
amplify: 13296/16000
amplify: 13298/16000
amplify: 13300/16000
amplify: 13302/16000
amplify: 13304/16000
amplify: 13306/16000
amplify: 13308/16000
amplify: 13310/16000
amplify: 13312/16000
amplify: 13314/16000
amplify: 13316/16000
amplify: 13318/16000
amplify: 13320/16000
amplify: 13322/16000
amplify: 13324/16000
amplify: 13326/16000
amplify: 13328/16000
amplify: 13330/16000
amplify: 13332/16000
amplify: 13334/16000
amplify: 13336/16000
amplify: 13338/16000
amplify: 13340/16000
amplify: 13342/16000
amplify: 13344/16000
amplify: 13346/16000
amplify: 13348/16000
amplify: 13350/16000
amplify: 13352/16000
amplify: 13354/16000
amplify: 13356/16000
amplify: 13358/16000
amplify: 13360/16000
amplify: 13362/16000
amplify: 13364/16000
amplify: 13366/16000
amplify: 13368/16000
amplify: 13370/16000
amplify: 13372/16000
amplify: 13374/16000
amplify: 13376/16000
amplify: 13378/16000
amplify: 13380/16000
amplify: 13382/16000
amplify: 13384/16000
amplify: 13386/16000
amplify: 13388/16000
amplify: 13390/16000
amplify: 13392/16000
amplify: 13394/16000
amplify: 13396/16000
amplify: 13398/16000
amplify: 13400/16000
amplify: 13402/16000
amplify: 13404/16000

amplify: 13406/16000
amplify: 13408/16000
amplify: 13410/16000
amplify: 13412/16000
amplify: 13414/16000
amplify: 13416/16000
amplify: 13418/16000
amplify: 13420/16000
amplify: 13422/16000
amplify: 13424/16000
amplify: 13426/16000
amplify: 13428/16000
amplify: 13430/16000
amplify: 13432/16000
amplify: 13434/16000
amplify: 13436/16000
amplify: 13438/16000
amplify: 13440/16000
amplify: 13442/16000
amplify: 13444/16000
amplify: 13446/16000
amplify: 13448/16000
amplify: 13450/16000
amplify: 13452/16000
amplify: 13454/16000
amplify: 13456/16000
amplify: 13458/16000
amplify: 13460/16000
amplify: 13462/16000
amplify: 13464/16000
amplify: 13466/16000
amplify: 13468/16000
amplify: 13470/16000
amplify: 13472/16000
amplify: 13474/16000
amplify: 13476/16000
amplify: 13478/16000
amplify: 13480/16000
amplify: 13482/16000
amplify: 13484/16000
amplify: 13486/16000
amplify: 13488/16000
amplify: 13490/16000
amplify: 13492/16000
amplify: 13494/16000
amplify: 13496/16000
amplify: 13498/16000
amplify: 13500/16000
amplify: 13502/16000
amplify: 13504/16000
amplify: 13506/16000
amplify: 13508/16000
amplify: 13510/16000
amplify: 13512/16000
amplify: 13514/16000
amplify: 13516/16000
amplify: 13518/16000
amplify: 13520/16000
amplify: 13522/16000
amplify: 13524/16000
amplify: 13526/16000
amplify: 13528/16000
amplify: 13530/16000
amplify: 13532/16000
amplify: 13534/16000
amplify: 13536/16000
amplify: 13538/16000
amplify: 13540/16000
amplify: 13542/16000
amplify: 13544/16000
amplify: 13546/16000
amplify: 13548/16000
amplify: 13550/16000
amplify: 13552/16000
amplify: 13554/16000
amplify: 13556/16000
amplify: 13558/16000
amplify: 13560/16000
amplify: 13562/16000
amplify: 13564/16000
amplify: 13566/16000
amplify: 13568/16000
amplify: 13570/16000
amplify: 13572/16000
amplify: 13574/16000
amplify: 13576/16000
amplify: 13578/16000
amplify: 13580/16000
amplify: 13582/16000
amplify: 13584/16000
amplify: 13586/16000
amplify: 13588/16000
amplify: 13590/16000
amplify: 13592/16000
amplify: 13594/16000
amplify: 13596/16000
amplify: 13598/16000
amplify: 13600/16000
amplify: 13602/16000
amplify: 13604/16000
amplify: 13606/16000
amplify: 13608/16000
amplify: 13610/16000
amplify: 13612/16000
amplify: 13614/16000
amplify: 13616/16000
amplify: 13618/16000
amplify: 13620/16000
amplify: 13622/16000
amplify: 13624/16000
amplify: 13626/16000
amplify: 13628/16000
amplify: 13630/16000
amplify: 13632/16000
amplify: 13634/16000
amplify: 13636/16000
amplify: 13638/16000
amplify: 13640/16000
amplify: 13642/16000
amplify: 13644/16000
amplify: 13646/16000
amplify: 13648/16000
amplify: 13650/16000
amplify: 13652/16000
amplify: 13654/16000
amplify: 13656/16000
amplify: 13658/16000
amplify: 13660/16000
amplify: 13662/16000
amplify: 13664/16000
amplify: 13666/16000
amplify: 13668/16000
amplify: 13670/16000
amplify: 13672/16000
amplify: 13674/16000
amplify: 13676/16000
amplify: 13678/16000
amplify: 13680/16000
amplify: 13682/16000
amplify: 13684/16000
amplify: 13686/16000
amplify: 13688/16000
amplify: 13690/16000
amplify: 13692/16000
amplify: 13694/16000
amplify: 13696/16000
amplify: 13698/16000
amplify: 13700/16000
amplify: 13702/16000
amplify: 13704/16000
amplify: 13706/16000
amplify: 13708/16000
amplify: 13710/16000
amplify: 13712/16000
amplify: 13714/16000
amplify: 13716/16000
amplify: 13718/16000
amplify: 13720/16000
amplify: 13722/16000
amplify: 13724/16000
amplify: 13726/16000
amplify: 13728/16000
amplify: 13730/16000
amplify: 13732/16000
amplify: 13734/16000
amplify: 13736/16000
amplify: 13738/16000
amplify: 13740/16000
amplify: 13742/16000
amplify: 13744/16000
amplify: 13746/16000
amplify: 13748/16000
amplify: 13750/16000
amplify: 13752/16000
amplify: 13754/16000
amplify: 13756/16000
amplify: 13758/16000
amplify: 13760/16000
amplify: 13762/16000
amplify: 13764/16000
amplify: 13766/16000
amplify: 13768/16000
amplify: 13770/16000
amplify: 13772/16000
amplify: 13774/16000
amplify: 13776/16000
amplify: 13778/16000
amplify: 13780/16000
amplify: 13782/16000
amplify: 13784/16000
amplify: 13786/16000
amplify: 13788/16000
amplify: 13790/16000
amplify: 13792/16000
amplify: 13794/16000
amplify: 13796/16000
amplify: 13798/16000
amplify: 13800/16000
amplify: 13802/16000
amplify: 13804/16000
amplify: 13806/16000
amplify: 13808/16000
amplify: 13810/16000
amplify: 13812/16000
amplify: 13814/16000
amplify: 13816/16000
amplify: 13818/16000
amplify: 13820/16000
amplify: 13822/16000
amplify: 13824/16000
amplify: 13826/16000
amplify: 13828/16000
amplify: 13830/16000
amplify: 13832/16000
amplify: 13834/16000
amplify: 13836/16000
amplify: 13838/16000
amplify: 13840/16000
amplify: 13842/16000
amplify: 13844/16000
amplify: 13846/16000
amplify: 13848/16000
amplify: 13850/16000
amplify: 13852/16000
amplify: 13854/16000
amplify: 13856/16000
amplify: 13858/16000
amplify: 13860/16000
amplify: 13862/16000
amplify: 13864/16000
amplify: 13866/16000
amplify: 13868/16000
amplify: 13870/16000
amplify: 13872/16000
amplify: 13874/16000
amplify: 13876/16000
amplify: 13878/16000
amplify: 13880/16000
amplify: 13882/16000
amplify: 13884/16000
amplify: 13886/16000
amplify: 13888/16000
amplify: 13890/16000
amplify: 13892/16000
amplify: 13894/16000
amplify: 13896/16000
amplify: 13898/16000
amplify: 13900/16000
amplify: 13902/16000
amplify: 13904/16000
amplify: 13906/16000
amplify: 13908/16000
amplify: 13910/16000
amplify: 13912/16000
amplify: 13914/16000
amplify: 13916/16000
amplify: 13918/16000
amplify: 13920/16000
amplify: 13922/16000
amplify: 13924/16000
amplify: 13926/16000
amplify: 13928/16000
amplify: 13930/16000
amplify: 13932/16000
amplify: 13934/16000
amplify: 13936/16000
amplify: 13938/16000
amplify: 13940/16000
amplify: 13942/16000
amplify: 13944/16000
amplify: 13946/16000
amplify: 13948/16000
amplify: 13950/16000
amplify: 13952/16000
amplify: 13954/16000
amplify: 13956/16000
amplify: 13958/16000
amplify: 13960/16000
amplify: 13962/16000
amplify: 13964/16000
amplify: 13966/16000
amplify: 13968/16000
amplify: 13970/16000
amplify: 13972/16000
amplify: 13974/16000
amplify: 13976/16000
amplify: 13978/16000
amplify: 13980/16000
amplify: 13982/16000
amplify: 13984/16000
amplify: 13986/16000
amplify: 13988/16000
amplify: 13990/16000
amplify: 13992/16000
amplify: 13994/16000
amplify: 13996/16000
amplify: 13998/16000
amplify: 14000/16000
amplify: 14002/16000
amplify: 14004/16000
amplify: 14006/16000
amplify: 14008/16000
amplify: 14010/16000
amplify: 14012/16000
amplify: 14014/16000
amplify: 14016/16000
amplify: 14018/16000
amplify: 14020/16000
amplify: 14022/16000
amplify: 14024/16000
amplify: 14026/16000
amplify: 14028/16000
amplify: 14030/16000
amplify: 14032/16000
amplify: 14034/16000
amplify: 14036/16000
amplify: 14038/16000
amplify: 14040/16000
amplify: 14042/16000
amplify: 14044/16000
amplify: 14046/16000
amplify: 14048/16000
amplify: 14050/16000
amplify: 14052/16000
amplify: 14054/16000
amplify: 14056/16000
amplify: 14058/16000
amplify: 14060/16000
amplify: 14062/16000
amplify: 14064/16000
amplify: 14066/16000
amplify: 14068/16000
amplify: 14070/16000
amplify: 14072/16000
amplify: 14074/16000
amplify: 14076/16000
amplify: 14078/16000
amplify: 14080/16000
amplify: 14082/16000
amplify: 14084/16000
amplify: 14086/16000
amplify: 14088/16000
amplify: 14090/16000
amplify: 14092/16000
amplify: 14094/16000
amplify: 14096/16000
amplify: 14098/16000
amplify: 14100/16000
amplify: 14102/16000
amplify: 14104/16000
amplify: 14106/16000
amplify: 14108/16000
amplify: 14110/16000
amplify: 14112/16000
amplify: 14114/16000
amplify: 14116/16000
amplify: 14118/16000
amplify: 14120/16000
amplify: 14122/16000
amplify: 14124/16000
amplify: 14126/16000
amplify: 14128/16000
amplify: 14130/16000
amplify: 14132/16000
amplify: 14134/16000
amplify: 14136/16000
amplify: 14138/16000
amplify: 14140/16000
amplify: 14142/16000
amplify: 14144/16000
amplify: 14146/16000
amplify: 14148/16000
amplify: 14150/16000
amplify: 14152/16000
amplify: 14154/16000
amplify: 14156/16000
amplify: 14158/16000
amplify: 14160/16000
amplify: 14162/16000
amplify: 14164/16000
amplify: 14166/16000
amplify: 14168/16000
amplify: 14170/16000
amplify: 14172/16000
amplify: 14174/16000
amplify: 14176/16000
amplify: 14178/16000
amplify: 14180/16000
amplify: 14182/16000
amplify: 14184/16000
amplify: 14186/16000

amplify: 14188/16000
amplify: 14190/16000
amplify: 14192/16000
amplify: 14194/16000
amplify: 14196/16000
amplify: 14198/16000
amplify: 14200/16000
amplify: 14202/16000
amplify: 14204/16000
amplify: 14206/16000
amplify: 14208/16000
amplify: 14210/16000
amplify: 14212/16000
amplify: 14214/16000
amplify: 14216/16000
amplify: 14218/16000
amplify: 14220/16000
amplify: 14222/16000
amplify: 14224/16000
amplify: 14226/16000
amplify: 14228/16000
amplify: 14230/16000
amplify: 14232/16000
amplify: 14234/16000
amplify: 14236/16000
amplify: 14238/16000
amplify: 14240/16000
amplify: 14242/16000
amplify: 14244/16000
amplify: 14246/16000
amplify: 14248/16000
amplify: 14250/16000
amplify: 14252/16000
amplify: 14254/16000
amplify: 14256/16000
amplify: 14258/16000
amplify: 14260/16000
amplify: 14262/16000
amplify: 14264/16000
amplify: 14266/16000
amplify: 14268/16000
amplify: 14270/16000
amplify: 14272/16000
amplify: 14274/16000
amplify: 14276/16000
amplify: 14278/16000
amplify: 14280/16000
amplify: 14282/16000
amplify: 14284/16000
amplify: 14286/16000
amplify: 14288/16000
amplify: 14290/16000
amplify: 14292/16000
amplify: 14294/16000
amplify: 14296/16000
amplify: 14298/16000
amplify: 14300/16000
amplify: 14302/16000
amplify: 14304/16000
amplify: 14306/16000
amplify: 14308/16000
amplify: 14310/16000
amplify: 14312/16000
amplify: 14314/16000
amplify: 14316/16000
amplify: 14318/16000
amplify: 14320/16000
amplify: 14322/16000
amplify: 14324/16000
amplify: 14326/16000
amplify: 14328/16000
amplify: 14330/16000
amplify: 14332/16000
amplify: 14334/16000
amplify: 14336/16000
amplify: 14338/16000
amplify: 14340/16000
amplify: 14342/16000
amplify: 14344/16000
amplify: 14346/16000
amplify: 14348/16000
amplify: 14350/16000
amplify: 14352/16000
amplify: 14354/16000
amplify: 14356/16000
amplify: 14358/16000
amplify: 14360/16000
amplify: 14362/16000
amplify: 14364/16000
amplify: 14366/16000
amplify: 14368/16000
amplify: 14370/16000
amplify: 14372/16000
amplify: 14374/16000
amplify: 14376/16000
amplify: 14378/16000
amplify: 14380/16000
amplify: 14382/16000
amplify: 14384/16000
amplify: 14386/16000
amplify: 14388/16000
amplify: 14390/16000
amplify: 14392/16000
amplify: 14394/16000
amplify: 14396/16000
amplify: 14398/16000
amplify: 14400/16000
amplify: 14402/16000
amplify: 14404/16000
amplify: 14406/16000
amplify: 14408/16000
amplify: 14410/16000
amplify: 14412/16000
amplify: 14414/16000
amplify: 14416/16000
amplify: 14418/16000
amplify: 14420/16000
amplify: 14422/16000
amplify: 14424/16000
amplify: 14426/16000
amplify: 14428/16000
amplify: 14430/16000
amplify: 14432/16000
amplify: 14434/16000
amplify: 14436/16000
amplify: 14438/16000
amplify: 14440/16000
amplify: 14442/16000
amplify: 14444/16000
amplify: 14446/16000
amplify: 14448/16000
amplify: 14450/16000
amplify: 14452/16000
amplify: 14454/16000
amplify: 14456/16000
amplify: 14458/16000
amplify: 14460/16000
amplify: 14462/16000
amplify: 14464/16000
amplify: 14466/16000
amplify: 14468/16000
amplify: 14470/16000
amplify: 14472/16000
amplify: 14474/16000
amplify: 14476/16000
amplify: 14478/16000
amplify: 14480/16000
amplify: 14482/16000
amplify: 14484/16000
amplify: 14486/16000
amplify: 14488/16000
amplify: 14490/16000
amplify: 14492/16000
amplify: 14494/16000
amplify: 14496/16000
amplify: 14498/16000
amplify: 14500/16000
amplify: 14502/16000
amplify: 14504/16000
amplify: 14506/16000
amplify: 14508/16000
amplify: 14510/16000
amplify: 14512/16000
amplify: 14514/16000
amplify: 14516/16000
amplify: 14518/16000
amplify: 14520/16000
amplify: 14522/16000
amplify: 14524/16000
amplify: 14526/16000
amplify: 14528/16000
amplify: 14530/16000
amplify: 14532/16000
amplify: 14534/16000
amplify: 14536/16000
amplify: 14538/16000
amplify: 14540/16000
amplify: 14542/16000
amplify: 14544/16000
amplify: 14546/16000
amplify: 14548/16000
amplify: 14550/16000
amplify: 14552/16000
amplify: 14554/16000
amplify: 14556/16000
amplify: 14558/16000
amplify: 14560/16000
amplify: 14562/16000
amplify: 14564/16000
amplify: 14566/16000
amplify: 14568/16000
amplify: 14570/16000
amplify: 14572/16000
amplify: 14574/16000
amplify: 14576/16000
amplify: 14578/16000
amplify: 14580/16000
amplify: 14582/16000
amplify: 14584/16000
amplify: 14586/16000
amplify: 14588/16000
amplify: 14590/16000
amplify: 14592/16000
amplify: 14594/16000
amplify: 14596/16000
amplify: 14598/16000
amplify: 14600/16000
amplify: 14602/16000
amplify: 14604/16000
amplify: 14606/16000
amplify: 14608/16000
amplify: 14610/16000
amplify: 14612/16000
amplify: 14614/16000
amplify: 14616/16000
amplify: 14618/16000
amplify: 14620/16000
amplify: 14622/16000
amplify: 14624/16000
amplify: 14626/16000
amplify: 14628/16000
amplify: 14630/16000
amplify: 14632/16000
amplify: 14634/16000
amplify: 14636/16000
amplify: 14638/16000
amplify: 14640/16000
amplify: 14642/16000
amplify: 14644/16000
amplify: 14646/16000
amplify: 14648/16000
amplify: 14650/16000
amplify: 14652/16000
amplify: 14654/16000
amplify: 14656/16000
amplify: 14658/16000
amplify: 14660/16000
amplify: 14662/16000
amplify: 14664/16000
amplify: 14666/16000
amplify: 14668/16000
amplify: 14670/16000
amplify: 14672/16000
amplify: 14674/16000
amplify: 14676/16000
amplify: 14678/16000
amplify: 14680/16000
amplify: 14682/16000
amplify: 14684/16000
amplify: 14686/16000
amplify: 14688/16000
amplify: 14690/16000
amplify: 14692/16000
amplify: 14694/16000
amplify: 14696/16000
amplify: 14698/16000
amplify: 14700/16000
amplify: 14702/16000
amplify: 14704/16000
amplify: 14706/16000
amplify: 14708/16000
amplify: 14710/16000
amplify: 14712/16000
amplify: 14714/16000
amplify: 14716/16000
amplify: 14718/16000
amplify: 14720/16000
amplify: 14722/16000
amplify: 14724/16000
amplify: 14726/16000
amplify: 14728/16000
amplify: 14730/16000
amplify: 14732/16000
amplify: 14734/16000
amplify: 14736/16000
amplify: 14738/16000
amplify: 14740/16000
amplify: 14742/16000
amplify: 14744/16000
amplify: 14746/16000
amplify: 14748/16000
amplify: 14750/16000
amplify: 14752/16000
amplify: 14754/16000
amplify: 14756/16000
amplify: 14758/16000
amplify: 14760/16000
amplify: 14762/16000
amplify: 14764/16000
amplify: 14766/16000
amplify: 14768/16000
amplify: 14770/16000
amplify: 14772/16000
amplify: 14774/16000
amplify: 14776/16000
amplify: 14778/16000
amplify: 14780/16000
amplify: 14782/16000
amplify: 14784/16000
amplify: 14786/16000
amplify: 14788/16000
amplify: 14790/16000
amplify: 14792/16000
amplify: 14794/16000
amplify: 14796/16000
amplify: 14798/16000
amplify: 14800/16000
amplify: 14802/16000
amplify: 14804/16000
amplify: 14806/16000
amplify: 14808/16000
amplify: 14810/16000
amplify: 14812/16000
amplify: 14814/16000
amplify: 14816/16000
amplify: 14818/16000
amplify: 14820/16000
amplify: 14822/16000
amplify: 14824/16000
amplify: 14826/16000
amplify: 14828/16000
amplify: 14830/16000
amplify: 14832/16000
amplify: 14834/16000
amplify: 14836/16000
amplify: 14838/16000
amplify: 14840/16000
amplify: 14842/16000
amplify: 14844/16000
amplify: 14846/16000
amplify: 14848/16000
amplify: 14850/16000
amplify: 14852/16000
amplify: 14854/16000
amplify: 14856/16000
amplify: 14858/16000
amplify: 14860/16000
amplify: 14862/16000
amplify: 14864/16000
amplify: 14866/16000
amplify: 14868/16000
amplify: 14870/16000
amplify: 14872/16000
amplify: 14874/16000
amplify: 14876/16000
amplify: 14878/16000
amplify: 14880/16000
amplify: 14882/16000
amplify: 14884/16000
amplify: 14886/16000
amplify: 14888/16000
amplify: 14890/16000
amplify: 14892/16000
amplify: 14894/16000
amplify: 14896/16000
amplify: 14898/16000
amplify: 14900/16000
amplify: 14902/16000
amplify: 14904/16000
amplify: 14906/16000
amplify: 14908/16000
amplify: 14910/16000
amplify: 14912/16000
amplify: 14914/16000
amplify: 14916/16000
amplify: 14918/16000
amplify: 14920/16000
amplify: 14922/16000
amplify: 14924/16000
amplify: 14926/16000
amplify: 14928/16000
amplify: 14930/16000
amplify: 14932/16000
amplify: 14934/16000
amplify: 14936/16000
amplify: 14938/16000
amplify: 14940/16000
amplify: 14942/16000
amplify: 14944/16000
amplify: 14946/16000
amplify: 14948/16000
amplify: 14950/16000
amplify: 14952/16000
amplify: 14954/16000
amplify: 14956/16000
amplify: 14958/16000
amplify: 14960/16000
amplify: 14962/16000
amplify: 14964/16000
amplify: 14966/16000
amplify: 14968/16000

amplify: 14970/16000
amplify: 14972/16000
amplify: 14974/16000
amplify: 14976/16000
amplify: 14978/16000
amplify: 14980/16000
amplify: 14982/16000
amplify: 14984/16000
amplify: 14986/16000
amplify: 14988/16000
amplify: 14990/16000
amplify: 14992/16000
amplify: 14994/16000
amplify: 14996/16000
amplify: 14998/16000
amplify: 15000/16000
amplify: 15002/16000
amplify: 15004/16000
amplify: 15006/16000
amplify: 15008/16000
amplify: 15010/16000
amplify: 15012/16000
amplify: 15014/16000
amplify: 15016/16000
amplify: 15018/16000
amplify: 15020/16000
amplify: 15022/16000
amplify: 15024/16000
amplify: 15026/16000
amplify: 15028/16000
amplify: 15030/16000
amplify: 15032/16000
amplify: 15034/16000
amplify: 15036/16000
amplify: 15038/16000
amplify: 15040/16000
amplify: 15042/16000
amplify: 15044/16000
amplify: 15046/16000
amplify: 15048/16000
amplify: 15050/16000
amplify: 15052/16000
amplify: 15054/16000
amplify: 15056/16000
amplify: 15058/16000
amplify: 15060/16000
amplify: 15062/16000
amplify: 15064/16000
amplify: 15066/16000
amplify: 15068/16000
amplify: 15070/16000
amplify: 15072/16000
amplify: 15074/16000
amplify: 15076/16000
amplify: 15078/16000
amplify: 15080/16000
amplify: 15082/16000
amplify: 15084/16000
amplify: 15086/16000
amplify: 15088/16000
amplify: 15090/16000
amplify: 15092/16000
amplify: 15094/16000
amplify: 15096/16000
amplify: 15098/16000
amplify: 15100/16000
amplify: 15102/16000
amplify: 15104/16000
amplify: 15106/16000
amplify: 15108/16000
amplify: 15110/16000
amplify: 15112/16000
amplify: 15114/16000
amplify: 15116/16000
amplify: 15118/16000
amplify: 15120/16000
amplify: 15122/16000
amplify: 15124/16000
amplify: 15126/16000
amplify: 15128/16000
amplify: 15130/16000
amplify: 15132/16000
amplify: 15134/16000
amplify: 15136/16000
amplify: 15138/16000
amplify: 15140/16000
amplify: 15142/16000
amplify: 15144/16000
amplify: 15146/16000
amplify: 15148/16000
amplify: 15150/16000
amplify: 15152/16000
amplify: 15154/16000
amplify: 15156/16000
amplify: 15158/16000
amplify: 15160/16000
amplify: 15162/16000
amplify: 15164/16000
amplify: 15166/16000
amplify: 15168/16000
amplify: 15170/16000
amplify: 15172/16000
amplify: 15174/16000
amplify: 15176/16000
amplify: 15178/16000
amplify: 15180/16000
amplify: 15182/16000
amplify: 15184/16000
amplify: 15186/16000
amplify: 15188/16000
amplify: 15190/16000
amplify: 15192/16000
amplify: 15194/16000
amplify: 15196/16000
amplify: 15198/16000
amplify: 15200/16000
amplify: 15202/16000
amplify: 15204/16000
amplify: 15206/16000
amplify: 15208/16000
amplify: 15210/16000
amplify: 15212/16000
amplify: 15214/16000
amplify: 15216/16000
amplify: 15218/16000
amplify: 15220/16000
amplify: 15222/16000
amplify: 15224/16000
amplify: 15226/16000
amplify: 15228/16000
amplify: 15230/16000
amplify: 15232/16000
amplify: 15234/16000
amplify: 15236/16000
amplify: 15238/16000
amplify: 15240/16000
amplify: 15242/16000
amplify: 15244/16000
amplify: 15246/16000
amplify: 15248/16000
amplify: 15250/16000
amplify: 15252/16000
amplify: 15254/16000
amplify: 15256/16000
amplify: 15258/16000
amplify: 15260/16000
amplify: 15262/16000
amplify: 15264/16000
amplify: 15266/16000
amplify: 15268/16000
amplify: 15270/16000
amplify: 15272/16000
amplify: 15274/16000
amplify: 15276/16000
amplify: 15278/16000
amplify: 15280/16000
amplify: 15282/16000
amplify: 15284/16000
amplify: 15286/16000
amplify: 15288/16000
amplify: 15290/16000
amplify: 15292/16000
amplify: 15294/16000
amplify: 15296/16000
amplify: 15298/16000
amplify: 15300/16000
amplify: 15302/16000
amplify: 15304/16000
amplify: 15306/16000
amplify: 15308/16000
amplify: 15310/16000
amplify: 15312/16000
amplify: 15314/16000
amplify: 15316/16000
amplify: 15318/16000
amplify: 15320/16000
amplify: 15322/16000
amplify: 15324/16000
amplify: 15326/16000
amplify: 15328/16000
amplify: 15330/16000
amplify: 15332/16000
amplify: 15334/16000
amplify: 15336/16000
amplify: 15338/16000
amplify: 15340/16000
amplify: 15342/16000
amplify: 15344/16000
amplify: 15346/16000
amplify: 15348/16000
amplify: 15350/16000
amplify: 15352/16000
amplify: 15354/16000
amplify: 15356/16000
amplify: 15358/16000
amplify: 15360/16000
amplify: 15362/16000
amplify: 15364/16000
amplify: 15366/16000
amplify: 15368/16000
amplify: 15370/16000
amplify: 15372/16000
amplify: 15374/16000
amplify: 15376/16000
amplify: 15378/16000
amplify: 15380/16000
amplify: 15382/16000
amplify: 15384/16000
amplify: 15386/16000
amplify: 15388/16000
amplify: 15390/16000
amplify: 15392/16000
amplify: 15394/16000
amplify: 15396/16000
amplify: 15398/16000
amplify: 15400/16000
amplify: 15402/16000
amplify: 15404/16000
amplify: 15406/16000
amplify: 15408/16000
amplify: 15410/16000
amplify: 15412/16000
amplify: 15414/16000
amplify: 15416/16000
amplify: 15418/16000
amplify: 15420/16000
amplify: 15422/16000
amplify: 15424/16000
amplify: 15426/16000
amplify: 15428/16000
amplify: 15430/16000
amplify: 15432/16000
amplify: 15434/16000
amplify: 15436/16000
amplify: 15438/16000
amplify: 15440/16000
amplify: 15442/16000
amplify: 15444/16000
amplify: 15446/16000
amplify: 15448/16000
amplify: 15450/16000
amplify: 15452/16000
amplify: 15454/16000
amplify: 15456/16000
amplify: 15458/16000
amplify: 15460/16000
amplify: 15462/16000
amplify: 15464/16000
amplify: 15466/16000
amplify: 15468/16000
amplify: 15470/16000
amplify: 15472/16000
amplify: 15474/16000
amplify: 15476/16000
amplify: 15478/16000
amplify: 15480/16000
amplify: 15482/16000
amplify: 15484/16000
amplify: 15486/16000
amplify: 15488/16000
amplify: 15490/16000
amplify: 15492/16000
amplify: 15494/16000
amplify: 15496/16000
amplify: 15498/16000
amplify: 15500/16000
amplify: 15502/16000
amplify: 15504/16000
amplify: 15506/16000
amplify: 15508/16000
amplify: 15510/16000
amplify: 15512/16000
amplify: 15514/16000
amplify: 15516/16000
amplify: 15518/16000
amplify: 15520/16000
amplify: 15522/16000
amplify: 15524/16000
amplify: 15526/16000
amplify: 15528/16000
amplify: 15530/16000
amplify: 15532/16000
amplify: 15534/16000
amplify: 15536/16000
amplify: 15538/16000
amplify: 15540/16000
amplify: 15542/16000
amplify: 15544/16000
amplify: 15546/16000
amplify: 15548/16000
amplify: 15550/16000
amplify: 15552/16000
amplify: 15554/16000
amplify: 15556/16000
amplify: 15558/16000
amplify: 15560/16000
amplify: 15562/16000
amplify: 15564/16000
amplify: 15566/16000
amplify: 15568/16000
amplify: 15570/16000
amplify: 15572/16000
amplify: 15574/16000
amplify: 15576/16000
amplify: 15578/16000
amplify: 15580/16000
amplify: 15582/16000
amplify: 15584/16000
amplify: 15586/16000
amplify: 15588/16000
amplify: 15590/16000
amplify: 15592/16000
amplify: 15594/16000
amplify: 15596/16000
amplify: 15598/16000
amplify: 15600/16000
amplify: 15602/16000
amplify: 15604/16000
amplify: 15606/16000
amplify: 15608/16000
amplify: 15610/16000
amplify: 15612/16000
amplify: 15614/16000
amplify: 15616/16000
amplify: 15618/16000
amplify: 15620/16000
amplify: 15622/16000
amplify: 15624/16000
amplify: 15626/16000
amplify: 15628/16000
amplify: 15630/16000
amplify: 15632/16000
amplify: 15634/16000
amplify: 15636/16000
amplify: 15638/16000
amplify: 15640/16000
amplify: 15642/16000
amplify: 15644/16000
amplify: 15646/16000
amplify: 15648/16000
amplify: 15650/16000
amplify: 15652/16000
amplify: 15654/16000
amplify: 15656/16000
amplify: 15658/16000
amplify: 15660/16000
amplify: 15662/16000
amplify: 15664/16000
amplify: 15666/16000
amplify: 15668/16000
amplify: 15670/16000
amplify: 15672/16000
amplify: 15674/16000
amplify: 15676/16000
amplify: 15678/16000
amplify: 15680/16000
amplify: 15682/16000
amplify: 15684/16000
amplify: 15686/16000
amplify: 15688/16000
amplify: 15690/16000
amplify: 15692/16000
amplify: 15694/16000
amplify: 15696/16000
amplify: 15698/16000
amplify: 15700/16000
amplify: 15702/16000
amplify: 15704/16000
amplify: 15706/16000
amplify: 15708/16000
amplify: 15710/16000
amplify: 15712/16000
amplify: 15714/16000
amplify: 15716/16000
amplify: 15718/16000
amplify: 15720/16000
amplify: 15722/16000
amplify: 15724/16000
amplify: 15726/16000
amplify: 15728/16000
amplify: 15730/16000
amplify: 15732/16000
amplify: 15734/16000
amplify: 15736/16000
amplify: 15738/16000
amplify: 15740/16000
amplify: 15742/16000
amplify: 15744/16000
amplify: 15746/16000
amplify: 15748/16000
amplify: 15750/16000

amplify: 15752/16000
amplify: 15754/16000
amplify: 15756/16000
amplify: 15758/16000
amplify: 15760/16000
amplify: 15762/16000
amplify: 15764/16000
amplify: 15766/16000
amplify: 15768/16000
amplify: 15770/16000
amplify: 15772/16000
amplify: 15774/16000
amplify: 15776/16000
amplify: 15778/16000
amplify: 15780/16000
amplify: 15782/16000
amplify: 15784/16000
amplify: 15786/16000
amplify: 15788/16000
amplify: 15790/16000
amplify: 15792/16000
amplify: 15794/16000
amplify: 15796/16000
amplify: 15798/16000
amplify: 15800/16000
amplify: 15802/16000
amplify: 15804/16000
amplify: 15806/16000
amplify: 15808/16000
amplify: 15810/16000
amplify: 15812/16000
amplify: 15814/16000
amplify: 15816/16000
amplify: 15818/16000
amplify: 15820/16000
amplify: 15822/16000
amplify: 15824/16000
amplify: 15826/16000
amplify: 15828/16000
amplify: 15830/16000
amplify: 15832/16000
amplify: 15834/16000
amplify: 15836/16000
amplify: 15838/16000
amplify: 15840/16000
amplify: 15842/16000
amplify: 15844/16000
amplify: 15846/16000
amplify: 15848/16000
amplify: 15850/16000
amplify: 15852/16000
amplify: 15854/16000
amplify: 15856/16000
amplify: 15858/16000
amplify: 15860/16000
amplify: 15862/16000
amplify: 15864/16000
amplify: 15866/16000
amplify: 15868/16000
amplify: 15870/16000
amplify: 15872/16000
amplify: 15874/16000
amplify: 15876/16000
amplify: 15878/16000
amplify: 15880/16000
amplify: 15882/16000
amplify: 15884/16000
amplify: 15886/16000
amplify: 15888/16000
amplify: 15890/16000
amplify: 15892/16000
amplify: 15894/16000
amplify: 15896/16000
amplify: 15898/16000
amplify: 15900/16000
amplify: 15902/16000
amplify: 15904/16000
amplify: 15906/16000
amplify: 15908/16000
amplify: 15910/16000
amplify: 15912/16000
amplify: 15914/16000
amplify: 15916/16000
amplify: 15918/16000
amplify: 15920/16000
amplify: 15922/16000
amplify: 15924/16000
amplify: 15926/16000
amplify: 15928/16000
amplify: 15930/16000
amplify: 15932/16000
amplify: 15934/16000
amplify: 15936/16000
amplify: 15938/16000
amplify: 15940/16000
amplify: 15942/16000
amplify: 15944/16000
amplify: 15946/16000
amplify: 15948/16000
amplify: 15950/16000
amplify: 15952/16000
amplify: 15954/16000
amplify: 15956/16000
amplify: 15958/16000
amplify: 15960/16000
amplify: 15962/16000
amplify: 15964/16000
amplify: 15966/16000
amplify: 15968/16000
amplify: 15970/16000
amplify: 15972/16000
amplify: 15974/16000
amplify: 15976/16000
amplify: 15978/16000
amplify: 15980/16000
amplify: 15982/16000
amplify: 15984/16000
amplify: 15986/16000
amplify: 15988/16000
amplify: 15990/16000
amplify: 15992/16000
amplify: 15994/16000
amplify: 15996/16000
amplify: 15998/16000
amplify: 16000/16000
Causal validation per label-feature pair:

,label_word,feature_idx,label_specific_rank,stable_by_rule,causal_group,baseline_label_specific_pre_gap,retention_rate_top_20,min_over_baseline,feature_active_prompt_fraction,baseline_p_label_pct,ablated_p_label_pct,amplified_p_label_pct,ablation_decrease_pp,amplification_increase_pp,frac_prompts_ablation_decreases_p_label,frac_prompts_amplification_increases_p_label
40,Business,16288,1,True,multi-prefix stable,18.021406,1.000,0.915144,0.810,70.431077,70.105240,71.882538,0.325838,1.451457,0.570,0.755
41,Business,5333,2,True,multi-prefix stable,13.143958,1.000,0.997345,0.365,70.431077,70.320312,71.198769,0.110770,0.767689,0.235,0.595
42,Business,5349,3,True,multi-prefix stable,10.461979,1.000,1.000000,0.480,70.431077,70.426292,72.086044,0.004788,1.654964,0.255,0.735
43,Business,1295,4,True,multi-prefix stable,9.786667,1.000,0.698910,1.000,70.431077,70.175079,70.401054,0.256005,-0.030027,0.490,0.440
44,Business,16159,5,True,multi-prefix stable,8.708261,1.000,0.895432,0.595,70.431077,70.487350,69.954430,-0.056266,-0.476649,0.285,0.400
45,Business,3678,6,True,multi-prefix stable,7.642838,1.000,0.855079,0.465,70.431077,70.319664,71.445084,0.111420,1.014002,0.325,0.765
46,Business,3375,7,True,multi-prefix stable,7.496718,1.000,1.000000,0.870,70.431077,70.270531,71.356133,0.160549,0.925054,0.450,0.580
47,Business,2039,8,True,multi-prefix stable,6.826914,1.000,0.950284,0.865,70.431077,69.499290,78.367104,0.931794,7.936026,0.670,0.880
48,Business,15267,9,True,multi-prefix stable,6.668333,1.000,0.854974,0.000,70.431077,70.431084,70.868896,0.000000,0.437812,0.000,0.415
49,Business,14960,10,True,multi-prefix stable,6.380482,1.000,0.841254,0.420,70.431077,70.436386,72.307350,-0.005302,1.876268,0.200,0.690
50,Business,10303,11,True,multi-prefix stable,5.940000,1.000,0.784775,0.275,70.431077,70.499664,70.362701,-0.068582,-0.068383,0.140,0.585
51,Business,10090,12,True,multi-prefix stable,5.499636,1.000,0.964464,0.140,70.431077,70.428825,73.838898,0.002254,3.407817,0.070,0.860
52,Business,6193,13,True,multi-prefix stable,5.424583,1.000,0.921029,0.395,70.431077,70.398582,73.120605,0.032497,2.689524,0.205,0.800
53,Business,10489,14,True,multi-prefix stable,5.201589,1.000,0.994893,0.235,70.431077,70.361465,71.200340,0.069614,0.769256,0.120,0.610
54,Business,8901,15,True,multi-prefix stable,4.534010,1.000,0.806325,0.620,70.431077,70.230751,71.485687,0.200331,1.054606,0.390,0.735
55,Business,10483,16,True,multi-prefix stable,4.466042,1.000,0.900534,0.260,70.431077,70.266083,72.119232,0.165002,1.688150,0.165,0.780
56,Business,8875,17,True,multi-prefix stable,4.051068,1.000,0.888449,0.275,70.431077,70.435280,70.452286,-0.004197,0.021205,0.110,0.495
20,Sports,8298,1,True,multi-prefix stable,24.050652,1.000,0.903064,0.880,98.260069,98.196587,98.356529,0.063484,0.096463,0.510,0.630
21,Sports,3408,2,True,multi-prefix stable,22.800678,1.000,0.980879,0.840,98.260069,98.237213,98.210556,0.022852,-0.049507,0.410,0.295
22,Sports,13985,3,True,multi-prefix stable,16.599998,1.000,0.881928,0.000,98.260069,98.260063,98.383789,0.000000,0.123725,0.000,0.600
23,Sports,1740,4,True,multi-prefix stable,14.022396,1.000,0.847929,0.775,98.260069,98.226875,98.324532,0.033192,0.064463,0.370,0.520
24,Sports,14142,5,True,multi-prefix stable,11.956979,1.000,0.984423,0.805,98.260069,98.151962,98.614182,0.108105,0.354118,0.465,0.820
25,Sports,5092,6,True,multi-prefix stable,9.999765,1.000,0.787270,0.590,98.260069,98.260597,98.374069,-0.000533,0.114005,0.245,0.555
26,Sports,5672,7,True,multi-prefix stable,9.779193,1.000,0.974758,0.660,98.260069,98.204300,98.725433,0.055765,0.465363,0.350,0.805
27,Sports,9289,8,True,multi-prefix stable,9.066875,1.000,0.840445,0.605,98.260069,98.236931,98.238289,0.023140,-0.021775,0.210,0.270
28,Sports,2671,9,True,multi-prefix stable,8.329636,1.000,0.760047,0.550,98.260069,98.262611,98.181244,-0.002544,-0.078819,0.265,0.445
29,Sports,3375,10,True,multi-prefix stable,8.309010,1.000,0.684341,0.855,98.260069,98.273804,98.137413,-0.013740,-0.122651,0.300,0.220
30,Sports,2999,11,True,multi-prefix stable,8.238750,1.000,0.884034,0.895,98.260069,98.292168,98.161057,-0.032102,-0.099008,0.435,0.350
31,Sports,5104,12,True,multi-prefix stable,7.969713,1.000,0.869565,0.510,98.260069,98.250259,98.679901,0.009808,0.419838,0.265,0.750
32,Sports,1774,13,True,multi-prefix stable,6.919844,1.000,0.999082,0.065,98.260069,98.259132,98.655746,0.000938,0.395677,0.035,0.785
33,Sports,45,14,True,multi-prefix stable,6.072083,1.000,0.923073,0.795,98.260069,98.258232,98.306435,0.001831,0.046366,0.410,0.675
34,Sports,13203,15,True,multi-prefix stable,5.700078,1.000,0.848070,0.430,98.260069,98.259407,98.617851,0.000659,0.357786,0.205,0.475
35,Sports,13093,16,True,multi-prefix stable,5.619583,1.000,0.886391,0.190,98.260069,98.260452,98.187439,-0.000385,-0.072629,0.075,0.355
60,Technology,1831,1,True,multi-prefix stable,18.446405,1.000,0.929656,0.410,66.787153,66.811913,67.559990,-0.024758,0.772837,0.150,0.575
61,Technology,3442,2,True,multi-prefix stable,14.010313,1.000,0.933159,0.550,66.787153,66.662361,67.203827,0.124792,0.416674,0.310,0.725
62,Technology,16159,3,True,multi-prefix stable,12.843471,1.000,0.786597,0.675,66.787153,66.791908,67.320854,-0.004751,0.533697,0.385,0.725
63,Technology,7700,4,True,multi-prefix stable,11.832865,1.000,0.978071,0.905,66.787153,66.454735,67.737709,0.332423,0.950552,0.550,0.645
64,Technology,9247,5,True,multi-prefix stable,11.271146,1.000,0.888367,0.455,66.787153,66.770149,67.374069,0.017007,0.586917,0.190,0.600
65,Technology,8875,6,True,multi-prefix stable,9.317318,1.000,0.767970,0.535,66.787153,66.785782,67.423996,0.001376,0.636846,0.305,0.580
66,Technology,13811,7,True,multi-prefix stable,8.518959,1.000,0.895454,0.195,66.787153,66.772377,67.683983,0.014779,0.896833,0.085,0.700
67,Technology,14601,8,True,multi-prefix stable,8.241979,1.000,0.778573,0.185,66.787153,66.798965,66.978867,-0.011813,0.191710,0.075,0.610
68,Technology,10070,9,True,multi-prefix stable,7.406666,1.000,0.806931,0.000,66.787153,66.787155,67.520020,0.000000,0.732866,0.000,0.745
69,Technology,10303,10,True,multi-prefix stable,7.059792,1.000,0.811421,0.485,66.787153,66.772797,68.294350,0.014360,1.507193,0.260,0.810
70,Technology,3375,11,True,multi-prefix stable,6.755260,1.000,0.674700,0.745,66.787153,66.696938,67.099518,0.090213,0.312363,0.365,0.570
72,Technology,14316,13,True,multi-prefix stable,5.854375,1.000,0.868741,0.530,66.787153,66.623222,71.202744,0.163932,4.415590,0.375,0.935
73,Technology,14370,14,True,multi-prefix stable,5.646875,1.000,0.846052,0.130,66.787153,66.783661,68.739853,0.003495,1.952703,0.060,0.770
0,World,13844,1,True,multi-prefix stable,22.572865,1.000,0.876930,0.535,91.038078,91.037628,91.293556,0.000449,0.255477,0.275,0.580
1,World,3994,2,True,multi-prefix stable,17.208542,1.000,1.000000,0.985,91.038078,90.874840,91.394760,0.163238,0.356679,0.730,0.805
2,World,14744,3,True,multi-prefix stable,17.116394,1.000,0.938417,0.995,91.038078,90.809723,91.203087,0.228358,0.165011,0.725,0.640
3,World,3163,4,True,multi-prefix stable,10.695886,1.000,0.927058,0.955,91.038078,90.887054,91.925507,0.151027,0.887424,0.575,0.830
4,World,5222,5,True,multi-prefix stable,9.152500,1.000,0.989780,0.225,91.038078,91.014015,91.171074,0.024062,0.132993,0.120,0.615
5,World,8901,6,True,multi-prefix stable,9.130677,1.000,0.990756,0.815,91.038078,91.009071,91.053291,0.029010,0.015209,0.490,0.635
6,World,406,7,True,multi-prefix stable,8.718281,1.000,0.877048,0.540,91.038078,91.051369,90.910522,-0.013291,-0.127559,0.210,0.450
7,World,1728,8,True,multi-prefix stable,8.028021,1.000,0.911988,0.175,91.038078,91.038376,90.999603,-0.000295,-0.038480,0.055,0.415
8,World,9069,9,True,multi-prefix stable,7.454505,1.000,0.970708,0.665,91.038078,90.983688,91.749687,0.054394,0.711610,0.325,0.730
9,World,5743,10,True,multi-prefix stable,7.108073,1.000,0.775164,0.860,91.038078,91.044952,90.817062,-0.006871,-0.221016,0.435,0.400
12,World,11438,13,True,multi-prefix stable,6.254206,1.000,0.883732,0.540,91.038078,91.026329,91.716782,0.011752,0.678701,0.185,0.455
13,World,2791,14,True,multi-prefix stable,5.826881,1.000,0.951773,0.265,91.038078,91.038055,91.236725,0.000021,0.198644,0.125,0.480
14,World,13051,15,True,multi-prefix stable,5.646966,1.000,0.852406,0.755,91.038078,90.980156,91.272949,0.057927,0.234870,0.370,0.670
18,World,14785,19,True,multi-prefix stable,5.302891,1.000,0.915494,0.130,91.038078,91.035286,91.601273,0.002797,0.563190,0.070,0.530
19,World,541,20,True,multi-prefix stable,5.249551,1.000,1.000000,0.420,91.038078,91.037804,91.515541,0.000276,0.477462,0.195,0.730
57,Business,9009,18,False,LFH-sensitive,3.850625,0.375,0.718268,0.020,70.431077,70.433418,70.625465,-0.002335,0.194382,0.005,0.515
58,Business,44,19,False,LFH-sensitive,3.568620,0.750,0.828547,0.470,70.431077,70.437019,70.929710,-0.005935,0.498629,0.195,0.520
59,Business,8551,20,False,LFH-sensitive,3.481354,0.625,0.839592,0.395,70.431077,70.375381,70.055321,0.055698,-0.375762,0.200,0.420
36,Sports,11476,17,False,LFH-sensitive,5.504167,0.625,0.821698,0.145,98.260069,98.251709,98.319168,0.008356,0.059102,0.060,0.620
37,Sports,7502,18,False,LFH-sensitive,5.475469,0.250,0.619344,0.040,98.260069,98.258644,98.301094,0.001424,0.041024,0.020,0.370
38,Sports,2572,19,False,LFH-sensitive,5.453331,0.625,0.622861,0.000,98.260069,98.260063,98.129364,0.000000,-0.130700,0.000,0.465
39,Sports,14255,20,False,LFH-sensitive,5.294167,0.625,0.890918,0.000,98.260069,98.260063,98.157227,0.000000,-0.102840,0.000,0.400
71,Technology,8551,12,False,LFH-sensitive,6.235520,0.875,0.625432,0.450,66.787153,66.883598,67.069458,-0.096441,0.282301,0.140,0.445
74,Technology,5131,15,False,LFH-sensitive,5.481668,0.875,0.761933,0.000,66.787153,66.787155,66.989624,0.000000,0.202467,0.000,0.610
75,Technology,7281,16,False,LFH-sensitive,4.958855,0.625,0.583962,0.700,66.787153,66.819016,67.115891,-0.031861,0.328740,0.385,0.625
76,Technology,12559,17,False,LFH-sensitive,4.935482,0.875,0.824121,0.335,66.787153,66.794189,67.239105,-0.007032,0.451949,0.125,0.710
77,Technology,7152,18,False,LFH-sensitive,4.660000,0.375,0.656652,0.000,66.787153,66.787155,66.263824,0.000000,-0.523328,0.000,0.395
78,Technology,12592,19,False,LFH-sensitive,4.537498,0.500,0.769514,0.000,66.787153,66.787155,66.978348,0.000000,0.191194,0.000,0.520
79,Technology,6880,20,False,LFH-sensitive,4.260000,0.375,0.735915,1.000,66.787153,66.511940,67.294891,0.275217,0.507735,0.545,0.560
10,World,1295,11,False,LFH-sensitive,6.906670,0.875,0.492277,1.000,91.038078,91.118393,90.952782,-0.080315,-0.085301,0.470,0.440
11,World,6211,12,False,LFH-sensitive,6.290755,0.875,0.714541,0.760,91.038078,90.958488,91.388542,0.079594,0.350465,0.440,0.665
15,World,8386,16,False,LFH-sensitive,5.642500,0.750,0.818177,0.530,91.038078,91.072617,90.828804,-0.034535,-0.209277,0.190,0.285
16,World,3648,17,False,LFH-sensitive,5.611178,0.500,0.847182,0.420,91.038078,91.017654,91.744423,0.020428,0.706342,0.170,0.525
17,World,2221,18,False,LFH-sensitive,5.330026,0.750,0.833608,0.090,91.038078,91.038132,91.494637,-0.000049,0.456557,0.030,0.600

Stable versus LFH-sensitive causal summary:

,causal_group,n_label_feature_pairs,mean_active_prompt_fraction,median_active_prompt_fraction,mean_ablation_decrease,mean_ablation_decrease_ci_low,mean_ablation_decrease_ci_high,mean_ablation_decrease_pp,mean_ablation_decrease_ci_low_pp,mean_ablation_decrease_ci_high_pp,mean_amplification_increase,mean_amplification_increase_ci_low,mean_amplification_increase_ci_high,mean_amplification_increase_pp,mean_amplification_increase_ci_low_pp,mean_amplification_increase_ci_high_pp
0,multi-prefix stable,61,0.527459,0.535,0.000644,0.000346,0.001036,0.064441,0.034605,0.103626,0.007428,0.004637,0.010916,0.742773,0.463699,1.091553
1,LFH-sensitive,19,0.334474,0.335,0.000096,-0.000183,0.000466,0.009590,-0.018280,0.046616,0.001497,0.000167,0.002893,0.149667,0.016672,0.289307

Per-label stable/sensitive causal summary:

,label_word,causal_group,n_label_feature_pairs,mean_ablation_decrease_pp,mean_amplification_increase_pp,mean_active_prompt_fraction
0,Business,LFH-sensitive,3,0.015809,0.105750,0.295000
1,Business,multi-prefix stable,17,0.131560,1.477575,0.474706
2,Sports,LFH-sensitive,4,0.002445,-0.033353,0.046250
3,Sports,multi-prefix stable,16,0.016904,0.124588,0.590313
4,Technology,LFH-sensitive,7,0.019983,0.205865,0.355000
5,Technology,multi-prefix stable,13,0.055466,1.069752,0.446154
6,World,LFH-sensitive,5,-0.002975,0.243757,0.560000
7,World,multi-prefix stable,15,0.046857,0.286014,0.590667

====================================================================================================
Quick readout
====================================================================================================
Mean ablation decrease, stable group:      0.0644 percentage points
Mean ablation decrease, LFH-sensitive:     0.0096 percentage points
Mean amplification increase, stable group: 0.7428 percentage points
Mean amplification increase, sensitive:    0.1497 percentage points

Pattern matches the ideal validation: multi-prefix-stable features are more causally relevant on both tests.


## How to report the causal validation

The key table to include in the rebuttal is `causal_group_summary_df`:

- `mean_ablation_decrease_pp`: how much gold-label probability falls when the selected feature is removed when active.
- `mean_amplification_increase_pp`: how much gold-label probability rises when the selected feature direction is added with the current `CAUSAL_AMPLIFICATION_ALPHA`.

The intended coarse validation pattern is:

```text
multi-prefix stable features  >  LFH-sensitive features
```

for both ablation decrease and amplification increase. If the pattern holds, the rebuttal can state that the multi-prefix stability filter is not merely a descriptive diagnostic: it preferentially retains features with stronger causal support for the intended label, while filtering out single-prefix features that are more likely to be local-history-sensitive artifacts.


## How to report this experiment

A compact rebuttal/table can report:

- that features are selected by **label-specific preactivation gap**, not by overall activation magnitude;
- for each AGNews label, the top-20 single-prefix label-specific features;
- the fraction of those features that pass the multi-prefix stability rule;
- examples of high-ranked label-specific features that are unstable when only the final demonstration changes;
- Plotly heatmaps showing label-specific preactivation gaps across final-demo variants.

Suggested interpretation:

> We add an LFH-aware multi-prefix stability check for label-specific SAE features. For each fixed query, only the final demonstration is resampled. A feature selected from the original prefix is retained as robust only if its label-specific preactivation gap remains high across these alternative prefixes. Features whose apparent label-specificity collapses or moves sharply under final-demo variation are flagged as LFH-sensitive rather than directly interpreted as query-semantic features.

This is intended as a lightweight diagnostic, not a complete causal decomposition.