# LFH-aware multi-prefix stability check — Gemma2-2B-IT / AGNews

This notebook is the **coarse preliminary rebuttal version** using the same method as the attached Gemma2-9B-IT notebook, but with `Gemma2-2B-IT`.

Experiment design:

1. Use `Gemma2-2B-IT` and the corresponding middle-layer residual SAE.
2. Sample AGNews test queries, label-balanced.
3. For each query, keep demonstrations 1–7 fixed and vary only demonstration 8 across eight balanced alternatives.
4. Measure query-side SAE pre/post-activations at token positions controlled by one variable only:
   ```python
   query_analysis_positions = [-2, -3, -4, -5]
   ```
   Here `-1` is the final query-span token, `-2` is the second-final token, etc.
5. Select **label-specific** candidate features from the ordinary single-prefix baseline. For label `L`, the score is:
   ```text
   mean preactivation on gold-label-L query items
   - mean preactivation on all other query items
   ```
6. For each label, report the top-20 label-specific features selected from `P1`.
7. Recompute their label-specific ranks under `P2..P8`, where only the final demonstration changes.
8. Split features into LFH-stable versus LFH-sensitive groups using the same coarse stability rule as the attached notebook.
9. Run the same coarse causal validation and Plotly diagnostics.

This notebook intentionally keeps **preactivation-based ranking**. Post-activation values are retained only as diagnostics.

In [1]:

# ============================================================
# 0. Imports and configuration
# ============================================================

import os
import re
import json
import math
import random
from collections import defaultdict

import numpy as np
import pandas as pd
import torch
import plotly.express as px
import plotly.graph_objects as go

from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM
from huggingface_hub import hf_hub_download
from IPython.display import display


def set_seed(seed: int):
    print("seed:", seed)
    torch.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.enabled = False
    torch.backends.cudnn.benchmark = False
    os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"
    os.environ["PYTHONHASHSEED"] = str(seed)


# -----------------------------
# User-facing experiment knobs
# -----------------------------
seed = 42
set_seed(seed)

MODEL_FAMILY = "gemma"
MODEL_NAME = "google/gemma-2-2b-it"
MODEL_SHORT_NAME = "Gemma2-2B-IT"
TARGET_LAYER = 12

# Gemma Scope residual SAE, middle checkpoint for this model.
SAE_BACKEND = "gemma_scope_npz"
SAE_REPO_ID = "google/gemma-scope-2b-pt-res"
SAE_WIDTH = "width_16k"
SAE_AVERAGE_L0 = "average_l0_82"
SAE_FILENAME = f"layer_{TARGET_LAYER}/{SAE_WIDTH}/{SAE_AVERAGE_L0}/params.npz"

# Gemma Scope variants do not need Qwen high-residual-norm filtering.
FILTER_HIGH_NORM_TOKENS_FOR_FEATURE_EXTRACTION = False
HIGH_NORM_FILTER_MULTIPLIER = 10.0

# Multi-prefix stability experiment.
N_QUERY_TOTAL = 100              # label-balanced test queries; use smaller values for debugging
N_SHOT = 8                       # demonstrations per prefix
N_PREFIX_VARIANTS = 8            # with AGNews labels, 8 gives 2 final demos per label
FINAL_DEMO_SLOT = N_SHOT         # vary the last demonstration: Example 8

# Coarse attached-file method: top-20 baseline features and top-20 retention.
LABEL_SPECIFIC_TOP_N = 20        # top-20 features per label in the ordinary single-prefix baseline
RETENTION_TOP_K = 20             # retention is computed against the top-K label-specific ranking in each variant
STABLE_MIN_RETENTION = 0.90
STABLE_MIN_BASELINE_RATIO = 0.50

# One feature-selection token-position variable only.
# -1 is the final query-span token, -2 is the second-final token, etc.
query_analysis_positions = [-2]

# Optional local-control condition: vary an earlier demo while keeping the final demo fixed.
# This approximately doubles the number of forward passes, so it is disabled by default.
RUN_EARLIER_DEMO_CONTROL = False
EARLIER_DEMO_CONTROL_SLOT = 3

# Runtime. Gemma2-2B is smaller than 9B/14B variants, so this batch size is moderately conservative.
DTYPE = torch.bfloat16
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
BATCH_SIZE = 4

# Optional HF token for higher rate limits / gated checkpoints.
HF_TOKEN = os.environ.get("HF_TOKEN") or os.environ.get("HUGGINGFACE_HUB_TOKEN")
HF_KWARGS = {"token": HF_TOKEN} if HF_TOKEN else {}

print("MODEL_NAME:", MODEL_NAME)
print("MODEL_SHORT_NAME:", MODEL_SHORT_NAME)
print("MODEL_FAMILY:", MODEL_FAMILY)
print("TARGET_LAYER:", TARGET_LAYER)
print("SAE_BACKEND:", SAE_BACKEND)
print("SAE_REPO_ID:", SAE_REPO_ID)
print("SAE_FILENAME:", SAE_FILENAME)
print("FILTER_HIGH_NORM_TOKENS_FOR_FEATURE_EXTRACTION:", FILTER_HIGH_NORM_TOKENS_FOR_FEATURE_EXTRACTION)
print("LABEL_SPECIFIC_TOP_N:", LABEL_SPECIFIC_TOP_N)
print("RETENTION_TOP_K:", RETENTION_TOP_K)
print("query_analysis_positions:", query_analysis_positions)
print("BATCH_SIZE:", BATCH_SIZE)
print("DEVICE:", DEVICE)

/home/ikhyuncho23/ml-env/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

seed: 42
MODEL_NAME: google/gemma-2-2b-it
MODEL_SHORT_NAME: Gemma2-2B-IT
MODEL_FAMILY: gemma
TARGET_LAYER: 12
SAE_BACKEND: gemma_scope_npz
SAE_REPO_ID: google/gemma-scope-2b-pt-res
SAE_FILENAME: layer_12/width_16k/average_l0_82/params.npz
FILTER_HIGH_NORM_TOKENS_FOR_FEATURE_EXTRACTION: False
LABEL_SPECIFIC_TOP_N: 20
RETENTION_TOP_K: 20
query_analysis_positions: [-2]
BATCH_SIZE: 4
DEVICE: cuda

In [2]:
# ============================================================
# 1. Load AGNews, tokenizer, model, and SAE
# ============================================================

label_to_words_agnews = {
    0: "World",
    1: "Sports",
    2: "Business",
    3: "Technology",
}
word_to_label_agnews = {v: k for k, v in label_to_words_agnews.items()}
NUM_LABELS = len(label_to_words_agnews)


def load_agnews_splits():
    """Use the namespaced HF dataset id to avoid recent hf:// URI errors."""
    candidates = ["fancyzhx/ag_news", "ag_news"]
    errors = []
    for dataset_id in candidates:
        try:
            print(f"Loading AGNews from {dataset_id!r}...")
            return load_dataset(dataset_id, split=["train", "test"], **HF_KWARGS)
        except Exception as e:
            errors.append((dataset_id, type(e).__name__, str(e)))
            print(f"Failed to load {dataset_id!r}: {type(e).__name__}: {e}")
    raise RuntimeError("Could not load AGNews. Errors:\n" + "\n\n".join(map(str, errors)))


dataset = load_agnews_splits()
train_data_agnews = dataset[0]
test_data_agnews = dataset[1]

train_indices_by_label = defaultdict(list)
test_indices_by_label = defaultdict(list)
for i, row in enumerate(train_data_agnews):
    train_indices_by_label[int(row["label"])].append(i)
for i, row in enumerate(test_data_agnews):
    test_indices_by_label[int(row["label"])].append(i)

print("Train counts:", {label_to_words_agnews[k]: len(v) for k, v in train_indices_by_label.items()})
print("Test counts:", {label_to_words_agnews[k]: len(v) for k, v in test_indices_by_label.items()})


tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME,
    trust_remote_code=True,
    use_fast=True,
    **HF_KWARGS,
)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
# Left padding makes causal labels natural and matches the previous notebooks.
tokenizer.padding_side = "left"

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=DTYPE,
    device_map="auto" if torch.cuda.is_available() else None,
    trust_remote_code=True,
    **HF_KWARGS,
)
model.eval()


def get_model_input_device(model):
    return model.get_input_embeddings().weight.device


def get_layer_device(model, layer_idx: int):
    block = model.get_submodule(f"model.layers.{layer_idx}")
    try:
        return next(block.parameters()).device
    except StopIteration:
        return get_model_input_device(model)


MODEL_INPUT_DEVICE = get_model_input_device(model)
TARGET_LAYER_DEVICE = get_layer_device(model, TARGET_LAYER)
print("MODEL_INPUT_DEVICE:", MODEL_INPUT_DEVICE)
print("TARGET_LAYER_DEVICE:", TARGET_LAYER_DEVICE)


class GemmaScopeJumpReLUSAE(torch.nn.Module):
    """Minimal inference wrapper for Gemma Scope JumpReLU residual-stream SAEs."""

    def __init__(self, params, device=DEVICE, dtype=DTYPE):
        super().__init__()
        self.device = torch.device(device)
        self.dtype = dtype

        def get_param(name, *aliases):
            for key in (name,) + aliases:
                if key in params:
                    value = params[key]
                    if isinstance(value, np.ndarray):
                        value = torch.from_numpy(value)
                    return value.detach() if torch.is_tensor(value) else torch.tensor(value)
            raise KeyError(f"Missing SAE parameter {name!r}. Available keys: {sorted(params.keys())}")

        W_enc = get_param("W_enc")
        W_dec = get_param("W_dec")
        b_enc = get_param("b_enc")
        b_dec = get_param("b_dec")
        threshold = get_param("threshold", "thresholds")

        if W_enc.ndim != 2 or W_dec.ndim != 2:
            raise ValueError(f"Expected 2D W_enc/W_dec, got {tuple(W_enc.shape)} and {tuple(W_dec.shape)}")

        d_model = int(W_enc.shape[0])
        n_features = int(W_enc.shape[1])

        if W_dec.shape == (d_model, n_features):
            W_dec = W_dec.T.contiguous()
        if W_dec.shape != (n_features, d_model):
            raise ValueError(f"Expected W_dec shape {(n_features, d_model)}, got {tuple(W_dec.shape)}")
        if b_enc.numel() != n_features:
            raise ValueError(f"Expected b_enc length {n_features}, got {b_enc.numel()}")
        if b_dec.numel() != d_model:
            raise ValueError(f"Expected b_dec length {d_model}, got {b_dec.numel()}")
        if threshold.numel() != n_features:
            raise ValueError(f"Expected threshold length {n_features}, got {threshold.numel()}")

        self.register_buffer("W_enc", W_enc.contiguous().to(device=self.device, dtype=self.dtype))
        self.register_buffer("W_dec", W_dec.contiguous().to(device=self.device, dtype=self.dtype))
        self.register_buffer("b_enc", b_enc.reshape(-1).contiguous().to(device=self.device, dtype=self.dtype))
        self.register_buffer("b_dec", b_dec.reshape(-1).contiguous().to(device=self.device, dtype=self.dtype))
        self.register_buffer("threshold", threshold.reshape(-1).contiguous().to(device=self.device, dtype=self.dtype))

        self.k = None
        self.d_model = d_model
        self.n_features = n_features

    def process_sae_in(self, x: torch.Tensor) -> torch.Tensor:
        # Gemma Scope folds any preprocessing into the encoder parameters for these checkpoints.
        return x

    def encode_pre(self, x: torch.Tensor) -> torch.Tensor:
        x = x.to(device=self.device, dtype=self.dtype)
        return self.process_sae_in(x) @ self.W_enc + self.b_enc

    def activation_fn(self, pre: torch.Tensor) -> torch.Tensor:
        return torch.where(pre > self.threshold, torch.relu(pre), torch.zeros_like(pre))

    def encode(self, x: torch.Tensor) -> torch.Tensor:
        return self.activation_fn(self.encode_pre(x))

    def decode(self, acts: torch.Tensor) -> torch.Tensor:
        acts = acts.to(device=self.device, dtype=self.dtype)
        return acts @ self.W_dec + self.b_dec


class QwenBatchTopKSAE(torch.nn.Module):
    """
    Minimal inference wrapper for Adam Karvonen's Qwen3 BatchTopK SAEs.

    The checkpoint has dictionary_learning-style keys:
      b_dec, k, threshold, decoder.weight, encoder.weight, encoder.bias

    This wrapper exposes the same interface used by the Gemma Scope wrapper:
      W_enc, W_dec, b_enc, b_dec, threshold, encode_pre, activation_fn, encode, decode.
    """

    def __init__(self, state_dict, device=DEVICE, dtype=DTYPE):
        super().__init__()
        self.device = torch.device(device)
        self.dtype = dtype

        if isinstance(state_dict, dict) and "state_dict" in state_dict:
            state_dict = state_dict["state_dict"]
        if isinstance(state_dict, dict) and "model" in state_dict and isinstance(state_dict["model"], dict):
            state_dict = state_dict["model"]

        b_dec = state_dict["b_dec"].detach()
        b_enc = state_dict.get("encoder.bias", state_dict.get("b_enc")).detach()
        enc_w = state_dict.get("encoder.weight", state_dict.get("W_enc")).detach()
        dec_w = state_dict.get("decoder.weight", state_dict.get("W_dec")).detach()
        threshold = state_dict["threshold"]
        threshold = threshold.detach() if torch.is_tensor(threshold) else torch.tensor(threshold)
        k = state_dict.get("k", None)
        if torch.is_tensor(k):
            k = int(k.item())

        d_model = int(b_dec.numel())
        n_features = int(b_enc.numel())

        if enc_w.shape == (n_features, d_model):
            W_enc = enc_w.T.contiguous()
        elif enc_w.shape == (d_model, n_features):
            W_enc = enc_w.contiguous()
        else:
            raise ValueError(
                f"Unexpected encoder.weight shape {tuple(enc_w.shape)} "
                f"for d_model={d_model}, n_features={n_features}"
            )

        if dec_w.shape == (d_model, n_features):
            W_dec = dec_w.T.contiguous()
        elif dec_w.shape == (n_features, d_model):
            W_dec = dec_w.contiguous()
        else:
            raise ValueError(
                f"Unexpected decoder.weight shape {tuple(dec_w.shape)} "
                f"for d_model={d_model}, n_features={n_features}"
            )

        self.register_buffer("W_enc", W_enc.to(device=self.device, dtype=self.dtype))
        self.register_buffer("W_dec", W_dec.to(device=self.device, dtype=self.dtype))
        self.register_buffer("b_enc", b_enc.to(device=self.device, dtype=self.dtype))
        self.register_buffer("b_dec", b_dec.to(device=self.device, dtype=self.dtype))
        self.register_buffer("threshold", threshold.to(device=self.device, dtype=self.dtype))

        self.k = k
        self.d_model = d_model
        self.n_features = n_features

    def process_sae_in(self, x: torch.Tensor) -> torch.Tensor:
        return x - self.b_dec

    def encode_pre(self, x: torch.Tensor) -> torch.Tensor:
        x = x.to(device=self.device, dtype=self.dtype)
        return self.process_sae_in(x) @ self.W_enc + self.b_enc

    def activation_fn(self, pre: torch.Tensor) -> torch.Tensor:
        return torch.where(pre > self.threshold, pre, torch.zeros_like(pre))

    def encode(self, x: torch.Tensor) -> torch.Tensor:
        return self.activation_fn(self.encode_pre(x))

    def decode(self, acts: torch.Tensor) -> torch.Tensor:
        acts = acts.to(device=self.device, dtype=self.dtype)
        return acts @ self.W_dec + self.b_dec


def load_gemma_scope_jumprelu_sae(repo_id: str, filename: str, device=DEVICE, dtype=DTYPE):
    print("Downloading/loading Gemma Scope SAE checkpoint:", repo_id, filename)
    path = hf_hub_download(repo_id=repo_id, filename=filename, **HF_KWARGS)
    with np.load(path, allow_pickle=False) as params_np:
        params = {k: torch.from_numpy(params_np[k]) for k in params_np.files}
    sae = GemmaScopeJumpReLUSAE(params, device=device, dtype=dtype)
    print(
        f"Loaded SAE: d_model={sae.d_model}, n_features={sae.n_features}, "
        f"mean_threshold={float(sae.threshold.detach().float().mean().cpu()):.4f}"
    )
    return sae


def load_qwen_batchtopk_sae(repo_id: str, filename: str, device=DEVICE, dtype=DTYPE):
    print("Downloading/loading Qwen BatchTopK SAE checkpoint:", repo_id, filename)
    path = hf_hub_download(repo_id=repo_id, filename=filename, **HF_KWARGS)
    try:
        state = torch.load(path, map_location="cpu", weights_only=True)
    except TypeError:
        state = torch.load(path, map_location="cpu")
    sae = QwenBatchTopKSAE(state, device=device, dtype=dtype)
    print(
        f"Loaded SAE: d_model={sae.d_model}, n_features={sae.n_features}, "
        f"k={sae.k}, mean_threshold={float(sae.threshold.detach().float().mean().cpu()):.4f}"
    )
    return sae


def load_configured_sae():
    if SAE_BACKEND == "gemma_scope_npz":
        return load_gemma_scope_jumprelu_sae(
            repo_id=SAE_REPO_ID,
            filename=SAE_FILENAME,
            device=TARGET_LAYER_DEVICE,
            dtype=DTYPE,
        )
    if SAE_BACKEND == "qwen_batchtopk":
        return load_qwen_batchtopk_sae(
            repo_id=SAE_REPO_ID,
            filename=SAE_FILENAME,
            device=TARGET_LAYER_DEVICE,
            dtype=DTYPE,
        )
    raise ValueError(f"Unknown SAE_BACKEND={SAE_BACKEND!r}")


sae = load_configured_sae()
print("SAE device:", sae.device)

Loading AGNews from 'fancyzhx/ag_news'...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Train counts: {'Business': 30000, 'Technology': 30000, 'Sports': 30000, 'World': 30000}
Test counts: {'Business': 1900, 'Technology': 1900, 'Sports': 1900, 'World': 1900}

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!
Loading weights: 100%|███████████████████████████████| 288/288 [00:00<00:00, 1111.10it/s]

MODEL_INPUT_DEVICE: cuda:0
TARGET_LAYER_DEVICE: cuda:0
Downloading/loading Gemma Scope SAE checkpoint: google/gemma-scope-2b-pt-res layer_12/width_16k/average_l0_82/params.npz
Loaded SAE: d_model=2304, n_features=16384, mean_threshold=3.1322
SAE device: cuda:0

In [3]:

# ============================================================
# 2. Prompt sampling and rendering
# ============================================================

rng = random.Random(seed)

INSTRUCTION = """You are given news articles and their topics.
Valid topics: World, Sports, Business, Technology.
For each example, identify the correct topic."""


def balanced_label_sequence(n: int, num_labels: int = NUM_LABELS, rng: random.Random | None = None):
    """Return labels as evenly as possible, shuffled."""
    rng = rng or random
    base = n // num_labels
    rem = n % num_labels
    labels = []
    for lab in range(num_labels):
        labels.extend([lab] * base)
    extra = list(range(num_labels))
    rng.shuffle(extra)
    labels.extend(extra[:rem])
    rng.shuffle(labels)
    return labels


def sample_train_indices_for_labels(label_seq, rng: random.Random, exclude=None):
    exclude = set(exclude or [])
    chosen = []
    used = set(exclude)
    for lab in label_seq:
        pool = [idx for idx in train_indices_by_label[int(lab)] if idx not in used]
        if not pool:
            raise RuntimeError(f"No available training examples for label {lab} after exclusions.")
        idx = rng.choice(pool)
        chosen.append(idx)
        used.add(idx)
    return chosen


def sample_label_balanced_test_indices(n_total: int, rng: random.Random):
    label_seq = balanced_label_sequence(n_total, num_labels=NUM_LABELS, rng=rng)
    out = []
    used = set()
    for lab in label_seq:
        pool = [idx for idx in test_indices_by_label[int(lab)] if idx not in used]
        idx = rng.choice(pool)
        out.append(idx)
        used.add(idx)
    return out


def format_demo(demo_number: int, row) -> str:
    return (
        f"Example {demo_number}:\n"
        f"News article:\n{row['text']}\n"
        f"Topic:\n{label_to_words_agnews[int(row['label'])]}"
    )


def render_single_user_prompt(demo_rows, query_row):
    """
    Render all demonstrations and the test query inside one model-native user prompt.

    Gemma uses one <start_of_turn>user block plus the model-generation header.
    Qwen uses one system message plus one user message plus the assistant-generation header.
    In both cases, all demonstrations are in a single user prompt; individual demos are not wrapped.

    Returns:
      prompt: full model input string
      query_char_span: [start, end) character span of the query block inside prompt
    """
    if len(demo_rows) != N_SHOT:
        raise ValueError(f"Expected {N_SHOT} demos, got {len(demo_rows)}")

    demo_text = "\n\n".join(format_demo(i + 1, row) for i, row in enumerate(demo_rows))
    query_block = f"Test article:\n{query_row['text']}\nTopic:\n"

    if MODEL_FAMILY == "gemma":
        user_content = f"{INSTRUCTION}\n\n{demo_text}\n\n{query_block}"
        prompt = f"<bos><start_of_turn>user\n{user_content}<end_of_turn>\n<start_of_turn>model\n"

        # Sanity checks: one user turn, one model-generation header, all demos in the user turn.
        if prompt.count("<start_of_turn>user") != 1:
            raise AssertionError("Prompt should contain exactly one user turn.")
        if prompt.count("<start_of_turn>model") != 1:
            raise AssertionError("Prompt should contain exactly one model-generation header.")
        if prompt.count("<end_of_turn>") != 1:
            raise AssertionError("Prompt should contain exactly one user-turn terminator.")

    elif MODEL_FAMILY == "qwen":
        user_content = f"{demo_text}\n\n{query_block}"
        messages = [
            {"role": "system", "content": INSTRUCTION},
            {"role": "user", "content": user_content},
        ]
        try:
            prompt = tokenizer.apply_chat_template(
                messages,
                tokenize=False,
                add_generation_prompt=True,
                enable_thinking=False,
            )
        except TypeError:
            # Older transformers/tokenizers may not expose enable_thinking.
            # In that case, include Qwen's non-thinking directive in the system content.
            messages = [
                {"role": "system", "content": INSTRUCTION + "\n/no_think"},
                {"role": "user", "content": user_content},
            ]
            prompt = tokenizer.apply_chat_template(
                messages,
                tokenize=False,
                add_generation_prompt=True,
            )

        if prompt.count(query_block) != 1:
            raise AssertionError("Could not uniquely locate the query block in the Qwen chat-template prompt.")
    else:
        raise ValueError(f"Unknown MODEL_FAMILY={MODEL_FAMILY!r}")

    query_start = prompt.index(query_block)
    query_end = query_start + len(query_block)

    if len(re.findall(r"(?m)^Example\s+\d+:", prompt)) != N_SHOT:
        raise AssertionError(f"Prompt should contain exactly {N_SHOT} numbered demo headers.")

    return prompt, (query_start, query_end)


def build_final_demo_variant_prompts():
    """
    Build Q x V prompts using the coarse attached-file method.

    For each fixed query:
      - demos 1..7 are fixed for that query;
      - demo 8 varies across N_PREFIX_VARIANTS alternatives;
      - final-demo labels are as balanced as possible.
    """
    test_indices = sample_label_balanced_test_indices(N_QUERY_TOTAL, rng)
    prompts = []
    metadata = []

    for q_local_idx, test_idx in enumerate(test_indices):
        query_row = test_data_agnews[int(test_idx)]

        fixed_label_seq = balanced_label_sequence(N_SHOT - 1, rng=rng)
        fixed_demo_indices = sample_train_indices_for_labels(fixed_label_seq, rng=rng)

        final_label_seq = balanced_label_sequence(N_PREFIX_VARIANTS, rng=rng)
        final_demo_indices = sample_train_indices_for_labels(
            final_label_seq,
            rng=rng,
            exclude=fixed_demo_indices,
        )

        fixed_demo_rows = [train_data_agnews[int(i)] for i in fixed_demo_indices]

        for variant_idx, final_demo_idx in enumerate(final_demo_indices):
            demo_indices = list(fixed_demo_indices) + [int(final_demo_idx)]
            demo_rows = fixed_demo_rows + [train_data_agnews[int(final_demo_idx)]]
            prompt, query_char_span = render_single_user_prompt(demo_rows, query_row)
            prompts.append(prompt)
            metadata.append({
                "query_local_idx": int(q_local_idx),
                "variant_idx": int(variant_idx),
                "query_test_idx": int(test_idx),
                "query_label": int(query_row["label"]),
                "query_label_word": label_to_words_agnews[int(query_row["label"])],
                "fixed_demo_indices": [int(x) for x in fixed_demo_indices],
                "fixed_demo_labels": [int(train_data_agnews[int(x)]["label"]) for x in fixed_demo_indices],
                "final_demo_idx": int(final_demo_idx),
                "final_demo_label": int(train_data_agnews[int(final_demo_idx)]["label"]),
                "final_demo_label_word": label_to_words_agnews[int(train_data_agnews[int(final_demo_idx)]["label"])],
                "query_char_start": int(query_char_span[0]),
                "query_char_end": int(query_char_span[1]),
            })

    return prompts, metadata


prompts, prompt_metadata = build_final_demo_variant_prompts()
print(f"Built {len(prompts)} prompts = {N_QUERY_TOTAL} queries x {N_PREFIX_VARIANTS} final-demo variants.")
print("First prompt excerpt:\n")
print(prompts[0][:2000])

meta_df = pd.DataFrame(prompt_metadata)
print("\nQuery label counts:")
display(meta_df.drop_duplicates("query_local_idx")["query_label_word"].value_counts().sort_index().to_frame("count"))
print("Final-demo label counts across all variants:")
display(meta_df["final_demo_label_word"].value_counts().sort_index().to_frame("count"))

Built 800 prompts = 100 queries x 8 final-demo variants.
First prompt excerpt:

<bos><start_of_turn>user
You are given news articles and their topics.
Valid topics: World, Sports, Business, Technology.
For each example, identify the correct topic.

Example 1:
News article:
Hamm #39;s legacy should be for Olympic ideal Even though he has fled the perceived hostile atmosphere of Athens and the Olympic village for more friendly terrain in the United States, there is still time for Paul Hamm to do what #39;s right.
Topic:
Sports

Example 2:
News article:
Greenspan rejects talk of throwing dollar a lifeline ALAN GREENSPAN, Chairman of the US Federal Reserve, undercut lingering hopes of staging an operation to support the dollar at a meeting of bankers in Frankfurt yesterday
Topic:
Business

Example 3:
News article:
Google Desktop Search app lets you 'google' your Windows PC Google Inc. unveiled a desktop search application that lets users catalog and search through e-mail, files, Web histories, instant message chats and other content on their PCs.
Topic:
Technology

Example 4:
News article:
Mozambique Prepares for Elections to Replace Chissano Mozambique holds elections on Wednesday and Thursday to choose a successor to President Joaquim Chissano, who ruled for 18 years and led the southern African country to peace after a long civil war that claimed up to a million lives.
Topic:
World

Example 5:
News article:
Israel celebrates joy of first gold medal Israel has celebrated its first Olympic gold medal, saying Gal Fridman #39;s win gave pride and joy to Jewish people around the world.
Topic:
Sports

Example 6:
News article:
Nephew has Arafat medical file No evidence exists that Palestinian leader Yasser Arafat died of poisoning, his nephew says. But at a press conference in Paris, Nasser al-Quidwa did not definitely dismiss
Topic:
World

Example 7:
News article:
Automatic Data #39;s Improving Fundamentals Prudential Equity Group raised its earnings estimates for Automatic Data Processing (nyse: ADP - news - people ) after the payroll and data proc

Query label counts:

                  count
query_label_word
Business             25
Sports               25
Technology           25
World                25

Final-demo label counts across all variants:

                       count
final_demo_label_word
Business                 200
Sports                   200
Technology               200
World                    200

In [4]:

# ============================================================
# 3. Token-span helpers and model/SAE extraction
# ============================================================


def token_positions_for_char_span(prompt: str, char_start: int, char_end: int):
    """Map a prompt character span to unpadded token indices."""
    enc = tokenizer(
        prompt,
        add_special_tokens=False,
        return_offsets_mapping=True,
    )
    offsets = enc["offset_mapping"]
    positions = []
    for tok_idx, (s, e) in enumerate(offsets):
        # Skip empty special offsets if any appear.
        if e <= s:
            continue
        # Token overlaps the query span.
        if max(int(s), int(char_start)) < min(int(e), int(char_end)):
            positions.append(tok_idx)
    if not positions:
        raise RuntimeError("No token positions found for query character span.")
    return positions


def select_query_positions(all_query_positions):
    """
    Select query-span token positions using query_analysis_positions only.

    Offset semantics:
      -1 -> final query-span token
      -2 -> second-final query-span token
      -3 -> third-final query-span token
    """
    selected = []
    n = len(all_query_positions)
    for off in query_analysis_positions:
        off = int(off)
        if off >= 0:
            raise ValueError("query_analysis_positions must contain negative offsets, e.g. [-1, -2].")
        idx = n + off
        if idx < 0 or idx >= n:
            raise IndexError(f"Offset {off} is out of range for query span with {n} tokens.")
        selected.append(all_query_positions[idx])
    return selected


# Precompute selected unpadded token positions for every prompt.
for meta, prompt in zip(prompt_metadata, prompts):
    all_positions = token_positions_for_char_span(
        prompt=prompt,
        char_start=meta["query_char_start"],
        char_end=meta["query_char_end"],
    )
    meta["all_query_token_positions"] = [int(x) for x in all_positions]
    meta["selected_query_token_positions"] = [int(x) for x in select_query_positions(all_positions)]
    meta["num_query_tokens"] = int(len(all_positions))
    meta["num_selected_query_tokens"] = int(len(meta["selected_query_token_positions"]))

print("Selected query-token counts:")
display(pd.Series([m["num_selected_query_tokens"] for m in prompt_metadata]).describe().to_frame("selected_query_tokens"))
print("Example selected offsets:", query_analysis_positions)
print("First prompt selected unpadded token positions:", prompt_metadata[0]["selected_query_token_positions"])


def clear_all_hooks(model: torch.nn.Module):
    for module in model.modules():
        module._forward_hooks.clear()
        module._forward_pre_hooks.clear()
        module._backward_hooks.clear()


@torch.no_grad()
def get_layer_output(model, input_ids, attention_mask, layer_idx: int):
    """Run a forward pass and capture model.layers[layer_idx] output, shape [B, S, D]."""
    captured = {}

    def hook_fn(module, inputs, output):
        captured["x"] = output[0].detach() if isinstance(output, tuple) else output.detach()
        return output

    block = model.get_submodule(f"model.layers.{layer_idx}")
    handle = block.register_forward_hook(hook_fn)
    try:
        _ = model(input_ids=input_ids, attention_mask=attention_mask, use_cache=False)
    finally:
        handle.remove()

    if "x" not in captured:
        raise RuntimeError(f"Failed to capture output from layer {layer_idx}")
    return captured["x"]



@torch.no_grad()
def sae_encode_pre_for_positions(hidden_row: torch.Tensor, selected_positions):
    """
    Encode SAE preactivations for selected positions from one prompt's hidden states.

    For Qwen BatchTopK SAEs, optionally zero out high-residual-norm tokens using the
    same median-norm rule used in the Qwen SAE release. Gemma variants keep this off.
    """
    positions = [int(p) for p in selected_positions]
    x = hidden_row[positions, :]
    pre = sae.encode_pre(x).float()

    if FILTER_HIGH_NORM_TOKENS_FOR_FEATURE_EXTRACTION:
        norms = hidden_row.detach().float().norm(dim=-1)
        median_norm = norms.median().clamp_min(1e-6)
        high_norm_mask = norms[positions] > (HIGH_NORM_FILTER_MULTIPLIER * median_norm)
        if bool(high_norm_mask.any().item()):
            pre = pre.clone()
            pre[high_norm_mask.to(pre.device)] = 0.0

    return pre




def apply_optional_high_norm_filter_to_pre(x: torch.Tensor, pre: torch.Tensor) -> torch.Tensor:
    """
    Optionally zero SAE preactivations for abnormally high-residual-norm tokens.

    This is enabled for Qwen BatchTopK SAEs and disabled for Gemma Scope SAEs.
    """
    if not FILTER_HIGH_NORM_TOKENS_FOR_FEATURE_EXTRACTION:
        return pre
    if x.ndim < 2:
        return pre
    norms = x.detach().float().norm(dim=-1)
    median_norm = norms.median().clamp_min(1e-6)
    high_norm_mask = norms > (HIGH_NORM_FILTER_MULTIPLIER * median_norm)
    if high_norm_mask.any():
        pre = pre.masked_fill(high_norm_mask.to(pre.device)[..., None], 0.0)
    return pre

@torch.no_grad()
def collect_query_feature_stats_for_prompts(prompts, metadata):
    """
    Return per-prompt query-side feature statistics:
      pre_by_prompt:  [P, F] mean SAE pre-activation over selected query tokens
      post_by_prompt: [P, F] mean SAE post-activation over selected query tokens
      freq_by_prompt: [P, F] fraction of selected query tokens with post-activation > 0
    """

    n_prompts = len(prompts)
    n_features = int(sae.n_features)
    pre_by_prompt = np.zeros((n_prompts, n_features), dtype=np.float32)
    post_by_prompt = np.zeros((n_prompts, n_features), dtype=np.float32)
    freq_by_prompt = np.zeros((n_prompts, n_features), dtype=np.float32)

    model_device = get_model_input_device(model)
    model.eval()
    sae.eval()

    for start in range(0, n_prompts, BATCH_SIZE):
        end = min(start + BATCH_SIZE, n_prompts)
        batch_prompts = prompts[start:end]
        batch_meta = metadata[start:end]

        enc = tokenizer(
            batch_prompts,
            padding=True,
            return_tensors="pt",
            add_special_tokens=False,
        )
        input_ids = enc["input_ids"].to(model_device)
        attention_mask = enc["attention_mask"].to(model_device)

        hidden = get_layer_output(model, input_ids, attention_mask, TARGET_LAYER)  # [B, S, D]
        batch_seq_len = int(input_ids.shape[1])

        for b, meta in enumerate(batch_meta):
            unpadded_len = int(attention_mask[b].sum().item())
            pad_shift = batch_seq_len - unpadded_len
            selected_positions = [pad_shift + int(pos) for pos in meta["selected_query_token_positions"]]
            selected_positions = [pos for pos in selected_positions if 0 <= pos < batch_seq_len]
            if not selected_positions:
                raise RuntimeError(f"No valid selected token positions for prompt index {start + b}.")

            pre = sae_encode_pre_for_positions(hidden[b], selected_positions)
            post = sae.activation_fn(pre.to(dtype=sae.dtype)).float()

            pre_by_prompt[start + b] = pre.mean(dim=0).detach().cpu().numpy()
            post_by_prompt[start + b] = post.mean(dim=0).detach().cpu().numpy()
            freq_by_prompt[start + b] = (post > 0).float().mean(dim=0).detach().cpu().numpy()

        del hidden, input_ids, attention_mask, enc

        print(f"Processed prompts {end}/{n_prompts}")

    return pre_by_prompt, post_by_prompt, freq_by_prompt, metadata

Selected query-token counts:

       selected_query_tokens
count                  800.0
mean                     1.0
std                      0.0
min                      1.0
25%                      1.0
50%                      1.0
75%                      1.0
max                      1.0

Example selected offsets: [-2]
First prompt selected unpadded token positions: [577]

In [5]:

# ============================================================
# 4. Run final-demo-variant extraction
# ============================================================

pre_by_prompt, post_by_prompt, freq_by_prompt, prompt_metadata_loaded = collect_query_feature_stats_for_prompts(
    prompts=prompts,
    metadata=prompt_metadata,
)

# Reshape from [Q*V, F] to [Q, V, F]. Prompts were built query-major, then variant-major.
n_features = pre_by_prompt.shape[-1]
pre_by_query_variant = pre_by_prompt.reshape(N_QUERY_TOTAL, N_PREFIX_VARIANTS, n_features)
post_by_query_variant = post_by_prompt.reshape(N_QUERY_TOTAL, N_PREFIX_VARIANTS, n_features)
freq_by_query_variant = freq_by_prompt.reshape(N_QUERY_TOTAL, N_PREFIX_VARIANTS, n_features)

print("pre_by_query_variant:", pre_by_query_variant.shape)
print("post_by_query_variant:", post_by_query_variant.shape)
print("freq_by_query_variant:", freq_by_query_variant.shape)

Processed prompts 4/800
Processed prompts 8/800
Processed prompts 12/800
Processed prompts 16/800
Processed prompts 20/800
Processed prompts 24/800
Processed prompts 28/800
Processed prompts 32/800
Processed prompts 36/800
Processed prompts 40/800
Processed prompts 44/800
Processed prompts 48/800
Processed prompts 52/800
Processed prompts 56/800
Processed prompts 60/800
Processed prompts 64/800
Processed prompts 68/800
Processed prompts 72/800
Processed prompts 76/800
Processed prompts 80/800
Processed prompts 84/800
Processed prompts 88/800
Processed prompts 92/800
Processed prompts 96/800
Processed prompts 100/800
Processed prompts 104/800
Processed prompts 108/800
Processed prompts 112/800
Processed prompts 116/800
Processed prompts 120/800
Processed prompts 124/800
Processed prompts 128/800
Processed prompts 132/800
Processed prompts 136/800
Processed prompts 140/800
Processed prompts 144/800
Processed prompts 148/800
Processed prompts 152/800
Processed prompts 156/800
Processed prompts 160/800
Processed prompts 164/800
Processed prompts 168/800
Processed prompts 172/800
Processed prompts 176/800
Processed prompts 180/800
Processed prompts 184/800
Processed prompts 188/800
Processed prompts 192/800
Processed prompts 196/800
Processed prompts 200/800
Processed prompts 204/800
Processed prompts 208/800
Processed prompts 212/800
Processed prompts 216/800
Processed prompts 220/800
Processed prompts 224/800
Processed prompts 228/800
Processed prompts 232/800
Processed prompts 236/800
Processed prompts 240/800
Processed prompts 244/800
Processed prompts 248/800
Processed prompts 252/800
Processed prompts 256/800
Processed prompts 260/800
Processed prompts 264/800
Processed prompts 268/800
Processed prompts 272/800
Processed prompts 276/800
Processed prompts 280/800
Processed prompts 284/800
Processed prompts 288/800
Processed prompts 292/800
Processed prompts 296/800
Processed prompts 300/800
Processed prompts 304/800
Processed prompts 308/800
Processed prompts 312/800
Processed prompts 316/800
Processed prompts 320/800
Processed prompts 324/800
Processed prompts 328/800
Processed prompts 332/800
Processed prompts 336/800
Processed prompts 340/800
Processed prompts 344/800
Processed prompts 348/800
Processed prompts 352/800
Processed prompts 356/800
Processed prompts 360/800
Processed prompts 364/800
Processed prompts 368/800
Processed prompts 372/800
Processed prompts 376/800
Processed prompts 380/800
Processed prompts 384/800
Processed prompts 388/800
Processed prompts 392/800
Processed prompts 396/800
Processed prompts 400/800
Processed prompts 404/800
Processed prompts 408/800
Processed prompts 412/800
Processed prompts 416/800
Processed prompts 420/800
Processed prompts 424/800
Processed prompts 428/800
Processed prompts 432/800
Processed prompts 436/800
Processed prompts 440/800
Processed prompts 444/800
Processed prompts 448/800
Processed prompts 452/800
Processed prompts 456/800
Processed prompts 460/800
Processed prompts 464/800
Processed prompts 468/800
Processed prompts 472/800
Processed prompts 476/800
Processed prompts 480/800
Processed prompts 484/800
Processed prompts 488/800
Processed prompts 492/800
Processed prompts 496/800
Processed prompts 500/800
Processed prompts 504/800
Processed prompts 508/800
Processed prompts 512/800
Processed prompts 516/800
Processed prompts 520/800
Processed prompts 524/800
Processed prompts 528/800
Processed prompts 532/800
Processed prompts 536/800
Processed prompts 540/800
Processed prompts 544/800
Processed prompts 548/800
Processed prompts 552/800
Processed prompts 556/800
Processed prompts 560/800
Processed prompts 564/800
Processed prompts 568/800
Processed prompts 572/800
Processed prompts 576/800
Processed prompts 580/800
Processed prompts 584/800
Processed prompts 588/800
Processed prompts 592/800
Processed prompts 596/800
Processed prompts 600/800
Processed prompts 604/800
Processed prompts 608/800
Processed prompts 612/800
Processed prompts 616/800
Processed prompts 620/800
Processed prompts 624/800
Processed prompts 628/800
Processed prompts 632/800
Processed prompts 636/800
Processed prompts 640/800
Processed prompts 644/800
Processed prompts 648/800
Processed prompts 652/800
Processed prompts 656/800
Processed prompts 660/800
Processed prompts 664/800
Processed prompts 668/800
Processed prompts 672/800
Processed prompts 676/800
Processed prompts 680/800
Processed prompts 684/800
Processed prompts 688/800
Processed prompts 692/800
Processed prompts 696/800
Processed prompts 700/800
Processed prompts 704/800
Processed prompts 708/800
Processed prompts 712/800
Processed prompts 716/800
Processed prompts 720/800
Processed prompts 724/800
Processed prompts 728/800
Processed prompts 732/800
Processed prompts 736/800
Processed prompts 740/800
Processed prompts 744/800
Processed prompts 748/800
Processed prompts 752/800
Processed prompts 756/800
Processed prompts 760/800
Processed prompts 764/800
Processed prompts 768/800
Processed prompts 772/800
Processed prompts 776/800
Processed prompts 780/800
Processed prompts 784/800
Processed prompts 788/800
Processed prompts 792/800
Processed prompts 796/800
Processed prompts 800/800
pre_by_query_variant: (100, 8, 16384)
post_by_query_variant: (100, 8, 16384)
freq_by_query_variant: (100, 8, 16384)

In [6]:

# ============================================================
# 5. Label-specific feature selection and multi-prefix stability
# ============================================================

# Query labels in the same query-major order used by pre_by_query_variant/post_by_query_variant.
query_meta_df = meta_df.drop_duplicates("query_local_idx").sort_values("query_local_idx").reset_index(drop=True)
query_labels = query_meta_df["query_label"].to_numpy(dtype=np.int64)
if len(query_labels) != N_QUERY_TOTAL:
    raise AssertionError(f"Expected {N_QUERY_TOTAL} query labels, got {len(query_labels)}")

print("Query label counts used for label-specific scoring:")
display(pd.Series(query_labels).map(label_to_words_agnews).value_counts().sort_index().to_frame("count"))


def label_vs_other_means(arr_qvf: np.ndarray, labels: np.ndarray):
    """
    Compute label-vs-other means for arrays shaped [Q, V, F].

    Returns:
      label_mean: [L, V, F]
      other_mean: [L, V, F]
    """
    if arr_qvf.shape[0] != labels.shape[0]:
        raise ValueError(f"arr_qvf has {arr_qvf.shape[0]} queries but labels has {labels.shape[0]}")
    label_mean = np.zeros((NUM_LABELS, arr_qvf.shape[1], arr_qvf.shape[2]), dtype=np.float32)
    other_mean = np.zeros_like(label_mean)
    for lab in range(NUM_LABELS):
        mask = labels == lab
        other = ~mask
        if mask.sum() == 0 or other.sum() == 0:
            raise RuntimeError(f"Need at least one label-{lab} and one non-label-{lab} query.")
        label_mean[lab] = arr_qvf[mask].mean(axis=0)
        other_mean[lab] = arr_qvf[other].mean(axis=0)
    return label_mean, other_mean


# Label-specific score requested by the user:
#   average preactivation on label L - average preactivation on all other labels.
label_mean_pre, other_mean_pre = label_vs_other_means(pre_by_query_variant, query_labels)
label_mean_post, other_mean_post = label_vs_other_means(post_by_query_variant, query_labels)
label_mean_freq, other_mean_freq = label_vs_other_means(freq_by_query_variant, query_labels)
label_specific_pre_gap = label_mean_pre - other_mean_pre  # [label, variant, feature]

# Rank every feature by label-specific preactivation gap within each label and prefix variant.
label_variant_ranks = np.empty_like(label_specific_pre_gap, dtype=np.int32)  # [L, V, F]
for lab in range(NUM_LABELS):
    for v in range(N_PREFIX_VARIANTS):
        order = np.argsort(-label_specific_pre_gap[lab, v])
        ranks_v = np.empty(n_features, dtype=np.int32)
        ranks_v[order] = np.arange(1, n_features + 1, dtype=np.int32)
        label_variant_ranks[lab, v] = ranks_v


def summarize_label_specific_feature(lab: int, feat: int, rank: int):
    scores_v = label_specific_pre_gap[lab, :, feat]
    ranks_v = label_variant_ranks[lab, :, feat]
    baseline = float(scores_v[0])
    mean_score = float(scores_v.mean())
    std_score = float(scores_v.std(ddof=0))
    min_score = float(scores_v.min())
    max_score = float(scores_v.max())
    score_range = float(max_score - min_score)
    eps = 1e-12

    if baseline > eps:
        min_over_baseline = float(min_score / baseline)
        mean_over_baseline = float(mean_score / baseline)
    else:
        min_over_baseline = np.nan
        mean_over_baseline = np.nan

    retention_rate = float((ranks_v <= RETENTION_TOP_K).mean())
    stable = bool(
        (retention_rate >= STABLE_MIN_RETENTION)
        and np.isfinite(min_over_baseline)
        and (min_over_baseline >= STABLE_MIN_BASELINE_RATIO)
    )

    return {
        "label": int(lab),
        "label_word": label_to_words_agnews[int(lab)],
        "label_specific_rank": int(rank),
        "feature_idx": int(feat),
        "baseline_label_specific_pre_gap": baseline,
        "mean_label_specific_pre_gap_across_prefixes": mean_score,
        "std_label_specific_pre_gap_across_prefixes": std_score,
        "min_label_specific_pre_gap_across_prefixes": min_score,
        "max_label_specific_pre_gap_across_prefixes": max_score,
        "range_label_specific_pre_gap_across_prefixes": score_range,
        "mean_over_baseline": mean_over_baseline,
        "min_over_baseline": min_over_baseline,
        f"retention_rate_top_{RETENTION_TOP_K}": retention_rate,
        "worst_variant_rank": int(ranks_v.max()),
        "best_variant_rank": int(ranks_v.min()),
        "stable_by_rule": stable,
        "baseline_mean_pre_label": float(label_mean_pre[lab, 0, feat]),
        "baseline_mean_pre_other": float(other_mean_pre[lab, 0, feat]),
        "baseline_mean_post_label": float(label_mean_post[lab, 0, feat]),
        "baseline_mean_post_other": float(other_mean_post[lab, 0, feat]),
        "baseline_activation_frequency_label": float(label_mean_freq[lab, 0, feat]),
        "baseline_activation_frequency_other": float(other_mean_freq[lab, 0, feat]),
        "mean_pre_label_across_prefixes": float(label_mean_pre[lab, :, feat].mean()),
        "mean_pre_other_across_prefixes": float(other_mean_pre[lab, :, feat].mean()),
        "mean_post_label_across_prefixes": float(label_mean_post[lab, :, feat].mean()),
        "mean_post_other_across_prefixes": float(other_mean_post[lab, :, feat].mean()),
        "activation_frequency_label_across_prefixes": float(label_mean_freq[lab, :, feat].mean()),
        "activation_frequency_other_across_prefixes": float(other_mean_freq[lab, :, feat].mean()),
    }


label_top_features = {}
rows = []
for lab in range(NUM_LABELS):
    baseline_scores = label_specific_pre_gap[lab, 0]  # ordinary single-prefix setting, variant 0
    order = np.argsort(-baseline_scores)
    top_feats = [int(x) for x in order[:LABEL_SPECIFIC_TOP_N]]
    label_top_features[lab] = top_feats
    for rank, feat in enumerate(top_feats, start=1):
        rows.append(summarize_label_specific_feature(lab=lab, feat=feat, rank=rank))

label_specific_stability_df = pd.DataFrame(rows)
label_specific_stability_df = label_specific_stability_df.sort_values(
    by=["label", "label_specific_rank"],
    ascending=[True, True],
).reset_index(drop=True)

lfh_sensitive_label_specific_df = label_specific_stability_df[~label_specific_stability_df["stable_by_rule"]].sort_values(
    by=["label", "label_specific_rank"],
    ascending=[True, True],
).reset_index(drop=True)

print(f"Top-{LABEL_SPECIFIC_TOP_N} label-specific features per label, selected by baseline preactivation gap.")
display(label_specific_stability_df)

print("\nOriginally top-ranked label-specific features flagged as LFH-sensitive by the simple multi-prefix rule:")
display(lfh_sensitive_label_specific_df)

print("\nPer-label tables:")
for lab in range(NUM_LABELS):
    label_word = label_to_words_agnews[lab]
    print("=" * 100)
    print(f"{label_word}: top-{LABEL_SPECIFIC_TOP_N} label-specific features")
    display(label_specific_stability_df[label_specific_stability_df["label"] == lab].reset_index(drop=True))

# Union of all top label-specific features, useful for optional controls.
candidate_label_feature_pairs = [
    (int(row["label"]), int(row["feature_idx"]))
    for _, row in label_specific_stability_df.iterrows()
]
candidate_feature_ids = sorted({feat for _, feat in candidate_label_feature_pairs})
print(f"Union of selected features across labels: {len(candidate_feature_ids)} unique features.")

Query label counts used for label-specific scoring:

            count
Business       25
Sports         25
Technology     25
World          25

Top-20 label-specific features per label, selected by baseline preactivation gap.

,label,label_word,label_specific_rank,feature_idx,baseline_label_specific_pre_gap,mean_label_specific_pre_gap_across_prefixes,std_label_specific_pre_gap_across_prefixes,min_label_specific_pre_gap_across_prefixes,max_label_specific_pre_gap_across_prefixes,range_label_specific_pre_gap_across_prefixes,...,baseline_mean_post_label,baseline_mean_post_other,baseline_activation_frequency_label,baseline_activation_frequency_other,mean_pre_label_across_prefixes,mean_pre_other_across_prefixes,mean_post_label_across_prefixes,mean_post_other_across_prefixes,activation_frequency_label_across_prefixes,activation_frequency_other_across_prefixes
0,0,World,1,14090,10.535886,11.010969,0.462503,10.438230,11.786680,1.348451,...,8.633125,1.132292,0.88,0.200000,9.022001,-1.988966,9.024531,1.086406,0.885,0.176667
1,0,World,2,1041,9.400000,7.415417,1.841982,5.306667,10.090000,4.783333,...,29.400000,20.386667,1.00,0.866667,25.852501,18.437084,25.915001,18.914167,0.950,0.895000
2,0,World,3,5185,6.020338,6.284726,0.363175,5.862135,6.825755,0.963620,...,4.573750,1.185417,0.72,0.200000,4.201113,-2.083613,4.618125,0.949818,0.640,0.168333
3,0,World,4,14599,4.966927,5.040378,0.374012,4.669115,5.816979,1.147865,...,9.920000,5.141667,1.00,0.640000,10.021523,4.981146,9.950313,5.299636,0.970,0.658333
4,0,World,5,9632,4.889818,4.474204,0.387047,3.779115,5.040885,1.261771,...,6.170000,2.414167,0.72,0.293333,4.683486,0.209282,5.661797,2.304089,0.680,0.305000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,3,Technology,16,11970,2.566107,2.470677,0.150967,2.161139,2.616777,0.455638,...,0.475625,0.048125,0.12,0.013333,0.868542,-1.602135,0.444922,0.030495,0.120,0.008333
76,3,Technology,17,11807,2.408334,2.006563,0.273738,1.615001,2.408334,0.793333,...,0.000000,0.000000,0.00,0.000000,-12.076876,-14.083438,0.000000,0.000000,0.000,0.000000
77,3,Technology,18,1443,2.175729,2.035298,0.152326,1.802969,2.203516,0.400547,...,0.138750,0.057500,0.04,0.013333,0.177363,-1.857935,0.094844,0.033359,0.025,0.008333
78,3,Technology,19,9059,2.104870,1.189616,0.532223,0.404271,2.104870,1.700599,...,2.018125,1.048333,0.28,0.133333,-0.888887,-2.078503,1.689531,1.407865,0.275,0.180000
79,3,Technology,20,4626,2.090404,1.494560,0.294586,1.063073,2.090404,1.027331,...,0.278125,0.104583,0.08,0.026667,0.138926,-1.355635,0.127500,0.058698,0.035,0.015000

Originally top-ranked label-specific features flagged as LFH-sensitive by the simple multi-prefix rule:

,label,label_word,label_specific_rank,feature_idx,baseline_label_specific_pre_gap,mean_label_specific_pre_gap_across_prefixes,std_label_specific_pre_gap_across_prefixes,min_label_specific_pre_gap_across_prefixes,max_label_specific_pre_gap_across_prefixes,range_label_specific_pre_gap_across_prefixes,...,baseline_mean_post_label,baseline_mean_post_other,baseline_activation_frequency_label,baseline_activation_frequency_other,mean_pre_label_across_prefixes,mean_pre_other_across_prefixes,mean_post_label_across_prefixes,mean_post_other_across_prefixes,activation_frequency_label_across_prefixes,activation_frequency_other_across_prefixes
0,0,World,9,12633,3.880599,3.421231,0.306985,2.868229,3.880599,1.012370,...,2.287500,1.175000,0.32,0.200000,2.200937,-1.220293,2.048750,1.066016,0.355,0.196667
1,0,World,12,8745,3.575313,2.922533,0.316825,2.527396,3.575313,1.047917,...,1.365000,2.036250,0.24,0.253333,0.723887,-2.198646,1.247031,1.730469,0.235,0.226667
2,0,World,14,3607,3.468281,2.783596,0.491979,1.999193,3.468281,1.469089,...,7.726250,3.854167,0.80,0.520000,6.763603,3.980008,7.106406,3.920182,0.790,0.545000
3,0,World,17,5266,3.168906,2.960234,0.239341,2.630208,3.439323,0.809114,...,0.151250,0.000000,0.04,0.000000,-0.781289,-3.741524,0.121719,0.000000,0.030,0.000000
4,0,World,19,3117,3.056589,2.973333,0.172350,2.670859,3.242956,0.572096,...,2.775000,0.782500,0.48,0.133333,2.626328,-0.347005,2.841562,0.735885,0.510,0.126667
5,1,Sports,14,6518,4.232188,3.763144,0.405598,3.314089,4.386563,1.072474,...,4.070625,2.014583,0.72,0.306667,3.812060,0.048916,3.807344,1.949063,0.615,0.305000
6,1,Sports,16,6810,3.966667,4.238750,1.817455,0.046667,6.296667,6.250000,...,0.790000,0.350000,0.12,0.040000,-15.773749,-20.012501,1.136250,0.294167,0.085,0.041667
7,1,Sports,17,6457,3.894870,3.295293,0.430474,2.656094,3.988151,1.332057,...,0.145000,0.161667,0.04,0.026667,-1.056289,-4.351582,0.178750,0.217057,0.050,0.038333
8,1,Sports,18,1303,3.811953,3.389150,0.257395,3.094844,3.811953,0.717109,...,1.490000,0.150833,0.28,0.040000,2.168086,-1.221064,1.413047,0.132812,0.280,0.035000
9,1,Sports,19,12388,3.729245,3.279492,0.351830,2.775026,3.729245,0.954219,...,2.160625,0.469792,0.44,0.093333,2.435215,-0.844277,1.792656,0.488385,0.315,0.098333
10,2,Business,11,3268,2.836563,2.660832,0.215137,2.337162,2.951510,0.614349,...,0.000000,0.000000,0.00,0.000000,-3.838765,-6.499597,0.017969,0.000000,0.005,0.000000
11,2,Business,14,826,2.765703,2.656413,0.282027,2.172083,3.207370,1.035286,...,1.596250,1.086875,0.32,0.200000,2.310390,-0.346022,1.934062,0.947630,0.360,0.166667
12,2,Business,18,11086,2.470133,2.422937,0.116860,2.220719,2.555892,0.335173,...,0.643750,0.094167,0.16,0.026667,1.368141,-1.054796,0.515000,0.054036,0.130,0.015000
13,2,Business,19,10245,2.392422,1.854907,0.259929,1.519453,2.392422,0.872969,...,0.580000,0.000000,0.04,0.000000,-0.538369,-2.393276,0.269141,0.014609,0.045,0.003333
14,2,Business,20,2245,2.342604,2.184818,0.541491,1.406250,2.996875,1.590625,...,2.984375,2.756667,0.44,0.280000,2.695625,0.510807,2.766875,2.820287,0.425,0.313333
15,3,Technology,17,11807,2.408334,2.006563,0.273738,1.615001,2.408334,0.793333,...,0.000000,0.000000,0.00,0.000000,-12.076876,-14.083438,0.000000,0.000000,0.000,0.000000
16,3,Technology,18,1443,2.175729,2.035298,0.152326,1.802969,2.203516,0.400547,...,0.138750,0.057500,0.04,0.013333,0.177363,-1.857935,0.094844,0.033359,0.025,0.008333
17,3,Technology,19,9059,2.104870,1.189616,0.532223,0.404271,2.104870,1.700599,...,2.018125,1.048333,0.28,0.133333,-0.888887,-2.078503,1.689531,1.407865,0.275,0.180000
18,3,Technology,20,4626,2.090404,1.494560,0.294586,1.063073,2.090404,1.027331,...,0.278125,0.104583,0.08,0.026667,0.138926,-1.355635,0.127500,0.058698,0.035,0.015000

Per-label tables:
====================================================================================================
World: top-20 label-specific features

,label,label_word,label_specific_rank,feature_idx,baseline_label_specific_pre_gap,mean_label_specific_pre_gap_across_prefixes,std_label_specific_pre_gap_across_prefixes,min_label_specific_pre_gap_across_prefixes,max_label_specific_pre_gap_across_prefixes,range_label_specific_pre_gap_across_prefixes,...,baseline_mean_post_label,baseline_mean_post_other,baseline_activation_frequency_label,baseline_activation_frequency_other,mean_pre_label_across_prefixes,mean_pre_other_across_prefixes,mean_post_label_across_prefixes,mean_post_other_across_prefixes,activation_frequency_label_across_prefixes,activation_frequency_other_across_prefixes
0,0,World,1,14090,10.535886,11.010969,0.462503,10.438230,11.786680,1.348451,...,8.633125,1.132292,0.88,0.200000,9.022001,-1.988966,9.024531,1.086406,0.885,0.176667
1,0,World,2,1041,9.400000,7.415417,1.841982,5.306667,10.090000,4.783333,...,29.400000,20.386667,1.00,0.866667,25.852501,18.437084,25.915001,18.914167,0.950,0.895000
2,0,World,3,5185,6.020338,6.284726,0.363175,5.862135,6.825755,0.963620,...,4.573750,1.185417,0.72,0.200000,4.201113,-2.083613,4.618125,0.949818,0.640,0.168333
3,0,World,4,14599,4.966927,5.040378,0.374012,4.669115,5.816979,1.147865,...,9.920000,5.141667,1.00,0.640000,10.021523,4.981146,9.950313,5.299636,0.970,0.658333
4,0,World,5,9632,4.889818,4.474204,0.387047,3.779115,5.040885,1.261771,...,6.170000,2.414167,0.72,0.293333,4.683486,0.209282,5.661797,2.304089,0.680,0.305000
5,0,World,6,2600,4.358828,4.213376,0.302375,3.678854,4.543125,0.864271,...,1.761250,0.106042,0.40,0.026667,2.247178,-1.966198,1.678750,0.053568,0.375,0.015000
6,0,World,7,5719,4.093334,4.152500,0.285042,3.661667,4.586666,0.924999,...,0.000000,0.000000,0.00,0.000000,-24.026249,-28.178749,0.000000,0.000000,0.000,0.000000
7,0,World,8,7921,4.070001,3.746042,0.200006,3.337500,4.070001,0.732501,...,0.000000,0.000000,0.00,0.000000,-13.432501,-17.178541,0.000000,0.000000,0.000,0.000000
8,0,World,9,12633,3.880599,3.421231,0.306985,2.868229,3.880599,1.012370,...,2.287500,1.175000,0.32,0.200000,2.200937,-1.220293,2.048750,1.066016,0.355,0.196667
9,0,World,10,9720,3.704857,4.133135,0.199130,3.704857,4.383021,0.678164,...,10.901250,7.154375,0.92,0.853333,11.421953,7.288818,11.336172,7.180756,0.950,0.861667
10,0,World,11,8806,3.686322,3.922911,0.274552,3.375313,4.364684,0.989371,...,0.000000,0.000000,0.00,0.000000,-3.846409,-7.769320,0.127109,0.000000,0.030,0.000000
11,0,World,12,8745,3.575313,2.922533,0.316825,2.527396,3.575313,1.047917,...,1.365000,2.036250,0.24,0.253333,0.723887,-2.198646,1.247031,1.730469,0.235,0.226667
12,0,World,13,12621,3.498815,3.380781,0.127572,3.149193,3.542630,0.393437,...,0.640625,0.093958,0.16,0.026667,1.484985,-1.895796,0.617344,0.060208,0.150,0.016667
13,0,World,14,3607,3.468281,2.783596,0.491979,1.999193,3.468281,1.469089,...,7.726250,3.854167,0.80,0.520000,6.763603,3.980008,7.106406,3.920182,0.790,0.545000
14,0,World,15,3812,3.289433,3.553783,0.457899,3.049219,4.444316,1.395098,...,4.338750,2.216875,0.48,0.373333,2.016350,-1.537433,4.448906,1.974662,0.525,0.310000
15,0,World,16,5089,3.271888,3.371716,0.195586,3.032480,3.653815,0.621335,...,3.650625,0.587917,0.64,0.120000,3.987231,0.615515,3.595469,0.652917,0.645,0.143333
16,0,World,17,5266,3.168906,2.960234,0.239341,2.630208,3.439323,0.809114,...,0.151250,0.000000,0.04,0.000000,-0.781289,-3.741524,0.121719,0.000000,0.030,0.000000
17,0,World,18,13287,3.130677,3.287093,0.128239,3.081250,3.431940,0.350690,...,0.130625,0.000000,0.04,0.000000,-1.950264,-5.237357,0.034766,0.000000,0.010,0.000000
18,0,World,19,3117,3.056589,2.973333,0.172350,2.670859,3.242956,0.572096,...,2.775000,0.782500,0.48,0.133333,2.626328,-0.347005,2.841562,0.735885,0.510,0.126667
19,0,World,20,11262,3.039660,3.107139,0.108487,3.011302,3.330402,0.319100,...,4.295000,1.052917,0.88,0.253333,4.415669,1.308530,4.071797,0.904115,0.800,0.215000

====================================================================================================
Sports: top-20 label-specific features

,label,label_word,label_specific_rank,feature_idx,baseline_label_specific_pre_gap,mean_label_specific_pre_gap_across_prefixes,std_label_specific_pre_gap_across_prefixes,min_label_specific_pre_gap_across_prefixes,max_label_specific_pre_gap_across_prefixes,range_label_specific_pre_gap_across_prefixes,...,baseline_mean_post_label,baseline_mean_post_other,baseline_activation_frequency_label,baseline_activation_frequency_other,mean_pre_label_across_prefixes,mean_pre_other_across_prefixes,mean_post_label_across_prefixes,mean_post_other_across_prefixes,activation_frequency_label_across_prefixes,activation_frequency_other_across_prefixes
0,1,Sports,1,8745,9.245937,8.471205,0.579436,7.693724,9.248724,1.555000,...,5.628750,0.615000,0.68,0.106667,4.885390,-3.585814,4.893750,0.514896,0.615,0.100000
1,1,Sports,2,4758,8.617722,8.679970,0.367313,8.207603,9.206654,0.999050,...,10.350000,1.042292,1.00,0.253333,10.449687,1.769718,10.449687,0.913255,1.000,0.216667
2,1,Sports,3,2863,8.447344,8.922070,0.457307,8.064584,9.489375,1.424791,...,5.710000,1.367500,0.76,0.186667,6.274434,-2.647637,6.118750,1.350000,0.765,0.205000
3,1,Sports,4,5160,7.059674,6.781435,0.494681,5.931094,7.532813,1.601719,...,6.736250,1.437917,0.72,0.226667,6.450928,-0.330508,6.647110,1.610703,0.735,0.261667
4,1,Sports,5,12369,6.620827,6.469864,0.418956,5.819180,7.101211,1.282032,...,7.648750,2.303958,0.84,0.320000,7.375440,0.905576,7.379141,2.331667,0.845,0.333333
5,1,Sports,6,10967,6.114896,6.304519,0.196481,6.074948,6.685521,0.610573,...,10.933750,4.503334,0.96,0.613333,11.465664,5.161146,11.420313,4.805834,0.980,0.673333
6,1,Sports,7,14851,5.910625,5.615187,0.444333,5.124011,6.431355,1.307344,...,4.503750,1.137500,0.68,0.213333,4.096406,-1.518781,4.785703,1.007396,0.690,0.180000
7,1,Sports,8,11313,5.748385,5.381244,0.410993,4.556302,5.967657,1.411355,...,1.771250,0.367917,0.32,0.080000,1.334004,-4.047240,1.587813,0.264323,0.260,0.063333
8,1,Sports,9,5638,5.524336,5.328878,0.301056,4.913906,5.901133,0.987226,...,1.120000,0.000000,0.24,0.000000,1.628589,-3.700290,1.181875,0.000000,0.255,0.000000
9,1,Sports,10,9632,5.520547,4.954178,0.402684,4.355625,5.520547,1.164922,...,5.647500,2.588333,0.64,0.320000,5.043467,0.089289,5.137578,2.478828,0.635,0.320000
10,1,Sports,11,12633,5.013203,4.239668,0.370695,3.807109,5.013203,1.206094,...,3.367500,0.815000,0.56,0.120000,2.814765,-1.424902,2.658047,0.862917,0.485,0.153333
11,1,Sports,12,3812,4.711959,4.329213,0.480825,3.433385,5.066283,1.632897,...,3.665000,2.441458,0.64,0.320000,2.597923,-1.731291,3.007187,2.455235,0.490,0.321667
12,1,Sports,13,5474,4.543802,4.275605,0.613557,3.445651,5.350338,1.904687,...,1.498750,0.127917,0.16,0.026667,-0.905713,-5.181318,1.384609,0.139323,0.190,0.028333
13,1,Sports,14,6518,4.232188,3.763144,0.405598,3.314089,4.386563,1.072474,...,4.070625,2.014583,0.72,0.306667,3.812060,0.048916,3.807344,1.949063,0.615,0.305000
14,1,Sports,15,1685,3.972604,3.823997,0.205079,3.559166,4.223437,0.664271,...,0.000000,0.000000,0.00,0.000000,-1.430664,-5.254662,0.000000,0.000000,0.000,0.000000
15,1,Sports,16,6810,3.966667,4.238750,1.817455,0.046667,6.296667,6.250000,...,0.790000,0.350000,0.12,0.040000,-15.773749,-20.012501,1.136250,0.294167,0.085,0.041667
16,1,Sports,17,6457,3.894870,3.295293,0.430474,2.656094,3.988151,1.332057,...,0.145000,0.161667,0.04,0.026667,-1.056289,-4.351582,0.178750,0.217057,0.050,0.038333
17,1,Sports,18,1303,3.811953,3.389150,0.257395,3.094844,3.811953,0.717109,...,1.490000,0.150833,0.28,0.040000,2.168086,-1.221064,1.413047,0.132812,0.280,0.035000
18,1,Sports,19,12388,3.729245,3.279492,0.351830,2.775026,3.729245,0.954219,...,2.160625,0.469792,0.44,0.093333,2.435215,-0.844277,1.792656,0.488385,0.315,0.098333
19,1,Sports,20,10867,3.638906,3.548480,0.200776,3.363841,3.963073,0.599232,...,0.949375,0.000000,0.24,0.000000,1.855396,-1.693084,1.027266,0.000000,0.250,0.000000

====================================================================================================
Business: top-20 label-specific features

,label,label_word,label_specific_rank,feature_idx,baseline_label_specific_pre_gap,mean_label_specific_pre_gap_across_prefixes,std_label_specific_pre_gap_across_prefixes,min_label_specific_pre_gap_across_prefixes,max_label_specific_pre_gap_across_prefixes,range_label_specific_pre_gap_across_prefixes,...,baseline_mean_post_label,baseline_mean_post_other,baseline_activation_frequency_label,baseline_activation_frequency_other,mean_pre_label_across_prefixes,mean_pre_other_across_prefixes,mean_post_label_across_prefixes,mean_post_other_across_prefixes,activation_frequency_label_across_prefixes,activation_frequency_other_across_prefixes
0,2,Business,1,13946,8.183893,8.621265,0.497649,8.051654,9.678268,1.626615,...,8.168750,2.342500,0.80,0.280000,8.015503,-0.605762,8.255078,2.248750,0.780,0.270000
1,2,Business,2,4300,6.055885,6.026465,0.394313,5.471042,6.604948,1.133906,...,4.858125,0.462292,0.60,0.093333,3.951289,-2.075176,4.886328,0.536406,0.555,0.105000
2,2,Business,3,2992,5.066381,4.503180,0.464620,3.932109,5.067864,1.135755,...,3.234375,1.848333,0.52,0.253333,2.550303,-1.952878,2.996797,1.696146,0.460,0.243333
3,2,Business,4,9059,4.688516,4.829642,0.298273,4.345469,5.232187,0.886719,...,2.990625,0.724167,0.36,0.106667,1.841133,-2.988509,3.621172,0.763984,0.410,0.135000
4,2,Business,5,14526,4.265446,4.237247,0.282547,3.608001,4.569173,0.961172,...,3.616250,1.686875,0.52,0.306667,3.427772,-0.809476,3.527109,1.542865,0.560,0.255000
5,2,Business,6,15109,4.202474,3.875576,0.209360,3.620677,4.202474,0.581797,...,1.781875,0.136667,0.36,0.026667,1.937783,-1.937793,1.577500,0.115417,0.365,0.021667
6,2,Business,7,10466,4.055599,3.798018,0.245648,3.296224,4.078073,0.781849,...,1.922500,0.382500,0.36,0.080000,2.491738,-1.306279,1.959844,0.354688,0.380,0.081667
7,2,Business,8,3635,3.261758,3.422835,0.290452,2.867174,3.950729,1.083555,...,0.000000,0.000000,0.00,0.000000,-2.185293,-5.608128,0.133125,0.000000,0.035,0.000000
8,2,Business,9,3607,3.010573,3.254312,0.288610,2.726107,3.603242,0.877135,...,6.685000,4.201250,0.80,0.520000,7.116641,3.862329,6.903750,3.987734,0.870,0.518333
9,2,Business,10,1370,2.900234,3.021581,0.141550,2.825163,3.289889,0.464727,...,0.000000,0.000000,0.00,0.000000,-0.492080,-3.513661,0.000000,0.000000,0.000,0.000000
10,2,Business,11,3268,2.836563,2.660832,0.215137,2.337162,2.951510,0.614349,...,0.000000,0.000000,0.00,0.000000,-3.838765,-6.499597,0.017969,0.000000,0.005,0.000000
11,2,Business,12,9706,2.820104,2.767259,0.300501,2.292474,3.274245,0.981771,...,4.711875,2.137917,0.80,0.306667,4.864043,2.096784,4.558125,2.105208,0.720,0.306667
12,2,Business,13,5493,2.785599,2.779198,0.187587,2.436589,3.095833,0.659245,...,4.796875,2.526458,0.80,0.453333,5.332109,2.552911,4.854531,2.582292,0.790,0.488333
13,2,Business,14,826,2.765703,2.656413,0.282027,2.172083,3.207370,1.035286,...,1.596250,1.086875,0.32,0.200000,2.310390,-0.346022,1.934062,0.947630,0.360,0.166667
14,2,Business,15,16158,2.751823,2.852774,0.068484,2.751823,2.973177,0.221354,...,1.587500,0.111667,0.36,0.026667,2.070742,-0.782031,1.548594,0.068698,0.340,0.016667
15,2,Business,16,15497,2.659792,2.601407,0.134852,2.400417,2.777604,0.377187,...,0.000000,0.000000,0.00,0.000000,-4.640039,-7.241446,0.000000,0.000000,0.000,0.000000
16,2,Business,17,2145,2.610547,2.668584,0.052149,2.598438,2.758203,0.159765,...,0.155000,0.000000,0.04,0.000000,0.581826,-2.086758,0.088750,0.000000,0.025,0.000000
17,2,Business,18,11086,2.470133,2.422937,0.116860,2.220719,2.555892,0.335173,...,0.643750,0.094167,0.16,0.026667,1.368141,-1.054796,0.515000,0.054036,0.130,0.015000
18,2,Business,19,10245,2.392422,1.854907,0.259929,1.519453,2.392422,0.872969,...,0.580000,0.000000,0.04,0.000000,-0.538369,-2.393276,0.269141,0.014609,0.045,0.003333
19,2,Business,20,2245,2.342604,2.184818,0.541491,1.406250,2.996875,1.590625,...,2.984375,2.756667,0.44,0.280000,2.695625,0.510807,2.766875,2.820287,0.425,0.313333

====================================================================================================
Technology: top-20 label-specific features

,label,label_word,label_specific_rank,feature_idx,baseline_label_specific_pre_gap,mean_label_specific_pre_gap_across_prefixes,std_label_specific_pre_gap_across_prefixes,min_label_specific_pre_gap_across_prefixes,max_label_specific_pre_gap_across_prefixes,range_label_specific_pre_gap_across_prefixes,...,baseline_mean_post_label,baseline_mean_post_other,baseline_activation_frequency_label,baseline_activation_frequency_other,mean_pre_label_across_prefixes,mean_pre_other_across_prefixes,mean_post_label_across_prefixes,mean_post_other_across_prefixes,activation_frequency_label_across_prefixes,activation_frequency_other_across_prefixes
0,3,Technology,1,2245,10.090416,8.761204,0.663875,7.877018,10.090416,2.213398,...,8.015000,1.079792,0.80,0.160000,7.627915,-1.133289,7.595390,1.210781,0.775,0.196667
1,3,Technology,2,14906,6.573333,7.124912,0.440537,6.573333,8.104662,1.531329,...,0.180000,0.095833,0.04,0.013333,-1.155562,-8.280474,0.611094,0.100208,0.120,0.013333
2,3,Technology,3,6810,6.473333,5.460416,1.012260,4.336667,7.379999,3.043332,...,1.050000,0.263333,0.12,0.040000,-14.857500,-20.317917,0.510000,0.502917,0.070,0.046667
3,3,Technology,4,2992,5.300130,4.855121,0.377165,4.218698,5.301589,1.082891,...,3.766875,1.670833,0.52,0.253333,2.814258,-2.040863,3.438750,1.548828,0.515,0.225000
4,3,Technology,5,12609,5.181510,4.951852,0.210619,4.653802,5.229479,0.575677,...,0.200000,0.000000,0.04,0.000000,-2.263037,-7.214890,0.179297,0.000000,0.045,0.000000
5,3,Technology,6,14559,5.149831,4.719727,0.273207,4.304310,5.149831,0.845521,...,3.083125,0.162917,0.48,0.026667,2.644692,-2.075034,3.086406,0.156771,0.500,0.023333
6,3,Technology,7,6049,4.664166,4.616022,0.170239,4.275911,4.869375,0.593464,...,1.083750,0.000000,0.20,0.000000,1.490469,-3.125553,1.363828,0.000000,0.295,0.000000
7,3,Technology,8,9257,4.543282,4.052793,0.369182,3.396927,4.543282,1.146354,...,5.981250,2.262292,0.76,0.386667,5.528047,1.475254,5.746797,2.396745,0.725,0.398333
8,3,Technology,9,826,4.095912,3.460371,0.389010,2.916224,4.095912,1.179688,...,3.020625,0.612083,0.56,0.120000,2.913359,-0.547012,2.559219,0.739245,0.435,0.141667
9,3,Technology,10,9706,3.697083,3.217168,0.373062,2.677891,3.728620,1.050729,...,5.323750,1.933958,0.72,0.333333,5.201475,1.984307,4.988438,1.961771,0.685,0.318333
10,3,Technology,11,2863,3.425885,3.388789,0.426954,2.699844,4.152292,1.452448,...,3.111250,2.233750,0.36,0.320000,2.124473,-1.264316,2.767656,2.467031,0.390,0.330000
11,3,Technology,12,10852,3.375039,2.807694,0.398130,2.091172,3.375039,1.283867,...,0.185000,0.000000,0.04,0.000000,-0.950146,-3.757840,0.447188,0.121927,0.105,0.026667
12,3,Technology,13,8841,3.050599,2.751696,0.182151,2.536354,3.050599,0.514245,...,0.000000,0.000000,0.00,0.000000,-2.185332,-4.937028,0.000000,0.000000,0.000,0.000000
13,3,Technology,14,14588,2.975260,2.731677,0.137402,2.512910,2.975260,0.462350,...,2.513125,0.339583,0.44,0.093333,3.189106,0.457429,2.255859,0.252786,0.415,0.068333
14,3,Technology,15,10410,2.677917,2.565475,0.175232,2.240625,2.833646,0.593021,...,0.000000,0.000000,0.00,0.000000,-3.671230,-6.236706,0.000000,0.000000,0.000,0.000000
15,3,Technology,16,11970,2.566107,2.470677,0.150967,2.161139,2.616777,0.455638,...,0.475625,0.048125,0.12,0.013333,0.868542,-1.602135,0.444922,0.030495,0.120,0.008333
16,3,Technology,17,11807,2.408334,2.006563,0.273738,1.615001,2.408334,0.793333,...,0.000000,0.000000,0.00,0.000000,-12.076876,-14.083438,0.000000,0.000000,0.000,0.000000
17,3,Technology,18,1443,2.175729,2.035298,0.152326,1.802969,2.203516,0.400547,...,0.138750,0.057500,0.04,0.013333,0.177363,-1.857935,0.094844,0.033359,0.025,0.008333
18,3,Technology,19,9059,2.104870,1.189616,0.532223,0.404271,2.104870,1.700599,...,2.018125,1.048333,0.28,0.133333,-0.888887,-2.078503,1.689531,1.407865,0.275,0.180000
19,3,Technology,20,4626,2.090404,1.494560,0.294586,1.063073,2.090404,1.027331,...,0.278125,0.104583,0.08,0.026667,0.138926,-1.355635,0.127500,0.058698,0.035,0.015000

Union of selected features across labels: 68 unique features.

## 5A. Rank table for baseline top-20 label-specific features across P2–P8

This diagnostic keeps the 80 features selected from the ordinary baseline prefix `P1` and reports where each one ranks under the alternative final-demo prefixes `P2` through `P8`. Rank `1` means the most label-specific feature for that label under that prefix; larger ranks indicate that the feature becomes less label-specific under that prefix.

In [7]:

# ============================================================
# 5A. Rank table: baseline top-20 label-specific features in P2..P8
# ============================================================

# This cell assumes Section 5 has already run and created:
#   label_specific_stability_df
#   label_variant_ranks
#   label_specific_pre_gap
#   label_top_features
#
# Interpretation:
#   P1 is the ordinary single-prefix baseline used to select top-20 features.
#   P2..P8 keep the same queries and demos 1..7, but replace only demo 8.
#   Rank 1 = most label-specific feature for that label under that prefix.

required_for_rank_table = [
    "label_specific_stability_df",
    "label_variant_ranks",
    "label_specific_pre_gap",
    "label_top_features",
]
missing = [name for name in required_for_rank_table if name not in globals()]
if missing:
    raise RuntimeError(
        "Run Sections 4 and 5 before this rank-table diagnostic. "
        f"Missing variables: {missing}"
    )

rank_rows = []
for _, row in label_specific_stability_df.iterrows():
    lab = int(row["label"])
    feat = int(row["feature_idx"])
    baseline_rank = int(row["label_specific_rank"])

    ranks = [int(label_variant_ranks[lab, v, feat]) for v in range(N_PREFIX_VARIANTS)]
    gaps = [float(label_specific_pre_gap[lab, v, feat]) for v in range(N_PREFIX_VARIANTS)]

    additional_ranks = ranks[1:]
    additional_gaps = gaps[1:]
    worst_additional_idx = int(np.argmax(additional_ranks)) + 1  # convert additional slot to variant index v
    best_additional_idx = int(np.argmin(additional_ranks)) + 1

    out = {
        "label_word": row["label_word"],
        "P1_baseline_rank": baseline_rank,
        "feature_idx": feat,
        "feature": f"L{TARGET_LAYER}-{feat}",
        "stable_by_rule": bool(row["stable_by_rule"]),
        "retention_rate_topK": float(row[f"retention_rate_top_{RETENTION_TOP_K}"]),
        "min_over_baseline": float(row["min_over_baseline"]),
        "baseline_gap_P1": float(gaps[0]),
        "worst_rank_P2_to_P8": int(max(additional_ranks)),
        "worst_prefix_P2_to_P8": f"P{worst_additional_idx + 1}",
        "best_rank_P2_to_P8": int(min(additional_ranks)),
        "best_prefix_P2_to_P8": f"P{best_additional_idx + 1}",
        f"n_P2_to_P8_in_top{RETENTION_TOP_K}": int(sum(r <= RETENTION_TOP_K for r in additional_ranks)),
    }

    # Add exact ranks and gaps for every prefix. P1 is included for context;
    # P2..P8 are the requested alternative-prefix ranks.
    for v in range(N_PREFIX_VARIANTS):
        out[f"P{v + 1}_rank"] = int(ranks[v])
    for v in range(N_PREFIX_VARIANTS):
        out[f"P{v + 1}_gap"] = float(gaps[v])

    rank_rows.append(out)

# Main table: one row per baseline-selected top-20 label-specific feature.
top20_label_specific_rank_by_prefix_df = pd.DataFrame(rank_rows)

rank_display_cols = (
    [
        "label_word",
        "P1_baseline_rank",
        "feature",
        "feature_idx",
        "stable_by_rule",
        "retention_rate_topK",
        "min_over_baseline",
        "baseline_gap_P1",
        "worst_rank_P2_to_P8",
        "worst_prefix_P2_to_P8",
        "best_rank_P2_to_P8",
        "best_prefix_P2_to_P8",
        f"n_P2_to_P8_in_top{RETENTION_TOP_K}",
    ]
    + [f"P{v + 1}_rank" for v in range(N_PREFIX_VARIANTS)]
)

# Requested table: rank under P2..P8 for each P1 top-20 label-specific feature.
print("=" * 100)
print(f"Ranks of P1 top-{LABEL_SPECIFIC_TOP_N} label-specific features under P2..P{N_PREFIX_VARIANTS}")
print("Rank 1 = most label-specific under that prefix. Larger ranks indicate loss of label specificity.")
print("=" * 100)
display(
    top20_label_specific_rank_by_prefix_df[rank_display_cols]
    .sort_values(["label_word", "P1_baseline_rank"])
    .reset_index(drop=True)
)

# Per-label compact tables, easier to copy into a rebuttal appendix.
for lab in range(NUM_LABELS):
    label_word = label_to_words_agnews[lab]
    print("=" * 100)
    print(f"{label_word}: P1 top-{LABEL_SPECIFIC_TOP_N} features and their ranks in P2..P{N_PREFIX_VARIANTS}")
    cols = (
        ["P1_baseline_rank", "feature", "stable_by_rule", "worst_rank_P2_to_P8", "worst_prefix_P2_to_P8"]
        + [f"P{v + 1}_rank" for v in range(1, N_PREFIX_VARIANTS)]
    )
    display(
        top20_label_specific_rank_by_prefix_df
        .loc[top20_label_specific_rank_by_prefix_df["label_word"] == label_word, cols]
        .sort_values("P1_baseline_rank")
        .reset_index(drop=True)
    )

# Worst rank collapses across all labels. This is useful for illustrating the single-prefix risk.
rank_collapse_examples_df = (
    top20_label_specific_rank_by_prefix_df
    .assign(rank_collapse=lambda df: df["worst_rank_P2_to_P8"] - df["P1_baseline_rank"])
    .sort_values("rank_collapse", ascending=False)
    .reset_index(drop=True)
)

print("=" * 100)
print("Largest rank-collapse examples among the P1 top-20 label-specific features")
print("=" * 100)
display(
    rank_collapse_examples_df[
        [
            "label_word", "P1_baseline_rank", "feature", "stable_by_rule",
            "worst_prefix_P2_to_P8", "worst_rank_P2_to_P8", "rank_collapse",
        ]
        + [f"P{v + 1}_rank" for v in range(N_PREFIX_VARIANTS)]
    ].head(20)
)

# Optional Plotly heatmap of log10(rank). This makes large rank collapses visible without saturating the scale.
def plot_top20_rank_heatmap_by_label(lab: int):
    label_word = label_to_words_agnews[int(lab)]
    sub = (
        top20_label_specific_rank_by_prefix_df
        .loc[top20_label_specific_rank_by_prefix_df["label_word"] == label_word]
        .sort_values("P1_baseline_rank")
        .reset_index(drop=True)
    )
    rank_cols = [f"P{v + 1}_rank" for v in range(N_PREFIX_VARIANTS)]
    ranks = sub[rank_cols].to_numpy(dtype=np.float64)
    log_ranks = np.log10(ranks)

    fig = go.Figure(
        data=go.Heatmap(
            z=log_ranks,
            x=[f"P{v + 1}" for v in range(N_PREFIX_VARIANTS)],
            y=[f"{r['feature']} (P1 rank {int(r['P1_baseline_rank'])})" for _, r in sub.iterrows()],
            colorscale="Blues",
            customdata=ranks,
            colorbar=dict(title="log10(rank)"),
            hovertemplate=(
                "feature=%{y}<br>prefix=%{x}<br>"
                "rank=%{customdata:.0f}<br>log10(rank)=%{z:.3f}<extra></extra>"
            ),
        )
    )
    fig.update_layout(
        title=f"{label_word}: ranks of P1 top-{LABEL_SPECIFIC_TOP_N} label-specific features across P1..P{N_PREFIX_VARIANTS}",
        xaxis_title="Prefix variant",
        yaxis_title="Feature selected from P1 baseline",
        height=max(450, 26 * len(sub) + 180),
        width=max(850, 90 * N_PREFIX_VARIANTS + 350),
    )
    fig.show()

for lab in range(NUM_LABELS):
    plot_top20_rank_heatmap_by_label(lab)

====================================================================================================
Ranks of P1 top-20 label-specific features under P2..P8
Rank 1 = most label-specific under that prefix. Larger ranks indicate loss of label specificity.
====================================================================================================

,label_word,P1_baseline_rank,feature,feature_idx,stable_by_rule,retention_rate_topK,min_over_baseline,baseline_gap_P1,worst_rank_P2_to_P8,worst_prefix_P2_to_P8,...,best_prefix_P2_to_P8,n_P2_to_P8_in_top20,P1_rank,P2_rank,P3_rank,P4_rank,P5_rank,P6_rank,P7_rank,P8_rank
0,Business,1,L12-13946,13946,True,1.000,0.983842,8.183893,1,P2,...,P2,7,1,1,1,1,1,1,1,1
1,Business,2,L12-4300,4300,True,1.000,0.903426,6.055885,2,P2,...,P2,7,2,2,2,2,2,2,2,2
2,Business,3,L12-2992,2992,True,1.000,0.776118,5.066381,5,P2,...,P4,7,3,5,5,3,4,4,5,4
3,Business,4,L12-9059,9059,True,1.000,0.926832,4.688516,4,P4,...,P2,7,4,3,3,4,3,3,3,3
4,Business,5,L12-14526,14526,True,1.000,0.845867,4.265446,7,P6,...,P2,7,5,4,4,5,5,7,4,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,World,16,L12-5089,5089,True,1.000,0.926829,3.271888,15,P4,...,P6,7,16,12,14,15,13,10,13,12
76,World,17,L12-5266,5266,False,0.625,0.830005,3.168906,26,P3,...,P8,4,17,24,26,19,20,17,22,14
77,World,18,L12-13287,13287,True,1.000,0.984212,3.130677,17,P3,...,P6,7,18,15,17,14,12,11,15,15
78,World,19,L12-3117,3117,False,0.625,0.873804,3.056589,25,P4,...,P5,4,19,16,19,25,15,22,18,23
79,World,20,L12-11262,11262,True,1.000,0.990671,3.039660,19,P7,...,P6,7,20,17,16,17,18,13,19,17

====================================================================================================
World: P1 top-20 features and their ranks in P2..P8

,P1_baseline_rank,feature,stable_by_rule,worst_rank_P2_to_P8,worst_prefix_P2_to_P8,P2_rank,P3_rank,P4_rank,P5_rank,P6_rank,P7_rank,P8_rank
0,1,L12-14090,True,1,P2,1,1,1,1,1,1,1
1,2,L12-1041,True,4,P4,2,2,4,3,2,2,3
2,3,L12-5185,True,3,P2,3,3,2,2,3,3,2
3,4,L12-14599,True,4,P2,4,4,3,4,4,4,4
4,5,L12-9632,True,9,P3,5,9,5,5,8,6,5
5,6,L12-2600,True,10,P3,6,10,9,6,7,7,6
6,7,L12-5719,True,10,P8,7,5,6,8,9,5,10
7,8,L12-7921,True,12,P6,11,7,10,10,12,11,11
8,9,L12-12633,False,21,P6,13,8,12,14,21,14,16
9,10,L12-9720,True,8,P2,8,6,7,7,6,8,8
10,11,L12-8806,True,11,P3,10,11,8,9,5,9,9
11,12,L12-8745,False,33,P6,19,15,18,25,33,32,21
12,13,L12-12621,True,15,P6,14,13,11,11,15,12,13
13,14,L12-3607,False,51,P4,21,47,51,16,16,20,27
14,15,L12-3812,True,17,P5,9,12,13,17,14,10,7
15,16,L12-5089,True,15,P4,12,14,15,13,10,13,12
16,17,L12-5266,False,26,P3,24,26,19,20,17,22,14
17,18,L12-13287,True,17,P3,15,17,14,12,11,15,15
18,19,L12-3117,False,25,P4,16,19,25,15,22,18,23
19,20,L12-11262,True,19,P7,17,16,17,18,13,19,17

====================================================================================================
Sports: P1 top-20 features and their ranks in P2..P8

,P1_baseline_rank,feature,stable_by_rule,worst_rank_P2_to_P8,worst_prefix_P2_to_P8,P2_rank,P3_rank,P4_rank,P5_rank,P6_rank,P7_rank,P8_rank
0,1,L12-8745,True,3,P3,2,3,3,3,2,3,3
1,2,L12-4758,True,3,P2,3,1,1,2,3,2,2
2,3,L12-2863,True,2,P3,1,2,2,1,1,1,1
3,4,L12-5160,True,6,P4,4,4,6,6,4,4,5
4,5,L12-12369,True,8,P7,7,5,5,4,5,8,4
5,6,L12-10967,True,6,P2,6,6,4,5,6,5,6
6,7,L12-14851,True,9,P3,5,9,7,7,9,7,9
7,8,L12-11313,True,11,P4,8,10,11,8,11,10,7
8,9,L12-5638,True,11,P3,9,11,9,9,10,11,8
9,10,L12-9632,True,12,P7,10,8,10,10,8,12,10
10,11,L12-12633,True,16,P3,14,16,13,12,13,15,12
11,12,L12-3812,True,16,P5,12,15,8,16,12,13,13
12,13,L12-5474,True,16,P8,11,12,15,13,14,9,16
13,14,L12-6518,False,23,P6,15,18,17,20,23,18,11
14,15,L12-1685,True,17,P3,13,17,14,14,15,14,14
15,16,L12-6810,False,7984,P8,21,7,12,11,7,6,7984
16,17,L12-6457,False,32,P5,16,22,23,32,29,21,23
17,18,L12-1303,False,25,P3,19,25,20,22,21,20,21
18,19,L12-12388,False,31,P7,23,24,25,25,16,31,17
19,20,L12-10867,True,19,P3,17,19,16,18,19,17,19

====================================================================================================
Business: P1 top-20 features and their ranks in P2..P8

,P1_baseline_rank,feature,stable_by_rule,worst_rank_P2_to_P8,worst_prefix_P2_to_P8,P2_rank,P3_rank,P4_rank,P5_rank,P6_rank,P7_rank,P8_rank
0,1,L12-13946,True,1,P2,1,1,1,1,1,1,1
1,2,L12-4300,True,2,P2,2,2,2,2,2,2,2
2,3,L12-2992,True,5,P2,5,5,3,4,4,5,4
3,4,L12-9059,True,4,P4,3,3,4,3,3,3,3
4,5,L12-14526,True,7,P6,4,4,5,5,7,4,5
5,6,L12-15109,True,7,P3,6,7,6,7,6,7,7
6,7,L12-10466,True,9,P6,7,6,7,8,9,6,6
7,8,L12-3635,True,10,P2,10,9,9,6,8,9,9
8,9,L12-3607,True,18,P6,8,10,12,11,18,8,8
9,10,L12-1370,True,13,P4,12,12,13,10,10,10,10
10,11,L12-3268,False,24,P6,22,19,17,13,24,12,11
11,12,L12-9706,True,20,P7,9,17,10,18,14,20,13
12,13,L12-5493,True,18,P2,18,13,16,12,13,14,15
13,14,L12-826,False,23,P7,15,14,11,20,15,23,17
14,15,L12-16158,True,15,P4,13,11,15,14,12,11,12
15,16,L12-15497,True,20,P2,20,18,19,15,16,16,14
16,17,L12-2145,True,18,P4,16,15,18,16,17,13,16
17,18,L12-11086,False,24,P5,19,16,21,24,23,22,19
18,19,L12-10245,False,75,P4,40,44,75,43,35,49,28
19,20,L12-2245,False,100,P5,14,27,20,100,11,59,41

====================================================================================================
Technology: P1 top-20 features and their ranks in P2..P8

,P1_baseline_rank,feature,stable_by_rule,worst_rank_P2_to_P8,worst_prefix_P2_to_P8,P2_rank,P3_rank,P4_rank,P5_rank,P6_rank,P7_rank,P8_rank
0,1,L12-2245,True,1,P2,1,1,1,1,1,1,1
1,2,L12-14906,True,3,P8,2,2,2,2,2,2,3
2,3,L12-6810,True,7,P3,3,7,3,3,3,7,2
3,4,L12-2992,True,7,P4,4,4,7,4,6,6,5
4,5,L12-12609,True,7,P8,5,3,4,5,4,3,7
5,6,L12-14559,True,7,P6,6,5,5,6,7,5,4
6,7,L12-6049,True,7,P2,7,6,6,7,5,4,6
7,8,L12-9257,True,9,P7,8,8,8,8,8,9,8
8,9,L12-826,True,11,P4,9,9,11,10,9,8,11
9,10,L12-9706,True,15,P8,10,11,10,12,10,10,15
10,11,L12-2863,True,11,P2,11,10,9,9,11,11,9
11,12,L12-10852,True,19,P3,12,19,12,11,13,15,10
12,13,L12-8841,True,16,P7,13,12,15,15,12,16,12
13,14,L12-14588,True,14,P2,14,13,13,14,14,12,13
14,15,L12-10410,True,17,P4,16,14,17,16,16,13,14
15,16,L12-11970,True,18,P6,15,15,16,17,18,14,16
16,17,L12-11807,False,60,P7,17,16,26,35,38,60,25
17,18,L12-1443,False,32,P2,32,23,32,19,24,19,19
18,19,L12-9059,False,3342,P6,150,68,191,105,3342,3307,355
19,20,L12-4626,False,294,P4,104,58,294,86,156,47,217

====================================================================================================
Largest rank-collapse examples among the P1 top-20 label-specific features
====================================================================================================

,label_word,P1_baseline_rank,feature,stable_by_rule,worst_prefix_P2_to_P8,worst_rank_P2_to_P8,rank_collapse,P1_rank,P2_rank,P3_rank,P4_rank,P5_rank,P6_rank,P7_rank,P8_rank
0,Sports,16,L12-6810,False,P8,7984,7968,16,21,7,12,11,7,6,7984
1,Technology,19,L12-9059,False,P6,3342,3323,19,150,68,191,105,3342,3307,355
2,Technology,20,L12-4626,False,P4,294,274,20,104,58,294,86,156,47,217
3,Business,20,L12-2245,False,P5,100,80,20,14,27,20,100,11,59,41
4,Business,19,L12-10245,False,P4,75,56,19,40,44,75,43,35,49,28
5,Technology,17,L12-11807,False,P7,60,43,17,17,16,26,35,38,60,25
6,World,14,L12-3607,False,P4,51,37,14,21,47,51,16,16,20,27
7,World,12,L12-8745,False,P6,33,21,12,19,15,18,25,33,32,21
8,Sports,17,L12-6457,False,P5,32,15,17,16,22,23,32,29,21,23
9,Technology,18,L12-1443,False,P2,32,14,18,32,23,32,19,24,19,19
10,Business,11,L12-3268,False,P6,24,13,11,22,19,17,13,24,12,11
11,World,9,L12-12633,False,P6,21,12,9,13,8,12,14,21,14,16
12,Sports,19,L12-12388,False,P7,31,12,19,23,24,25,25,16,31,17
13,Business,9,L12-3607,True,P6,18,9,9,8,10,12,11,18,8,8
14,World,17,L12-5266,False,P3,26,9,17,24,26,19,20,17,22,14
15,Sports,14,L12-6518,False,P6,23,9,14,15,18,17,20,23,18,11
16,Business,14,L12-826,False,P7,23,9,14,15,14,11,20,15,23,17
17,Business,12,L12-9706,True,P7,20,8,12,9,17,10,18,14,20,13
18,Technology,12,L12-10852,True,P3,19,7,12,12,19,12,11,13,15,10
19,Sports,18,L12-1303,False,P3,25,7,18,19,25,20,22,21,20,21

In [ ]:

# ============================================================
# 6. Plotly diagnostics and heatmaps
# ============================================================

summary = {
    "model": MODEL_SHORT_NAME,
    "target_layer": TARGET_LAYER,
    "n_queries": N_QUERY_TOTAL,
    "n_prefix_variants": N_PREFIX_VARIANTS,
    "label_specific_top_n_per_label": LABEL_SPECIFIC_TOP_N,
    "retention_top_k": RETENTION_TOP_K,
    "stable_min_retention": STABLE_MIN_RETENTION,
    "stable_min_baseline_ratio": STABLE_MIN_BASELINE_RATIO,
    "query_analysis_positions": query_analysis_positions,
    "stable_count": int(label_specific_stability_df["stable_by_rule"].sum()),
    "sensitive_count": int((~label_specific_stability_df["stable_by_rule"]).sum()),
}
print(json.dumps(summary, indent=2))

# Per-variant final-demo label distribution. This checks whether variant index itself is label-confounded.
variant_label_counts = pd.crosstab(meta_df["variant_idx"], meta_df["final_demo_label_word"])
print("Final-demo label counts by variant index:")
display(variant_label_counts)

fig_counts = px.imshow(
    variant_label_counts,
    text_auto=True,
    aspect="auto",
    title="Final-demo label counts by prefix-variant index",
    labels=dict(x="Final-demo label", y="Variant index", color="count"),
)
fig_counts.show()


def plot_label_specific_heatmap(lab: int, normalize_to_baseline: bool = False):
    """Plot top label-specific features for one label across final-demo variants."""
    feature_ids = label_top_features[int(lab)]
    mat = label_specific_pre_gap[int(lab), :, feature_ids].T  # [features, variants]
    if normalize_to_baseline:
        denom = np.abs(mat[:, [0]]) + 1e-12
        mat_to_plot = mat / denom
        colorbar_title = "pre-gap / |baseline gap|"
        title_suffix = "ratio to baseline"
    else:
        mat_to_plot = mat
        colorbar_title = "label-specific preactivation gap"
        title_suffix = "raw gap"

    y_labels = [f"L{TARGET_LAYER}-{int(f)}" for f in feature_ids]
    x_labels = [f"v{v}" for v in range(N_PREFIX_VARIANTS)]
    fig = go.Figure(
        data=go.Heatmap(
            z=mat_to_plot,
            x=x_labels,
            y=y_labels,
            colorscale="RdBu",
            reversescale=True,
            zmid=0.0,
            colorbar=dict(title=colorbar_title),
            hovertemplate=(
                "feature=%{y}<br>variant=%{x}<br>"
                + colorbar_title
                + "=%{z:.4f}<extra></extra>"
            ),
        )
    )
    fig.update_layout(
        title=f"{label_to_words_agnews[int(lab)]}: top-{LABEL_SPECIFIC_TOP_N} label-specific features across final-demo variants ({title_suffix})",
        xaxis_title="Final-demo prefix variant",
        yaxis_title="SAE feature",
        height=max(450, 26 * len(feature_ids) + 180),
        width=max(850, 80 * N_PREFIX_VARIANTS + 350),
    )
    fig.show()


for lab in range(NUM_LABELS):
    plot_label_specific_heatmap(lab, normalize_to_baseline=False)

# Optional normalized heatmaps. These are useful for visually identifying LFH-sensitive features.
for lab in range(NUM_LABELS):
    plot_label_specific_heatmap(lab, normalize_to_baseline=True)

# Retention plot for all selected label-specific features.
fig_retention = px.scatter(
    label_specific_stability_df,
    x="label_specific_rank",
    y=f"retention_rate_top_{RETENTION_TOP_K}",
    color="label_word",
    symbol="stable_by_rule",
    hover_data=[
        "feature_idx",
        "baseline_label_specific_pre_gap",
        "min_over_baseline",
        "worst_variant_rank",
        "best_variant_rank",
    ],
    title=f"Single-prefix label-specific rank versus multi-prefix retention in top-{RETENTION_TOP_K}",
    labels={
        "label_specific_rank": "Original single-prefix label-specific rank",
        f"retention_rate_top_{RETENTION_TOP_K}": f"Retention rate in top-{RETENTION_TOP_K}",
        "label_word": "Gold label",
    },
)
fig_retention.add_hline(y=STABLE_MIN_RETENTION, line_dash="dash")
fig_retention.update_layout(height=500, width=900)
fig_retention.show()

# Gap range plot: how much the label-specific score moves when only the final demo changes.
fig_range = px.scatter(
    label_specific_stability_df,
    x="baseline_label_specific_pre_gap",
    y="range_label_specific_pre_gap_across_prefixes",
    color="label_word",
    symbol="stable_by_rule",
    hover_data=["feature_idx", "label_specific_rank", "min_over_baseline", f"retention_rate_top_{RETENTION_TOP_K}"],
    title="Label-specific preactivation gap instability under final-demo variation",
    labels={
        "baseline_label_specific_pre_gap": "Baseline label-specific preactivation gap",
        "range_label_specific_pre_gap_across_prefixes": "Range of gap across prefix variants",
        "label_word": "Gold label",
    },
)
fig_range.update_layout(height=500, width=900)
fig_range.show()


# 8. Causal validation: are multi-prefix-stable label features more causally relevant?

This section tests the hypothesis behind the LFH-aware stability filter:

- **Stable group:** label-specific features that remain label-specific across final-demo variants.
- **LFH-sensitive group:** label-specific features that looked strong under the original single-prefix prompt but failed the multi-prefix stability rule.

For every selected `(label, feature)` pair, we evaluate prompts whose gold query label is that label and intervene at the same query-token positions used for feature measurement.

Two interventions are run:

1. **Active-feature ablation:** when the feature is active at an edited token, subtract its current SAE reconstruction contribution:
   `hidden <- hidden - activation_f * W_dec[f]`.
2. **Feature amplification:** add the feature decoder direction with the current value of `CAUSAL_AMPLIFICATION_ALPHA`:
   `hidden <- hidden + CAUSAL_AMPLIFICATION_ALPHA * W_dec[f]`.

The outcome is the model's next-token probability for the gold label, normalized over the four AGNews label tokens. The main quantities are:

- `ablation_decrease_p_label = baseline P(L) - ablated P(L)`; larger is stronger causal support for the label.
- `amplification_increase_p_label = amplified P(L) - baseline P(L)`; larger is stronger causal support for the label.

In [9]:

# ============================================================
# 8. Causal validation of stable versus LFH-sensitive features
# ============================================================

# Causal validation settings.
# By default this evaluates all 80 selected label-feature pairs: top-20 per AGNews label.
CAUSAL_MAX_PAIRS = None          # None = all selected pairs; set e.g. 8 for a quick smoke test
CAUSAL_BATCH_SIZE = BATCH_SIZE   # reduce if you hit memory limits
CAUSAL_AMPLIFICATION_ALPHA = 50.0  # coarse preliminary setting from the attached candidate notebook
CAUSAL_BOOTSTRAP_SAMPLES = 2000

# The causal outcome is P(label) normalized over the four label words. This is usually the
# most interpretable probability for a classification prompt.
CAUSAL_PROBABILITY_MODE = "label_conditional"  # fixed in this cell

print("CAUSAL_MAX_PAIRS:", CAUSAL_MAX_PAIRS)
print("CAUSAL_BATCH_SIZE:", CAUSAL_BATCH_SIZE)
print("CAUSAL_AMPLIFICATION_ALPHA:", CAUSAL_AMPLIFICATION_ALPHA)
print("CAUSAL_PROBABILITY_MODE:", CAUSAL_PROBABILITY_MODE)


def get_single_token_label_ids():
    """Return one tokenizer id per AGNews label word, with sanity checks."""
    label_ids = []
    rows = []
    for lab in range(NUM_LABELS):
        word = label_to_words_agnews[lab]
        ids = tokenizer(word, add_special_tokens=False)["input_ids"]
        rows.append({"label": lab, "label_word": word, "token_ids": ids, "n_tokens": len(ids)})
        if len(ids) != 1:
            raise ValueError(
                f"Label word {word!r} tokenized into {len(ids)} tokens: {ids}. "
                "This causal cell expects single-token labels."
            )
        label_ids.append(int(ids[0]))
    display(pd.DataFrame(rows))
    return label_ids


LABEL_TOKEN_IDS = get_single_token_label_ids()
LABEL_TOKEN_IDS_TENSOR = torch.tensor(LABEL_TOKEN_IDS, dtype=torch.long, device=get_model_input_device(model))


def label_conditional_probs_from_logits(logits: torch.Tensor) -> torch.Tensor:
    """
    Return P(label) normalized over the four AGNews label tokens.

    logits: [B, S, vocab]. We use logits at the final prompt token to score the next token.
    Returns: [B, NUM_LABELS].
    """
    label_token_ids = LABEL_TOKEN_IDS_TENSOR.to(logits.device)
    next_logits = logits[:, -1, :].float()
    label_logits = next_logits[:, label_token_ids]
    return torch.softmax(label_logits, dim=-1)


@torch.no_grad()
def collect_baseline_label_probs(prompts, batch_size: int = CAUSAL_BATCH_SIZE):
    """Collect baseline next-token P(label), normalized across the four label tokens, for every prompt."""
    model_device = get_model_input_device(model)
    probs = np.zeros((len(prompts), NUM_LABELS), dtype=np.float32)
    model.eval()

    for start in range(0, len(prompts), batch_size):
        end = min(start + batch_size, len(prompts))
        enc = tokenizer(
            prompts[start:end],
            padding=True,
            return_tensors="pt",
            add_special_tokens=False,
        )
        input_ids = enc["input_ids"].to(model_device)
        attention_mask = enc["attention_mask"].to(model_device)

        out = model(input_ids=input_ids, attention_mask=attention_mask, use_cache=False)
        label_probs = label_conditional_probs_from_logits(out.logits)
        probs[start:end] = label_probs.detach().cpu().numpy()

        del out, input_ids, attention_mask, enc, label_probs
        print(f"Baseline probabilities: {end}/{len(prompts)}")

    return probs


baseline_label_probs_by_prompt = collect_baseline_label_probs(prompts)
print("baseline_label_probs_by_prompt:", baseline_label_probs_by_prompt.shape)


# Build the label-feature pairs to test. Each row corresponds to the same pair used in the
# stability table, so duplicated feature ids across labels are intentionally retained.
causal_pairs_df = label_specific_stability_df.copy().reset_index(drop=False).rename(columns={"index": "pair_id"})
if CAUSAL_MAX_PAIRS is not None:
    # Balanced quick mode: take from stable and sensitive groups separately when possible.
    stable_part = causal_pairs_df[causal_pairs_df["stable_by_rule"]].head(int(CAUSAL_MAX_PAIRS) // 2)
    sensitive_part = causal_pairs_df[~causal_pairs_df["stable_by_rule"]].head(int(CAUSAL_MAX_PAIRS) - len(stable_part))
    causal_pairs_df = pd.concat([stable_part, sensitive_part], ignore_index=True)

causal_pairs_df["causal_group"] = np.where(causal_pairs_df["stable_by_rule"], "multi-prefix stable", "LFH-sensitive")
print("Causal pairs to test:", len(causal_pairs_df))
display(causal_pairs_df[[
    "pair_id", "label_word", "feature_idx", "label_specific_rank", "stable_by_rule",
    "baseline_label_specific_pre_gap", f"retention_rate_top_{RETENTION_TOP_K}", "min_over_baseline", "worst_variant_rank"
]])


# Construct one intervention instance per (label-feature pair, prompt whose query label matches that label).
instance_rows = []
for _, pair in causal_pairs_df.iterrows():
    lab = int(pair["label"])
    feat = int(pair["feature_idx"])
    pair_id = int(pair["pair_id"])
    prompt_indices_for_label = meta_df.index[meta_df["query_label"].to_numpy(dtype=np.int64) == lab].to_numpy(dtype=np.int64)
    for prompt_idx in prompt_indices_for_label:
        meta = prompt_metadata[int(prompt_idx)]
        instance_rows.append({
            "pair_id": pair_id,
            "prompt_idx": int(prompt_idx),
            "query_local_idx": int(meta["query_local_idx"]),
            "variant_idx": int(meta["variant_idx"]),
            "label": lab,
            "label_word": label_to_words_agnews[lab],
            "feature_idx": feat,
        })

causal_instances_df = pd.DataFrame(instance_rows)
print("Causal intervention instances:", len(causal_instances_df))
display(causal_instances_df.head())


def _selected_padded_positions_for_batch(batch_meta, attention_mask, batch_seq_len: int):
    """Convert saved unpadded selected query positions into padded batch positions."""
    selected_positions_by_row = []
    for b, meta in enumerate(batch_meta):
        unpadded_len = int(attention_mask[b].sum().item())
        pad_shift = int(batch_seq_len - unpadded_len)
        positions = [pad_shift + int(pos) for pos in meta["selected_query_token_positions"]]
        positions = [pos for pos in positions if 0 <= pos < batch_seq_len]
        if not positions:
            raise RuntimeError("No valid selected token positions after padding adjustment.")
        selected_positions_by_row.append(positions)
    return selected_positions_by_row


@torch.no_grad()
def collect_intervened_gold_label_probs(instances_df: pd.DataFrame, mode: str, batch_size: int = CAUSAL_BATCH_SIZE):
    """
    Run feature-level interventions for prompt-feature instances.

    mode:
      - 'ablate_active': subtract current post-activation_f * W_dec[f] on selected query tokens.
      - 'amplify': add CAUSAL_AMPLIFICATION_ALPHA * W_dec[f] on selected query tokens.

    Returns: [n_instances] containing P(gold label) after intervention.
    """
    if mode not in {"ablate_active", "amplify"}:
        raise ValueError(f"Unknown intervention mode: {mode}")

    n = len(instances_df)
    gold_probs = np.zeros(n, dtype=np.float32)
    model_device = get_model_input_device(model)
    block = model.get_submodule(f"model.layers.{TARGET_LAYER}")
    model.eval()
    sae.eval()

    for start in range(0, n, batch_size):
        end = min(start + batch_size, n)
        batch_rows = instances_df.iloc[start:end]
        batch_prompt_indices = batch_rows["prompt_idx"].to_numpy(dtype=np.int64)
        batch_prompts = [prompts[int(i)] for i in batch_prompt_indices]
        batch_meta = [prompt_metadata[int(i)] for i in batch_prompt_indices]
        batch_features = batch_rows["feature_idx"].to_numpy(dtype=np.int64)
        batch_labels = batch_rows["label"].to_numpy(dtype=np.int64)

        enc = tokenizer(
            batch_prompts,
            padding=True,
            return_tensors="pt",
            add_special_tokens=False,
        )
        input_ids = enc["input_ids"].to(model_device)
        attention_mask = enc["attention_mask"].to(model_device)
        batch_seq_len = int(input_ids.shape[1])
        selected_positions_by_row = _selected_padded_positions_for_batch(batch_meta, attention_mask, batch_seq_len)

        def hook_fn(module, inputs, output):
            hidden = output[0] if isinstance(output, tuple) else output
            hidden_mod = hidden.clone()
            hidden_device = hidden_mod.device
            hidden_dtype = hidden_mod.dtype

            for b, feat in enumerate(batch_features):
                feat = int(feat)
                pos = selected_positions_by_row[b]
                x = hidden[b, pos, :]
                decoder_dir = sae.W_dec[feat].to(device=hidden_device, dtype=hidden_dtype)

                if mode == "ablate_active":
                    # Compute the current SAE post-activation and remove only the active contribution.
                    pre = sae_encode_pre_for_positions(hidden[b], pos)
                    post = sae.activation_fn(pre.to(dtype=sae.dtype)).float()
                    coeff = post[:, feat].to(device=hidden_device, dtype=hidden_dtype)
                    hidden_mod[b, pos, :] = hidden_mod[b, pos, :] - coeff[:, None] * decoder_dir[None, :]
                elif mode == "amplify":
                    hidden_mod[b, pos, :] = hidden_mod[b, pos, :] + float(CAUSAL_AMPLIFICATION_ALPHA) * decoder_dir[None, :]

            if isinstance(output, tuple):
                return (hidden_mod,) + output[1:]
            return hidden_mod

        handle = block.register_forward_hook(hook_fn)
        try:
            out = model(input_ids=input_ids, attention_mask=attention_mask, use_cache=False)
        finally:
            handle.remove()

        label_probs = label_conditional_probs_from_logits(out.logits).detach().cpu().numpy()
        gold_probs[start:end] = label_probs[np.arange(end - start), batch_labels]

        del out, input_ids, attention_mask, enc, label_probs
        print(f"{mode}: {end}/{n}")

    return gold_probs


# Baseline summaries per pair using the same prompt subset as each intervention.
baseline_rows = []
for _, pair in causal_pairs_df.iterrows():
    pair_id = int(pair["pair_id"])
    lab = int(pair["label"])
    feat = int(pair["feature_idx"])
    prompt_indices = causal_instances_df.loc[causal_instances_df["pair_id"] == pair_id, "prompt_idx"].to_numpy(dtype=np.int64)

    baseline_gold = baseline_label_probs_by_prompt[prompt_indices, lab]
    feature_freq = freq_by_prompt[prompt_indices, feat]
    feature_post = post_by_prompt[prompt_indices, feat]
    feature_pre = pre_by_prompt[prompt_indices, feat]

    baseline_rows.append({
        "pair_id": pair_id,
        "baseline_mean_p_label": float(np.mean(baseline_gold)),
        "baseline_median_p_label": float(np.median(baseline_gold)),
        "n_prompts_for_label": int(len(prompt_indices)),
        "feature_active_prompt_fraction": float(np.mean(feature_freq > 0)),
        "mean_feature_preactivation_on_gold_label_prompts": float(np.mean(feature_pre)),
        "mean_feature_postactivation_on_gold_label_prompts": float(np.mean(feature_post)),
    })

baseline_pair_df = pd.DataFrame(baseline_rows)

# Run the two causal interventions.
ablation_gold_probs = collect_intervened_gold_label_probs(causal_instances_df, mode="ablate_active")
amplified_gold_probs = collect_intervened_gold_label_probs(causal_instances_df, mode="amplify")

causal_instances_df = causal_instances_df.copy()
causal_instances_df["baseline_p_label"] = baseline_label_probs_by_prompt[
    causal_instances_df["prompt_idx"].to_numpy(dtype=np.int64),
    causal_instances_df["label"].to_numpy(dtype=np.int64),
]
causal_instances_df["ablated_p_label"] = ablation_gold_probs
causal_instances_df["amplified_p_label"] = amplified_gold_probs
causal_instances_df["ablation_decrease_p_label"] = causal_instances_df["baseline_p_label"] - causal_instances_df["ablated_p_label"]
causal_instances_df["amplification_increase_p_label"] = causal_instances_df["amplified_p_label"] - causal_instances_df["baseline_p_label"]

# Aggregate intervention effects per label-feature pair.
causal_pair_effects_df = (
    causal_instances_df
    .groupby("pair_id")
    .agg(
        ablated_mean_p_label=("ablated_p_label", "mean"),
        amplified_mean_p_label=("amplified_p_label", "mean"),
        mean_ablation_decrease_p_label=("ablation_decrease_p_label", "mean"),
        median_ablation_decrease_p_label=("ablation_decrease_p_label", "median"),
        mean_amplification_increase_p_label=("amplification_increase_p_label", "mean"),
        median_amplification_increase_p_label=("amplification_increase_p_label", "median"),
        frac_prompts_ablation_decreases_p_label=("ablation_decrease_p_label", lambda x: float(np.mean(np.asarray(x) > 0))),
        frac_prompts_amplification_increases_p_label=("amplification_increase_p_label", lambda x: float(np.mean(np.asarray(x) > 0))),
    )
    .reset_index()
)

causal_validation_df = (
    causal_pairs_df
    .merge(baseline_pair_df, on="pair_id", how="left")
    .merge(causal_pair_effects_df, on="pair_id", how="left")
)

# Convenience columns for reading.
causal_validation_df["ablation_decrease_pp"] = 100.0 * causal_validation_df["mean_ablation_decrease_p_label"]
causal_validation_df["amplification_increase_pp"] = 100.0 * causal_validation_df["mean_amplification_increase_p_label"]
causal_validation_df["baseline_p_label_pct"] = 100.0 * causal_validation_df["baseline_mean_p_label"]
causal_validation_df["ablated_p_label_pct"] = 100.0 * causal_validation_df["ablated_mean_p_label"]
causal_validation_df["amplified_p_label_pct"] = 100.0 * causal_validation_df["amplified_mean_p_label"]

print("Causal validation per label-feature pair:")
display(causal_validation_df[[
    "label_word", "feature_idx", "label_specific_rank", "stable_by_rule", "causal_group",
    "baseline_label_specific_pre_gap", f"retention_rate_top_{RETENTION_TOP_K}", "min_over_baseline",
    "feature_active_prompt_fraction", "baseline_p_label_pct", "ablated_p_label_pct", "amplified_p_label_pct",
    "ablation_decrease_pp", "amplification_increase_pp",
    "frac_prompts_ablation_decreases_p_label", "frac_prompts_amplification_increases_p_label",
]].sort_values(["stable_by_rule", "label_word", "label_specific_rank"], ascending=[False, True, True]))


def bootstrap_mean_ci(values, n_boot: int = CAUSAL_BOOTSTRAP_SAMPLES, seed: int = seed, ci: float = 0.95):
    vals = np.asarray(values, dtype=np.float64)
    vals = vals[np.isfinite(vals)]
    if vals.size == 0:
        return np.nan, np.nan, np.nan
    mean = float(vals.mean())
    if vals.size == 1 or n_boot <= 0:
        return mean, np.nan, np.nan
    rng_boot = np.random.default_rng(seed)
    draws = rng_boot.choice(vals, size=(int(n_boot), vals.size), replace=True).mean(axis=1)
    lo = float(np.quantile(draws, (1.0 - ci) / 2.0))
    hi = float(np.quantile(draws, 1.0 - (1.0 - ci) / 2.0))
    return mean, lo, hi


group_rows = []
for stable_value, group_name in [(True, "multi-prefix stable"), (False, "LFH-sensitive")]:
    g = causal_validation_df[causal_validation_df["stable_by_rule"] == stable_value]
    row = {
        "causal_group": group_name,
        "n_label_feature_pairs": int(len(g)),
        "mean_active_prompt_fraction": float(g["feature_active_prompt_fraction"].mean()) if len(g) else np.nan,
        "median_active_prompt_fraction": float(g["feature_active_prompt_fraction"].median()) if len(g) else np.nan,
    }
    for metric, label in [
        ("mean_ablation_decrease_p_label", "ablation_decrease"),
        ("mean_amplification_increase_p_label", "amplification_increase"),
    ]:
        mean, lo, hi = bootstrap_mean_ci(g[metric].to_numpy(), seed=seed + (1 if stable_value else 2))
        row[f"mean_{label}"] = mean
        row[f"mean_{label}_ci_low"] = lo
        row[f"mean_{label}_ci_high"] = hi
        row[f"mean_{label}_pp"] = 100.0 * mean if np.isfinite(mean) else np.nan
        row[f"mean_{label}_ci_low_pp"] = 100.0 * lo if np.isfinite(lo) else np.nan
        row[f"mean_{label}_ci_high_pp"] = 100.0 * hi if np.isfinite(hi) else np.nan
    group_rows.append(row)

causal_group_summary_df = pd.DataFrame(group_rows)
print("Stable versus LFH-sensitive causal summary:")
display(causal_group_summary_df)

# Label-level group summary, useful for finding whether one label dominates the comparison.
label_group_summary_df = (
    causal_validation_df
    .groupby(["label_word", "causal_group"])
    .agg(
        n_label_feature_pairs=("feature_idx", "count"),
        mean_ablation_decrease_pp=("ablation_decrease_pp", "mean"),
        mean_amplification_increase_pp=("amplification_increase_pp", "mean"),
        mean_active_prompt_fraction=("feature_active_prompt_fraction", "mean"),
    )
    .reset_index()
)
print("Per-label stable/sensitive causal summary:")
display(label_group_summary_df)

# Plotly comparison: ablation and amplification effects by stability group.
plot_df = causal_validation_df.copy()
plot_df["stability_group"] = np.where(plot_df["stable_by_rule"], "multi-prefix stable", "LFH-sensitive")

fig_ablation = px.box(
    plot_df,
    x="stability_group",
    y="ablation_decrease_pp",
    color="label_word",
    points="all",
    hover_data=["feature_idx", "label_specific_rank", "feature_active_prompt_fraction", f"retention_rate_top_{RETENTION_TOP_K}", "min_over_baseline"],
    title="Feature ablation: decrease in gold-label probability by multi-prefix stability group",
    labels={
        "stability_group": "Feature group",
        "ablation_decrease_pp": "Baseline P(L) - ablated P(L), percentage points",
        "label_word": "Gold label",
    },
)
fig_ablation.add_hline(y=0.0, line_dash="dash")
fig_ablation.update_layout(height=550, width=950)
fig_ablation.show()

fig_amplification = px.box(
    plot_df,
    x="stability_group",
    y="amplification_increase_pp",
    color="label_word",
    points="all",
    hover_data=["feature_idx", "label_specific_rank", "feature_active_prompt_fraction", f"retention_rate_top_{RETENTION_TOP_K}", "min_over_baseline"],
    title=f"Feature amplification (alpha={CAUSAL_AMPLIFICATION_ALPHA:g}): increase in gold-label probability by stability group",
    labels={
        "stability_group": "Feature group",
        "amplification_increase_pp": "Amplified P(L) - baseline P(L), percentage points",
        "label_word": "Gold label",
    },
)
fig_amplification.add_hline(y=0.0, line_dash="dash")
fig_amplification.update_layout(height=550, width=950)
fig_amplification.show()

# Scatter: stability score versus causal effect. Ideally, more stable features have stronger causal effects.
fig_scatter = px.scatter(
    plot_df,
    x=f"retention_rate_top_{RETENTION_TOP_K}",
    y="ablation_decrease_pp",
    color="label_word",
    symbol="stable_by_rule",
    size="feature_active_prompt_fraction",
    hover_data=["feature_idx", "label_specific_rank", "amplification_increase_pp", "min_over_baseline", "worst_variant_rank"],
    title="Does multi-prefix retention predict feature-ablation causal relevance?",
    labels={
        f"retention_rate_top_{RETENTION_TOP_K}": f"Retention rate in top-{RETENTION_TOP_K}",
        "ablation_decrease_pp": "Ablation decrease in P(L), percentage points",
        "label_word": "Gold label",
    },
)
fig_scatter.add_hline(y=0.0, line_dash="dash")
fig_scatter.add_vline(x=STABLE_MIN_RETENTION, line_dash="dash")
fig_scatter.update_layout(height=550, width=950)
fig_scatter.show()

# Compact interpretation helper.
stable_mean_ablate = causal_group_summary_df.loc[causal_group_summary_df["causal_group"] == "multi-prefix stable", "mean_ablation_decrease_pp"].iloc[0]
sens_mean_ablate = causal_group_summary_df.loc[causal_group_summary_df["causal_group"] == "LFH-sensitive", "mean_ablation_decrease_pp"].iloc[0]
stable_mean_amp = causal_group_summary_df.loc[causal_group_summary_df["causal_group"] == "multi-prefix stable", "mean_amplification_increase_pp"].iloc[0]
sens_mean_amp = causal_group_summary_df.loc[causal_group_summary_df["causal_group"] == "LFH-sensitive", "mean_amplification_increase_pp"].iloc[0]

print("=" * 100)
print("Quick readout")
print("=" * 100)
print(f"Mean ablation decrease, stable group:      {stable_mean_ablate:.4f} percentage points")
print(f"Mean ablation decrease, LFH-sensitive:     {sens_mean_ablate:.4f} percentage points")
print(f"Mean amplification increase, stable group: {stable_mean_amp:.4f} percentage points")
print(f"Mean amplification increase, sensitive:    {sens_mean_amp:.4f} percentage points")
print()
if stable_mean_ablate > sens_mean_ablate and stable_mean_amp > sens_mean_amp:
    print("Pattern matches the ideal validation: multi-prefix-stable features are more causally relevant on both tests.")
elif stable_mean_ablate > sens_mean_ablate or stable_mean_amp > sens_mean_amp:
    print("Pattern is partially supportive: stable features are stronger on one causal test but not both.")
else:
    print("Pattern is not supportive under this run/settings; inspect label-wise summaries and active fractions.")

CAUSAL_MAX_PAIRS: None
CAUSAL_BATCH_SIZE: 4
CAUSAL_AMPLIFICATION_ALPHA: 50.0
CAUSAL_PROBABILITY_MODE: label_conditional

   label  label_word token_ids  n_tokens
0      0       World   [10772]         1
1      1      Sports   [27093]         1
2      2    Business   [14103]         1
3      3  Technology   [39364]         1

Baseline probabilities: 4/800
Baseline probabilities: 8/800
Baseline probabilities: 12/800
Baseline probabilities: 16/800
Baseline probabilities: 20/800
Baseline probabilities: 24/800
Baseline probabilities: 28/800
Baseline probabilities: 32/800
Baseline probabilities: 36/800
Baseline probabilities: 40/800
Baseline probabilities: 44/800
Baseline probabilities: 48/800
Baseline probabilities: 52/800
Baseline probabilities: 56/800
Baseline probabilities: 60/800
Baseline probabilities: 64/800
Baseline probabilities: 68/800
Baseline probabilities: 72/800
Baseline probabilities: 76/800
Baseline probabilities: 80/800
Baseline probabilities: 84/800
Baseline probabilities: 88/800
Baseline probabilities: 92/800
Baseline probabilities: 96/800
Baseline probabilities: 100/800
Baseline probabilities: 104/800
Baseline probabilities: 108/800
Baseline probabilities: 112/800
Baseline probabilities: 116/800
Baseline probabilities: 120/800
Baseline probabilities: 124/800
Baseline probabilities: 128/800
Baseline probabilities: 132/800
Baseline probabilities: 136/800
Baseline probabilities: 140/800
Baseline probabilities: 144/800
Baseline probabilities: 148/800
Baseline probabilities: 152/800
Baseline probabilities: 156/800
Baseline probabilities: 160/800
Baseline probabilities: 164/800
Baseline probabilities: 168/800
Baseline probabilities: 172/800
Baseline probabilities: 176/800
Baseline probabilities: 180/800
Baseline probabilities: 184/800
Baseline probabilities: 188/800
Baseline probabilities: 192/800
Baseline probabilities: 196/800
Baseline probabilities: 200/800
Baseline probabilities: 204/800
Baseline probabilities: 208/800
Baseline probabilities: 212/800
Baseline probabilities: 216/800
Baseline probabilities: 220/800
Baseline probabilities: 224/800
Baseline probabilities: 228/800
Baseline probabilities: 232/800
Baseline probabilities: 236/800
Baseline probabilities: 240/800
Baseline probabilities: 244/800
Baseline probabilities: 248/800
Baseline probabilities: 252/800
Baseline probabilities: 256/800
Baseline probabilities: 260/800
Baseline probabilities: 264/800
Baseline probabilities: 268/800
Baseline probabilities: 272/800
Baseline probabilities: 276/800
Baseline probabilities: 280/800
Baseline probabilities: 284/800
Baseline probabilities: 288/800
Baseline probabilities: 292/800
Baseline probabilities: 296/800
Baseline probabilities: 300/800
Baseline probabilities: 304/800
Baseline probabilities: 308/800
Baseline probabilities: 312/800
Baseline probabilities: 316/800
Baseline probabilities: 320/800
Baseline probabilities: 324/800
Baseline probabilities: 328/800
Baseline probabilities: 332/800
Baseline probabilities: 336/800
Baseline probabilities: 340/800
Baseline probabilities: 344/800
Baseline probabilities: 348/800
Baseline probabilities: 352/800
Baseline probabilities: 356/800
Baseline probabilities: 360/800
Baseline probabilities: 364/800
Baseline probabilities: 368/800
Baseline probabilities: 372/800
Baseline probabilities: 376/800
Baseline probabilities: 380/800
Baseline probabilities: 384/800
Baseline probabilities: 388/800
Baseline probabilities: 392/800
Baseline probabilities: 396/800
Baseline probabilities: 400/800
Baseline probabilities: 404/800
Baseline probabilities: 408/800
Baseline probabilities: 412/800
Baseline probabilities: 416/800
Baseline probabilities: 420/800
Baseline probabilities: 424/800
Baseline probabilities: 428/800
Baseline probabilities: 432/800
Baseline probabilities: 436/800
Baseline probabilities: 440/800
Baseline probabilities: 444/800
Baseline probabilities: 448/800
Baseline probabilities: 452/800
Baseline probabilities: 456/800
Baseline probabilities: 460/800
Baseline probabilities: 464/800
Baseline probabilities: 468/800
Baseline probabilities: 472/800
Baseline probabilities: 476/800
Baseline probabilities: 480/800
Baseline probabilities: 484/800
Baseline probabilities: 488/800
Baseline probabilities: 492/800
Baseline probabilities: 496/800
Baseline probabilities: 500/800
Baseline probabilities: 504/800
Baseline probabilities: 508/800
Baseline probabilities: 512/800
Baseline probabilities: 516/800
Baseline probabilities: 520/800
Baseline probabilities: 524/800
Baseline probabilities: 528/800
Baseline probabilities: 532/800
Baseline probabilities: 536/800
Baseline probabilities: 540/800
Baseline probabilities: 544/800
Baseline probabilities: 548/800
Baseline probabilities: 552/800
Baseline probabilities: 556/800
Baseline probabilities: 560/800
Baseline probabilities: 564/800
Baseline probabilities: 568/800
Baseline probabilities: 572/800
Baseline probabilities: 576/800
Baseline probabilities: 580/800
Baseline probabilities: 584/800
Baseline probabilities: 588/800
Baseline probabilities: 592/800
Baseline probabilities: 596/800
Baseline probabilities: 600/800
Baseline probabilities: 604/800
Baseline probabilities: 608/800
Baseline probabilities: 612/800
Baseline probabilities: 616/800
Baseline probabilities: 620/800
Baseline probabilities: 624/800
Baseline probabilities: 628/800
Baseline probabilities: 632/800
Baseline probabilities: 636/800
Baseline probabilities: 640/800
Baseline probabilities: 644/800
Baseline probabilities: 648/800
Baseline probabilities: 652/800
Baseline probabilities: 656/800
Baseline probabilities: 660/800
Baseline probabilities: 664/800
Baseline probabilities: 668/800
Baseline probabilities: 672/800
Baseline probabilities: 676/800
Baseline probabilities: 680/800
Baseline probabilities: 684/800
Baseline probabilities: 688/800
Baseline probabilities: 692/800
Baseline probabilities: 696/800
Baseline probabilities: 700/800
Baseline probabilities: 704/800
Baseline probabilities: 708/800
Baseline probabilities: 712/800
Baseline probabilities: 716/800
Baseline probabilities: 720/800
Baseline probabilities: 724/800
Baseline probabilities: 728/800
Baseline probabilities: 732/800
Baseline probabilities: 736/800
Baseline probabilities: 740/800
Baseline probabilities: 744/800
Baseline probabilities: 748/800
Baseline probabilities: 752/800
Baseline probabilities: 756/800
Baseline probabilities: 760/800
Baseline probabilities: 764/800
Baseline probabilities: 768/800
Baseline probabilities: 772/800
Baseline probabilities: 776/800
Baseline probabilities: 780/800
Baseline probabilities: 784/800
Baseline probabilities: 788/800
Baseline probabilities: 792/800
Baseline probabilities: 796/800
Baseline probabilities: 800/800
baseline_label_probs_by_prompt: (800, 4)
Causal pairs to test: 80

,pair_id,label_word,feature_idx,label_specific_rank,stable_by_rule,baseline_label_specific_pre_gap,retention_rate_top_20,min_over_baseline,worst_variant_rank
0,0,World,14090,1,True,10.535886,1.000,0.990731,1
1,1,World,1041,2,True,9.400000,1.000,0.564539,4
2,2,World,5185,3,True,6.020338,1.000,0.973722,3
3,3,World,14599,4,True,4.966927,1.000,0.940041,4
4,4,World,9632,5,True,4.889818,1.000,0.772854,9
...,...,...,...,...,...,...,...,...,...
75,75,Technology,11970,16,True,2.566107,1.000,0.842186,18
76,76,Technology,11807,17,False,2.408334,0.375,0.670588,60
77,77,Technology,1443,18,False,2.175729,0.500,0.828673,32
78,78,Technology,9059,19,False,2.104870,0.125,0.192065,3342
79,79,Technology,4626,20,False,2.090404,0.125,0.508549,294

Causal intervention instances: 16000

,pair_id,prompt_idx,query_local_idx,variant_idx,label,label_word,feature_idx
0,0,16,2,0,0,World,14090
1,0,17,2,1,0,World,14090
2,0,18,2,2,0,World,14090
3,0,19,2,3,0,World,14090
4,0,20,2,4,0,World,14090

ablate_active: 4/16000
ablate_active: 8/16000
ablate_active: 12/16000
ablate_active: 16/16000
ablate_active: 20/16000
ablate_active: 24/16000
ablate_active: 28/16000
ablate_active: 32/16000
ablate_active: 36/16000
ablate_active: 40/16000
ablate_active: 44/16000
ablate_active: 48/16000
ablate_active: 52/16000
ablate_active: 56/16000
ablate_active: 60/16000
ablate_active: 64/16000
ablate_active: 68/16000
ablate_active: 72/16000
ablate_active: 76/16000
ablate_active: 80/16000
ablate_active: 84/16000
ablate_active: 88/16000
ablate_active: 92/16000
ablate_active: 96/16000
ablate_active: 100/16000
ablate_active: 104/16000
ablate_active: 108/16000
ablate_active: 112/16000
ablate_active: 116/16000
ablate_active: 120/16000
ablate_active: 124/16000
ablate_active: 128/16000
ablate_active: 132/16000
ablate_active: 136/16000
ablate_active: 140/16000
ablate_active: 144/16000
ablate_active: 148/16000
ablate_active: 152/16000
ablate_active: 156/16000
ablate_active: 160/16000
ablate_active: 164/16000
ablate_active: 168/16000
ablate_active: 172/16000
ablate_active: 176/16000
ablate_active: 180/16000
ablate_active: 184/16000
ablate_active: 188/16000
ablate_active: 192/16000
ablate_active: 196/16000
ablate_active: 200/16000
ablate_active: 204/16000
ablate_active: 208/16000
ablate_active: 212/16000
ablate_active: 216/16000
ablate_active: 220/16000
ablate_active: 224/16000
ablate_active: 228/16000
ablate_active: 232/16000
ablate_active: 236/16000
ablate_active: 240/16000
ablate_active: 244/16000
ablate_active: 248/16000
ablate_active: 252/16000
ablate_active: 256/16000
ablate_active: 260/16000
ablate_active: 264/16000
ablate_active: 268/16000
ablate_active: 272/16000
ablate_active: 276/16000
ablate_active: 280/16000
ablate_active: 284/16000
ablate_active: 288/16000
ablate_active: 292/16000
ablate_active: 296/16000
ablate_active: 300/16000
ablate_active: 304/16000
ablate_active: 308/16000
ablate_active: 312/16000
ablate_active: 316/16000
ablate_active: 320/16000
ablate_active: 324/16000
ablate_active: 328/16000
ablate_active: 332/16000
ablate_active: 336/16000
ablate_active: 340/16000
ablate_active: 344/16000
ablate_active: 348/16000
ablate_active: 352/16000
ablate_active: 356/16000
ablate_active: 360/16000
ablate_active: 364/16000
ablate_active: 368/16000
ablate_active: 372/16000
ablate_active: 376/16000
ablate_active: 380/16000
ablate_active: 384/16000
ablate_active: 388/16000
ablate_active: 392/16000
ablate_active: 396/16000
ablate_active: 400/16000
ablate_active: 404/16000
ablate_active: 408/16000
ablate_active: 412/16000
ablate_active: 416/16000
ablate_active: 420/16000
ablate_active: 424/16000
ablate_active: 428/16000
ablate_active: 432/16000
ablate_active: 436/16000
ablate_active: 440/16000
ablate_active: 444/16000
ablate_active: 448/16000
ablate_active: 452/16000
ablate_active: 456/16000
ablate_active: 460/16000
ablate_active: 464/16000
ablate_active: 468/16000
ablate_active: 472/16000
ablate_active: 476/16000
ablate_active: 480/16000
ablate_active: 484/16000
ablate_active: 488/16000
ablate_active: 492/16000
ablate_active: 496/16000
ablate_active: 500/16000
ablate_active: 504/16000
ablate_active: 508/16000
ablate_active: 512/16000
ablate_active: 516/16000
ablate_active: 520/16000
ablate_active: 524/16000
ablate_active: 528/16000
ablate_active: 532/16000
ablate_active: 536/16000
ablate_active: 540/16000
ablate_active: 544/16000
ablate_active: 548/16000
ablate_active: 552/16000
ablate_active: 556/16000
ablate_active: 560/16000
ablate_active: 564/16000
ablate_active: 568/16000
ablate_active: 572/16000
ablate_active: 576/16000
ablate_active: 580/16000
ablate_active: 584/16000
ablate_active: 588/16000
ablate_active: 592/16000
ablate_active: 596/16000
ablate_active: 600/16000
ablate_active: 604/16000
ablate_active: 608/16000
ablate_active: 612/16000
ablate_active: 616/16000
ablate_active: 620/16000
ablate_active: 624/16000
ablate_active: 628/16000
ablate_active: 632/16000
ablate_active: 636/16000
ablate_active: 640/16000
ablate_active: 644/16000
ablate_active: 648/16000
ablate_active: 652/16000
ablate_active: 656/16000
ablate_active: 660/16000
ablate_active: 664/16000
ablate_active: 668/16000
ablate_active: 672/16000
ablate_active: 676/16000
ablate_active: 680/16000
ablate_active: 684/16000
ablate_active: 688/16000
ablate_active: 692/16000
ablate_active: 696/16000
ablate_active: 700/16000
ablate_active: 704/16000
ablate_active: 708/16000
ablate_active: 712/16000
ablate_active: 716/16000
ablate_active: 720/16000
ablate_active: 724/16000
ablate_active: 728/16000
ablate_active: 732/16000
ablate_active: 736/16000
ablate_active: 740/16000
ablate_active: 744/16000
ablate_active: 748/16000
ablate_active: 752/16000
ablate_active: 756/16000
ablate_active: 760/16000
ablate_active: 764/16000
ablate_active: 768/16000
ablate_active: 772/16000
ablate_active: 776/16000
ablate_active: 780/16000
ablate_active: 784/16000
ablate_active: 788/16000
ablate_active: 792/16000
ablate_active: 796/16000
ablate_active: 800/16000
ablate_active: 804/16000
ablate_active: 808/16000
ablate_active: 812/16000
ablate_active: 816/16000
ablate_active: 820/16000
ablate_active: 824/16000
ablate_active: 828/16000
ablate_active: 832/16000
ablate_active: 836/16000
ablate_active: 840/16000
ablate_active: 844/16000
ablate_active: 848/16000
ablate_active: 852/16000
ablate_active: 856/16000
ablate_active: 860/16000
ablate_active: 864/16000
ablate_active: 868/16000
ablate_active: 872/16000
ablate_active: 876/16000
ablate_active: 880/16000
ablate_active: 884/16000
ablate_active: 888/16000
ablate_active: 892/16000
ablate_active: 896/16000
ablate_active: 900/16000
ablate_active: 904/16000
ablate_active: 908/16000
ablate_active: 912/16000
ablate_active: 916/16000
ablate_active: 920/16000
ablate_active: 924/16000
ablate_active: 928/16000
ablate_active: 932/16000
ablate_active: 936/16000
ablate_active: 940/16000
ablate_active: 944/16000
ablate_active: 948/16000
ablate_active: 952/16000
ablate_active: 956/16000
ablate_active: 960/16000
ablate_active: 964/16000
ablate_active: 968/16000
ablate_active: 972/16000
ablate_active: 976/16000
ablate_active: 980/16000
ablate_active: 984/16000
ablate_active: 988/16000
ablate_active: 992/16000
ablate_active: 996/16000
ablate_active: 1000/16000
ablate_active: 1004/16000
ablate_active: 1008/16000
ablate_active: 1012/16000
ablate_active: 1016/16000
ablate_active: 1020/16000
ablate_active: 1024/16000
ablate_active: 1028/16000
ablate_active: 1032/16000
ablate_active: 1036/16000
ablate_active: 1040/16000
ablate_active: 1044/16000
ablate_active: 1048/16000
ablate_active: 1052/16000
ablate_active: 1056/16000
ablate_active: 1060/16000
ablate_active: 1064/16000
ablate_active: 1068/16000
ablate_active: 1072/16000
ablate_active: 1076/16000
ablate_active: 1080/16000
ablate_active: 1084/16000
ablate_active: 1088/16000
ablate_active: 1092/16000
ablate_active: 1096/16000
ablate_active: 1100/16000
ablate_active: 1104/16000
ablate_active: 1108/16000
ablate_active: 1112/16000
ablate_active: 1116/16000
ablate_active: 1120/16000
ablate_active: 1124/16000
ablate_active: 1128/16000
ablate_active: 1132/16000
ablate_active: 1136/16000
ablate_active: 1140/16000
ablate_active: 1144/16000
ablate_active: 1148/16000
ablate_active: 1152/16000
ablate_active: 1156/16000
ablate_active: 1160/16000
ablate_active: 1164/16000
ablate_active: 1168/16000
ablate_active: 1172/16000
ablate_active: 1176/16000
ablate_active: 1180/16000
ablate_active: 1184/16000
ablate_active: 1188/16000
ablate_active: 1192/16000
ablate_active: 1196/16000
ablate_active: 1200/16000
ablate_active: 1204/16000
ablate_active: 1208/16000
ablate_active: 1212/16000
ablate_active: 1216/16000
ablate_active: 1220/16000
ablate_active: 1224/16000
ablate_active: 1228/16000
ablate_active: 1232/16000
ablate_active: 1236/16000
ablate_active: 1240/16000
ablate_active: 1244/16000
ablate_active: 1248/16000
ablate_active: 1252/16000
ablate_active: 1256/16000
ablate_active: 1260/16000
ablate_active: 1264/16000
ablate_active: 1268/16000
ablate_active: 1272/16000
ablate_active: 1276/16000
ablate_active: 1280/16000
ablate_active: 1284/16000
ablate_active: 1288/16000
ablate_active: 1292/16000
ablate_active: 1296/16000
ablate_active: 1300/16000
ablate_active: 1304/16000

ablate_active: 1308/16000
ablate_active: 1312/16000
ablate_active: 1316/16000
ablate_active: 1320/16000
ablate_active: 1324/16000
ablate_active: 1328/16000
ablate_active: 1332/16000
ablate_active: 1336/16000
ablate_active: 1340/16000
ablate_active: 1344/16000
ablate_active: 1348/16000
ablate_active: 1352/16000
ablate_active: 1356/16000
ablate_active: 1360/16000
ablate_active: 1364/16000
ablate_active: 1368/16000
ablate_active: 1372/16000
ablate_active: 1376/16000
ablate_active: 1380/16000
ablate_active: 1384/16000
ablate_active: 1388/16000
ablate_active: 1392/16000
ablate_active: 1396/16000
ablate_active: 1400/16000
ablate_active: 1404/16000
ablate_active: 1408/16000
ablate_active: 1412/16000
ablate_active: 1416/16000
ablate_active: 1420/16000
ablate_active: 1424/16000
ablate_active: 1428/16000
ablate_active: 1432/16000
ablate_active: 1436/16000
ablate_active: 1440/16000
ablate_active: 1444/16000
ablate_active: 1448/16000
ablate_active: 1452/16000
ablate_active: 1456/16000
ablate_active: 1460/16000
ablate_active: 1464/16000
ablate_active: 1468/16000
ablate_active: 1472/16000
ablate_active: 1476/16000
ablate_active: 1480/16000
ablate_active: 1484/16000
ablate_active: 1488/16000
ablate_active: 1492/16000
ablate_active: 1496/16000
ablate_active: 1500/16000
ablate_active: 1504/16000
ablate_active: 1508/16000
ablate_active: 1512/16000
ablate_active: 1516/16000
ablate_active: 1520/16000
ablate_active: 1524/16000
ablate_active: 1528/16000
ablate_active: 1532/16000
ablate_active: 1536/16000
ablate_active: 1540/16000
ablate_active: 1544/16000
ablate_active: 1548/16000
ablate_active: 1552/16000
ablate_active: 1556/16000
ablate_active: 1560/16000
ablate_active: 1564/16000
ablate_active: 1568/16000
ablate_active: 1572/16000
ablate_active: 1576/16000
ablate_active: 1580/16000
ablate_active: 1584/16000
ablate_active: 1588/16000
ablate_active: 1592/16000
ablate_active: 1596/16000
ablate_active: 1600/16000
ablate_active: 1604/16000
ablate_active: 1608/16000
ablate_active: 1612/16000
ablate_active: 1616/16000
ablate_active: 1620/16000
ablate_active: 1624/16000
ablate_active: 1628/16000
ablate_active: 1632/16000
ablate_active: 1636/16000
ablate_active: 1640/16000
ablate_active: 1644/16000
ablate_active: 1648/16000
ablate_active: 1652/16000
ablate_active: 1656/16000
ablate_active: 1660/16000
ablate_active: 1664/16000
ablate_active: 1668/16000
ablate_active: 1672/16000
ablate_active: 1676/16000
ablate_active: 1680/16000
ablate_active: 1684/16000
ablate_active: 1688/16000
ablate_active: 1692/16000
ablate_active: 1696/16000
ablate_active: 1700/16000
ablate_active: 1704/16000
ablate_active: 1708/16000
ablate_active: 1712/16000
ablate_active: 1716/16000
ablate_active: 1720/16000
ablate_active: 1724/16000
ablate_active: 1728/16000
ablate_active: 1732/16000
ablate_active: 1736/16000
ablate_active: 1740/16000
ablate_active: 1744/16000
ablate_active: 1748/16000
ablate_active: 1752/16000
ablate_active: 1756/16000
ablate_active: 1760/16000
ablate_active: 1764/16000
ablate_active: 1768/16000
ablate_active: 1772/16000
ablate_active: 1776/16000
ablate_active: 1780/16000
ablate_active: 1784/16000
ablate_active: 1788/16000
ablate_active: 1792/16000
ablate_active: 1796/16000
ablate_active: 1800/16000
ablate_active: 1804/16000
ablate_active: 1808/16000
ablate_active: 1812/16000
ablate_active: 1816/16000
ablate_active: 1820/16000
ablate_active: 1824/16000
ablate_active: 1828/16000
ablate_active: 1832/16000
ablate_active: 1836/16000
ablate_active: 1840/16000
ablate_active: 1844/16000
ablate_active: 1848/16000
ablate_active: 1852/16000
ablate_active: 1856/16000
ablate_active: 1860/16000
ablate_active: 1864/16000
ablate_active: 1868/16000
ablate_active: 1872/16000
ablate_active: 1876/16000
ablate_active: 1880/16000
ablate_active: 1884/16000
ablate_active: 1888/16000
ablate_active: 1892/16000
ablate_active: 1896/16000
ablate_active: 1900/16000
ablate_active: 1904/16000
ablate_active: 1908/16000
ablate_active: 1912/16000
ablate_active: 1916/16000
ablate_active: 1920/16000
ablate_active: 1924/16000
ablate_active: 1928/16000
ablate_active: 1932/16000
ablate_active: 1936/16000
ablate_active: 1940/16000
ablate_active: 1944/16000
ablate_active: 1948/16000
ablate_active: 1952/16000
ablate_active: 1956/16000
ablate_active: 1960/16000
ablate_active: 1964/16000
ablate_active: 1968/16000
ablate_active: 1972/16000
ablate_active: 1976/16000
ablate_active: 1980/16000
ablate_active: 1984/16000
ablate_active: 1988/16000
ablate_active: 1992/16000
ablate_active: 1996/16000
ablate_active: 2000/16000
ablate_active: 2004/16000
ablate_active: 2008/16000
ablate_active: 2012/16000
ablate_active: 2016/16000
ablate_active: 2020/16000
ablate_active: 2024/16000
ablate_active: 2028/16000
ablate_active: 2032/16000
ablate_active: 2036/16000
ablate_active: 2040/16000
ablate_active: 2044/16000
ablate_active: 2048/16000
ablate_active: 2052/16000
ablate_active: 2056/16000
ablate_active: 2060/16000
ablate_active: 2064/16000
ablate_active: 2068/16000
ablate_active: 2072/16000
ablate_active: 2076/16000
ablate_active: 2080/16000
ablate_active: 2084/16000
ablate_active: 2088/16000
ablate_active: 2092/16000
ablate_active: 2096/16000
ablate_active: 2100/16000
ablate_active: 2104/16000
ablate_active: 2108/16000
ablate_active: 2112/16000
ablate_active: 2116/16000
ablate_active: 2120/16000
ablate_active: 2124/16000
ablate_active: 2128/16000
ablate_active: 2132/16000
ablate_active: 2136/16000
ablate_active: 2140/16000
ablate_active: 2144/16000
ablate_active: 2148/16000
ablate_active: 2152/16000
ablate_active: 2156/16000
ablate_active: 2160/16000
ablate_active: 2164/16000
ablate_active: 2168/16000
ablate_active: 2172/16000
ablate_active: 2176/16000
ablate_active: 2180/16000
ablate_active: 2184/16000
ablate_active: 2188/16000
ablate_active: 2192/16000
ablate_active: 2196/16000
ablate_active: 2200/16000
ablate_active: 2204/16000
ablate_active: 2208/16000
ablate_active: 2212/16000
ablate_active: 2216/16000
ablate_active: 2220/16000
ablate_active: 2224/16000
ablate_active: 2228/16000
ablate_active: 2232/16000
ablate_active: 2236/16000
ablate_active: 2240/16000
ablate_active: 2244/16000
ablate_active: 2248/16000
ablate_active: 2252/16000
ablate_active: 2256/16000
ablate_active: 2260/16000
ablate_active: 2264/16000
ablate_active: 2268/16000
ablate_active: 2272/16000
ablate_active: 2276/16000
ablate_active: 2280/16000
ablate_active: 2284/16000
ablate_active: 2288/16000
ablate_active: 2292/16000
ablate_active: 2296/16000
ablate_active: 2300/16000
ablate_active: 2304/16000
ablate_active: 2308/16000
ablate_active: 2312/16000
ablate_active: 2316/16000
ablate_active: 2320/16000
ablate_active: 2324/16000
ablate_active: 2328/16000
ablate_active: 2332/16000
ablate_active: 2336/16000
ablate_active: 2340/16000
ablate_active: 2344/16000
ablate_active: 2348/16000
ablate_active: 2352/16000
ablate_active: 2356/16000
ablate_active: 2360/16000
ablate_active: 2364/16000
ablate_active: 2368/16000
ablate_active: 2372/16000
ablate_active: 2376/16000
ablate_active: 2380/16000
ablate_active: 2384/16000
ablate_active: 2388/16000
ablate_active: 2392/16000
ablate_active: 2396/16000
ablate_active: 2400/16000
ablate_active: 2404/16000
ablate_active: 2408/16000
ablate_active: 2412/16000
ablate_active: 2416/16000
ablate_active: 2420/16000
ablate_active: 2424/16000
ablate_active: 2428/16000
ablate_active: 2432/16000
ablate_active: 2436/16000
ablate_active: 2440/16000
ablate_active: 2444/16000
ablate_active: 2448/16000
ablate_active: 2452/16000
ablate_active: 2456/16000
ablate_active: 2460/16000
ablate_active: 2464/16000
ablate_active: 2468/16000
ablate_active: 2472/16000
ablate_active: 2476/16000
ablate_active: 2480/16000
ablate_active: 2484/16000
ablate_active: 2488/16000
ablate_active: 2492/16000
ablate_active: 2496/16000
ablate_active: 2500/16000
ablate_active: 2504/16000
ablate_active: 2508/16000
ablate_active: 2512/16000
ablate_active: 2516/16000
ablate_active: 2520/16000
ablate_active: 2524/16000
ablate_active: 2528/16000
ablate_active: 2532/16000
ablate_active: 2536/16000
ablate_active: 2540/16000
ablate_active: 2544/16000
ablate_active: 2548/16000
ablate_active: 2552/16000
ablate_active: 2556/16000
ablate_active: 2560/16000
ablate_active: 2564/16000
ablate_active: 2568/16000

ablate_active: 2572/16000
ablate_active: 2576/16000
ablate_active: 2580/16000
ablate_active: 2584/16000
ablate_active: 2588/16000
ablate_active: 2592/16000
ablate_active: 2596/16000
ablate_active: 2600/16000
ablate_active: 2604/16000
ablate_active: 2608/16000
ablate_active: 2612/16000
ablate_active: 2616/16000
ablate_active: 2620/16000
ablate_active: 2624/16000
ablate_active: 2628/16000
ablate_active: 2632/16000
ablate_active: 2636/16000
ablate_active: 2640/16000
ablate_active: 2644/16000
ablate_active: 2648/16000
ablate_active: 2652/16000
ablate_active: 2656/16000
ablate_active: 2660/16000
ablate_active: 2664/16000
ablate_active: 2668/16000
ablate_active: 2672/16000
ablate_active: 2676/16000
ablate_active: 2680/16000
ablate_active: 2684/16000
ablate_active: 2688/16000
ablate_active: 2692/16000
ablate_active: 2696/16000
ablate_active: 2700/16000
ablate_active: 2704/16000
ablate_active: 2708/16000
ablate_active: 2712/16000
ablate_active: 2716/16000
ablate_active: 2720/16000
ablate_active: 2724/16000
ablate_active: 2728/16000
ablate_active: 2732/16000
ablate_active: 2736/16000
ablate_active: 2740/16000
ablate_active: 2744/16000
ablate_active: 2748/16000
ablate_active: 2752/16000
ablate_active: 2756/16000
ablate_active: 2760/16000
ablate_active: 2764/16000
ablate_active: 2768/16000
ablate_active: 2772/16000
ablate_active: 2776/16000
ablate_active: 2780/16000
ablate_active: 2784/16000
ablate_active: 2788/16000
ablate_active: 2792/16000
ablate_active: 2796/16000
ablate_active: 2800/16000
ablate_active: 2804/16000
ablate_active: 2808/16000
ablate_active: 2812/16000
ablate_active: 2816/16000
ablate_active: 2820/16000
ablate_active: 2824/16000
ablate_active: 2828/16000
ablate_active: 2832/16000
ablate_active: 2836/16000
ablate_active: 2840/16000
ablate_active: 2844/16000
ablate_active: 2848/16000
ablate_active: 2852/16000
ablate_active: 2856/16000
ablate_active: 2860/16000
ablate_active: 2864/16000
ablate_active: 2868/16000
ablate_active: 2872/16000
ablate_active: 2876/16000
ablate_active: 2880/16000
ablate_active: 2884/16000
ablate_active: 2888/16000
ablate_active: 2892/16000
ablate_active: 2896/16000
ablate_active: 2900/16000
ablate_active: 2904/16000
ablate_active: 2908/16000
ablate_active: 2912/16000
ablate_active: 2916/16000
ablate_active: 2920/16000
ablate_active: 2924/16000
ablate_active: 2928/16000
ablate_active: 2932/16000
ablate_active: 2936/16000
ablate_active: 2940/16000
ablate_active: 2944/16000
ablate_active: 2948/16000
ablate_active: 2952/16000
ablate_active: 2956/16000
ablate_active: 2960/16000
ablate_active: 2964/16000
ablate_active: 2968/16000
ablate_active: 2972/16000
ablate_active: 2976/16000
ablate_active: 2980/16000
ablate_active: 2984/16000
ablate_active: 2988/16000
ablate_active: 2992/16000
ablate_active: 2996/16000
ablate_active: 3000/16000
ablate_active: 3004/16000
ablate_active: 3008/16000
ablate_active: 3012/16000
ablate_active: 3016/16000
ablate_active: 3020/16000
ablate_active: 3024/16000
ablate_active: 3028/16000
ablate_active: 3032/16000
ablate_active: 3036/16000
ablate_active: 3040/16000
ablate_active: 3044/16000
ablate_active: 3048/16000
ablate_active: 3052/16000
ablate_active: 3056/16000
ablate_active: 3060/16000
ablate_active: 3064/16000
ablate_active: 3068/16000
ablate_active: 3072/16000
ablate_active: 3076/16000
ablate_active: 3080/16000
ablate_active: 3084/16000
ablate_active: 3088/16000
ablate_active: 3092/16000
ablate_active: 3096/16000
ablate_active: 3100/16000
ablate_active: 3104/16000
ablate_active: 3108/16000
ablate_active: 3112/16000
ablate_active: 3116/16000
ablate_active: 3120/16000
ablate_active: 3124/16000
ablate_active: 3128/16000
ablate_active: 3132/16000
ablate_active: 3136/16000
ablate_active: 3140/16000
ablate_active: 3144/16000
ablate_active: 3148/16000
ablate_active: 3152/16000
ablate_active: 3156/16000
ablate_active: 3160/16000
ablate_active: 3164/16000
ablate_active: 3168/16000
ablate_active: 3172/16000
ablate_active: 3176/16000
ablate_active: 3180/16000
ablate_active: 3184/16000
ablate_active: 3188/16000
ablate_active: 3192/16000
ablate_active: 3196/16000
ablate_active: 3200/16000
ablate_active: 3204/16000
ablate_active: 3208/16000
ablate_active: 3212/16000
ablate_active: 3216/16000
ablate_active: 3220/16000
ablate_active: 3224/16000
ablate_active: 3228/16000
ablate_active: 3232/16000
ablate_active: 3236/16000
ablate_active: 3240/16000
ablate_active: 3244/16000
ablate_active: 3248/16000
ablate_active: 3252/16000
ablate_active: 3256/16000
ablate_active: 3260/16000
ablate_active: 3264/16000
ablate_active: 3268/16000
ablate_active: 3272/16000
ablate_active: 3276/16000
ablate_active: 3280/16000
ablate_active: 3284/16000
ablate_active: 3288/16000
ablate_active: 3292/16000
ablate_active: 3296/16000
ablate_active: 3300/16000
ablate_active: 3304/16000
ablate_active: 3308/16000
ablate_active: 3312/16000
ablate_active: 3316/16000
ablate_active: 3320/16000
ablate_active: 3324/16000
ablate_active: 3328/16000
ablate_active: 3332/16000
ablate_active: 3336/16000
ablate_active: 3340/16000
ablate_active: 3344/16000
ablate_active: 3348/16000
ablate_active: 3352/16000
ablate_active: 3356/16000
ablate_active: 3360/16000
ablate_active: 3364/16000
ablate_active: 3368/16000
ablate_active: 3372/16000
ablate_active: 3376/16000
ablate_active: 3380/16000
ablate_active: 3384/16000
ablate_active: 3388/16000
ablate_active: 3392/16000
ablate_active: 3396/16000
ablate_active: 3400/16000
ablate_active: 3404/16000
ablate_active: 3408/16000
ablate_active: 3412/16000
ablate_active: 3416/16000
ablate_active: 3420/16000
ablate_active: 3424/16000
ablate_active: 3428/16000
ablate_active: 3432/16000
ablate_active: 3436/16000
ablate_active: 3440/16000
ablate_active: 3444/16000
ablate_active: 3448/16000
ablate_active: 3452/16000
ablate_active: 3456/16000
ablate_active: 3460/16000
ablate_active: 3464/16000
ablate_active: 3468/16000
ablate_active: 3472/16000
ablate_active: 3476/16000
ablate_active: 3480/16000
ablate_active: 3484/16000
ablate_active: 3488/16000
ablate_active: 3492/16000
ablate_active: 3496/16000
ablate_active: 3500/16000
ablate_active: 3504/16000
ablate_active: 3508/16000
ablate_active: 3512/16000
ablate_active: 3516/16000
ablate_active: 3520/16000
ablate_active: 3524/16000
ablate_active: 3528/16000
ablate_active: 3532/16000
ablate_active: 3536/16000
ablate_active: 3540/16000
ablate_active: 3544/16000
ablate_active: 3548/16000
ablate_active: 3552/16000
ablate_active: 3556/16000
ablate_active: 3560/16000
ablate_active: 3564/16000
ablate_active: 3568/16000
ablate_active: 3572/16000
ablate_active: 3576/16000
ablate_active: 3580/16000
ablate_active: 3584/16000
ablate_active: 3588/16000
ablate_active: 3592/16000
ablate_active: 3596/16000
ablate_active: 3600/16000
ablate_active: 3604/16000
ablate_active: 3608/16000
ablate_active: 3612/16000
ablate_active: 3616/16000
ablate_active: 3620/16000
ablate_active: 3624/16000
ablate_active: 3628/16000
ablate_active: 3632/16000
ablate_active: 3636/16000
ablate_active: 3640/16000
ablate_active: 3644/16000
ablate_active: 3648/16000
ablate_active: 3652/16000
ablate_active: 3656/16000
ablate_active: 3660/16000
ablate_active: 3664/16000
ablate_active: 3668/16000
ablate_active: 3672/16000
ablate_active: 3676/16000
ablate_active: 3680/16000
ablate_active: 3684/16000
ablate_active: 3688/16000
ablate_active: 3692/16000
ablate_active: 3696/16000
ablate_active: 3700/16000
ablate_active: 3704/16000
ablate_active: 3708/16000
ablate_active: 3712/16000
ablate_active: 3716/16000
ablate_active: 3720/16000
ablate_active: 3724/16000
ablate_active: 3728/16000
ablate_active: 3732/16000
ablate_active: 3736/16000
ablate_active: 3740/16000
ablate_active: 3744/16000
ablate_active: 3748/16000
ablate_active: 3752/16000
ablate_active: 3756/16000
ablate_active: 3760/16000
ablate_active: 3764/16000
ablate_active: 3768/16000
ablate_active: 3772/16000
ablate_active: 3776/16000
ablate_active: 3780/16000
ablate_active: 3784/16000
ablate_active: 3788/16000
ablate_active: 3792/16000
ablate_active: 3796/16000
ablate_active: 3800/16000
ablate_active: 3804/16000
ablate_active: 3808/16000
ablate_active: 3812/16000
ablate_active: 3816/16000
ablate_active: 3820/16000
ablate_active: 3824/16000
ablate_active: 3828/16000
ablate_active: 3832/16000
ablate_active: 3836/16000
ablate_active: 3840/16000
ablate_active: 3844/16000

ablate_active: 3848/16000
ablate_active: 3852/16000
ablate_active: 3856/16000
ablate_active: 3860/16000
ablate_active: 3864/16000
ablate_active: 3868/16000
ablate_active: 3872/16000
ablate_active: 3876/16000
ablate_active: 3880/16000
ablate_active: 3884/16000
ablate_active: 3888/16000
ablate_active: 3892/16000
ablate_active: 3896/16000
ablate_active: 3900/16000
ablate_active: 3904/16000
ablate_active: 3908/16000
ablate_active: 3912/16000
ablate_active: 3916/16000
ablate_active: 3920/16000
ablate_active: 3924/16000
ablate_active: 3928/16000
ablate_active: 3932/16000
ablate_active: 3936/16000
ablate_active: 3940/16000
ablate_active: 3944/16000
ablate_active: 3948/16000
ablate_active: 3952/16000
ablate_active: 3956/16000
ablate_active: 3960/16000
ablate_active: 3964/16000
ablate_active: 3968/16000
ablate_active: 3972/16000
ablate_active: 3976/16000
ablate_active: 3980/16000
ablate_active: 3984/16000
ablate_active: 3988/16000
ablate_active: 3992/16000
ablate_active: 3996/16000
ablate_active: 4000/16000
ablate_active: 4004/16000
ablate_active: 4008/16000
ablate_active: 4012/16000
ablate_active: 4016/16000
ablate_active: 4020/16000
ablate_active: 4024/16000
ablate_active: 4028/16000
ablate_active: 4032/16000
ablate_active: 4036/16000
ablate_active: 4040/16000
ablate_active: 4044/16000
ablate_active: 4048/16000
ablate_active: 4052/16000
ablate_active: 4056/16000
ablate_active: 4060/16000
ablate_active: 4064/16000
ablate_active: 4068/16000
ablate_active: 4072/16000
ablate_active: 4076/16000
ablate_active: 4080/16000
ablate_active: 4084/16000
ablate_active: 4088/16000
ablate_active: 4092/16000
ablate_active: 4096/16000
ablate_active: 4100/16000
ablate_active: 4104/16000
ablate_active: 4108/16000
ablate_active: 4112/16000
ablate_active: 4116/16000
ablate_active: 4120/16000
ablate_active: 4124/16000
ablate_active: 4128/16000
ablate_active: 4132/16000
ablate_active: 4136/16000
ablate_active: 4140/16000
ablate_active: 4144/16000
ablate_active: 4148/16000
ablate_active: 4152/16000
ablate_active: 4156/16000
ablate_active: 4160/16000
ablate_active: 4164/16000
ablate_active: 4168/16000
ablate_active: 4172/16000
ablate_active: 4176/16000
ablate_active: 4180/16000
ablate_active: 4184/16000
ablate_active: 4188/16000
ablate_active: 4192/16000
ablate_active: 4196/16000
ablate_active: 4200/16000
ablate_active: 4204/16000
ablate_active: 4208/16000
ablate_active: 4212/16000
ablate_active: 4216/16000
ablate_active: 4220/16000
ablate_active: 4224/16000
ablate_active: 4228/16000
ablate_active: 4232/16000
ablate_active: 4236/16000
ablate_active: 4240/16000
ablate_active: 4244/16000
ablate_active: 4248/16000
ablate_active: 4252/16000
ablate_active: 4256/16000
ablate_active: 4260/16000
ablate_active: 4264/16000
ablate_active: 4268/16000
ablate_active: 4272/16000
ablate_active: 4276/16000
ablate_active: 4280/16000
ablate_active: 4284/16000
ablate_active: 4288/16000
ablate_active: 4292/16000
ablate_active: 4296/16000
ablate_active: 4300/16000
ablate_active: 4304/16000
ablate_active: 4308/16000
ablate_active: 4312/16000
ablate_active: 4316/16000
ablate_active: 4320/16000
ablate_active: 4324/16000
ablate_active: 4328/16000
ablate_active: 4332/16000
ablate_active: 4336/16000
ablate_active: 4340/16000
ablate_active: 4344/16000
ablate_active: 4348/16000
ablate_active: 4352/16000
ablate_active: 4356/16000
ablate_active: 4360/16000
ablate_active: 4364/16000
ablate_active: 4368/16000
ablate_active: 4372/16000
ablate_active: 4376/16000
ablate_active: 4380/16000
ablate_active: 4384/16000
ablate_active: 4388/16000
ablate_active: 4392/16000
ablate_active: 4396/16000
ablate_active: 4400/16000
ablate_active: 4404/16000
ablate_active: 4408/16000
ablate_active: 4412/16000
ablate_active: 4416/16000
ablate_active: 4420/16000
ablate_active: 4424/16000
ablate_active: 4428/16000
ablate_active: 4432/16000
ablate_active: 4436/16000
ablate_active: 4440/16000
ablate_active: 4444/16000
ablate_active: 4448/16000
ablate_active: 4452/16000
ablate_active: 4456/16000
ablate_active: 4460/16000
ablate_active: 4464/16000
ablate_active: 4468/16000
ablate_active: 4472/16000
ablate_active: 4476/16000
ablate_active: 4480/16000
ablate_active: 4484/16000
ablate_active: 4488/16000
ablate_active: 4492/16000
ablate_active: 4496/16000
ablate_active: 4500/16000
ablate_active: 4504/16000
ablate_active: 4508/16000
ablate_active: 4512/16000
ablate_active: 4516/16000
ablate_active: 4520/16000
ablate_active: 4524/16000
ablate_active: 4528/16000
ablate_active: 4532/16000
ablate_active: 4536/16000
ablate_active: 4540/16000
ablate_active: 4544/16000
ablate_active: 4548/16000
ablate_active: 4552/16000
ablate_active: 4556/16000
ablate_active: 4560/16000
ablate_active: 4564/16000
ablate_active: 4568/16000
ablate_active: 4572/16000
ablate_active: 4576/16000
ablate_active: 4580/16000
ablate_active: 4584/16000
ablate_active: 4588/16000
ablate_active: 4592/16000
ablate_active: 4596/16000
ablate_active: 4600/16000
ablate_active: 4604/16000
ablate_active: 4608/16000
ablate_active: 4612/16000
ablate_active: 4616/16000
ablate_active: 4620/16000
ablate_active: 4624/16000
ablate_active: 4628/16000
ablate_active: 4632/16000
ablate_active: 4636/16000
ablate_active: 4640/16000
ablate_active: 4644/16000
ablate_active: 4648/16000
ablate_active: 4652/16000
ablate_active: 4656/16000
ablate_active: 4660/16000
ablate_active: 4664/16000
ablate_active: 4668/16000
ablate_active: 4672/16000
ablate_active: 4676/16000
ablate_active: 4680/16000
ablate_active: 4684/16000
ablate_active: 4688/16000
ablate_active: 4692/16000
ablate_active: 4696/16000
ablate_active: 4700/16000
ablate_active: 4704/16000
ablate_active: 4708/16000
ablate_active: 4712/16000
ablate_active: 4716/16000
ablate_active: 4720/16000
ablate_active: 4724/16000
ablate_active: 4728/16000
ablate_active: 4732/16000
ablate_active: 4736/16000
ablate_active: 4740/16000
ablate_active: 4744/16000
ablate_active: 4748/16000
ablate_active: 4752/16000
ablate_active: 4756/16000
ablate_active: 4760/16000
ablate_active: 4764/16000
ablate_active: 4768/16000
ablate_active: 4772/16000
ablate_active: 4776/16000
ablate_active: 4780/16000
ablate_active: 4784/16000
ablate_active: 4788/16000
ablate_active: 4792/16000
ablate_active: 4796/16000
ablate_active: 4800/16000
ablate_active: 4804/16000
ablate_active: 4808/16000
ablate_active: 4812/16000
ablate_active: 4816/16000
ablate_active: 4820/16000
ablate_active: 4824/16000
ablate_active: 4828/16000
ablate_active: 4832/16000
ablate_active: 4836/16000
ablate_active: 4840/16000
ablate_active: 4844/16000
ablate_active: 4848/16000
ablate_active: 4852/16000
ablate_active: 4856/16000
ablate_active: 4860/16000
ablate_active: 4864/16000
ablate_active: 4868/16000
ablate_active: 4872/16000
ablate_active: 4876/16000
ablate_active: 4880/16000
ablate_active: 4884/16000
ablate_active: 4888/16000
ablate_active: 4892/16000
ablate_active: 4896/16000
ablate_active: 4900/16000
ablate_active: 4904/16000
ablate_active: 4908/16000
ablate_active: 4912/16000
ablate_active: 4916/16000
ablate_active: 4920/16000
ablate_active: 4924/16000
ablate_active: 4928/16000
ablate_active: 4932/16000
ablate_active: 4936/16000
ablate_active: 4940/16000
ablate_active: 4944/16000
ablate_active: 4948/16000
ablate_active: 4952/16000
ablate_active: 4956/16000
ablate_active: 4960/16000
ablate_active: 4964/16000
ablate_active: 4968/16000
ablate_active: 4972/16000
ablate_active: 4976/16000
ablate_active: 4980/16000
ablate_active: 4984/16000
ablate_active: 4988/16000
ablate_active: 4992/16000
ablate_active: 4996/16000
ablate_active: 5000/16000
ablate_active: 5004/16000
ablate_active: 5008/16000
ablate_active: 5012/16000
ablate_active: 5016/16000
ablate_active: 5020/16000
ablate_active: 5024/16000
ablate_active: 5028/16000
ablate_active: 5032/16000
ablate_active: 5036/16000
ablate_active: 5040/16000
ablate_active: 5044/16000
ablate_active: 5048/16000
ablate_active: 5052/16000
ablate_active: 5056/16000
ablate_active: 5060/16000
ablate_active: 5064/16000
ablate_active: 5068/16000
ablate_active: 5072/16000
ablate_active: 5076/16000
ablate_active: 5080/16000
ablate_active: 5084/16000
ablate_active: 5088/16000
ablate_active: 5092/16000
ablate_active: 5096/16000
ablate_active: 5100/16000
ablate_active: 5104/16000
ablate_active: 5108/16000

ablate_active: 5112/16000
ablate_active: 5116/16000
ablate_active: 5120/16000
ablate_active: 5124/16000
ablate_active: 5128/16000
ablate_active: 5132/16000
ablate_active: 5136/16000
ablate_active: 5140/16000
ablate_active: 5144/16000
ablate_active: 5148/16000
ablate_active: 5152/16000
ablate_active: 5156/16000
ablate_active: 5160/16000
ablate_active: 5164/16000
ablate_active: 5168/16000
ablate_active: 5172/16000
ablate_active: 5176/16000
ablate_active: 5180/16000
ablate_active: 5184/16000
ablate_active: 5188/16000
ablate_active: 5192/16000
ablate_active: 5196/16000
ablate_active: 5200/16000
ablate_active: 5204/16000
ablate_active: 5208/16000
ablate_active: 5212/16000
ablate_active: 5216/16000
ablate_active: 5220/16000
ablate_active: 5224/16000
ablate_active: 5228/16000
ablate_active: 5232/16000
ablate_active: 5236/16000
ablate_active: 5240/16000
ablate_active: 5244/16000
ablate_active: 5248/16000
ablate_active: 5252/16000
ablate_active: 5256/16000
ablate_active: 5260/16000
ablate_active: 5264/16000
ablate_active: 5268/16000
ablate_active: 5272/16000
ablate_active: 5276/16000
ablate_active: 5280/16000
ablate_active: 5284/16000
ablate_active: 5288/16000
ablate_active: 5292/16000
ablate_active: 5296/16000
ablate_active: 5300/16000
ablate_active: 5304/16000
ablate_active: 5308/16000
ablate_active: 5312/16000
ablate_active: 5316/16000
ablate_active: 5320/16000
ablate_active: 5324/16000
ablate_active: 5328/16000
ablate_active: 5332/16000
ablate_active: 5336/16000
ablate_active: 5340/16000
ablate_active: 5344/16000
ablate_active: 5348/16000
ablate_active: 5352/16000
ablate_active: 5356/16000
ablate_active: 5360/16000
ablate_active: 5364/16000
ablate_active: 5368/16000
ablate_active: 5372/16000
ablate_active: 5376/16000
ablate_active: 5380/16000
ablate_active: 5384/16000
ablate_active: 5388/16000
ablate_active: 5392/16000
ablate_active: 5396/16000
ablate_active: 5400/16000
ablate_active: 5404/16000
ablate_active: 5408/16000
ablate_active: 5412/16000
ablate_active: 5416/16000
ablate_active: 5420/16000
ablate_active: 5424/16000
ablate_active: 5428/16000
ablate_active: 5432/16000
ablate_active: 5436/16000
ablate_active: 5440/16000
ablate_active: 5444/16000
ablate_active: 5448/16000
ablate_active: 5452/16000
ablate_active: 5456/16000
ablate_active: 5460/16000
ablate_active: 5464/16000
ablate_active: 5468/16000
ablate_active: 5472/16000
ablate_active: 5476/16000
ablate_active: 5480/16000
ablate_active: 5484/16000
ablate_active: 5488/16000
ablate_active: 5492/16000
ablate_active: 5496/16000
ablate_active: 5500/16000
ablate_active: 5504/16000
ablate_active: 5508/16000
ablate_active: 5512/16000
ablate_active: 5516/16000
ablate_active: 5520/16000
ablate_active: 5524/16000
ablate_active: 5528/16000
ablate_active: 5532/16000
ablate_active: 5536/16000
ablate_active: 5540/16000
ablate_active: 5544/16000
ablate_active: 5548/16000
ablate_active: 5552/16000
ablate_active: 5556/16000
ablate_active: 5560/16000
ablate_active: 5564/16000
ablate_active: 5568/16000
ablate_active: 5572/16000
ablate_active: 5576/16000
ablate_active: 5580/16000
ablate_active: 5584/16000
ablate_active: 5588/16000
ablate_active: 5592/16000
ablate_active: 5596/16000
ablate_active: 5600/16000
ablate_active: 5604/16000
ablate_active: 5608/16000
ablate_active: 5612/16000
ablate_active: 5616/16000
ablate_active: 5620/16000
ablate_active: 5624/16000
ablate_active: 5628/16000
ablate_active: 5632/16000
ablate_active: 5636/16000
ablate_active: 5640/16000
ablate_active: 5644/16000
ablate_active: 5648/16000
ablate_active: 5652/16000
ablate_active: 5656/16000
ablate_active: 5660/16000
ablate_active: 5664/16000
ablate_active: 5668/16000
ablate_active: 5672/16000
ablate_active: 5676/16000
ablate_active: 5680/16000
ablate_active: 5684/16000
ablate_active: 5688/16000
ablate_active: 5692/16000
ablate_active: 5696/16000
ablate_active: 5700/16000
ablate_active: 5704/16000
ablate_active: 5708/16000
ablate_active: 5712/16000
ablate_active: 5716/16000
ablate_active: 5720/16000
ablate_active: 5724/16000
ablate_active: 5728/16000
ablate_active: 5732/16000
ablate_active: 5736/16000
ablate_active: 5740/16000
ablate_active: 5744/16000
ablate_active: 5748/16000
ablate_active: 5752/16000
ablate_active: 5756/16000
ablate_active: 5760/16000
ablate_active: 5764/16000
ablate_active: 5768/16000
ablate_active: 5772/16000
ablate_active: 5776/16000
ablate_active: 5780/16000
ablate_active: 5784/16000
ablate_active: 5788/16000
ablate_active: 5792/16000
ablate_active: 5796/16000
ablate_active: 5800/16000
ablate_active: 5804/16000
ablate_active: 5808/16000
ablate_active: 5812/16000
ablate_active: 5816/16000
ablate_active: 5820/16000
ablate_active: 5824/16000
ablate_active: 5828/16000
ablate_active: 5832/16000
ablate_active: 5836/16000
ablate_active: 5840/16000
ablate_active: 5844/16000
ablate_active: 5848/16000
ablate_active: 5852/16000
ablate_active: 5856/16000
ablate_active: 5860/16000
ablate_active: 5864/16000
ablate_active: 5868/16000
ablate_active: 5872/16000
ablate_active: 5876/16000
ablate_active: 5880/16000
ablate_active: 5884/16000
ablate_active: 5888/16000
ablate_active: 5892/16000
ablate_active: 5896/16000
ablate_active: 5900/16000
ablate_active: 5904/16000
ablate_active: 5908/16000
ablate_active: 5912/16000
ablate_active: 5916/16000
ablate_active: 5920/16000
ablate_active: 5924/16000
ablate_active: 5928/16000
ablate_active: 5932/16000
ablate_active: 5936/16000
ablate_active: 5940/16000
ablate_active: 5944/16000
ablate_active: 5948/16000
ablate_active: 5952/16000
ablate_active: 5956/16000
ablate_active: 5960/16000
ablate_active: 5964/16000
ablate_active: 5968/16000
ablate_active: 5972/16000
ablate_active: 5976/16000
ablate_active: 5980/16000
ablate_active: 5984/16000
ablate_active: 5988/16000
ablate_active: 5992/16000
ablate_active: 5996/16000
ablate_active: 6000/16000
ablate_active: 6004/16000
ablate_active: 6008/16000
ablate_active: 6012/16000
ablate_active: 6016/16000
ablate_active: 6020/16000
ablate_active: 6024/16000
ablate_active: 6028/16000
ablate_active: 6032/16000
ablate_active: 6036/16000
ablate_active: 6040/16000
ablate_active: 6044/16000
ablate_active: 6048/16000
ablate_active: 6052/16000
ablate_active: 6056/16000
ablate_active: 6060/16000
ablate_active: 6064/16000
ablate_active: 6068/16000
ablate_active: 6072/16000
ablate_active: 6076/16000
ablate_active: 6080/16000
ablate_active: 6084/16000
ablate_active: 6088/16000
ablate_active: 6092/16000
ablate_active: 6096/16000
ablate_active: 6100/16000
ablate_active: 6104/16000
ablate_active: 6108/16000
ablate_active: 6112/16000
ablate_active: 6116/16000
ablate_active: 6120/16000
ablate_active: 6124/16000
ablate_active: 6128/16000
ablate_active: 6132/16000
ablate_active: 6136/16000
ablate_active: 6140/16000
ablate_active: 6144/16000
ablate_active: 6148/16000
ablate_active: 6152/16000
ablate_active: 6156/16000
ablate_active: 6160/16000
ablate_active: 6164/16000
ablate_active: 6168/16000
ablate_active: 6172/16000
ablate_active: 6176/16000
ablate_active: 6180/16000
ablate_active: 6184/16000
ablate_active: 6188/16000
ablate_active: 6192/16000
ablate_active: 6196/16000
ablate_active: 6200/16000
ablate_active: 6204/16000
ablate_active: 6208/16000
ablate_active: 6212/16000
ablate_active: 6216/16000
ablate_active: 6220/16000
ablate_active: 6224/16000
ablate_active: 6228/16000
ablate_active: 6232/16000
ablate_active: 6236/16000
ablate_active: 6240/16000
ablate_active: 6244/16000
ablate_active: 6248/16000
ablate_active: 6252/16000
ablate_active: 6256/16000
ablate_active: 6260/16000
ablate_active: 6264/16000
ablate_active: 6268/16000
ablate_active: 6272/16000
ablate_active: 6276/16000
ablate_active: 6280/16000
ablate_active: 6284/16000
ablate_active: 6288/16000
ablate_active: 6292/16000
ablate_active: 6296/16000
ablate_active: 6300/16000
ablate_active: 6304/16000
ablate_active: 6308/16000
ablate_active: 6312/16000
ablate_active: 6316/16000
ablate_active: 6320/16000
ablate_active: 6324/16000
ablate_active: 6328/16000
ablate_active: 6332/16000
ablate_active: 6336/16000
ablate_active: 6340/16000
ablate_active: 6344/16000
ablate_active: 6348/16000
ablate_active: 6352/16000
ablate_active: 6356/16000
ablate_active: 6360/16000
ablate_active: 6364/16000
ablate_active: 6368/16000
ablate_active: 6372/16000
ablate_active: 6376/16000

ablate_active: 6380/16000
ablate_active: 6384/16000
ablate_active: 6388/16000
ablate_active: 6392/16000
ablate_active: 6396/16000
ablate_active: 6400/16000
ablate_active: 6404/16000
ablate_active: 6408/16000
ablate_active: 6412/16000
ablate_active: 6416/16000
ablate_active: 6420/16000
ablate_active: 6424/16000
ablate_active: 6428/16000
ablate_active: 6432/16000
ablate_active: 6436/16000
ablate_active: 6440/16000
ablate_active: 6444/16000
ablate_active: 6448/16000
ablate_active: 6452/16000
ablate_active: 6456/16000
ablate_active: 6460/16000
ablate_active: 6464/16000
ablate_active: 6468/16000
ablate_active: 6472/16000
ablate_active: 6476/16000
ablate_active: 6480/16000
ablate_active: 6484/16000
ablate_active: 6488/16000
ablate_active: 6492/16000
ablate_active: 6496/16000
ablate_active: 6500/16000
ablate_active: 6504/16000
ablate_active: 6508/16000
ablate_active: 6512/16000
ablate_active: 6516/16000
ablate_active: 6520/16000
ablate_active: 6524/16000
ablate_active: 6528/16000
ablate_active: 6532/16000
ablate_active: 6536/16000
ablate_active: 6540/16000
ablate_active: 6544/16000
ablate_active: 6548/16000
ablate_active: 6552/16000
ablate_active: 6556/16000
ablate_active: 6560/16000
ablate_active: 6564/16000
ablate_active: 6568/16000
ablate_active: 6572/16000
ablate_active: 6576/16000
ablate_active: 6580/16000
ablate_active: 6584/16000
ablate_active: 6588/16000
ablate_active: 6592/16000
ablate_active: 6596/16000
ablate_active: 6600/16000
ablate_active: 6604/16000
ablate_active: 6608/16000
ablate_active: 6612/16000
ablate_active: 6616/16000
ablate_active: 6620/16000
ablate_active: 6624/16000
ablate_active: 6628/16000
ablate_active: 6632/16000
ablate_active: 6636/16000
ablate_active: 6640/16000
ablate_active: 6644/16000
ablate_active: 6648/16000
ablate_active: 6652/16000
ablate_active: 6656/16000
ablate_active: 6660/16000
ablate_active: 6664/16000
ablate_active: 6668/16000
ablate_active: 6672/16000
ablate_active: 6676/16000
ablate_active: 6680/16000
ablate_active: 6684/16000
ablate_active: 6688/16000
ablate_active: 6692/16000
ablate_active: 6696/16000
ablate_active: 6700/16000
ablate_active: 6704/16000
ablate_active: 6708/16000
ablate_active: 6712/16000
ablate_active: 6716/16000
ablate_active: 6720/16000
ablate_active: 6724/16000
ablate_active: 6728/16000
ablate_active: 6732/16000
ablate_active: 6736/16000
ablate_active: 6740/16000
ablate_active: 6744/16000
ablate_active: 6748/16000
ablate_active: 6752/16000
ablate_active: 6756/16000
ablate_active: 6760/16000
ablate_active: 6764/16000
ablate_active: 6768/16000
ablate_active: 6772/16000
ablate_active: 6776/16000
ablate_active: 6780/16000
ablate_active: 6784/16000
ablate_active: 6788/16000
ablate_active: 6792/16000
ablate_active: 6796/16000
ablate_active: 6800/16000
ablate_active: 6804/16000
ablate_active: 6808/16000
ablate_active: 6812/16000
ablate_active: 6816/16000
ablate_active: 6820/16000
ablate_active: 6824/16000
ablate_active: 6828/16000
ablate_active: 6832/16000
ablate_active: 6836/16000
ablate_active: 6840/16000
ablate_active: 6844/16000
ablate_active: 6848/16000
ablate_active: 6852/16000
ablate_active: 6856/16000
ablate_active: 6860/16000
ablate_active: 6864/16000
ablate_active: 6868/16000
ablate_active: 6872/16000
ablate_active: 6876/16000
ablate_active: 6880/16000
ablate_active: 6884/16000
ablate_active: 6888/16000
ablate_active: 6892/16000
ablate_active: 6896/16000
ablate_active: 6900/16000
ablate_active: 6904/16000
ablate_active: 6908/16000
ablate_active: 6912/16000
ablate_active: 6916/16000
ablate_active: 6920/16000
ablate_active: 6924/16000
ablate_active: 6928/16000
ablate_active: 6932/16000
ablate_active: 6936/16000
ablate_active: 6940/16000
ablate_active: 6944/16000
ablate_active: 6948/16000
ablate_active: 6952/16000
ablate_active: 6956/16000
ablate_active: 6960/16000
ablate_active: 6964/16000
ablate_active: 6968/16000
ablate_active: 6972/16000
ablate_active: 6976/16000
ablate_active: 6980/16000
ablate_active: 6984/16000
ablate_active: 6988/16000
ablate_active: 6992/16000
ablate_active: 6996/16000
ablate_active: 7000/16000
ablate_active: 7004/16000
ablate_active: 7008/16000
ablate_active: 7012/16000
ablate_active: 7016/16000
ablate_active: 7020/16000
ablate_active: 7024/16000
ablate_active: 7028/16000
ablate_active: 7032/16000
ablate_active: 7036/16000
ablate_active: 7040/16000
ablate_active: 7044/16000
ablate_active: 7048/16000
ablate_active: 7052/16000
ablate_active: 7056/16000
ablate_active: 7060/16000
ablate_active: 7064/16000
ablate_active: 7068/16000
ablate_active: 7072/16000
ablate_active: 7076/16000
ablate_active: 7080/16000
ablate_active: 7084/16000
ablate_active: 7088/16000
ablate_active: 7092/16000
ablate_active: 7096/16000
ablate_active: 7100/16000
ablate_active: 7104/16000
ablate_active: 7108/16000
ablate_active: 7112/16000
ablate_active: 7116/16000
ablate_active: 7120/16000
ablate_active: 7124/16000
ablate_active: 7128/16000
ablate_active: 7132/16000
ablate_active: 7136/16000
ablate_active: 7140/16000
ablate_active: 7144/16000
ablate_active: 7148/16000
ablate_active: 7152/16000
ablate_active: 7156/16000
ablate_active: 7160/16000
ablate_active: 7164/16000
ablate_active: 7168/16000
ablate_active: 7172/16000
ablate_active: 7176/16000
ablate_active: 7180/16000
ablate_active: 7184/16000
ablate_active: 7188/16000
ablate_active: 7192/16000
ablate_active: 7196/16000
ablate_active: 7200/16000
ablate_active: 7204/16000
ablate_active: 7208/16000
ablate_active: 7212/16000
ablate_active: 7216/16000
ablate_active: 7220/16000
ablate_active: 7224/16000
ablate_active: 7228/16000
ablate_active: 7232/16000
ablate_active: 7236/16000
ablate_active: 7240/16000
ablate_active: 7244/16000
ablate_active: 7248/16000
ablate_active: 7252/16000
ablate_active: 7256/16000
ablate_active: 7260/16000
ablate_active: 7264/16000
ablate_active: 7268/16000
ablate_active: 7272/16000
ablate_active: 7276/16000
ablate_active: 7280/16000
ablate_active: 7284/16000
ablate_active: 7288/16000
ablate_active: 7292/16000
ablate_active: 7296/16000
ablate_active: 7300/16000
ablate_active: 7304/16000
ablate_active: 7308/16000
ablate_active: 7312/16000
ablate_active: 7316/16000
ablate_active: 7320/16000
ablate_active: 7324/16000
ablate_active: 7328/16000
ablate_active: 7332/16000
ablate_active: 7336/16000
ablate_active: 7340/16000
ablate_active: 7344/16000
ablate_active: 7348/16000
ablate_active: 7352/16000
ablate_active: 7356/16000
ablate_active: 7360/16000
ablate_active: 7364/16000
ablate_active: 7368/16000
ablate_active: 7372/16000
ablate_active: 7376/16000
ablate_active: 7380/16000
ablate_active: 7384/16000
ablate_active: 7388/16000
ablate_active: 7392/16000
ablate_active: 7396/16000
ablate_active: 7400/16000
ablate_active: 7404/16000
ablate_active: 7408/16000
ablate_active: 7412/16000
ablate_active: 7416/16000
ablate_active: 7420/16000
ablate_active: 7424/16000
ablate_active: 7428/16000
ablate_active: 7432/16000
ablate_active: 7436/16000
ablate_active: 7440/16000
ablate_active: 7444/16000
ablate_active: 7448/16000
ablate_active: 7452/16000
ablate_active: 7456/16000
ablate_active: 7460/16000
ablate_active: 7464/16000
ablate_active: 7468/16000
ablate_active: 7472/16000
ablate_active: 7476/16000
ablate_active: 7480/16000
ablate_active: 7484/16000
ablate_active: 7488/16000
ablate_active: 7492/16000
ablate_active: 7496/16000
ablate_active: 7500/16000
ablate_active: 7504/16000
ablate_active: 7508/16000
ablate_active: 7512/16000
ablate_active: 7516/16000
ablate_active: 7520/16000
ablate_active: 7524/16000
ablate_active: 7528/16000
ablate_active: 7532/16000
ablate_active: 7536/16000
ablate_active: 7540/16000
ablate_active: 7544/16000
ablate_active: 7548/16000
ablate_active: 7552/16000
ablate_active: 7556/16000
ablate_active: 7560/16000
ablate_active: 7564/16000
ablate_active: 7568/16000
ablate_active: 7572/16000
ablate_active: 7576/16000
ablate_active: 7580/16000
ablate_active: 7584/16000
ablate_active: 7588/16000
ablate_active: 7592/16000
ablate_active: 7596/16000
ablate_active: 7600/16000
ablate_active: 7604/16000
ablate_active: 7608/16000
ablate_active: 7612/16000
ablate_active: 7616/16000
ablate_active: 7620/16000
ablate_active: 7624/16000
ablate_active: 7628/16000
ablate_active: 7632/16000
ablate_active: 7636/16000
ablate_active: 7640/16000

ablate_active: 7644/16000
ablate_active: 7648/16000
ablate_active: 7652/16000
ablate_active: 7656/16000
ablate_active: 7660/16000
ablate_active: 7664/16000
ablate_active: 7668/16000
ablate_active: 7672/16000
ablate_active: 7676/16000
ablate_active: 7680/16000
ablate_active: 7684/16000
ablate_active: 7688/16000
ablate_active: 7692/16000
ablate_active: 7696/16000
ablate_active: 7700/16000
ablate_active: 7704/16000
ablate_active: 7708/16000
ablate_active: 7712/16000
ablate_active: 7716/16000
ablate_active: 7720/16000
ablate_active: 7724/16000
ablate_active: 7728/16000
ablate_active: 7732/16000
ablate_active: 7736/16000
ablate_active: 7740/16000
ablate_active: 7744/16000
ablate_active: 7748/16000
ablate_active: 7752/16000
ablate_active: 7756/16000
ablate_active: 7760/16000
ablate_active: 7764/16000
ablate_active: 7768/16000
ablate_active: 7772/16000
ablate_active: 7776/16000
ablate_active: 7780/16000
ablate_active: 7784/16000
ablate_active: 7788/16000
ablate_active: 7792/16000
ablate_active: 7796/16000
ablate_active: 7800/16000
ablate_active: 7804/16000
ablate_active: 7808/16000
ablate_active: 7812/16000
ablate_active: 7816/16000
ablate_active: 7820/16000
ablate_active: 7824/16000
ablate_active: 7828/16000
ablate_active: 7832/16000
ablate_active: 7836/16000
ablate_active: 7840/16000
ablate_active: 7844/16000
ablate_active: 7848/16000
ablate_active: 7852/16000
ablate_active: 7856/16000
ablate_active: 7860/16000
ablate_active: 7864/16000
ablate_active: 7868/16000
ablate_active: 7872/16000
ablate_active: 7876/16000
ablate_active: 7880/16000
ablate_active: 7884/16000
ablate_active: 7888/16000
ablate_active: 7892/16000
ablate_active: 7896/16000
ablate_active: 7900/16000
ablate_active: 7904/16000
ablate_active: 7908/16000
ablate_active: 7912/16000
ablate_active: 7916/16000
ablate_active: 7920/16000
ablate_active: 7924/16000
ablate_active: 7928/16000
ablate_active: 7932/16000
ablate_active: 7936/16000
ablate_active: 7940/16000
ablate_active: 7944/16000
ablate_active: 7948/16000
ablate_active: 7952/16000
ablate_active: 7956/16000
ablate_active: 7960/16000
ablate_active: 7964/16000
ablate_active: 7968/16000
ablate_active: 7972/16000
ablate_active: 7976/16000
ablate_active: 7980/16000
ablate_active: 7984/16000
ablate_active: 7988/16000
ablate_active: 7992/16000
ablate_active: 7996/16000
ablate_active: 8000/16000
ablate_active: 8004/16000
ablate_active: 8008/16000
ablate_active: 8012/16000
ablate_active: 8016/16000
ablate_active: 8020/16000
ablate_active: 8024/16000
ablate_active: 8028/16000
ablate_active: 8032/16000
ablate_active: 8036/16000
ablate_active: 8040/16000
ablate_active: 8044/16000
ablate_active: 8048/16000
ablate_active: 8052/16000
ablate_active: 8056/16000
ablate_active: 8060/16000
ablate_active: 8064/16000
ablate_active: 8068/16000
ablate_active: 8072/16000
ablate_active: 8076/16000
ablate_active: 8080/16000
ablate_active: 8084/16000
ablate_active: 8088/16000
ablate_active: 8092/16000
ablate_active: 8096/16000
ablate_active: 8100/16000
ablate_active: 8104/16000
ablate_active: 8108/16000
ablate_active: 8112/16000
ablate_active: 8116/16000
ablate_active: 8120/16000
ablate_active: 8124/16000
ablate_active: 8128/16000
ablate_active: 8132/16000
ablate_active: 8136/16000
ablate_active: 8140/16000
ablate_active: 8144/16000
ablate_active: 8148/16000
ablate_active: 8152/16000
ablate_active: 8156/16000
ablate_active: 8160/16000
ablate_active: 8164/16000
ablate_active: 8168/16000
ablate_active: 8172/16000
ablate_active: 8176/16000
ablate_active: 8180/16000
ablate_active: 8184/16000
ablate_active: 8188/16000
ablate_active: 8192/16000
ablate_active: 8196/16000
ablate_active: 8200/16000
ablate_active: 8204/16000
ablate_active: 8208/16000
ablate_active: 8212/16000
ablate_active: 8216/16000
ablate_active: 8220/16000
ablate_active: 8224/16000
ablate_active: 8228/16000
ablate_active: 8232/16000
ablate_active: 8236/16000
ablate_active: 8240/16000
ablate_active: 8244/16000
ablate_active: 8248/16000
ablate_active: 8252/16000
ablate_active: 8256/16000
ablate_active: 8260/16000
ablate_active: 8264/16000
ablate_active: 8268/16000
ablate_active: 8272/16000
ablate_active: 8276/16000
ablate_active: 8280/16000
ablate_active: 8284/16000
ablate_active: 8288/16000
ablate_active: 8292/16000
ablate_active: 8296/16000
ablate_active: 8300/16000
ablate_active: 8304/16000
ablate_active: 8308/16000
ablate_active: 8312/16000
ablate_active: 8316/16000
ablate_active: 8320/16000
ablate_active: 8324/16000
ablate_active: 8328/16000
ablate_active: 8332/16000
ablate_active: 8336/16000
ablate_active: 8340/16000
ablate_active: 8344/16000
ablate_active: 8348/16000
ablate_active: 8352/16000
ablate_active: 8356/16000
ablate_active: 8360/16000
ablate_active: 8364/16000
ablate_active: 8368/16000
ablate_active: 8372/16000
ablate_active: 8376/16000
ablate_active: 8380/16000
ablate_active: 8384/16000
ablate_active: 8388/16000
ablate_active: 8392/16000
ablate_active: 8396/16000
ablate_active: 8400/16000
ablate_active: 8404/16000
ablate_active: 8408/16000
ablate_active: 8412/16000
ablate_active: 8416/16000
ablate_active: 8420/16000
ablate_active: 8424/16000
ablate_active: 8428/16000
ablate_active: 8432/16000
ablate_active: 8436/16000
ablate_active: 8440/16000
ablate_active: 8444/16000
ablate_active: 8448/16000
ablate_active: 8452/16000
ablate_active: 8456/16000
ablate_active: 8460/16000
ablate_active: 8464/16000
ablate_active: 8468/16000
ablate_active: 8472/16000
ablate_active: 8476/16000
ablate_active: 8480/16000
ablate_active: 8484/16000
ablate_active: 8488/16000
ablate_active: 8492/16000
ablate_active: 8496/16000
ablate_active: 8500/16000
ablate_active: 8504/16000
ablate_active: 8508/16000
ablate_active: 8512/16000
ablate_active: 8516/16000
ablate_active: 8520/16000
ablate_active: 8524/16000
ablate_active: 8528/16000
ablate_active: 8532/16000
ablate_active: 8536/16000
ablate_active: 8540/16000
ablate_active: 8544/16000
ablate_active: 8548/16000
ablate_active: 8552/16000
ablate_active: 8556/16000
ablate_active: 8560/16000
ablate_active: 8564/16000
ablate_active: 8568/16000
ablate_active: 8572/16000
ablate_active: 8576/16000
ablate_active: 8580/16000
ablate_active: 8584/16000
ablate_active: 8588/16000
ablate_active: 8592/16000
ablate_active: 8596/16000
ablate_active: 8600/16000
ablate_active: 8604/16000
ablate_active: 8608/16000
ablate_active: 8612/16000
ablate_active: 8616/16000
ablate_active: 8620/16000
ablate_active: 8624/16000
ablate_active: 8628/16000
ablate_active: 8632/16000
ablate_active: 8636/16000
ablate_active: 8640/16000
ablate_active: 8644/16000
ablate_active: 8648/16000
ablate_active: 8652/16000
ablate_active: 8656/16000
ablate_active: 8660/16000
ablate_active: 8664/16000
ablate_active: 8668/16000
ablate_active: 8672/16000
ablate_active: 8676/16000
ablate_active: 8680/16000
ablate_active: 8684/16000
ablate_active: 8688/16000
ablate_active: 8692/16000
ablate_active: 8696/16000
ablate_active: 8700/16000
ablate_active: 8704/16000
ablate_active: 8708/16000
ablate_active: 8712/16000
ablate_active: 8716/16000
ablate_active: 8720/16000
ablate_active: 8724/16000
ablate_active: 8728/16000
ablate_active: 8732/16000
ablate_active: 8736/16000
ablate_active: 8740/16000
ablate_active: 8744/16000
ablate_active: 8748/16000
ablate_active: 8752/16000
ablate_active: 8756/16000
ablate_active: 8760/16000
ablate_active: 8764/16000
ablate_active: 8768/16000
ablate_active: 8772/16000
ablate_active: 8776/16000
ablate_active: 8780/16000
ablate_active: 8784/16000
ablate_active: 8788/16000
ablate_active: 8792/16000
ablate_active: 8796/16000
ablate_active: 8800/16000
ablate_active: 8804/16000
ablate_active: 8808/16000
ablate_active: 8812/16000
ablate_active: 8816/16000
ablate_active: 8820/16000
ablate_active: 8824/16000
ablate_active: 8828/16000
ablate_active: 8832/16000
ablate_active: 8836/16000
ablate_active: 8840/16000
ablate_active: 8844/16000
ablate_active: 8848/16000
ablate_active: 8852/16000
ablate_active: 8856/16000
ablate_active: 8860/16000
ablate_active: 8864/16000
ablate_active: 8868/16000
ablate_active: 8872/16000
ablate_active: 8876/16000
ablate_active: 8880/16000
ablate_active: 8884/16000
ablate_active: 8888/16000
ablate_active: 8892/16000
ablate_active: 8896/16000
ablate_active: 8900/16000
ablate_active: 8904/16000
ablate_active: 8908/16000

ablate_active: 8912/16000
ablate_active: 8916/16000
ablate_active: 8920/16000
ablate_active: 8924/16000
ablate_active: 8928/16000
ablate_active: 8932/16000
ablate_active: 8936/16000
ablate_active: 8940/16000
ablate_active: 8944/16000
ablate_active: 8948/16000
ablate_active: 8952/16000
ablate_active: 8956/16000
ablate_active: 8960/16000
ablate_active: 8964/16000
ablate_active: 8968/16000
ablate_active: 8972/16000
ablate_active: 8976/16000
ablate_active: 8980/16000
ablate_active: 8984/16000
ablate_active: 8988/16000
ablate_active: 8992/16000
ablate_active: 8996/16000
ablate_active: 9000/16000
ablate_active: 9004/16000
ablate_active: 9008/16000
ablate_active: 9012/16000
ablate_active: 9016/16000
ablate_active: 9020/16000
ablate_active: 9024/16000
ablate_active: 9028/16000
ablate_active: 9032/16000
ablate_active: 9036/16000
ablate_active: 9040/16000
ablate_active: 9044/16000
ablate_active: 9048/16000
ablate_active: 9052/16000
ablate_active: 9056/16000
ablate_active: 9060/16000
ablate_active: 9064/16000
ablate_active: 9068/16000
ablate_active: 9072/16000
ablate_active: 9076/16000
ablate_active: 9080/16000
ablate_active: 9084/16000
ablate_active: 9088/16000
ablate_active: 9092/16000
ablate_active: 9096/16000
ablate_active: 9100/16000
ablate_active: 9104/16000
ablate_active: 9108/16000
ablate_active: 9112/16000
ablate_active: 9116/16000
ablate_active: 9120/16000
ablate_active: 9124/16000
ablate_active: 9128/16000
ablate_active: 9132/16000
ablate_active: 9136/16000
ablate_active: 9140/16000
ablate_active: 9144/16000
ablate_active: 9148/16000
ablate_active: 9152/16000
ablate_active: 9156/16000
ablate_active: 9160/16000
ablate_active: 9164/16000
ablate_active: 9168/16000
ablate_active: 9172/16000
ablate_active: 9176/16000
ablate_active: 9180/16000
ablate_active: 9184/16000
ablate_active: 9188/16000
ablate_active: 9192/16000
ablate_active: 9196/16000
ablate_active: 9200/16000
ablate_active: 9204/16000
ablate_active: 9208/16000
ablate_active: 9212/16000
ablate_active: 9216/16000
ablate_active: 9220/16000
ablate_active: 9224/16000
ablate_active: 9228/16000
ablate_active: 9232/16000
ablate_active: 9236/16000
ablate_active: 9240/16000
ablate_active: 9244/16000
ablate_active: 9248/16000
ablate_active: 9252/16000
ablate_active: 9256/16000
ablate_active: 9260/16000
ablate_active: 9264/16000
ablate_active: 9268/16000
ablate_active: 9272/16000
ablate_active: 9276/16000
ablate_active: 9280/16000
ablate_active: 9284/16000
ablate_active: 9288/16000
ablate_active: 9292/16000
ablate_active: 9296/16000
ablate_active: 9300/16000
ablate_active: 9304/16000
ablate_active: 9308/16000
ablate_active: 9312/16000
ablate_active: 9316/16000
ablate_active: 9320/16000
ablate_active: 9324/16000
ablate_active: 9328/16000
ablate_active: 9332/16000
ablate_active: 9336/16000
ablate_active: 9340/16000
ablate_active: 9344/16000
ablate_active: 9348/16000
ablate_active: 9352/16000
ablate_active: 9356/16000
ablate_active: 9360/16000
ablate_active: 9364/16000
ablate_active: 9368/16000
ablate_active: 9372/16000
ablate_active: 9376/16000
ablate_active: 9380/16000
ablate_active: 9384/16000
ablate_active: 9388/16000
ablate_active: 9392/16000
ablate_active: 9396/16000
ablate_active: 9400/16000
ablate_active: 9404/16000
ablate_active: 9408/16000
ablate_active: 9412/16000
ablate_active: 9416/16000
ablate_active: 9420/16000
ablate_active: 9424/16000
ablate_active: 9428/16000
ablate_active: 9432/16000
ablate_active: 9436/16000
ablate_active: 9440/16000
ablate_active: 9444/16000
ablate_active: 9448/16000
ablate_active: 9452/16000
ablate_active: 9456/16000
ablate_active: 9460/16000
ablate_active: 9464/16000
ablate_active: 9468/16000
ablate_active: 9472/16000
ablate_active: 9476/16000
ablate_active: 9480/16000
ablate_active: 9484/16000
ablate_active: 9488/16000
ablate_active: 9492/16000
ablate_active: 9496/16000
ablate_active: 9500/16000
ablate_active: 9504/16000
ablate_active: 9508/16000
ablate_active: 9512/16000
ablate_active: 9516/16000
ablate_active: 9520/16000
ablate_active: 9524/16000
ablate_active: 9528/16000
ablate_active: 9532/16000
ablate_active: 9536/16000
ablate_active: 9540/16000
ablate_active: 9544/16000
ablate_active: 9548/16000
ablate_active: 9552/16000
ablate_active: 9556/16000
ablate_active: 9560/16000
ablate_active: 9564/16000
ablate_active: 9568/16000
ablate_active: 9572/16000
ablate_active: 9576/16000
ablate_active: 9580/16000
ablate_active: 9584/16000
ablate_active: 9588/16000
ablate_active: 9592/16000
ablate_active: 9596/16000
ablate_active: 9600/16000
ablate_active: 9604/16000
ablate_active: 9608/16000
ablate_active: 9612/16000
ablate_active: 9616/16000
ablate_active: 9620/16000
ablate_active: 9624/16000
ablate_active: 9628/16000
ablate_active: 9632/16000
ablate_active: 9636/16000
ablate_active: 9640/16000
ablate_active: 9644/16000
ablate_active: 9648/16000
ablate_active: 9652/16000
ablate_active: 9656/16000
ablate_active: 9660/16000
ablate_active: 9664/16000
ablate_active: 9668/16000
ablate_active: 9672/16000
ablate_active: 9676/16000
ablate_active: 9680/16000
ablate_active: 9684/16000
ablate_active: 9688/16000
ablate_active: 9692/16000
ablate_active: 9696/16000
ablate_active: 9700/16000
ablate_active: 9704/16000
ablate_active: 9708/16000
ablate_active: 9712/16000
ablate_active: 9716/16000
ablate_active: 9720/16000
ablate_active: 9724/16000
ablate_active: 9728/16000
ablate_active: 9732/16000
ablate_active: 9736/16000
ablate_active: 9740/16000
ablate_active: 9744/16000
ablate_active: 9748/16000
ablate_active: 9752/16000
ablate_active: 9756/16000
ablate_active: 9760/16000
ablate_active: 9764/16000
ablate_active: 9768/16000
ablate_active: 9772/16000
ablate_active: 9776/16000
ablate_active: 9780/16000
ablate_active: 9784/16000
ablate_active: 9788/16000
ablate_active: 9792/16000
ablate_active: 9796/16000
ablate_active: 9800/16000
ablate_active: 9804/16000
ablate_active: 9808/16000
ablate_active: 9812/16000
ablate_active: 9816/16000
ablate_active: 9820/16000
ablate_active: 9824/16000
ablate_active: 9828/16000
ablate_active: 9832/16000
ablate_active: 9836/16000
ablate_active: 9840/16000
ablate_active: 9844/16000
ablate_active: 9848/16000
ablate_active: 9852/16000
ablate_active: 9856/16000
ablate_active: 9860/16000
ablate_active: 9864/16000
ablate_active: 9868/16000
ablate_active: 9872/16000
ablate_active: 9876/16000
ablate_active: 9880/16000
ablate_active: 9884/16000
ablate_active: 9888/16000
ablate_active: 9892/16000
ablate_active: 9896/16000
ablate_active: 9900/16000
ablate_active: 9904/16000
ablate_active: 9908/16000
ablate_active: 9912/16000
ablate_active: 9916/16000
ablate_active: 9920/16000
ablate_active: 9924/16000
ablate_active: 9928/16000
ablate_active: 9932/16000
ablate_active: 9936/16000
ablate_active: 9940/16000
ablate_active: 9944/16000
ablate_active: 9948/16000
ablate_active: 9952/16000
ablate_active: 9956/16000
ablate_active: 9960/16000
ablate_active: 9964/16000
ablate_active: 9968/16000
ablate_active: 9972/16000
ablate_active: 9976/16000
ablate_active: 9980/16000
ablate_active: 9984/16000
ablate_active: 9988/16000
ablate_active: 9992/16000
ablate_active: 9996/16000
ablate_active: 10000/16000
ablate_active: 10004/16000
ablate_active: 10008/16000
ablate_active: 10012/16000
ablate_active: 10016/16000
ablate_active: 10020/16000
ablate_active: 10024/16000
ablate_active: 10028/16000
ablate_active: 10032/16000
ablate_active: 10036/16000
ablate_active: 10040/16000
ablate_active: 10044/16000
ablate_active: 10048/16000
ablate_active: 10052/16000
ablate_active: 10056/16000
ablate_active: 10060/16000
ablate_active: 10064/16000
ablate_active: 10068/16000
ablate_active: 10072/16000
ablate_active: 10076/16000
ablate_active: 10080/16000
ablate_active: 10084/16000
ablate_active: 10088/16000
ablate_active: 10092/16000
ablate_active: 10096/16000
ablate_active: 10100/16000
ablate_active: 10104/16000
ablate_active: 10108/16000
ablate_active: 10112/16000
ablate_active: 10116/16000
ablate_active: 10120/16000
ablate_active: 10124/16000
ablate_active: 10128/16000
ablate_active: 10132/16000
ablate_active: 10136/16000
ablate_active: 10140/16000
ablate_active: 10144/16000
ablate_active: 10148/16000
ablate_active: 10152/16000
ablate_active: 10156/16000
ablate_active: 10160/16000
ablate_active: 10164/16000
ablate_active: 10168/16000

ablate_active: 10172/16000
ablate_active: 10176/16000
ablate_active: 10180/16000
ablate_active: 10184/16000
ablate_active: 10188/16000
ablate_active: 10192/16000
ablate_active: 10196/16000
ablate_active: 10200/16000
ablate_active: 10204/16000
ablate_active: 10208/16000
ablate_active: 10212/16000
ablate_active: 10216/16000
ablate_active: 10220/16000
ablate_active: 10224/16000
ablate_active: 10228/16000
ablate_active: 10232/16000
ablate_active: 10236/16000
ablate_active: 10240/16000
ablate_active: 10244/16000
ablate_active: 10248/16000
ablate_active: 10252/16000
ablate_active: 10256/16000
ablate_active: 10260/16000
ablate_active: 10264/16000
ablate_active: 10268/16000
ablate_active: 10272/16000
ablate_active: 10276/16000
ablate_active: 10280/16000
ablate_active: 10284/16000
ablate_active: 10288/16000
ablate_active: 10292/16000
ablate_active: 10296/16000
ablate_active: 10300/16000
ablate_active: 10304/16000
ablate_active: 10308/16000
ablate_active: 10312/16000
ablate_active: 10316/16000
ablate_active: 10320/16000
ablate_active: 10324/16000
ablate_active: 10328/16000
ablate_active: 10332/16000
ablate_active: 10336/16000
ablate_active: 10340/16000
ablate_active: 10344/16000
ablate_active: 10348/16000
ablate_active: 10352/16000
ablate_active: 10356/16000
ablate_active: 10360/16000
ablate_active: 10364/16000
ablate_active: 10368/16000
ablate_active: 10372/16000
ablate_active: 10376/16000
ablate_active: 10380/16000
ablate_active: 10384/16000
ablate_active: 10388/16000
ablate_active: 10392/16000
ablate_active: 10396/16000
ablate_active: 10400/16000
ablate_active: 10404/16000
ablate_active: 10408/16000
ablate_active: 10412/16000
ablate_active: 10416/16000
ablate_active: 10420/16000
ablate_active: 10424/16000
ablate_active: 10428/16000
ablate_active: 10432/16000
ablate_active: 10436/16000
ablate_active: 10440/16000
ablate_active: 10444/16000
ablate_active: 10448/16000
ablate_active: 10452/16000
ablate_active: 10456/16000
ablate_active: 10460/16000
ablate_active: 10464/16000
ablate_active: 10468/16000
ablate_active: 10472/16000
ablate_active: 10476/16000
ablate_active: 10480/16000
ablate_active: 10484/16000
ablate_active: 10488/16000
ablate_active: 10492/16000
ablate_active: 10496/16000
ablate_active: 10500/16000
ablate_active: 10504/16000
ablate_active: 10508/16000
ablate_active: 10512/16000
ablate_active: 10516/16000
ablate_active: 10520/16000
ablate_active: 10524/16000
ablate_active: 10528/16000
ablate_active: 10532/16000
ablate_active: 10536/16000
ablate_active: 10540/16000
ablate_active: 10544/16000
ablate_active: 10548/16000
ablate_active: 10552/16000
ablate_active: 10556/16000
ablate_active: 10560/16000
ablate_active: 10564/16000
ablate_active: 10568/16000
ablate_active: 10572/16000
ablate_active: 10576/16000
ablate_active: 10580/16000
ablate_active: 10584/16000
ablate_active: 10588/16000
ablate_active: 10592/16000
ablate_active: 10596/16000
ablate_active: 10600/16000
ablate_active: 10604/16000
ablate_active: 10608/16000
ablate_active: 10612/16000
ablate_active: 10616/16000
ablate_active: 10620/16000
ablate_active: 10624/16000
ablate_active: 10628/16000
ablate_active: 10632/16000
ablate_active: 10636/16000
ablate_active: 10640/16000
ablate_active: 10644/16000
ablate_active: 10648/16000
ablate_active: 10652/16000
ablate_active: 10656/16000
ablate_active: 10660/16000
ablate_active: 10664/16000
ablate_active: 10668/16000
ablate_active: 10672/16000
ablate_active: 10676/16000
ablate_active: 10680/16000
ablate_active: 10684/16000
ablate_active: 10688/16000
ablate_active: 10692/16000
ablate_active: 10696/16000
ablate_active: 10700/16000
ablate_active: 10704/16000
ablate_active: 10708/16000
ablate_active: 10712/16000
ablate_active: 10716/16000
ablate_active: 10720/16000
ablate_active: 10724/16000
ablate_active: 10728/16000
ablate_active: 10732/16000
ablate_active: 10736/16000
ablate_active: 10740/16000
ablate_active: 10744/16000
ablate_active: 10748/16000
ablate_active: 10752/16000
ablate_active: 10756/16000
ablate_active: 10760/16000
ablate_active: 10764/16000
ablate_active: 10768/16000
ablate_active: 10772/16000
ablate_active: 10776/16000
ablate_active: 10780/16000
ablate_active: 10784/16000
ablate_active: 10788/16000
ablate_active: 10792/16000
ablate_active: 10796/16000
ablate_active: 10800/16000
ablate_active: 10804/16000
ablate_active: 10808/16000
ablate_active: 10812/16000
ablate_active: 10816/16000
ablate_active: 10820/16000
ablate_active: 10824/16000
ablate_active: 10828/16000
ablate_active: 10832/16000
ablate_active: 10836/16000
ablate_active: 10840/16000
ablate_active: 10844/16000
ablate_active: 10848/16000
ablate_active: 10852/16000
ablate_active: 10856/16000
ablate_active: 10860/16000
ablate_active: 10864/16000
ablate_active: 10868/16000
ablate_active: 10872/16000
ablate_active: 10876/16000
ablate_active: 10880/16000
ablate_active: 10884/16000
ablate_active: 10888/16000
ablate_active: 10892/16000
ablate_active: 10896/16000
ablate_active: 10900/16000
ablate_active: 10904/16000
ablate_active: 10908/16000
ablate_active: 10912/16000
ablate_active: 10916/16000
ablate_active: 10920/16000
ablate_active: 10924/16000
ablate_active: 10928/16000
ablate_active: 10932/16000
ablate_active: 10936/16000
ablate_active: 10940/16000
ablate_active: 10944/16000
ablate_active: 10948/16000
ablate_active: 10952/16000
ablate_active: 10956/16000
ablate_active: 10960/16000
ablate_active: 10964/16000
ablate_active: 10968/16000
ablate_active: 10972/16000
ablate_active: 10976/16000
ablate_active: 10980/16000
ablate_active: 10984/16000
ablate_active: 10988/16000
ablate_active: 10992/16000
ablate_active: 10996/16000
ablate_active: 11000/16000
ablate_active: 11004/16000
ablate_active: 11008/16000
ablate_active: 11012/16000
ablate_active: 11016/16000
ablate_active: 11020/16000
ablate_active: 11024/16000
ablate_active: 11028/16000
ablate_active: 11032/16000
ablate_active: 11036/16000
ablate_active: 11040/16000
ablate_active: 11044/16000
ablate_active: 11048/16000
ablate_active: 11052/16000
ablate_active: 11056/16000
ablate_active: 11060/16000
ablate_active: 11064/16000
ablate_active: 11068/16000
ablate_active: 11072/16000
ablate_active: 11076/16000
ablate_active: 11080/16000
ablate_active: 11084/16000
ablate_active: 11088/16000
ablate_active: 11092/16000
ablate_active: 11096/16000
ablate_active: 11100/16000
ablate_active: 11104/16000
ablate_active: 11108/16000
ablate_active: 11112/16000
ablate_active: 11116/16000
ablate_active: 11120/16000
ablate_active: 11124/16000
ablate_active: 11128/16000
ablate_active: 11132/16000
ablate_active: 11136/16000
ablate_active: 11140/16000
ablate_active: 11144/16000
ablate_active: 11148/16000
ablate_active: 11152/16000
ablate_active: 11156/16000
ablate_active: 11160/16000
ablate_active: 11164/16000
ablate_active: 11168/16000
ablate_active: 11172/16000
ablate_active: 11176/16000
ablate_active: 11180/16000
ablate_active: 11184/16000
ablate_active: 11188/16000
ablate_active: 11192/16000
ablate_active: 11196/16000
ablate_active: 11200/16000
ablate_active: 11204/16000
ablate_active: 11208/16000
ablate_active: 11212/16000
ablate_active: 11216/16000
ablate_active: 11220/16000
ablate_active: 11224/16000
ablate_active: 11228/16000
ablate_active: 11232/16000
ablate_active: 11236/16000
ablate_active: 11240/16000
ablate_active: 11244/16000
ablate_active: 11248/16000
ablate_active: 11252/16000
ablate_active: 11256/16000
ablate_active: 11260/16000
ablate_active: 11264/16000
ablate_active: 11268/16000
ablate_active: 11272/16000
ablate_active: 11276/16000
ablate_active: 11280/16000
ablate_active: 11284/16000
ablate_active: 11288/16000
ablate_active: 11292/16000
ablate_active: 11296/16000
ablate_active: 11300/16000
ablate_active: 11304/16000
ablate_active: 11308/16000
ablate_active: 11312/16000
ablate_active: 11316/16000
ablate_active: 11320/16000
ablate_active: 11324/16000
ablate_active: 11328/16000
ablate_active: 11332/16000
ablate_active: 11336/16000
ablate_active: 11340/16000
ablate_active: 11344/16000
ablate_active: 11348/16000
ablate_active: 11352/16000
ablate_active: 11356/16000
ablate_active: 11360/16000
ablate_active: 11364/16000
ablate_active: 11368/16000
ablate_active: 11372/16000
ablate_active: 11376/16000
ablate_active: 11380/16000
ablate_active: 11384/16000
ablate_active: 11388/16000
ablate_active: 11392/16000
ablate_active: 11396/16000

ablate_active: 11400/16000
ablate_active: 11404/16000
ablate_active: 11408/16000
ablate_active: 11412/16000
ablate_active: 11416/16000
ablate_active: 11420/16000
ablate_active: 11424/16000
ablate_active: 11428/16000
ablate_active: 11432/16000
ablate_active: 11436/16000
ablate_active: 11440/16000
ablate_active: 11444/16000
ablate_active: 11448/16000
ablate_active: 11452/16000
ablate_active: 11456/16000
ablate_active: 11460/16000
ablate_active: 11464/16000
ablate_active: 11468/16000
ablate_active: 11472/16000
ablate_active: 11476/16000
ablate_active: 11480/16000
ablate_active: 11484/16000
ablate_active: 11488/16000
ablate_active: 11492/16000
ablate_active: 11496/16000
ablate_active: 11500/16000
ablate_active: 11504/16000
ablate_active: 11508/16000
ablate_active: 11512/16000
ablate_active: 11516/16000
ablate_active: 11520/16000
ablate_active: 11524/16000
ablate_active: 11528/16000
ablate_active: 11532/16000
ablate_active: 11536/16000
ablate_active: 11540/16000
ablate_active: 11544/16000
ablate_active: 11548/16000
ablate_active: 11552/16000
ablate_active: 11556/16000
ablate_active: 11560/16000
ablate_active: 11564/16000
ablate_active: 11568/16000
ablate_active: 11572/16000
ablate_active: 11576/16000
ablate_active: 11580/16000
ablate_active: 11584/16000
ablate_active: 11588/16000
ablate_active: 11592/16000
ablate_active: 11596/16000
ablate_active: 11600/16000
ablate_active: 11604/16000
ablate_active: 11608/16000
ablate_active: 11612/16000
ablate_active: 11616/16000
ablate_active: 11620/16000
ablate_active: 11624/16000
ablate_active: 11628/16000
ablate_active: 11632/16000
ablate_active: 11636/16000
ablate_active: 11640/16000
ablate_active: 11644/16000
ablate_active: 11648/16000
ablate_active: 11652/16000
ablate_active: 11656/16000
ablate_active: 11660/16000
ablate_active: 11664/16000
ablate_active: 11668/16000
ablate_active: 11672/16000
ablate_active: 11676/16000
ablate_active: 11680/16000
ablate_active: 11684/16000
ablate_active: 11688/16000
ablate_active: 11692/16000
ablate_active: 11696/16000
ablate_active: 11700/16000
ablate_active: 11704/16000
ablate_active: 11708/16000
ablate_active: 11712/16000
ablate_active: 11716/16000
ablate_active: 11720/16000
ablate_active: 11724/16000
ablate_active: 11728/16000
ablate_active: 11732/16000
ablate_active: 11736/16000
ablate_active: 11740/16000
ablate_active: 11744/16000
ablate_active: 11748/16000
ablate_active: 11752/16000
ablate_active: 11756/16000
ablate_active: 11760/16000
ablate_active: 11764/16000
ablate_active: 11768/16000
ablate_active: 11772/16000
ablate_active: 11776/16000
ablate_active: 11780/16000
ablate_active: 11784/16000
ablate_active: 11788/16000
ablate_active: 11792/16000
ablate_active: 11796/16000
ablate_active: 11800/16000
ablate_active: 11804/16000
ablate_active: 11808/16000
ablate_active: 11812/16000
ablate_active: 11816/16000
ablate_active: 11820/16000
ablate_active: 11824/16000
ablate_active: 11828/16000
ablate_active: 11832/16000
ablate_active: 11836/16000
ablate_active: 11840/16000
ablate_active: 11844/16000
ablate_active: 11848/16000
ablate_active: 11852/16000
ablate_active: 11856/16000
ablate_active: 11860/16000
ablate_active: 11864/16000
ablate_active: 11868/16000
ablate_active: 11872/16000
ablate_active: 11876/16000
ablate_active: 11880/16000
ablate_active: 11884/16000
ablate_active: 11888/16000
ablate_active: 11892/16000
ablate_active: 11896/16000
ablate_active: 11900/16000
ablate_active: 11904/16000
ablate_active: 11908/16000
ablate_active: 11912/16000
ablate_active: 11916/16000
ablate_active: 11920/16000
ablate_active: 11924/16000
ablate_active: 11928/16000
ablate_active: 11932/16000
ablate_active: 11936/16000
ablate_active: 11940/16000
ablate_active: 11944/16000
ablate_active: 11948/16000
ablate_active: 11952/16000
ablate_active: 11956/16000
ablate_active: 11960/16000
ablate_active: 11964/16000
ablate_active: 11968/16000
ablate_active: 11972/16000
ablate_active: 11976/16000
ablate_active: 11980/16000
ablate_active: 11984/16000
ablate_active: 11988/16000
ablate_active: 11992/16000
ablate_active: 11996/16000
ablate_active: 12000/16000
ablate_active: 12004/16000
ablate_active: 12008/16000
ablate_active: 12012/16000
ablate_active: 12016/16000
ablate_active: 12020/16000
ablate_active: 12024/16000
ablate_active: 12028/16000
ablate_active: 12032/16000
ablate_active: 12036/16000
ablate_active: 12040/16000
ablate_active: 12044/16000
ablate_active: 12048/16000
ablate_active: 12052/16000
ablate_active: 12056/16000
ablate_active: 12060/16000
ablate_active: 12064/16000
ablate_active: 12068/16000
ablate_active: 12072/16000
ablate_active: 12076/16000
ablate_active: 12080/16000
ablate_active: 12084/16000
ablate_active: 12088/16000
ablate_active: 12092/16000
ablate_active: 12096/16000
ablate_active: 12100/16000
ablate_active: 12104/16000
ablate_active: 12108/16000
ablate_active: 12112/16000
ablate_active: 12116/16000
ablate_active: 12120/16000
ablate_active: 12124/16000
ablate_active: 12128/16000
ablate_active: 12132/16000
ablate_active: 12136/16000
ablate_active: 12140/16000
ablate_active: 12144/16000
ablate_active: 12148/16000
ablate_active: 12152/16000
ablate_active: 12156/16000
ablate_active: 12160/16000
ablate_active: 12164/16000
ablate_active: 12168/16000
ablate_active: 12172/16000
ablate_active: 12176/16000
ablate_active: 12180/16000
ablate_active: 12184/16000
ablate_active: 12188/16000
ablate_active: 12192/16000
ablate_active: 12196/16000
ablate_active: 12200/16000
ablate_active: 12204/16000
ablate_active: 12208/16000
ablate_active: 12212/16000
ablate_active: 12216/16000
ablate_active: 12220/16000
ablate_active: 12224/16000
ablate_active: 12228/16000
ablate_active: 12232/16000
ablate_active: 12236/16000
ablate_active: 12240/16000
ablate_active: 12244/16000
ablate_active: 12248/16000
ablate_active: 12252/16000
ablate_active: 12256/16000
ablate_active: 12260/16000
ablate_active: 12264/16000
ablate_active: 12268/16000
ablate_active: 12272/16000
ablate_active: 12276/16000
ablate_active: 12280/16000
ablate_active: 12284/16000
ablate_active: 12288/16000
ablate_active: 12292/16000
ablate_active: 12296/16000
ablate_active: 12300/16000
ablate_active: 12304/16000
ablate_active: 12308/16000
ablate_active: 12312/16000
ablate_active: 12316/16000
ablate_active: 12320/16000
ablate_active: 12324/16000
ablate_active: 12328/16000
ablate_active: 12332/16000
ablate_active: 12336/16000
ablate_active: 12340/16000
ablate_active: 12344/16000
ablate_active: 12348/16000
ablate_active: 12352/16000
ablate_active: 12356/16000
ablate_active: 12360/16000
ablate_active: 12364/16000
ablate_active: 12368/16000
ablate_active: 12372/16000
ablate_active: 12376/16000
ablate_active: 12380/16000
ablate_active: 12384/16000
ablate_active: 12388/16000
ablate_active: 12392/16000
ablate_active: 12396/16000
ablate_active: 12400/16000
ablate_active: 12404/16000
ablate_active: 12408/16000
ablate_active: 12412/16000
ablate_active: 12416/16000
ablate_active: 12420/16000
ablate_active: 12424/16000
ablate_active: 12428/16000
ablate_active: 12432/16000
ablate_active: 12436/16000
ablate_active: 12440/16000
ablate_active: 12444/16000
ablate_active: 12448/16000
ablate_active: 12452/16000
ablate_active: 12456/16000
ablate_active: 12460/16000
ablate_active: 12464/16000
ablate_active: 12468/16000
ablate_active: 12472/16000
ablate_active: 12476/16000
ablate_active: 12480/16000
ablate_active: 12484/16000
ablate_active: 12488/16000
ablate_active: 12492/16000
ablate_active: 12496/16000
ablate_active: 12500/16000
ablate_active: 12504/16000
ablate_active: 12508/16000
ablate_active: 12512/16000
ablate_active: 12516/16000
ablate_active: 12520/16000
ablate_active: 12524/16000
ablate_active: 12528/16000
ablate_active: 12532/16000
ablate_active: 12536/16000
ablate_active: 12540/16000
ablate_active: 12544/16000
ablate_active: 12548/16000
ablate_active: 12552/16000
ablate_active: 12556/16000
ablate_active: 12560/16000
ablate_active: 12564/16000
ablate_active: 12568/16000
ablate_active: 12572/16000
ablate_active: 12576/16000
ablate_active: 12580/16000
ablate_active: 12584/16000
ablate_active: 12588/16000
ablate_active: 12592/16000
ablate_active: 12596/16000
ablate_active: 12600/16000
ablate_active: 12604/16000
ablate_active: 12608/16000
ablate_active: 12612/16000
ablate_active: 12616/16000
ablate_active: 12620/16000
ablate_active: 12624/16000

ablate_active: 12628/16000
ablate_active: 12632/16000
ablate_active: 12636/16000
ablate_active: 12640/16000
ablate_active: 12644/16000
ablate_active: 12648/16000
ablate_active: 12652/16000
ablate_active: 12656/16000
ablate_active: 12660/16000
ablate_active: 12664/16000
ablate_active: 12668/16000
ablate_active: 12672/16000
ablate_active: 12676/16000
ablate_active: 12680/16000
ablate_active: 12684/16000
ablate_active: 12688/16000
ablate_active: 12692/16000
ablate_active: 12696/16000
ablate_active: 12700/16000
ablate_active: 12704/16000
ablate_active: 12708/16000
ablate_active: 12712/16000
ablate_active: 12716/16000
ablate_active: 12720/16000
ablate_active: 12724/16000
ablate_active: 12728/16000
ablate_active: 12732/16000
ablate_active: 12736/16000
ablate_active: 12740/16000
ablate_active: 12744/16000
ablate_active: 12748/16000
ablate_active: 12752/16000
ablate_active: 12756/16000
ablate_active: 12760/16000
ablate_active: 12764/16000
ablate_active: 12768/16000
ablate_active: 12772/16000
ablate_active: 12776/16000
ablate_active: 12780/16000
ablate_active: 12784/16000
ablate_active: 12788/16000
ablate_active: 12792/16000
ablate_active: 12796/16000
ablate_active: 12800/16000
ablate_active: 12804/16000
ablate_active: 12808/16000
ablate_active: 12812/16000
ablate_active: 12816/16000
ablate_active: 12820/16000
ablate_active: 12824/16000
ablate_active: 12828/16000
ablate_active: 12832/16000
ablate_active: 12836/16000
ablate_active: 12840/16000
ablate_active: 12844/16000
ablate_active: 12848/16000
ablate_active: 12852/16000
ablate_active: 12856/16000
ablate_active: 12860/16000
ablate_active: 12864/16000
ablate_active: 12868/16000
ablate_active: 12872/16000
ablate_active: 12876/16000
ablate_active: 12880/16000
ablate_active: 12884/16000
ablate_active: 12888/16000
ablate_active: 12892/16000
ablate_active: 12896/16000
ablate_active: 12900/16000
ablate_active: 12904/16000
ablate_active: 12908/16000
ablate_active: 12912/16000
ablate_active: 12916/16000
ablate_active: 12920/16000
ablate_active: 12924/16000
ablate_active: 12928/16000
ablate_active: 12932/16000
ablate_active: 12936/16000
ablate_active: 12940/16000
ablate_active: 12944/16000
ablate_active: 12948/16000
ablate_active: 12952/16000
ablate_active: 12956/16000
ablate_active: 12960/16000
ablate_active: 12964/16000
ablate_active: 12968/16000
ablate_active: 12972/16000
ablate_active: 12976/16000
ablate_active: 12980/16000
ablate_active: 12984/16000
ablate_active: 12988/16000
ablate_active: 12992/16000
ablate_active: 12996/16000
ablate_active: 13000/16000
ablate_active: 13004/16000
ablate_active: 13008/16000
ablate_active: 13012/16000
ablate_active: 13016/16000
ablate_active: 13020/16000
ablate_active: 13024/16000
ablate_active: 13028/16000
ablate_active: 13032/16000
ablate_active: 13036/16000
ablate_active: 13040/16000
ablate_active: 13044/16000
ablate_active: 13048/16000
ablate_active: 13052/16000
ablate_active: 13056/16000
ablate_active: 13060/16000
ablate_active: 13064/16000
ablate_active: 13068/16000
ablate_active: 13072/16000
ablate_active: 13076/16000
ablate_active: 13080/16000
ablate_active: 13084/16000
ablate_active: 13088/16000
ablate_active: 13092/16000
ablate_active: 13096/16000
ablate_active: 13100/16000
ablate_active: 13104/16000
ablate_active: 13108/16000
ablate_active: 13112/16000
ablate_active: 13116/16000
ablate_active: 13120/16000
ablate_active: 13124/16000
ablate_active: 13128/16000
ablate_active: 13132/16000
ablate_active: 13136/16000
ablate_active: 13140/16000
ablate_active: 13144/16000
ablate_active: 13148/16000
ablate_active: 13152/16000
ablate_active: 13156/16000
ablate_active: 13160/16000
ablate_active: 13164/16000
ablate_active: 13168/16000
ablate_active: 13172/16000
ablate_active: 13176/16000
ablate_active: 13180/16000
ablate_active: 13184/16000
ablate_active: 13188/16000
ablate_active: 13192/16000
ablate_active: 13196/16000
ablate_active: 13200/16000
ablate_active: 13204/16000
ablate_active: 13208/16000
ablate_active: 13212/16000
ablate_active: 13216/16000
ablate_active: 13220/16000
ablate_active: 13224/16000
ablate_active: 13228/16000
ablate_active: 13232/16000
ablate_active: 13236/16000
ablate_active: 13240/16000
ablate_active: 13244/16000
ablate_active: 13248/16000
ablate_active: 13252/16000
ablate_active: 13256/16000
ablate_active: 13260/16000
ablate_active: 13264/16000
ablate_active: 13268/16000
ablate_active: 13272/16000
ablate_active: 13276/16000
ablate_active: 13280/16000
ablate_active: 13284/16000
ablate_active: 13288/16000
ablate_active: 13292/16000
ablate_active: 13296/16000
ablate_active: 13300/16000
ablate_active: 13304/16000
ablate_active: 13308/16000
ablate_active: 13312/16000
ablate_active: 13316/16000
ablate_active: 13320/16000
ablate_active: 13324/16000
ablate_active: 13328/16000
ablate_active: 13332/16000
ablate_active: 13336/16000
ablate_active: 13340/16000
ablate_active: 13344/16000
ablate_active: 13348/16000
ablate_active: 13352/16000
ablate_active: 13356/16000
ablate_active: 13360/16000
ablate_active: 13364/16000
ablate_active: 13368/16000
ablate_active: 13372/16000
ablate_active: 13376/16000
ablate_active: 13380/16000
ablate_active: 13384/16000
ablate_active: 13388/16000
ablate_active: 13392/16000
ablate_active: 13396/16000
ablate_active: 13400/16000
ablate_active: 13404/16000
ablate_active: 13408/16000
ablate_active: 13412/16000
ablate_active: 13416/16000
ablate_active: 13420/16000
ablate_active: 13424/16000
ablate_active: 13428/16000
ablate_active: 13432/16000
ablate_active: 13436/16000
ablate_active: 13440/16000
ablate_active: 13444/16000
ablate_active: 13448/16000
ablate_active: 13452/16000
ablate_active: 13456/16000
ablate_active: 13460/16000
ablate_active: 13464/16000
ablate_active: 13468/16000
ablate_active: 13472/16000
ablate_active: 13476/16000
ablate_active: 13480/16000
ablate_active: 13484/16000
ablate_active: 13488/16000
ablate_active: 13492/16000
ablate_active: 13496/16000
ablate_active: 13500/16000
ablate_active: 13504/16000
ablate_active: 13508/16000
ablate_active: 13512/16000
ablate_active: 13516/16000
ablate_active: 13520/16000
ablate_active: 13524/16000
ablate_active: 13528/16000
ablate_active: 13532/16000
ablate_active: 13536/16000
ablate_active: 13540/16000
ablate_active: 13544/16000
ablate_active: 13548/16000
ablate_active: 13552/16000
ablate_active: 13556/16000
ablate_active: 13560/16000
ablate_active: 13564/16000
ablate_active: 13568/16000
ablate_active: 13572/16000
ablate_active: 13576/16000
ablate_active: 13580/16000
ablate_active: 13584/16000
ablate_active: 13588/16000
ablate_active: 13592/16000
ablate_active: 13596/16000
ablate_active: 13600/16000
ablate_active: 13604/16000
ablate_active: 13608/16000
ablate_active: 13612/16000
ablate_active: 13616/16000
ablate_active: 13620/16000
ablate_active: 13624/16000
ablate_active: 13628/16000
ablate_active: 13632/16000
ablate_active: 13636/16000
ablate_active: 13640/16000
ablate_active: 13644/16000
ablate_active: 13648/16000
ablate_active: 13652/16000
ablate_active: 13656/16000
ablate_active: 13660/16000
ablate_active: 13664/16000
ablate_active: 13668/16000
ablate_active: 13672/16000
ablate_active: 13676/16000
ablate_active: 13680/16000
ablate_active: 13684/16000
ablate_active: 13688/16000
ablate_active: 13692/16000
ablate_active: 13696/16000
ablate_active: 13700/16000
ablate_active: 13704/16000
ablate_active: 13708/16000
ablate_active: 13712/16000
ablate_active: 13716/16000
ablate_active: 13720/16000
ablate_active: 13724/16000
ablate_active: 13728/16000
ablate_active: 13732/16000
ablate_active: 13736/16000
ablate_active: 13740/16000
ablate_active: 13744/16000
ablate_active: 13748/16000
ablate_active: 13752/16000
ablate_active: 13756/16000
ablate_active: 13760/16000
ablate_active: 13764/16000
ablate_active: 13768/16000
ablate_active: 13772/16000
ablate_active: 13776/16000
ablate_active: 13780/16000
ablate_active: 13784/16000
ablate_active: 13788/16000
ablate_active: 13792/16000
ablate_active: 13796/16000
ablate_active: 13800/16000
ablate_active: 13804/16000
ablate_active: 13808/16000
ablate_active: 13812/16000
ablate_active: 13816/16000
ablate_active: 13820/16000
ablate_active: 13824/16000
ablate_active: 13828/16000
ablate_active: 13832/16000
ablate_active: 13836/16000
ablate_active: 13840/16000
ablate_active: 13844/16000
ablate_active: 13848/16000

ablate_active: 13852/16000
ablate_active: 13856/16000
ablate_active: 13860/16000
ablate_active: 13864/16000
ablate_active: 13868/16000
ablate_active: 13872/16000
ablate_active: 13876/16000
ablate_active: 13880/16000
ablate_active: 13884/16000
ablate_active: 13888/16000
ablate_active: 13892/16000
ablate_active: 13896/16000
ablate_active: 13900/16000
ablate_active: 13904/16000
ablate_active: 13908/16000
ablate_active: 13912/16000
ablate_active: 13916/16000
ablate_active: 13920/16000
ablate_active: 13924/16000
ablate_active: 13928/16000
ablate_active: 13932/16000
ablate_active: 13936/16000
ablate_active: 13940/16000
ablate_active: 13944/16000
ablate_active: 13948/16000
ablate_active: 13952/16000
ablate_active: 13956/16000
ablate_active: 13960/16000
ablate_active: 13964/16000
ablate_active: 13968/16000
ablate_active: 13972/16000
ablate_active: 13976/16000
ablate_active: 13980/16000
ablate_active: 13984/16000
ablate_active: 13988/16000
ablate_active: 13992/16000
ablate_active: 13996/16000
ablate_active: 14000/16000
ablate_active: 14004/16000
ablate_active: 14008/16000
ablate_active: 14012/16000
ablate_active: 14016/16000
ablate_active: 14020/16000
ablate_active: 14024/16000
ablate_active: 14028/16000
ablate_active: 14032/16000
ablate_active: 14036/16000
ablate_active: 14040/16000
ablate_active: 14044/16000
ablate_active: 14048/16000
ablate_active: 14052/16000
ablate_active: 14056/16000
ablate_active: 14060/16000
ablate_active: 14064/16000
ablate_active: 14068/16000
ablate_active: 14072/16000
ablate_active: 14076/16000
ablate_active: 14080/16000
ablate_active: 14084/16000
ablate_active: 14088/16000
ablate_active: 14092/16000
ablate_active: 14096/16000
ablate_active: 14100/16000
ablate_active: 14104/16000
ablate_active: 14108/16000
ablate_active: 14112/16000
ablate_active: 14116/16000
ablate_active: 14120/16000
ablate_active: 14124/16000
ablate_active: 14128/16000
ablate_active: 14132/16000
ablate_active: 14136/16000
ablate_active: 14140/16000
ablate_active: 14144/16000
ablate_active: 14148/16000
ablate_active: 14152/16000
ablate_active: 14156/16000
ablate_active: 14160/16000
ablate_active: 14164/16000
ablate_active: 14168/16000
ablate_active: 14172/16000
ablate_active: 14176/16000
ablate_active: 14180/16000
ablate_active: 14184/16000
ablate_active: 14188/16000
ablate_active: 14192/16000
ablate_active: 14196/16000
ablate_active: 14200/16000
ablate_active: 14204/16000
ablate_active: 14208/16000
ablate_active: 14212/16000
ablate_active: 14216/16000
ablate_active: 14220/16000
ablate_active: 14224/16000
ablate_active: 14228/16000
ablate_active: 14232/16000
ablate_active: 14236/16000
ablate_active: 14240/16000
ablate_active: 14244/16000
ablate_active: 14248/16000
ablate_active: 14252/16000
ablate_active: 14256/16000
ablate_active: 14260/16000
ablate_active: 14264/16000
ablate_active: 14268/16000
ablate_active: 14272/16000
ablate_active: 14276/16000
ablate_active: 14280/16000
ablate_active: 14284/16000
ablate_active: 14288/16000
ablate_active: 14292/16000
ablate_active: 14296/16000
ablate_active: 14300/16000
ablate_active: 14304/16000
ablate_active: 14308/16000
ablate_active: 14312/16000
ablate_active: 14316/16000
ablate_active: 14320/16000
ablate_active: 14324/16000
ablate_active: 14328/16000
ablate_active: 14332/16000
ablate_active: 14336/16000
ablate_active: 14340/16000
ablate_active: 14344/16000
ablate_active: 14348/16000
ablate_active: 14352/16000
ablate_active: 14356/16000
ablate_active: 14360/16000
ablate_active: 14364/16000
ablate_active: 14368/16000
ablate_active: 14372/16000
ablate_active: 14376/16000
ablate_active: 14380/16000
ablate_active: 14384/16000
ablate_active: 14388/16000
ablate_active: 14392/16000
ablate_active: 14396/16000
ablate_active: 14400/16000
ablate_active: 14404/16000
ablate_active: 14408/16000
ablate_active: 14412/16000
ablate_active: 14416/16000
ablate_active: 14420/16000
ablate_active: 14424/16000
ablate_active: 14428/16000
ablate_active: 14432/16000
ablate_active: 14436/16000
ablate_active: 14440/16000
ablate_active: 14444/16000
ablate_active: 14448/16000
ablate_active: 14452/16000
ablate_active: 14456/16000
ablate_active: 14460/16000
ablate_active: 14464/16000
ablate_active: 14468/16000
ablate_active: 14472/16000
ablate_active: 14476/16000
ablate_active: 14480/16000
ablate_active: 14484/16000
ablate_active: 14488/16000
ablate_active: 14492/16000
ablate_active: 14496/16000
ablate_active: 14500/16000
ablate_active: 14504/16000
ablate_active: 14508/16000
ablate_active: 14512/16000
ablate_active: 14516/16000
ablate_active: 14520/16000
ablate_active: 14524/16000
ablate_active: 14528/16000
ablate_active: 14532/16000
ablate_active: 14536/16000
ablate_active: 14540/16000
ablate_active: 14544/16000
ablate_active: 14548/16000
ablate_active: 14552/16000
ablate_active: 14556/16000
ablate_active: 14560/16000
ablate_active: 14564/16000
ablate_active: 14568/16000
ablate_active: 14572/16000
ablate_active: 14576/16000
ablate_active: 14580/16000
ablate_active: 14584/16000
ablate_active: 14588/16000
ablate_active: 14592/16000
ablate_active: 14596/16000
ablate_active: 14600/16000
ablate_active: 14604/16000
ablate_active: 14608/16000
ablate_active: 14612/16000
ablate_active: 14616/16000
ablate_active: 14620/16000
ablate_active: 14624/16000
ablate_active: 14628/16000
ablate_active: 14632/16000
ablate_active: 14636/16000
ablate_active: 14640/16000
ablate_active: 14644/16000
ablate_active: 14648/16000
ablate_active: 14652/16000
ablate_active: 14656/16000
ablate_active: 14660/16000
ablate_active: 14664/16000
ablate_active: 14668/16000
ablate_active: 14672/16000
ablate_active: 14676/16000
ablate_active: 14680/16000
ablate_active: 14684/16000
ablate_active: 14688/16000
ablate_active: 14692/16000
ablate_active: 14696/16000
ablate_active: 14700/16000
ablate_active: 14704/16000
ablate_active: 14708/16000
ablate_active: 14712/16000
ablate_active: 14716/16000
ablate_active: 14720/16000
ablate_active: 14724/16000
ablate_active: 14728/16000
ablate_active: 14732/16000
ablate_active: 14736/16000
ablate_active: 14740/16000
ablate_active: 14744/16000
ablate_active: 14748/16000
ablate_active: 14752/16000
ablate_active: 14756/16000
ablate_active: 14760/16000
ablate_active: 14764/16000
ablate_active: 14768/16000
ablate_active: 14772/16000
ablate_active: 14776/16000
ablate_active: 14780/16000
ablate_active: 14784/16000
ablate_active: 14788/16000
ablate_active: 14792/16000
ablate_active: 14796/16000
ablate_active: 14800/16000
ablate_active: 14804/16000
ablate_active: 14808/16000
ablate_active: 14812/16000
ablate_active: 14816/16000
ablate_active: 14820/16000
ablate_active: 14824/16000
ablate_active: 14828/16000
ablate_active: 14832/16000
ablate_active: 14836/16000
ablate_active: 14840/16000
ablate_active: 14844/16000
ablate_active: 14848/16000
ablate_active: 14852/16000
ablate_active: 14856/16000
ablate_active: 14860/16000
ablate_active: 14864/16000
ablate_active: 14868/16000
ablate_active: 14872/16000
ablate_active: 14876/16000
ablate_active: 14880/16000
ablate_active: 14884/16000
ablate_active: 14888/16000
ablate_active: 14892/16000
ablate_active: 14896/16000
ablate_active: 14900/16000
ablate_active: 14904/16000
ablate_active: 14908/16000
ablate_active: 14912/16000
ablate_active: 14916/16000
ablate_active: 14920/16000
ablate_active: 14924/16000
ablate_active: 14928/16000
ablate_active: 14932/16000
ablate_active: 14936/16000
ablate_active: 14940/16000
ablate_active: 14944/16000
ablate_active: 14948/16000
ablate_active: 14952/16000
ablate_active: 14956/16000
ablate_active: 14960/16000
ablate_active: 14964/16000
ablate_active: 14968/16000
ablate_active: 14972/16000
ablate_active: 14976/16000
ablate_active: 14980/16000
ablate_active: 14984/16000
ablate_active: 14988/16000
ablate_active: 14992/16000
ablate_active: 14996/16000
ablate_active: 15000/16000
ablate_active: 15004/16000
ablate_active: 15008/16000
ablate_active: 15012/16000
ablate_active: 15016/16000
ablate_active: 15020/16000
ablate_active: 15024/16000
ablate_active: 15028/16000
ablate_active: 15032/16000
ablate_active: 15036/16000
ablate_active: 15040/16000
ablate_active: 15044/16000
ablate_active: 15048/16000
ablate_active: 15052/16000
ablate_active: 15056/16000
ablate_active: 15060/16000
ablate_active: 15064/16000

ablate_active: 15068/16000
ablate_active: 15072/16000
ablate_active: 15076/16000
ablate_active: 15080/16000
ablate_active: 15084/16000
ablate_active: 15088/16000
ablate_active: 15092/16000
ablate_active: 15096/16000
ablate_active: 15100/16000
ablate_active: 15104/16000
ablate_active: 15108/16000
ablate_active: 15112/16000
ablate_active: 15116/16000
ablate_active: 15120/16000
ablate_active: 15124/16000
ablate_active: 15128/16000
ablate_active: 15132/16000
ablate_active: 15136/16000
ablate_active: 15140/16000
ablate_active: 15144/16000
ablate_active: 15148/16000
ablate_active: 15152/16000
ablate_active: 15156/16000
ablate_active: 15160/16000
ablate_active: 15164/16000
ablate_active: 15168/16000
ablate_active: 15172/16000
ablate_active: 15176/16000
ablate_active: 15180/16000
ablate_active: 15184/16000
ablate_active: 15188/16000
ablate_active: 15192/16000
ablate_active: 15196/16000
ablate_active: 15200/16000
ablate_active: 15204/16000
ablate_active: 15208/16000
ablate_active: 15212/16000
ablate_active: 15216/16000
ablate_active: 15220/16000
ablate_active: 15224/16000
ablate_active: 15228/16000
ablate_active: 15232/16000
ablate_active: 15236/16000
ablate_active: 15240/16000
ablate_active: 15244/16000
ablate_active: 15248/16000
ablate_active: 15252/16000
ablate_active: 15256/16000
ablate_active: 15260/16000
ablate_active: 15264/16000
ablate_active: 15268/16000
ablate_active: 15272/16000
ablate_active: 15276/16000
ablate_active: 15280/16000
ablate_active: 15284/16000
ablate_active: 15288/16000
ablate_active: 15292/16000
ablate_active: 15296/16000
ablate_active: 15300/16000
ablate_active: 15304/16000
ablate_active: 15308/16000
ablate_active: 15312/16000
ablate_active: 15316/16000
ablate_active: 15320/16000
ablate_active: 15324/16000
ablate_active: 15328/16000
ablate_active: 15332/16000
ablate_active: 15336/16000
ablate_active: 15340/16000
ablate_active: 15344/16000
ablate_active: 15348/16000
ablate_active: 15352/16000
ablate_active: 15356/16000
ablate_active: 15360/16000
ablate_active: 15364/16000
ablate_active: 15368/16000
ablate_active: 15372/16000
ablate_active: 15376/16000
ablate_active: 15380/16000
ablate_active: 15384/16000
ablate_active: 15388/16000
ablate_active: 15392/16000
ablate_active: 15396/16000
ablate_active: 15400/16000
ablate_active: 15404/16000
ablate_active: 15408/16000
ablate_active: 15412/16000
ablate_active: 15416/16000
ablate_active: 15420/16000
ablate_active: 15424/16000
ablate_active: 15428/16000
ablate_active: 15432/16000
ablate_active: 15436/16000
ablate_active: 15440/16000
ablate_active: 15444/16000
ablate_active: 15448/16000
ablate_active: 15452/16000
ablate_active: 15456/16000
ablate_active: 15460/16000
ablate_active: 15464/16000
ablate_active: 15468/16000
ablate_active: 15472/16000
ablate_active: 15476/16000
ablate_active: 15480/16000
ablate_active: 15484/16000
ablate_active: 15488/16000
ablate_active: 15492/16000
ablate_active: 15496/16000
ablate_active: 15500/16000
ablate_active: 15504/16000
ablate_active: 15508/16000
ablate_active: 15512/16000
ablate_active: 15516/16000
ablate_active: 15520/16000
ablate_active: 15524/16000
ablate_active: 15528/16000
ablate_active: 15532/16000
ablate_active: 15536/16000
ablate_active: 15540/16000
ablate_active: 15544/16000
ablate_active: 15548/16000
ablate_active: 15552/16000
ablate_active: 15556/16000
ablate_active: 15560/16000
ablate_active: 15564/16000
ablate_active: 15568/16000
ablate_active: 15572/16000
ablate_active: 15576/16000
ablate_active: 15580/16000
ablate_active: 15584/16000
ablate_active: 15588/16000
ablate_active: 15592/16000
ablate_active: 15596/16000
ablate_active: 15600/16000
ablate_active: 15604/16000
ablate_active: 15608/16000
ablate_active: 15612/16000
ablate_active: 15616/16000
ablate_active: 15620/16000
ablate_active: 15624/16000
ablate_active: 15628/16000
ablate_active: 15632/16000
ablate_active: 15636/16000
ablate_active: 15640/16000
ablate_active: 15644/16000
ablate_active: 15648/16000
ablate_active: 15652/16000
ablate_active: 15656/16000
ablate_active: 15660/16000
ablate_active: 15664/16000
ablate_active: 15668/16000
ablate_active: 15672/16000
ablate_active: 15676/16000
ablate_active: 15680/16000
ablate_active: 15684/16000
ablate_active: 15688/16000
ablate_active: 15692/16000
ablate_active: 15696/16000
ablate_active: 15700/16000
ablate_active: 15704/16000
ablate_active: 15708/16000
ablate_active: 15712/16000
ablate_active: 15716/16000
ablate_active: 15720/16000
ablate_active: 15724/16000
ablate_active: 15728/16000
ablate_active: 15732/16000
ablate_active: 15736/16000
ablate_active: 15740/16000
ablate_active: 15744/16000
ablate_active: 15748/16000
ablate_active: 15752/16000
ablate_active: 15756/16000
ablate_active: 15760/16000
ablate_active: 15764/16000
ablate_active: 15768/16000
ablate_active: 15772/16000
ablate_active: 15776/16000
ablate_active: 15780/16000
ablate_active: 15784/16000
ablate_active: 15788/16000
ablate_active: 15792/16000
ablate_active: 15796/16000
ablate_active: 15800/16000
ablate_active: 15804/16000
ablate_active: 15808/16000
ablate_active: 15812/16000
ablate_active: 15816/16000
ablate_active: 15820/16000
ablate_active: 15824/16000
ablate_active: 15828/16000
ablate_active: 15832/16000
ablate_active: 15836/16000
ablate_active: 15840/16000
ablate_active: 15844/16000
ablate_active: 15848/16000
ablate_active: 15852/16000
ablate_active: 15856/16000
ablate_active: 15860/16000
ablate_active: 15864/16000
ablate_active: 15868/16000
ablate_active: 15872/16000
ablate_active: 15876/16000
ablate_active: 15880/16000
ablate_active: 15884/16000
ablate_active: 15888/16000
ablate_active: 15892/16000
ablate_active: 15896/16000
ablate_active: 15900/16000
ablate_active: 15904/16000
ablate_active: 15908/16000
ablate_active: 15912/16000
ablate_active: 15916/16000
ablate_active: 15920/16000
ablate_active: 15924/16000
ablate_active: 15928/16000
ablate_active: 15932/16000
ablate_active: 15936/16000
ablate_active: 15940/16000
ablate_active: 15944/16000
ablate_active: 15948/16000
ablate_active: 15952/16000
ablate_active: 15956/16000
ablate_active: 15960/16000
ablate_active: 15964/16000
ablate_active: 15968/16000
ablate_active: 15972/16000
ablate_active: 15976/16000
ablate_active: 15980/16000
ablate_active: 15984/16000
ablate_active: 15988/16000
ablate_active: 15992/16000
ablate_active: 15996/16000
ablate_active: 16000/16000
amplify: 4/16000
amplify: 8/16000
amplify: 12/16000
amplify: 16/16000
amplify: 20/16000
amplify: 24/16000
amplify: 28/16000
amplify: 32/16000
amplify: 36/16000
amplify: 40/16000
amplify: 44/16000
amplify: 48/16000
amplify: 52/16000
amplify: 56/16000
amplify: 60/16000
amplify: 64/16000
amplify: 68/16000
amplify: 72/16000
amplify: 76/16000
amplify: 80/16000
amplify: 84/16000
amplify: 88/16000
amplify: 92/16000
amplify: 96/16000
amplify: 100/16000
amplify: 104/16000
amplify: 108/16000
amplify: 112/16000
amplify: 116/16000
amplify: 120/16000
amplify: 124/16000
amplify: 128/16000
amplify: 132/16000
amplify: 136/16000
amplify: 140/16000
amplify: 144/16000
amplify: 148/16000
amplify: 152/16000
amplify: 156/16000
amplify: 160/16000
amplify: 164/16000
amplify: 168/16000
amplify: 172/16000
amplify: 176/16000
amplify: 180/16000
amplify: 184/16000
amplify: 188/16000
amplify: 192/16000
amplify: 196/16000
amplify: 200/16000
amplify: 204/16000
amplify: 208/16000
amplify: 212/16000
amplify: 216/16000
amplify: 220/16000
amplify: 224/16000
amplify: 228/16000
amplify: 232/16000
amplify: 236/16000
amplify: 240/16000
amplify: 244/16000
amplify: 248/16000
amplify: 252/16000
amplify: 256/16000
amplify: 260/16000
amplify: 264/16000
amplify: 268/16000
amplify: 272/16000
amplify: 276/16000
amplify: 280/16000
amplify: 284/16000
amplify: 288/16000
amplify: 292/16000
amplify: 296/16000
amplify: 300/16000
amplify: 304/16000
amplify: 308/16000
amplify: 312/16000
amplify: 316/16000
amplify: 320/16000
amplify: 324/16000
amplify: 328/16000
amplify: 332/16000
amplify: 336/16000
amplify: 340/16000
amplify: 344/16000
amplify: 348/16000
amplify: 352/16000
amplify: 356/16000
amplify: 360/16000
amplify: 364/16000
amplify: 368/16000
amplify: 372/16000
amplify: 376/16000
amplify: 380/16000
amplify: 384/16000
amplify: 388/16000
amplify: 392/16000
amplify: 396/16000
amplify: 400/16000
amplify: 404/16000
amplify: 408/16000

amplify: 412/16000
amplify: 416/16000
amplify: 420/16000
amplify: 424/16000
amplify: 428/16000
amplify: 432/16000
amplify: 436/16000
amplify: 440/16000
amplify: 444/16000
amplify: 448/16000
amplify: 452/16000
amplify: 456/16000
amplify: 460/16000
amplify: 464/16000
amplify: 468/16000
amplify: 472/16000
amplify: 476/16000
amplify: 480/16000
amplify: 484/16000
amplify: 488/16000
amplify: 492/16000
amplify: 496/16000
amplify: 500/16000
amplify: 504/16000
amplify: 508/16000
amplify: 512/16000
amplify: 516/16000
amplify: 520/16000
amplify: 524/16000
amplify: 528/16000
amplify: 532/16000
amplify: 536/16000
amplify: 540/16000
amplify: 544/16000
amplify: 548/16000
amplify: 552/16000
amplify: 556/16000
amplify: 560/16000
amplify: 564/16000
amplify: 568/16000
amplify: 572/16000
amplify: 576/16000
amplify: 580/16000
amplify: 584/16000
amplify: 588/16000
amplify: 592/16000
amplify: 596/16000
amplify: 600/16000
amplify: 604/16000
amplify: 608/16000
amplify: 612/16000
amplify: 616/16000
amplify: 620/16000
amplify: 624/16000
amplify: 628/16000
amplify: 632/16000
amplify: 636/16000
amplify: 640/16000
amplify: 644/16000
amplify: 648/16000
amplify: 652/16000
amplify: 656/16000
amplify: 660/16000
amplify: 664/16000
amplify: 668/16000
amplify: 672/16000
amplify: 676/16000
amplify: 680/16000
amplify: 684/16000
amplify: 688/16000
amplify: 692/16000
amplify: 696/16000
amplify: 700/16000
amplify: 704/16000
amplify: 708/16000
amplify: 712/16000
amplify: 716/16000
amplify: 720/16000
amplify: 724/16000
amplify: 728/16000
amplify: 732/16000
amplify: 736/16000
amplify: 740/16000
amplify: 744/16000
amplify: 748/16000
amplify: 752/16000
amplify: 756/16000
amplify: 760/16000
amplify: 764/16000
amplify: 768/16000
amplify: 772/16000
amplify: 776/16000
amplify: 780/16000
amplify: 784/16000
amplify: 788/16000
amplify: 792/16000
amplify: 796/16000
amplify: 800/16000
amplify: 804/16000
amplify: 808/16000
amplify: 812/16000
amplify: 816/16000
amplify: 820/16000
amplify: 824/16000
amplify: 828/16000
amplify: 832/16000
amplify: 836/16000
amplify: 840/16000
amplify: 844/16000
amplify: 848/16000
amplify: 852/16000
amplify: 856/16000
amplify: 860/16000
amplify: 864/16000
amplify: 868/16000
amplify: 872/16000
amplify: 876/16000
amplify: 880/16000
amplify: 884/16000
amplify: 888/16000
amplify: 892/16000
amplify: 896/16000
amplify: 900/16000
amplify: 904/16000
amplify: 908/16000
amplify: 912/16000
amplify: 916/16000
amplify: 920/16000
amplify: 924/16000
amplify: 928/16000
amplify: 932/16000
amplify: 936/16000
amplify: 940/16000
amplify: 944/16000
amplify: 948/16000
amplify: 952/16000
amplify: 956/16000
amplify: 960/16000
amplify: 964/16000
amplify: 968/16000
amplify: 972/16000
amplify: 976/16000
amplify: 980/16000
amplify: 984/16000
amplify: 988/16000
amplify: 992/16000
amplify: 996/16000
amplify: 1000/16000
amplify: 1004/16000
amplify: 1008/16000
amplify: 1012/16000
amplify: 1016/16000
amplify: 1020/16000
amplify: 1024/16000
amplify: 1028/16000
amplify: 1032/16000
amplify: 1036/16000
amplify: 1040/16000
amplify: 1044/16000
amplify: 1048/16000
amplify: 1052/16000
amplify: 1056/16000
amplify: 1060/16000
amplify: 1064/16000
amplify: 1068/16000
amplify: 1072/16000
amplify: 1076/16000
amplify: 1080/16000
amplify: 1084/16000
amplify: 1088/16000
amplify: 1092/16000
amplify: 1096/16000
amplify: 1100/16000
amplify: 1104/16000
amplify: 1108/16000
amplify: 1112/16000
amplify: 1116/16000
amplify: 1120/16000
amplify: 1124/16000
amplify: 1128/16000
amplify: 1132/16000
amplify: 1136/16000
amplify: 1140/16000
amplify: 1144/16000
amplify: 1148/16000
amplify: 1152/16000
amplify: 1156/16000
amplify: 1160/16000
amplify: 1164/16000
amplify: 1168/16000
amplify: 1172/16000
amplify: 1176/16000
amplify: 1180/16000
amplify: 1184/16000
amplify: 1188/16000
amplify: 1192/16000
amplify: 1196/16000
amplify: 1200/16000
amplify: 1204/16000
amplify: 1208/16000
amplify: 1212/16000
amplify: 1216/16000
amplify: 1220/16000
amplify: 1224/16000
amplify: 1228/16000
amplify: 1232/16000
amplify: 1236/16000
amplify: 1240/16000
amplify: 1244/16000
amplify: 1248/16000
amplify: 1252/16000
amplify: 1256/16000
amplify: 1260/16000
amplify: 1264/16000
amplify: 1268/16000
amplify: 1272/16000
amplify: 1276/16000
amplify: 1280/16000
amplify: 1284/16000
amplify: 1288/16000
amplify: 1292/16000
amplify: 1296/16000
amplify: 1300/16000
amplify: 1304/16000
amplify: 1308/16000
amplify: 1312/16000
amplify: 1316/16000
amplify: 1320/16000
amplify: 1324/16000
amplify: 1328/16000
amplify: 1332/16000
amplify: 1336/16000
amplify: 1340/16000
amplify: 1344/16000
amplify: 1348/16000
amplify: 1352/16000
amplify: 1356/16000
amplify: 1360/16000
amplify: 1364/16000
amplify: 1368/16000
amplify: 1372/16000
amplify: 1376/16000
amplify: 1380/16000
amplify: 1384/16000
amplify: 1388/16000
amplify: 1392/16000
amplify: 1396/16000
amplify: 1400/16000
amplify: 1404/16000
amplify: 1408/16000
amplify: 1412/16000
amplify: 1416/16000
amplify: 1420/16000
amplify: 1424/16000
amplify: 1428/16000
amplify: 1432/16000
amplify: 1436/16000
amplify: 1440/16000
amplify: 1444/16000
amplify: 1448/16000
amplify: 1452/16000
amplify: 1456/16000
amplify: 1460/16000
amplify: 1464/16000
amplify: 1468/16000
amplify: 1472/16000
amplify: 1476/16000
amplify: 1480/16000
amplify: 1484/16000
amplify: 1488/16000
amplify: 1492/16000
amplify: 1496/16000
amplify: 1500/16000
amplify: 1504/16000
amplify: 1508/16000
amplify: 1512/16000
amplify: 1516/16000
amplify: 1520/16000
amplify: 1524/16000
amplify: 1528/16000
amplify: 1532/16000
amplify: 1536/16000
amplify: 1540/16000
amplify: 1544/16000
amplify: 1548/16000
amplify: 1552/16000
amplify: 1556/16000
amplify: 1560/16000
amplify: 1564/16000
amplify: 1568/16000
amplify: 1572/16000
amplify: 1576/16000
amplify: 1580/16000
amplify: 1584/16000
amplify: 1588/16000
amplify: 1592/16000
amplify: 1596/16000
amplify: 1600/16000
amplify: 1604/16000
amplify: 1608/16000
amplify: 1612/16000
amplify: 1616/16000
amplify: 1620/16000
amplify: 1624/16000
amplify: 1628/16000
amplify: 1632/16000
amplify: 1636/16000
amplify: 1640/16000
amplify: 1644/16000
amplify: 1648/16000
amplify: 1652/16000
amplify: 1656/16000
amplify: 1660/16000
amplify: 1664/16000
amplify: 1668/16000
amplify: 1672/16000
amplify: 1676/16000
amplify: 1680/16000
amplify: 1684/16000
amplify: 1688/16000
amplify: 1692/16000
amplify: 1696/16000
amplify: 1700/16000
amplify: 1704/16000
amplify: 1708/16000
amplify: 1712/16000
amplify: 1716/16000
amplify: 1720/16000
amplify: 1724/16000
amplify: 1728/16000
amplify: 1732/16000
amplify: 1736/16000
amplify: 1740/16000
amplify: 1744/16000
amplify: 1748/16000
amplify: 1752/16000
amplify: 1756/16000
amplify: 1760/16000
amplify: 1764/16000
amplify: 1768/16000
amplify: 1772/16000
amplify: 1776/16000
amplify: 1780/16000
amplify: 1784/16000
amplify: 1788/16000
amplify: 1792/16000
amplify: 1796/16000
amplify: 1800/16000
amplify: 1804/16000
amplify: 1808/16000
amplify: 1812/16000
amplify: 1816/16000
amplify: 1820/16000
amplify: 1824/16000
amplify: 1828/16000
amplify: 1832/16000
amplify: 1836/16000
amplify: 1840/16000
amplify: 1844/16000
amplify: 1848/16000
amplify: 1852/16000
amplify: 1856/16000
amplify: 1860/16000
amplify: 1864/16000
amplify: 1868/16000
amplify: 1872/16000
amplify: 1876/16000
amplify: 1880/16000
amplify: 1884/16000
amplify: 1888/16000
amplify: 1892/16000
amplify: 1896/16000
amplify: 1900/16000
amplify: 1904/16000
amplify: 1908/16000
amplify: 1912/16000
amplify: 1916/16000
amplify: 1920/16000
amplify: 1924/16000
amplify: 1928/16000
amplify: 1932/16000
amplify: 1936/16000
amplify: 1940/16000
amplify: 1944/16000
amplify: 1948/16000
amplify: 1952/16000
amplify: 1956/16000
amplify: 1960/16000
amplify: 1964/16000
amplify: 1968/16000
amplify: 1972/16000
amplify: 1976/16000
amplify: 1980/16000
amplify: 1984/16000
amplify: 1988/16000
amplify: 1992/16000
amplify: 1996/16000
amplify: 2000/16000
amplify: 2004/16000
amplify: 2008/16000
amplify: 2012/16000
amplify: 2016/16000
amplify: 2020/16000
amplify: 2024/16000
amplify: 2028/16000
amplify: 2032/16000
amplify: 2036/16000
amplify: 2040/16000
amplify: 2044/16000
amplify: 2048/16000
amplify: 2052/16000
amplify: 2056/16000
amplify: 2060/16000
amplify: 2064/16000
amplify: 2068/16000
amplify: 2072/16000
amplify: 2076/16000
amplify: 2080/16000
amplify: 2084/16000

amplify: 2088/16000
amplify: 2092/16000
amplify: 2096/16000
amplify: 2100/16000
amplify: 2104/16000
amplify: 2108/16000
amplify: 2112/16000
amplify: 2116/16000
amplify: 2120/16000
amplify: 2124/16000
amplify: 2128/16000
amplify: 2132/16000
amplify: 2136/16000
amplify: 2140/16000
amplify: 2144/16000
amplify: 2148/16000
amplify: 2152/16000
amplify: 2156/16000
amplify: 2160/16000
amplify: 2164/16000
amplify: 2168/16000
amplify: 2172/16000
amplify: 2176/16000
amplify: 2180/16000
amplify: 2184/16000
amplify: 2188/16000
amplify: 2192/16000
amplify: 2196/16000
amplify: 2200/16000
amplify: 2204/16000
amplify: 2208/16000
amplify: 2212/16000
amplify: 2216/16000
amplify: 2220/16000
amplify: 2224/16000
amplify: 2228/16000
amplify: 2232/16000
amplify: 2236/16000
amplify: 2240/16000
amplify: 2244/16000
amplify: 2248/16000
amplify: 2252/16000
amplify: 2256/16000
amplify: 2260/16000
amplify: 2264/16000
amplify: 2268/16000
amplify: 2272/16000
amplify: 2276/16000
amplify: 2280/16000
amplify: 2284/16000
amplify: 2288/16000
amplify: 2292/16000
amplify: 2296/16000
amplify: 2300/16000
amplify: 2304/16000
amplify: 2308/16000
amplify: 2312/16000
amplify: 2316/16000
amplify: 2320/16000
amplify: 2324/16000
amplify: 2328/16000
amplify: 2332/16000
amplify: 2336/16000
amplify: 2340/16000
amplify: 2344/16000
amplify: 2348/16000
amplify: 2352/16000
amplify: 2356/16000
amplify: 2360/16000
amplify: 2364/16000
amplify: 2368/16000
amplify: 2372/16000
amplify: 2376/16000
amplify: 2380/16000
amplify: 2384/16000
amplify: 2388/16000
amplify: 2392/16000
amplify: 2396/16000
amplify: 2400/16000
amplify: 2404/16000
amplify: 2408/16000
amplify: 2412/16000
amplify: 2416/16000
amplify: 2420/16000
amplify: 2424/16000
amplify: 2428/16000
amplify: 2432/16000
amplify: 2436/16000
amplify: 2440/16000
amplify: 2444/16000
amplify: 2448/16000
amplify: 2452/16000
amplify: 2456/16000
amplify: 2460/16000
amplify: 2464/16000
amplify: 2468/16000
amplify: 2472/16000
amplify: 2476/16000
amplify: 2480/16000
amplify: 2484/16000
amplify: 2488/16000
amplify: 2492/16000
amplify: 2496/16000
amplify: 2500/16000
amplify: 2504/16000
amplify: 2508/16000
amplify: 2512/16000
amplify: 2516/16000
amplify: 2520/16000
amplify: 2524/16000
amplify: 2528/16000
amplify: 2532/16000
amplify: 2536/16000
amplify: 2540/16000
amplify: 2544/16000
amplify: 2548/16000
amplify: 2552/16000
amplify: 2556/16000
amplify: 2560/16000
amplify: 2564/16000
amplify: 2568/16000
amplify: 2572/16000
amplify: 2576/16000
amplify: 2580/16000
amplify: 2584/16000
amplify: 2588/16000
amplify: 2592/16000
amplify: 2596/16000
amplify: 2600/16000
amplify: 2604/16000
amplify: 2608/16000
amplify: 2612/16000
amplify: 2616/16000
amplify: 2620/16000
amplify: 2624/16000
amplify: 2628/16000
amplify: 2632/16000
amplify: 2636/16000
amplify: 2640/16000
amplify: 2644/16000
amplify: 2648/16000
amplify: 2652/16000
amplify: 2656/16000
amplify: 2660/16000
amplify: 2664/16000
amplify: 2668/16000
amplify: 2672/16000
amplify: 2676/16000
amplify: 2680/16000
amplify: 2684/16000
amplify: 2688/16000
amplify: 2692/16000
amplify: 2696/16000
amplify: 2700/16000
amplify: 2704/16000
amplify: 2708/16000
amplify: 2712/16000
amplify: 2716/16000
amplify: 2720/16000
amplify: 2724/16000
amplify: 2728/16000
amplify: 2732/16000
amplify: 2736/16000
amplify: 2740/16000
amplify: 2744/16000
amplify: 2748/16000
amplify: 2752/16000
amplify: 2756/16000
amplify: 2760/16000
amplify: 2764/16000
amplify: 2768/16000
amplify: 2772/16000
amplify: 2776/16000
amplify: 2780/16000
amplify: 2784/16000
amplify: 2788/16000
amplify: 2792/16000
amplify: 2796/16000
amplify: 2800/16000
amplify: 2804/16000
amplify: 2808/16000
amplify: 2812/16000
amplify: 2816/16000
amplify: 2820/16000
amplify: 2824/16000
amplify: 2828/16000
amplify: 2832/16000
amplify: 2836/16000
amplify: 2840/16000
amplify: 2844/16000
amplify: 2848/16000
amplify: 2852/16000
amplify: 2856/16000
amplify: 2860/16000
amplify: 2864/16000
amplify: 2868/16000
amplify: 2872/16000
amplify: 2876/16000
amplify: 2880/16000
amplify: 2884/16000
amplify: 2888/16000
amplify: 2892/16000
amplify: 2896/16000
amplify: 2900/16000
amplify: 2904/16000
amplify: 2908/16000
amplify: 2912/16000
amplify: 2916/16000
amplify: 2920/16000
amplify: 2924/16000
amplify: 2928/16000
amplify: 2932/16000
amplify: 2936/16000
amplify: 2940/16000
amplify: 2944/16000
amplify: 2948/16000
amplify: 2952/16000
amplify: 2956/16000
amplify: 2960/16000
amplify: 2964/16000
amplify: 2968/16000
amplify: 2972/16000
amplify: 2976/16000
amplify: 2980/16000
amplify: 2984/16000
amplify: 2988/16000
amplify: 2992/16000
amplify: 2996/16000
amplify: 3000/16000
amplify: 3004/16000
amplify: 3008/16000
amplify: 3012/16000
amplify: 3016/16000
amplify: 3020/16000
amplify: 3024/16000
amplify: 3028/16000
amplify: 3032/16000
amplify: 3036/16000
amplify: 3040/16000
amplify: 3044/16000
amplify: 3048/16000
amplify: 3052/16000
amplify: 3056/16000
amplify: 3060/16000
amplify: 3064/16000
amplify: 3068/16000
amplify: 3072/16000
amplify: 3076/16000
amplify: 3080/16000
amplify: 3084/16000
amplify: 3088/16000
amplify: 3092/16000
amplify: 3096/16000
amplify: 3100/16000
amplify: 3104/16000
amplify: 3108/16000
amplify: 3112/16000
amplify: 3116/16000
amplify: 3120/16000
amplify: 3124/16000
amplify: 3128/16000
amplify: 3132/16000
amplify: 3136/16000
amplify: 3140/16000
amplify: 3144/16000
amplify: 3148/16000
amplify: 3152/16000
amplify: 3156/16000
amplify: 3160/16000
amplify: 3164/16000
amplify: 3168/16000
amplify: 3172/16000
amplify: 3176/16000
amplify: 3180/16000
amplify: 3184/16000
amplify: 3188/16000
amplify: 3192/16000
amplify: 3196/16000
amplify: 3200/16000
amplify: 3204/16000
amplify: 3208/16000
amplify: 3212/16000
amplify: 3216/16000
amplify: 3220/16000
amplify: 3224/16000
amplify: 3228/16000
amplify: 3232/16000
amplify: 3236/16000
amplify: 3240/16000
amplify: 3244/16000
amplify: 3248/16000
amplify: 3252/16000
amplify: 3256/16000
amplify: 3260/16000
amplify: 3264/16000
amplify: 3268/16000
amplify: 3272/16000
amplify: 3276/16000
amplify: 3280/16000
amplify: 3284/16000
amplify: 3288/16000
amplify: 3292/16000
amplify: 3296/16000
amplify: 3300/16000
amplify: 3304/16000
amplify: 3308/16000
amplify: 3312/16000
amplify: 3316/16000
amplify: 3320/16000
amplify: 3324/16000
amplify: 3328/16000
amplify: 3332/16000
amplify: 3336/16000
amplify: 3340/16000
amplify: 3344/16000
amplify: 3348/16000
amplify: 3352/16000
amplify: 3356/16000
amplify: 3360/16000
amplify: 3364/16000
amplify: 3368/16000
amplify: 3372/16000
amplify: 3376/16000
amplify: 3380/16000
amplify: 3384/16000
amplify: 3388/16000
amplify: 3392/16000
amplify: 3396/16000
amplify: 3400/16000
amplify: 3404/16000
amplify: 3408/16000
amplify: 3412/16000
amplify: 3416/16000
amplify: 3420/16000
amplify: 3424/16000
amplify: 3428/16000
amplify: 3432/16000
amplify: 3436/16000
amplify: 3440/16000
amplify: 3444/16000
amplify: 3448/16000
amplify: 3452/16000
amplify: 3456/16000
amplify: 3460/16000
amplify: 3464/16000
amplify: 3468/16000
amplify: 3472/16000
amplify: 3476/16000
amplify: 3480/16000
amplify: 3484/16000
amplify: 3488/16000
amplify: 3492/16000
amplify: 3496/16000
amplify: 3500/16000
amplify: 3504/16000
amplify: 3508/16000
amplify: 3512/16000
amplify: 3516/16000
amplify: 3520/16000
amplify: 3524/16000
amplify: 3528/16000
amplify: 3532/16000
amplify: 3536/16000
amplify: 3540/16000
amplify: 3544/16000
amplify: 3548/16000
amplify: 3552/16000
amplify: 3556/16000
amplify: 3560/16000
amplify: 3564/16000
amplify: 3568/16000
amplify: 3572/16000
amplify: 3576/16000
amplify: 3580/16000
amplify: 3584/16000
amplify: 3588/16000
amplify: 3592/16000
amplify: 3596/16000
amplify: 3600/16000
amplify: 3604/16000
amplify: 3608/16000
amplify: 3612/16000
amplify: 3616/16000
amplify: 3620/16000
amplify: 3624/16000
amplify: 3628/16000
amplify: 3632/16000
amplify: 3636/16000
amplify: 3640/16000
amplify: 3644/16000
amplify: 3648/16000
amplify: 3652/16000
amplify: 3656/16000
amplify: 3660/16000
amplify: 3664/16000
amplify: 3668/16000
amplify: 3672/16000
amplify: 3676/16000
amplify: 3680/16000
amplify: 3684/16000
amplify: 3688/16000
amplify: 3692/16000
amplify: 3696/16000
amplify: 3700/16000
amplify: 3704/16000
amplify: 3708/16000
amplify: 3712/16000
amplify: 3716/16000
amplify: 3720/16000
amplify: 3724/16000
amplify: 3728/16000

amplify: 3732/16000
amplify: 3736/16000
amplify: 3740/16000
amplify: 3744/16000
amplify: 3748/16000
amplify: 3752/16000
amplify: 3756/16000
amplify: 3760/16000
amplify: 3764/16000
amplify: 3768/16000
amplify: 3772/16000
amplify: 3776/16000
amplify: 3780/16000
amplify: 3784/16000
amplify: 3788/16000
amplify: 3792/16000
amplify: 3796/16000
amplify: 3800/16000
amplify: 3804/16000
amplify: 3808/16000
amplify: 3812/16000
amplify: 3816/16000
amplify: 3820/16000
amplify: 3824/16000
amplify: 3828/16000
amplify: 3832/16000
amplify: 3836/16000
amplify: 3840/16000
amplify: 3844/16000
amplify: 3848/16000
amplify: 3852/16000
amplify: 3856/16000
amplify: 3860/16000
amplify: 3864/16000
amplify: 3868/16000
amplify: 3872/16000
amplify: 3876/16000
amplify: 3880/16000
amplify: 3884/16000
amplify: 3888/16000
amplify: 3892/16000
amplify: 3896/16000
amplify: 3900/16000
amplify: 3904/16000
amplify: 3908/16000
amplify: 3912/16000
amplify: 3916/16000
amplify: 3920/16000
amplify: 3924/16000
amplify: 3928/16000
amplify: 3932/16000
amplify: 3936/16000
amplify: 3940/16000
amplify: 3944/16000
amplify: 3948/16000
amplify: 3952/16000
amplify: 3956/16000
amplify: 3960/16000
amplify: 3964/16000
amplify: 3968/16000
amplify: 3972/16000
amplify: 3976/16000
amplify: 3980/16000
amplify: 3984/16000
amplify: 3988/16000
amplify: 3992/16000
amplify: 3996/16000
amplify: 4000/16000
amplify: 4004/16000
amplify: 4008/16000
amplify: 4012/16000
amplify: 4016/16000
amplify: 4020/16000
amplify: 4024/16000
amplify: 4028/16000
amplify: 4032/16000
amplify: 4036/16000
amplify: 4040/16000
amplify: 4044/16000
amplify: 4048/16000
amplify: 4052/16000
amplify: 4056/16000
amplify: 4060/16000
amplify: 4064/16000
amplify: 4068/16000
amplify: 4072/16000
amplify: 4076/16000
amplify: 4080/16000
amplify: 4084/16000
amplify: 4088/16000
amplify: 4092/16000
amplify: 4096/16000
amplify: 4100/16000
amplify: 4104/16000
amplify: 4108/16000
amplify: 4112/16000
amplify: 4116/16000
amplify: 4120/16000
amplify: 4124/16000
amplify: 4128/16000
amplify: 4132/16000
amplify: 4136/16000
amplify: 4140/16000
amplify: 4144/16000
amplify: 4148/16000
amplify: 4152/16000
amplify: 4156/16000
amplify: 4160/16000
amplify: 4164/16000
amplify: 4168/16000
amplify: 4172/16000
amplify: 4176/16000
amplify: 4180/16000
amplify: 4184/16000
amplify: 4188/16000
amplify: 4192/16000
amplify: 4196/16000
amplify: 4200/16000
amplify: 4204/16000
amplify: 4208/16000
amplify: 4212/16000
amplify: 4216/16000
amplify: 4220/16000
amplify: 4224/16000
amplify: 4228/16000
amplify: 4232/16000
amplify: 4236/16000
amplify: 4240/16000
amplify: 4244/16000
amplify: 4248/16000
amplify: 4252/16000
amplify: 4256/16000
amplify: 4260/16000
amplify: 4264/16000
amplify: 4268/16000
amplify: 4272/16000
amplify: 4276/16000
amplify: 4280/16000
amplify: 4284/16000
amplify: 4288/16000
amplify: 4292/16000
amplify: 4296/16000
amplify: 4300/16000
amplify: 4304/16000
amplify: 4308/16000
amplify: 4312/16000
amplify: 4316/16000
amplify: 4320/16000
amplify: 4324/16000
amplify: 4328/16000
amplify: 4332/16000
amplify: 4336/16000
amplify: 4340/16000
amplify: 4344/16000
amplify: 4348/16000
amplify: 4352/16000
amplify: 4356/16000
amplify: 4360/16000
amplify: 4364/16000
amplify: 4368/16000
amplify: 4372/16000
amplify: 4376/16000
amplify: 4380/16000
amplify: 4384/16000
amplify: 4388/16000
amplify: 4392/16000
amplify: 4396/16000
amplify: 4400/16000
amplify: 4404/16000
amplify: 4408/16000
amplify: 4412/16000
amplify: 4416/16000
amplify: 4420/16000
amplify: 4424/16000
amplify: 4428/16000
amplify: 4432/16000
amplify: 4436/16000
amplify: 4440/16000
amplify: 4444/16000
amplify: 4448/16000
amplify: 4452/16000
amplify: 4456/16000
amplify: 4460/16000
amplify: 4464/16000
amplify: 4468/16000
amplify: 4472/16000
amplify: 4476/16000
amplify: 4480/16000
amplify: 4484/16000
amplify: 4488/16000
amplify: 4492/16000
amplify: 4496/16000
amplify: 4500/16000
amplify: 4504/16000
amplify: 4508/16000
amplify: 4512/16000
amplify: 4516/16000
amplify: 4520/16000
amplify: 4524/16000
amplify: 4528/16000
amplify: 4532/16000
amplify: 4536/16000
amplify: 4540/16000
amplify: 4544/16000
amplify: 4548/16000
amplify: 4552/16000
amplify: 4556/16000
amplify: 4560/16000
amplify: 4564/16000
amplify: 4568/16000
amplify: 4572/16000
amplify: 4576/16000
amplify: 4580/16000
amplify: 4584/16000
amplify: 4588/16000
amplify: 4592/16000
amplify: 4596/16000
amplify: 4600/16000
amplify: 4604/16000
amplify: 4608/16000
amplify: 4612/16000
amplify: 4616/16000
amplify: 4620/16000
amplify: 4624/16000
amplify: 4628/16000
amplify: 4632/16000
amplify: 4636/16000
amplify: 4640/16000
amplify: 4644/16000
amplify: 4648/16000
amplify: 4652/16000
amplify: 4656/16000
amplify: 4660/16000
amplify: 4664/16000
amplify: 4668/16000
amplify: 4672/16000
amplify: 4676/16000
amplify: 4680/16000
amplify: 4684/16000
amplify: 4688/16000
amplify: 4692/16000
amplify: 4696/16000
amplify: 4700/16000
amplify: 4704/16000
amplify: 4708/16000
amplify: 4712/16000
amplify: 4716/16000
amplify: 4720/16000
amplify: 4724/16000
amplify: 4728/16000
amplify: 4732/16000
amplify: 4736/16000
amplify: 4740/16000
amplify: 4744/16000
amplify: 4748/16000
amplify: 4752/16000
amplify: 4756/16000
amplify: 4760/16000
amplify: 4764/16000
amplify: 4768/16000
amplify: 4772/16000
amplify: 4776/16000
amplify: 4780/16000
amplify: 4784/16000
amplify: 4788/16000
amplify: 4792/16000
amplify: 4796/16000
amplify: 4800/16000
amplify: 4804/16000
amplify: 4808/16000
amplify: 4812/16000
amplify: 4816/16000
amplify: 4820/16000
amplify: 4824/16000
amplify: 4828/16000
amplify: 4832/16000
amplify: 4836/16000
amplify: 4840/16000
amplify: 4844/16000
amplify: 4848/16000
amplify: 4852/16000
amplify: 4856/16000
amplify: 4860/16000
amplify: 4864/16000
amplify: 4868/16000
amplify: 4872/16000
amplify: 4876/16000
amplify: 4880/16000
amplify: 4884/16000
amplify: 4888/16000
amplify: 4892/16000
amplify: 4896/16000
amplify: 4900/16000
amplify: 4904/16000
amplify: 4908/16000
amplify: 4912/16000
amplify: 4916/16000
amplify: 4920/16000
amplify: 4924/16000
amplify: 4928/16000
amplify: 4932/16000
amplify: 4936/16000
amplify: 4940/16000
amplify: 4944/16000
amplify: 4948/16000
amplify: 4952/16000
amplify: 4956/16000
amplify: 4960/16000
amplify: 4964/16000
amplify: 4968/16000
amplify: 4972/16000
amplify: 4976/16000
amplify: 4980/16000
amplify: 4984/16000
amplify: 4988/16000
amplify: 4992/16000
amplify: 4996/16000
amplify: 5000/16000
amplify: 5004/16000
amplify: 5008/16000
amplify: 5012/16000
amplify: 5016/16000
amplify: 5020/16000
amplify: 5024/16000
amplify: 5028/16000
amplify: 5032/16000
amplify: 5036/16000
amplify: 5040/16000
amplify: 5044/16000
amplify: 5048/16000
amplify: 5052/16000
amplify: 5056/16000
amplify: 5060/16000
amplify: 5064/16000
amplify: 5068/16000
amplify: 5072/16000
amplify: 5076/16000
amplify: 5080/16000
amplify: 5084/16000
amplify: 5088/16000
amplify: 5092/16000
amplify: 5096/16000
amplify: 5100/16000
amplify: 5104/16000
amplify: 5108/16000
amplify: 5112/16000
amplify: 5116/16000
amplify: 5120/16000
amplify: 5124/16000
amplify: 5128/16000
amplify: 5132/16000
amplify: 5136/16000
amplify: 5140/16000
amplify: 5144/16000
amplify: 5148/16000
amplify: 5152/16000
amplify: 5156/16000
amplify: 5160/16000
amplify: 5164/16000
amplify: 5168/16000
amplify: 5172/16000
amplify: 5176/16000
amplify: 5180/16000
amplify: 5184/16000
amplify: 5188/16000
amplify: 5192/16000
amplify: 5196/16000
amplify: 5200/16000
amplify: 5204/16000
amplify: 5208/16000
amplify: 5212/16000
amplify: 5216/16000
amplify: 5220/16000
amplify: 5224/16000
amplify: 5228/16000
amplify: 5232/16000
amplify: 5236/16000
amplify: 5240/16000
amplify: 5244/16000
amplify: 5248/16000
amplify: 5252/16000
amplify: 5256/16000
amplify: 5260/16000
amplify: 5264/16000
amplify: 5268/16000
amplify: 5272/16000
amplify: 5276/16000
amplify: 5280/16000
amplify: 5284/16000
amplify: 5288/16000
amplify: 5292/16000
amplify: 5296/16000
amplify: 5300/16000
amplify: 5304/16000
amplify: 5308/16000
amplify: 5312/16000
amplify: 5316/16000
amplify: 5320/16000
amplify: 5324/16000
amplify: 5328/16000
amplify: 5332/16000
amplify: 5336/16000
amplify: 5340/16000
amplify: 5344/16000
amplify: 5348/16000
amplify: 5352/16000
amplify: 5356/16000
amplify: 5360/16000
amplify: 5364/16000
amplify: 5368/16000
amplify: 5372/16000
amplify: 5376/16000

amplify: 5380/16000
amplify: 5384/16000
amplify: 5388/16000
amplify: 5392/16000
amplify: 5396/16000
amplify: 5400/16000
amplify: 5404/16000
amplify: 5408/16000
amplify: 5412/16000
amplify: 5416/16000
amplify: 5420/16000
amplify: 5424/16000
amplify: 5428/16000
amplify: 5432/16000
amplify: 5436/16000
amplify: 5440/16000
amplify: 5444/16000
amplify: 5448/16000
amplify: 5452/16000
amplify: 5456/16000
amplify: 5460/16000
amplify: 5464/16000
amplify: 5468/16000
amplify: 5472/16000
amplify: 5476/16000
amplify: 5480/16000
amplify: 5484/16000
amplify: 5488/16000
amplify: 5492/16000
amplify: 5496/16000
amplify: 5500/16000
amplify: 5504/16000
amplify: 5508/16000
amplify: 5512/16000
amplify: 5516/16000
amplify: 5520/16000
amplify: 5524/16000
amplify: 5528/16000
amplify: 5532/16000
amplify: 5536/16000
amplify: 5540/16000
amplify: 5544/16000
amplify: 5548/16000
amplify: 5552/16000
amplify: 5556/16000
amplify: 5560/16000
amplify: 5564/16000
amplify: 5568/16000
amplify: 5572/16000
amplify: 5576/16000
amplify: 5580/16000
amplify: 5584/16000
amplify: 5588/16000
amplify: 5592/16000
amplify: 5596/16000
amplify: 5600/16000
amplify: 5604/16000
amplify: 5608/16000
amplify: 5612/16000
amplify: 5616/16000
amplify: 5620/16000
amplify: 5624/16000
amplify: 5628/16000
amplify: 5632/16000
amplify: 5636/16000
amplify: 5640/16000
amplify: 5644/16000
amplify: 5648/16000
amplify: 5652/16000
amplify: 5656/16000
amplify: 5660/16000
amplify: 5664/16000
amplify: 5668/16000
amplify: 5672/16000
amplify: 5676/16000
amplify: 5680/16000
amplify: 5684/16000
amplify: 5688/16000
amplify: 5692/16000
amplify: 5696/16000
amplify: 5700/16000
amplify: 5704/16000
amplify: 5708/16000
amplify: 5712/16000
amplify: 5716/16000
amplify: 5720/16000
amplify: 5724/16000
amplify: 5728/16000
amplify: 5732/16000
amplify: 5736/16000
amplify: 5740/16000
amplify: 5744/16000
amplify: 5748/16000
amplify: 5752/16000
amplify: 5756/16000
amplify: 5760/16000
amplify: 5764/16000
amplify: 5768/16000
amplify: 5772/16000
amplify: 5776/16000
amplify: 5780/16000
amplify: 5784/16000
amplify: 5788/16000
amplify: 5792/16000
amplify: 5796/16000
amplify: 5800/16000
amplify: 5804/16000
amplify: 5808/16000
amplify: 5812/16000
amplify: 5816/16000
amplify: 5820/16000
amplify: 5824/16000
amplify: 5828/16000
amplify: 5832/16000
amplify: 5836/16000
amplify: 5840/16000
amplify: 5844/16000
amplify: 5848/16000
amplify: 5852/16000
amplify: 5856/16000
amplify: 5860/16000
amplify: 5864/16000
amplify: 5868/16000
amplify: 5872/16000
amplify: 5876/16000
amplify: 5880/16000
amplify: 5884/16000
amplify: 5888/16000
amplify: 5892/16000
amplify: 5896/16000
amplify: 5900/16000
amplify: 5904/16000
amplify: 5908/16000
amplify: 5912/16000
amplify: 5916/16000
amplify: 5920/16000
amplify: 5924/16000
amplify: 5928/16000
amplify: 5932/16000
amplify: 5936/16000
amplify: 5940/16000
amplify: 5944/16000
amplify: 5948/16000
amplify: 5952/16000
amplify: 5956/16000
amplify: 5960/16000
amplify: 5964/16000
amplify: 5968/16000
amplify: 5972/16000
amplify: 5976/16000
amplify: 5980/16000
amplify: 5984/16000
amplify: 5988/16000
amplify: 5992/16000
amplify: 5996/16000
amplify: 6000/16000
amplify: 6004/16000
amplify: 6008/16000
amplify: 6012/16000
amplify: 6016/16000
amplify: 6020/16000
amplify: 6024/16000
amplify: 6028/16000
amplify: 6032/16000
amplify: 6036/16000
amplify: 6040/16000
amplify: 6044/16000
amplify: 6048/16000
amplify: 6052/16000
amplify: 6056/16000
amplify: 6060/16000
amplify: 6064/16000
amplify: 6068/16000
amplify: 6072/16000
amplify: 6076/16000
amplify: 6080/16000
amplify: 6084/16000
amplify: 6088/16000
amplify: 6092/16000
amplify: 6096/16000
amplify: 6100/16000
amplify: 6104/16000
amplify: 6108/16000
amplify: 6112/16000
amplify: 6116/16000
amplify: 6120/16000
amplify: 6124/16000
amplify: 6128/16000
amplify: 6132/16000
amplify: 6136/16000
amplify: 6140/16000
amplify: 6144/16000
amplify: 6148/16000
amplify: 6152/16000
amplify: 6156/16000
amplify: 6160/16000
amplify: 6164/16000
amplify: 6168/16000
amplify: 6172/16000
amplify: 6176/16000
amplify: 6180/16000
amplify: 6184/16000
amplify: 6188/16000
amplify: 6192/16000
amplify: 6196/16000
amplify: 6200/16000
amplify: 6204/16000
amplify: 6208/16000
amplify: 6212/16000
amplify: 6216/16000
amplify: 6220/16000
amplify: 6224/16000
amplify: 6228/16000
amplify: 6232/16000
amplify: 6236/16000
amplify: 6240/16000
amplify: 6244/16000
amplify: 6248/16000
amplify: 6252/16000
amplify: 6256/16000
amplify: 6260/16000
amplify: 6264/16000
amplify: 6268/16000
amplify: 6272/16000
amplify: 6276/16000
amplify: 6280/16000
amplify: 6284/16000
amplify: 6288/16000
amplify: 6292/16000
amplify: 6296/16000
amplify: 6300/16000
amplify: 6304/16000
amplify: 6308/16000
amplify: 6312/16000
amplify: 6316/16000
amplify: 6320/16000
amplify: 6324/16000
amplify: 6328/16000
amplify: 6332/16000
amplify: 6336/16000
amplify: 6340/16000
amplify: 6344/16000
amplify: 6348/16000
amplify: 6352/16000
amplify: 6356/16000
amplify: 6360/16000
amplify: 6364/16000
amplify: 6368/16000
amplify: 6372/16000
amplify: 6376/16000
amplify: 6380/16000
amplify: 6384/16000
amplify: 6388/16000
amplify: 6392/16000
amplify: 6396/16000
amplify: 6400/16000
amplify: 6404/16000
amplify: 6408/16000
amplify: 6412/16000
amplify: 6416/16000
amplify: 6420/16000
amplify: 6424/16000
amplify: 6428/16000
amplify: 6432/16000
amplify: 6436/16000
amplify: 6440/16000
amplify: 6444/16000
amplify: 6448/16000
amplify: 6452/16000
amplify: 6456/16000
amplify: 6460/16000
amplify: 6464/16000
amplify: 6468/16000
amplify: 6472/16000
amplify: 6476/16000
amplify: 6480/16000
amplify: 6484/16000
amplify: 6488/16000
amplify: 6492/16000
amplify: 6496/16000
amplify: 6500/16000
amplify: 6504/16000
amplify: 6508/16000
amplify: 6512/16000
amplify: 6516/16000
amplify: 6520/16000
amplify: 6524/16000
amplify: 6528/16000
amplify: 6532/16000
amplify: 6536/16000
amplify: 6540/16000
amplify: 6544/16000
amplify: 6548/16000
amplify: 6552/16000
amplify: 6556/16000
amplify: 6560/16000
amplify: 6564/16000
amplify: 6568/16000
amplify: 6572/16000
amplify: 6576/16000
amplify: 6580/16000
amplify: 6584/16000
amplify: 6588/16000
amplify: 6592/16000
amplify: 6596/16000
amplify: 6600/16000
amplify: 6604/16000
amplify: 6608/16000
amplify: 6612/16000
amplify: 6616/16000
amplify: 6620/16000
amplify: 6624/16000
amplify: 6628/16000
amplify: 6632/16000
amplify: 6636/16000
amplify: 6640/16000
amplify: 6644/16000
amplify: 6648/16000
amplify: 6652/16000
amplify: 6656/16000
amplify: 6660/16000
amplify: 6664/16000
amplify: 6668/16000
amplify: 6672/16000
amplify: 6676/16000
amplify: 6680/16000
amplify: 6684/16000
amplify: 6688/16000
amplify: 6692/16000
amplify: 6696/16000
amplify: 6700/16000
amplify: 6704/16000
amplify: 6708/16000
amplify: 6712/16000
amplify: 6716/16000
amplify: 6720/16000
amplify: 6724/16000
amplify: 6728/16000
amplify: 6732/16000
amplify: 6736/16000
amplify: 6740/16000
amplify: 6744/16000
amplify: 6748/16000
amplify: 6752/16000
amplify: 6756/16000
amplify: 6760/16000
amplify: 6764/16000
amplify: 6768/16000
amplify: 6772/16000
amplify: 6776/16000
amplify: 6780/16000
amplify: 6784/16000
amplify: 6788/16000
amplify: 6792/16000
amplify: 6796/16000
amplify: 6800/16000
amplify: 6804/16000
amplify: 6808/16000
amplify: 6812/16000
amplify: 6816/16000
amplify: 6820/16000
amplify: 6824/16000
amplify: 6828/16000
amplify: 6832/16000
amplify: 6836/16000
amplify: 6840/16000
amplify: 6844/16000
amplify: 6848/16000
amplify: 6852/16000
amplify: 6856/16000
amplify: 6860/16000
amplify: 6864/16000
amplify: 6868/16000
amplify: 6872/16000
amplify: 6876/16000
amplify: 6880/16000
amplify: 6884/16000
amplify: 6888/16000
amplify: 6892/16000
amplify: 6896/16000
amplify: 6900/16000
amplify: 6904/16000
amplify: 6908/16000
amplify: 6912/16000
amplify: 6916/16000
amplify: 6920/16000
amplify: 6924/16000
amplify: 6928/16000
amplify: 6932/16000
amplify: 6936/16000
amplify: 6940/16000
amplify: 6944/16000
amplify: 6948/16000
amplify: 6952/16000
amplify: 6956/16000
amplify: 6960/16000
amplify: 6964/16000
amplify: 6968/16000
amplify: 6972/16000
amplify: 6976/16000
amplify: 6980/16000
amplify: 6984/16000
amplify: 6988/16000
amplify: 6992/16000
amplify: 6996/16000
amplify: 7000/16000
amplify: 7004/16000
amplify: 7008/16000
amplify: 7012/16000
amplify: 7016/16000
amplify: 7020/16000
amplify: 7024/16000

amplify: 7028/16000
amplify: 7032/16000
amplify: 7036/16000
amplify: 7040/16000
amplify: 7044/16000
amplify: 7048/16000
amplify: 7052/16000
amplify: 7056/16000
amplify: 7060/16000
amplify: 7064/16000
amplify: 7068/16000
amplify: 7072/16000
amplify: 7076/16000
amplify: 7080/16000
amplify: 7084/16000
amplify: 7088/16000
amplify: 7092/16000
amplify: 7096/16000
amplify: 7100/16000
amplify: 7104/16000
amplify: 7108/16000
amplify: 7112/16000
amplify: 7116/16000
amplify: 7120/16000
amplify: 7124/16000
amplify: 7128/16000
amplify: 7132/16000
amplify: 7136/16000
amplify: 7140/16000
amplify: 7144/16000
amplify: 7148/16000
amplify: 7152/16000
amplify: 7156/16000
amplify: 7160/16000
amplify: 7164/16000
amplify: 7168/16000
amplify: 7172/16000
amplify: 7176/16000
amplify: 7180/16000
amplify: 7184/16000
amplify: 7188/16000
amplify: 7192/16000
amplify: 7196/16000
amplify: 7200/16000
amplify: 7204/16000
amplify: 7208/16000
amplify: 7212/16000
amplify: 7216/16000
amplify: 7220/16000
amplify: 7224/16000
amplify: 7228/16000
amplify: 7232/16000
amplify: 7236/16000
amplify: 7240/16000
amplify: 7244/16000
amplify: 7248/16000
amplify: 7252/16000
amplify: 7256/16000
amplify: 7260/16000
amplify: 7264/16000
amplify: 7268/16000
amplify: 7272/16000
amplify: 7276/16000
amplify: 7280/16000
amplify: 7284/16000
amplify: 7288/16000
amplify: 7292/16000
amplify: 7296/16000
amplify: 7300/16000
amplify: 7304/16000
amplify: 7308/16000
amplify: 7312/16000
amplify: 7316/16000
amplify: 7320/16000
amplify: 7324/16000
amplify: 7328/16000
amplify: 7332/16000
amplify: 7336/16000
amplify: 7340/16000
amplify: 7344/16000
amplify: 7348/16000
amplify: 7352/16000
amplify: 7356/16000
amplify: 7360/16000
amplify: 7364/16000
amplify: 7368/16000
amplify: 7372/16000
amplify: 7376/16000
amplify: 7380/16000
amplify: 7384/16000
amplify: 7388/16000
amplify: 7392/16000
amplify: 7396/16000
amplify: 7400/16000
amplify: 7404/16000
amplify: 7408/16000
amplify: 7412/16000
amplify: 7416/16000
amplify: 7420/16000
amplify: 7424/16000
amplify: 7428/16000
amplify: 7432/16000
amplify: 7436/16000
amplify: 7440/16000
amplify: 7444/16000
amplify: 7448/16000
amplify: 7452/16000
amplify: 7456/16000
amplify: 7460/16000
amplify: 7464/16000
amplify: 7468/16000
amplify: 7472/16000
amplify: 7476/16000
amplify: 7480/16000
amplify: 7484/16000
amplify: 7488/16000
amplify: 7492/16000
amplify: 7496/16000
amplify: 7500/16000
amplify: 7504/16000
amplify: 7508/16000
amplify: 7512/16000
amplify: 7516/16000
amplify: 7520/16000
amplify: 7524/16000
amplify: 7528/16000
amplify: 7532/16000
amplify: 7536/16000
amplify: 7540/16000
amplify: 7544/16000
amplify: 7548/16000
amplify: 7552/16000
amplify: 7556/16000
amplify: 7560/16000
amplify: 7564/16000
amplify: 7568/16000
amplify: 7572/16000
amplify: 7576/16000
amplify: 7580/16000
amplify: 7584/16000
amplify: 7588/16000
amplify: 7592/16000
amplify: 7596/16000
amplify: 7600/16000
amplify: 7604/16000
amplify: 7608/16000
amplify: 7612/16000
amplify: 7616/16000
amplify: 7620/16000
amplify: 7624/16000
amplify: 7628/16000
amplify: 7632/16000
amplify: 7636/16000
amplify: 7640/16000
amplify: 7644/16000
amplify: 7648/16000
amplify: 7652/16000
amplify: 7656/16000
amplify: 7660/16000
amplify: 7664/16000
amplify: 7668/16000
amplify: 7672/16000
amplify: 7676/16000
amplify: 7680/16000
amplify: 7684/16000
amplify: 7688/16000
amplify: 7692/16000
amplify: 7696/16000
amplify: 7700/16000
amplify: 7704/16000
amplify: 7708/16000
amplify: 7712/16000
amplify: 7716/16000
amplify: 7720/16000
amplify: 7724/16000
amplify: 7728/16000
amplify: 7732/16000
amplify: 7736/16000
amplify: 7740/16000
amplify: 7744/16000
amplify: 7748/16000
amplify: 7752/16000
amplify: 7756/16000
amplify: 7760/16000
amplify: 7764/16000
amplify: 7768/16000
amplify: 7772/16000
amplify: 7776/16000
amplify: 7780/16000
amplify: 7784/16000
amplify: 7788/16000
amplify: 7792/16000
amplify: 7796/16000
amplify: 7800/16000
amplify: 7804/16000
amplify: 7808/16000
amplify: 7812/16000
amplify: 7816/16000
amplify: 7820/16000
amplify: 7824/16000
amplify: 7828/16000
amplify: 7832/16000
amplify: 7836/16000
amplify: 7840/16000
amplify: 7844/16000
amplify: 7848/16000
amplify: 7852/16000
amplify: 7856/16000
amplify: 7860/16000
amplify: 7864/16000
amplify: 7868/16000
amplify: 7872/16000
amplify: 7876/16000
amplify: 7880/16000
amplify: 7884/16000
amplify: 7888/16000
amplify: 7892/16000
amplify: 7896/16000
amplify: 7900/16000
amplify: 7904/16000
amplify: 7908/16000
amplify: 7912/16000
amplify: 7916/16000
amplify: 7920/16000
amplify: 7924/16000
amplify: 7928/16000
amplify: 7932/16000
amplify: 7936/16000
amplify: 7940/16000
amplify: 7944/16000
amplify: 7948/16000
amplify: 7952/16000
amplify: 7956/16000
amplify: 7960/16000
amplify: 7964/16000
amplify: 7968/16000
amplify: 7972/16000
amplify: 7976/16000
amplify: 7980/16000
amplify: 7984/16000
amplify: 7988/16000
amplify: 7992/16000
amplify: 7996/16000
amplify: 8000/16000
amplify: 8004/16000
amplify: 8008/16000
amplify: 8012/16000
amplify: 8016/16000
amplify: 8020/16000
amplify: 8024/16000
amplify: 8028/16000
amplify: 8032/16000
amplify: 8036/16000
amplify: 8040/16000
amplify: 8044/16000
amplify: 8048/16000
amplify: 8052/16000
amplify: 8056/16000
amplify: 8060/16000
amplify: 8064/16000
amplify: 8068/16000
amplify: 8072/16000
amplify: 8076/16000
amplify: 8080/16000
amplify: 8084/16000
amplify: 8088/16000
amplify: 8092/16000
amplify: 8096/16000
amplify: 8100/16000
amplify: 8104/16000
amplify: 8108/16000
amplify: 8112/16000
amplify: 8116/16000
amplify: 8120/16000
amplify: 8124/16000
amplify: 8128/16000
amplify: 8132/16000
amplify: 8136/16000
amplify: 8140/16000
amplify: 8144/16000
amplify: 8148/16000
amplify: 8152/16000
amplify: 8156/16000
amplify: 8160/16000
amplify: 8164/16000
amplify: 8168/16000
amplify: 8172/16000
amplify: 8176/16000
amplify: 8180/16000
amplify: 8184/16000
amplify: 8188/16000
amplify: 8192/16000
amplify: 8196/16000
amplify: 8200/16000
amplify: 8204/16000
amplify: 8208/16000
amplify: 8212/16000
amplify: 8216/16000
amplify: 8220/16000
amplify: 8224/16000
amplify: 8228/16000
amplify: 8232/16000
amplify: 8236/16000
amplify: 8240/16000
amplify: 8244/16000
amplify: 8248/16000
amplify: 8252/16000
amplify: 8256/16000
amplify: 8260/16000
amplify: 8264/16000
amplify: 8268/16000
amplify: 8272/16000
amplify: 8276/16000
amplify: 8280/16000
amplify: 8284/16000
amplify: 8288/16000
amplify: 8292/16000
amplify: 8296/16000
amplify: 8300/16000
amplify: 8304/16000
amplify: 8308/16000
amplify: 8312/16000
amplify: 8316/16000
amplify: 8320/16000
amplify: 8324/16000
amplify: 8328/16000
amplify: 8332/16000
amplify: 8336/16000
amplify: 8340/16000
amplify: 8344/16000
amplify: 8348/16000
amplify: 8352/16000
amplify: 8356/16000
amplify: 8360/16000
amplify: 8364/16000
amplify: 8368/16000
amplify: 8372/16000
amplify: 8376/16000
amplify: 8380/16000
amplify: 8384/16000
amplify: 8388/16000
amplify: 8392/16000
amplify: 8396/16000
amplify: 8400/16000
amplify: 8404/16000
amplify: 8408/16000
amplify: 8412/16000
amplify: 8416/16000
amplify: 8420/16000
amplify: 8424/16000
amplify: 8428/16000
amplify: 8432/16000
amplify: 8436/16000
amplify: 8440/16000
amplify: 8444/16000
amplify: 8448/16000
amplify: 8452/16000
amplify: 8456/16000
amplify: 8460/16000
amplify: 8464/16000
amplify: 8468/16000
amplify: 8472/16000
amplify: 8476/16000
amplify: 8480/16000
amplify: 8484/16000
amplify: 8488/16000
amplify: 8492/16000
amplify: 8496/16000
amplify: 8500/16000
amplify: 8504/16000
amplify: 8508/16000
amplify: 8512/16000
amplify: 8516/16000
amplify: 8520/16000
amplify: 8524/16000
amplify: 8528/16000
amplify: 8532/16000
amplify: 8536/16000
amplify: 8540/16000
amplify: 8544/16000
amplify: 8548/16000
amplify: 8552/16000
amplify: 8556/16000
amplify: 8560/16000
amplify: 8564/16000
amplify: 8568/16000
amplify: 8572/16000
amplify: 8576/16000
amplify: 8580/16000
amplify: 8584/16000
amplify: 8588/16000
amplify: 8592/16000
amplify: 8596/16000
amplify: 8600/16000
amplify: 8604/16000
amplify: 8608/16000
amplify: 8612/16000
amplify: 8616/16000
amplify: 8620/16000
amplify: 8624/16000
amplify: 8628/16000
amplify: 8632/16000
amplify: 8636/16000
amplify: 8640/16000
amplify: 8644/16000
amplify: 8648/16000
amplify: 8652/16000
amplify: 8656/16000
amplify: 8660/16000
amplify: 8664/16000
amplify: 8668/16000

amplify: 8672/16000
amplify: 8676/16000
amplify: 8680/16000
amplify: 8684/16000
amplify: 8688/16000
amplify: 8692/16000
amplify: 8696/16000
amplify: 8700/16000
amplify: 8704/16000
amplify: 8708/16000
amplify: 8712/16000
amplify: 8716/16000
amplify: 8720/16000
amplify: 8724/16000
amplify: 8728/16000
amplify: 8732/16000
amplify: 8736/16000
amplify: 8740/16000
amplify: 8744/16000
amplify: 8748/16000
amplify: 8752/16000
amplify: 8756/16000
amplify: 8760/16000
amplify: 8764/16000
amplify: 8768/16000
amplify: 8772/16000
amplify: 8776/16000
amplify: 8780/16000
amplify: 8784/16000
amplify: 8788/16000
amplify: 8792/16000
amplify: 8796/16000
amplify: 8800/16000
amplify: 8804/16000
amplify: 8808/16000
amplify: 8812/16000
amplify: 8816/16000
amplify: 8820/16000
amplify: 8824/16000
amplify: 8828/16000
amplify: 8832/16000
amplify: 8836/16000
amplify: 8840/16000
amplify: 8844/16000
amplify: 8848/16000
amplify: 8852/16000
amplify: 8856/16000
amplify: 8860/16000
amplify: 8864/16000
amplify: 8868/16000
amplify: 8872/16000
amplify: 8876/16000
amplify: 8880/16000
amplify: 8884/16000
amplify: 8888/16000
amplify: 8892/16000
amplify: 8896/16000
amplify: 8900/16000
amplify: 8904/16000
amplify: 8908/16000
amplify: 8912/16000
amplify: 8916/16000
amplify: 8920/16000
amplify: 8924/16000
amplify: 8928/16000
amplify: 8932/16000
amplify: 8936/16000
amplify: 8940/16000
amplify: 8944/16000
amplify: 8948/16000
amplify: 8952/16000
amplify: 8956/16000
amplify: 8960/16000
amplify: 8964/16000
amplify: 8968/16000
amplify: 8972/16000
amplify: 8976/16000
amplify: 8980/16000
amplify: 8984/16000
amplify: 8988/16000
amplify: 8992/16000
amplify: 8996/16000
amplify: 9000/16000
amplify: 9004/16000
amplify: 9008/16000
amplify: 9012/16000
amplify: 9016/16000
amplify: 9020/16000
amplify: 9024/16000
amplify: 9028/16000
amplify: 9032/16000
amplify: 9036/16000
amplify: 9040/16000
amplify: 9044/16000
amplify: 9048/16000
amplify: 9052/16000
amplify: 9056/16000
amplify: 9060/16000
amplify: 9064/16000
amplify: 9068/16000
amplify: 9072/16000
amplify: 9076/16000
amplify: 9080/16000
amplify: 9084/16000
amplify: 9088/16000
amplify: 9092/16000
amplify: 9096/16000
amplify: 9100/16000
amplify: 9104/16000
amplify: 9108/16000
amplify: 9112/16000
amplify: 9116/16000
amplify: 9120/16000
amplify: 9124/16000
amplify: 9128/16000
amplify: 9132/16000
amplify: 9136/16000
amplify: 9140/16000
amplify: 9144/16000
amplify: 9148/16000
amplify: 9152/16000
amplify: 9156/16000
amplify: 9160/16000
amplify: 9164/16000
amplify: 9168/16000
amplify: 9172/16000
amplify: 9176/16000
amplify: 9180/16000
amplify: 9184/16000
amplify: 9188/16000
amplify: 9192/16000
amplify: 9196/16000
amplify: 9200/16000
amplify: 9204/16000
amplify: 9208/16000
amplify: 9212/16000
amplify: 9216/16000
amplify: 9220/16000
amplify: 9224/16000
amplify: 9228/16000
amplify: 9232/16000
amplify: 9236/16000
amplify: 9240/16000
amplify: 9244/16000
amplify: 9248/16000
amplify: 9252/16000
amplify: 9256/16000
amplify: 9260/16000
amplify: 9264/16000
amplify: 9268/16000
amplify: 9272/16000
amplify: 9276/16000
amplify: 9280/16000
amplify: 9284/16000
amplify: 9288/16000
amplify: 9292/16000
amplify: 9296/16000
amplify: 9300/16000
amplify: 9304/16000
amplify: 9308/16000
amplify: 9312/16000
amplify: 9316/16000
amplify: 9320/16000
amplify: 9324/16000
amplify: 9328/16000
amplify: 9332/16000
amplify: 9336/16000
amplify: 9340/16000
amplify: 9344/16000
amplify: 9348/16000
amplify: 9352/16000
amplify: 9356/16000
amplify: 9360/16000
amplify: 9364/16000
amplify: 9368/16000
amplify: 9372/16000
amplify: 9376/16000
amplify: 9380/16000
amplify: 9384/16000
amplify: 9388/16000
amplify: 9392/16000
amplify: 9396/16000
amplify: 9400/16000
amplify: 9404/16000
amplify: 9408/16000
amplify: 9412/16000
amplify: 9416/16000
amplify: 9420/16000
amplify: 9424/16000
amplify: 9428/16000
amplify: 9432/16000
amplify: 9436/16000
amplify: 9440/16000
amplify: 9444/16000
amplify: 9448/16000
amplify: 9452/16000
amplify: 9456/16000
amplify: 9460/16000
amplify: 9464/16000
amplify: 9468/16000
amplify: 9472/16000
amplify: 9476/16000
amplify: 9480/16000
amplify: 9484/16000
amplify: 9488/16000
amplify: 9492/16000
amplify: 9496/16000
amplify: 9500/16000
amplify: 9504/16000
amplify: 9508/16000
amplify: 9512/16000
amplify: 9516/16000
amplify: 9520/16000
amplify: 9524/16000
amplify: 9528/16000
amplify: 9532/16000
amplify: 9536/16000
amplify: 9540/16000
amplify: 9544/16000
amplify: 9548/16000
amplify: 9552/16000
amplify: 9556/16000
amplify: 9560/16000
amplify: 9564/16000
amplify: 9568/16000
amplify: 9572/16000
amplify: 9576/16000
amplify: 9580/16000
amplify: 9584/16000
amplify: 9588/16000
amplify: 9592/16000
amplify: 9596/16000
amplify: 9600/16000
amplify: 9604/16000
amplify: 9608/16000
amplify: 9612/16000
amplify: 9616/16000
amplify: 9620/16000
amplify: 9624/16000
amplify: 9628/16000
amplify: 9632/16000
amplify: 9636/16000
amplify: 9640/16000
amplify: 9644/16000
amplify: 9648/16000
amplify: 9652/16000
amplify: 9656/16000
amplify: 9660/16000
amplify: 9664/16000
amplify: 9668/16000
amplify: 9672/16000
amplify: 9676/16000
amplify: 9680/16000
amplify: 9684/16000
amplify: 9688/16000
amplify: 9692/16000
amplify: 9696/16000
amplify: 9700/16000
amplify: 9704/16000
amplify: 9708/16000
amplify: 9712/16000
amplify: 9716/16000
amplify: 9720/16000
amplify: 9724/16000
amplify: 9728/16000
amplify: 9732/16000
amplify: 9736/16000
amplify: 9740/16000
amplify: 9744/16000
amplify: 9748/16000
amplify: 9752/16000
amplify: 9756/16000
amplify: 9760/16000
amplify: 9764/16000
amplify: 9768/16000
amplify: 9772/16000
amplify: 9776/16000
amplify: 9780/16000
amplify: 9784/16000
amplify: 9788/16000
amplify: 9792/16000
amplify: 9796/16000
amplify: 9800/16000
amplify: 9804/16000
amplify: 9808/16000
amplify: 9812/16000
amplify: 9816/16000
amplify: 9820/16000
amplify: 9824/16000
amplify: 9828/16000
amplify: 9832/16000
amplify: 9836/16000
amplify: 9840/16000
amplify: 9844/16000
amplify: 9848/16000
amplify: 9852/16000
amplify: 9856/16000
amplify: 9860/16000
amplify: 9864/16000
amplify: 9868/16000
amplify: 9872/16000
amplify: 9876/16000
amplify: 9880/16000
amplify: 9884/16000
amplify: 9888/16000
amplify: 9892/16000
amplify: 9896/16000
amplify: 9900/16000
amplify: 9904/16000
amplify: 9908/16000
amplify: 9912/16000
amplify: 9916/16000
amplify: 9920/16000
amplify: 9924/16000
amplify: 9928/16000
amplify: 9932/16000
amplify: 9936/16000
amplify: 9940/16000
amplify: 9944/16000
amplify: 9948/16000
amplify: 9952/16000
amplify: 9956/16000
amplify: 9960/16000
amplify: 9964/16000
amplify: 9968/16000
amplify: 9972/16000
amplify: 9976/16000
amplify: 9980/16000
amplify: 9984/16000
amplify: 9988/16000
amplify: 9992/16000
amplify: 9996/16000
amplify: 10000/16000
amplify: 10004/16000
amplify: 10008/16000
amplify: 10012/16000
amplify: 10016/16000
amplify: 10020/16000
amplify: 10024/16000
amplify: 10028/16000
amplify: 10032/16000
amplify: 10036/16000
amplify: 10040/16000
amplify: 10044/16000
amplify: 10048/16000
amplify: 10052/16000
amplify: 10056/16000
amplify: 10060/16000
amplify: 10064/16000
amplify: 10068/16000
amplify: 10072/16000
amplify: 10076/16000
amplify: 10080/16000
amplify: 10084/16000
amplify: 10088/16000
amplify: 10092/16000
amplify: 10096/16000
amplify: 10100/16000
amplify: 10104/16000
amplify: 10108/16000
amplify: 10112/16000
amplify: 10116/16000
amplify: 10120/16000
amplify: 10124/16000
amplify: 10128/16000
amplify: 10132/16000
amplify: 10136/16000
amplify: 10140/16000
amplify: 10144/16000
amplify: 10148/16000
amplify: 10152/16000
amplify: 10156/16000
amplify: 10160/16000
amplify: 10164/16000
amplify: 10168/16000
amplify: 10172/16000
amplify: 10176/16000
amplify: 10180/16000
amplify: 10184/16000
amplify: 10188/16000
amplify: 10192/16000
amplify: 10196/16000
amplify: 10200/16000
amplify: 10204/16000
amplify: 10208/16000
amplify: 10212/16000
amplify: 10216/16000
amplify: 10220/16000
amplify: 10224/16000
amplify: 10228/16000
amplify: 10232/16000
amplify: 10236/16000
amplify: 10240/16000
amplify: 10244/16000
amplify: 10248/16000
amplify: 10252/16000
amplify: 10256/16000
amplify: 10260/16000
amplify: 10264/16000
amplify: 10268/16000
amplify: 10272/16000
amplify: 10276/16000
amplify: 10280/16000
amplify: 10284/16000
amplify: 10288/16000
amplify: 10292/16000

amplify: 10296/16000
amplify: 10300/16000
amplify: 10304/16000
amplify: 10308/16000
amplify: 10312/16000
amplify: 10316/16000
amplify: 10320/16000
amplify: 10324/16000
amplify: 10328/16000
amplify: 10332/16000
amplify: 10336/16000
amplify: 10340/16000
amplify: 10344/16000
amplify: 10348/16000
amplify: 10352/16000
amplify: 10356/16000
amplify: 10360/16000
amplify: 10364/16000
amplify: 10368/16000
amplify: 10372/16000
amplify: 10376/16000
amplify: 10380/16000
amplify: 10384/16000
amplify: 10388/16000
amplify: 10392/16000
amplify: 10396/16000
amplify: 10400/16000
amplify: 10404/16000
amplify: 10408/16000
amplify: 10412/16000
amplify: 10416/16000
amplify: 10420/16000
amplify: 10424/16000
amplify: 10428/16000
amplify: 10432/16000
amplify: 10436/16000
amplify: 10440/16000
amplify: 10444/16000
amplify: 10448/16000
amplify: 10452/16000
amplify: 10456/16000
amplify: 10460/16000
amplify: 10464/16000
amplify: 10468/16000
amplify: 10472/16000
amplify: 10476/16000
amplify: 10480/16000
amplify: 10484/16000
amplify: 10488/16000
amplify: 10492/16000
amplify: 10496/16000
amplify: 10500/16000
amplify: 10504/16000
amplify: 10508/16000
amplify: 10512/16000
amplify: 10516/16000
amplify: 10520/16000
amplify: 10524/16000
amplify: 10528/16000
amplify: 10532/16000
amplify: 10536/16000
amplify: 10540/16000
amplify: 10544/16000
amplify: 10548/16000
amplify: 10552/16000
amplify: 10556/16000
amplify: 10560/16000
amplify: 10564/16000
amplify: 10568/16000
amplify: 10572/16000
amplify: 10576/16000
amplify: 10580/16000
amplify: 10584/16000
amplify: 10588/16000
amplify: 10592/16000
amplify: 10596/16000
amplify: 10600/16000
amplify: 10604/16000
amplify: 10608/16000
amplify: 10612/16000
amplify: 10616/16000
amplify: 10620/16000
amplify: 10624/16000
amplify: 10628/16000
amplify: 10632/16000
amplify: 10636/16000
amplify: 10640/16000
amplify: 10644/16000
amplify: 10648/16000
amplify: 10652/16000
amplify: 10656/16000
amplify: 10660/16000
amplify: 10664/16000
amplify: 10668/16000
amplify: 10672/16000
amplify: 10676/16000
amplify: 10680/16000
amplify: 10684/16000
amplify: 10688/16000
amplify: 10692/16000
amplify: 10696/16000
amplify: 10700/16000
amplify: 10704/16000
amplify: 10708/16000
amplify: 10712/16000
amplify: 10716/16000
amplify: 10720/16000
amplify: 10724/16000
amplify: 10728/16000
amplify: 10732/16000
amplify: 10736/16000
amplify: 10740/16000
amplify: 10744/16000
amplify: 10748/16000
amplify: 10752/16000
amplify: 10756/16000
amplify: 10760/16000
amplify: 10764/16000
amplify: 10768/16000
amplify: 10772/16000
amplify: 10776/16000
amplify: 10780/16000
amplify: 10784/16000
amplify: 10788/16000
amplify: 10792/16000
amplify: 10796/16000
amplify: 10800/16000
amplify: 10804/16000
amplify: 10808/16000
amplify: 10812/16000
amplify: 10816/16000
amplify: 10820/16000
amplify: 10824/16000
amplify: 10828/16000
amplify: 10832/16000
amplify: 10836/16000
amplify: 10840/16000
amplify: 10844/16000
amplify: 10848/16000
amplify: 10852/16000
amplify: 10856/16000
amplify: 10860/16000
amplify: 10864/16000
amplify: 10868/16000
amplify: 10872/16000
amplify: 10876/16000
amplify: 10880/16000
amplify: 10884/16000
amplify: 10888/16000
amplify: 10892/16000
amplify: 10896/16000
amplify: 10900/16000
amplify: 10904/16000
amplify: 10908/16000
amplify: 10912/16000
amplify: 10916/16000
amplify: 10920/16000
amplify: 10924/16000
amplify: 10928/16000
amplify: 10932/16000
amplify: 10936/16000
amplify: 10940/16000
amplify: 10944/16000
amplify: 10948/16000
amplify: 10952/16000
amplify: 10956/16000
amplify: 10960/16000
amplify: 10964/16000
amplify: 10968/16000
amplify: 10972/16000
amplify: 10976/16000
amplify: 10980/16000
amplify: 10984/16000
amplify: 10988/16000
amplify: 10992/16000
amplify: 10996/16000
amplify: 11000/16000
amplify: 11004/16000
amplify: 11008/16000
amplify: 11012/16000
amplify: 11016/16000
amplify: 11020/16000
amplify: 11024/16000
amplify: 11028/16000
amplify: 11032/16000
amplify: 11036/16000
amplify: 11040/16000
amplify: 11044/16000
amplify: 11048/16000
amplify: 11052/16000
amplify: 11056/16000
amplify: 11060/16000
amplify: 11064/16000
amplify: 11068/16000
amplify: 11072/16000
amplify: 11076/16000
amplify: 11080/16000
amplify: 11084/16000
amplify: 11088/16000
amplify: 11092/16000
amplify: 11096/16000
amplify: 11100/16000
amplify: 11104/16000
amplify: 11108/16000
amplify: 11112/16000
amplify: 11116/16000
amplify: 11120/16000
amplify: 11124/16000
amplify: 11128/16000
amplify: 11132/16000
amplify: 11136/16000
amplify: 11140/16000
amplify: 11144/16000
amplify: 11148/16000
amplify: 11152/16000
amplify: 11156/16000
amplify: 11160/16000
amplify: 11164/16000
amplify: 11168/16000
amplify: 11172/16000
amplify: 11176/16000
amplify: 11180/16000
amplify: 11184/16000
amplify: 11188/16000
amplify: 11192/16000
amplify: 11196/16000
amplify: 11200/16000
amplify: 11204/16000
amplify: 11208/16000
amplify: 11212/16000
amplify: 11216/16000
amplify: 11220/16000
amplify: 11224/16000
amplify: 11228/16000
amplify: 11232/16000
amplify: 11236/16000
amplify: 11240/16000
amplify: 11244/16000
amplify: 11248/16000
amplify: 11252/16000
amplify: 11256/16000
amplify: 11260/16000
amplify: 11264/16000
amplify: 11268/16000
amplify: 11272/16000
amplify: 11276/16000
amplify: 11280/16000
amplify: 11284/16000
amplify: 11288/16000
amplify: 11292/16000
amplify: 11296/16000
amplify: 11300/16000
amplify: 11304/16000
amplify: 11308/16000
amplify: 11312/16000
amplify: 11316/16000
amplify: 11320/16000
amplify: 11324/16000
amplify: 11328/16000
amplify: 11332/16000
amplify: 11336/16000
amplify: 11340/16000
amplify: 11344/16000
amplify: 11348/16000
amplify: 11352/16000
amplify: 11356/16000
amplify: 11360/16000
amplify: 11364/16000
amplify: 11368/16000
amplify: 11372/16000
amplify: 11376/16000
amplify: 11380/16000
amplify: 11384/16000
amplify: 11388/16000
amplify: 11392/16000
amplify: 11396/16000
amplify: 11400/16000
amplify: 11404/16000
amplify: 11408/16000
amplify: 11412/16000
amplify: 11416/16000
amplify: 11420/16000
amplify: 11424/16000
amplify: 11428/16000
amplify: 11432/16000
amplify: 11436/16000
amplify: 11440/16000
amplify: 11444/16000
amplify: 11448/16000
amplify: 11452/16000
amplify: 11456/16000
amplify: 11460/16000
amplify: 11464/16000
amplify: 11468/16000
amplify: 11472/16000
amplify: 11476/16000
amplify: 11480/16000
amplify: 11484/16000
amplify: 11488/16000
amplify: 11492/16000
amplify: 11496/16000
amplify: 11500/16000
amplify: 11504/16000
amplify: 11508/16000
amplify: 11512/16000
amplify: 11516/16000
amplify: 11520/16000
amplify: 11524/16000
amplify: 11528/16000
amplify: 11532/16000
amplify: 11536/16000
amplify: 11540/16000
amplify: 11544/16000
amplify: 11548/16000
amplify: 11552/16000
amplify: 11556/16000
amplify: 11560/16000
amplify: 11564/16000
amplify: 11568/16000
amplify: 11572/16000
amplify: 11576/16000
amplify: 11580/16000
amplify: 11584/16000
amplify: 11588/16000
amplify: 11592/16000
amplify: 11596/16000
amplify: 11600/16000
amplify: 11604/16000
amplify: 11608/16000
amplify: 11612/16000
amplify: 11616/16000
amplify: 11620/16000
amplify: 11624/16000
amplify: 11628/16000
amplify: 11632/16000
amplify: 11636/16000
amplify: 11640/16000
amplify: 11644/16000
amplify: 11648/16000
amplify: 11652/16000
amplify: 11656/16000
amplify: 11660/16000
amplify: 11664/16000
amplify: 11668/16000
amplify: 11672/16000
amplify: 11676/16000
amplify: 11680/16000
amplify: 11684/16000
amplify: 11688/16000
amplify: 11692/16000
amplify: 11696/16000
amplify: 11700/16000
amplify: 11704/16000
amplify: 11708/16000
amplify: 11712/16000
amplify: 11716/16000
amplify: 11720/16000
amplify: 11724/16000
amplify: 11728/16000
amplify: 11732/16000
amplify: 11736/16000
amplify: 11740/16000
amplify: 11744/16000
amplify: 11748/16000
amplify: 11752/16000
amplify: 11756/16000
amplify: 11760/16000
amplify: 11764/16000
amplify: 11768/16000
amplify: 11772/16000
amplify: 11776/16000
amplify: 11780/16000
amplify: 11784/16000
amplify: 11788/16000
amplify: 11792/16000
amplify: 11796/16000
amplify: 11800/16000
amplify: 11804/16000
amplify: 11808/16000
amplify: 11812/16000
amplify: 11816/16000
amplify: 11820/16000
amplify: 11824/16000
amplify: 11828/16000
amplify: 11832/16000
amplify: 11836/16000
amplify: 11840/16000
amplify: 11844/16000
amplify: 11848/16000
amplify: 11852/16000
amplify: 11856/16000

amplify: 11860/16000
amplify: 11864/16000
amplify: 11868/16000
amplify: 11872/16000
amplify: 11876/16000
amplify: 11880/16000
amplify: 11884/16000
amplify: 11888/16000
amplify: 11892/16000
amplify: 11896/16000
amplify: 11900/16000
amplify: 11904/16000
amplify: 11908/16000
amplify: 11912/16000
amplify: 11916/16000
amplify: 11920/16000
amplify: 11924/16000
amplify: 11928/16000
amplify: 11932/16000
amplify: 11936/16000
amplify: 11940/16000
amplify: 11944/16000
amplify: 11948/16000
amplify: 11952/16000
amplify: 11956/16000
amplify: 11960/16000
amplify: 11964/16000
amplify: 11968/16000
amplify: 11972/16000
amplify: 11976/16000
amplify: 11980/16000
amplify: 11984/16000
amplify: 11988/16000
amplify: 11992/16000
amplify: 11996/16000
amplify: 12000/16000
amplify: 12004/16000
amplify: 12008/16000
amplify: 12012/16000
amplify: 12016/16000
amplify: 12020/16000
amplify: 12024/16000
amplify: 12028/16000
amplify: 12032/16000
amplify: 12036/16000
amplify: 12040/16000
amplify: 12044/16000
amplify: 12048/16000
amplify: 12052/16000
amplify: 12056/16000
amplify: 12060/16000
amplify: 12064/16000
amplify: 12068/16000
amplify: 12072/16000
amplify: 12076/16000
amplify: 12080/16000
amplify: 12084/16000
amplify: 12088/16000
amplify: 12092/16000
amplify: 12096/16000
amplify: 12100/16000
amplify: 12104/16000
amplify: 12108/16000
amplify: 12112/16000
amplify: 12116/16000
amplify: 12120/16000
amplify: 12124/16000
amplify: 12128/16000
amplify: 12132/16000
amplify: 12136/16000
amplify: 12140/16000
amplify: 12144/16000
amplify: 12148/16000
amplify: 12152/16000
amplify: 12156/16000
amplify: 12160/16000
amplify: 12164/16000
amplify: 12168/16000
amplify: 12172/16000
amplify: 12176/16000
amplify: 12180/16000
amplify: 12184/16000
amplify: 12188/16000
amplify: 12192/16000
amplify: 12196/16000
amplify: 12200/16000
amplify: 12204/16000
amplify: 12208/16000
amplify: 12212/16000
amplify: 12216/16000
amplify: 12220/16000
amplify: 12224/16000
amplify: 12228/16000
amplify: 12232/16000
amplify: 12236/16000
amplify: 12240/16000
amplify: 12244/16000
amplify: 12248/16000
amplify: 12252/16000
amplify: 12256/16000
amplify: 12260/16000
amplify: 12264/16000
amplify: 12268/16000
amplify: 12272/16000
amplify: 12276/16000
amplify: 12280/16000
amplify: 12284/16000
amplify: 12288/16000
amplify: 12292/16000
amplify: 12296/16000
amplify: 12300/16000
amplify: 12304/16000
amplify: 12308/16000
amplify: 12312/16000
amplify: 12316/16000
amplify: 12320/16000
amplify: 12324/16000
amplify: 12328/16000
amplify: 12332/16000
amplify: 12336/16000
amplify: 12340/16000
amplify: 12344/16000
amplify: 12348/16000
amplify: 12352/16000
amplify: 12356/16000
amplify: 12360/16000
amplify: 12364/16000
amplify: 12368/16000
amplify: 12372/16000
amplify: 12376/16000
amplify: 12380/16000
amplify: 12384/16000
amplify: 12388/16000
amplify: 12392/16000
amplify: 12396/16000
amplify: 12400/16000
amplify: 12404/16000
amplify: 12408/16000
amplify: 12412/16000
amplify: 12416/16000
amplify: 12420/16000
amplify: 12424/16000
amplify: 12428/16000
amplify: 12432/16000
amplify: 12436/16000
amplify: 12440/16000
amplify: 12444/16000
amplify: 12448/16000
amplify: 12452/16000
amplify: 12456/16000
amplify: 12460/16000
amplify: 12464/16000
amplify: 12468/16000
amplify: 12472/16000
amplify: 12476/16000
amplify: 12480/16000
amplify: 12484/16000
amplify: 12488/16000
amplify: 12492/16000
amplify: 12496/16000
amplify: 12500/16000
amplify: 12504/16000
amplify: 12508/16000
amplify: 12512/16000
amplify: 12516/16000
amplify: 12520/16000
amplify: 12524/16000
amplify: 12528/16000
amplify: 12532/16000
amplify: 12536/16000
amplify: 12540/16000
amplify: 12544/16000
amplify: 12548/16000
amplify: 12552/16000
amplify: 12556/16000
amplify: 12560/16000
amplify: 12564/16000
amplify: 12568/16000
amplify: 12572/16000
amplify: 12576/16000
amplify: 12580/16000
amplify: 12584/16000
amplify: 12588/16000
amplify: 12592/16000
amplify: 12596/16000
amplify: 12600/16000
amplify: 12604/16000
amplify: 12608/16000
amplify: 12612/16000
amplify: 12616/16000
amplify: 12620/16000
amplify: 12624/16000
amplify: 12628/16000
amplify: 12632/16000
amplify: 12636/16000
amplify: 12640/16000
amplify: 12644/16000
amplify: 12648/16000
amplify: 12652/16000
amplify: 12656/16000
amplify: 12660/16000
amplify: 12664/16000
amplify: 12668/16000
amplify: 12672/16000
amplify: 12676/16000
amplify: 12680/16000
amplify: 12684/16000
amplify: 12688/16000
amplify: 12692/16000
amplify: 12696/16000
amplify: 12700/16000
amplify: 12704/16000
amplify: 12708/16000
amplify: 12712/16000
amplify: 12716/16000
amplify: 12720/16000
amplify: 12724/16000
amplify: 12728/16000
amplify: 12732/16000
amplify: 12736/16000
amplify: 12740/16000
amplify: 12744/16000
amplify: 12748/16000
amplify: 12752/16000
amplify: 12756/16000
amplify: 12760/16000
amplify: 12764/16000
amplify: 12768/16000
amplify: 12772/16000
amplify: 12776/16000
amplify: 12780/16000
amplify: 12784/16000
amplify: 12788/16000
amplify: 12792/16000
amplify: 12796/16000
amplify: 12800/16000
amplify: 12804/16000
amplify: 12808/16000
amplify: 12812/16000
amplify: 12816/16000
amplify: 12820/16000
amplify: 12824/16000
amplify: 12828/16000
amplify: 12832/16000
amplify: 12836/16000
amplify: 12840/16000
amplify: 12844/16000
amplify: 12848/16000
amplify: 12852/16000
amplify: 12856/16000
amplify: 12860/16000
amplify: 12864/16000
amplify: 12868/16000
amplify: 12872/16000
amplify: 12876/16000
amplify: 12880/16000
amplify: 12884/16000
amplify: 12888/16000
amplify: 12892/16000
amplify: 12896/16000
amplify: 12900/16000
amplify: 12904/16000
amplify: 12908/16000
amplify: 12912/16000
amplify: 12916/16000
amplify: 12920/16000
amplify: 12924/16000
amplify: 12928/16000
amplify: 12932/16000
amplify: 12936/16000
amplify: 12940/16000
amplify: 12944/16000
amplify: 12948/16000
amplify: 12952/16000
amplify: 12956/16000
amplify: 12960/16000
amplify: 12964/16000
amplify: 12968/16000
amplify: 12972/16000
amplify: 12976/16000
amplify: 12980/16000
amplify: 12984/16000
amplify: 12988/16000
amplify: 12992/16000
amplify: 12996/16000
amplify: 13000/16000
amplify: 13004/16000
amplify: 13008/16000
amplify: 13012/16000
amplify: 13016/16000
amplify: 13020/16000
amplify: 13024/16000
amplify: 13028/16000
amplify: 13032/16000
amplify: 13036/16000
amplify: 13040/16000
amplify: 13044/16000
amplify: 13048/16000
amplify: 13052/16000
amplify: 13056/16000
amplify: 13060/16000
amplify: 13064/16000
amplify: 13068/16000
amplify: 13072/16000
amplify: 13076/16000
amplify: 13080/16000
amplify: 13084/16000
amplify: 13088/16000
amplify: 13092/16000
amplify: 13096/16000
amplify: 13100/16000
amplify: 13104/16000
amplify: 13108/16000
amplify: 13112/16000
amplify: 13116/16000
amplify: 13120/16000
amplify: 13124/16000
amplify: 13128/16000
amplify: 13132/16000
amplify: 13136/16000
amplify: 13140/16000
amplify: 13144/16000
amplify: 13148/16000
amplify: 13152/16000
amplify: 13156/16000
amplify: 13160/16000
amplify: 13164/16000
amplify: 13168/16000
amplify: 13172/16000
amplify: 13176/16000
amplify: 13180/16000
amplify: 13184/16000
amplify: 13188/16000
amplify: 13192/16000
amplify: 13196/16000
amplify: 13200/16000
amplify: 13204/16000
amplify: 13208/16000
amplify: 13212/16000
amplify: 13216/16000
amplify: 13220/16000
amplify: 13224/16000
amplify: 13228/16000
amplify: 13232/16000
amplify: 13236/16000
amplify: 13240/16000
amplify: 13244/16000
amplify: 13248/16000
amplify: 13252/16000
amplify: 13256/16000
amplify: 13260/16000
amplify: 13264/16000
amplify: 13268/16000
amplify: 13272/16000
amplify: 13276/16000
amplify: 13280/16000
amplify: 13284/16000
amplify: 13288/16000
amplify: 13292/16000
amplify: 13296/16000
amplify: 13300/16000
amplify: 13304/16000
amplify: 13308/16000
amplify: 13312/16000
amplify: 13316/16000
amplify: 13320/16000
amplify: 13324/16000
amplify: 13328/16000
amplify: 13332/16000
amplify: 13336/16000
amplify: 13340/16000
amplify: 13344/16000
amplify: 13348/16000
amplify: 13352/16000
amplify: 13356/16000
amplify: 13360/16000
amplify: 13364/16000
amplify: 13368/16000
amplify: 13372/16000
amplify: 13376/16000
amplify: 13380/16000
amplify: 13384/16000
amplify: 13388/16000
amplify: 13392/16000
amplify: 13396/16000
amplify: 13400/16000
amplify: 13404/16000
amplify: 13408/16000
amplify: 13412/16000
amplify: 13416/16000
amplify: 13420/16000
amplify: 13424/16000
amplify: 13428/16000

amplify: 13432/16000
amplify: 13436/16000
amplify: 13440/16000
amplify: 13444/16000
amplify: 13448/16000
amplify: 13452/16000
amplify: 13456/16000
amplify: 13460/16000
amplify: 13464/16000
amplify: 13468/16000
amplify: 13472/16000
amplify: 13476/16000
amplify: 13480/16000
amplify: 13484/16000
amplify: 13488/16000
amplify: 13492/16000
amplify: 13496/16000
amplify: 13500/16000
amplify: 13504/16000
amplify: 13508/16000
amplify: 13512/16000
amplify: 13516/16000
amplify: 13520/16000
amplify: 13524/16000
amplify: 13528/16000
amplify: 13532/16000
amplify: 13536/16000
amplify: 13540/16000
amplify: 13544/16000
amplify: 13548/16000
amplify: 13552/16000
amplify: 13556/16000
amplify: 13560/16000
amplify: 13564/16000
amplify: 13568/16000
amplify: 13572/16000
amplify: 13576/16000
amplify: 13580/16000
amplify: 13584/16000
amplify: 13588/16000
amplify: 13592/16000
amplify: 13596/16000
amplify: 13600/16000
amplify: 13604/16000
amplify: 13608/16000
amplify: 13612/16000
amplify: 13616/16000
amplify: 13620/16000
amplify: 13624/16000
amplify: 13628/16000
amplify: 13632/16000
amplify: 13636/16000
amplify: 13640/16000
amplify: 13644/16000
amplify: 13648/16000
amplify: 13652/16000
amplify: 13656/16000
amplify: 13660/16000
amplify: 13664/16000
amplify: 13668/16000
amplify: 13672/16000
amplify: 13676/16000
amplify: 13680/16000
amplify: 13684/16000
amplify: 13688/16000
amplify: 13692/16000
amplify: 13696/16000
amplify: 13700/16000
amplify: 13704/16000
amplify: 13708/16000
amplify: 13712/16000
amplify: 13716/16000
amplify: 13720/16000
amplify: 13724/16000
amplify: 13728/16000
amplify: 13732/16000
amplify: 13736/16000
amplify: 13740/16000
amplify: 13744/16000
amplify: 13748/16000
amplify: 13752/16000
amplify: 13756/16000
amplify: 13760/16000
amplify: 13764/16000
amplify: 13768/16000
amplify: 13772/16000
amplify: 13776/16000
amplify: 13780/16000
amplify: 13784/16000
amplify: 13788/16000
amplify: 13792/16000
amplify: 13796/16000
amplify: 13800/16000
amplify: 13804/16000
amplify: 13808/16000
amplify: 13812/16000
amplify: 13816/16000
amplify: 13820/16000
amplify: 13824/16000
amplify: 13828/16000
amplify: 13832/16000
amplify: 13836/16000
amplify: 13840/16000
amplify: 13844/16000
amplify: 13848/16000
amplify: 13852/16000
amplify: 13856/16000
amplify: 13860/16000
amplify: 13864/16000
amplify: 13868/16000
amplify: 13872/16000
amplify: 13876/16000
amplify: 13880/16000
amplify: 13884/16000
amplify: 13888/16000
amplify: 13892/16000
amplify: 13896/16000
amplify: 13900/16000
amplify: 13904/16000
amplify: 13908/16000
amplify: 13912/16000
amplify: 13916/16000
amplify: 13920/16000
amplify: 13924/16000
amplify: 13928/16000
amplify: 13932/16000
amplify: 13936/16000
amplify: 13940/16000
amplify: 13944/16000
amplify: 13948/16000
amplify: 13952/16000
amplify: 13956/16000
amplify: 13960/16000
amplify: 13964/16000
amplify: 13968/16000
amplify: 13972/16000
amplify: 13976/16000
amplify: 13980/16000
amplify: 13984/16000
amplify: 13988/16000
amplify: 13992/16000
amplify: 13996/16000
amplify: 14000/16000
amplify: 14004/16000
amplify: 14008/16000
amplify: 14012/16000
amplify: 14016/16000
amplify: 14020/16000
amplify: 14024/16000
amplify: 14028/16000
amplify: 14032/16000
amplify: 14036/16000
amplify: 14040/16000
amplify: 14044/16000
amplify: 14048/16000
amplify: 14052/16000
amplify: 14056/16000
amplify: 14060/16000
amplify: 14064/16000
amplify: 14068/16000
amplify: 14072/16000
amplify: 14076/16000
amplify: 14080/16000
amplify: 14084/16000
amplify: 14088/16000
amplify: 14092/16000
amplify: 14096/16000
amplify: 14100/16000
amplify: 14104/16000
amplify: 14108/16000
amplify: 14112/16000
amplify: 14116/16000
amplify: 14120/16000
amplify: 14124/16000
amplify: 14128/16000
amplify: 14132/16000
amplify: 14136/16000
amplify: 14140/16000
amplify: 14144/16000
amplify: 14148/16000
amplify: 14152/16000
amplify: 14156/16000
amplify: 14160/16000
amplify: 14164/16000
amplify: 14168/16000
amplify: 14172/16000
amplify: 14176/16000
amplify: 14180/16000
amplify: 14184/16000
amplify: 14188/16000
amplify: 14192/16000
amplify: 14196/16000
amplify: 14200/16000
amplify: 14204/16000
amplify: 14208/16000
amplify: 14212/16000
amplify: 14216/16000
amplify: 14220/16000
amplify: 14224/16000
amplify: 14228/16000
amplify: 14232/16000
amplify: 14236/16000
amplify: 14240/16000
amplify: 14244/16000
amplify: 14248/16000
amplify: 14252/16000
amplify: 14256/16000
amplify: 14260/16000
amplify: 14264/16000
amplify: 14268/16000
amplify: 14272/16000
amplify: 14276/16000
amplify: 14280/16000
amplify: 14284/16000
amplify: 14288/16000
amplify: 14292/16000
amplify: 14296/16000
amplify: 14300/16000
amplify: 14304/16000
amplify: 14308/16000
amplify: 14312/16000
amplify: 14316/16000
amplify: 14320/16000
amplify: 14324/16000
amplify: 14328/16000
amplify: 14332/16000
amplify: 14336/16000
amplify: 14340/16000
amplify: 14344/16000
amplify: 14348/16000
amplify: 14352/16000
amplify: 14356/16000
amplify: 14360/16000
amplify: 14364/16000
amplify: 14368/16000
amplify: 14372/16000
amplify: 14376/16000
amplify: 14380/16000
amplify: 14384/16000
amplify: 14388/16000
amplify: 14392/16000
amplify: 14396/16000
amplify: 14400/16000
amplify: 14404/16000
amplify: 14408/16000
amplify: 14412/16000
amplify: 14416/16000
amplify: 14420/16000
amplify: 14424/16000
amplify: 14428/16000
amplify: 14432/16000
amplify: 14436/16000
amplify: 14440/16000
amplify: 14444/16000
amplify: 14448/16000
amplify: 14452/16000
amplify: 14456/16000
amplify: 14460/16000
amplify: 14464/16000
amplify: 14468/16000
amplify: 14472/16000
amplify: 14476/16000
amplify: 14480/16000
amplify: 14484/16000
amplify: 14488/16000
amplify: 14492/16000
amplify: 14496/16000
amplify: 14500/16000
amplify: 14504/16000
amplify: 14508/16000
amplify: 14512/16000
amplify: 14516/16000
amplify: 14520/16000
amplify: 14524/16000
amplify: 14528/16000
amplify: 14532/16000
amplify: 14536/16000
amplify: 14540/16000
amplify: 14544/16000
amplify: 14548/16000
amplify: 14552/16000
amplify: 14556/16000
amplify: 14560/16000
amplify: 14564/16000
amplify: 14568/16000
amplify: 14572/16000
amplify: 14576/16000
amplify: 14580/16000
amplify: 14584/16000
amplify: 14588/16000
amplify: 14592/16000
amplify: 14596/16000
amplify: 14600/16000
amplify: 14604/16000
amplify: 14608/16000
amplify: 14612/16000
amplify: 14616/16000
amplify: 14620/16000
amplify: 14624/16000
amplify: 14628/16000
amplify: 14632/16000
amplify: 14636/16000
amplify: 14640/16000
amplify: 14644/16000
amplify: 14648/16000
amplify: 14652/16000
amplify: 14656/16000
amplify: 14660/16000
amplify: 14664/16000
amplify: 14668/16000
amplify: 14672/16000
amplify: 14676/16000
amplify: 14680/16000
amplify: 14684/16000
amplify: 14688/16000
amplify: 14692/16000
amplify: 14696/16000
amplify: 14700/16000
amplify: 14704/16000
amplify: 14708/16000
amplify: 14712/16000
amplify: 14716/16000
amplify: 14720/16000
amplify: 14724/16000
amplify: 14728/16000
amplify: 14732/16000
amplify: 14736/16000
amplify: 14740/16000
amplify: 14744/16000
amplify: 14748/16000
amplify: 14752/16000
amplify: 14756/16000
amplify: 14760/16000
amplify: 14764/16000
amplify: 14768/16000
amplify: 14772/16000
amplify: 14776/16000
amplify: 14780/16000
amplify: 14784/16000
amplify: 14788/16000
amplify: 14792/16000
amplify: 14796/16000
amplify: 14800/16000
amplify: 14804/16000
amplify: 14808/16000
amplify: 14812/16000
amplify: 14816/16000
amplify: 14820/16000
amplify: 14824/16000
amplify: 14828/16000
amplify: 14832/16000
amplify: 14836/16000
amplify: 14840/16000
amplify: 14844/16000
amplify: 14848/16000
amplify: 14852/16000
amplify: 14856/16000
amplify: 14860/16000
amplify: 14864/16000
amplify: 14868/16000
amplify: 14872/16000
amplify: 14876/16000
amplify: 14880/16000
amplify: 14884/16000
amplify: 14888/16000
amplify: 14892/16000
amplify: 14896/16000
amplify: 14900/16000
amplify: 14904/16000
amplify: 14908/16000
amplify: 14912/16000
amplify: 14916/16000
amplify: 14920/16000
amplify: 14924/16000
amplify: 14928/16000
amplify: 14932/16000
amplify: 14936/16000
amplify: 14940/16000
amplify: 14944/16000
amplify: 14948/16000
amplify: 14952/16000
amplify: 14956/16000
amplify: 14960/16000
amplify: 14964/16000
amplify: 14968/16000
amplify: 14972/16000
amplify: 14976/16000
amplify: 14980/16000
amplify: 14984/16000
amplify: 14988/16000
amplify: 14992/16000
amplify: 14996/16000

amplify: 15000/16000
amplify: 15004/16000
amplify: 15008/16000
amplify: 15012/16000
amplify: 15016/16000
amplify: 15020/16000
amplify: 15024/16000
amplify: 15028/16000
amplify: 15032/16000
amplify: 15036/16000
amplify: 15040/16000
amplify: 15044/16000
amplify: 15048/16000
amplify: 15052/16000
amplify: 15056/16000
amplify: 15060/16000
amplify: 15064/16000
amplify: 15068/16000
amplify: 15072/16000
amplify: 15076/16000
amplify: 15080/16000
amplify: 15084/16000
amplify: 15088/16000
amplify: 15092/16000
amplify: 15096/16000
amplify: 15100/16000
amplify: 15104/16000
amplify: 15108/16000
amplify: 15112/16000
amplify: 15116/16000
amplify: 15120/16000
amplify: 15124/16000
amplify: 15128/16000
amplify: 15132/16000
amplify: 15136/16000
amplify: 15140/16000
amplify: 15144/16000
amplify: 15148/16000
amplify: 15152/16000
amplify: 15156/16000
amplify: 15160/16000
amplify: 15164/16000
amplify: 15168/16000
amplify: 15172/16000
amplify: 15176/16000
amplify: 15180/16000
amplify: 15184/16000
amplify: 15188/16000
amplify: 15192/16000
amplify: 15196/16000
amplify: 15200/16000
amplify: 15204/16000
amplify: 15208/16000
amplify: 15212/16000
amplify: 15216/16000
amplify: 15220/16000
amplify: 15224/16000
amplify: 15228/16000
amplify: 15232/16000
amplify: 15236/16000
amplify: 15240/16000
amplify: 15244/16000
amplify: 15248/16000
amplify: 15252/16000
amplify: 15256/16000
amplify: 15260/16000
amplify: 15264/16000
amplify: 15268/16000
amplify: 15272/16000
amplify: 15276/16000
amplify: 15280/16000
amplify: 15284/16000
amplify: 15288/16000
amplify: 15292/16000
amplify: 15296/16000
amplify: 15300/16000
amplify: 15304/16000
amplify: 15308/16000
amplify: 15312/16000
amplify: 15316/16000
amplify: 15320/16000
amplify: 15324/16000
amplify: 15328/16000
amplify: 15332/16000
amplify: 15336/16000
amplify: 15340/16000
amplify: 15344/16000
amplify: 15348/16000
amplify: 15352/16000
amplify: 15356/16000
amplify: 15360/16000
amplify: 15364/16000
amplify: 15368/16000
amplify: 15372/16000
amplify: 15376/16000
amplify: 15380/16000
amplify: 15384/16000
amplify: 15388/16000
amplify: 15392/16000
amplify: 15396/16000
amplify: 15400/16000
amplify: 15404/16000
amplify: 15408/16000
amplify: 15412/16000
amplify: 15416/16000
amplify: 15420/16000
amplify: 15424/16000
amplify: 15428/16000
amplify: 15432/16000
amplify: 15436/16000
amplify: 15440/16000
amplify: 15444/16000
amplify: 15448/16000
amplify: 15452/16000
amplify: 15456/16000
amplify: 15460/16000
amplify: 15464/16000
amplify: 15468/16000
amplify: 15472/16000
amplify: 15476/16000
amplify: 15480/16000
amplify: 15484/16000
amplify: 15488/16000
amplify: 15492/16000
amplify: 15496/16000
amplify: 15500/16000
amplify: 15504/16000
amplify: 15508/16000
amplify: 15512/16000
amplify: 15516/16000
amplify: 15520/16000
amplify: 15524/16000
amplify: 15528/16000
amplify: 15532/16000
amplify: 15536/16000
amplify: 15540/16000
amplify: 15544/16000
amplify: 15548/16000
amplify: 15552/16000
amplify: 15556/16000
amplify: 15560/16000
amplify: 15564/16000
amplify: 15568/16000
amplify: 15572/16000
amplify: 15576/16000
amplify: 15580/16000
amplify: 15584/16000
amplify: 15588/16000
amplify: 15592/16000
amplify: 15596/16000
amplify: 15600/16000
amplify: 15604/16000
amplify: 15608/16000
amplify: 15612/16000
amplify: 15616/16000
amplify: 15620/16000
amplify: 15624/16000
amplify: 15628/16000
amplify: 15632/16000
amplify: 15636/16000
amplify: 15640/16000
amplify: 15644/16000
amplify: 15648/16000
amplify: 15652/16000
amplify: 15656/16000
amplify: 15660/16000
amplify: 15664/16000
amplify: 15668/16000
amplify: 15672/16000
amplify: 15676/16000
amplify: 15680/16000
amplify: 15684/16000
amplify: 15688/16000
amplify: 15692/16000
amplify: 15696/16000
amplify: 15700/16000
amplify: 15704/16000
amplify: 15708/16000
amplify: 15712/16000
amplify: 15716/16000
amplify: 15720/16000
amplify: 15724/16000
amplify: 15728/16000
amplify: 15732/16000
amplify: 15736/16000
amplify: 15740/16000
amplify: 15744/16000
amplify: 15748/16000
amplify: 15752/16000
amplify: 15756/16000
amplify: 15760/16000
amplify: 15764/16000
amplify: 15768/16000
amplify: 15772/16000
amplify: 15776/16000
amplify: 15780/16000
amplify: 15784/16000
amplify: 15788/16000
amplify: 15792/16000
amplify: 15796/16000
amplify: 15800/16000
amplify: 15804/16000
amplify: 15808/16000
amplify: 15812/16000
amplify: 15816/16000
amplify: 15820/16000
amplify: 15824/16000
amplify: 15828/16000
amplify: 15832/16000
amplify: 15836/16000
amplify: 15840/16000
amplify: 15844/16000
amplify: 15848/16000
amplify: 15852/16000
amplify: 15856/16000
amplify: 15860/16000
amplify: 15864/16000
amplify: 15868/16000
amplify: 15872/16000
amplify: 15876/16000
amplify: 15880/16000
amplify: 15884/16000
amplify: 15888/16000
amplify: 15892/16000
amplify: 15896/16000
amplify: 15900/16000
amplify: 15904/16000
amplify: 15908/16000
amplify: 15912/16000
amplify: 15916/16000
amplify: 15920/16000
amplify: 15924/16000
amplify: 15928/16000
amplify: 15932/16000
amplify: 15936/16000
amplify: 15940/16000
amplify: 15944/16000
amplify: 15948/16000
amplify: 15952/16000
amplify: 15956/16000
amplify: 15960/16000
amplify: 15964/16000
amplify: 15968/16000
amplify: 15972/16000
amplify: 15976/16000
amplify: 15980/16000
amplify: 15984/16000
amplify: 15988/16000
amplify: 15992/16000
amplify: 15996/16000
amplify: 16000/16000
Causal validation per label-feature pair:

,label_word,feature_idx,label_specific_rank,stable_by_rule,causal_group,baseline_label_specific_pre_gap,retention_rate_top_20,min_over_baseline,feature_active_prompt_fraction,baseline_p_label_pct,ablated_p_label_pct,amplified_p_label_pct,ablation_decrease_pp,amplification_increase_pp,frac_prompts_ablation_decreases_p_label,frac_prompts_amplification_increases_p_label
40,Business,13946,1,True,multi-prefix stable,8.183893,1.000,0.983842,0.780,76.217061,75.867188,80.764648,0.349874,4.547580,0.510,0.895
41,Business,4300,2,True,multi-prefix stable,6.055885,1.000,0.903426,0.555,76.217061,76.138863,77.407745,0.078202,1.190679,0.280,0.715
42,Business,2992,3,True,multi-prefix stable,5.066381,1.000,0.776118,0.460,76.217061,75.904778,77.928139,0.312287,1.711070,0.335,0.890
43,Business,9059,4,True,multi-prefix stable,4.688516,1.000,0.926832,0.410,76.217061,76.259155,76.060669,-0.042093,-0.156395,0.195,0.640
44,Business,14526,5,True,multi-prefix stable,4.265446,1.000,0.845867,0.560,76.217061,76.305923,76.156441,-0.088859,-0.060626,0.195,0.535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8,World,12633,9,False,LFH-sensitive,3.880599,0.875,0.739120,0.355,85.489357,85.397644,86.482216,0.091709,0.992861,0.150,0.835
11,World,8745,12,False,LFH-sensitive,3.575313,0.500,0.706902,0.235,85.489357,85.507416,85.498848,-0.018064,0.009496,0.085,0.740
13,World,3607,14,False,LFH-sensitive,3.468281,0.500,0.576422,0.790,85.489357,85.377945,86.678101,0.111409,1.188751,0.485,0.855
16,World,5266,17,False,LFH-sensitive,3.168906,0.625,0.830005,0.030,85.489357,85.489197,86.403839,0.000155,0.914484,0.015,0.735
18,World,3117,19,False,LFH-sensitive,3.056589,0.625,0.873804,0.510,85.489357,85.482353,87.828819,0.007002,2.339468,0.290,0.845

Stable versus LFH-sensitive causal summary:

,causal_group,n_label_feature_pairs,mean_active_prompt_fraction,median_active_prompt_fraction,mean_ablation_decrease,mean_ablation_decrease_ci_low,mean_ablation_decrease_ci_high,mean_ablation_decrease_pp,mean_ablation_decrease_ci_low_pp,mean_ablation_decrease_ci_high_pp,mean_amplification_increase,mean_amplification_increase_ci_low,mean_amplification_increase_ci_high,mean_amplification_increase_pp,mean_amplification_increase_ci_low_pp,mean_amplification_increase_ci_high_pp
0,multi-prefix stable,61,0.447377,0.460,0.000411,0.000217,0.000626,0.041106,0.021720,0.062565,0.010587,0.007826,0.013508,1.058659,0.782643,1.350761
1,LFH-sensitive,19,0.240263,0.235,0.000049,-0.000225,0.000282,0.004858,-0.022478,0.028173,0.005863,0.001690,0.010320,0.586253,0.168962,1.032003

Per-label stable/sensitive causal summary:

,label_word,causal_group,n_label_feature_pairs,mean_ablation_decrease_pp,mean_amplification_increase_pp,mean_active_prompt_fraction
0,Business,LFH-sensitive,5,-0.036826,0.377450,0.193000
1,Business,multi-prefix stable,15,0.041801,1.709063,0.419333
2,Sports,LFH-sensitive,5,0.012737,0.628009,0.269000
3,Sports,multi-prefix stable,15,0.058889,0.814826,0.546333
4,Technology,LFH-sensitive,4,0.005136,0.166615,0.083750
5,Technology,multi-prefix stable,16,0.019521,0.750722,0.324688
6,World,LFH-sensitive,5,0.038442,1.089012,0.384000
7,World,multi-prefix stable,15,0.045651,0.980556,0.507333

====================================================================================================
Quick readout
====================================================================================================
Mean ablation decrease, stable group:      0.0411 percentage points
Mean ablation decrease, LFH-sensitive:     0.0049 percentage points
Mean amplification increase, stable group: 1.0587 percentage points
Mean amplification increase, sensitive:    0.5863 percentage points

Pattern matches the ideal validation: multi-prefix-stable features are more causally relevant on both tests.


## How to report the causal validation

The key table to include in the rebuttal is `causal_group_summary_df`:

- `mean_ablation_decrease_pp`: how much gold-label probability falls when the selected feature is removed when active.
- `mean_amplification_increase_pp`: how much gold-label probability rises when the selected feature direction is added with the current `CAUSAL_AMPLIFICATION_ALPHA`.

The intended coarse validation pattern is:

```text
multi-prefix stable features  >  LFH-sensitive features
```

for both ablation decrease and amplification increase. If the pattern holds, the rebuttal can state that the multi-prefix stability filter is not merely a descriptive diagnostic: it preferentially retains features with stronger causal support for the intended label, while filtering out single-prefix features that are more likely to be local-history-sensitive artifacts.


## How to report this experiment

A compact rebuttal/table can report:

- that features are selected by **label-specific preactivation gap**, not by overall activation magnitude;
- for each AGNews label, the top-20 single-prefix label-specific features;
- the fraction of those features that pass the multi-prefix stability rule;
- examples of high-ranked label-specific features that are unstable when only the final demonstration changes;
- Plotly heatmaps showing label-specific preactivation gaps across final-demo variants.

Suggested interpretation:

> We add an LFH-aware multi-prefix stability check for label-specific SAE features. For each fixed query, only the final demonstration is resampled. A feature selected from the original prefix is retained as robust only if its label-specific preactivation gap remains high across these alternative prefixes. Features whose apparent label-specificity collapses or moves sharply under final-demo variation are flagged as LFH-sensitive rather than directly interpreted as query-semantic features.

This is intended as a lightweight diagnostic, not a complete causal decomposition.